/**
 * Conformance: eslint-plugin-es-x (math-number) mounted in rslint via `plugins` must
 * report identically to ESLint v10. es-x rules are AST pattern matches over ES
 * version features / builtin APIs (no type info), so rslint reproduces ESLint
 * byte-for-byte. Representative triggers from the upstream test suite (v9.6.0).
 */
import { runConformanceSuite } from '../conformance.js';
import type { DiffCase } from '../harness.js';

const CASES: DiffCase[] = [
  { pkg: 'eslint-plugin-es-x', rule: 'no-atomics', code: 'Atomics' },
  {
    pkg: 'eslint-plugin-es-x',
    rule: 'no-atomics',
    code: 'function f() { Atomics }',
  },
  {
    pkg: 'eslint-plugin-es-x',
    rule: 'no-atomics-waitasync',
    code: 'Atomics.waitAsync',
  },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-acosh', code: 'Math.acosh' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-asinh', code: 'Math.asinh' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-atanh', code: 'Math.atanh' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-cbrt', code: 'Math.cbrt' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-clz32', code: 'Math.clz32' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-cosh', code: 'Math.cosh' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-expm1', code: 'Math.expm1' },
  {
    pkg: 'eslint-plugin-es-x',
    rule: 'no-math-f16round',
    code: 'Math.f16round',
  },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-fround', code: 'Math.fround' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-hypot', code: 'Math.hypot' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-imul', code: 'Math.imul' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-log1p', code: 'Math.log1p' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-log2', code: 'Math.log2' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-log10', code: 'Math.log10' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-sign', code: 'Math.sign' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-sinh', code: 'Math.sinh' },
  {
    pkg: 'eslint-plugin-es-x',
    rule: 'no-math-sumprecise',
    code: 'Math.sumPrecise',
  },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-tanh', code: 'Math.tanh' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-trunc', code: 'Math.trunc' },
  {
    pkg: 'eslint-plugin-es-x',
    rule: 'no-number-epsilon',
    code: 'Number.EPSILON',
  },
  {
    pkg: 'eslint-plugin-es-x',
    rule: 'no-number-epsilon',
    code: 'Number.EPSILON.toString?.()',
  },
  {
    pkg: 'eslint-plugin-es-x',
    rule: 'no-number-isfinite',
    code: 'Number.isFinite',
  },
  {
    pkg: 'eslint-plugin-es-x',
    rule: 'no-number-isinteger',
    code: 'Number.isInteger',
  },
  { pkg: 'eslint-plugin-es-x', rule: 'no-number-isnan', code: 'Number.isNaN' },
  {
    pkg: 'eslint-plugin-es-x',
    rule: 'no-number-issafeinteger',
    code: 'Number.isSafeInteger',
  },
  {
    pkg: 'eslint-plugin-es-x',
    rule: 'no-number-maxsafeinteger',
    code: 'Number.MAX_SAFE_INTEGER',
  },
  {
    pkg: 'eslint-plugin-es-x',
    rule: 'no-number-minsafeinteger',
    code: 'Number.MIN_SAFE_INTEGER',
  },
  {
    pkg: 'eslint-plugin-es-x',
    rule: 'no-number-parsefloat',
    code: 'Number.parseFloat',
  },
  {
    pkg: 'eslint-plugin-es-x',
    rule: 'no-number-parseint',
    code: 'Number.parseInt',
  },
  { pkg: 'eslint-plugin-es-x', rule: 'no-numeric-separators', code: '123_456' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-numeric-separators', code: '5_000' },
  {
    pkg: 'eslint-plugin-es-x',
    rule: 'no-numeric-separators',
    code: '1_234_56',
  },
  { pkg: 'eslint-plugin-es-x', rule: 'no-numeric-separators', code: '5.00_00' },
];

const CLEAN_CASES: DiffCase[] = [
  { pkg: 'eslint-plugin-es-x', rule: 'no-atomics', code: 'Array' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-atomics', code: 'Object' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-atomics-waitasync', code: 'Atomics' },
  {
    pkg: 'eslint-plugin-es-x',
    rule: 'no-atomics-waitasync',
    code: 'Atomics.wait',
  },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-acosh', code: 'Math' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-acosh', code: 'Math.min' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-asinh', code: 'Math' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-asinh', code: 'Math.min' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-atanh', code: 'Math' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-atanh', code: 'Math.min' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-cbrt', code: 'Math' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-cbrt', code: 'Math.min' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-clz32', code: 'Math' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-clz32', code: 'Math.min' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-cosh', code: 'Math' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-cosh', code: 'Math.min' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-expm1', code: 'Math' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-expm1', code: 'Math.min' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-f16round', code: 'Math' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-f16round', code: 'Math.min' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-fround', code: 'Math' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-fround', code: 'Math.min' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-hypot', code: 'Math' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-hypot', code: 'Math.min' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-imul', code: 'Math' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-imul', code: 'Math.min' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-log1p', code: 'Math' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-log1p', code: 'Math.min' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-log2', code: 'Math' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-log2', code: 'Math.min' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-log10', code: 'Math' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-log10', code: 'Math.min' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-sign', code: 'Math' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-sign', code: 'Math.min' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-sinh', code: 'Math' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-sinh', code: 'Math.min' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-sumprecise', code: 'Math' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-sumprecise', code: 'Math.abs' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-tanh', code: 'Math' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-tanh', code: 'Math.min' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-trunc', code: 'Math' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-math-trunc', code: 'Math.min' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-number-epsilon', code: 'Number' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-number-epsilon', code: 'Number.xyz' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-number-isfinite', code: 'Number' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-number-isfinite', code: 'Number.xyz' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-number-isinteger', code: 'Number' },
  {
    pkg: 'eslint-plugin-es-x',
    rule: 'no-number-isinteger',
    code: 'Number.xyz',
  },
  { pkg: 'eslint-plugin-es-x', rule: 'no-number-isnan', code: 'Number' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-number-isnan', code: 'Number.xyz' },
  {
    pkg: 'eslint-plugin-es-x',
    rule: 'no-number-issafeinteger',
    code: 'Number',
  },
  {
    pkg: 'eslint-plugin-es-x',
    rule: 'no-number-issafeinteger',
    code: 'Number.xyz',
  },
  {
    pkg: 'eslint-plugin-es-x',
    rule: 'no-number-maxsafeinteger',
    code: 'Number',
  },
  {
    pkg: 'eslint-plugin-es-x',
    rule: 'no-number-maxsafeinteger',
    code: 'Number.xyz',
  },
  {
    pkg: 'eslint-plugin-es-x',
    rule: 'no-number-minsafeinteger',
    code: 'Number',
  },
  {
    pkg: 'eslint-plugin-es-x',
    rule: 'no-number-minsafeinteger',
    code: 'Number.xyz',
  },
  { pkg: 'eslint-plugin-es-x', rule: 'no-number-parsefloat', code: 'Number' },
  {
    pkg: 'eslint-plugin-es-x',
    rule: 'no-number-parsefloat',
    code: 'Number.xyz',
  },
  { pkg: 'eslint-plugin-es-x', rule: 'no-number-parseint', code: 'Number' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-number-parseint', code: 'Number.xyz' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-numeric-separators', code: '123456' },
  { pkg: 'eslint-plugin-es-x', rule: 'no-numeric-separators', code: '-123' },
];

runConformanceSuite('eslint-plugin-es-x', CASES, CLEAN_CASES);
