// Ported from eslint-plugin-unicorn v77.0.0 tests and documentation.
// https://github.com/sindresorhus/eslint-plugin-unicorn/blob/v77.0.0/test/no-unnecessary-await.js
package no_unnecessary_await_test

import (
	"testing"

	"github.com/web-infra-dev/rslint/internal/plugins/unicorn/rules/no_unnecessary_await"
	"github.com/web-infra-dev/rslint/internal/rule_tester"
)

func TestNoUnnecessaryAwaitUpstream(t *testing.T) {
	rule_tester.RunRuleTester(moduleRoot(), "tsconfig.await.json", t, &no_unnecessary_await.NoUnnecessaryAwaitRule,
		[]rule_tester.ValidTestCase{
			// JavaScript
			{Code: "await {then}", FileName: "input.mjs"},
			{Code: "await a ? b : c", FileName: "input.mjs"},
			{Code: "await a || b", FileName: "input.mjs"},
			{Code: "await a && b", FileName: "input.mjs"},
			{Code: "await a ?? b", FileName: "input.mjs"},
			{Code: "await new Foo()", FileName: "input.mjs"},
			{Code: "await tagged``", FileName: "input.mjs"},
			{Code: "class A { async foo() { await this }}", FileName: "input.mjs"},
			{Code: "async function * foo() {await (yield bar);}", FileName: "input.mjs"},
			{Code: "await (1, Promise.resolve())", FileName: "input.mjs"},
			// TypeScript
			{Code: "async function f() { return await (a as Promise<number>); }", FileName: "input.ts"},
			{Code: "async function f() { return await (a!); }", FileName: "input.ts"},
			// Documentation
			{Code: "await promise;", FileName: "input.mjs"},
			{Code: "await Promise.allSettled([promise1, promise2]);", FileName: "input.mjs"},
		}, []rule_tester.InvalidTestCase{
			// JavaScript
			{Code: "await []", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 1, EndLine: 1, EndColumn: 6}},
				Output: []string{"[]"},
			},
			{Code: "await [Promise.resolve()]", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 1, EndLine: 1, EndColumn: 6}},
				Output: []string{"[Promise.resolve()]"},
			},
			{Code: "await (() => {})", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 1, EndLine: 1, EndColumn: 6}},
				Output: []string{"(() => {})"},
			},
			{Code: "await (() => Promise.resolve())", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 1, EndLine: 1, EndColumn: 6}},
				Output: []string{"(() => Promise.resolve())"},
			},
			{Code: "await (a === b)", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 1, EndLine: 1, EndColumn: 6}},
				Output: []string{"(a === b)"},
			},
			{Code: "await (a instanceof Promise)", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 1, EndLine: 1, EndColumn: 6}},
				Output: []string{"(a instanceof Promise)"},
			},
			{Code: "await (a > b)", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 1, EndLine: 1, EndColumn: 6}},
				Output: []string{"(a > b)"},
			},
			{Code: "await class {}", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 1, EndLine: 1, EndColumn: 6}},
			},
			{Code: "await class extends Promise {}", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 1, EndLine: 1, EndColumn: 6}},
			},
			{Code: "await function() {}", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 1, EndLine: 1, EndColumn: 6}},
			},
			{Code: "await function name() {}", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 1, EndLine: 1, EndColumn: 6}},
			},
			{Code: "await function() { return Promise.resolve() }", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 1, EndLine: 1, EndColumn: 6}},
			},
			{Code: "await (<></>)", FileName: "input.jsx",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 1, EndLine: 1, EndColumn: 6}},
				Output: []string{"(<></>)"},
			},
			{Code: "await (<a></a>)", FileName: "input.jsx",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 1, EndLine: 1, EndColumn: 6}},
				Output: []string{"(<a></a>)"},
			},
			{Code: "await 0", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 1, EndLine: 1, EndColumn: 6}},
				Output: []string{"0"},
			},
			{Code: "await 1", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 1, EndLine: 1, EndColumn: 6}},
				Output: []string{"1"},
			},
			{Code: "await \"\"", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 1, EndLine: 1, EndColumn: 6}},
				Output: []string{"\"\""},
			},
			{Code: "await \"string\"", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 1, EndLine: 1, EndColumn: 6}},
				Output: []string{"\"string\""},
			},
			{Code: "await true", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 1, EndLine: 1, EndColumn: 6}},
				Output: []string{"true"},
			},
			{Code: "await false", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 1, EndLine: 1, EndColumn: 6}},
				Output: []string{"false"},
			},
			{Code: "await null", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 1, EndLine: 1, EndColumn: 6}},
				Output: []string{"null"},
			},
			{Code: "await 0n", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 1, EndLine: 1, EndColumn: 6}},
				Output: []string{"0n"},
			},
			{Code: "await 1n", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 1, EndLine: 1, EndColumn: 6}},
				Output: []string{"1n"},
			},
			{Code: "await `${Promise.resolve()}`", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 1, EndLine: 1, EndColumn: 6}},
				Output: []string{"`${Promise.resolve()}`"},
			},
			// tsgo rejects this original JS input with TS8013 before rules run.
			// Keep the upstream expectation and exercise the same runtime AST in TS below.
			{Code: "await !Promise.resolve()", FileName: "input.mjs", Skip: true,
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 1, EndLine: 1, EndColumn: 6}},
				Output: []string{"!Promise.resolve()"},
			},
			{Code: "await !Promise.resolve()", FileName: "input.mts",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 1, EndLine: 1, EndColumn: 6}},
				Output: []string{"!Promise.resolve()"},
			},
			{Code: "await void Promise.resolve()", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 1, EndLine: 1, EndColumn: 6}},
				Output: []string{"void Promise.resolve()"},
			},
			{Code: "await +Promise.resolve()", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 1, EndLine: 1, EndColumn: 6}},
				Output: []string{"+Promise.resolve()"},
			},
			{Code: "await ~1", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 1, EndLine: 1, EndColumn: 6}},
				Output: []string{"~1"},
			},
			{Code: "await ++foo", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 1, EndLine: 1, EndColumn: 6}},
				Output: []string{"++foo"},
			},
			{Code: "await foo--", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 1, EndLine: 1, EndColumn: 6}},
				Output: []string{"foo--"},
			},
			{Code: "await (Promise.resolve(), 1)", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 1, EndLine: 1, EndColumn: 6}},
				Output: []string{"(Promise.resolve(), 1)"},
			},
			{Code: "async function foo() {\n\treturn await\n\t\t// comment\n\t\t1;\n}", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 2, Column: 9, EndLine: 2, EndColumn: 14}},
				Output: []string{"async function foo() {\n\treturn ( // comment\n\t\t1);\n}"},
			},
			{Code: "async function foo() {\n\treturn await\n\t\t// comment\n\t\t1\n}", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 2, Column: 9, EndLine: 2, EndColumn: 14}},
				Output: []string{"async function foo() {\n\treturn ( // comment\n\t\t1)\n}"},
			},
			{Code: "async function foo() {\n\treturn( await\n\t\t// comment\n\t\t1);\n}", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 2, Column: 10, EndLine: 2, EndColumn: 15}},
				Output: []string{"async function foo() {\n\treturn( // comment\n\t\t1);\n}"},
			},
			{Code: "foo()\nawait []", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 2, Column: 1, EndLine: 2, EndColumn: 6}},
				Output: []string{"foo()\n;[]"},
			},
			{Code: "foo()\nawait +1", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 2, Column: 1, EndLine: 2, EndColumn: 6}},
				Output: []string{"foo()\n;+1"},
			},
			{Code: "async function foo() {\n\treturn await\n\t\t// comment\n\t\t[];\n}", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 2, Column: 9, EndLine: 2, EndColumn: 14}},
				Output: []string{"async function foo() {\n\treturn ( // comment\n\t\t[]);\n}"},
			},
			{Code: "async function foo() {\n\tthrow await\n\t\t// comment\n\t\t1;\n}", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 2, Column: 8, EndLine: 2, EndColumn: 13}},
				Output: []string{"async function foo() {\n\tthrow ( // comment\n\t\t1);\n}"},
			},
			{Code: "console.log(\n\tawait\n\t\t// comment\n\t\t[]\n);", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 2, Column: 2, EndLine: 2, EndColumn: 7}},
			},
			{Code: "async function foo() {+await +1}", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 24, EndLine: 1, EndColumn: 29}},
			},
			{Code: "async function foo() {-await-1}", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 24, EndLine: 1, EndColumn: 29}},
			},
			{Code: "async function foo() {+await -1}", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 24, EndLine: 1, EndColumn: 29}},
			},
			{Code: "async function foo() {+await ++bar}", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 24, EndLine: 1, EndColumn: 29}},
			},
			{Code: "async function foo() {-await --bar}", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 24, EndLine: 1, EndColumn: 29}},
			},
			{Code: "async function foo() {const a = +await ++b;}", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 34, EndLine: 1, EndColumn: 39}},
			},
			{Code: "async function foo() {+await --bar}", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 24, EndLine: 1, EndColumn: 29}},
			},
			{Code: "async function foo() {-await ++bar}", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 24, EndLine: 1, EndColumn: 29}},
			},
			{Code: "async function foo() {+await bar++}", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 24, EndLine: 1, EndColumn: 29}},
			},
			{Code: "async function foo() {~await ~1}", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 24, EndLine: 1, EndColumn: 29}},
			},
			// TypeScript
			{Code: "async function f() { return await (1 as number); }", FileName: "input.ts",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 29, EndLine: 1, EndColumn: 34}},
				Output: []string{"async function f() { return (1 as number); }"},
			},
			{Code: "async function f() { return await ([1, 2]!); }", FileName: "input.ts",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 29, EndLine: 1, EndColumn: 34}},
				Output: []string{"async function f() { return ([1, 2]!); }"},
			},
			{Code: "async function f() { return await ([1, 2] as const); }", FileName: "input.ts",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 29, EndLine: 1, EndColumn: 34}},
				Output: []string{"async function f() { return ([1, 2] as const); }"},
			},
			{Code: "async function f() { return await ([1, 2] satisfies number[]); }", FileName: "input.ts",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 29, EndLine: 1, EndColumn: 34}},
				Output: []string{"async function f() { return ([1, 2] satisfies number[]); }"},
			},
			// Microtask ordering
			{Code: "async function f() { log(\"s\"); await 1; log(\"e\"); }", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 32, EndLine: 1, EndColumn: 37}},
			},
			{Code: "async function f() { await 1; log(\"e\"); }", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 22, EndLine: 1, EndColumn: 27}},
			},
			{Code: "async function f() { if (q) { run(); } await 1; }", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 40, EndLine: 1, EndColumn: 45}},
				Output: []string{"async function f() { if (q) { run(); } 1; }"},
			},
			{Code: "async function f() { log(\"s\"); await 1; }", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 32, EndLine: 1, EndColumn: 37}},
				Output: []string{"async function f() { log(\"s\"); 1; }"},
			},
			{Code: "async function f() { await 1; }", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 22, EndLine: 1, EndColumn: 27}},
				Output: []string{"async function f() { 1; }"},
			},
			{Code: "async function f() { return await 1; }", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 29, EndLine: 1, EndColumn: 34}},
				Output: []string{"async function f() { return 1; }"},
			},
			{Code: "async function f() { const x = await 1; }", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 32, EndLine: 1, EndColumn: 37}},
				Output: []string{"async function f() { const x = 1; }"},
			},
			{Code: "async function f() { if (q) { await 1; } }", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 31, EndLine: 1, EndColumn: 36}},
				Output: []string{"async function f() { if (q) { 1; } }"},
			},
			{Code: "const f = async () => { await 1; };", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 25, EndLine: 1, EndColumn: 30}},
				Output: []string{"const f = async () => { 1; };"},
			},
			{Code: "async function f() { if (q) { await 1; log(\"e\"); } }", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 31, EndLine: 1, EndColumn: 36}},
			},
			{Code: "async function f() { log(await 1); }", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 26, EndLine: 1, EndColumn: 31}},
			},
			{Code: "async function f() { for (const x of xs) { await 1; } }", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 44, EndLine: 1, EndColumn: 49}},
			},
			{Code: "async function f() { try { await 1; } finally { log(\"e\"); } }", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 28, EndLine: 1, EndColumn: 33}},
			},
			{Code: "async function outer() { return async () => (await 1, log(\"e\")); }", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 46, EndLine: 1, EndColumn: 51}},
			},
			{Code: "async function outer() { const f = async () => await 1; run(); }", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 48, EndLine: 1, EndColumn: 53}},
				Output: []string{"async function outer() { const f = async () => 1; run(); }"},
			},
			{Code: "Promise.resolve().then(() => log(\"a\")); await 1; log(\"b\");", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 41, EndLine: 1, EndColumn: 46}},
			},
			{Code: "run(); await 1;", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 8, EndLine: 1, EndColumn: 13}},
				Output: []string{"run(); 1;"},
			},
			// Documentation
			{Code: "await await promise;", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 1, EndLine: 1, EndColumn: 6}},
				Output: []string{"await promise;"},
			},
			{Code: "await [promise1, promise2];", FileName: "input.mjs",
				Errors: []rule_tester.InvalidTestCaseError{{MessageId: "no-unnecessary-await", Message: "Do not `await` non-promise value.", Line: 1, Column: 1, EndLine: 1, EndColumn: 6}},
				Output: []string{"[promise1, promise2];"},
			},
		})
}
