// Code generated by tools/gen_shims. DO NOT EDIT.

package stringutil

import "github.com/microsoft/typescript-go/internal/stringutil"
import _ "unsafe"

//go:linkname AddUTF8ByteOrderMark github.com/microsoft/typescript-go/internal/stringutil.AddUTF8ByteOrderMark
func AddUTF8ByteOrderMark(text string) string

//go:linkname CodePointToSurrogatePair github.com/microsoft/typescript-go/internal/stringutil.CodePointToSurrogatePair
func CodePointToSurrogatePair(ch rune) (high rune, low rune)

//go:linkname CombineSurrogatePairs github.com/microsoft/typescript-go/internal/stringutil.CombineSurrogatePairs
func CombineSurrogatePairs(s string) string

//go:linkname CompareStringsCaseInsensitive github.com/microsoft/typescript-go/internal/stringutil.CompareStringsCaseInsensitive
func CompareStringsCaseInsensitive(a string, b string) stringutil.Comparison

//go:linkname CompareStringsCaseInsensitiveEslintCompatible github.com/microsoft/typescript-go/internal/stringutil.CompareStringsCaseInsensitiveEslintCompatible
func CompareStringsCaseInsensitiveEslintCompatible(a string, b string) stringutil.Comparison

//go:linkname CompareStringsCaseInsensitiveThenSensitive github.com/microsoft/typescript-go/internal/stringutil.CompareStringsCaseInsensitiveThenSensitive
func CompareStringsCaseInsensitiveThenSensitive(a string, b string) stringutil.Comparison

//go:linkname CompareStringsCaseSensitive github.com/microsoft/typescript-go/internal/stringutil.CompareStringsCaseSensitive
func CompareStringsCaseSensitive(a string, b string) stringutil.Comparison

type Comparison = stringutil.Comparison

const ComparisonEqual = stringutil.ComparisonEqual
const ComparisonGreaterThan = stringutil.ComparisonGreaterThan
const ComparisonLessThan = stringutil.ComparisonLessThan

//go:linkname ContainsNonASCII github.com/microsoft/typescript-go/internal/stringutil.ContainsNonASCII
func ContainsNonASCII(s string) bool

//go:linkname DecodeJSStringRune github.com/microsoft/typescript-go/internal/stringutil.DecodeJSStringRune
func DecodeJSStringRune(s string) (rune, int)

//go:linkname EncodeJSStringRune github.com/microsoft/typescript-go/internal/stringutil.EncodeJSStringRune
func EncodeJSStringRune(ch rune) string

//go:linkname EncodeURI github.com/microsoft/typescript-go/internal/stringutil.EncodeURI
func EncodeURI(s string) string

//go:linkname EquateStringCaseInsensitive github.com/microsoft/typescript-go/internal/stringutil.EquateStringCaseInsensitive
func EquateStringCaseInsensitive(a string, b string) bool

//go:linkname EquateStringCaseSensitive github.com/microsoft/typescript-go/internal/stringutil.EquateStringCaseSensitive
func EquateStringCaseSensitive(a string, b string) bool

//go:linkname GetStringComparer github.com/microsoft/typescript-go/internal/stringutil.GetStringComparer
func GetStringComparer(ignoreCase bool) func(a string, b string) stringutil.Comparison

//go:linkname GetStringEqualityComparer github.com/microsoft/typescript-go/internal/stringutil.GetStringEqualityComparer
func GetStringEqualityComparer(ignoreCase bool) func(a string, b string) bool

//go:linkname GuessIndentation github.com/microsoft/typescript-go/internal/stringutil.GuessIndentation
func GuessIndentation(lines []string) int

//go:linkname HasPrefix github.com/microsoft/typescript-go/internal/stringutil.HasPrefix
func HasPrefix(s string, prefix string, caseSensitive bool) bool

//go:linkname HasPrefixAndSuffixWithoutOverlap github.com/microsoft/typescript-go/internal/stringutil.HasPrefixAndSuffixWithoutOverlap
func HasPrefixAndSuffixWithoutOverlap(s string, prefix string, suffix string, caseSensitive bool) bool

//go:linkname HasSuffix github.com/microsoft/typescript-go/internal/stringutil.HasSuffix
func HasSuffix(s string, suffix string, caseSensitive bool) bool

//go:linkname IsASCIILetter github.com/microsoft/typescript-go/internal/stringutil.IsASCIILetter
func IsASCIILetter(ch rune) bool

//go:linkname IsDigit github.com/microsoft/typescript-go/internal/stringutil.IsDigit
func IsDigit(ch rune) bool

//go:linkname IsHexDigit github.com/microsoft/typescript-go/internal/stringutil.IsHexDigit
func IsHexDigit(ch rune) bool

//go:linkname IsHighSurrogate github.com/microsoft/typescript-go/internal/stringutil.IsHighSurrogate
func IsHighSurrogate(ch rune) bool

//go:linkname IsLineBreak github.com/microsoft/typescript-go/internal/stringutil.IsLineBreak
func IsLineBreak(ch rune) bool

//go:linkname IsLowSurrogate github.com/microsoft/typescript-go/internal/stringutil.IsLowSurrogate
func IsLowSurrogate(ch rune) bool

//go:linkname IsOctalDigit github.com/microsoft/typescript-go/internal/stringutil.IsOctalDigit
func IsOctalDigit(ch rune) bool

//go:linkname IsSurrogate github.com/microsoft/typescript-go/internal/stringutil.IsSurrogate
func IsSurrogate(ch rune) bool

//go:linkname IsUnicodeIdentifierPart github.com/microsoft/typescript-go/internal/stringutil.IsUnicodeIdentifierPart
func IsUnicodeIdentifierPart(ch rune) bool

//go:linkname IsUnicodeIdentifierStart github.com/microsoft/typescript-go/internal/stringutil.IsUnicodeIdentifierStart
func IsUnicodeIdentifierStart(ch rune) bool

//go:linkname IsWhiteSpaceLike github.com/microsoft/typescript-go/internal/stringutil.IsWhiteSpaceLike
func IsWhiteSpaceLike(ch rune) bool

//go:linkname IsWhiteSpaceSingleLine github.com/microsoft/typescript-go/internal/stringutil.IsWhiteSpaceSingleLine
func IsWhiteSpaceSingleLine(ch rune) bool

//go:linkname LowerFirstChar github.com/microsoft/typescript-go/internal/stringutil.LowerFirstChar
func LowerFirstChar(str string) string

//go:linkname RemoveByteOrderMark github.com/microsoft/typescript-go/internal/stringutil.RemoveByteOrderMark
func RemoveByteOrderMark(text string) string

//go:linkname SplitLines github.com/microsoft/typescript-go/internal/stringutil.SplitLines
func SplitLines(text string) []string

//go:linkname StripQuotes github.com/microsoft/typescript-go/internal/stringutil.StripQuotes
func StripQuotes(name string) string

const SurrogateLowStart = stringutil.SurrogateLowStart

//go:linkname SurrogatePairToCodePoint github.com/microsoft/typescript-go/internal/stringutil.SurrogatePairToCodePoint
func SurrogatePairToCodePoint(high rune, low rune) rune

//go:linkname ToLowerJS github.com/microsoft/typescript-go/internal/stringutil.ToLowerJS
func ToLowerJS(str string) string

//go:linkname ToUpperJS github.com/microsoft/typescript-go/internal/stringutil.ToUpperJS
func ToUpperJS(str string) string

//go:linkname TruncateByRunes github.com/microsoft/typescript-go/internal/stringutil.TruncateByRunes
func TruncateByRunes(str string, maxLength int) string

//go:linkname UnquoteString github.com/microsoft/typescript-go/internal/stringutil.UnquoteString
func UnquoteString(str string) string
