package global_require_test

import (
	"testing"

	"github.com/web-infra-dev/rslint/internal/plugins/node/rules/global_require"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/fixtures"
	"github.com/web-infra-dev/rslint/internal/rule"
	"github.com/web-infra-dev/rslint/internal/rule_tester"
)

func TestGlobalRequireExtras(t *testing.T) {
	rule_tester.RunRuleTester(fixtures.GetRootDir(), "tsconfig.json", t, &global_require.GlobalRequireRule,
		[]rule_tester.ValidTestCase{
			// Only direct require calls are checked. Top-level assignments, calls and members are allowed.
			{Code: "function f() { loader.require('x'); loader['require']('x'); require.resolve('x'); new require('x'); require`x`; }",
				FileName:        "input.cjs",
				LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"},
				TSConfig:        "tsconfig.allowJs.json"},
			{Code: "const { readFile } = require('fs'); use(require('fs')); target[require('key')] = require('value');",
				FileName:        "input.cjs",
				LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"},
				TSConfig:        "tsconfig.allowJs.json"},
			{Code: "value += require('x'); value ||= require('y'); value ??= require('z');",
				FileName:        "input.cjs",
				LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"},
				TSConfig:        "tsconfig.allowJs.json"},
			{Code: "const x = (require)('x'); ((require('y'))).load(); require('a') ? require('b') : require('c');",
				FileName:        "input.cjs",
				LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"},
				TSConfig:        "tsconfig.allowJs.json"},
			{Code: "/** @type {any} */ (require('x')); (/** @type {any} */ (require))('y');",
				FileName:        "input.cjs",
				LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"},
				TSConfig:        "tsconfig.allowJs.json"},
			// Bindings shadow require; declarations in unrelated scopes do not.
			{Code: "const require = loader; function f() { require('x'); }",
				FileName:        "input.cjs",
				LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"},
				TSConfig:        "tsconfig.allowJs.json"},
			{Code: "function f() { require('x'); var require = loader; }",
				FileName:        "input.cjs",
				LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"},
				TSConfig:        "tsconfig.allowJs.json"},
			{Code: "function f() { require('x'); function require() {} }",
				FileName:        "input.cjs",
				LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"},
				TSConfig:        "tsconfig.allowJs.json"},
			{Code: "if (ok) { require('x'); let require = loader; }",
				FileName:        "input.cjs",
				LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"},
				TSConfig:        "tsconfig.allowJs.json"},
			{Code: "function f({ require }) { (() => require('x'))(); }",
				FileName:        "input.cjs",
				LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"},
				TSConfig:        "tsconfig.allowJs.json"},
			{Code: "function f(require, x = require('x')) { return require('y'); }",
				FileName:        "input.cjs",
				LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"},
				TSConfig:        "tsconfig.allowJs.json"},
			{Code: "try {} catch (require) { require('x'); }",
				FileName:        "input.cjs",
				LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"},
				TSConfig:        "tsconfig.allowJs.json"},
			{Code: "const f = function require() { return require('x'); }; const C = class require { static x = require('x'); };",
				FileName:        "input.cjs",
				LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"},
				TSConfig:        "tsconfig.allowJs.json"},
			{Code: "function f() { const require = loader; } require('x');",
				FileName:        "input.cjs",
				LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"},
				TSConfig:        "tsconfig.allowJs.json"},
			{Code: "import require from 'loader'; function f() { require('x'); }",
				FileName:        "input.mjs",
				LanguageOptions: rule.LanguageOptions{SourceType: "module"},
				TSConfig:        "tsconfig.allowJs.json"},
			{Code: "import type require from 'loader'; function f() { require('x'); }",
				FileName:        "input.ts",
				LanguageOptions: rule.LanguageOptions{SourceType: "module"}},
			{Code: "declare const require: any; function f() { require('x'); }",
				FileName:        "input.ts",
				LanguageOptions: rule.LanguageOptions{SourceType: "module"}},
			{Code: "namespace require { export const load = 1; } function f() { require('x'); }",
				FileName:        "input.ts",
				LanguageOptions: rule.LanguageOptions{SourceType: "module"}},
			// Authored TypeScript wrappers stay visible; JSX containers are not allowed parents.
			{Code: "function f() { (require as any)('x'); require!('y'); }",
				FileName:        "input.ts",
				LanguageOptions: rule.LanguageOptions{SourceType: "module"}},
		},
		[]rule_tester.InvalidTestCase{
			// A disallowed ancestor is enough to report, even in top-level expressions.
			{Code: "const values = [require('x')]; const object = { value: require('y') };",
				FileName:        "input.cjs",
				LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"},
				TSConfig:        "tsconfig.allowJs.json",
				Errors:          []rule_tester.InvalidTestCaseError{unexpectedAt(1, 17, 1, 29), unexpectedAt(1, 56, 1, 68)}},
			{Code: "const x = enabled && require('x'); const y = cached ?? require('y'); require('z') + 1; (0, require('w'));",
				FileName:        "input.cjs",
				LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"},
				TSConfig:        "tsconfig.allowJs.json",
				Errors:          []rule_tester.InvalidTestCaseError{unexpectedAt(1, 22, 1, 34), unexpectedAt(1, 56, 1, 68), unexpectedAt(1, 70, 1, 82), unexpectedAt(1, 92, 1, 104)}},
			{Code: "void require('x'); new Loader(require('y')); use(...require('z'));",
				FileName:        "input.cjs",
				LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"},
				TSConfig:        "tsconfig.allowJs.json",
				Errors:          []rule_tester.InvalidTestCaseError{unexpectedAt(1, 6, 1, 18), unexpectedAt(1, 31, 1, 43), unexpectedAt(1, 53, 1, 65)}},
			{Code: "const text = `module: ${require('x')}`; require('tag')`text`;",
				FileName:        "input.cjs",
				LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"},
				TSConfig:        "tsconfig.allowJs.json",
				Errors:          []rule_tester.InvalidTestCaseError{unexpectedAt(1, 25, 1, 37), unexpectedAt(1, 41, 1, 55)}},
			{Code: "const { x = require('x') } = options; [value = require('y')] = values;",
				FileName:        "input.cjs",
				LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"},
				TSConfig:        "tsconfig.allowJs.json",
				Errors:          []rule_tester.InvalidTestCaseError{unexpectedAt(1, 13, 1, 25), unexpectedAt(1, 48, 1, 60)}},
			{Code: "export const x = require('x'); export default require('y');",
				FileName:        "input.mjs",
				LanguageOptions: rule.LanguageOptions{SourceType: "module"},
				TSConfig:        "tsconfig.allowJs.json",
				Errors:          []rule_tester.InvalidTestCaseError{unexpectedAt(1, 18, 1, 30), unexpectedAt(1, 47, 1, 59)}},
			{Code: "label: require('x'); if (ready) require('y'); while (ready) require('z');",
				FileName:        "input.cjs",
				LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"},
				TSConfig:        "tsconfig.allowJs.json",
				Errors:          []rule_tester.InvalidTestCaseError{unexpectedAt(1, 8, 1, 20), unexpectedAt(1, 33, 1, 45), unexpectedAt(1, 61, 1, 73)}},
			{Code: "do require('x'); while (ready); for (const x of require('y')) {} for (; require('z');) { break; }",
				FileName:        "input.cjs",
				LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"},
				TSConfig:        "tsconfig.allowJs.json",
				Errors:          []rule_tester.InvalidTestCaseError{unexpectedAt(1, 4, 1, 16), unexpectedAt(1, 49, 1, 61), unexpectedAt(1, 73, 1, 85)}},
			{Code: "class C extends require('base') { [require('key')]() {} field = require('field'); static { require('static'); } }",
				FileName:        "input.cjs",
				LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"},
				TSConfig:        "tsconfig.allowJs.json",
				Errors:          []rule_tester.InvalidTestCaseError{unexpectedAt(1, 17, 1, 32), unexpectedAt(1, 36, 1, 50), unexpectedAt(1, 65, 1, 81), unexpectedAt(1, 92, 1, 109)}},
			{Code: "const object = { [require('key')]: true, load() { return require('value'); } };",
				FileName:        "input.cjs",
				LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"},
				TSConfig:        "tsconfig.allowJs.json",
				Errors:          []rule_tester.InvalidTestCaseError{unexpectedAt(1, 19, 1, 33), unexpectedAt(1, 58, 1, 74)}},
			{Code: "async function f() { return await require('x'); } function* g() { yield require('y'); }",
				FileName:        "input.cjs",
				LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"},
				TSConfig:        "tsconfig.allowJs.json",
				Errors:          []rule_tester.InvalidTestCaseError{unexpectedAt(1, 35, 1, 47), unexpectedAt(1, 73, 1, 85)}},
			// Optional chains and source wrappers have different ESTree representations.
			{Code: "require?.('x'); require('y')?.load(); use?.(require('z'));",
				FileName:        "input.cjs",
				LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"},
				TSConfig:        "tsconfig.allowJs.json",
				Errors:          []rule_tester.InvalidTestCaseError{unexpectedAt(1, 1, 1, 15), unexpectedAt(1, 17, 1, 29), unexpectedAt(1, 45, 1, 57)}},
			{Code: "(require?.('x'))('y'); (require('z')?.load)();",
				FileName:        "input.cjs",
				LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"},
				TSConfig:        "tsconfig.allowJs.json",
				Errors:          []rule_tester.InvalidTestCaseError{unexpectedAt(1, 2, 1, 16), unexpectedAt(1, 25, 1, 37)}},
			{Code: "function f() { (require)('x'); ((require))('y'); }",
				FileName:        "input.cjs",
				LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"},
				TSConfig:        "tsconfig.allowJs.json",
				Errors:          []rule_tester.InvalidTestCaseError{unexpectedAt(1, 16, 1, 30), unexpectedAt(1, 32, 1, 48)}},
			{Code: "function f() { (/** @type {any} */ (require))('x'); }",
				FileName:        "input.cjs",
				LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"},
				TSConfig:        "tsconfig.allowJs.json",
				Errors:          []rule_tester.InvalidTestCaseError{unexpectedAt(1, 16, 1, 51)}},
			{Code: "function f() { /** @type {any} */ (require('x')); }",
				FileName:        "input.cjs",
				LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"},
				TSConfig:        "tsconfig.allowJs.json",
				Errors:          []rule_tester.InvalidTestCaseError{unexpectedAt(1, 36, 1, 48)}},
			// Only local definitions shadow require; globals and JSDoc types do not.
			{Code: "function f() { require(); require(...modules); }",
				FileName:        "input.cjs",
				LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"},
				TSConfig:        "tsconfig.allowJs.json",
				Errors:          []rule_tester.InvalidTestCaseError{unexpectedAt(1, 16, 1, 25), unexpectedAt(1, 27, 1, 46)}},
			{Code: "function f(x = require('x')) { var require = loader; }",
				FileName:        "input.cjs",
				LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"},
				TSConfig:        "tsconfig.allowJs.json",
				Errors:          []rule_tester.InvalidTestCaseError{unexpectedAt(1, 16, 1, 28)}},
			{Code: "function f() { var require = loader; } if (ready) require('x');",
				FileName:        "input.cjs",
				LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"},
				TSConfig:        "tsconfig.allowJs.json",
				Errors:          []rule_tester.InvalidTestCaseError{unexpectedAt(1, 51, 1, 63)}},
			{Code: "if (ready) require('x');",
				FileName:        "input.cjs",
				LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"},
				TSConfig:        "tsconfig.allowJs.json",
				Globals:         map[string]any{"require": "off"},
				Errors:          []rule_tester.InvalidTestCaseError{unexpectedAt(1, 12, 1, 24)}},
			{Code: "/** @typedef {Function} require */ function f() { require('x'); }",
				FileName:        "input.cjs",
				LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"},
				TSConfig:        "tsconfig.allowJs.json",
				Errors:          []rule_tester.InvalidTestCaseError{unexpectedAt(1, 51, 1, 63)}},
			{Code: `"😀"; if (ready) require(
  '中文',
);`,
				FileName:        "input.cjs",
				LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"},
				TSConfig:        "tsconfig.allowJs.json",
				Errors:          []rule_tester.InvalidTestCaseError{unexpectedAt(1, 18, 3, 2)}},
			{Code: "const x = require('x') as unknown; const y = require('y')!; const z = require('z') satisfies unknown;",
				FileName:        "input.ts",
				LanguageOptions: rule.LanguageOptions{SourceType: "module"},
				Errors:          []rule_tester.InvalidTestCaseError{unexpectedAt(1, 11, 1, 23), unexpectedAt(1, 46, 1, 58), unexpectedAt(1, 71, 1, 83)}},
			{Code: "function f() { require<string>('x'); }",
				FileName:        "input.ts",
				LanguageOptions: rule.LanguageOptions{SourceType: "module"},
				Errors:          []rule_tester.InvalidTestCaseError{unexpectedAt(1, 16, 1, 36)}},
			{Code: "type require = unknown; interface Other {} function f() { require('x'); }",
				FileName:        "input.ts",
				LanguageOptions: rule.LanguageOptions{SourceType: "module"},
				Errors:          []rule_tester.InvalidTestCaseError{unexpectedAt(1, 59, 1, 71)}},
			{Code: "const element = <View value={require('x')}>{require('y')}</View>;",
				FileName:        "input.tsx",
				LanguageOptions: rule.LanguageOptions{SourceType: "module"},
				Tsx:             true,
				Errors:          []rule_tester.InvalidTestCaseError{unexpectedAt(1, 30, 1, 42), unexpectedAt(1, 45, 1, 57)}},
		},
	)
}

func TestGlobalRequireAdditionalASTBoundaries(t *testing.T) {
	rule_tester.RunRuleTester(fixtures.GetRootDir(), "tsconfig.json", t, &global_require.GlobalRequireRule,
		[]rule_tester.ValidTestCase{
			// An import argument does not change the ancestors of the outer require call.
			{Code: "require('x').load(import('y'));",
				FileName:        "input.mjs",
				LanguageOptions: rule.LanguageOptions{SourceType: "module"},
				TSConfig:        "tsconfig.allowJs.json"},
			// Script-level declarations and function-expression names also shadow require.
			{Code: "var require = loader; function f() { require('x'); }",
				FileName:        "input.cjs",
				LanguageOptions: rule.LanguageOptions{SourceType: "script"},
				TSConfig:        "tsconfig.allowJs.json"},
			{Code: "const f = function require(value = require('x')) {};",
				FileName:        "input.cjs",
				LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"},
				TSConfig:        "tsconfig.allowJs.json"},
			{Code: "const C = class require extends require('x') {};",
				FileName:        "input.cjs",
				LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"},
				TSConfig:        "tsconfig.allowJs.json"},
			// TypeScript namespaces are value-capable even without a runtime member.
			{Code: "namespace require {} function f() { require('x'); }",
				FileName:        "input.ts",
				LanguageOptions: rule.LanguageOptions{SourceType: "module"}},
			{Code: "declare namespace require {} function f() { require('x'); }",
				FileName:        "input.ts",
				LanguageOptions: rule.LanguageOptions{SourceType: "module"}},
			// Import aliases shadow require, including import-equals declarations.
			{Code: "import require = load; function f() { require('x'); }",
				FileName:        "input.ts",
				LanguageOptions: rule.LanguageOptions{SourceType: "module"}},
			{Code: "import require = require('loader'); function f() { require('x'); }",
				FileName:        "input.ts",
				LanguageOptions: rule.LanguageOptions{SourceType: "module"}},
			// Import-equals syntax does not contain an ordinary require call.
			{Code: "import x = require('x');",
				FileName:        "input.ts",
				LanguageOptions: rule.LanguageOptions{SourceType: "module"}},
			{Code: "enum E { require = 0, X = require('x') }",
				FileName:        "input.ts",
				LanguageOptions: rule.LanguageOptions{SourceType: "module"}},
			// RuleTester registers the rule under the name "test".
			{Code: `// rslint-disable-next-line test
function f() { require('x'); }`,
				FileName:        "input.cjs",
				LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"},
				TSConfig:        "tsconfig.allowJs.json"},
		},
		[]rule_tester.InvalidTestCase{
			// Dynamic import is not an ordinary call ancestor.
			{Code: "import(require('x'));",
				FileName:        "input.mjs",
				LanguageOptions: rule.LanguageOptions{SourceType: "module"},
				TSConfig:        "tsconfig.allowJs.json",
				Errors:          []rule_tester.InvalidTestCaseError{unexpectedAt(1, 8, 1, 20)}},
			// Identifiers use their decoded spelling, while ranges retain authored escapes.
			{Code: "function f() { r\\u0065quire('x'); }",
				FileName:        "input.cjs",
				LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"},
				TSConfig:        "tsconfig.allowJs.json",
				Errors:          []rule_tester.InvalidTestCaseError{unexpectedAt(1, 16, 1, 33)}},
			// Computed binding keys are evaluated, but patterns are not allowed ancestors.
			{Code: "const { [require('key')]: value } = source;",
				FileName:        "input.cjs",
				LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"},
				TSConfig:        "tsconfig.allowJs.json",
				Errors:          []rule_tester.InvalidTestCaseError{unexpectedAt(1, 10, 1, 24)}},
			// Block function declarations do not shadow a require outside the block.
			{Code: "if (ready) { function require() {} } require('x'); if (ready) require('x');",
				FileName:        "input.cjs",
				LanguageOptions: rule.LanguageOptions{SourceType: "script"},
				TSConfig:        "tsconfig.allowJs.json",
				Errors:          []rule_tester.InvalidTestCaseError{unexpectedAt(1, 63, 1, 75)}},
			// Assigning a global is not a local declaration.
			{Code: "function f() { require('x'); } require = loader;",
				FileName:        "input.cjs",
				LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"},
				TSConfig:        "tsconfig.allowJs.json",
				Errors:          []rule_tester.InvalidTestCaseError{unexpectedAt(1, 16, 1, 28)}},
			// Loop bindings stop shadowing outside the loop.
			{Code: "for (let require of loaders) { require('x'); } if (ready) require('y');",
				FileName:        "input.cjs",
				LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"},
				TSConfig:        "tsconfig.allowJs.json",
				Errors:          []rule_tester.InvalidTestCaseError{unexpectedAt(1, 59, 1, 71)}},
			// Export assignments, assertions and decorators are disallowed ancestors.
			{Code: "export = require('x');",
				FileName:        "input.ts",
				LanguageOptions: rule.LanguageOptions{SourceType: "module"},
				Errors:          []rule_tester.InvalidTestCaseError{unexpectedAt(1, 10, 1, 22)}},
			{Code: "const x = (<any>require)('x'); const y = <any>require('y');",
				FileName:        "input.ts",
				LanguageOptions: rule.LanguageOptions{SourceType: "module"},
				Errors:          []rule_tester.InvalidTestCaseError{unexpectedAt(1, 47, 1, 59)}},
			{Code: "@require('decorator') class C { @require('field') x = 1; }",
				FileName:        "input.ts",
				LanguageOptions: rule.LanguageOptions{SourceType: "module"},
				Errors:          []rule_tester.InvalidTestCaseError{unexpectedAt(1, 2, 1, 22), unexpectedAt(1, 34, 1, 50)}},
		},
	)
}
