
// Code generated by tools/gen_shims. DO NOT EDIT.

package semver

import "github.com/microsoft/TypeScript/tsc/internal/semver"
import _ "unsafe"

//go:linkname MustParse github.com/microsoft/TypeScript/tsc/internal/semver.MustParse
func MustParse(text string) semver.Version
type SemverParseError = semver.SemverParseError
//go:linkname TryParseVersion github.com/microsoft/TypeScript/tsc/internal/semver.TryParseVersion
func TryParseVersion(text string) (semver.Version, error)
//go:linkname TryParseVersionRange github.com/microsoft/TypeScript/tsc/internal/semver.TryParseVersionRange
func TryParseVersionRange(text string) (semver.VersionRange, bool)
type Version = semver.Version
type VersionRange = semver.VersionRange
