name: Setup Node
description: Setup Node.js Environment

runs:
  using: composite

  steps:
    - name: Setup Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: '24'

    - name: Install pnpm
      shell: bash
      run: corepack enable

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
