// Upstream fixture identifiers and intentional misspellings.
// cspell:ignore defaul Guestlist frob
package default_props_match_prop_types

import (
	"testing"

	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/fixtures"
	"github.com/web-infra-dev/rslint/internal/rule_tester"
)

// TestDefaultPropsMatchPropTypesUpstream migrates every upstream v7.37.5 case.
// All supported invalid cases assert complete messages and locations. Additional
// branches and syntax shapes live in default_props_match_prop_types_extras_test.go.
func TestDefaultPropsMatchPropTypesUpstream(t *testing.T) {
	rule_tester.RunRuleTester(fixtures.GetRootDir(), "tsconfig.json", t, &DefaultPropsMatchPropTypesRule,
		[]rule_tester.ValidTestCase{
			// Upstream valid-1
			{Code: "\n        function MyStatelessComponent({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n        MyStatelessComponent.propTypes = {\n          foo: React.PropTypes.string.isRequired,\n          bar: React.PropTypes.string.isRequired\n        };\n      ", Tsx: true},
			// Upstream valid-2
			{Code: "\n        function MyStatelessComponent({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n        MyStatelessComponent.propTypes = {\n          foo: React.PropTypes.string,\n          bar: React.PropTypes.string.isRequired\n        };\n        MyStatelessComponent.defaultProps = {\n          foo: \"foo\"\n        };\n      ", Tsx: true},
			// Upstream valid-3
			{Code: "\n        function MyStatelessComponent({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n      ", Tsx: true},
			// Upstream valid-4
			{Code: "\n        function MyStatelessComponent({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n        MyStatelessComponent.propTypes = {\n          bar: React.PropTypes.string.isRequired\n        };\n        MyStatelessComponent.propTypes.foo = React.PropTypes.string;\n        MyStatelessComponent.defaultProps = {\n          foo: \"foo\"\n        };\n      ", Tsx: true},
			// Upstream valid-5
			{Code: "\n        function MyStatelessComponent({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n        MyStatelessComponent.propTypes = {\n          bar: React.PropTypes.string.isRequired\n        };\n        MyStatelessComponent.defaultProps = {\n          bar: \"bar\"\n        };\n      ", Tsx: true, Options: []any{map[string]any{"allowRequiredDefaults": true}}},
			// Upstream valid-6
			{Code: "\n        function MyStatelessComponent({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n        MyStatelessComponent.propTypes = {\n          bar: React.PropTypes.string.isRequired\n        };\n        MyStatelessComponent.propTypes.foo = React.PropTypes.string;\n        MyStatelessComponent.defaultProps = {};\n        MyStatelessComponent.defaultProps.foo = \"foo\";\n      ", Tsx: true},
			// Upstream valid-7
			{Code: "\n        function MyStatelessComponent({ foo }) {\n          return <div>{foo}</div>;\n        }\n        MyStatelessComponent.propTypes = {};\n        MyStatelessComponent.propTypes.foo = React.PropTypes.string;\n        MyStatelessComponent.defaultProps = {};\n        MyStatelessComponent.defaultProps.foo = \"foo\";\n      ", Tsx: true},
			// Upstream valid-8
			{Code: "\n        const types = {\n          foo: React.PropTypes.string,\n          bar: React.PropTypes.string.isRequired\n        };\n\n        function MyStatelessComponent({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n        MyStatelessComponent.propTypes = types;\n        MyStatelessComponent.defaultProps = {\n          foo: \"foo\"\n        };\n      ", Tsx: true},
			// Upstream valid-9
			{Code: "\n        const defaults = {\n          foo: \"foo\"\n        };\n\n        function MyStatelessComponent({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n        MyStatelessComponent.propTypes = {\n          foo: React.PropTypes.string,\n          bar: React.PropTypes.string.isRequired\n        };\n        MyStatelessComponent.defaultProps = defaults;\n      ", Tsx: true},
			// Upstream valid-10
			{Code: "\n        const defaults = {\n          foo: \"foo\"\n        };\n        const types = {\n          foo: React.PropTypes.string,\n          bar: React.PropTypes.string.isRequired\n        };\n\n        function MyStatelessComponent({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n        MyStatelessComponent.propTypes = types;\n        MyStatelessComponent.defaultProps = defaults;\n      ", Tsx: true},
			// Upstream valid-11
			{Code: "\n        var Greeting = createReactClass({\n          render: function() {\n            return <div>Hello {this.props.foo} {this.props.bar}</div>;\n          },\n          propTypes: {\n            foo: React.PropTypes.string.isRequired,\n            bar: React.PropTypes.string.isRequired\n          }\n        });\n      ", Tsx: true},
			// Upstream valid-12
			{Code: "\n        var Greeting = createReactClass({\n          render: function() {\n            return <div>Hello {this.props.foo} {this.props.bar}</div>;\n          },\n          propTypes: {\n            foo: React.PropTypes.string,\n            bar: React.PropTypes.string.isRequired\n          },\n          getDefaultProps: function() {\n            return {\n              foo: \"foo\"\n            };\n          }\n        });\n      ", Tsx: true},
			// Upstream valid-13
			{Code: "\n        var Greeting = createReactClass({\n          render: function() {\n            return <div>Hello {this.props.foo} {this.props.bar}</div>;\n          },\n          propTypes: {\n            foo: React.PropTypes.string,\n            bar: React.PropTypes.string\n          },\n          getDefaultProps: function() {\n            return {\n              foo: \"foo\",\n              bar: \"bar\"\n            };\n          }\n        });\n      ", Tsx: true},
			// Upstream valid-14
			{Code: "\n        var Greeting = createReactClass({\n          render: function() {\n            return <div>Hello {this.props.foo} {this.props.bar}</div>;\n          }\n        });\n      ", Tsx: true},
			// Upstream valid-15
			{Code: "\n        class Greeting extends React.Component {\n          render() {\n            return (\n              <h1>Hello, {this.props.foo} {this.props.bar}</h1>\n            );\n          }\n        }\n        Greeting.propTypes = {\n          foo: React.PropTypes.string,\n          bar: React.PropTypes.string.isRequired\n        };\n        Greeting.defaultProps = {\n          foo: \"foo\"\n        };\n      ", Tsx: true},
			// Upstream valid-16
			{Code: "\n        class Greeting extends React.Component {\n          render() {\n            return (\n              <h1>Hello, {this.props.foo} {this.props.bar}</h1>\n            );\n          }\n        }\n      ", Tsx: true},
			// Upstream valid-17
			{Code: "\n        class Greeting extends React.Component {\n          render() {\n            return (\n              <h1>Hello, {this.props.foo} {this.props.bar}</h1>\n            );\n          }\n        }\n        Greeting.propTypes = {\n          bar: React.PropTypes.string.isRequired\n        };\n        Greeting.propTypes.foo = React.PropTypes.string;\n        Greeting.defaultProps = {\n          foo: \"foo\"\n        };\n      ", Tsx: true},
			// Upstream valid-18
			{Code: "\n        class Greeting extends React.Component {\n          render() {\n            return (\n              <h1>Hello, {this.props.foo} {this.props.bar}</h1>\n            );\n          }\n        }\n        Greeting.propTypes = {\n          bar: React.PropTypes.string.isRequired\n        };\n        Greeting.propTypes.foo = React.PropTypes.string;\n        Greeting.defaultProps = {};\n        Greeting.defaultProps.foo = \"foo\";\n      ", Tsx: true},
			// Upstream valid-19
			{Code: "\n        class Greeting extends React.Component {\n          render() {\n            return (\n              <h1>Hello, {this.props.foo} {this.props.bar}</h1>\n            );\n          }\n        }\n        Greeting.propTypes = {};\n        Greeting.propTypes.foo = React.PropTypes.string;\n        Greeting.defaultProps = {};\n        Greeting.defaultProps.foo = \"foo\";\n      ", Tsx: true},
			// Upstream valid-20
			{Code: "\n        function NotAComponent({ foo, bar }) {}\n        NotAComponent.defaultProps = {\n          bar: \"bar\"\n        };\n      ", Tsx: true},
			// Upstream valid-21
			{Code: "\n        class Greeting {\n          render() {\n            return (\n              <h1>Hello, {this.props.foo} {this.props.bar}</h1>\n            );\n          }\n        }\n        Greeting.defaulProps = {\n          bar: \"bar\"\n        };\n      ", Tsx: true},
			// Upstream valid-22
			{Code: "\n        const defaults = require(\"./defaults\");\n        const types = {\n          foo: React.PropTypes.string,\n          bar: React.PropTypes.string\n        };\n\n        function MyStatelessComponent({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n        MyStatelessComponent.propTypes = types;\n        MyStatelessComponent.defaultProps = defaults;\n      ", Tsx: true},
			// Upstream valid-23
			{Code: "\n        const defaults = {\n          foo: \"foo\"\n        };\n        const types = require(\"./propTypes\");\n\n        function MyStatelessComponent({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n        MyStatelessComponent.propTypes = types;\n        MyStatelessComponent.defaultProps = defaults;\n      ", Tsx: true},
			// Upstream valid-24
			{Code: "\n        MyStatelessComponent.propTypes = {\n          foo: React.PropTypes.string\n        };\n        MyStatelessComponent.defaultProps = require(\"./defaults\").foo;\n\n        function MyStatelessComponent({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n      ", Tsx: true},
			// Upstream valid-25
			{Code: "\n        MyStatelessComponent.propTypes = {\n          foo: React.PropTypes.string\n        };\n        MyStatelessComponent.defaultProps = require(\"./defaults\").foo;\n        MyStatelessComponent.defaultProps.bar = \"bar\";\n\n        function MyStatelessComponent({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n      ", Tsx: true},
			// Upstream valid-26
			{Code: "\n        import defaults from \"./defaults\";\n\n        MyStatelessComponent.propTypes = {\n          foo: React.PropTypes.string\n        };\n        MyStatelessComponent.defaultProps = defaults;\n\n        function MyStatelessComponent({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n      ", Tsx: true},
			// Upstream valid-27
			{Code: "\n        import { foo } from \"./defaults\";\n\n        MyStatelessComponent.propTypes = {\n          foo: React.PropTypes.string\n        };\n        MyStatelessComponent.defaultProps = foo;\n\n        function MyStatelessComponent({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n      ", Tsx: true},
			// Upstream valid-28
			{Code: "\n        const component = rowsOfType(GuestlistEntry, (rowData, ownProps) => ({\n            ...rowData,\n            onPress: () => ownProps.onPress(rowData.id),\n        }));\n      ", Tsx: true},
			// Upstream valid-29
			{Code: "\n        MyStatelessComponent.propTypes = {\n          ...stuff,\n          foo: React.PropTypes.string\n        };\n        MyStatelessComponent.defaultProps = {\n         foo: \"foo\"\n        };\n        function MyStatelessComponent({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n      ", Tsx: true},
			// Upstream valid-30
			{Code: "\n        MyStatelessComponent.propTypes = {\n          foo: React.PropTypes.string\n        };\n        MyStatelessComponent.defaultProps = {\n         ...defaults,\n        };\n        function MyStatelessComponent({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n      ", Tsx: true},
			// Upstream valid-31
			{Code: "\n        class Greeting extends React.Component {\n          render() {\n            return (\n              <h1>Hello, {this.props.foo} {this.props.bar}</h1>\n            );\n          }\n        }\n        Greeting.propTypes = {\n          ...someProps,\n          bar: React.PropTypes.string.isRequired\n        };\n      ", Tsx: true},
			// Upstream valid-32
			{Code: "\n        class Greeting extends React.Component {\n          render() {\n            return (\n              <h1>Hello, {this.props.foo} {this.props.bar}</h1>\n            );\n          }\n        }\n        Greeting.propTypes = {\n          foo: React.PropTypes.string,\n          bar: React.PropTypes.string.isRequired\n        };\n        Greeting.defaultProps = {\n          ...defaults,\n          bar: \"bar\"\n        };\n      ", Tsx: true},
			// Upstream valid-33
			{Code: "\n        type Props = {\n          foo: string\n        };\n\n        class Hello extends React.Component {\n          props: Props;\n\n          render() {\n            return <div>Hello {this.props.foo}</div>;\n          }\n        }\n      ", Tsx: true},
			// Upstream valid-34
			{Code: "\n        type Props = {\n          foo: string,\n          bar?: string\n        };\n\n        class Hello extends React.Component {\n          props: Props;\n\n          render() {\n            return <div>Hello {this.props.foo}</div>;\n          }\n        }\n\n        Hello.defaultProps = {\n          bar: \"bar\"\n        };\n      ", Tsx: true},
			// Upstream valid-35
			{Code: "\n        class Hello extends React.Component {\n          props: {\n            foo: string,\n            bar?: string\n          };\n\n          render() {\n            return <div>Hello {this.props.foo}</div>;\n          }\n        }\n\n        Hello.defaultProps = {\n          bar: \"bar\"\n        };\n      ", Tsx: true},
			// Upstream valid-36
			{Code: "\n        class Hello extends React.Component {\n          props: {\n            foo: string\n          };\n\n          render() {\n            return <div>Hello {this.props.foo}</div>;\n          }\n        }\n      ", Tsx: true},
			// Upstream valid-37
			{Code: "\n        function Hello(props: { foo?: string }) {\n          return <div>Hello {props.foo}</div>;\n        }\n\n        Hello.defaultProps = { foo: \"foo\" };\n      ", Tsx: true},
			// Upstream valid-38
			{Code: "\n        function Hello(props: { foo: string }) {\n          return <div>Hello {foo}</div>;\n        }\n      ", Tsx: true},
			// Upstream valid-39
			{Code: "\n        const Hello = (props: { foo?: string }) => {\n          return <div>Hello {props.foo}</div>;\n        };\n\n        Hello.defaultProps = { foo: \"foo\" };\n      ", Tsx: true},
			// Upstream valid-40
			{Code: "\n        const Hello = (props: { foo: string }) => {\n          return <div>Hello {foo}</div>;\n        };\n      ", Tsx: true},
			// Upstream valid-41
			{Code: "\n        const Hello = function(props: { foo?: string }) {\n          return <div>Hello {props.foo}</div>;\n        };\n\n        Hello.defaultProps = { foo: \"foo\" };\n      ", Tsx: true},
			// Upstream valid-42
			{Code: "\n        const Hello = function(props: { foo: string }) {\n          return <div>Hello {foo}</div>;\n        };\n      ", Tsx: true},
			// Upstream valid-43
			{Code: "\n        type Props = {\n          foo: string,\n          bar?: string\n        };\n\n        type Props2 = {\n          foo: string,\n          baz?: string\n        }\n\n        function Hello(props: Props | Props2) {\n          return <div>Hello {props.foo}</div>;\n        }\n\n        Hello.defaultProps = {\n          bar: \"bar\",\n          baz: \"baz\"\n        };\n      ", Tsx: true},
			// Upstream valid-44
			{Code: "\n        type PropsA = { foo?: string };\n        type PropsB = { bar?: string, fooBar: string };\n        type Props = PropsA & PropsB;\n\n        class Bar extends React.Component {\n          props: Props;\n          static defaultProps = {\n            foo: \"foo\",\n          }\n\n          render() {\n            return <div>{this.props.foo} - {this.props.bar}</div>\n          }\n        }\n      ", Tsx: true},
			// Upstream valid-45
			{Code: "\n        import type Props from \"fake\";\n        class Hello extends React.Component {\n          props: Props;\n          render () {\n            return <div>Hello {this.props.name.firstname}</div>;\n          }\n        }\n      ", Tsx: true},
			// Upstream valid-46
			{Code: "\n        type Props = any;\n\n        const Hello = function({ foo }: Props) {\n          return <div>Hello {foo}</div>;\n        };\n      ", Tsx: true},
			// Upstream valid-47
			{Code: "\n        import type ImportedProps from \"fake\";\n        type Props = ImportedProps;\n        function Hello(props: Props) {\n          return <div>Hello {props.name.firstname}</div>;\n        }\n      ", Tsx: true},
			// Upstream valid-48
			// SKIP: upstream explicitly selects the Flow parser; Rslint does not parse Flow.
			{Code: "\n        type DefaultProps1 = {|\n          bar1?: string\n        |};\n        type DefaultProps2 = {|\n          ...DefaultProps1,\n          bar2?: string\n        |};\n        type Props = {\n          foo: string,\n          ...DefaultProps2\n        };\n\n        function Hello(props: Props) {\n          return <div>Hello {props.foo}</div>;\n        }\n\n        Hello.defaultProps = {\n          bar1: \"bar1\",\n          bar2: \"bar2\",\n        };\n      ", Tsx: true, Skip: true},
			// Upstream valid-49
			// SKIP: upstream explicitly selects the Flow parser; Rslint does not parse Flow.
			{Code: "\n        type DefaultProps1 = {|\n          bar1?: string\n        |};\n        type DefaultProps2 = {|\n          ...DefaultProps1,\n          bar2?: string\n        |};\n        type Props = {\n          foo: string,\n          ...DefaultProps2\n        };\n\n        class Hello extends React.Component<Props> {\n          render() {\n            return <div>Hello {props.foo}</div>;\n          }\n        }\n\n        Hello.defaultProps = {\n          bar1: \"bar1\",\n          bar2: \"bar2\",\n        };\n      ", Tsx: true, Skip: true},
			// Upstream valid-50
			{Code: "\n        import type { ImportedType } from \"fake\";\n        type Props = ImportedType;\n        function Hello(props: Props) {\n          return <div>Hello {props.name.firstname}</div>;\n        }\n      ", Tsx: true},
			// Upstream valid-51
			{Code: "\n        import type ImportedProps from \"fake\";\n        type NestedProps = ImportedProps;\n        type Props = NestedProps;\n        function Hello(props: Props) {\n          return <div>Hello {props.name.firstname}</div>;\n        }\n      ", Tsx: true},
			// Upstream valid-52
			{Code: "\n        import type ImportedProps from \"fake\";\n        type Props = ImportedProps & {\n          foo: string\n        };\n        function Hello(props: Props) {\n          return <div>Hello {props.name.firstname}</div>;\n        }\n      ", Tsx: true},
			// Upstream valid-53
			{Code: "\n        import type { FieldProps } from 'redux-form';\n\n        type Props = FieldProps & {\n          name: string,\n          type: string,\n          label?: string,\n          placeholder?: string,\n          disabled?: boolean,\n        };\n\n        TextField.defaultProps = {\n          label: '',\n          placeholder: '',\n          disabled: false,\n        };\n      ", Tsx: true},
		},
		[]rule_tester.InvalidTestCase{
			// Upstream invalid-1
			{Code: "\n        function MyStatelessComponent({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n        MyStatelessComponent.propTypes = {\n          foo: React.PropTypes.string,\n          bar: React.PropTypes.string.isRequired\n        };\n        MyStatelessComponent.defaultProps = {\n          baz: \"baz\"\n        };\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "defaultHasNoType", Message: "defaultProp \"baz\" has no corresponding propTypes declaration.", Line: 10, Column: 11, EndLine: 10, EndColumn: 21}}},
			// Upstream invalid-2
			{Code: "\n        function MyStatelessComponent({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n        MyStatelessComponent.propTypes = forbidExtraProps({\n          foo: React.PropTypes.string,\n          bar: React.PropTypes.string.isRequired\n        })\n        MyStatelessComponent.defaultProps = {\n          baz: \"baz\"\n        };\n      ", Tsx: true, Settings: map[string]any{"propWrapperFunctions": []any{"forbidExtraProps"}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "defaultHasNoType", Message: "defaultProp \"baz\" has no corresponding propTypes declaration.", Line: 10, Column: 11, EndLine: 10, EndColumn: 21}}},
			// Upstream invalid-3
			{Code: "\n        function MyStatelessComponent({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n        const propTypes = {\n          foo: React.PropTypes.string,\n          bar: React.PropTypes.string.isRequired\n        };\n        MyStatelessComponent.propTypes = forbidExtraProps(propTypes);\n        MyStatelessComponent.defaultProps = {\n          baz: \"baz\"\n        };\n      ", Tsx: true, Settings: map[string]any{"propWrapperFunctions": []any{"forbidExtraProps"}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "defaultHasNoType", Message: "defaultProp \"baz\" has no corresponding propTypes declaration.", Line: 11, Column: 11, EndLine: 11, EndColumn: 21}}},
			// Upstream invalid-4
			{Code: "\n        function MyStatelessComponent({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n        MyStatelessComponent.propTypes = {\n          foo: React.PropTypes.string,\n          bar: React.PropTypes.string.isRequired\n        };\n        MyStatelessComponent.defaultProps = {\n          baz: \"baz\"\n        };\n      ", Tsx: true, Options: []any{map[string]any{"allowRequiredDefaults": true}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "defaultHasNoType", Message: "defaultProp \"baz\" has no corresponding propTypes declaration.", Line: 10, Column: 11, EndLine: 10, EndColumn: 21}}},
			// Upstream invalid-5
			{Code: "\n        function MyStatelessComponent({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n        MyStatelessComponent.propTypes = {\n          foo: React.PropTypes.string,\n          bar: React.PropTypes.string.isRequired\n        };\n        MyStatelessComponent.defaultProps = {\n          bar: \"bar\"\n        };\n        MyStatelessComponent.defaultProps.baz = \"baz\";\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "requiredHasDefault", Message: "defaultProp \"bar\" defined for isRequired propType.", Line: 10, Column: 11, EndLine: 10, EndColumn: 21}, {MessageId: "defaultHasNoType", Message: "defaultProp \"baz\" has no corresponding propTypes declaration.", Line: 12, Column: 9, EndLine: 12, EndColumn: 54}}},
			// Upstream invalid-6
			{Code: "\n        const types = {\n          foo: React.PropTypes.string,\n          bar: React.PropTypes.string.isRequired\n        };\n\n        function MyStatelessComponent({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n        MyStatelessComponent.propTypes = types;\n        MyStatelessComponent.defaultProps = {\n          bar: \"bar\"\n        };\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "requiredHasDefault", Message: "defaultProp \"bar\" defined for isRequired propType.", Line: 12, Column: 11, EndLine: 12, EndColumn: 21}}},
			// Upstream invalid-7
			{Code: "\n        const defaults = {\n          foo: \"foo\"\n        };\n\n        function MyStatelessComponent({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n        MyStatelessComponent.propTypes = {\n          foo: React.PropTypes.string.isRequired,\n          bar: React.PropTypes.string\n        };\n        MyStatelessComponent.defaultProps = defaults;\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "requiredHasDefault", Message: "defaultProp \"foo\" defined for isRequired propType.", Line: 3, Column: 11, EndLine: 3, EndColumn: 21}}},
			// Upstream invalid-8
			{Code: "\n        const defaults = {\n          foo: \"foo\"\n        };\n        const types = {\n          foo: React.PropTypes.string.isRequired,\n          bar: React.PropTypes.string\n        };\n\n        function MyStatelessComponent({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n        MyStatelessComponent.propTypes = types;\n        MyStatelessComponent.defaultProps = defaults;\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "requiredHasDefault", Message: "defaultProp \"foo\" defined for isRequired propType.", Line: 3, Column: 11, EndLine: 3, EndColumn: 21}}},
			// Upstream invalid-9
			{Code: "\n        var Greeting = createReactClass({\n          render: function() {\n            return <div>Hello {this.props.foo} {this.props.bar}</div>;\n          },\n          propTypes: {\n            foo: React.PropTypes.string,\n            bar: React.PropTypes.string.isRequired\n          },\n          getDefaultProps: function() {\n            return {\n              baz: \"baz\"\n            };\n          }\n        });\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "defaultHasNoType", Message: "defaultProp \"baz\" has no corresponding propTypes declaration.", Line: 12, Column: 15, EndLine: 12, EndColumn: 25}}},
			// Upstream invalid-10
			{Code: "\n        var Greeting = createReactClass({\n          render: function() {\n            return <div>Hello {this.props.foo} {this.props.bar}</div>;\n          },\n          propTypes: {\n            foo: React.PropTypes.string.isRequired,\n            bar: React.PropTypes.string\n          },\n          getDefaultProps: function() {\n            return {\n              foo: \"foo\"\n            };\n          }\n        });\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "requiredHasDefault", Message: "defaultProp \"foo\" defined for isRequired propType.", Line: 12, Column: 15, EndLine: 12, EndColumn: 25}}},
			// Upstream invalid-11
			{Code: "\n        class Greeting extends React.Component {\n          render() {\n            return (\n              <h1>Hello, {this.props.foo} {this.props.bar}</h1>\n            );\n          }\n        }\n        Greeting.propTypes = {\n          foo: React.PropTypes.string,\n          bar: React.PropTypes.string.isRequired\n        };\n        Greeting.defaultProps = {\n          baz: \"baz\"\n        };\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "defaultHasNoType", Message: "defaultProp \"baz\" has no corresponding propTypes declaration.", Line: 14, Column: 11, EndLine: 14, EndColumn: 21}}},
			// Upstream invalid-12
			{Code: "\n        class Greeting extends React.Component {\n          render() {\n            return (\n              <h1>Hello, {this.props.foo} {this.props.bar}</h1>\n            );\n          }\n        }\n        Greeting.propTypes = {\n          foo: React.PropTypes.string.isRequired,\n          bar: React.PropTypes.string\n        };\n        Greeting.defaultProps = {\n          foo: \"foo\"\n        };\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "requiredHasDefault", Message: "defaultProp \"foo\" defined for isRequired propType.", Line: 14, Column: 11, EndLine: 14, EndColumn: 21}}},
			// Upstream invalid-13
			{Code: "\n        class Greeting extends React.Component {\n          render() {\n            return (\n              <h1>Hello, {this.props.foo} {this.props.bar}</h1>\n            );\n          }\n        }\n        Greeting.propTypes = {\n          bar: React.PropTypes.string.isRequired\n        };\n        Greeting.propTypes.foo = React.PropTypes.string.isRequired;\n        Greeting.defaultProps = {};\n        Greeting.defaultProps.foo = \"foo\";\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "requiredHasDefault", Message: "defaultProp \"foo\" defined for isRequired propType.", Line: 14, Column: 9, EndLine: 14, EndColumn: 42}}},
			// Upstream invalid-14
			{Code: "\n        class Greeting extends React.Component {\n          render() {\n            return (\n              <h1>Hello, {this.props.foo} {this.props.bar}</h1>\n            );\n          }\n        }\n        Greeting.propTypes = {\n          bar: React.PropTypes.string\n        };\n        Greeting.propTypes.foo = React.PropTypes.string;\n        Greeting.defaultProps = {};\n        Greeting.defaultProps.baz = \"baz\";\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "defaultHasNoType", Message: "defaultProp \"baz\" has no corresponding propTypes declaration.", Line: 14, Column: 9, EndLine: 14, EndColumn: 42}}},
			// Upstream invalid-15
			{Code: "\n        class Greeting extends React.Component {\n          render() {\n            return (\n              <h1>Hello, {this.props.foo} {this.props.bar}</h1>\n            );\n          }\n        }\n        Greeting.propTypes = {};\n        Greeting.propTypes.foo = React.PropTypes.string.isRequired;\n        Greeting.defaultProps = {};\n        Greeting.defaultProps.foo = \"foo\";\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "requiredHasDefault", Message: "defaultProp \"foo\" defined for isRequired propType.", Line: 12, Column: 9, EndLine: 12, EndColumn: 42}}},
			// Upstream invalid-16
			{Code: "\n        class Greeting extends React.Component {\n          render() {\n            return (\n              <h1>Hello, {this.props.foo} {this.props.bar}</h1>\n            );\n          }\n        }\n        const props = {\n          foo: React.PropTypes.string,\n          bar: React.PropTypes.string.isRequired\n        };\n        Greeting.propTypes = props;\n        const defaults = {\n          bar: \"bar\"\n        };\n        Greeting.defaultProps = defaults;\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "requiredHasDefault", Message: "defaultProp \"bar\" defined for isRequired propType.", Line: 15, Column: 11, EndLine: 15, EndColumn: 21}}},
			// Upstream invalid-17
			{Code: "\n        class Greeting extends React.Component {\n          render() {\n            return (\n              <h1>Hello, {this.props.foo} {this.props.bar}</h1>\n            );\n          }\n        }\n        const props = {\n          foo: React.PropTypes.string,\n          bar: React.PropTypes.string\n        };\n        const defaults = {\n          baz: \"baz\"\n        };\n        Greeting.propTypes = props;\n        Greeting.defaultProps = defaults;\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "defaultHasNoType", Message: "defaultProp \"baz\" has no corresponding propTypes declaration.", Line: 14, Column: 11, EndLine: 14, EndColumn: 21}}},
			// Upstream invalid-18
			{Code: "\n        class Hello extends React.Component {\n          static get propTypes() {\n            return {\n              name: React.PropTypes.string.isRequired\n            };\n          }\n          static get defaultProps() {\n            return {\n              name: \"name\"\n            };\n          }\n          render() {\n            return <div>Hello {this.props.name}</div>;\n          }\n        }\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "requiredHasDefault", Message: "defaultProp \"name\" defined for isRequired propType.", Line: 10, Column: 15, EndLine: 10, EndColumn: 27}}},
			// Upstream invalid-19
			{Code: "\n        class Hello extends React.Component {\n          static get propTypes() {\n            return {\n              foo: React.PropTypes.string,\n              bar: React.PropTypes.string\n            };\n          }\n          static get defaultProps() {\n            return {\n              baz: \"world\"\n            };\n          }\n          render() {\n            return <div>Hello {this.props.bar}</div>;\n          }\n        }\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "defaultHasNoType", Message: "defaultProp \"baz\" has no corresponding propTypes declaration.", Line: 11, Column: 15, EndLine: 11, EndColumn: 27}}},
			// Upstream invalid-20
			{Code: "\n        const props = {\n          foo: React.PropTypes.string\n        };\n        const defaults = {\n          baz: \"baz\"\n        };\n\n        class Hello extends React.Component {\n          static get propTypes() {\n            return props;\n          }\n          static get defaultProps() {\n            return defaults;\n          }\n          render() {\n            return <div>Hello {this.props.foo}</div>;\n          }\n        }\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "defaultHasNoType", Message: "defaultProp \"baz\" has no corresponding propTypes declaration.", Line: 6, Column: 11, EndLine: 6, EndColumn: 21}}},
			// Upstream invalid-21
			{Code: "\n        const defaults = {\n          bar: \"world\"\n        };\n\n        class Hello extends React.Component {\n          static get propTypes() {\n            return {\n              foo: React.PropTypes.string,\n              bar: React.PropTypes.string.isRequired\n            };\n          }\n          static get defaultProps() {\n            return defaults;\n          }\n          render() {\n            return <div>Hello {this.props.bar}</div>;\n          }\n        }\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "requiredHasDefault", Message: "defaultProp \"bar\" defined for isRequired propType.", Line: 3, Column: 11, EndLine: 3, EndColumn: 23}}},
			// Upstream invalid-22
			{Code: "\n        class Greeting extends React.Component {\n          render() {\n            return (\n              <h1>Hello, {this.props.foo} {this.props.bar}</h1>\n            );\n          }\n          static propTypes = {\n            foo: React.PropTypes.string,\n            bar: React.PropTypes.string.isRequired\n          };\n          static defaultProps = {\n            bar: \"bar\"\n          };\n        }\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "requiredHasDefault", Message: "defaultProp \"bar\" defined for isRequired propType.", Line: 13, Column: 13, EndLine: 13, EndColumn: 23}}},
			// Upstream invalid-23
			{Code: "\n        class Greeting extends React.Component {\n          render() {\n            return (\n              <h1>Hello, {this.props.foo} {this.props.bar}</h1>\n            );\n          }\n          static propTypes = {\n            foo: React.PropTypes.string,\n            bar: React.PropTypes.string\n          };\n          static defaultProps = {\n            baz: \"baz\"\n          };\n        }\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "defaultHasNoType", Message: "defaultProp \"baz\" has no corresponding propTypes declaration.", Line: 13, Column: 13, EndLine: 13, EndColumn: 23}}},
			// Upstream invalid-24
			{Code: "\n        const props = {\n          foo: React.PropTypes.string,\n          bar: React.PropTypes.string.isRequired\n        };\n        const defaults = {\n          bar: \"bar\"\n        };\n        class Greeting extends React.Component {\n          render() {\n            return (\n              <h1>Hello, {this.props.foo} {this.props.bar}</h1>\n            );\n          }\n          static propTypes = props;\n          static defaultProps = defaults;\n        }\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "requiredHasDefault", Message: "defaultProp \"bar\" defined for isRequired propType.", Line: 7, Column: 11, EndLine: 7, EndColumn: 21}}},
			// Upstream invalid-25
			{Code: "\n        const props = {\n          foo: React.PropTypes.string,\n          bar: React.PropTypes.string\n        };\n        const defaults = {\n          baz: \"baz\"\n        };\n        class Greeting extends React.Component {\n          render() {\n            return (\n              <h1>Hello, {this.props.foo} {this.props.bar}</h1>\n            );\n          }\n          static propTypes = props;\n          static defaultProps = defaults;\n        }\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "defaultHasNoType", Message: "defaultProp \"baz\" has no corresponding propTypes declaration.", Line: 7, Column: 11, EndLine: 7, EndColumn: 21}}},
			// Upstream invalid-26
			{Code: "\n        let Greetings = {};\n        Greetings.Hello = class extends React.Component {\n          render () {\n            return <div>Hello {this.props.foo}</div>;\n          }\n        }\n        Greetings.Hello.propTypes = {\n          foo: React.PropTypes.string.isRequired\n        };\n        Greetings.Hello.defaultProps = {\n          foo: \"foo\"\n        };\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "requiredHasDefault", Message: "defaultProp \"foo\" defined for isRequired propType.", Line: 12, Column: 11, EndLine: 12, EndColumn: 21}}},
			// Upstream invalid-27
			{Code: "\n        var Greetings = ({ foo = \"foo\" }) => {\n          return <div>Hello {this.props.foo}</div>;\n        }\n        Greetings.propTypes = {\n          foo: React.PropTypes.string.isRequired\n        };\n        Greetings.defaultProps = {\n          foo: \"foo\"\n        };\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "requiredHasDefault", Message: "defaultProp \"foo\" defined for isRequired propType.", Line: 9, Column: 11, EndLine: 9, EndColumn: 21}}},
			// Upstream invalid-28
			{Code: "\n        class Hello extends React.Component {\n          props: {\n            foo: string,\n            bar?: string\n          };\n\n          render() {\n            return <div>Hello {this.props.foo}</div>;\n          }\n        }\n\n        Hello.defaultProps = {\n          foo: \"foo\"\n        };\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "requiredHasDefault", Message: "defaultProp \"foo\" defined for isRequired propType.", Line: 14, Column: 11, EndLine: 14, EndColumn: 21}}},
			// Upstream invalid-29
			{Code: "\n        function Hello(props: { foo: string }) {\n          return <div>Hello {props.foo}</div>;\n        }\n        Hello.defaultProps = {\n          foo: \"foo\"\n        }\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "requiredHasDefault", Message: "defaultProp \"foo\" defined for isRequired propType.", Line: 6, Column: 11, EndLine: 6, EndColumn: 21}}},
			// Upstream invalid-30
			{Code: "\n        type Props = {\n          foo: string\n        };\n\n        function Hello(props: Props) {\n          return <div>Hello {props.foo}</div>;\n        }\n        Hello.defaultProps = {\n          foo: \"foo\"\n        }\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "requiredHasDefault", Message: "defaultProp \"foo\" defined for isRequired propType.", Line: 10, Column: 11, EndLine: 10, EndColumn: 21}}},
			// Upstream invalid-31
			{Code: "\n        const Hello = (props: { foo: string, bar?: string }) => {\n          return <div>Hello {props.foo}</div>;\n        };\n        Hello.defaultProps = { foo: \"foo\", bar: \"bar\" };\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "requiredHasDefault", Message: "defaultProp \"foo\" defined for isRequired propType.", Line: 5, Column: 32, EndLine: 5, EndColumn: 42}}},
			// Upstream invalid-32
			// SKIP: upstream explicitly selects the Flow parser; Rslint does not parse Flow.
			{Code: "\n        type Props = {\n          foo: string,\n          bar?: string\n        };\n\n        type Props2 = {\n          foo: string,\n          baz?: string\n        }\n\n        function Hello(props: Props | Props2) {\n          return <div>Hello {props.foo}</div>;\n        }\n        Hello.defaultProps = { foo: \"foo\", frob: \"frob\" };\n      ", Tsx: true, Skip: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "requiredHasDefault", Line: 15, Column: 32}, {MessageId: "defaultHasNoType", Line: 15, Column: 44}}},
			// Upstream invalid-33
			{Code: "\n        type PropsA = { foo: string };\n        type PropsB = { bar: string };\n        type Props = PropsA & PropsB;\n\n        class Bar extends React.Component {\n          props: Props;\n          static defaultProps = {\n            fooBar: \"fooBar\",\n            foo: \"foo\",\n          }\n\n          render() {\n            return <div>{this.props.foo} - {this.props.bar}</div>\n          }\n        }\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "defaultHasNoType", Message: "defaultProp \"fooBar\" has no corresponding propTypes declaration.", Line: 9, Column: 13, EndLine: 9, EndColumn: 29}, {MessageId: "requiredHasDefault", Message: "defaultProp \"foo\" defined for isRequired propType.", Line: 10, Column: 13, EndLine: 10, EndColumn: 23}}},
			// Upstream invalid-34
			{Code: "\n        class SomeComponent extends React.Component {\n          render() {\n            return <div />;\n          }\n        }\n        SomeComponent.propTypes = {\n          \"firstProperty\": PropTypes.string.isRequired,\n        };\n\n        SomeComponent.defaultProps = {\n          \"firstProperty\": () => undefined\n        };\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "requiredHasDefault", Message: "defaultProp \"firstProperty\" defined for isRequired propType.", Line: 12, Column: 11, EndLine: 12, EndColumn: 43}}},
			// Upstream invalid-35
			// SKIP: upstream explicitly selects the Flow parser; Rslint does not parse Flow.
			{Code: "\n        type DefaultProps = {\n          baz?: string,\n          bar?: string\n        };\n\n        type Props = {\n          foo: string,\n          ...DefaultProps\n        }\n\n        function Hello(props: Props) {\n          return <div>Hello {props.foo}</div>;\n        }\n        Hello.defaultProps = { foo: \"foo\", frob: \"frob\", baz: \"bar\" };\n      ", Tsx: true, Skip: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "requiredHasDefault", Line: 15, Column: 32}, {MessageId: "defaultHasNoType", Line: 15, Column: 44}}},
			// Upstream invalid-36
			// SKIP: upstream explicitly selects the Flow parser; Rslint does not parse Flow.
			{Code: "\n        type DefaultProps = {\n          baz?: string,\n          bar?: string\n        };\n\n        type Props = {\n          foo: string,\n          ...DefaultProps\n        }\n\n        class Hello extends React.Component<Props> {\n          render() {\n            return <div>Hello {props.foo}</div>;\n          }\n        }\n        Hello.defaultProps = { foo: \"foo\", frob: \"frob\", baz: \"bar\" };\n      ", Tsx: true, Skip: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "requiredHasDefault", Line: 17, Column: 32}, {MessageId: "defaultHasNoType", Line: 17, Column: 44}}},
			// Upstream invalid-37
			// SKIP: upstream explicitly selects the Flow parser; Rslint does not parse Flow.
			{Code: "\n        export type SharedProps = {|\n            disabled: boolean,\n        |};\n\n        type Props = {|\n            ...SharedProps,\n            focused?: boolean,\n        |};\n\n        class Foo extends React.Component<Props> {\n            static defaultProps = {\n              disabled: false\n            };\n        };\n      ", Tsx: true, Skip: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "requiredHasDefault"}}},
		},
	)
}
