# .github/release.yml

changelog:
  categories:
    - title: Breaking Changes 🍭
      labels:
        - 'release: breaking change'
    - title: New Features 🎉
      labels:
        - 'release: feature'
    - title: Performance 🚀
      labels:
        - 'release: performance'
    - title: Bug Fixes 🐞
      labels:
        - 'release: bug fix'
    - title: Refactor 🔨
      labels:
        - 'release: refactor'
    - title: Document 📖
      labels:
        - 'release: document'
    - title: Other Changes
      labels:
        - '*'
