package rules

import (
	"sync"

	importPlugin "github.com/web-infra-dev/rslint/internal/plugins/import"
	jestPlugin "github.com/web-infra-dev/rslint/internal/plugins/jest"
	jsxA11yPlugin "github.com/web-infra-dev/rslint/internal/plugins/jsx_a11y"
	promisePlugin "github.com/web-infra-dev/rslint/internal/plugins/promise"
	reactPlugin "github.com/web-infra-dev/rslint/internal/plugins/react"
	reactHooksPlugin "github.com/web-infra-dev/rslint/internal/plugins/react_hooks"
	rstestPlugin "github.com/web-infra-dev/rslint/internal/plugins/rstest"
	typescriptPlugin "github.com/web-infra-dev/rslint/internal/plugins/typescript"
	unicornPlugin "github.com/web-infra-dev/rslint/internal/plugins/unicorn"
	"github.com/web-infra-dev/rslint/internal/rule"
	"github.com/web-infra-dev/rslint/internal/rules/accessor_pairs"
	"github.com/web-infra-dev/rslint/internal/rules/array_callback_return"
	"github.com/web-infra-dev/rslint/internal/rules/arrow_body_style"
	"github.com/web-infra-dev/rslint/internal/rules/block_scoped_var"
	"github.com/web-infra-dev/rslint/internal/rules/capitalized_comments"
	"github.com/web-infra-dev/rslint/internal/rules/class_methods_use_this"
	"github.com/web-infra-dev/rslint/internal/rules/complexity"
	"github.com/web-infra-dev/rslint/internal/rules/consistent_return"
	"github.com/web-infra-dev/rslint/internal/rules/consistent_this"
	"github.com/web-infra-dev/rslint/internal/rules/constructor_super"
	"github.com/web-infra-dev/rslint/internal/rules/curly"
	"github.com/web-infra-dev/rslint/internal/rules/default_case"
	"github.com/web-infra-dev/rslint/internal/rules/default_case_last"
	"github.com/web-infra-dev/rslint/internal/rules/default_param_last"
	"github.com/web-infra-dev/rslint/internal/rules/dot_notation"
	"github.com/web-infra-dev/rslint/internal/rules/eqeqeq"
	"github.com/web-infra-dev/rslint/internal/rules/for_direction"
	"github.com/web-infra-dev/rslint/internal/rules/func_name_matching"
	"github.com/web-infra-dev/rslint/internal/rules/func_names"
	"github.com/web-infra-dev/rslint/internal/rules/getter_return"
	"github.com/web-infra-dev/rslint/internal/rules/guard_for_in"
	"github.com/web-infra-dev/rslint/internal/rules/id_length"
	"github.com/web-infra-dev/rslint/internal/rules/init_declarations"
	"github.com/web-infra-dev/rslint/internal/rules/max_classes_per_file"
	"github.com/web-infra-dev/rslint/internal/rules/max_depth"
	"github.com/web-infra-dev/rslint/internal/rules/max_lines"
	"github.com/web-infra-dev/rslint/internal/rules/max_lines_per_function"
	"github.com/web-infra-dev/rslint/internal/rules/max_nested_callbacks"
	"github.com/web-infra-dev/rslint/internal/rules/max_params"
	"github.com/web-infra-dev/rslint/internal/rules/max_statements"
	"github.com/web-infra-dev/rslint/internal/rules/new_cap"
	"github.com/web-infra-dev/rslint/internal/rules/no_alert"
	"github.com/web-infra-dev/rslint/internal/rules/no_array_constructor"
	"github.com/web-infra-dev/rslint/internal/rules/no_async_promise_executor"
	"github.com/web-infra-dev/rslint/internal/rules/no_await_in_loop"
	"github.com/web-infra-dev/rslint/internal/rules/no_bitwise"
	"github.com/web-infra-dev/rslint/internal/rules/no_caller"
	"github.com/web-infra-dev/rslint/internal/rules/no_case_declarations"
	"github.com/web-infra-dev/rslint/internal/rules/no_class_assign"
	"github.com/web-infra-dev/rslint/internal/rules/no_compare_neg_zero"
	"github.com/web-infra-dev/rslint/internal/rules/no_cond_assign"
	"github.com/web-infra-dev/rslint/internal/rules/no_console"
	"github.com/web-infra-dev/rslint/internal/rules/no_const_assign"
	"github.com/web-infra-dev/rslint/internal/rules/no_constant_binary_expression"
	"github.com/web-infra-dev/rslint/internal/rules/no_constant_condition"
	"github.com/web-infra-dev/rslint/internal/rules/no_constructor_return"
	"github.com/web-infra-dev/rslint/internal/rules/no_continue"
	"github.com/web-infra-dev/rslint/internal/rules/no_control_regex"
	"github.com/web-infra-dev/rslint/internal/rules/no_debugger"
	"github.com/web-infra-dev/rslint/internal/rules/no_delete_var"
	"github.com/web-infra-dev/rslint/internal/rules/no_div_regex"
	"github.com/web-infra-dev/rslint/internal/rules/no_dupe_args"
	"github.com/web-infra-dev/rslint/internal/rules/no_dupe_class_members"
	"github.com/web-infra-dev/rslint/internal/rules/no_dupe_else_if"
	"github.com/web-infra-dev/rslint/internal/rules/no_dupe_keys"
	"github.com/web-infra-dev/rslint/internal/rules/no_duplicate_case"
	"github.com/web-infra-dev/rslint/internal/rules/no_duplicate_imports"
	"github.com/web-infra-dev/rslint/internal/rules/no_else_return"
	"github.com/web-infra-dev/rslint/internal/rules/no_empty"
	"github.com/web-infra-dev/rslint/internal/rules/no_empty_character_class"
	"github.com/web-infra-dev/rslint/internal/rules/no_empty_function"
	"github.com/web-infra-dev/rslint/internal/rules/no_empty_pattern"
	"github.com/web-infra-dev/rslint/internal/rules/no_empty_static_block"
	"github.com/web-infra-dev/rslint/internal/rules/no_eq_null"
	"github.com/web-infra-dev/rslint/internal/rules/no_eval"
	"github.com/web-infra-dev/rslint/internal/rules/no_ex_assign"
	"github.com/web-infra-dev/rslint/internal/rules/no_extend_native"
	"github.com/web-infra-dev/rslint/internal/rules/no_extra_bind"
	"github.com/web-infra-dev/rslint/internal/rules/no_extra_boolean_cast"
	"github.com/web-infra-dev/rslint/internal/rules/no_extra_label"
	"github.com/web-infra-dev/rslint/internal/rules/no_fallthrough"
	"github.com/web-infra-dev/rslint/internal/rules/no_func_assign"
	"github.com/web-infra-dev/rslint/internal/rules/no_global_assign"
	"github.com/web-infra-dev/rslint/internal/rules/no_implicit_coercion"
	"github.com/web-infra-dev/rslint/internal/rules/no_implied_eval"
	"github.com/web-infra-dev/rslint/internal/rules/no_import_assign"
	"github.com/web-infra-dev/rslint/internal/rules/no_inline_comments"
	"github.com/web-infra-dev/rslint/internal/rules/no_inner_declarations"
	"github.com/web-infra-dev/rslint/internal/rules/no_invalid_regexp"
	"github.com/web-infra-dev/rslint/internal/rules/no_invalid_this"
	"github.com/web-infra-dev/rslint/internal/rules/no_irregular_whitespace"
	"github.com/web-infra-dev/rslint/internal/rules/no_iterator"
	"github.com/web-infra-dev/rslint/internal/rules/no_label_var"
	"github.com/web-infra-dev/rslint/internal/rules/no_labels"
	"github.com/web-infra-dev/rslint/internal/rules/no_lone_blocks"
	"github.com/web-infra-dev/rslint/internal/rules/no_lonely_if"
	"github.com/web-infra-dev/rslint/internal/rules/no_loop_func"
	"github.com/web-infra-dev/rslint/internal/rules/no_loss_of_precision"
	"github.com/web-infra-dev/rslint/internal/rules/no_magic_numbers"
	"github.com/web-infra-dev/rslint/internal/rules/no_misleading_character_class"
	"github.com/web-infra-dev/rslint/internal/rules/no_multi_assign"
	"github.com/web-infra-dev/rslint/internal/rules/no_multi_str"
	"github.com/web-infra-dev/rslint/internal/rules/no_negated_condition"
	"github.com/web-infra-dev/rslint/internal/rules/no_nested_ternary"
	"github.com/web-infra-dev/rslint/internal/rules/no_new"
	"github.com/web-infra-dev/rslint/internal/rules/no_new_func"
	"github.com/web-infra-dev/rslint/internal/rules/no_new_native_nonconstructor"
	"github.com/web-infra-dev/rslint/internal/rules/no_new_object"
	"github.com/web-infra-dev/rslint/internal/rules/no_new_symbol"
	"github.com/web-infra-dev/rslint/internal/rules/no_new_wrappers"
	"github.com/web-infra-dev/rslint/internal/rules/no_nonoctal_decimal_escape"
	"github.com/web-infra-dev/rslint/internal/rules/no_obj_calls"
	"github.com/web-infra-dev/rslint/internal/rules/no_object_constructor"
	"github.com/web-infra-dev/rslint/internal/rules/no_octal"
	"github.com/web-infra-dev/rslint/internal/rules/no_octal_escape"
	"github.com/web-infra-dev/rslint/internal/rules/no_param_reassign"
	"github.com/web-infra-dev/rslint/internal/rules/no_plusplus"
	"github.com/web-infra-dev/rslint/internal/rules/no_promise_executor_return"
	"github.com/web-infra-dev/rslint/internal/rules/no_proto"
	"github.com/web-infra-dev/rslint/internal/rules/no_prototype_builtins"
	"github.com/web-infra-dev/rslint/internal/rules/no_redeclare"
	"github.com/web-infra-dev/rslint/internal/rules/no_regex_spaces"
	"github.com/web-infra-dev/rslint/internal/rules/no_restricted_exports"
	"github.com/web-infra-dev/rslint/internal/rules/no_restricted_globals"
	"github.com/web-infra-dev/rslint/internal/rules/no_restricted_imports"
	"github.com/web-infra-dev/rslint/internal/rules/no_restricted_properties"
	"github.com/web-infra-dev/rslint/internal/rules/no_restricted_syntax"
	"github.com/web-infra-dev/rslint/internal/rules/no_return_assign"
	"github.com/web-infra-dev/rslint/internal/rules/no_script_url"
	"github.com/web-infra-dev/rslint/internal/rules/no_self_assign"
	"github.com/web-infra-dev/rslint/internal/rules/no_self_compare"
	"github.com/web-infra-dev/rslint/internal/rules/no_sequences"
	"github.com/web-infra-dev/rslint/internal/rules/no_setter_return"
	"github.com/web-infra-dev/rslint/internal/rules/no_shadow"
	"github.com/web-infra-dev/rslint/internal/rules/no_shadow_restricted_names"
	"github.com/web-infra-dev/rslint/internal/rules/no_sparse_arrays"
	"github.com/web-infra-dev/rslint/internal/rules/no_template_curly_in_string"
	"github.com/web-infra-dev/rslint/internal/rules/no_ternary"
	"github.com/web-infra-dev/rslint/internal/rules/no_this_before_super"
	"github.com/web-infra-dev/rslint/internal/rules/no_throw_literal"
	"github.com/web-infra-dev/rslint/internal/rules/no_unassigned_vars"
	"github.com/web-infra-dev/rslint/internal/rules/no_undef"
	"github.com/web-infra-dev/rslint/internal/rules/no_undef_init"
	"github.com/web-infra-dev/rslint/internal/rules/no_undefined"
	"github.com/web-infra-dev/rslint/internal/rules/no_underscore_dangle"
	"github.com/web-infra-dev/rslint/internal/rules/no_unexpected_multiline"
	"github.com/web-infra-dev/rslint/internal/rules/no_unmodified_loop_condition"
	"github.com/web-infra-dev/rslint/internal/rules/no_unneeded_ternary"
	"github.com/web-infra-dev/rslint/internal/rules/no_unreachable"
	"github.com/web-infra-dev/rslint/internal/rules/no_unreachable_loop"
	"github.com/web-infra-dev/rslint/internal/rules/no_unsafe_finally"
	"github.com/web-infra-dev/rslint/internal/rules/no_unsafe_negation"
	"github.com/web-infra-dev/rslint/internal/rules/no_unsafe_optional_chaining"
	"github.com/web-infra-dev/rslint/internal/rules/no_unused_expressions"
	"github.com/web-infra-dev/rslint/internal/rules/no_unused_labels"
	"github.com/web-infra-dev/rslint/internal/rules/no_unused_private_class_members"
	"github.com/web-infra-dev/rslint/internal/rules/no_unused_vars"
	"github.com/web-infra-dev/rslint/internal/rules/no_use_before_define"
	"github.com/web-infra-dev/rslint/internal/rules/no_useless_assignment"
	"github.com/web-infra-dev/rslint/internal/rules/no_useless_backreference"
	"github.com/web-infra-dev/rslint/internal/rules/no_useless_call"
	"github.com/web-infra-dev/rslint/internal/rules/no_useless_catch"
	"github.com/web-infra-dev/rslint/internal/rules/no_useless_computed_key"
	"github.com/web-infra-dev/rslint/internal/rules/no_useless_concat"
	"github.com/web-infra-dev/rslint/internal/rules/no_useless_constructor"
	"github.com/web-infra-dev/rslint/internal/rules/no_useless_escape"
	"github.com/web-infra-dev/rslint/internal/rules/no_useless_rename"
	"github.com/web-infra-dev/rslint/internal/rules/no_useless_return"
	"github.com/web-infra-dev/rslint/internal/rules/no_var"
	"github.com/web-infra-dev/rslint/internal/rules/no_void"
	"github.com/web-infra-dev/rslint/internal/rules/no_warning_comments"
	"github.com/web-infra-dev/rslint/internal/rules/no_with"
	"github.com/web-infra-dev/rslint/internal/rules/object_shorthand"
	"github.com/web-infra-dev/rslint/internal/rules/one_var"
	"github.com/web-infra-dev/rslint/internal/rules/operator_assignment"
	"github.com/web-infra-dev/rslint/internal/rules/prefer_arrow_callback"
	"github.com/web-infra-dev/rslint/internal/rules/prefer_const"
	"github.com/web-infra-dev/rslint/internal/rules/prefer_destructuring"
	"github.com/web-infra-dev/rslint/internal/rules/prefer_exponentiation_operator"
	"github.com/web-infra-dev/rslint/internal/rules/prefer_numeric_literals"
	"github.com/web-infra-dev/rslint/internal/rules/prefer_object_has_own"
	"github.com/web-infra-dev/rslint/internal/rules/prefer_object_spread"
	"github.com/web-infra-dev/rslint/internal/rules/prefer_promise_reject_errors"
	"github.com/web-infra-dev/rslint/internal/rules/prefer_regex_literals"
	"github.com/web-infra-dev/rslint/internal/rules/prefer_rest_params"
	"github.com/web-infra-dev/rslint/internal/rules/prefer_spread"
	"github.com/web-infra-dev/rslint/internal/rules/prefer_template"
	"github.com/web-infra-dev/rslint/internal/rules/preserve_caught_error"
	"github.com/web-infra-dev/rslint/internal/rules/radix"
	"github.com/web-infra-dev/rslint/internal/rules/require_atomic_updates"
	"github.com/web-infra-dev/rslint/internal/rules/require_await"
	"github.com/web-infra-dev/rslint/internal/rules/require_yield"
	"github.com/web-infra-dev/rslint/internal/rules/sort_imports"
	"github.com/web-infra-dev/rslint/internal/rules/sort_keys"
	"github.com/web-infra-dev/rslint/internal/rules/sort_vars"
	"github.com/web-infra-dev/rslint/internal/rules/strict"
	"github.com/web-infra-dev/rslint/internal/rules/symbol_description"
	"github.com/web-infra-dev/rslint/internal/rules/unicode_bom"
	"github.com/web-infra-dev/rslint/internal/rules/use_isnan"
	"github.com/web-infra-dev/rslint/internal/rules/valid_typeof"
	"github.com/web-infra-dev/rslint/internal/rules/vars_on_top"
	"github.com/web-infra-dev/rslint/internal/rules/yoda"
)

var allRuleCatalog = sync.OnceValue(func() *rule.Catalog {
	return rule.NewCatalog(allRules()...)
})

func allRules() []rule.Rule {
	var implementedRules []rule.Rule
	implementedRules = append(implementedRules, typescriptPlugin.GetAllRules()...)
	implementedRules = append(implementedRules, importPlugin.GetAllRules()...)
	implementedRules = append(implementedRules, reactPlugin.GetAllRules()...)
	implementedRules = append(implementedRules, reactHooksPlugin.GetAllRules()...)
	implementedRules = append(implementedRules, jestPlugin.GetAllRules()...)
	implementedRules = append(implementedRules, rstestPlugin.GetAllRules()...)
	implementedRules = append(implementedRules, jsxA11yPlugin.GetAllRules()...)
	implementedRules = append(implementedRules, promisePlugin.GetAllRules()...)
	implementedRules = append(implementedRules, unicornPlugin.GetAllRules()...)
	implementedRules = append(implementedRules, coreRules()...)
	return implementedRules
}

// All returns the shared immutable catalog containing every rule implemented
// in Go. It is safe to share across concurrent lint runs.
func All() *rule.Catalog {
	return allRuleCatalog()
}

func coreRules() []rule.Rule {
	return []rule.Rule{
		accessor_pairs.AccessorPairsRule,
		array_callback_return.ArrayCallbackReturnRule,
		arrow_body_style.ArrowBodyStyleRule,
		block_scoped_var.BlockScopedVarRule,
		capitalized_comments.CapitalizedCommentsRule,
		class_methods_use_this.ClassMethodsUseThisRule,
		complexity.ComplexityRule,
		consistent_return.ConsistentReturnRule,
		consistent_this.ConsistentThisRule,
		constructor_super.ConstructorSuperRule,
		curly.CurlyRule,
		default_case.DefaultCaseRule,
		default_case_last.DefaultCaseLastRule,
		default_param_last.DefaultParamLastRule,
		dot_notation.DotNotationRule,
		for_direction.ForDirectionRule,
		func_name_matching.FuncNameMatchingRule,
		func_names.FuncNamesRule,
		getter_return.GetterReturnRule,
		guard_for_in.GuardForInRule,
		id_length.IdLengthRule,
		init_declarations.InitDeclarationsRule,
		max_classes_per_file.MaxClassesPerFileRule,
		max_depth.MaxDepthRule,
		max_lines.MaxLinesRule,
		max_lines_per_function.MaxLinesPerFunctionRule,
		max_nested_callbacks.MaxNestedCallbacksRule,
		max_params.MaxParamsRule,
		max_statements.MaxStatementsRule,
		new_cap.NewCapRule,
		no_alert.NoAlertRule,
		no_array_constructor.NoArrayConstructorRule,
		no_async_promise_executor.NoAsyncPromiseExecutorRule,
		no_await_in_loop.NoAwaitInLoopRule,
		no_bitwise.NoBitwiseRule,
		no_caller.NoCallerRule,
		no_case_declarations.NoCaseDeclarationsRule,
		no_class_assign.NoClassAssignRule,
		no_compare_neg_zero.NoCompareNegZeroRule,
		no_cond_assign.NoCondAssignRule,
		no_console.NoConsoleRule,
		no_const_assign.NoConstAssignRule,
		no_constant_binary_expression.NoConstantBinaryExpressionRule,
		no_constant_condition.NoConstantConditionRule,
		no_constructor_return.NoConstructorReturnRule,
		no_continue.NoContinueRule,
		no_control_regex.NoControlRegexRule,
		no_debugger.NoDebuggerRule,
		no_delete_var.NoDeleteVarRule,
		no_div_regex.NoDivRegexRule,
		no_dupe_args.NoDupeArgsRule,
		no_dupe_class_members.NoDupeClassMembersRule,
		no_dupe_keys.NoDupeKeysRule,
		no_duplicate_case.NoDuplicateCaseRule,
		no_duplicate_imports.NoDuplicateImportsRule,
		no_else_return.NoElseReturnRule,
		no_empty.NoEmptyRule,
		no_empty_function.NoEmptyFunctionRule,
		no_empty_pattern.NoEmptyPatternRule,
		no_empty_static_block.NoEmptyStaticBlockRule,
		no_eq_null.NoEqNullRule,
		no_eval.NoEvalRule,
		no_ex_assign.NoExAssignRule,
		no_extend_native.NoExtendNativeRule,
		no_extra_bind.NoExtraBindRule,
		no_extra_label.NoExtraLabelRule,
		no_label_var.NoLabelVarRule,
		no_labels.NoLabelsRule,
		no_func_assign.NoFuncAssignRule,
		no_global_assign.NoGlobalAssignRule,
		no_implicit_coercion.NoImplicitCoercionRule,
		no_implied_eval.NoImpliedEvalRule,
		no_import_assign.NoImportAssignRule,
		no_inline_comments.NoInlineCommentsRule,
		no_inner_declarations.NoInnerDeclarationsRule,
		no_irregular_whitespace.NoIrregularWhitespaceRule,
		no_lone_blocks.NoLoneBlocksRule,
		no_lonely_if.NoLonelyIfRule,
		no_loop_func.NoLoopFuncRule,
		no_loss_of_precision.NoLossOfPrecisionRule,
		no_magic_numbers.NoMagicNumbersRule,
		no_misleading_character_class.NoMisleadingCharacterClassRule,
		no_new.NoNewRule,
		no_new_func.NoNewFuncRule,
		no_new_native_nonconstructor.NoNewNativeNonconstructorRule,
		no_new_wrappers.NoNewWrappersRule,
		no_object_constructor.NoObjectConstructorRule,
		no_restricted_exports.NoRestrictedExportsRule,
		no_restricted_globals.NoRestrictedGlobalsRule,
		no_restricted_imports.NoRestrictedImportsRule,
		no_restricted_properties.NoRestrictedPropertiesRule,
		no_restricted_syntax.NoRestrictedSyntaxRule,
		no_multi_assign.NoMultiAssignRule,
		no_multi_str.NoMultiStrRule,
		no_negated_condition.NoNegatedConditionRule,
		no_nested_ternary.NoNestedTernaryRule,
		no_nonoctal_decimal_escape.NoNonoctalDecimalEscapeRule,
		no_octal.NoOctalRule,
		no_octal_escape.NoOctalEscapeRule,
		no_param_reassign.NoParamReassignRule,
		no_plusplus.NoPlusplusRule,
		no_promise_executor_return.NoPromiseExecutorReturnRule,
		no_proto.NoProtoRule,
		no_redeclare.NoRedeclareRule,
		radix.RadixRule,
		no_regex_spaces.NoRegexSpacesRule,
		no_return_assign.NoReturnAssignRule,
		no_script_url.NoScriptUrlRule,
		no_self_assign.NoSelfAssignRule,
		no_self_compare.NoSelfCompareRule,
		no_sequences.NoSequencesRule,
		no_shadow.NoShadowRule,
		no_shadow_restricted_names.NoShadowRestrictedNamesRule,
		strict.StrictRule,
		no_template_curly_in_string.NoTemplateCurlyInStringRule,
		no_ternary.NoTernaryRule,
		no_useless_computed_key.NoUselessComputedKeyRule,
		no_useless_concat.NoUselessConcatRule,
		no_sparse_arrays.NoSparseArraysRule,
		no_extra_boolean_cast.NoExtraBooleanCastRule,
		no_unneeded_ternary.NoUnneededTernaryRule,
		no_undef.NoUndefRule,
		no_undef_init.NoUndefInitRule,
		no_undefined.NoUndefinedRule,
		no_underscore_dangle.NoUnderscoreDangleRule,
		no_unassigned_vars.NoUnassignedVarsRule,
		prefer_const.PreferConstRule,
		prefer_destructuring.PreferDestructuringRule,
		prefer_exponentiation_operator.PreferExponentiationOperatorRule,
		prefer_numeric_literals.PreferNumericLiteralsRule,
		prefer_object_has_own.PreferObjectHasOwnRule,
		prefer_object_spread.PreferObjectSpreadRule,
		prefer_promise_reject_errors.PreferPromiseRejectErrorsRule,
		preserve_caught_error.PreserveCaughtErrorRule,
		prefer_regex_literals.PreferRegexLiteralsRule,
		prefer_template.PreferTemplateRule,
		no_this_before_super.NoThisBeforeSuperRule,
		no_var.NoVarRule,
		vars_on_top.VarsOnTopRule,
		no_void.NoVoidRule,
		no_warning_comments.NoWarningCommentsRule,
		no_with.NoWithRule,
		prefer_rest_params.PreferRestParamsRule,
		prefer_spread.PreferSpreadRule,
		no_empty_character_class.NoEmptyCharacterClassRule,
		no_invalid_regexp.NoInvalidRegexpRule,
		no_invalid_this.NoInvalidThisRule,
		no_iterator.NoIteratorRule,
		no_setter_return.NoSetterReturnRule,
		no_unsafe_negation.NoUnsafeNegationRule,
		no_obj_calls.NoObjCallsRule,
		no_new_object.NoNewObjectRule,
		no_new_symbol.NoNewSymbolRule,
		use_isnan.UseIsNaNRule,
		eqeqeq.EqeqeqRule,
		no_fallthrough.NoFallthroughRule,
		valid_typeof.ValidTypeofRule,
		no_unsafe_optional_chaining.NoUnsafeOptionalChainingRule,
		no_unsafe_finally.NoUnsafeFinallyRule,
		no_unmodified_loop_condition.NoUnmodifiedLoopConditionRule,
		no_unreachable.NoUnreachableRule,
		no_unreachable_loop.NoUnreachableLoopRule,
		require_atomic_updates.RequireAtomicUpdatesRule,
		object_shorthand.ObjectShorthandRule,
		no_unused_expressions.NoUnusedExpressionsRule,
		no_unused_labels.NoUnusedLabelsRule,
		no_unused_private_class_members.NoUnusedPrivateClassMembersRule,
		no_unused_vars.NoUnusedVarsRule,
		no_use_before_define.NoUseBeforeDefineRule,
		one_var.OneVarRule,
		prefer_arrow_callback.PreferArrowCallbackRule,
		no_dupe_else_if.NoDupeElseIfRule,
		no_throw_literal.NoThrowLiteralRule,
		no_useless_assignment.NoUselessAssignmentRule,
		no_useless_backreference.NoUselessBackreferenceRule,
		no_useless_call.NoUselessCallRule,
		no_useless_catch.NoUselessCatchRule,
		no_useless_escape.NoUselessEscapeRule,
		no_useless_rename.NoUselessRenameRule,
		no_useless_return.NoUselessReturnRule,
		no_useless_constructor.NoUselessConstructorRule,
		no_prototype_builtins.NoPrototypeBuiltinsRule,
		require_await.RequireAwaitRule,
		require_yield.RequireYieldRule,
		symbol_description.SymbolDescriptionRule,
		no_unexpected_multiline.NoUnexpectedMultilineRule,
		unicode_bom.UnicodeBomRule,
		operator_assignment.OperatorAssignmentRule,
		sort_imports.SortImportsRule,
		sort_keys.SortKeysRule,
		sort_vars.SortVarsRule,
		yoda.YodaRule,
	}
}
