
// Code generated by tools/gen_shims. DO NOT EDIT.

package jsonrpc

import "github.com/microsoft/typescript-go/internal/jsonrpc"
import "io"
import _ "unsafe"

const CodeInternalError = jsonrpc.CodeInternalError
const CodeInvalidParams = jsonrpc.CodeInvalidParams
const CodeInvalidRequest = jsonrpc.CodeInvalidRequest
const CodeMethodNotFound = jsonrpc.CodeMethodNotFound
const CodeParseError = jsonrpc.CodeParseError
var ErrInvalidContentLength = jsonrpc.ErrInvalidContentLength
var ErrInvalidHeader = jsonrpc.ErrInvalidHeader
var ErrInvalidJSONRPCVersion = jsonrpc.ErrInvalidJSONRPCVersion
var ErrNoContentLength = jsonrpc.ErrNoContentLength
type ID = jsonrpc.ID
type IntegerOrString = jsonrpc.IntegerOrString
type JSONRPCVersion = jsonrpc.JSONRPCVersion
type Message = jsonrpc.Message
type MessageKind = jsonrpc.MessageKind
const MessageKindNotification = jsonrpc.MessageKindNotification
const MessageKindRequest = jsonrpc.MessageKindRequest
const MessageKindResponse = jsonrpc.MessageKindResponse
//go:linkname NewID github.com/microsoft/typescript-go/internal/jsonrpc.NewID
func NewID(rawValue jsonrpc.IntegerOrString) *jsonrpc.ID
//go:linkname NewIDInt github.com/microsoft/typescript-go/internal/jsonrpc.NewIDInt
func NewIDInt(i int32) *jsonrpc.ID
//go:linkname NewIDString github.com/microsoft/typescript-go/internal/jsonrpc.NewIDString
func NewIDString(str string) *jsonrpc.ID
//go:linkname NewReader github.com/microsoft/typescript-go/internal/jsonrpc.NewReader
func NewReader(r io.Reader) *jsonrpc.Reader
//go:linkname NewWriter github.com/microsoft/typescript-go/internal/jsonrpc.NewWriter
func NewWriter(w io.Writer) *jsonrpc.Writer
type Reader = jsonrpc.Reader
type RequestMessage = jsonrpc.RequestMessage
type ResponseError = jsonrpc.ResponseError
type ResponseMessage = jsonrpc.ResponseMessage
type Writer = jsonrpc.Writer
