/**
 * Conformance: @stylistic/eslint-plugin (spacing) mounted in rslint via `plugins`
 * must report identically to ESLint v10. Representative triggers from the
 * upstream suite; each verified to reproduce ESLint v10 byte-for-byte.
 */
import { runConformanceSuite } from '../conformance.js';
import type { DiffCase } from '../harness.js';

const CASES: DiffCase[] = [
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'array-bracket-spacing',
    code: 'var foo = [ ]',
    options: ['never'],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'array-bracket-spacing',
    code: 'var [x,y] = y',
    options: ['always'],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'array-bracket-spacing',
    code: "var foo = [ { 'bar': 'baz' }, 1,  5];",
    options: ['always', { objectsInArrays: false }],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'arrow-spacing',
    code: 'a=>a',
    options: [{ after: true, before: true }],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'arrow-spacing',
    code: '(a)=>{}',
    options: [{ after: true, before: true }],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'arrow-spacing',
    code: 'a=> a',
    options: [{ after: false, before: true }],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'block-spacing',
    code: '{foo();}',
    options: ['always'],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'block-spacing',
    code: 'if (a) {foo();}',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'block-spacing',
    code: '{ foo(); }',
    options: ['never'],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'comma-spacing',
    code: 'a(b,c)',
    options: [{ before: true, after: true }],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'comma-spacing',
    code: 'var arr = [1 , 2];',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'comma-spacing',
    code: 'var a = 1 ,b = 2;',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'computed-property-spacing',
    code: 'var foo = obj[ 1];',
    options: ['always'],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'computed-property-spacing',
    code: 'var foo = obj[ 1];',
    options: ['never'],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'computed-property-spacing',
    code: 'obj[ foo ]',
    options: ['never'],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'function-call-spacing',
    code: 'f ();',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'function-call-spacing',
    code: 'f();',
    options: ['always'],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'function-call-spacing',
    code: 'f\n();',
    options: ['always'],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'function-call-spacing',
    code: 'func ?. ()',
    options: ['never'],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'generator-star-spacing',
    code: 'function*foo(){}',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'generator-star-spacing',
    code: 'function* foo(arg1, arg2){}',
    options: ['before'],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'generator-star-spacing',
    code: 'var foo = {* foo(){} };',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'generator-star-spacing',
    code: 'class Foo { static* foo(){} }',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'key-spacing',
    code: "var a ={'key' : value };",
    options: [{ beforeColon: false, afterColon: false }],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'key-spacing',
    code: "var a ={'key' :value };",
    options: [{ beforeColon: false, afterColon: true }],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'key-spacing',
    code: "var bat = function() { return { foo:bar, 'key': value }; };",
    options: [{ beforeColon: false, afterColon: false }],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'keyword-spacing',
    code: 'import { "a"as b } from "foo"',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'keyword-spacing',
    code: 'import{ "a" as b }from"foo"',
    options: [{ before: false, after: false }],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'keyword-spacing',
    code: 'let a; export { a as"b" };',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'keyword-spacing',
    code: 'export { "a"as"b" } from "foo";',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'no-mixed-spaces-and-tabs',
    code: 'function add(x, y) {\n\t return x + y;\n}',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'no-mixed-spaces-and-tabs',
    code: '\t // comment',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'no-mixed-spaces-and-tabs',
    code: '\tvar x = 5,\n  \t  y = 2;',
    options: ['smart-tabs'],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'no-mixed-spaces-and-tabs',
    code: '   \tfoo',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'no-multi-spaces',
    code: 'function foo(a,  b) {}',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'no-multi-spaces',
    code: 'var a =  1',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'no-multi-spaces',
    code: 'var a = [1,  2,  3,  4]',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'no-multi-spaces',
    code: 'var x = 5;  // comment',
    options: [{ ignoreEOLComments: false }],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'no-tabs',
    code: 'function test(){\t}',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'no-tabs',
    code: '/** \t comment test */',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'no-tabs',
    code: '\t// Comment with leading tab \t and inline tab',
    options: [{ allowIndentationTabs: true }],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'no-trailing-spaces',
    code: 'var a = 5;      \n',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'no-trailing-spaces',
    code: 'var a = 5; \n b = 3; ',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'no-trailing-spaces',
    code: '     \n    var c = 1;',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'no-trailing-spaces',
    code: "var a = 'bar';  \n \n\t",
    options: [{ skipBlankLines: true }],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'no-whitespace-before-property',
    code: 'foo. bar',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'no-whitespace-before-property',
    code: 'foo .bar',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'no-whitespace-before-property',
    code: 'foo [bar]',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'no-whitespace-before-property',
    code: 'obj?. prop',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'object-curly-spacing',
    code: "import {bar} from 'foo.js';",
    options: ['always'],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'object-curly-spacing',
    code: "import { bar as y} from 'foo.js';",
    options: ['always'],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'object-curly-spacing',
    code: "import { bar} from 'foo.js';",
    options: ['always'],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'rest-spread-spacing',
    code: 'fn(... args)',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'rest-spread-spacing',
    code: 'fn(...  args)',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'rest-spread-spacing',
    code: 'fn(... args)',
    options: ['never'],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'rest-spread-spacing',
    code: 'fn(...args)',
    options: ['always'],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'semi-spacing',
    code: "var a = 'b'  ;",
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'semi-spacing',
    code: "var a = 'b' ;",
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'semi-spacing',
    code: 'while (true) { break ; }',
  },
  { pkg: '@stylistic/eslint-plugin', rule: 'semi-spacing', code: 'debugger ;' },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'space-before-blocks',
    code: 'if(a){}',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'space-before-blocks',
    code: 'if(a) {}',
    options: ['never'],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'space-before-blocks',
    code: 'function a(){}',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'space-before-blocks',
    code: 'function a() {}',
    options: ['never'],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'space-before-function-paren',
    code: 'function foo() {}',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'space-before-function-paren',
    code: 'var foo = function() {}',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'space-before-function-paren',
    code: 'var bar = function foo() {}',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'space-before-function-paren',
    code: 'var obj = { get foo() {}, set foo(val) {} };',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'space-in-parens',
    code: 'bar(baz )',
    options: ['never'],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'space-in-parens',
    code: 'bar( baz )',
    options: ['never'],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'space-in-parens',
    code: 'foo( bar)',
    options: ['always'],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'space-in-parens',
    code: 'foo(bar() )',
    options: ['never'],
  },
  { pkg: '@stylistic/eslint-plugin', rule: 'space-infix-ops', code: 'a+b' },
  { pkg: '@stylistic/eslint-plugin', rule: 'space-infix-ops', code: 'a||b' },
  { pkg: '@stylistic/eslint-plugin', rule: 'space-infix-ops', code: 'a=b' },
  { pkg: '@stylistic/eslint-plugin', rule: 'space-infix-ops', code: 'a +b' },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'space-unary-ops',
    code: 'delete(foo.bar)',
    options: [{ words: true }],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'space-unary-ops',
    code: 'delete (foo.bar)',
    options: [{ words: false }],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'space-unary-ops',
    code: 'new(Foo)',
    options: [{ words: true }],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'space-unary-ops',
    code: 'typeof(foo)',
    options: [{ words: true }],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'spaced-comment',
    code: '//An invalid comment NOT starting with space\nvar a = 1;',
    options: ['always'],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'spaced-comment',
    code: '// An invalid comment starting with space\nvar a = 2;',
    options: ['never'],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'spaced-comment',
    code: '//-=-=-=-=-=-=\n// A comment\n//-=-=-=-=-=-=',
    options: ['always', { exceptions: ['-', '=', '*', '#', '!@#'] }],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'spaced-comment',
    code: '//!<docblock style comment',
    options: ['always', { markers: ['/', '!<'] }],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'switch-colon-spacing',
    code: 'switch(a){case 0 :break;}',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'switch-colon-spacing',
    code: 'switch(a){case 0 : break;}',
    options: [{ before: false, after: false }],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'switch-colon-spacing',
    code: 'switch(a){case 0:break;}',
    options: [{ before: true, after: true }],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'switch-colon-spacing',
    code: 'switch(a){case (0) :break;}',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'template-curly-spacing',
    code: '`${ foo } ${ bar }`',
    options: ['never'],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'template-curly-spacing',
    code: '`${foo} ${bar}`',
    options: ['always'],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'template-curly-spacing',
    code: 'tag`${ foo } ${ bar }`',
    options: ['never'],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'template-curly-spacing',
    code: 'tag`${foo} ${bar}`',
    options: ['always'],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'template-tag-spacing',
    code: 'tag `name`',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'template-tag-spacing',
    code: 'tag`name`',
    options: ['always'],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'template-tag-spacing',
    code: 'new tag `name`',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'template-tag-spacing',
    code: 'tag `hello ${name}`',
    options: ['never'],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'yield-star-spacing',
    code: 'function *foo(){ yield *foo1; }',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'yield-star-spacing',
    code: 'function *foo(){ yield* foo; }',
    options: ['before'],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'yield-star-spacing',
    code: 'function *foo(){ yield*foo4; }',
    options: ['both'],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'yield-star-spacing',
    code: 'function *foo(){ yield * foo; }',
    options: ['neither'],
  },
];

const CLEAN_CASES: DiffCase[] = [
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'array-bracket-spacing',
    code: 'var foo = obj[ 1 ]',
    options: ['always'],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'array-bracket-spacing',
    code: 'var arr = [[ 1, 2 ], 2, 3, 4 ];',
    options: ['always', { arraysInArrays: false }],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'arrow-spacing',
    code: 'a => a',
    options: [{ after: true, before: true }],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'arrow-spacing',
    code: 'a=> a',
    options: [{ after: true, before: false }],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'block-spacing',
    code: '{ foo(); }',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'block-spacing',
    code: '{foo();}',
    options: ['never'],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'comma-spacing',
    code: 'var a = 1, b = 2;',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'comma-spacing',
    code: "myfunc(404, // comment\n true,/* bla bla bla */ 'hello');",
    options: [{ before: false, after: false }],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'computed-property-spacing',
    code: 'obj[foo]',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'computed-property-spacing',
    code: 'obj[ foo ]',
    options: ['always'],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'function-call-spacing',
    code: 'f(a, b);',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'function-call-spacing',
    code: 'f ();',
    options: ['always'],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'generator-star-spacing',
    code: 'function *foo(){}',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'generator-star-spacing',
    code: 'function* foo(){}',
    options: ['after'],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'key-spacing',
    code: 'var obj = { key: value };',
    options: [{}],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'key-spacing',
    code: 'var foo = { a: bar };',
    options: [{ beforeColon: false, afterColon: true }],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'keyword-spacing',
    code: 'import { a as b } from "foo"',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'keyword-spacing',
    code: 'import{ a as b }from"foo"',
    options: [{ before: false, after: false }],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'no-mixed-spaces-and-tabs',
    code: '\tvar x = 5;',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'no-mixed-spaces-and-tabs',
    code: '\tvar x = 5,\n\t    y = 2;',
    options: ['smart-tabs'],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'no-multi-spaces',
    code: 'var a = 1;',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'no-multi-spaces',
    code: 'var  answer = 6 *  7;',
    options: [
      { exceptions: { VariableDeclaration: true, BinaryExpression: true } },
    ],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'no-tabs',
    code: 'function test(){\n}',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'no-tabs',
    code: '\tdoSomething();',
    options: [{ allowIndentationTabs: true }],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'no-trailing-spaces',
    code: 'var a = 5,\n    b = 3;',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'no-trailing-spaces',
    code: '// Trailing comment test. ',
    options: [{ ignoreComments: true }],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'no-whitespace-before-property',
    code: 'foo.bar',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'no-whitespace-before-property',
    code: 'obj?.prop',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'object-curly-spacing',
    code: 'var obj = { foo: bar, baz: qux };',
    options: ['always'],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'object-curly-spacing',
    code: 'var obj = {foo: bar, baz: qux};',
    options: ['never'],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'rest-spread-spacing',
    code: 'fn(...args)',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'rest-spread-spacing',
    code: 'fn(... args)',
    options: ['always'],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'semi-spacing',
    code: "var a = 'b';",
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'semi-spacing',
    code: 'while (true) { break; }',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'space-before-blocks',
    code: 'if(a) {}',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'space-before-blocks',
    code: 'if(a){}',
    options: ['never'],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'space-before-function-paren',
    code: 'function foo () {}',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'space-before-function-paren',
    code: 'var foo = function () {}',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'space-in-parens',
    code: 'foo()',
    options: ['never'],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'space-in-parens',
    code: 'foo( bar )',
    options: ['always'],
  },
  { pkg: '@stylistic/eslint-plugin', rule: 'space-infix-ops', code: 'a + b' },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'space-infix-ops',
    code: '(a) + (b)',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'space-unary-ops',
    code: '++this.a',
    options: [{ words: true }],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'space-unary-ops',
    code: 'this.a++',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'spaced-comment',
    code: '// A valid comment starting with space\nvar a = 1;',
    options: ['always'],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'spaced-comment',
    code: '//A valid comment NOT starting with space\nvar a = 2;',
    options: ['never'],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'switch-colon-spacing',
    code: 'switch(a){case 0: break;}',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'switch-colon-spacing',
    code: 'switch(a){case 0 : break;}',
    options: [{ before: true, after: true }],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'template-curly-spacing',
    code: '`${foo} ${bar}`',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'template-curly-spacing',
    code: '`${ foo } ${ bar } ${\n  baz\n}`',
    options: ['always'],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'template-tag-spacing',
    code: 'tag`name`',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'template-tag-spacing',
    code: 'tag `name`',
    options: ['always'],
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'yield-star-spacing',
    code: 'function *foo(){ yield* foo; }',
  },
  {
    pkg: '@stylistic/eslint-plugin',
    rule: 'yield-star-spacing',
    code: 'function *foo(){ yield *foo; }',
    options: ['before'],
  },
];

runConformanceSuite('@stylistic/eslint-plugin', CASES, CLEAN_CASES);
