package no_redundant_roles

// ariaRolesSet is the set of valid ARIA role names — the keys of
// aria-query's `roles` map. Used as the membership oracle by
// [getImplicitRole] (filter the per-element implicit-role output) and
// [getExplicitRole] (validate the user-provided role attribute) so
// that only ARIA-recognized roles can match.
//
// Source: https://github.com/A11yance/aria-query/blob/main/src/etc/roles
// (sorted by name). The full set is mirrored byte-for-byte —
// including:
//
//   - WAI-ARIA abstract roles (the 12 superclasses flagged
//     `abstract: true` in aria-query: roletype, structure, widget,
//     window, command, composite, input, landmark, range, section,
//     sectionhead, select). Upstream's `rolesMap.has` returns true for
//     these; on this rule they have no observable effect (no HTML
//     element's implicit role is abstract), but keeping them in the set
//     preserves the rolesMap shape for any future a11y rule that
//     reuses this oracle and DOES care about abstract roles
//     (e.g. `aria-role`).
//   - DPub digital-publishing roles (`doc-*`).
//   - SVG Accessibility API Mappings graphics roles (`graphics-*`).
var ariaRolesSet = map[string]struct{}{
	"alert":                {},
	"alertdialog":          {},
	"application":          {},
	"article":              {},
	"banner":               {},
	"blockquote":           {},
	"button":               {},
	"caption":              {},
	"cell":                 {},
	"checkbox":             {},
	"code":                 {},
	"columnheader":         {},
	"combobox":             {},
	"command":              {},
	"complementary":        {},
	"composite":            {},
	"contentinfo":          {},
	"definition":           {},
	"deletion":             {},
	"dialog":               {},
	"directory":            {},
	"doc-abstract":         {},
	"doc-acknowledgments":  {},
	"doc-afterword":        {},
	"doc-appendix":         {},
	"doc-backlink":         {},
	"doc-biblioentry":      {},
	"doc-bibliography":     {},
	"doc-biblioref":        {},
	"doc-chapter":          {},
	"doc-colophon":         {},
	"doc-conclusion":       {},
	"doc-cover":            {},
	"doc-credit":           {},
	"doc-credits":          {},
	"doc-dedication":       {},
	"doc-endnote":          {},
	"doc-endnotes":         {},
	"doc-epigraph":         {},
	"doc-epilogue":         {},
	"doc-errata":           {},
	"doc-example":          {},
	"doc-footnote":         {},
	"doc-foreword":         {},
	"doc-glossary":         {},
	"doc-glossref":         {},
	"doc-index":            {},
	"doc-introduction":     {},
	"doc-noteref":          {},
	"doc-notice":           {},
	"doc-pagebreak":        {},
	"doc-pagefooter":       {},
	"doc-pageheader":       {},
	"doc-pagelist":         {},
	"doc-part":             {},
	"doc-preface":          {},
	"doc-prologue":         {},
	"doc-pullquote":        {},
	"doc-qna":              {},
	"doc-subtitle":         {},
	"doc-tip":              {},
	"doc-toc":              {},
	"document":             {},
	"emphasis":             {},
	"feed":                 {},
	"figure":               {},
	"form":                 {},
	"generic":              {},
	"graphics-document":    {},
	"graphics-object":      {},
	"graphics-symbol":      {},
	"grid":                 {},
	"gridcell":             {},
	"group":                {},
	"heading":              {},
	"img":                  {},
	"input":                {},
	"insertion":            {},
	"landmark":             {},
	"link":                 {},
	"list":                 {},
	"listbox":              {},
	"listitem":             {},
	"log":                  {},
	"main":                 {},
	"mark":                 {},
	"marquee":              {},
	"math":                 {},
	"menu":                 {},
	"menubar":              {},
	"menuitem":             {},
	"menuitemcheckbox":     {},
	"menuitemradio":        {},
	"meter":                {},
	"navigation":           {},
	"none":                 {},
	"note":                 {},
	"option":               {},
	"paragraph":            {},
	"presentation":         {},
	"progressbar":          {},
	"radio":                {},
	"radiogroup":           {},
	"range":                {},
	"region":               {},
	"roletype":             {},
	"row":                  {},
	"rowgroup":             {},
	"rowheader":            {},
	"scrollbar":            {},
	"search":               {},
	"searchbox":            {},
	"section":              {},
	"sectionhead":          {},
	"select":               {},
	"separator":            {},
	"slider":               {},
	"spinbutton":           {},
	"status":               {},
	"strong":               {},
	"structure":            {},
	"subscript":            {},
	"superscript":          {},
	"switch":               {},
	"tab":                  {},
	"table":                {},
	"tablist":              {},
	"tabpanel":             {},
	"term":                 {},
	"textbox":              {},
	"time":                 {},
	"timer":                {},
	"toolbar":              {},
	"tooltip":              {},
	"tree":                 {},
	"treegrid":             {},
	"treeitem":             {},
	"widget":               {},
	"window":               {},
}
