// This file migrates every test case from eslint-plugin-react v7.37.5's
// hook-use-state suite. rslint-specific shape and branch tests live in
// hook_use_state_extras_test.go.
package hook_use_state

import (
	"testing"

	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/fixtures"
	"github.com/web-infra-dev/rslint/internal/rule_tester"
)

func TestHookUseStateUpstream(t *testing.T) {
	rule_tester.RunRuleTester(
		fixtures.GetRootDir(),
		"tsconfig.json",
		t,
		&HookUseStateRule,
		[]rule_tester.ValidTestCase{
			{Code: "\n        import { useState } from 'react'\n        function useColor() {\n          const [color, setColor] = useState()\n          return [color, setColor]\n        }\n      ", Tsx: true},
			{Code: "\n        import { useState } from 'react'\n        function useRGB() {\n          const [rgb, setRGB] = useState()\n          return [rgb, setRGB]\n        }\n      ", Tsx: true},
			{Code: "\n        import { useState } from 'react'\n        function useRGBValue() {\n          const [rgbValue, setRGBValue] = useState()\n          return [rgbValue, setRGBValue]\n        }\n      ", Tsx: true},
			{Code: "\n        import { useState } from 'react'\n        function useCustomColorValue() {\n          const [customColorValue, setCustomColorValue] = useState()\n          return [customColorValue, setCustomColorValue]\n        }\n      ", Tsx: true},
			{Code: "\n        import { useState } from 'react'\n        function useColor() {\n          const [color, setColor] = useState('#ffffff')\n          return [color, setColor]\n        }\n      ", Tsx: true},
			{Code: "\n        import React from 'react'\n        function useColor() {\n          const [color, setColor] = React.useState()\n          return [color, setColor]\n        }\n      ", Tsx: true},
			{Code: "\n        import { useState } from 'react'\n        function useColor() {\n          const [color1, setColor1] = useState()\n          return [color1, setColor1]\n        }\n      ", Tsx: true},
			{Code: "useState()", Tsx: true},
			{Code: "const result = useState()", Tsx: true},
			{Code: "const [color, setFlavor] = useState()", Tsx: true},
			{Code: "\n        import React from 'react'\n        import useState from 'someOtherUseState'\n        const [color, setFlavor] = useState()\n      ", Tsx: true},
			{Code: "\n        import { useRef } from 'react'\n        const result = useState()\n      ", Tsx: true},
			{Code: "\n        import { useState as useStateAlternativeName } from 'react'\n        function useColor() {\n          const [color, setColor] = useStateAlternativeName()\n          return [color, setColor]\n        }\n      ", Tsx: true},
			{Code: "const result = React.useState()", Tsx: true},
			{Code: "\n        import { useState } from 'react'\n        function useColor() {\n          return useState()\n        }\n      ", Tsx: true},
			{Code: "\n        import { useState } from 'react'\n        function useColor() {\n          function useState() { // shadows React's useState\n            return null\n          }\n\n          const result = useState()\n        }\n      ", Tsx: true},
			{Code: "\n        import React from 'react'\n        function useColor() {\n          const React = {\n            useState: () => {\n              return null\n            }\n          }\n\n          const result = React.useState()\n        }\n      ", Tsx: true},
			{Code: "\n        import { useState } from 'react';\n        function useColor() {\n          const [color, setColor] = useState<string>()\n          return [color, setColor]\n        }\n      ", Tsx: true},
			{Code: "\n        import { useState } from 'react';\n        function useColor() {\n          const [color, setColor] = useState<string>('#ffffff')\n          return [color, setColor]\n        }\n      ", Tsx: true},
			{Code: "\n        import { useState } from 'react';\n\n        const [{foo, bar, baz}, setFooBarBaz] = useState({foo: \"bbb\", bar: \"aaa\", baz: \"qqq\"})\n      ", Tsx: true, Options: []any{map[string]any{"allowDestructuredState": true}}},
			{Code: "\n        import { useState } from 'react';\n\n        const [[index, value], setValueWithIndex] = useState([0, \"hello\"])\n      ", Tsx: true, Options: []any{map[string]any{"allowDestructuredState": true}}},
		},
		[]rule_tester.InvalidTestCase{
			{Code: "\n        import { useState } from 'react';\n        const result = useState()\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "useStateErrorMessage", Message: "useState call is not destructured into value + setter pair"}}},
			{Code: "\n        import { useState } from 'react';\n        function useColor() {\n          const result = useState()\n          return result\n        }\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "useStateErrorMessage", Message: "useState call is not destructured into value + setter pair"}}},
			{Code: "\n        import { useState as useStateAlternativeName } from 'react'\n        function useColor() {\n          const result = useStateAlternativeName()\n          return result\n        }\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "useStateErrorMessage", Message: "useState call is not destructured into value + setter pair"}}},
			{Code: "\n        import React from 'react'\n        function useColor() {\n          const result = React.useState()\n          return result\n        }\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "useStateErrorMessage", Message: "useState call is not destructured into value + setter pair"}}},
			{Code: "\n        import ReactAlternative from 'react'\n        function useColor() {\n          const result = ReactAlternative.useState()\n          return result\n        }\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "useStateErrorMessage", Message: "useState call is not destructured into value + setter pair"}}},
			{Code: "\n        import { useState } from 'react'\n        function useColor() {\n          const result = useState()\n          return result\n        }\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "useStateErrorMessage", Message: "useState call is not destructured into value + setter pair"}}},
			{Code: "\n        import { useState } from 'react'\n        function useColor() {\n          const [, , extra1] = useState()\n        }\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "useStateErrorMessage", Message: "useState call is not destructured into value + setter pair"}}},
			{Code: "\n        import { useState } from 'react'\n        function useColor() {\n          const [, setColor] = useState()\n        }\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "useStateErrorMessage", Message: "useState call is not destructured into value + setter pair"}}},
			{Code: "\n        import { useState } from 'react'\n        function useColor() {\n          const { color } = useState()\n        }\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "useStateErrorMessage", Message: "useState call is not destructured into value + setter pair"}}},
			{Code: "\n        import { useState } from 'react'\n        function useColor() {\n          const [] = useState()\n        }\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "useStateErrorMessage", Message: "useState call is not destructured into value + setter pair"}}},
			{Code: "\n        import { useState } from 'react'\n        function useColor() {\n          const [, , , ,] = useState()\n        }\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "useStateErrorMessage", Message: "useState call is not destructured into value + setter pair"}}},
			{Code: "\n        import { useState } from 'react'\n        function useColor() {\n          const [color] = useState()\n        }\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "useStateErrorMessage", Message: "useState call is not destructured into value + setter pair", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestPair", Output: "\n        import { useState } from 'react'\n        function useColor() {\n          const [color, setColor] = useState()\n        }\n      "}}}}},
			{Code: "\n        import { useState } from 'react'\n        function useColor(initialColor) {\n          const [color] = useState(initialColor)\n        }\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "useStateErrorMessage", Message: "useState call is not destructured into value + setter pair", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestMemo", Output: "\n        import { useState, useMemo } from 'react'\n        function useColor(initialColor) {\n          const color = useMemo(() => initialColor, [])\n        }\n      "}, {MessageId: "suggestPair", Output: "\n        import { useState } from 'react'\n        function useColor(initialColor) {\n          const [color, setColor] = useState(initialColor)\n        }\n      "}}}}},
			{Code: "\n        import { useState, useMemo as useMemoAlternative } from 'react'\n        function useColor(initialColor) {\n          const [color] = useState(initialColor)\n        }\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "useStateErrorMessage", Message: "useState call is not destructured into value + setter pair", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestMemo", Output: "\n        import { useState, useMemo as useMemoAlternative } from 'react'\n        function useColor(initialColor) {\n          const color = useMemoAlternative(() => initialColor, [])\n        }\n      "}, {MessageId: "suggestPair", Output: "\n        import { useState, useMemo as useMemoAlternative } from 'react'\n        function useColor(initialColor) {\n          const [color, setColor] = useState(initialColor)\n        }\n      "}}}}},
			{Code: "\n        import React from 'react'\n        function useColor(initialColor) {\n          const [color] = React.useState(initialColor)\n        }\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "useStateErrorMessage", Message: "useState call is not destructured into value + setter pair", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestMemo", Output: "\n        import React from 'react'\n        function useColor(initialColor) {\n          const color = React.useMemo(() => initialColor, [])\n        }\n      "}, {MessageId: "suggestPair", Output: "\n        import React from 'react'\n        function useColor(initialColor) {\n          const [color, setColor] = React.useState(initialColor)\n        }\n      "}}}}},
			{Code: "\n        import { useState } from 'react'\n        function useColor() {\n          const [color, , extra1] = useState()\n          return [color]\n        }\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "useStateErrorMessage", Message: "useState call is not destructured into value + setter pair", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestPair", Output: "\n        import { useState } from 'react'\n        function useColor() {\n          const [color, setColor] = useState()\n          return [color]\n        }\n      "}}}}},
			{Code: "\n        import { useState } from 'react'\n        function useColor() {\n          const [color, setColor, extra1, extra2, extra3] = useState()\n          return [color, setColor]\n        }\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "useStateErrorMessage", Message: "useState call is not destructured into value + setter pair", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestPair", Output: "\n        import { useState } from 'react'\n        function useColor() {\n          const [color, setColor] = useState()\n          return [color, setColor]\n        }\n      "}}}}},
			{Code: "\n        import { useState } from 'react'\n        const [, makeColor] = useState()\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "useStateErrorMessage", Message: "useState call is not destructured into value + setter pair"}}},
			{Code: "\n        import { useState } from 'react'\n        const [color, setFlavor, extraneous] = useState()\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "useStateErrorMessage", Message: "useState call is not destructured into value + setter pair", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestPair", Output: "\n        import { useState } from 'react'\n        const [color, setColor] = useState()\n      "}}}}},
			{Code: "\n        import { useState } from 'react'\n        const [color, setFlavor] = useState()\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "useStateErrorMessage", Message: "useState call is not destructured into value + setter pair", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestPair", Output: "\n        import { useState } from 'react'\n        const [color, setColor] = useState()\n      "}}}}},
			{Code: "\n        import { useState } from 'react';\n\n        const [{foo, bar, baz}, setFooBarBaz] = useState({foo: \"bbb\", bar: \"aaa\", baz: \"qqq\"})\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "useStateErrorMessageOrAddOption", Message: "useState call is not destructured into value + setter pair (you can allow destructuring by enabling \"allowDestructuredState\" option)"}}},
			{Code: "\n        import { useState } from 'react';\n\n        const [[index, value], setValueWithIndex] = useState([0, \"hello\"])\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "useStateErrorMessageOrAddOption", Message: "useState call is not destructured into value + setter pair (you can allow destructuring by enabling \"allowDestructuredState\" option)"}}},
			{Code: "\n        import { useState } from 'react';\n\n        const [{foo, bar, baz}, {setFooBarBaz}] = useState({foo: \"bbb\", bar: \"aaa\", baz: \"qqq\"})\n      ", Tsx: true, Options: []any{map[string]any{"allowDestructuredState": true}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "useStateErrorMessage", Message: "useState call is not destructured into value + setter pair"}}},
			{Code: "\n        import { useState } from 'react'\n        const [color, setFlavor] = useState<string>()\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "useStateErrorMessage", Message: "useState call is not destructured into value + setter pair", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestPair", Output: "\n        import { useState } from 'react'\n        const [color, setColor] = useState<string>()\n      "}}}}},
			{Code: "\n        import { useState } from 'react'\n        function useColor() {\n          const [color, setFlavor] = useState<string>('#ffffff')\n          return [color, setFlavor]\n        }\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "useStateErrorMessage", Message: "useState call is not destructured into value + setter pair", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestPair", Output: "\n        import { useState } from 'react'\n        function useColor() {\n          const [color, setColor] = useState<string>('#ffffff')\n          return [color, setFlavor]\n        }\n      "}}}}},
			{Code: "\n        import React from 'react'\n        function useColor() {\n          const [color, setFlavor] = React.useState<string>('#ffffff')\n          return [color, setFlavor]\n        }\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "useStateErrorMessage", Message: "useState call is not destructured into value + setter pair", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestPair", Output: "\n        import React from 'react'\n        function useColor() {\n          const [color, setColor] = React.useState<string>('#ffffff')\n          return [color, setFlavor]\n        }\n      "}}}}},
		},
	)
}
