
// Code generated by tools/gen_shims. DO NOT EDIT.

package core

import "github.com/microsoft/typescript-go/internal/core"
import "iter"
import _ "unsafe"

type CompilerOptions = core.CompilerOptions
//go:linkname ComputeLineStarts github.com/microsoft/typescript-go/internal/core.ComputeLineStarts
func ComputeLineStarts(text string) []core.TextPos
//go:linkname ComputeLineStartsSeq github.com/microsoft/typescript-go/internal/core.ComputeLineStartsSeq
func ComputeLineStartsSeq(text string) iter.Seq[core.TextPos]
//go:linkname FindBestPatternMatch github.com/microsoft/typescript-go/internal/core.FindBestPatternMatch
func FindBestPatternMatch(patterns []core.Pattern, candidate string) core.Pattern
//go:linkname GetOutputExtension github.com/microsoft/typescript-go/internal/core.GetOutputExtension
func GetOutputExtension(fileName string, jsx core.JsxEmit) string
//go:linkname GetScriptKindFromFileName github.com/microsoft/typescript-go/internal/core.GetScriptKindFromFileName
func GetScriptKindFromFileName(fileName string) core.ScriptKind
type JsxEmit = core.JsxEmit
const JsxEmitNone = core.JsxEmitNone
const JsxEmitPreserve = core.JsxEmitPreserve
const JsxEmitReact = core.JsxEmitReact
const JsxEmitReactJSX = core.JsxEmitReactJSX
const JsxEmitReactJSXDev = core.JsxEmitReactJSXDev
const JsxEmitReactNative = core.JsxEmitReactNative
type LanguageVariant = core.LanguageVariant
const LanguageVariantJSX = core.LanguageVariantJSX
const LanguageVariantStandard = core.LanguageVariantStandard
type LinkStore[K comparable, V any] = core.LinkStore[K,V]
type ModuleDetectionKind = core.ModuleDetectionKind
const ModuleDetectionKindAuto = core.ModuleDetectionKindAuto
const ModuleDetectionKindForce = core.ModuleDetectionKindForce
const ModuleDetectionKindLegacy = core.ModuleDetectionKindLegacy
const ModuleDetectionKindNone = core.ModuleDetectionKindNone
type ModuleKind = core.ModuleKind
const ModuleKindAMD = core.ModuleKindAMD
const ModuleKindCommonJS = core.ModuleKindCommonJS
const ModuleKindES2015 = core.ModuleKindES2015
const ModuleKindES2020 = core.ModuleKindES2020
const ModuleKindES2022 = core.ModuleKindES2022
const ModuleKindESNext = core.ModuleKindESNext
const ModuleKindNode16 = core.ModuleKindNode16
const ModuleKindNodeNext = core.ModuleKindNodeNext
const ModuleKindNone = core.ModuleKindNone
const ModuleKindPreserve = core.ModuleKindPreserve
const ModuleKindSystem = core.ModuleKindSystem
const ModuleKindUMD = core.ModuleKindUMD
type ModuleResolutionKind = core.ModuleResolutionKind
const ModuleResolutionKindBundler = core.ModuleResolutionKindBundler
const ModuleResolutionKindNode16 = core.ModuleResolutionKindNode16
const ModuleResolutionKindNodeNext = core.ModuleResolutionKindNodeNext
const ModuleResolutionKindUnknown = core.ModuleResolutionKindUnknown
type MultiMap[K, V comparable] = core.MultiMap[K,V]
type NewLineKind = core.NewLineKind
const NewLineKindCRLF = core.NewLineKindCRLF
const NewLineKindLF = core.NewLineKindLF
const NewLineKindNone = core.NewLineKindNone
//go:linkname NewTextRange github.com/microsoft/typescript-go/internal/core.NewTextRange
func NewTextRange(pos int, end int) core.TextRange
//go:linkname NewWorkGroup github.com/microsoft/typescript-go/internal/core.NewWorkGroup
func NewWorkGroup(singleThreaded bool) core.WorkGroup
type ParsedOptions = core.ParsedOptions
type Pattern = core.Pattern
type PollingKind = core.PollingKind
const PollingKindDynamicPriority = core.PollingKindDynamicPriority
const PollingKindFixedChunkSize = core.PollingKindFixedChunkSize
const PollingKindFixedInterval = core.PollingKindFixedInterval
const PollingKindNone = core.PollingKindNone
const PollingKindPriorityInterval = core.PollingKindPriorityInterval
type Pool[T any] = core.Pool[T]
//go:linkname PositionToLineAndCharacter github.com/microsoft/typescript-go/internal/core.PositionToLineAndCharacter
func PositionToLineAndCharacter(position int, lineStarts []core.TextPos) (line int, character int)
type ProjectReference = core.ProjectReference
type ResolutionMode = core.ResolutionMode
const ResolutionModeCommonJS = core.ResolutionModeCommonJS
const ResolutionModeESM = core.ResolutionModeESM
const ResolutionModeNone = core.ResolutionModeNone
type ScriptKind = core.ScriptKind
const ScriptKindDeferred = core.ScriptKindDeferred
const ScriptKindExternal = core.ScriptKindExternal
const ScriptKindJS = core.ScriptKindJS
const ScriptKindJSON = core.ScriptKindJSON
const ScriptKindJSX = core.ScriptKindJSX
const ScriptKindTS = core.ScriptKindTS
const ScriptKindTSX = core.ScriptKindTSX
const ScriptKindUnknown = core.ScriptKindUnknown
type ScriptTarget = core.ScriptTarget
const ScriptTargetES2015 = core.ScriptTargetES2015
const ScriptTargetES2016 = core.ScriptTargetES2016
const ScriptTargetES2017 = core.ScriptTargetES2017
const ScriptTargetES2018 = core.ScriptTargetES2018
const ScriptTargetES2019 = core.ScriptTargetES2019
const ScriptTargetES2020 = core.ScriptTargetES2020
const ScriptTargetES2021 = core.ScriptTargetES2021
const ScriptTargetES2022 = core.ScriptTargetES2022
const ScriptTargetES2023 = core.ScriptTargetES2023
const ScriptTargetES3 = core.ScriptTargetES3
const ScriptTargetES5 = core.ScriptTargetES5
const ScriptTargetESNext = core.ScriptTargetESNext
const ScriptTargetJSON = core.ScriptTargetJSON
const ScriptTargetLatest = core.ScriptTargetLatest
const ScriptTargetNone = core.ScriptTargetNone
type Set[T comparable] = core.Set[T]
type SourceFileAffectingCompilerOptions = core.SourceFileAffectingCompilerOptions
type Stack[T any] = core.Stack[T]
//go:linkname StringifyJson github.com/microsoft/typescript-go/internal/core.StringifyJson
func StringifyJson(input any, prefix string, indent string) (string, error)
const TSFalse = core.TSFalse
const TSTrue = core.TSTrue
const TSUnknown = core.TSUnknown
type TextPos = core.TextPos
type TextRange = core.TextRange
type Tristate = core.Tristate
//go:linkname TryParsePattern github.com/microsoft/typescript-go/internal/core.TryParsePattern
func TryParsePattern(pattern string) core.Pattern
//go:linkname UndefinedTextRange github.com/microsoft/typescript-go/internal/core.UndefinedTextRange
func UndefinedTextRange() core.TextRange
const Version = core.Version
const VersionMajorMinor = core.VersionMajorMinor
type WatchDirectoryKind = core.WatchDirectoryKind
const WatchDirectoryKindDynamicPriorityPolling = core.WatchDirectoryKindDynamicPriorityPolling
const WatchDirectoryKindFixedChunkSizePolling = core.WatchDirectoryKindFixedChunkSizePolling
const WatchDirectoryKindFixedPollingInterval = core.WatchDirectoryKindFixedPollingInterval
const WatchDirectoryKindNone = core.WatchDirectoryKindNone
const WatchDirectoryKindUseFsEvents = core.WatchDirectoryKindUseFsEvents
type WatchFileKind = core.WatchFileKind
const WatchFileKindDynamicPriorityPolling = core.WatchFileKindDynamicPriorityPolling
const WatchFileKindFixedChunkSizePolling = core.WatchFileKindFixedChunkSizePolling
const WatchFileKindFixedPollingInterval = core.WatchFileKindFixedPollingInterval
const WatchFileKindNone = core.WatchFileKindNone
const WatchFileKindPriorityPollingInterval = core.WatchFileKindPriorityPollingInterval
const WatchFileKindUseFsEvents = core.WatchFileKindUseFsEvents
const WatchFileKindUseFsEventsOnParentDirectory = core.WatchFileKindUseFsEventsOnParentDirectory
type WatchOptions = core.WatchOptions
type WorkGroup = core.WorkGroup
