// Code generated by internal/ipc/internal/generate; DO NOT EDIT.

export const FRAME_HEADER_SIZE = 4;
export const MAX_FRAME_SIZE = 268435456;
export const KIND_RESPONSE = 'response';
export const KIND_ERROR = 'error';
export const KIND_HANDSHAKE = 'handshake';
export const KIND_EXIT = 'exit';
export const PROTOCOL_VERSION = 1;
export const SLOT_COUNT = 16;
export const SLOT_SIZE = 16777216;
export const INHERITED_FD = 3;
export const MAX_GENERATION = 4294967295;

export interface SourceMapping {
  version: number;
  fd?: number;
  handle?: string;
  processId?: number;
}

export interface SourceBatch {
  slot: number;
  generation: number;
  length: number;
}

export interface SourceRange {
  offset: number;
  length: number;
}

export interface TextAttachment {
  text?: string;
  range?: SourceRange;
}

export interface TransportMetadata {
  mapping?: SourceMapping;
  batch?: SourceBatch;
  released?: SourceBatch;
}

export interface WireMessage {
  kind: string;
  id: number;
  data?: unknown;
  attachments?: TextAttachment[];
  transport?: TransportMetadata;
}

export interface ErrorResponseData {
  message: string;
}
