package unified_signatures

// TestUnifiedSignaturesUpstream migrates every valid and invalid case from
// typescript-eslint v8.68.0. Rslint-specific coverage lives in
// unified_signatures_extras_test.go.

import (
	"testing"

	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/fixtures"
	"github.com/web-infra-dev/rslint/internal/rule_tester"
)

func TestUnifiedSignaturesUpstream(t *testing.T) {
	rule_tester.RunRuleTester(
		fixtures.GetRootDir(),
		"tsconfig.json",
		t,
		&UnifiedSignaturesRule,
		[]rule_tester.ValidTestCase{
			{Code: "\nfunction g(): void;\nfunction g(a: number, b: number): void;\nfunction g(a?: number, b?: number): void {}\n    "},
			{Code: "\nfunction rest(...xs: number[]): void;\nfunction rest(xs: number[], y: string): void;\nfunction rest(...args: any[]) {}\n    "},
			{Code: "\nclass C {\n  constructor();\n  constructor(a: number, b: number);\n  constructor(a?: number, b?: number) {}\n\n  a(): void;\n  a(a: number, b: number): void;\n  a(a?: number, b?: number): void {}\n}\n    "},
			{Code: "\ndeclare class Example {\n  privateMethod(a: number): void;\n  #privateMethod(a: number, b?: string): void;\n}\n    "},
			{Code: "\ndeclare class Example {\n  #privateMethod1(a: number): void;\n  #privateMethod2(a: number, b?: string): void;\n}\n    "},
			{Code: "\ninterface I {\n  a2(): void;\n  a2(x: number, y: number): void;\n}\n    "},
			{Code: "\ninterface I {\n  a4(): void;\n  a4(x: number): number;\n}\n    "},
			{Code: "\ninterface I {\n  a5<T>(x: T): T;\n  a5(x: number): number;\n}\n    "},
			{Code: "\ninterface I {\n  b2(x: string): void;\n  b2(...x: number[]): void;\n}\n    "},
			{Code: "\ninterface I {\n  b3(...x: number[]): void;\n  b3(...x: string[]): void;\n}\n    "},
			{Code: "\ninterface I {\n  c3(x: number): void;\n  c3(x?: string): void;\n}\n    "},
			{Code: "\ninterface I {\n  d2(x: string, y: number): void;\n  d2(x: number, y: string): void;\n}\n    "},
			{Code: "\ndeclare class D {\n  static a();\n  a(x: number);\n}\n    "},
			{Code: "\ninterface Generic<T> {\n  x(): void;\n  x(x: T[]): void;\n}\n    "},
			{Code: "\ninterface I {\n  f(x1: number): void;\n  f(x1: boolean, x2?: number): void;\n}\n    "},
			{Code: "\nfunction f<T extends number>(x: T[]): void;\nfunction f<T extends string>(x: T): void;\n    "},
			{Code: "\ndeclare function foo(n: number): number;\n\ndeclare module 'hello' {\n  function foo(n: number, s: string): number;\n}\n    "},
			{Code: "\n{\n  function block(): number;\n  function block(n: number): number;\n  function block(n?: number): number {\n    return 3;\n  }\n}\n    "},
			{Code: "\nexport interface Foo {\n  bar(baz: string): number[];\n  bar(): string[];\n}\n    "},
			{Code: "\ndeclare module 'foo' {\n  export default function (foo: number): string[];\n}\n    "},
			{Code: "\nexport default function (foo: number): string[];\n    "},
			{Code: "\nfunction p(key: string): Promise<string | undefined>;\nfunction p(key: string, defaultValue: string): Promise<string>;\nfunction p(key: string, defaultValue?: string): Promise<string | undefined> {\n  const obj: Record<string, string> = {};\n  return obj[key] || defaultValue;\n}\n    "},
			{Code: "\ninterface I {\n  p<T>(x: T): Promise<T>;\n  p(x: number): Promise<number>;\n}\n    "},
			{Code: "\nfunction rest(...xs: number[]): Promise<number[]>;\nfunction rest(xs: number[], y: string): Promise<string>;\nasync function rest(...args: any[], y?: string): Promise<number[] | string> {\n  return y || args;\n}\n    "},
			{Code: "\ndeclare class Foo {\n  get bar();\n  set bar(x: number);\n}\n    "},
			{Code: "\ninterface Foo {\n  get bar();\n  set bar(x: number);\n}\n    "},
			{Code: "\nabstract class Foo {\n  abstract get bar();\n  abstract set bar(a: unknown);\n}\n    "},
			{Code: "\nfunction f(a: number): void;\nfunction f(b: string): void;\nfunction f(a: number | string): void {}\n      ", Options: []any{map[string]any{"ignoreDifferentlyNamedParameters": true}}},
			{Code: "\nfunction f(m: number): void;\nfunction f(v: number, u: string): void;\nfunction f(v: number, u?: string): void {}\n      ", Options: []any{map[string]any{"ignoreDifferentlyNamedParameters": true}}},
			{Code: "\nfunction f(v: boolean): number;\nfunction f(): string;\n      ", Options: []any{map[string]any{"ignoreDifferentlyNamedParameters": true}}},
			{Code: "\nfunction f(v: boolean, u: boolean): number;\nfunction f(v: boolean): string;\n      ", Options: []any{map[string]any{"ignoreDifferentlyNamedParameters": true}}},
			{Code: "\nfunction f(v: number, u?: string): void {}\nfunction f(v: number): void;\nfunction f(): string;\n      ", Options: []any{map[string]any{"ignoreDifferentlyNamedParameters": true}}},
			{Code: "\nfunction f(a: boolean, ...c: number[]): void;\nfunction f(a: boolean, ...d: string[]): void;\nfunction f(a: boolean, ...c: (number | string)[]): void {}\n      ", Options: []any{map[string]any{"ignoreDifferentlyNamedParameters": true}}},
			{Code: "\nclass C {\n  constructor();\n  constructor(a: number, b: number);\n  constructor(c?: number, b?: number) {}\n\n  a(): void;\n  a(a: number, b: number): void;\n  a(a?: number, d?: number): void {}\n}\n      ", Options: []any{map[string]any{"ignoreDifferentlyNamedParameters": true}}},
			{Code: "\n/** @deprecated */\ndeclare function f(x: number): unknown;\ndeclare function f(x: boolean): unknown;\n      ", Options: []any{map[string]any{"ignoreOverloadsWithDifferentJSDoc": true}}},
			{Code: "\ndeclare function f(x: number): unknown;\n/** @deprecated */\ndeclare function f(x: boolean): unknown;\n      ", Options: []any{map[string]any{"ignoreOverloadsWithDifferentJSDoc": true}}},
			{Code: "\ndeclare function f(x: number): unknown;\n/** @deprecated */ declare function f(x: boolean): unknown;\n      ", Options: []any{map[string]any{"ignoreOverloadsWithDifferentJSDoc": true}}},
			{Code: "\ndeclare function f(x: string): void;\n/**\n * @async\n */\ndeclare function f(x: boolean): void;\n/**\n * @deprecate\n */\ndeclare function f(x: number): void;\n      ", Options: []any{map[string]any{"ignoreOverloadsWithDifferentJSDoc": true}}},
			{Code: "\n/**\n * @deprecate\n */\ndeclare function f(x: string): void;\n/**\n * @async\n */\ndeclare function f(x: boolean): void;\ndeclare function f(x: number): void;\n      ", Options: []any{map[string]any{"ignoreOverloadsWithDifferentJSDoc": true}}},
			{Code: "\n/**\n * This signature does something.\n */\ndeclare function f(x: number): void;\n\n/**\n * This signature does something else.\n */\ndeclare function f(x: string): void;\n      ", Options: []any{map[string]any{"ignoreOverloadsWithDifferentJSDoc": true}}},
			{Code: "\n/** @deprecated */\nexport function f(x: number): unknown;\nexport function f(x: boolean): unknown;\n      ", Options: []any{map[string]any{"ignoreOverloadsWithDifferentJSDoc": true}}},
			{Code: "\n/**\n * This signature does something.\n */\n\n// some other comment\nexport function f(x: number): void;\n\n/**\n * This signature does something else.\n */\nexport function f(x: string): void;\n      ", Options: []any{map[string]any{"ignoreOverloadsWithDifferentJSDoc": true}}},
			{Code: "\ninterface I {\n  /**\n   * This signature does something else.\n   */\n  f(x: number): void;\n  f(x: string): void;\n}\n      ", Options: []any{map[string]any{"ignoreOverloadsWithDifferentJSDoc": true}}},
			{Code: "\n/* @deprecated */\ndeclare function f(x: number): unknown;\ndeclare function f(x: boolean): unknown;\n      ", Options: []any{map[string]any{"ignoreOverloadsWithDifferentJSDoc": true}}},
			{Code: "\n/*\n * This signature does something.\n */\ndeclare function f(x: number): unknown;\ndeclare function f(x: boolean): unknown;\n      ", Options: []any{map[string]any{"ignoreOverloadsWithDifferentJSDoc": true}}},
			{Code: "\n/**\n * This signature does something.\n **/\ndeclare function f(x: number): unknown;\ndeclare function f(x: boolean): unknown;\n      ", Options: []any{map[string]any{"ignoreOverloadsWithDifferentJSDoc": true}}},
			{Code: "\nclass C {\n  a(b: string): void;\n  /**\n   * @deprecate\n   */\n  a(b: number): void;\n}\n      ", Options: []any{map[string]any{"ignoreOverloadsWithDifferentJSDoc": true}}},
			{Code: "\nfunction f(): void;\nfunction f(this: {}): void;\nfunction f(this: void | {}): void {}\n    "},
			{Code: "\nfunction f(a: boolean): void;\nfunction f(this: {}, a: boolean): void;\nfunction f(this: void | {}, a: boolean): void {}\n    "},
			{Code: "\nfunction f(this: void, a: boolean): void;\nfunction f(this: {}, a: boolean): void;\nfunction f(this: void | {}, a: boolean): void {}\n    "},
		},
		[]rule_tester.InvalidTestCase{
			{Code: "\nfunction f(a: number): void;\nfunction f(b: string): void;\nfunction f(a: number | string): void {}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "singleParameterDifference", Line: 3, Column: 12}}},
			{Code: "\nfunction f(x: number): void;\nfunction f(x: string): void;\nfunction f(x: any): any {\n  return x;\n}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "singleParameterDifference", Line: 3, Column: 12}}},
			{Code: "\nfunction f(x: number): void;\nfunction f(x: string): void;\nfunction f(x: any): any {\n  return x;\n}\n      ", Options: []any{map[string]any{"ignoreDifferentlyNamedParameters": true}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "singleParameterDifference", Line: 3, Column: 12}}},
			{Code: "\nfunction opt(xs?: number[]): void;\nfunction opt(xs: number[], y: string): void;\nfunction opt(...args: any[]) {}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "omittingSingleParameter", Line: 3, Column: 28}}},
			{Code: "\ninterface I {\n  a0(): void;\n  a0(x: string): string;\n  a0(x: number): void;\n}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "omittingSingleParameter", Line: 5, Column: 6}}},
			{Code: "\ninterface I {\n  a0(): void;\n  a0(x: string): string;\n  a0(x: number): void;\n}\n      ", Options: []any{map[string]any{"ignoreDifferentlyNamedParameters": true}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "omittingSingleParameter", Line: 5, Column: 6}}},
			{Code: "\ninterface I {\n  a1(): void;\n  a1(x: number): void;\n}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "omittingSingleParameter", Line: 4, Column: 6}}},
			{Code: "\ninterface I {\n  a3(): void;\n  a3(x: number, y?: number, ...z: number[]): void;\n}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "omittingRestParameter", Line: 4, Column: 29}}},
			{Code: "\ninterface I {\n  b(): void;\n  b(...x: number[]): void;\n}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "omittingRestParameter", Line: 4, Column: 5}}},
			{Code: "\ninterface I {\n  c(): void;\n  c(x?: number): void;\n}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "omittingSingleParameter", Line: 4, Column: 5}}},
			{Code: "\ninterface I {\n  c2(x?: number): void;\n  c2(x?: string): void;\n}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "singleParameterDifference", Line: 4, Column: 6}}},
			{Code: "\ninterface I {\n  d(x: number): void;\n  d(x: string): void;\n}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "singleParameterDifference", Line: 4, Column: 5}}},
			{Code: "\ntype T = {\n  (): void;\n  (x: number): void;\n};\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "omittingSingleParameter", Line: 4, Column: 4}}},
			{Code: "\ndeclare class Example {\n  #privateMethod(a: number): void;\n  #privateMethod(a: number, b?: string): void;\n}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "omittingSingleParameter", Line: 4, Column: 29}}},
			{Code: "\ndeclare class C {\n  constructor();\n  constructor(x: number);\n}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "omittingSingleParameter", Line: 4, Column: 15}}},
			{Code: "\ninterface I {\n  f(x: number);\n  f(x: string | boolean);\n}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "singleParameterDifference", Line: 4, Column: 5}}},
			{Code: "\ninterface I {\n  f(x: number);\n  f(x: [string, boolean]);\n}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "singleParameterDifference", Line: 4, Column: 5}}},
			{Code: "\ninterface Generic<T> {\n  y(x: T[]): void;\n  y(x: T): void;\n}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "singleParameterDifference", Line: 4, Column: 5}}},
			{Code: "\nfunction f<T>(x: T[]): void;\nfunction f<T>(x: T): void;\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "singleParameterDifference", Line: 3, Column: 15}}},
			{Code: "\nfunction f<T extends number>(x: T[]): void;\nfunction f<T extends number>(x: T): void;\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "singleParameterDifference", Line: 3, Column: 30}}},
			{Code: "\nabstract class Foo {\n  public abstract f(x: number): void;\n  public abstract f(x: string): void;\n}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "singleParameterDifference", Line: 4, Column: 21}}},
			{Code: "\nabstract class C {\n  a(b: string): void;\n  /**\n   * @deprecate\n   */\n  a(b: number): void;\n}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "singleParameterDifference", Line: 7, Column: 5}}},
			{Code: "\ninterface Foo {\n  'f'(x: string): void;\n  'f'(x: number): void;\n}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "singleParameterDifference", Line: 4, Column: 7}}},
			{Code: "\ninterface Foo {\n  new (x: string): Foo;\n  new (x: number): Foo;\n}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "singleParameterDifference", Line: 4, Column: 8}}},
			{Code: "\nenum Enum {\n  Func = 'function',\n}\n\ninterface IFoo {\n  [Enum.Func](x: string): void;\n  [Enum.Func](x: number): void;\n}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "singleParameterDifference", Line: 8, Column: 15}}},
			{Code: "\nexport function foo(line: number): number;\nexport function foo(line: number, character?: number): number;\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "omittingSingleParameter", Line: 3, Column: 35}}},
			{Code: "\ndeclare function foo(line: number): number;\nexport function foo(line: number, character?: number): number;\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "omittingSingleParameter", Line: 3, Column: 35}}},
			{Code: "\ndeclare module 'foo' {\n  export default function (foo: number): string[];\n  export default function (foo: number, bar?: string): string[];\n}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "omittingSingleParameter", Line: 4, Column: 41}}},
			{Code: "\nexport default function (foo: number): string[];\nexport default function (foo: number, bar?: string): string[];\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "omittingSingleParameter", Line: 3, Column: 39}}},
			{Code: "\n/**\n * @deprecate\n */\ndeclare function f(x: string): void;\ndeclare function f(x: number): void;\ndeclare function f(x: boolean): void;\n      ", Options: []any{map[string]any{"ignoreOverloadsWithDifferentJSDoc": true}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "singleParameterDifference", Line: 7, Column: 20}}},
			{Code: "\n/**\n * @deprecate\n */\ndeclare function f(x: string): void;\n/**\n * @deprecate\n */\ndeclare function f(x: number): void;\ndeclare function f(x: boolean): void;\n      ", Options: []any{map[string]any{"ignoreOverloadsWithDifferentJSDoc": true}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "singleParameterDifference", Line: 9, Column: 20}}},
			{Code: "\ndeclare function f(x: string): void;\n/**\n * @deprecate\n */\ndeclare function f(x: number): void;\n/**\n * @deprecate\n */\ndeclare function f(x: boolean): void;\n      ", Options: []any{map[string]any{"ignoreOverloadsWithDifferentJSDoc": true}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "singleParameterDifference", Line: 10, Column: 20}}},
			{Code: "\nexport function f(x: string): void;\n/**\n * @deprecate\n */\nexport function f(x: number): void;\n/**\n * @deprecate\n */\nexport function f(x: boolean): void;\n      ", Options: []any{map[string]any{"ignoreOverloadsWithDifferentJSDoc": true}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "singleParameterDifference", Line: 10, Column: 19}}},
			{Code: "\n/**\n * This signature does something.\n */\n\n/**\n * This signature does something else.\n */\nfunction f(x: number): void;\n\n/**\n * This signature does something else.\n */\nfunction f(x: string): void;\n      ", Options: []any{map[string]any{"ignoreOverloadsWithDifferentJSDoc": true}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "singleParameterDifference", Line: 14, Column: 12}}},
			{Code: "\ninterface I {\n  f(x: string): void;\n  /**\n   * @deprecate\n   */\n  f(x: number): void;\n  /**\n   * @deprecate\n   */\n  f(x: boolean): void;\n}\n      ", Options: []any{map[string]any{"ignoreOverloadsWithDifferentJSDoc": true}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "singleParameterDifference", Line: 11, Column: 5}}},
			{Code: "\n// a line comment\ndeclare function f(x: number): unknown;\ndeclare function f(x: boolean): unknown;\n      ", Options: []any{map[string]any{"ignoreOverloadsWithDifferentJSDoc": true}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "singleParameterDifference", Line: 4, Column: 20}}},
			{Code: "\nfunction f(this: {}, a: boolean): void;\nfunction f(this: {}, a: string): void;\nfunction f(this: {}, a: boolean | string): void {}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "singleParameterDifference", Line: 3, Column: 22}}},
			{Code: "\nfunction f(this: {}): void;\nfunction f(this: {}, a: string): void;\nfunction f(this: {}, a?: string): void {}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "omittingSingleParameter", Line: 3, Column: 22}}},
			{Code: "\nfunction f(this: string): void;\nfunction f(this: number): void;\nfunction f(this: string | number): void {}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "singleParameterDifference", Line: 3, Column: 12}}},
			{Code: "\nfunction f(this: string, a: boolean): void;\nfunction f(this: number, a: boolean): void;\nfunction f(this: string | number, a: boolean): void {}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "singleParameterDifference", Line: 3, Column: 12}}},
			{Code: "\ndeclare function f(a: number): void;\ndeclare function f(a: number): void;\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "allParametersAreSame", Line: 3, Column: 1}}},
			{Code: "\ndeclare function f(a: number): void;\ndeclare function f(a: number): void;\ndeclare function f(a: string): string;\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "allParametersAreSame", Line: 3, Column: 1}}},
			{Code: "\nfunction f(a: number): void;\nfunction f(a: number): void;\nfunction f(a: number): void {}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "allParametersAreSame", Line: 3, Column: 1}}},
			{Code: "\nclass A {\n  f(a: number): void;\n  f(a: number): void;\n  f(a: number): void {}\n}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "allParametersAreSame", Line: 4, Column: 4}}},
			{Code: "\nfunction f(x: string | number): void;\nfunction f(x: number | boolean): void;\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "singleParameterDifference", Line: 3, Column: 12}}},
			{Code: "\nfunction f(value): void;\nfunction f(value: string): void;\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "singleParameterDifference", Line: 3, Column: 12}}},
			{Code: "\nfunction f(value: string): void;\nfunction f(value): void;\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "singleParameterDifference", Line: 3, Column: 12}}},
			{Code: "\ntype Alias = string;\nfunction f(x: Alias): void;\nfunction f(x: Alias | number): void;\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "singleParameterDifference", Line: 4, Column: 12}}},
			{Code: "\ntype Name = string;\nfunction f(x: Name): void;\nfunction f(x: string | Name): void;\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "singleParameterDifference", Line: 4, Column: 12}}},
			{Code: "\nfunction f<T>(x: T): void;\nfunction f<T>(x: T | string): void;\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "singleParameterDifference", Line: 3, Column: 15}}},
			{Code: "\nfunction f(x: 'a|b'): void;\nfunction f(x: 'a|b' | string): void;\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "singleParameterDifference", Line: 3, Column: 12}}},
			{Code: "\nfunction f(x: string /* first */ | number): void;\nfunction f(x: number | /* second */ string): void;\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "singleParameterDifference", Line: 3, Column: 12}}},
			{Code: "\ndeclare function fn(a: number): void;\ndeclare function fn(a: (/* before */ string /* after */)): void;\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "singleParameterDifference", Line: 3, Column: 21}}},
			{Code: "\nfunction f(x: string & { brand: true }): void;\nfunction f(x: number | string & /* brand */ { brand: true }): void;\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "singleParameterDifference", Line: 3, Column: 12}}},
			{Code: "\nfunction f(x: string & { brand: true }): void;\nfunction f(x: number | string & { brand: true }): void;\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "singleParameterDifference", Line: 3, Column: 12}}},
			{Code: "\nfunction f<T, U>(x: () => void): void;\nfunction f<T, U>(x: T extends U ? string : number): void;\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "singleParameterDifference", Line: 3, Column: 18}}},
			{Code: "\ninterface Value {}\nfunction f(x: new () => Value): void;\nfunction f(x: string): void;\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "singleParameterDifference", Line: 4, Column: 12}}},
			{Code: "\ninterface I {\n  f(x: string | number): void;\n  f(x: number | boolean): void;\n  f(x: symbol): string;\n}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "singleParameterDifference", Line: 4, Column: 5}}},
			{Code: "\nfunction f(x: 'a' | 'b'): void;\nfunction f(x: 'b' | 'c'): void;\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "singleParameterDifference", Line: 3, Column: 12}}},
			{Code: "\nfunction f(x: Array<string> | boolean): void;\nfunction f(x: Array<number> | boolean): void;\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "singleParameterDifference", Line: 3, Column: 12}}},
			{Code: "\nfunction f(x: Promise | boolean): void;\nfunction f(x: Promise<string> | boolean): void;\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "singleParameterDifference", Line: 3, Column: 12}}},
			{Code: "\nnamespace Namespace {\n  export type Value = string;\n}\nfunction f(x: Namespace.Value): void;\nfunction f(x: Namespace.Value | string): void;\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "singleParameterDifference", Line: 6, Column: 12}}},
		},
	)
}
