
// Code generated by tools/gen_shims. DO NOT EDIT.

package bundled

import "github.com/microsoft/TypeScript/tsc/internal/bundled"
import "github.com/microsoft/TypeScript/tsc/internal/vfs"
import _ "unsafe"

const Embedded = bundled.Embedded
//go:linkname IsBundled github.com/microsoft/TypeScript/tsc/internal/bundled.IsBundled
func IsBundled(path string) bool
var LibNames = bundled.LibNames
//go:linkname LibPath github.com/microsoft/TypeScript/tsc/internal/bundled.LibPath
func LibPath() string
//go:linkname TestingLibPath github.com/microsoft/TypeScript/tsc/internal/bundled.TestingLibPath
func TestingLibPath() string
//go:linkname WrapFS github.com/microsoft/TypeScript/tsc/internal/bundled.WrapFS
func WrapFS(fs vfs.FS) vfs.FS
