package iframe_missing_sandbox

import (
	"testing"

	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/fixtures"
	"github.com/web-infra-dev/rslint/internal/rule_tester"
)

func TestIframeMissingSandboxExtras(t *testing.T) {
	rule_tester.RunRuleTester(fixtures.GetRootDir(), "tsconfig.json", t, &IframeMissingSandboxRule, []rule_tester.ValidTestCase{
		// Tokens supported upstream but not exercised by its v7.37.5 suite.
		{Code: `<iframe sandbox="allow-downloads allow-downloads-without-user-activation allow-storage-access-by-user-activation" />`, Tsx: true},
		// Direct JSX attributes decode HTML entities before the rule sees their
		// ESTree Literal value; entities can form both a token and a delimiter.
		{Code: `<iframe sandbox="allow&#x2D;forms" />`, Tsx: true},
		{Code: `<iframe sandbox="allow-forms&#x20;allow-modals" />`, Tsx: true},
		// Upstream validates only direct Literal values; expressions remain dynamic.
		{Code: `<iframe sandbox={"__unknown__"} />`, Tsx: true},
		{Code: `React.createElement("iframe", {sandbox: value})`, Tsx: true},
		// Property forms without a literal value are dynamic, but still count as
		// defining sandbox. They must not be unwrapped as nil values.
		{Code: `React.createElement("iframe", {sandbox})`, Tsx: true},
		{Code: `React.createElement("iframe", {sandbox() {}})`, Tsx: true},
		{Code: `React.createElement("iframe", {get sandbox() {}})`, Tsx: true},
		{Code: `React.createElement("iframe", {set sandbox(value) {}})`, Tsx: true},
		// The first matching property wins, matching Array.prototype.find upstream.
		{Code: `React.createElement("iframe", {sandbox: "allow-forms", sandbox: "__unknown__"})`, Tsx: true},
		// A destructured React factory is supported by upstream's isCreateElement.
		{Code: `import { createElement } from "react"; createElement("iframe", {sandbox: "allow-forms"})`, Tsx: true},
		// Upstream reads MemberExpression.property.name, so an identifier in a
		// computed access is still recognized as createElement.
		{Code: `React[createElement]("iframe", {sandbox: "allow-forms"})`, Tsx: true},
		{Code: `React?.[createElement]("iframe", {sandbox: "allow-forms"})`, Tsx: true},
		// Configured pragma support comes from the shared upstream-equivalent matcher.
		{Code: `h.createElement("iframe", {sandbox: "allow-forms"})`, Tsx: true, Settings: map[string]interface{}{"react": map[string]interface{}{"pragma": "h"}}},
	}, []rule_tester.InvalidTestCase{
		{
			Code:     "import { createElement } from 'react'; createElement('div'); createElement('iframe');",
			FileName: "sandbox.jsx",
			TSConfig: "tsconfig.allow-js.json",
			Errors:   []rule_tester.InvalidTestCaseError{{MessageId: "attributeMissing", Message: msgAttributeMissing, Line: 1, Column: 62, EndLine: 1, EndColumn: 85}},
		},
		{
			Code: `React.createElement("iframe", {"sandbox": "allow-forms"})`, Tsx: true,
			Errors: []rule_tester.InvalidTestCaseError{{MessageId: "attributeMissing", Message: msgAttributeMissing, Line: 1, Column: 1, EndLine: 1, EndColumn: 58}},
		},
		{
			Code: `React.createElement("iframe", {[sandbox]: "__unknown__"})`, Tsx: true,
			Errors: []rule_tester.InvalidTestCaseError{{MessageId: "invalidValue", Message: `An iframe element defines a sandbox attribute with invalid value "__unknown__"`, Line: 1, Column: 1, EndLine: 1, EndColumn: 58}},
		},
		{
			Code: `import { createElement } from "react"; createElement("iframe")`, Tsx: true,
			Errors: []rule_tester.InvalidTestCaseError{{MessageId: "attributeMissing", Message: msgAttributeMissing, Line: 1, Column: 40, EndLine: 1, EndColumn: 63}},
		},
		{
			Code: `React[createElement]("iframe")`, Tsx: true,
			Errors: []rule_tester.InvalidTestCaseError{{MessageId: "attributeMissing", Message: msgAttributeMissing, Line: 1, Column: 1, EndLine: 1, EndColumn: 31}},
		},
		{
			Code: `React?.[createElement]("iframe")`, Tsx: true,
			Errors: []rule_tester.InvalidTestCaseError{{MessageId: "attributeMissing", Message: msgAttributeMissing, Line: 1, Column: 1, EndLine: 1, EndColumn: 33}},
		},
		{
			Code: `h.createElement("iframe")`, Tsx: true, Settings: map[string]interface{}{"react": map[string]interface{}{"pragma": "h"}},
			Errors: []rule_tester.InvalidTestCaseError{{MessageId: "attributeMissing", Message: msgAttributeMissing, Line: 1, Column: 1, EndLine: 1, EndColumn: 26}},
		},
	})
}

// Expectations verified with eslint-plugin-react 7.37.5 on ESLint 10.10.0
// and typescript-eslint/parser 8.70.0. JavaScript filenames exercise the JSDoc
// wrappers that tsgo synthesizes; authored TypeScript assertions stay visible.
func TestIframeMissingSandboxExpressionWrappers(t *testing.T) {
	rule_tester.RunRuleTester(fixtures.GetRootDir(), "tsconfig.allow-js.json", t, &IframeMissingSandboxRule, []rule_tester.ValidTestCase{
		{Code: "const sandbox = 'sandbox'; React.createElement('iframe', { [(sandbox)]: 'allow-forms' });",
			FileName: "sandbox.jsx"},
		{Code: "const sandbox = 'sandbox'; React.createElement('iframe', { [(sandbox)]() {} });",
			FileName: "sandbox.jsx"},
		{Code: "const sandbox = 'sandbox'; React.createElement('iframe', { [(sandbox)]: true });",
			FileName: "sandbox.jsx"},
		{Code: "const sandbox = 'sandbox'; React.createElement('iframe', { [(sandbox)]: value });",
			FileName: "sandbox.jsx"},
		{Code: "React.createElement('iframe', { *[(sandbox)]() {} });",
			FileName: "sandbox.jsx"},
		{Code: "React.createElement('iframe', { get [(sandbox)]() {} });",
			FileName: "sandbox.jsx"},
		{Code: "React.createElement('iframe', { set [(sandbox)](value) {} });",
			FileName: "sandbox.jsx"},
		{Code: "const sandbox = 'sandbox'; React.createElement('iframe', { [((/* comment */ sandbox))]: 'allow-forms' });",
			FileName: "sandbox.jsx"},
		{Code: "React.createElement('iframe', { sandbox: /** @type {any} */ ('allow-forms') });",
			FileName: "sandbox.jsx"},
		{Code: "React.createElement('iframe', /** @type {any} */ ({ sandbox: 'allow-forms' }));",
			FileName: "sandbox.jsx"},
		{Code: "const sandbox = 'sandbox'; React.createElement('iframe', { [/** @type {any} */ (sandbox)]: 'allow-forms' });",
			FileName: "sandbox.jsx"},
		{Code: "React.createElement('iframe', { sandbox: /** @satisfies {any} */ ('allow-forms') });",
			FileName: "sandbox.jsx"},
		{Code: "React.createElement('iframe', /** @satisfies {any} */ ({ sandbox: 'allow-forms' }));",
			FileName: "sandbox.jsx"},
		{Code: "const sandbox = 'sandbox'; React.createElement('iframe', { [/** @satisfies {any} */ (sandbox)]: 'allow-forms' });",
			FileName: "sandbox.jsx"},
		{Code: "React.createElement('iframe', { sandbox: /** @type {any} */ ((/** @satisfies {any} */ ('allow-forms'))) });",
			FileName: "sandbox.jsx"},
		{Code: "<div sandbox=\"unknown\" />;",
			FileName: "sandbox.jsx"},
		{Code: "<Iframe sandbox=\"unknown\" />;",
			FileName: "sandbox.jsx"},
		{Code: "<UI.iframe sandbox=\"unknown\" />;",
			FileName: "sandbox.jsx"},
		{Code: "<iframe.Frame sandbox=\"unknown\" />;",
			FileName: "sandbox.jsx"},
		{Code: "<svg:iframe sandbox=\"unknown\" />;",
			FileName: "sandbox.jsx"},
		{Code: "<this.iframe sandbox=\"unknown\" />;",
			FileName: "sandbox.jsx"},
		{Code: "React.createElement(('iframe' as any));",
			FileName: "sandbox.tsx"},
		{Code: "React.createElement('iframe', { sandbox: ('unknown' as any) });",
			FileName: "sandbox.tsx"},
		{Code: "React.createElement(('iframe' satisfies any));",
			FileName: "sandbox.tsx"},
		{Code: "React.createElement('iframe', { sandbox: ('unknown' satisfies any) });",
			FileName: "sandbox.tsx"},
		{Code: "React.createElement(('iframe'!));",
			FileName: "sandbox.tsx"},
		{Code: "React.createElement('iframe', { sandbox: ('unknown'!) });",
			FileName: "sandbox.tsx"},
	}, []rule_tester.InvalidTestCase{
		{Code: "const sandbox = 'sandbox'; React.createElement('iframe', { [(sandbox)]: 'unknown' });",
			FileName: "sandbox.jsx",
			Errors:   []rule_tester.InvalidTestCaseError{{MessageId: "invalidValue", Message: "An iframe element defines a sandbox attribute with invalid value \"unknown\"", Line: 1, Column: 28, EndLine: 1, EndColumn: 85}}},
		{Code: "const sandbox = 'sandbox'; React.createElement('iframe', { [(sandbox)]: 'allow-scripts allow-same-origin' });",
			FileName: "sandbox.jsx",
			Errors:   []rule_tester.InvalidTestCaseError{{MessageId: "invalidCombination", Message: "An iframe element defines a sandbox attribute with both allow-scripts and allow-same-origin which is invalid", Line: 1, Column: 28, EndLine: 1, EndColumn: 109}}},
		{Code: "const sandbox = 'sandbox'; React.createElement('iframe', { [((/* comment */ sandbox))]: 'unknown' });",
			FileName: "sandbox.jsx",
			Errors:   []rule_tester.InvalidTestCaseError{{MessageId: "invalidValue", Message: "An iframe element defines a sandbox attribute with invalid value \"unknown\"", Line: 1, Column: 28, EndLine: 1, EndColumn: 101}}},
		{Code: "const sandbox = 'sandbox'; React.createElement('iframe', { [((/* comment */ sandbox))]: 'allow-scripts allow-same-origin' });",
			FileName: "sandbox.jsx",
			Errors:   []rule_tester.InvalidTestCaseError{{MessageId: "invalidCombination", Message: "An iframe element defines a sandbox attribute with both allow-scripts and allow-same-origin which is invalid", Line: 1, Column: 28, EndLine: 1, EndColumn: 125}}},
		{Code: "React.createElement('iframe', { sandbox: /** @type {any} */ ('unknown') });",
			FileName: "sandbox.jsx",
			Errors:   []rule_tester.InvalidTestCaseError{{MessageId: "invalidValue", Message: "An iframe element defines a sandbox attribute with invalid value \"unknown\"", Line: 1, Column: 1, EndLine: 1, EndColumn: 75}}},
		{Code: "React.createElement('iframe', /** @type {any} */ ({ sandbox: 'unknown' }));",
			FileName: "sandbox.jsx",
			Errors:   []rule_tester.InvalidTestCaseError{{MessageId: "invalidValue", Message: "An iframe element defines a sandbox attribute with invalid value \"unknown\"", Line: 1, Column: 1, EndLine: 1, EndColumn: 75}}},
		{Code: "const sandbox = 'sandbox'; React.createElement('iframe', { [/** @type {any} */ (sandbox)]: 'unknown' });",
			FileName: "sandbox.jsx",
			Errors:   []rule_tester.InvalidTestCaseError{{MessageId: "invalidValue", Message: "An iframe element defines a sandbox attribute with invalid value \"unknown\"", Line: 1, Column: 28, EndLine: 1, EndColumn: 104}}},
		{Code: "React.createElement('iframe', { sandbox: /** @type {any} */ ('allow-scripts allow-same-origin') });",
			FileName: "sandbox.jsx",
			Errors:   []rule_tester.InvalidTestCaseError{{MessageId: "invalidCombination", Message: "An iframe element defines a sandbox attribute with both allow-scripts and allow-same-origin which is invalid", Line: 1, Column: 1, EndLine: 1, EndColumn: 99}}},
		{Code: "React.createElement('iframe', /** @type {any} */ ({ sandbox: 'allow-scripts allow-same-origin' }));",
			FileName: "sandbox.jsx",
			Errors:   []rule_tester.InvalidTestCaseError{{MessageId: "invalidCombination", Message: "An iframe element defines a sandbox attribute with both allow-scripts and allow-same-origin which is invalid", Line: 1, Column: 1, EndLine: 1, EndColumn: 99}}},
		{Code: "const sandbox = 'sandbox'; React.createElement('iframe', { [/** @type {any} */ (sandbox)]: 'allow-scripts allow-same-origin' });",
			FileName: "sandbox.jsx",
			Errors:   []rule_tester.InvalidTestCaseError{{MessageId: "invalidCombination", Message: "An iframe element defines a sandbox attribute with both allow-scripts and allow-same-origin which is invalid", Line: 1, Column: 28, EndLine: 1, EndColumn: 128}}},
		{Code: "React.createElement(/** @type {any} */ ('iframe'));",
			FileName: "sandbox.jsx",
			Errors:   []rule_tester.InvalidTestCaseError{{MessageId: "attributeMissing", Message: "An iframe element is missing a sandbox attribute", Line: 1, Column: 1, EndLine: 1, EndColumn: 51}}},
		{Code: "React.createElement('iframe', { sandbox: /** @satisfies {any} */ ('unknown') });",
			FileName: "sandbox.jsx",
			Errors:   []rule_tester.InvalidTestCaseError{{MessageId: "invalidValue", Message: "An iframe element defines a sandbox attribute with invalid value \"unknown\"", Line: 1, Column: 1, EndLine: 1, EndColumn: 80}}},
		{Code: "React.createElement('iframe', /** @satisfies {any} */ ({ sandbox: 'unknown' }));",
			FileName: "sandbox.jsx",
			Errors:   []rule_tester.InvalidTestCaseError{{MessageId: "invalidValue", Message: "An iframe element defines a sandbox attribute with invalid value \"unknown\"", Line: 1, Column: 1, EndLine: 1, EndColumn: 80}}},
		{Code: "const sandbox = 'sandbox'; React.createElement('iframe', { [/** @satisfies {any} */ (sandbox)]: 'unknown' });",
			FileName: "sandbox.jsx",
			Errors:   []rule_tester.InvalidTestCaseError{{MessageId: "invalidValue", Message: "An iframe element defines a sandbox attribute with invalid value \"unknown\"", Line: 1, Column: 28, EndLine: 1, EndColumn: 109}}},
		{Code: "React.createElement('iframe', { sandbox: /** @satisfies {any} */ ('allow-scripts allow-same-origin') });",
			FileName: "sandbox.jsx",
			Errors:   []rule_tester.InvalidTestCaseError{{MessageId: "invalidCombination", Message: "An iframe element defines a sandbox attribute with both allow-scripts and allow-same-origin which is invalid", Line: 1, Column: 1, EndLine: 1, EndColumn: 104}}},
		{Code: "React.createElement('iframe', /** @satisfies {any} */ ({ sandbox: 'allow-scripts allow-same-origin' }));",
			FileName: "sandbox.jsx",
			Errors:   []rule_tester.InvalidTestCaseError{{MessageId: "invalidCombination", Message: "An iframe element defines a sandbox attribute with both allow-scripts and allow-same-origin which is invalid", Line: 1, Column: 1, EndLine: 1, EndColumn: 104}}},
		{Code: "const sandbox = 'sandbox'; React.createElement('iframe', { [/** @satisfies {any} */ (sandbox)]: 'allow-scripts allow-same-origin' });",
			FileName: "sandbox.jsx",
			Errors:   []rule_tester.InvalidTestCaseError{{MessageId: "invalidCombination", Message: "An iframe element defines a sandbox attribute with both allow-scripts and allow-same-origin which is invalid", Line: 1, Column: 28, EndLine: 1, EndColumn: 133}}},
		{Code: "React.createElement(/** @satisfies {any} */ ('iframe'));",
			FileName: "sandbox.jsx",
			Errors:   []rule_tester.InvalidTestCaseError{{MessageId: "attributeMissing", Message: "An iframe element is missing a sandbox attribute", Line: 1, Column: 1, EndLine: 1, EndColumn: 56}}},
		{Code: "React.createElement('iframe', { sandbox: /** @type {any} */ ((/** @satisfies {any} */ ('unknown'))) });",
			FileName: "sandbox.jsx",
			Errors:   []rule_tester.InvalidTestCaseError{{MessageId: "invalidValue", Message: "An iframe element defines a sandbox attribute with invalid value \"unknown\"", Line: 1, Column: 1, EndLine: 1, EndColumn: 103}}},
		{Code: "React.createElement('iframe', { sandbox: /** @type {any} */ ((/** @satisfies {any} */ ('allow-scripts allow-same-origin'))) });",
			FileName: "sandbox.jsx",
			Errors:   []rule_tester.InvalidTestCaseError{{MessageId: "invalidCombination", Message: "An iframe element defines a sandbox attribute with both allow-scripts and allow-same-origin which is invalid", Line: 1, Column: 1, EndLine: 1, EndColumn: 127}}},
		{Code: "React.createElement('iframe', ({ sandbox: 'allow-forms' } as any));",
			FileName: "sandbox.tsx",
			Errors:   []rule_tester.InvalidTestCaseError{{MessageId: "attributeMissing", Message: "An iframe element is missing a sandbox attribute", Line: 1, Column: 1, EndLine: 1, EndColumn: 67}}},
		{Code: "React.createElement('iframe', { [(sandbox as any)]: 'allow-forms' });",
			FileName: "sandbox.tsx",
			Errors:   []rule_tester.InvalidTestCaseError{{MessageId: "attributeMissing", Message: "An iframe element is missing a sandbox attribute", Line: 1, Column: 1, EndLine: 1, EndColumn: 69}}},
		{Code: "React.createElement('iframe', ({ sandbox: 'allow-forms' } satisfies any));",
			FileName: "sandbox.tsx",
			Errors:   []rule_tester.InvalidTestCaseError{{MessageId: "attributeMissing", Message: "An iframe element is missing a sandbox attribute", Line: 1, Column: 1, EndLine: 1, EndColumn: 74}}},
		{Code: "React.createElement('iframe', { [(sandbox satisfies any)]: 'allow-forms' });",
			FileName: "sandbox.tsx",
			Errors:   []rule_tester.InvalidTestCaseError{{MessageId: "attributeMissing", Message: "An iframe element is missing a sandbox attribute", Line: 1, Column: 1, EndLine: 1, EndColumn: 76}}},
		{Code: "React.createElement('iframe', ({ sandbox: 'allow-forms' }!));",
			FileName: "sandbox.tsx",
			Errors:   []rule_tester.InvalidTestCaseError{{MessageId: "attributeMissing", Message: "An iframe element is missing a sandbox attribute", Line: 1, Column: 1, EndLine: 1, EndColumn: 61}}},
		{Code: "React.createElement('iframe', { [(sandbox!)]: 'allow-forms' });",
			FileName: "sandbox.tsx",
			Errors:   []rule_tester.InvalidTestCaseError{{MessageId: "attributeMissing", Message: "An iframe element is missing a sandbox attribute", Line: 1, Column: 1, EndLine: 1, EndColumn: 63}}},
	})
}
