// cspell:ignore someregular notregbutstring avalue mysafereg
package prefer_regex_literals

import (
	"testing"

	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/fixtures"
	"github.com/web-infra-dev/rslint/internal/rule_tester"
)

// TestPreferRegexLiteralsUpstream migrates the full valid/invalid suite from upstream tests/lib/rules/prefer-regex-literals.js 1:1. Position assertions cover upstream-provided line/column data. rslint-specific lock-in cases live in the prefer_regex_literals_extras_test.go file.
func TestPreferRegexLiteralsUpstream(t *testing.T) {
	rule_tester.RunRuleTester(
		fixtures.GetRootDir(),
		"tsconfig.json",
		t,
		&PreferRegexLiteralsRule,
		[]rule_tester.ValidTestCase{
			{Code: "/abc/"},
			{Code: "/abc/g"},
			{Code: "new RegExp(pattern)"},
			{Code: "new RegExp('\\\\p{Emoji_Presentation}\\\\P{Script_Extensions=Latin}' + '', `ug`)"},
			{Code: "new RegExp('\\\\cA' + '')"},
			{Code: "RegExp(pattern, 'g')"},
			{Code: "new RegExp(f('a'))"},
			{Code: "RegExp(prefix + 'a')"},
			{Code: "new RegExp('a' + suffix)"},
			{Code: "RegExp(`a` + suffix);"},
			{Code: "new RegExp(String.raw`a` + suffix);"},
			{Code: "RegExp('a', flags)"},
			{Code: "const flags = 'gu';RegExp('a', flags)"},
			{Code: "RegExp('a', 'g' + flags)"},
			{Code: "new RegExp(String.raw`a`, flags);"},
			{Code: "RegExp(`${prefix}abc`)"},
			{Code: "new RegExp(`a${b}c`);"},
			{Code: "new RegExp(`a${''}c`);"},
			{Code: "new RegExp(String.raw`a${b}c`);"},
			{Code: "new RegExp(String.raw`a${''}c`);"},
			{Code: "new RegExp('a' + 'b')"},
			{Code: "RegExp(1)"},
			{Code: "new RegExp('(\\\\p{Emoji_Presentation})\\\\1' + '', `ug`)"},
			{Code: "RegExp(String.raw`\\78\\126` + '\\\\5934', '' + `g` + '')"},
			{Code: "func(new RegExp(String.raw`a${''}c\\d`, 'u'),new RegExp(String.raw`a${''}c\\d`, 'u'))"},
			{Code: "new RegExp('\\\\[' + \"b\\\\]\")"},
			{Code: "new RegExp(/a/, flags);", Options: []interface{}{map[string]interface{}{"disallowRedundantWrapping": true}}},
			{Code: "new RegExp(/a/, `u${flags}`);", Options: []interface{}{map[string]interface{}{"disallowRedundantWrapping": true}}},
			{Code: "new RegExp(/a/);", Options: []interface{}{map[string]interface{}{}}},
			{Code: "new RegExp(/a/);", Options: []interface{}{map[string]interface{}{"disallowRedundantWrapping": false}}},
			{Code: "new RegExp;"},
			{Code: "new RegExp();"},
			{Code: "RegExp();"},
			{Code: "new RegExp('a', 'g', 'b');"},
			{Code: "RegExp('a', 'g', 'b');"},
			{Code: "new RegExp(`a`, `g`, `b`);"},
			{Code: "RegExp(`a`, `g`, `b`);"},
			{Code: "new RegExp(String.raw`a`, String.raw`g`, String.raw`b`);"},
			{Code: "RegExp(String.raw`a`, String.raw`g`, String.raw`b`);"},
			{Code: "new RegExp(/a/, 'u', 'foo');", Options: []interface{}{map[string]interface{}{"disallowRedundantWrapping": true}}},
			{Code: "new RegExp(String`a`);"},
			{Code: "RegExp(raw`a`);"},
			{Code: "new RegExp(f(String.raw)`a`);"},
			{Code: "RegExp(string.raw`a`);"},
			{Code: "new RegExp(String.Raw`a`);"},
			{Code: "new RegExp(String[raw]`a`);"},
			{Code: "RegExp(String.raw.foo`a`);"},
			{Code: "new RegExp(String.foo.raw`a`);"},
			{Code: "RegExp(foo.String.raw`a`);"},
			{Code: "new RegExp(String.raw);"},
			{Code: "let String; new RegExp(String.raw`a`);"},
			{Code: "function foo() { var String; new RegExp(String.raw`a`); }"},
			{Code: "function foo(String) { RegExp(String.raw`a`); }"},
			{Code: "if (foo) { const String = bar; RegExp(String.raw`a`); }"},
			// SKIP: rslint does not support ESLint global directive comments.
			{Code: "/* globals String:off */ new RegExp(String.raw`a`);", Skip: true},
			// SKIP: rslint does not support disabling globals through languageOptions.globals.
			{Code: "RegExp('a', String.raw`g`);", Skip: true},
			{Code: "new Regexp('abc');"},
			{Code: "Regexp(`a`);"},
			{Code: "new Regexp(String.raw`a`);"},
			{Code: "let RegExp; new RegExp('a');"},
			{Code: "function foo() { var RegExp; RegExp('a', 'g'); }"},
			{Code: "function foo(RegExp) { new RegExp(String.raw`a`); }"},
			{Code: "if (foo) { const RegExp = bar; RegExp('a'); }"},
			// SKIP: rslint does not support ESLint global directive comments.
			{Code: "/* globals RegExp:off */ new RegExp('a');", Skip: true},
			// SKIP: rslint does not support disabling globals through languageOptions.globals.
			{Code: "RegExp('a');", Skip: true},
			// SKIP: rslint does not emulate ESLint ecmaVersion-specific global availability.
			{Code: "new globalThis.RegExp('a');", Skip: true},
			// SKIP: rslint does not emulate ESLint ecmaVersion-specific global availability.
			{Code: "new globalThis.RegExp('a');", Skip: true},
			// SKIP: rslint does not emulate ESLint ecmaVersion-specific global availability.
			{Code: "new globalThis.RegExp('a');", Skip: true},
			{Code: "class C { #RegExp; foo() { globalThis.#RegExp('a'); } }"},
			{Code: "new RegExp('[[A--B]]' + a, 'v')"},
		},
		[]rule_tester.InvalidTestCase{
			{Code: "new RegExp('abc');", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/abc/;"}}}}},
			{Code: "RegExp('abc');", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/abc/;"}}}}},
			{Code: "new RegExp('abc', 'g');", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/abc/g;"}}}}},
			{Code: "RegExp('abc', 'g');", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/abc/g;"}}}}},
			{Code: "new RegExp(`abc`);", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/abc/;"}}}}},
			{Code: "RegExp(`abc`);", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/abc/;"}}}}},
			{Code: "new RegExp(`abc`, `g`);", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/abc/g;"}}}}},
			{Code: "RegExp(`abc`, `g`);", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/abc/g;"}}}}},
			{Code: "new RegExp(String.raw`abc`);", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/abc/;"}}}}},
			{Code: "new RegExp(String.raw`abc\nabc`);", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/abc\\nabc/;"}}}}},
			{Code: "new RegExp(String.raw`\tabc\nabc`);", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/\\tabc\\nabc/;"}}}}},
			{Code: "RegExp(String.raw`abc`);", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/abc/;"}}}}},
			{Code: "new RegExp(String.raw`abc`, String.raw`g`);", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/abc/g;"}}}}},
			{Code: "RegExp(String.raw`abc`, String.raw`g`);", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/abc/g;"}}}}},
			{Code: "new RegExp(String['raw']`a`);", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/a/;"}}}}},
			{Code: "new RegExp('');", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/(?:)/;"}}}}},
			{Code: "RegExp('', '');", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/(?:)/;"}}}}},
			{Code: "new RegExp(String.raw``);", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/(?:)/;"}}}}},
			{Code: "new RegExp('a', `g`);", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/a/g;"}}}}},
			{Code: "RegExp(`a`, 'g');", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/a/g;"}}}}},
			{Code: "RegExp(String.raw`a`, 'g');", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/a/g;"}}}}},
			{Code: "new RegExp(String.raw`\\d`, `g`);", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/\\d/g;"}}}}},
			{Code: "new RegExp(String.raw`\\\\d`, `g`);", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/\\\\d/g;"}}}}},
			{Code: "new RegExp(String['raw']`\\\\d`, `g`);", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/\\\\d/g;"}}}}},
			{Code: "new RegExp(String[\"raw\"]`\\\\d`, `g`);", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/\\\\d/g;"}}}}},
			{Code: "RegExp('a', String.raw`g`);", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/a/g;"}}}}},
			{Code: "new globalThis.RegExp('a');", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/a/;"}}}}},
			{Code: "globalThis.RegExp('a');", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/a/;"}}}}},
			{Code: "new RegExp(/a/);", Options: []interface{}{map[string]interface{}{"disallowRedundantWrapping": true}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRedundantRegExp", Line: 1, Column: 1, Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/a/;"}}}}},
			{Code: "new RegExp(/a/, 'u');", Options: []interface{}{map[string]interface{}{"disallowRedundantWrapping": true}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRedundantRegExpWithFlags", Line: 1, Column: 1, Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteralAndFlags", Output: "/a/u;"}}}}},
			{Code: "new RegExp(/a/g, '');", Options: []interface{}{map[string]interface{}{"disallowRedundantWrapping": true}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRedundantRegExpWithFlags", Line: 1, Column: 1, Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteralAndFlags", Output: "/a/;"}, {MessageId: "replaceWithIntendedLiteralAndFlags", Output: "/a/g;"}}}}},
			{Code: "new RegExp(/a/g, 'g');", Options: []interface{}{map[string]interface{}{"disallowRedundantWrapping": true}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRedundantRegExpWithFlags", Line: 1, Column: 1, Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteralAndFlags", Output: "/a/g;"}}}}},
			{Code: "new RegExp(/a/ig, 'g');", Options: []interface{}{map[string]interface{}{"disallowRedundantWrapping": true}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRedundantRegExpWithFlags", Line: 1, Column: 1, Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteralAndFlags", Output: "/a/g;"}, {MessageId: "replaceWithIntendedLiteralAndFlags", Output: "/a/ig;"}}}}},
			{Code: "new RegExp(/a/g, 'ig');", Options: []interface{}{map[string]interface{}{"disallowRedundantWrapping": true}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRedundantRegExpWithFlags", Line: 1, Column: 1, Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteralAndFlags", Output: "/a/ig;"}}}}},
			{Code: "new RegExp(/a/i, 'g');", Options: []interface{}{map[string]interface{}{"disallowRedundantWrapping": true}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRedundantRegExpWithFlags", Line: 1, Column: 1, Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteralAndFlags", Output: "/a/g;"}, {MessageId: "replaceWithIntendedLiteralAndFlags", Output: "/a/ig;"}}}}},
			{Code: "new RegExp(/a/i, 'i');", Options: []interface{}{map[string]interface{}{"disallowRedundantWrapping": true}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRedundantRegExpWithFlags", Line: 1, Column: 1, Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteralAndFlags", Output: "/a/i;"}}}}},
			{Code: "new RegExp(/a/, `u`);", Options: []interface{}{map[string]interface{}{"disallowRedundantWrapping": true}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRedundantRegExpWithFlags", Line: 1, Column: 1, Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteralAndFlags", Output: "/a/u;"}}}}},
			{Code: "new RegExp(/a/, `gi`);", Options: []interface{}{map[string]interface{}{"disallowRedundantWrapping": true}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRedundantRegExpWithFlags", Line: 1, Column: 1, Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteralAndFlags", Output: "/a/gi;"}}}}},
			{Code: "new RegExp('a');", Options: []interface{}{map[string]interface{}{"disallowRedundantWrapping": true}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Line: 1, Column: 1, Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/a/;"}}}}},
			{Code: "new RegExp(/a/, String.raw`u`);", Options: []interface{}{map[string]interface{}{"disallowRedundantWrapping": true}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRedundantRegExpWithFlags", Line: 1, Column: 1, Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteralAndFlags", Output: "/a/u;"}}}}},
			{Code: "new RegExp(/a/ /* comment */);", Options: []interface{}{map[string]interface{}{"disallowRedundantWrapping": true}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRedundantRegExp", Line: 1, Column: 1}}},
			// SKIP: rslint does not emulate ESLint ecmaVersion-specific d flag validation.
			{Code: "new RegExp(/a/, 'd');", Options: []interface{}{map[string]interface{}{"disallowRedundantWrapping": true}}, Skip: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRedundantRegExpWithFlags", Line: 1, Column: 1}}},
			{Code: "(a)\nnew RegExp(/b/);", Options: []interface{}{map[string]interface{}{"disallowRedundantWrapping": true}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRedundantRegExp", Line: 2, Column: 1}}},
			{Code: "(a)\nnew RegExp(/b/, 'g');", Options: []interface{}{map[string]interface{}{"disallowRedundantWrapping": true}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRedundantRegExpWithFlags", Line: 2, Column: 1}}},
			{Code: "a/RegExp(/foo/);", Options: []interface{}{map[string]interface{}{"disallowRedundantWrapping": true}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRedundantRegExp", Line: 1, Column: 3, Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "a/ /foo/;"}}}}},
			{Code: "RegExp(/foo/)in a;", Options: []interface{}{map[string]interface{}{"disallowRedundantWrapping": true}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRedundantRegExp", Line: 1, Column: 1, Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/foo/ in a;"}}}}},
			{Code: "new RegExp((String?.raw)`a`);", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/a/;"}}}}},
			{Code: "new RegExp('+');", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp"}}},
			{Code: "new RegExp('*');", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp"}}},
			{Code: "RegExp('+');", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp"}}},
			{Code: "RegExp('*');", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp"}}},
			{Code: "new RegExp('+', 'g');", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp"}}},
			{Code: "new RegExp('*', 'g');", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp"}}},
			{Code: "RegExp('+', 'g');", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp"}}},
			{Code: "RegExp('*', 'g');", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp"}}},
			// SKIP: rslint does not emulate ESLint ecmaVersion-specific regex literal validation.
			{Code: "RegExp('abc', 'u');", Skip: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp"}}},
			// SKIP: rslint does not emulate ESLint ecmaVersion-specific d flag validation.
			{Code: "new RegExp('abc', 'd');", Skip: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp"}}},
			{Code: "RegExp('abc', 'd');", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/abc/d;"}}}}},
			{Code: "RegExp('\\\\\\\\', '');", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/\\\\/;"}}}}},
			{Code: "RegExp('\\n', '');", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/\\n/;"}}}}},
			{Code: "RegExp('\\n\\n', '');", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/\\n\\n/;"}}}}},
			{Code: "RegExp('\\t', '');", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/\\t/;"}}}}},
			{Code: "RegExp('\\t\\t', '');", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/\\t\\t/;"}}}}},
			{Code: "RegExp('\\r\\n', '');", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/\\r\\n/;"}}}}},
			{Code: "RegExp('\\u1234', 'g')", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp"}}},
			{Code: "RegExp('\\u{1234}', 'g')", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp"}}},
			{Code: "RegExp('\\u{11111}', 'g')", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp"}}},
			{Code: "RegExp('\\v', '');", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/\\v/;"}}}}},
			{Code: "RegExp('\\v\\v', '');", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/\\v\\v/;"}}}}},
			{Code: "RegExp('\\f', '');", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/\\f/;"}}}}},
			{Code: "RegExp('\\f\\f', '');", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/\\f\\f/;"}}}}},
			{Code: "RegExp('\\\\b', '');", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/\\b/;"}}}}},
			{Code: "RegExp('\\\\b\\\\b', '');", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/\\b\\b/;"}}}}},
			{Code: "new RegExp('\\\\B\\\\b', '');", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/\\B\\b/;"}}}}},
			{Code: "RegExp('\\\\w', '');", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/\\w/;"}}}}},
			{Code: "new globalThis.RegExp('\\\\W', '');", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/\\W/;"}}}}},
			{Code: "RegExp('\\\\s', '');", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/\\s/;"}}}}},
			{Code: "new RegExp('\\\\S', '')", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/\\S/"}}}}},
			{Code: "globalThis.RegExp('\\\\d', '');", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/\\d/;"}}}}},
			{Code: "globalThis.RegExp('\\\\D', '')", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/\\D/"}}}}},
			{Code: "globalThis.RegExp('\\\\\\\\\\\\D', '')", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/\\\\\\D/"}}}}},
			{Code: "new RegExp('\\\\D\\\\D', '')", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/\\D\\D/"}}}}},
			{Code: "new globalThis.RegExp('\\\\0\\\\0', '');", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/\\0\\0/;"}}}}},
			{Code: "new RegExp('\\\\0\\\\0', '');", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/\\0\\0/;"}}}}},
			{Code: "new RegExp('\\0\\0', 'g');", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp"}}},
			{Code: "RegExp('\\\\0\\\\0\\\\0', '')", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/\\0\\0\\0/"}}}}},
			{Code: "RegExp('\\\\78\\\\126\\\\5934', '')", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/\\78\\126\\5934/"}}}}},
			{Code: "new window['RegExp']('\\\\x56\\\\x78\\\\x45', '');", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/\\x56\\x78\\x45/;"}}}}},
			{Code: "a in(RegExp('abc'))", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "a in(/abc/)"}}}}},
			{Code: "x = y\n            RegExp(\"foo\").test(x) ? bar() : baz()", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp"}}},
			{Code: "func(new RegExp(String.raw`\\w{1, 2`, 'u'),new RegExp(String.raw`\\w{1, 2`, 'u'))", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp"}, {MessageId: "unexpectedRegExp"}}},
			{Code: "x = y;\n            RegExp(\"foo\").test(x) ? bar() : baz()", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "x = y;\n            /foo/.test(x) ? bar() : baz()"}}}}},
			{Code: "typeof RegExp(\"foo\")", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "typeof /foo/"}}}}},
			{Code: "RegExp(\"foo\") instanceof RegExp(String.raw`blahblah`, 'g') ? typeof new RegExp('(\\\\p{Emoji_Presentation})\\\\1', `ug`) : false", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/foo/ instanceof RegExp(String.raw`blahblah`, 'g') ? typeof new RegExp('(\\\\p{Emoji_Presentation})\\\\1', `ug`) : false"}}}, {MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "RegExp(\"foo\") instanceof /blahblah/g ? typeof new RegExp('(\\\\p{Emoji_Presentation})\\\\1', `ug`) : false"}}}, {MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "RegExp(\"foo\") instanceof RegExp(String.raw`blahblah`, 'g') ? typeof /(\\p{Emoji_Presentation})\\1/ug : false"}}}}},
			{Code: "[   new RegExp(`someregular`)]", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "[   /someregular/]"}}}}},
			{Code: "const totallyValidatesEmails = new RegExp(\"\\\\S+@(\\\\S+\\\\.)+\\\\S+\")\n            if (typeof totallyValidatesEmails === 'object') {\n                runSomethingThatExists(Regexp('stuff'))\n            }", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "const totallyValidatesEmails = /\\S+@(\\S+\\.)+\\S+/\n            if (typeof totallyValidatesEmails === 'object') {\n                runSomethingThatExists(Regexp('stuff'))\n            }"}}}}},
			{Code: "!new RegExp('^Hey, ', 'u') && new RegExp('jk$') && ~new RegExp('^Sup, ') || new RegExp('hi') + new RegExp('person') === -new RegExp('hi again') ? 5 * new RegExp('abc') : 'notregbutstring'", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "!/^Hey, /u && new RegExp('jk$') && ~new RegExp('^Sup, ') || new RegExp('hi') + new RegExp('person') === -new RegExp('hi again') ? 5 * new RegExp('abc') : 'notregbutstring'"}}}, {MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "!new RegExp('^Hey, ', 'u') && /jk$/ && ~new RegExp('^Sup, ') || new RegExp('hi') + new RegExp('person') === -new RegExp('hi again') ? 5 * new RegExp('abc') : 'notregbutstring'"}}}, {MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "!new RegExp('^Hey, ', 'u') && new RegExp('jk$') && ~/^Sup, / || new RegExp('hi') + new RegExp('person') === -new RegExp('hi again') ? 5 * new RegExp('abc') : 'notregbutstring'"}}}, {MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "!new RegExp('^Hey, ', 'u') && new RegExp('jk$') && ~new RegExp('^Sup, ') || /hi/ + new RegExp('person') === -new RegExp('hi again') ? 5 * new RegExp('abc') : 'notregbutstring'"}}}, {MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "!new RegExp('^Hey, ', 'u') && new RegExp('jk$') && ~new RegExp('^Sup, ') || new RegExp('hi') + /person/ === -new RegExp('hi again') ? 5 * new RegExp('abc') : 'notregbutstring'"}}}, {MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "!new RegExp('^Hey, ', 'u') && new RegExp('jk$') && ~new RegExp('^Sup, ') || new RegExp('hi') + new RegExp('person') === -/hi again/ ? 5 * new RegExp('abc') : 'notregbutstring'"}}}, {MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "!new RegExp('^Hey, ', 'u') && new RegExp('jk$') && ~new RegExp('^Sup, ') || new RegExp('hi') + new RegExp('person') === -new RegExp('hi again') ? 5 * /abc/ : 'notregbutstring'"}}}}},
			{Code: "#!/usr/bin/sh\n            RegExp(\"foo\")", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "#!/usr/bin/sh\n            /foo/"}}}}},
			{Code: "async function abc(){await new RegExp(\"foo\")}", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp"}}},
			{Code: "function* abc(){yield new RegExp(\"foo\")}", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp"}}},
			{Code: "function* abc(){yield* new RegExp(\"foo\")}", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "function* abc(){yield* /foo/}"}}}}},
			{Code: "console.log({ ...new RegExp('a') })", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "console.log({ .../a/ })"}}}}},
			{Code: "delete RegExp('a');", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "delete /a/;"}}}}},
			{Code: "void RegExp('a');", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "void /a/;"}}}}},
			{Code: "new RegExp(\"\\\\S+@(\\\\S+\\\\.)+\\\\S+\")**RegExp('a')", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/\\S+@(\\S+\\.)+\\S+/**RegExp('a')"}}}, {MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "new RegExp(\"\\\\S+@(\\\\S+\\\\.)+\\\\S+\")**/a/"}}}}},
			{Code: "new RegExp(\"\\\\S+@(\\\\S+\\\\.)+\\\\S+\")%RegExp('a')", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/\\S+@(\\S+\\.)+\\S+/%RegExp('a')"}}}, {MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "new RegExp(\"\\\\S+@(\\\\S+\\\\.)+\\\\S+\")%/a/"}}}}},
			{Code: "a in RegExp('abc')", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "a in /abc/"}}}}},
			{Code: "\n            /abc/ == new RegExp('cba');\n            ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "\n            /abc/ == /cba/;\n            "}}}}},
			{Code: "\n            /abc/ === new RegExp('cba');\n            ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "\n            /abc/ === /cba/;\n            "}}}}},
			{Code: "\n            /abc/ != new RegExp('cba');\n            ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "\n            /abc/ != /cba/;\n            "}}}}},
			{Code: "\n            /abc/ !== new RegExp('cba');\n            ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "\n            /abc/ !== /cba/;\n            "}}}}},
			{Code: "\n            /abc/ > new RegExp('cba');\n            ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "\n            /abc/ > /cba/;\n            "}}}}},
			{Code: "\n            /abc/ < new RegExp('cba');\n            ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "\n            /abc/ < /cba/;\n            "}}}}},
			{Code: "\n            /abc/ >= new RegExp('cba');\n            ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "\n            /abc/ >= /cba/;\n            "}}}}},
			{Code: "\n            /abc/ <= new RegExp('cba');\n            ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "\n            /abc/ <= /cba/;\n            "}}}}},
			{Code: "\n            /abc/ << new RegExp('cba');\n            ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "\n            /abc/ << /cba/;\n            "}}}}},
			{Code: "\n            /abc/ >> new RegExp('cba');\n            ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "\n            /abc/ >> /cba/;\n            "}}}}},
			{Code: "\n            /abc/ >>> new RegExp('cba');\n            ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "\n            /abc/ >>> /cba/;\n            "}}}}},
			{Code: "\n            /abc/ ^ new RegExp('cba');\n            ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "\n            /abc/ ^ /cba/;\n            "}}}}},
			{Code: "\n            /abc/ & new RegExp('cba');\n            ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "\n            /abc/ & /cba/;\n            "}}}}},
			{Code: "\n            /abc/ | new RegExp('cba');\n            ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "\n            /abc/ | /cba/;\n            "}}}}},
			{Code: "\n            null ?? new RegExp('blah')\n            ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "\n            null ?? /blah/\n            "}}}}},
			{Code: "\n            abc *= new RegExp('blah')\n            ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "\n            abc *= /blah/\n            "}}}}},
			{Code: "\n            console.log({a: new RegExp('sup')})\n            ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "\n            console.log({a: /sup/})\n            "}}}}},
			{Code: "\n            console.log(() => {new RegExp('sup')})\n            ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "\n            console.log(() => {/sup/})\n            "}}}}},
			{Code: "\n            function abc() {new RegExp('sup')}\n            ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "\n            function abc() {/sup/}\n            "}}}}},
			{Code: "\n            function abc() {return new RegExp('sup')}\n            ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "\n            function abc() {return /sup/}\n            "}}}}},
			{Code: "\n            abc <<= new RegExp('cba');\n            ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "\n            abc <<= /cba/;\n            "}}}}},
			{Code: "\n            abc >>= new RegExp('cba');\n            ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "\n            abc >>= /cba/;\n            "}}}}},
			{Code: "\n            abc >>>= new RegExp('cba');\n            ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "\n            abc >>>= /cba/;\n            "}}}}},
			{Code: "\n            abc ^= new RegExp('cba');\n            ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "\n            abc ^= /cba/;\n            "}}}}},
			{Code: "\n            abc &= new RegExp('cba');\n            ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "\n            abc &= /cba/;\n            "}}}}},
			{Code: "\n            abc |= new RegExp('cba');\n            ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "\n            abc |= /cba/;\n            "}}}}},
			{Code: "\n            abc ??= new RegExp('cba');\n            ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "\n            abc ??= /cba/;\n            "}}}}},
			{Code: "\n            abc &&= new RegExp('cba');\n            ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "\n            abc &&= /cba/;\n            "}}}}},
			{Code: "\n            abc ||= new RegExp('cba');\n            ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "\n            abc ||= /cba/;\n            "}}}}},
			{Code: "\n            abc **= new RegExp('blah')\n            ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "\n            abc **= /blah/\n            "}}}}},
			{Code: "\n            abc /= new RegExp('blah')\n            ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "\n            abc /= /blah/\n            "}}}}},
			{Code: "\n            abc += new RegExp('blah')\n            ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "\n            abc += /blah/\n            "}}}}},
			{Code: "\n            abc -= new RegExp('blah')\n            ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "\n            abc -= /blah/\n            "}}}}},
			{Code: "\n            abc %= new RegExp('blah')\n            ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "\n            abc %= /blah/\n            "}}}}},
			{Code: "\n            () => new RegExp('blah')\n            ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "\n            () => /blah/\n            "}}}}},
			{Code: "a/RegExp(\"foo\")in b", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "a/ /foo/ in b"}}}}},
			{Code: "a/RegExp(\"foo\")instanceof b", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "a/ /foo/ instanceof b"}}}}},
			{Code: "do RegExp(\"foo\")\nwhile (true);", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "do /foo/\nwhile (true);"}}}}},
			{Code: "for(let i;i<5;i++) { break\nnew RegExp('search')}", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "for(let i;i<5;i++) { break\n/search/}"}}}}},
			{Code: "for(let i;i<5;i++) { continue\nnew RegExp('search')}", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "for(let i;i<5;i++) { continue\n/search/}"}}}}},
			{Code: "\n            switch (value) {\n                case \"possibility\":\n                    console.log('possibility matched')\n                case RegExp('myReg').toString():\n                    console.log('matches a regexp\\' toString value')\n                    break;\n            }\n            ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "\n            switch (value) {\n                case \"possibility\":\n                    console.log('possibility matched')\n                case /myReg/.toString():\n                    console.log('matches a regexp\\' toString value')\n                    break;\n            }\n            "}}}}},
			{Code: "throw new RegExp('abcdefg') // fail with a regular expression", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "throw /abcdefg/ // fail with a regular expression"}}}}},
			{Code: "for (value of new RegExp('something being searched')) { console.log(value) }", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp"}}},
			{Code: "(async function(){for await (value of new RegExp('something being searched')) { console.log(value) }})()", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp"}}},
			{Code: "for (value in new RegExp('something being searched')) { console.log(value) }", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "for (value in /something being searched/) { console.log(value) }"}}}}},
			{Code: "if (condition1 && condition2) new RegExp('avalue').test(str);", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp"}}},
			{Code: "debugger\nnew RegExp('myReg')", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "debugger\n/myReg/"}}}}},
			{Code: "RegExp(\"\\\\\\n\")", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/\\n/"}}}}},
			{Code: "RegExp(\"\\\\\\t\")", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/\\t/"}}}}},
			{Code: "RegExp(\"\\\\\\f\")", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/\\f/"}}}}},
			{Code: "RegExp(\"\\\\\\v\")", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/\\v/"}}}}},
			{Code: "RegExp(\"\\\\\\r\")", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/\\r/"}}}}},
			{Code: "new RegExp(\"\t\")", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/\\t/"}}}}},
			{Code: "new RegExp(\"/\")", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/\\//"}}}}},
			{Code: "new RegExp(\"\\.\")", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/./"}}}}},
			{Code: "new RegExp(\"\\\\.\")", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/\\./"}}}}},
			{Code: "new RegExp(\"\\\\\\n\\\\\\n\")", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/\\n\\n/"}}}}},
			{Code: "new RegExp(\"\\\\\\n\\\\\\f\\\\\\n\")", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/\\n\\f\\n/"}}}}},
			{Code: "new RegExp(\"\\u000A\\u000A\");", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/\\n\\n/;"}}}}},
			{Code: "new RegExp('mysafereg' /* comment explaining its safety */)", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp"}}},
			{Code: "new RegExp('[[A--B]]', 'v')", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/[[A--B]]/v"}}}}},
			// SKIP: rslint does not emulate ESLint ecmaVersion-specific v flag validation.
			{Code: "new RegExp('[[A--B]]', 'v')", Skip: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp"}}},
			{Code: "new RegExp('[[A&&&]]', 'v')", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp"}}},
			{Code: "new RegExp('a', 'uv')", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp"}}},
			{Code: "new RegExp(/a/, 'v')", Options: []interface{}{map[string]interface{}{"disallowRedundantWrapping": true}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRedundantRegExpWithFlags", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteralAndFlags", Output: "/a/v"}}}}},
			// SKIP: rslint does not emulate ESLint ecmaVersion-specific v flag validation.
			{Code: "new RegExp(/a/, 'v')", Options: []interface{}{map[string]interface{}{"disallowRedundantWrapping": true}}, Skip: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRedundantRegExpWithFlags"}}},
			{Code: "new RegExp(/a/g, 'v')", Options: []interface{}{map[string]interface{}{"disallowRedundantWrapping": true}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRedundantRegExpWithFlags", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteralAndFlags", Output: "/a/v"}, {MessageId: "replaceWithIntendedLiteralAndFlags", Output: "/a/gv"}}}}},
			{Code: "new RegExp(/[[A--B]]/v, 'g')", Options: []interface{}{map[string]interface{}{"disallowRedundantWrapping": true}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRedundantRegExpWithFlags", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithIntendedLiteralAndFlags", Output: "/[[A--B]]/vg"}}}}},
			{Code: "new RegExp(/a/u, 'v')", Options: []interface{}{map[string]interface{}{"disallowRedundantWrapping": true}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRedundantRegExpWithFlags", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteralAndFlags", Output: "/a/v"}}}}},
			{Code: "new RegExp(/a/v, 'u')", Options: []interface{}{map[string]interface{}{"disallowRedundantWrapping": true}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRedundantRegExpWithFlags", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteralAndFlags", Output: "/a/u"}}}}},
			{Code: "new RegExp(/[[A--B]]/v, 'u')", Options: []interface{}{map[string]interface{}{"disallowRedundantWrapping": true}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRedundantRegExpWithFlags"}}},
			{Code: "new RegExp('(?i:foo)bar')", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "/(?i:foo)bar/"}}}}},
			// SKIP: rslint does not emulate ESLint ecmaVersion-specific inline modifier validation.
			{Code: "new RegExp('(?i:foo)bar')", Skip: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp"}}},
			{Code: "var regex = new RegExp('foo', 'u');", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedRegExp", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "replaceWithLiteral", Output: "var regex = /foo/u;"}}}}},
		},
	)
}
