package code_path_analysis

import (
	"strconv"
	"sync/atomic"
)

type AutoGeneratedId = uint32

// A generator for unique Ids.
type IdGenerator struct {
	prefix string
	n      AutoGeneratedId
}

func NewIdGenerator(prefix string) *IdGenerator {
	return &IdGenerator{
		prefix: prefix,
		n:      0,
	}
}

func (g *IdGenerator) Next() string {
	next := atomic.AddUint32(&g.n, 1)
	g.n = next

	return g.prefix + strconv.FormatUint(uint64(next), 10)
}
