// Upstream cases from eslint-plugin-n v18.3.0, using eslint-plugin-es-x v7.8.0.
// https://github.com/eslint-community/eslint-plugin-n/blob/v18.3.0/tests/lib/rules/no-unsupported-features/es-syntax.js
// Complete messages and ranges were checked with the pinned ESLint rule.
package es_syntax

import (
	"maps"
	"testing"

	"github.com/microsoft/TypeScript/tsc/shim/tspath"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/fixtures"
	"github.com/web-infra-dev/rslint/internal/rule"
	"github.com/web-infra-dev/rslint/internal/rule_tester"
	"github.com/web-infra-dev/rslint/internal/testutil/txtarfs"
	"github.com/web-infra-dev/rslint/internal/utils"
)

func syntaxRoot(t *testing.T) rule_tester.Root {
	t.Helper()
	base := fixtures.GetRootDir()
	directory := tspath.ResolvePath(base.Dir, "es-syntax-fixtures")
	archive := txtarfs.MustParseFile(t, "testdata/upstream.txtar")
	names, err := archive.FileNames("")
	if err != nil {
		t.Fatal(err)
	}
	files := map[string]string{}
	for _, name := range names {
		data, err := archive.ReadFile(name)
		if err != nil {
			t.Fatal(err)
		}
		files[tspath.ResolvePath(directory, name)] = string(data)
	}
	return rule_tester.Root{Dir: directory, FS: utils.NewOverlayVFS(base.FS, files)}
}
func runSyntaxTests(t *testing.T, valid []rule_tester.ValidTestCase, invalid []rule_tester.InvalidTestCase) {
	t.Helper()
	for i := range valid {
		if valid[i].FileName == "" {
			valid[i].FileName = "input.js"
		}
		if valid[i].LanguageOptions.SourceType == "" {
			valid[i].LanguageOptions.SourceType = "commonjs"
		}
	}
	for i := range invalid {
		if invalid[i].FileName == "" {
			invalid[i].FileName = "input.js"
		}
		if invalid[i].LanguageOptions.SourceType == "" {
			invalid[i].LanguageOptions.SourceType = "commonjs"
		}
	}
	// The upstream mirror uses Espree without a TypeScript project.
	syntaxRule := ESSyntaxRule
	syntaxRule.Run = func(ctx rule.RuleContext, options []any) rule.RuleListeners {
		ctx.TypeChecker = nil
		return ESSyntaxRule.Run(ctx, options)
	}
	rule_tester.RunRuleTester(syntaxRoot(t), "tsconfig.json", t, &syntaxRule, valid, invalid)
}
func TestESSyntaxUpstream(t *testing.T) {
	groups := []struct {
		name    string
		ignores []string
		valid   []rule_tester.ValidTestCase
		invalid []rule_tester.InvalidTestCase
	}{

		{name: "arrowFunctions", ignores: []string{"arrowFunctions"}, valid: []rule_tester.ValidTestCase{
			{Code: "function f() {}",
				Options: []any{map[string]any{"version": "3.9.9"}}},
			{Code: "!function f() {}",
				Options: []any{map[string]any{"version": "3.9.9"}}},
			{Code: "(() => 1)",
				Options: []any{map[string]any{"version": "4.0.0"}}},
			{Code: "(() => {})",
				Options: []any{map[string]any{"version": "4.0.0"}}},
		}, invalid: []rule_tester.InvalidTestCase{
			{Code: "(() => 1)",
				Options: []any{map[string]any{"version": "3.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'arrow-functions' is not supported until Node.js >=4.0.0. The configured version range is '3.9.9'.", Line: 1, Column: 2, EndLine: 1, EndColumn: 9}}},
			{Code: "(() => {})",
				Options: []any{map[string]any{"version": "3.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'arrow-functions' is not supported until Node.js >=4.0.0. The configured version range is '3.9.9'.", Line: 1, Column: 2, EndLine: 1, EndColumn: 10}}},
		}},
		{name: "binaryNumericLiterals", ignores: []string{"binaryNumericLiterals"}, valid: []rule_tester.ValidTestCase{
			{Code: "0x01",
				Options: []any{map[string]any{"version": "3.9.9"}}},
			{Code: "1",
				Options: []any{map[string]any{"version": "3.9.9"}}},
			{Code: "0b01",
				Options: []any{map[string]any{"version": "4.0.0"}}},
		}, invalid: []rule_tester.InvalidTestCase{
			{Code: "0b01",
				Options: []any{map[string]any{"version": "3.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'binary-numeric-literals' is not supported until Node.js >=4.0.0. The configured version range is '3.9.9'.", Line: 1, Column: 1, EndLine: 1, EndColumn: 5}}},
		}},
		{name: "blockScopedFunctions", ignores: []string{"blockScopedFunctions"}, valid: []rule_tester.ValidTestCase{
			{Code: "'use strict'; if (a) { function f() {} }",
				Options: []any{map[string]any{"version": "4.0.0"}}},
			{Code: "'use strict'; function wrap() { if (a) { function f() {} } }",
				Options: []any{map[string]any{"version": "4.0.0"}}},
			{Code: "function wrap() { 'use strict'; if (a) { function f() {} } }",
				Options: []any{map[string]any{"version": "4.0.0"}}},
			{Code: "if (a) { function f() {} }",
				Options: []any{map[string]any{"version": "6.0.0"}}},
		}, invalid: []rule_tester.InvalidTestCase{
			{Code: "'use strict'; if (a) { function f() {} }",
				Options: []any{map[string]any{"version": "3.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'block-scoped-functions' is not supported until Node.js >=4.0.0. The configured version range is '3.9.9'.", Line: 1, Column: 24, EndLine: 1, EndColumn: 39}}},
			{Code: "if (a) { function f() {} }",
				Options: []any{map[string]any{"version": "5.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'block-scoped-functions' is not supported until Node.js >=6.0.0. The configured version range is '5.9.9'.", Line: 1, Column: 10, EndLine: 1, EndColumn: 25}}},
		}},
		{name: "blockScopedVariables", ignores: []string{"blockScopedVariables"}, valid: []rule_tester.ValidTestCase{
			{Code: "var a = 0",
				Options: []any{map[string]any{"version": "3.9.9"}}},
			{Code: "'use strict'; let a = 0",
				Options: []any{map[string]any{"version": "4.0.0"}}},
			{Code: "'use strict'; const a = 0",
				Options: []any{map[string]any{"version": "4.0.0"}}},
			{Code: "'use strict'; function wrap() { const a = 0 }",
				Options: []any{map[string]any{"version": "4.0.0"}}},
			{Code: "function wrap() { 'use strict'; const a = 0 }",
				Options: []any{map[string]any{"version": "4.0.0"}}},
			{Code: "let a = 0",
				Options: []any{map[string]any{"version": "6.0.0"}}},
			{Code: "const a = 0",
				Options: []any{map[string]any{"version": "6.0.0"}}},
		}, invalid: []rule_tester.InvalidTestCase{
			{Code: "'use strict'; let a = 0",
				Options: []any{map[string]any{"version": "3.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'block-scoped-variables' is not supported until Node.js >=4.0.0. The configured version range is '3.9.9'.", Line: 1, Column: 15, EndLine: 1, EndColumn: 24}}},
			{Code: "'use strict'; const a = 0",
				Options: []any{map[string]any{"version": "3.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'block-scoped-variables' is not supported until Node.js >=4.0.0. The configured version range is '3.9.9'.", Line: 1, Column: 15, EndLine: 1, EndColumn: 26}}},
			{Code: "let a = 0",
				Options: []any{map[string]any{"version": "5.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'block-scoped-variables' is not supported until Node.js >=6.0.0. The configured version range is '5.9.9'.", Line: 1, Column: 1, EndLine: 1, EndColumn: 10}}},
			{Code: "const a = 0",
				Options: []any{map[string]any{"version": "5.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'block-scoped-variables' is not supported until Node.js >=6.0.0. The configured version range is '5.9.9'.", Line: 1, Column: 1, EndLine: 1, EndColumn: 12}}},
		}},
		{name: "classes", ignores: []string{"classes"}, valid: []rule_tester.ValidTestCase{
			{Code: "'use strict'; class A {}",
				Options: []any{map[string]any{"version": "4.0.0"}}},
			{Code: "'use strict'; function wrap() { class A {} }",
				Options: []any{map[string]any{"version": "4.0.0"}}},
			{Code: "function wrap() { 'use strict'; class A {} }",
				Options: []any{map[string]any{"version": "4.0.0"}}},
			{Code: "class A {}",
				Options: []any{map[string]any{"version": "6.0.0"}}},
		}, invalid: []rule_tester.InvalidTestCase{
			{Code: "'use strict'; class A {}",
				Options: []any{map[string]any{"version": "3.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'classes' is not supported until Node.js >=4.0.0. The configured version range is '3.9.9'.", Line: 1, Column: 15, EndLine: 1, EndColumn: 25}}},
			{Code: "class A {}",
				Options: []any{map[string]any{"version": "5.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'classes' is not supported until Node.js >=6.0.0. The configured version range is '5.9.9'.", Line: 1, Column: 1, EndLine: 1, EndColumn: 11}}},
		}},
		{name: "computedProperties", ignores: []string{"computedProperties"}, valid: []rule_tester.ValidTestCase{
			{Code: "({ 0: 0, key: 1, 'key2': 2, key3, key4() {} })",
				Options: []any{map[string]any{"version": "3.9.9", "ignores": []any{"propertyShorthands"}}}},
			{Code: "({ [key]: 1 })",
				Options: []any{map[string]any{"version": "4.0.0"}}},
			{Code: "({ [key]() {} })",
				Options: []any{map[string]any{"version": "4.0.0"}}},
			{Code: "class A { [key]() {} }",
				Options: []any{map[string]any{"version": "4.0.0", "ignores": []any{"classes"}}}},
			{Code: "(class { [key]() {} })",
				Options: []any{map[string]any{"version": "4.0.0", "ignores": []any{"classes"}}}},
		}, invalid: []rule_tester.InvalidTestCase{
			{Code: "({ [key]: 1 })",
				Options: []any{map[string]any{"version": "3.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'computed-properties' is not supported until Node.js >=4.0.0. The configured version range is '3.9.9'.", Line: 1, Column: 4, EndLine: 1, EndColumn: 12}}},
			{Code: "({ [key]() {} })",
				Options: []any{map[string]any{"version": "3.9.9", "ignores": []any{"propertyShorthands"}}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'computed-properties' is not supported until Node.js >=4.0.0. The configured version range is '3.9.9'.", Line: 1, Column: 4, EndLine: 1, EndColumn: 14}}},
			{Code: "class A { [key]() {} }",
				Options: []any{map[string]any{"version": "3.9.9", "ignores": []any{"classes"}}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'computed-properties' is not supported until Node.js >=4.0.0. The configured version range is '3.9.9'.", Line: 1, Column: 11, EndLine: 1, EndColumn: 21}}},
			{Code: "(class { [key]() {} })",
				Options: []any{map[string]any{"version": "3.9.9", "ignores": []any{"classes"}}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'computed-properties' is not supported until Node.js >=4.0.0. The configured version range is '3.9.9'.", Line: 1, Column: 10, EndLine: 1, EndColumn: 20}}},
		}},
		{name: "defaultParameters", ignores: []string{"defaultParameters"}, valid: []rule_tester.ValidTestCase{
			{Code: "a = 0",
				Options: []any{map[string]any{"version": "5.9.9"}}},
			{Code: "var a = 0",
				Options: []any{map[string]any{"version": "5.9.9"}}},
			{Code: "var [a = 0] = []",
				Options: []any{map[string]any{"version": "5.9.9", "ignores": []any{"destructuring"}}}},
			{Code: "var {a = 0} = {}",
				Options: []any{map[string]any{"version": "5.9.9", "ignores": []any{"destructuring"}}}},
			{Code: "function f(a = 0) {}",
				Options: []any{map[string]any{"version": "6.0.0"}}},
			{Code: "(function(a = 0) {})",
				Options: []any{map[string]any{"version": "6.0.0"}}},
			{Code: "((a = 0) => a)",
				Options: []any{map[string]any{"version": "6.0.0"}}},
			{Code: "({ key(a = 0) {} })",
				Options: []any{map[string]any{"version": "6.0.0"}}},
			{Code: "class A { key(a = 0) {} }",
				Options: []any{map[string]any{"version": "6.0.0"}}},
			{Code: "(class { key(a = 0) {} })",
				Options: []any{map[string]any{"version": "6.0.0"}}},
		}, invalid: []rule_tester.InvalidTestCase{
			{Code: "function f(a = 0) {}",
				Options: []any{map[string]any{"version": "5.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'default-parameters' is not supported until Node.js >=6.0.0. The configured version range is '5.9.9'.", Line: 1, Column: 12, EndLine: 1, EndColumn: 17}}},
			{Code: "(function(a = 0) {})",
				Options: []any{map[string]any{"version": "5.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'default-parameters' is not supported until Node.js >=6.0.0. The configured version range is '5.9.9'.", Line: 1, Column: 11, EndLine: 1, EndColumn: 16}}},
			{Code: "((a = 0) => a)",
				Options: []any{map[string]any{"version": "5.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'default-parameters' is not supported until Node.js >=6.0.0. The configured version range is '5.9.9'.", Line: 1, Column: 3, EndLine: 1, EndColumn: 8}}},
			{Code: "({ key(a = 0) {} })",
				Options: []any{map[string]any{"version": "5.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'default-parameters' is not supported until Node.js >=6.0.0. The configured version range is '5.9.9'.", Line: 1, Column: 8, EndLine: 1, EndColumn: 13}}},
			{Code: "class A { key(a = 0) {} }",
				Options: []any{map[string]any{"version": "5.9.9", "ignores": []any{"classes"}}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'default-parameters' is not supported until Node.js >=6.0.0. The configured version range is '5.9.9'.", Line: 1, Column: 15, EndLine: 1, EndColumn: 20}}},
			{Code: "(class { key(a = 0) {} })",
				Options: []any{map[string]any{"version": "5.9.9", "ignores": []any{"classes"}}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'default-parameters' is not supported until Node.js >=6.0.0. The configured version range is '5.9.9'.", Line: 1, Column: 14, EndLine: 1, EndColumn: 19}}},
		}},
		{name: "destructuring", ignores: []string{"destructuring"}, valid: []rule_tester.ValidTestCase{
			{Code: "function f(a = 0) {}",
				Options: []any{map[string]any{"version": "5.9.9", "ignores": []any{"defaultParameters"}}}},
			{Code: "[...a]",
				Options: []any{map[string]any{"version": "5.9.9"}}},
			{Code: "f(...a)",
				Options: []any{map[string]any{"version": "5.9.9"}}},
			{Code: "new A(...a)",
				Options: []any{map[string]any{"version": "5.9.9"}}},
			{Code: "var a = {}",
				Options: []any{map[string]any{"version": "5.9.9"}}},
			{Code: "var {a} = {}",
				Options: []any{map[string]any{"version": "6.0.0"}}},
			{Code: "var [a] = {}",
				Options: []any{map[string]any{"version": "6.0.0"}}},
			{Code: "function f({a}) {}",
				Options: []any{map[string]any{"version": "6.0.0"}}},
			{Code: "function f([a]) {}",
				Options: []any{map[string]any{"version": "6.0.0"}}},
		}, invalid: []rule_tester.InvalidTestCase{
			{Code: "var {a} = {}",
				Options: []any{map[string]any{"version": "5.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'destructuring' is not supported until Node.js >=6.0.0. The configured version range is '5.9.9'.", Line: 1, Column: 5, EndLine: 1, EndColumn: 8}}},
			{Code: "var [a] = {}",
				Options: []any{map[string]any{"version": "5.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'destructuring' is not supported until Node.js >=6.0.0. The configured version range is '5.9.9'.", Line: 1, Column: 5, EndLine: 1, EndColumn: 8}}},
			{Code: "function f({a}) {}",
				Options: []any{map[string]any{"version": "5.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'destructuring' is not supported until Node.js >=6.0.0. The configured version range is '5.9.9'.", Line: 1, Column: 12, EndLine: 1, EndColumn: 15}}},
			{Code: "function f([a]) {}",
				Options: []any{map[string]any{"version": "5.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'destructuring' is not supported until Node.js >=6.0.0. The configured version range is '5.9.9'.", Line: 1, Column: 12, EndLine: 1, EndColumn: 15}}},
			{Code: "var {a: {b: [c = 0]}} = {}",
				Options: []any{map[string]any{"version": "5.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'destructuring' is not supported until Node.js >=6.0.0. The configured version range is '5.9.9'.", Line: 1, Column: 5, EndLine: 1, EndColumn: 22}}},
			{Code: "var [{a: [b = 0]}] = {}",
				Options: []any{map[string]any{"version": "5.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'destructuring' is not supported until Node.js >=6.0.0. The configured version range is '5.9.9'.", Line: 1, Column: 5, EndLine: 1, EndColumn: 19}}},
			{Code: "function f({a: {b: [c = 0]}}) {}",
				Options: []any{map[string]any{"version": "5.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'destructuring' is not supported until Node.js >=6.0.0. The configured version range is '5.9.9'.", Line: 1, Column: 12, EndLine: 1, EndColumn: 29}}},
			{Code: "function f([{a: [b = 0]}]) {}",
				Options: []any{map[string]any{"version": "5.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'destructuring' is not supported until Node.js >=6.0.0. The configured version range is '5.9.9'.", Line: 1, Column: 12, EndLine: 1, EndColumn: 26}}},
		}},
		{name: "forOfLoops", ignores: []string{"forOfLoops"}, valid: []rule_tester.ValidTestCase{
			{Code: "for (;;);",
				Options: []any{map[string]any{"version": "0.11.9"}}},
			{Code: "for (a in b);",
				Options: []any{map[string]any{"version": "0.11.9"}}},
			{Code: "for (var a in b);",
				Options: []any{map[string]any{"version": "0.11.9"}}},
			{Code: "for (a of b);",
				Options: []any{map[string]any{"version": "0.12.0"}}},
			{Code: "for (var a of b);",
				Options: []any{map[string]any{"version": "0.12.0"}}},
		}, invalid: []rule_tester.InvalidTestCase{
			{Code: "for (a of b);",
				Options: []any{map[string]any{"version": "0.11.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'for-of-loops' is not supported until Node.js >=0.12.0. The configured version range is '0.11.9'.", Line: 1, Column: 1, EndLine: 1, EndColumn: 14}}},
			{Code: "for (var a of b);",
				Options: []any{map[string]any{"version": "0.11.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'for-of-loops' is not supported until Node.js >=0.12.0. The configured version range is '0.11.9'.", Line: 1, Column: 1, EndLine: 1, EndColumn: 18}}},
			{Code: "async function wrap() { for await (var a of b); }",
				Options: []any{map[string]any{"version": "0.11.9", "ignores": []any{"asyncFunctions", "asyncIteration"}}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'for-of-loops' is not supported until Node.js >=0.12.0. The configured version range is '0.11.9'.", Line: 1, Column: 25, EndLine: 1, EndColumn: 48}}},
		}},
		{name: "generators", ignores: []string{"generators"}, valid: []rule_tester.ValidTestCase{
			{Code: "function f() {}",
				Options: []any{map[string]any{"version": "3.9.9"}}},
			{Code: "async function f() {}",
				Options: []any{map[string]any{"version": "3.9.9", "ignores": []any{"asyncFunctions"}}}},
			{Code: "function* f() {}",
				Options: []any{map[string]any{"version": "4.0.0"}}},
			{Code: "(function*() {})",
				Options: []any{map[string]any{"version": "4.0.0"}}},
			{Code: "({ *f() {} })",
				Options: []any{map[string]any{"version": "4.0.0", "ignores": []any{"propertyShorthands"}}}},
			{Code: "class A { *f() {} }",
				Options: []any{map[string]any{"version": "4.0.0", "ignores": []any{"classes"}}}},
			{Code: "(class { *f() {} })",
				Options: []any{map[string]any{"version": "4.0.0", "ignores": []any{"classes"}}}},
		}, invalid: []rule_tester.InvalidTestCase{
			{Code: "function* f() {}",
				Options: []any{map[string]any{"version": "3.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'generators' is not supported until Node.js >=4.0.0. The configured version range is '3.9.9'.", Line: 1, Column: 1, EndLine: 1, EndColumn: 17}}},
			{Code: "(function*() {})",
				Options: []any{map[string]any{"version": "3.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'generators' is not supported until Node.js >=4.0.0. The configured version range is '3.9.9'.", Line: 1, Column: 2, EndLine: 1, EndColumn: 16}}},
			{Code: "({ *f() {} })",
				Options: []any{map[string]any{"version": "3.9.9", "ignores": []any{"propertyShorthands"}}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'generators' is not supported until Node.js >=4.0.0. The configured version range is '3.9.9'.", Line: 1, Column: 6, EndLine: 1, EndColumn: 11}}},
			{Code: "class A { *f() {} }",
				Options: []any{map[string]any{"version": "3.9.9", "ignores": []any{"classes"}}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'generators' is not supported until Node.js >=4.0.0. The configured version range is '3.9.9'.", Line: 1, Column: 13, EndLine: 1, EndColumn: 18}}},
			{Code: "(class { *f() {} })",
				Options: []any{map[string]any{"version": "3.9.9", "ignores": []any{"classes"}}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'generators' is not supported until Node.js >=4.0.0. The configured version range is '3.9.9'.", Line: 1, Column: 12, EndLine: 1, EndColumn: 17}}},
		}},
		{name: "modules", ignores: []string{"modules"}, valid: []rule_tester.ValidTestCase{
			{Code: "require('a')",
				Options: []any{map[string]any{"version": "0.0.0"}}},
			{Code: "module.exports = {}",
				Options: []any{map[string]any{"version": "0.0.0"}}},
			{Code: "exports.a = {}",
				Options: []any{map[string]any{"version": "0.0.0"}}},
			{Code: "import a from 'a'",
				Options:         []any{map[string]any{"version": "13.1.0", "ignores": []any{"modules"}}},
				LanguageOptions: rule.LanguageOptions{SourceType: "module"}},
			{Code: "export default {}",
				Options:         []any{map[string]any{"version": "13.1.0", "ignores": []any{"modules"}}},
				LanguageOptions: rule.LanguageOptions{SourceType: "module"}},
			{Code: "export const a = {}",
				Options:         []any{map[string]any{"version": "13.1.0", "ignores": []any{"modules"}}},
				LanguageOptions: rule.LanguageOptions{SourceType: "module"}},
			{Code: "export {}",
				Options:         []any{map[string]any{"version": "13.1.0", "ignores": []any{"modules"}}},
				LanguageOptions: rule.LanguageOptions{SourceType: "module"}},
		}, invalid: []rule_tester.InvalidTestCase{
			{Code: "import a from 'a'",
				Options:         []any{map[string]any{"version": "10.0.0"}},
				LanguageOptions: rule.LanguageOptions{SourceType: "module"},
				Errors:          []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'modules' is not supported until Node.js ^12.17.0 || >=13.2.0. The configured version range is '10.0.0'.", Line: 1, Column: 1, EndLine: 1, EndColumn: 18}}},
			{Code: "export default {}",
				Options:         []any{map[string]any{"version": "10.0.0"}},
				LanguageOptions: rule.LanguageOptions{SourceType: "module"},
				Errors:          []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'modules' is not supported until Node.js ^12.17.0 || >=13.2.0. The configured version range is '10.0.0'.", Line: 1, Column: 1, EndLine: 1, EndColumn: 18}}},
			{Code: "export const a = {}",
				Options:         []any{map[string]any{"version": "10.0.0"}},
				LanguageOptions: rule.LanguageOptions{SourceType: "module"},
				Errors:          []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'modules' is not supported until Node.js ^12.17.0 || >=13.2.0. The configured version range is '10.0.0'.", Line: 1, Column: 1, EndLine: 1, EndColumn: 20}}},
			{Code: "export {}",
				Options:         []any{map[string]any{"version": "10.0.0"}},
				LanguageOptions: rule.LanguageOptions{SourceType: "module"},
				Errors:          []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'modules' is not supported until Node.js ^12.17.0 || >=13.2.0. The configured version range is '10.0.0'.", Line: 1, Column: 1, EndLine: 1, EndColumn: 10}}},
		}},
		{name: "newTarget, new.target", ignores: []string{"newTarget", "new.target"}, valid: []rule_tester.ValidTestCase{
			{Code: "new target",
				Options: []any{map[string]any{"version": "4.9.9"}}},
			{Code: "class A { constructor() { new.target } }",
				Options: []any{map[string]any{"version": "5.0.0", "ignores": []any{"classes"}}}},
			{Code: "function A() { new.target }",
				Options: []any{map[string]any{"version": "5.0.0"}}},
		}, invalid: []rule_tester.InvalidTestCase{
			{Code: "class A { constructor() { new.target } }",
				Options: []any{map[string]any{"version": "4.9.9", "ignores": []any{"classes"}}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'new-target' is not supported until Node.js >=5.0.0. The configured version range is '4.9.9'.", Line: 1, Column: 27, EndLine: 1, EndColumn: 37}}},
			{Code: "function A() { new.target }",
				Options: []any{map[string]any{"version": "4.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'new-target' is not supported until Node.js >=5.0.0. The configured version range is '4.9.9'.", Line: 1, Column: 16, EndLine: 1, EndColumn: 26}}},
		}},
		{name: "objectSuperProperties", ignores: []string{"objectSuperProperties"}, valid: []rule_tester.ValidTestCase{
			{Code: "class A { foo() { super.foo } }",
				Options: []any{map[string]any{"version": "3.9.9", "ignores": []any{"classes"}}}},
			{Code: "(class { foo() { super.foo } })",
				Options: []any{map[string]any{"version": "3.9.9", "ignores": []any{"classes"}}}},
			{Code: "class A extends B { constructor() { super() } }",
				Options: []any{map[string]any{"version": "3.9.9", "ignores": []any{"classes"}}}},
			{Code: "({ foo() { super.foo } })",
				Options: []any{map[string]any{"version": "4.0.0", "ignores": []any{"propertyShorthands"}}}},
			{Code: "({ foo() { super.foo() } })",
				Options: []any{map[string]any{"version": "4.0.0", "ignores": []any{"propertyShorthands"}}}},
		}, invalid: []rule_tester.InvalidTestCase{
			{Code: "({ foo() { super.foo } })",
				Options: []any{map[string]any{"version": "3.9.9", "ignores": []any{"propertyShorthands"}}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'object-super-properties' is not supported until Node.js >=4.0.0. The configured version range is '3.9.9'.", Line: 1, Column: 12, EndLine: 1, EndColumn: 17}}},
			{Code: "({ foo() { super.foo() } })",
				Options: []any{map[string]any{"version": "3.9.9", "ignores": []any{"propertyShorthands"}}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'object-super-properties' is not supported until Node.js >=4.0.0. The configured version range is '3.9.9'.", Line: 1, Column: 12, EndLine: 1, EndColumn: 17}}},
		}},
		{name: "octalNumericLiterals", ignores: []string{"octalNumericLiterals"}, valid: []rule_tester.ValidTestCase{
			// tsgo rejects legacy octal literals (TS1121) before the rule runs.
			{Code: "0755", Skip: true,
				Options: []any{map[string]any{"version": "3.9.9"}}},
			{Code: "0x755",
				Options: []any{map[string]any{"version": "3.9.9"}}},
			{Code: "0X755",
				Options: []any{map[string]any{"version": "3.9.9"}}},
			{Code: "0b01",
				Options: []any{map[string]any{"version": "3.9.9", "ignores": []any{"binaryNumericLiterals"}}}},
			{Code: "0B01",
				Options: []any{map[string]any{"version": "3.9.9", "ignores": []any{"binaryNumericLiterals"}}}},
			{Code: "0o755",
				Options: []any{map[string]any{"version": "4.0.0"}}},
			{Code: "0O755",
				Options: []any{map[string]any{"version": "4.0.0"}}},
		}, invalid: []rule_tester.InvalidTestCase{
			{Code: "0o755",
				Options: []any{map[string]any{"version": "3.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'octal-numeric-literals' is not supported until Node.js >=4.0.0. The configured version range is '3.9.9'.", Line: 1, Column: 1, EndLine: 1, EndColumn: 6}}},
			{Code: "0O755",
				Options: []any{map[string]any{"version": "3.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'octal-numeric-literals' is not supported until Node.js >=4.0.0. The configured version range is '3.9.9'.", Line: 1, Column: 1, EndLine: 1, EndColumn: 6}}},
		}},
		{name: "propertyShorthands", ignores: []string{"propertyShorthands"}, valid: []rule_tester.ValidTestCase{
			{Code: "({ a: 1 })",
				Options: []any{map[string]any{"version": "3.9.9"}}},
			{Code: "({ get: get })",
				Options: []any{map[string]any{"version": "3.9.9"}}},
			{Code: "({ get a() {} })",
				Options: []any{map[string]any{"version": "3.9.9"}}},
			{Code: "({ a })",
				Options: []any{map[string]any{"version": "4.0.0"}}},
			{Code: "({ b() {} })",
				Options: []any{map[string]any{"version": "4.0.0"}}},
			{Code: "({ get() {} })",
				Options: []any{map[string]any{"version": "4.0.0"}}},
			{Code: "({ [c]() {} })",
				Options: []any{map[string]any{"version": "4.0.0", "ignores": []any{"computedProperties"}}}},
			{Code: "({ get })",
				Options: []any{map[string]any{"version": "6.0.0"}}},
			{Code: "({ set })",
				Options: []any{map[string]any{"version": "6.0.0"}}},
		}, invalid: []rule_tester.InvalidTestCase{
			{Code: "({ a })",
				Options: []any{map[string]any{"version": "3.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'property-shorthands' is not supported until Node.js >=4.0.0. The configured version range is '3.9.9'.", Line: 1, Column: 4, EndLine: 1, EndColumn: 5}}},
			{Code: "({ b() {} })",
				Options: []any{map[string]any{"version": "3.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'property-shorthands' is not supported until Node.js >=4.0.0. The configured version range is '3.9.9'.", Line: 1, Column: 4, EndLine: 1, EndColumn: 10}}},
			{Code: "({ [c]() {} })",
				Options: []any{map[string]any{"version": "3.9.9", "ignores": []any{"computedProperties"}}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'property-shorthands' is not supported until Node.js >=4.0.0. The configured version range is '3.9.9'.", Line: 1, Column: 4, EndLine: 1, EndColumn: 12}}},
		}},
		{name: "regexpU, regexpUFlag", ignores: []string{"regexpU", "regexpUFlag"}, valid: []rule_tester.ValidTestCase{
			{Code: "/foo/",
				Options: []any{map[string]any{"version": "5.9.9"}}},
			{Code: "/foo/gmi",
				Options: []any{map[string]any{"version": "5.9.9"}}},
			{Code: "/foo/y",
				Options: []any{map[string]any{"version": "5.9.9", "ignores": []any{"regexpYFlag"}}}},
			{Code: "/foo/u",
				Options: []any{map[string]any{"version": "6.0.0"}}},
		}, invalid: []rule_tester.InvalidTestCase{
			{Code: "/foo/u",
				Options: []any{map[string]any{"version": "5.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'regexp-u-flag' is not supported until Node.js >=6.0.0. The configured version range is '5.9.9'.", Line: 1, Column: 1, EndLine: 1, EndColumn: 7}}},
		}},
		{name: "regexpY, regexpYFlag", ignores: []string{"regexpY", "regexpYFlag"}, valid: []rule_tester.ValidTestCase{
			{Code: "/foo/",
				Options: []any{map[string]any{"version": "5.9.9"}}},
			{Code: "/foo/gmi",
				Options: []any{map[string]any{"version": "5.9.9"}}},
			{Code: "/foo/u",
				Options: []any{map[string]any{"version": "5.9.9", "ignores": []any{"regexpUFlag"}}}},
			{Code: "/foo/y",
				Options: []any{map[string]any{"version": "6.0.0"}}},
		}, invalid: []rule_tester.InvalidTestCase{
			{Code: "/foo/y",
				Options: []any{map[string]any{"version": "5.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'regexp-y-flag' is not supported until Node.js >=6.0.0. The configured version range is '5.9.9'.", Line: 1, Column: 1, EndLine: 1, EndColumn: 7}}},
		}},
		{name: "restParameters", ignores: []string{"restParameters"}, valid: []rule_tester.ValidTestCase{
			{Code: "var [...a] = b",
				Options: []any{map[string]any{"version": "5.9.9", "ignores": []any{"destructuring"}}}},
			{Code: "var {...a} = b",
				Options: []any{map[string]any{"version": "5.9.9", "ignores": []any{"destructuring", "restSpreadProperties"}}}},
			{Code: "var a = [...b]",
				Options: []any{map[string]any{"version": "5.9.9"}}},
			{Code: "var a = {...b}",
				Options: []any{map[string]any{"version": "5.9.9", "ignores": []any{"restSpreadProperties"}}}},
			{Code: "f(...a)",
				Options: []any{map[string]any{"version": "5.9.9"}}},
			{Code: "function f(...a) {}",
				Options: []any{map[string]any{"version": "6.0.0"}}},
			{Code: "function f(...[a, b = 0]) {}",
				Options: []any{map[string]any{"version": "6.0.0", "ignores": []any{"destructuring"}}}},
			{Code: "(function(...a) {})",
				Options: []any{map[string]any{"version": "6.0.0"}}},
			{Code: "((...a) => {})",
				Options: []any{map[string]any{"version": "6.0.0"}}},
			{Code: "({ f(...a) {} })",
				Options: []any{map[string]any{"version": "6.0.0"}}},
			{Code: "class A { f(...a) {} }",
				Options: []any{map[string]any{"version": "6.0.0", "ignores": []any{"classes"}}}},
			{Code: "(class { f(...a) {} })",
				Options: []any{map[string]any{"version": "6.0.0", "ignores": []any{"classes"}}}},
		}, invalid: []rule_tester.InvalidTestCase{
			{Code: "function f(...a) {}",
				Options: []any{map[string]any{"version": "5.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'rest-parameters' is not supported until Node.js >=6.0.0. The configured version range is '5.9.9'.", Line: 1, Column: 12, EndLine: 1, EndColumn: 16}}},
			{Code: "function f(...[a, b = 0]) {}",
				Options: []any{map[string]any{"version": "5.9.9", "ignores": []any{"destructuring"}}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'rest-parameters' is not supported until Node.js >=6.0.0. The configured version range is '5.9.9'.", Line: 1, Column: 12, EndLine: 1, EndColumn: 25}}},
			{Code: "(function(...a) {})",
				Options: []any{map[string]any{"version": "5.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'rest-parameters' is not supported until Node.js >=6.0.0. The configured version range is '5.9.9'.", Line: 1, Column: 11, EndLine: 1, EndColumn: 15}}},
			{Code: "((...a) => {})",
				Options: []any{map[string]any{"version": "5.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'rest-parameters' is not supported until Node.js >=6.0.0. The configured version range is '5.9.9'.", Line: 1, Column: 3, EndLine: 1, EndColumn: 7}}},
			{Code: "({ f(...a) {} })",
				Options: []any{map[string]any{"version": "5.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'rest-parameters' is not supported until Node.js >=6.0.0. The configured version range is '5.9.9'.", Line: 1, Column: 6, EndLine: 1, EndColumn: 10}}},
			{Code: "class A { f(...a) {} }",
				Options: []any{map[string]any{"version": "5.9.9", "ignores": []any{"classes"}}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'rest-parameters' is not supported until Node.js >=6.0.0. The configured version range is '5.9.9'.", Line: 1, Column: 13, EndLine: 1, EndColumn: 17}}},
			{Code: "(class { f(...a) {} })",
				Options: []any{map[string]any{"version": "5.9.9", "ignores": []any{"classes"}}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'rest-parameters' is not supported until Node.js >=6.0.0. The configured version range is '5.9.9'.", Line: 1, Column: 12, EndLine: 1, EndColumn: 16}}},
		}},
		{name: "spreadElements", ignores: []string{"spreadElements"}, valid: []rule_tester.ValidTestCase{
			{Code: "var [...a] = b",
				Options: []any{map[string]any{"version": "4.9.9", "ignores": []any{"destructuring"}}}},
			{Code: "var {...a} = b",
				Options: []any{map[string]any{"version": "4.9.9", "ignores": []any{"destructuring", "restSpreadProperties"}}}},
			{Code: "var a = {...b}",
				Options: []any{map[string]any{"version": "4.9.9", "ignores": []any{"restSpreadProperties"}}}},
			{Code: "function f(...a) {}",
				Options: []any{map[string]any{"version": "4.9.9", "ignores": []any{"restParameters"}}}},
			{Code: "[...a]",
				Options: []any{map[string]any{"version": "5.0.0"}}},
			{Code: "[...a, ...b]",
				Options: []any{map[string]any{"version": "5.0.0"}}},
			{Code: "f(...a)",
				Options: []any{map[string]any{"version": "5.0.0"}}},
			{Code: "new F(...a)",
				Options: []any{map[string]any{"version": "5.0.0"}}},
		}, invalid: []rule_tester.InvalidTestCase{
			{Code: "[...a]",
				Options: []any{map[string]any{"version": "4.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'spread-elements' is not supported until Node.js >=5.0.0. The configured version range is '4.9.9'.", Line: 1, Column: 2, EndLine: 1, EndColumn: 6}}},
			{Code: "[...a, ...b]",
				Options: []any{map[string]any{"version": "4.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'spread-elements' is not supported until Node.js >=5.0.0. The configured version range is '4.9.9'.", Line: 1, Column: 2, EndLine: 1, EndColumn: 6}, {MessageId: "not-supported-till", Message: "'spread-elements' is not supported until Node.js >=5.0.0. The configured version range is '4.9.9'.", Line: 1, Column: 8, EndLine: 1, EndColumn: 12}}},
			{Code: "f(...a)",
				Options: []any{map[string]any{"version": "4.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'spread-elements' is not supported until Node.js >=5.0.0. The configured version range is '4.9.9'.", Line: 1, Column: 3, EndLine: 1, EndColumn: 7}}},
			{Code: "new F(...a)",
				Options: []any{map[string]any{"version": "4.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'spread-elements' is not supported until Node.js >=5.0.0. The configured version range is '4.9.9'.", Line: 1, Column: 7, EndLine: 1, EndColumn: 11}}},
		}},
		{name: "templateLiterals", ignores: []string{"templateLiterals"}, valid: []rule_tester.ValidTestCase{
			{Code: "'`foo`'",
				Options: []any{map[string]any{"version": "3.9.9"}}},
			{Code: "`foo`",
				Options: []any{map[string]any{"version": "4.0.0"}}},
			{Code: "`foo${a}bar`",
				Options: []any{map[string]any{"version": "4.0.0"}}},
			{Code: "tag`foo`",
				Options: []any{map[string]any{"version": "4.0.0"}}},
			{Code: "tag`foo${a}bar`",
				Options: []any{map[string]any{"version": "4.0.0"}}},
		}, invalid: []rule_tester.InvalidTestCase{
			{Code: "`foo`",
				Options: []any{map[string]any{"version": "3.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'template-literals' is not supported until Node.js >=4.0.0. The configured version range is '3.9.9'.", Line: 1, Column: 1, EndLine: 1, EndColumn: 6}}},
			{Code: "`foo${a}bar`",
				Options: []any{map[string]any{"version": "3.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'template-literals' is not supported until Node.js >=4.0.0. The configured version range is '3.9.9'.", Line: 1, Column: 1, EndLine: 1, EndColumn: 13}}},
			{Code: "tag`foo`",
				Options: []any{map[string]any{"version": "3.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'template-literals' is not supported until Node.js >=4.0.0. The configured version range is '3.9.9'.", Line: 1, Column: 1, EndLine: 1, EndColumn: 9}}},
			{Code: "tag`foo${a}bar`",
				Options: []any{map[string]any{"version": "3.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'template-literals' is not supported until Node.js >=4.0.0. The configured version range is '3.9.9'.", Line: 1, Column: 1, EndLine: 1, EndColumn: 16}}},
		}},
		{name: "unicodeCodePointEscapes, unicodeCodepointEscapes", ignores: []string{"unicodeCodePointEscapes", "unicodeCodepointEscapes"}, valid: []rule_tester.ValidTestCase{
			{Code: "var a = \"\\x61\"",
				Options: []any{map[string]any{"version": "3.9.9"}}},
			{Code: "var a = \"\\u0061\"",
				Options: []any{map[string]any{"version": "3.9.9"}}},
			{Code: "var a = \"\\\\u{61}\"",
				Options: []any{map[string]any{"version": "3.9.9"}}},
			{Code: "var \\u{61} = 0",
				Options: []any{map[string]any{"version": "4.0.0"}}},
			{Code: "var a = \"\\u{61}\"",
				Options: []any{map[string]any{"version": "4.0.0"}}},
			{Code: "var a = '\\u{61}'",
				Options: []any{map[string]any{"version": "4.0.0"}}},
			{Code: "var a = `\\u{61}`",
				Options: []any{map[string]any{"version": "4.0.0"}}},
		}, invalid: []rule_tester.InvalidTestCase{
			{Code: "var \\u{61} = 0",
				Options: []any{map[string]any{"version": "3.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'unicode-codepoint-escapes' is not supported until Node.js >=4.0.0. The configured version range is '3.9.9'.", Line: 1, Column: 5, EndLine: 1, EndColumn: 11}}},
			{Code: "var a = \"\\u{61}\"",
				Options: []any{map[string]any{"version": "3.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'unicode-codepoint-escapes' is not supported until Node.js >=4.0.0. The configured version range is '3.9.9'.", Line: 1, Column: 10, EndLine: 1, EndColumn: 16}}},
			{Code: "var a = \"\\\\\\u{61}\"",
				Options: []any{map[string]any{"version": "3.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'unicode-codepoint-escapes' is not supported until Node.js >=4.0.0. The configured version range is '3.9.9'.", Line: 1, Column: 12, EndLine: 1, EndColumn: 18}}},
			{Code: "var a = '\\u{61}'",
				Options: []any{map[string]any{"version": "3.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'unicode-codepoint-escapes' is not supported until Node.js >=4.0.0. The configured version range is '3.9.9'.", Line: 1, Column: 10, EndLine: 1, EndColumn: 16}}},
			{Code: "var a = `\\u{61}`",
				Options: []any{map[string]any{"version": "3.9.9", "ignores": []any{"templateLiterals"}}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'unicode-codepoint-escapes' is not supported until Node.js >=4.0.0. The configured version range is '3.9.9'.", Line: 1, Column: 10, EndLine: 1, EndColumn: 16}}},
		}},
		{name: "exponentialOperators", ignores: []string{"exponentialOperators"}, valid: []rule_tester.ValidTestCase{
			{Code: "a ** b",
				Options: []any{map[string]any{"version": "7.0.0"}}},
			{Code: "a **= b",
				Options: []any{map[string]any{"version": "7.0.0"}}},
			{Code: "a * b",
				Options: []any{map[string]any{"version": "6.9.9"}}},
			{Code: "a *= b",
				Options: []any{map[string]any{"version": "6.9.9"}}},
		}, invalid: []rule_tester.InvalidTestCase{
			{Code: "a ** b",
				Options: []any{map[string]any{"version": "6.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'exponential-operators' is not supported until Node.js >=7.0.0. The configured version range is '6.9.9'.", Line: 1, Column: 1, EndLine: 1, EndColumn: 7}}},
			{Code: "a **= b",
				Options: []any{map[string]any{"version": "6.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'exponential-operators' is not supported until Node.js >=7.0.0. The configured version range is '6.9.9'.", Line: 1, Column: 1, EndLine: 1, EndColumn: 8}}},
		}},
		{name: "asyncFunctions", ignores: []string{"asyncFunctions"}, valid: []rule_tester.ValidTestCase{
			{Code: "async function f() {}",
				Options: []any{map[string]any{"version": "7.6.0"}}},
			{Code: "async function f() { await 1 }",
				Options: []any{map[string]any{"version": "7.6.0"}}},
			{Code: "(async function() { await 1 })",
				Options: []any{map[string]any{"version": "7.6.0"}}},
			{Code: "(async() => { await 1 })",
				Options: []any{map[string]any{"version": "7.6.0"}}},
			{Code: "({ async method() { await 1 } })",
				Options: []any{map[string]any{"version": "7.6.0"}}},
			{Code: "class A { async method() { await 1 } }",
				Options: []any{map[string]any{"version": "7.6.0"}}},
			{Code: "(class { async method() { await 1 } })",
				Options: []any{map[string]any{"version": "7.6.0"}}},
		}, invalid: []rule_tester.InvalidTestCase{
			{Code: "async function f() {}",
				Options: []any{map[string]any{"version": "7.5.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'async-functions' is not supported until Node.js >=7.6.0. The configured version range is '7.5.9'.", Line: 1, Column: 1, EndLine: 1, EndColumn: 22}}},
			{Code: "async function f() { await 1 }",
				Options: []any{map[string]any{"version": "7.5.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'async-functions' is not supported until Node.js >=7.6.0. The configured version range is '7.5.9'.", Line: 1, Column: 1, EndLine: 1, EndColumn: 31}}},
			{Code: "(async function() { await 1 })",
				Options: []any{map[string]any{"version": "7.5.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'async-functions' is not supported until Node.js >=7.6.0. The configured version range is '7.5.9'.", Line: 1, Column: 2, EndLine: 1, EndColumn: 30}}},
			{Code: "(async() => { await 1 })",
				Options: []any{map[string]any{"version": "7.5.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'async-functions' is not supported until Node.js >=7.6.0. The configured version range is '7.5.9'.", Line: 1, Column: 2, EndLine: 1, EndColumn: 24}}},
			{Code: "({ async method() { await 1 } })",
				Options: []any{map[string]any{"version": "7.5.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'async-functions' is not supported until Node.js >=7.6.0. The configured version range is '7.5.9'.", Line: 1, Column: 16, EndLine: 1, EndColumn: 30}}},
			{Code: "class A { async method() { await 1 } }",
				Options: []any{map[string]any{"version": "7.5.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'async-functions' is not supported until Node.js >=7.6.0. The configured version range is '7.5.9'.", Line: 1, Column: 23, EndLine: 1, EndColumn: 37}}},
			{Code: "(class { async method() { await 1 } })",
				Options: []any{map[string]any{"version": "7.5.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'async-functions' is not supported until Node.js >=7.6.0. The configured version range is '7.5.9'.", Line: 1, Column: 22, EndLine: 1, EndColumn: 36}}},
		}},
		{name: "trailingCommasInFunctions, trailingFunctionCommas", ignores: []string{"trailingCommasInFunctions", "trailingFunctionCommas"}, valid: []rule_tester.ValidTestCase{
			{Code: "function f(a,) {}",
				Options: []any{map[string]any{"version": "8.0.0"}}},
			{Code: "(function(a,) {})",
				Options: []any{map[string]any{"version": "8.0.0"}}},
			{Code: "((a,) => {})",
				Options: []any{map[string]any{"version": "8.0.0"}}},
			{Code: "({ method(a,) {} })",
				Options: []any{map[string]any{"version": "8.0.0"}}},
			{Code: "class A { method(a,) {} }",
				Options: []any{map[string]any{"version": "8.0.0"}}},
			{Code: "(class { method(a,) {} })",
				Options: []any{map[string]any{"version": "8.0.0"}}},
			{Code: "f(1,)",
				Options: []any{map[string]any{"version": "8.0.0"}}},
			{Code: "new A(1,)",
				Options: []any{map[string]any{"version": "8.0.0"}}},
		}, invalid: []rule_tester.InvalidTestCase{
			{Code: "function f(a,) {}",
				Options: []any{map[string]any{"version": "7.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'trailing-function-commas' is not supported until Node.js >=8.0.0. The configured version range is '7.9.9'.", Line: 1, Column: 13, EndLine: 1, EndColumn: 14}}},
			{Code: "(function(a,) {})",
				Options: []any{map[string]any{"version": "7.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'trailing-function-commas' is not supported until Node.js >=8.0.0. The configured version range is '7.9.9'.", Line: 1, Column: 12, EndLine: 1, EndColumn: 13}}},
			{Code: "((a,) => {})",
				Options: []any{map[string]any{"version": "7.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'trailing-function-commas' is not supported until Node.js >=8.0.0. The configured version range is '7.9.9'.", Line: 1, Column: 4, EndLine: 1, EndColumn: 5}}},
			{Code: "({ method(a,) {} })",
				Options: []any{map[string]any{"version": "7.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'trailing-function-commas' is not supported until Node.js >=8.0.0. The configured version range is '7.9.9'.", Line: 1, Column: 12, EndLine: 1, EndColumn: 13}}},
			{Code: "class A { method(a,) {} }",
				Options: []any{map[string]any{"version": "7.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'trailing-function-commas' is not supported until Node.js >=8.0.0. The configured version range is '7.9.9'.", Line: 1, Column: 19, EndLine: 1, EndColumn: 20}}},
			{Code: "(class { method(a,) {} })",
				Options: []any{map[string]any{"version": "7.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'trailing-function-commas' is not supported until Node.js >=8.0.0. The configured version range is '7.9.9'.", Line: 1, Column: 18, EndLine: 1, EndColumn: 19}}},
			{Code: "f(1,)",
				Options: []any{map[string]any{"version": "7.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'trailing-function-commas' is not supported until Node.js >=8.0.0. The configured version range is '7.9.9'.", Line: 1, Column: 4, EndLine: 1, EndColumn: 5}}},
			{Code: "new A(1,)",
				Options: []any{map[string]any{"version": "7.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'trailing-function-commas' is not supported until Node.js >=8.0.0. The configured version range is '7.9.9'.", Line: 1, Column: 8, EndLine: 1, EndColumn: 9}}},
		}},
		{name: "asyncIteration", ignores: []string{"asyncIteration"}, valid: []rule_tester.ValidTestCase{
			{Code: "async function f() { for await (const x of xs) {} }",
				Options: []any{map[string]any{"version": "10.0.0"}}},
			{Code: "async function* f() { }",
				Options: []any{map[string]any{"version": "10.0.0"}}},
			{Code: "(async function* () { })",
				Options: []any{map[string]any{"version": "10.0.0"}}},
			{Code: "({ async* method() { } })",
				Options: []any{map[string]any{"version": "10.0.0"}}},
			{Code: "class A { async* method() { } }",
				Options: []any{map[string]any{"version": "10.0.0"}}},
			{Code: "(class { async* method() { } })",
				Options: []any{map[string]any{"version": "10.0.0"}}},
			{Code: "function f() { for (const x of xs) {} }",
				Options: []any{map[string]any{"version": "9.9.9"}}},
			{Code: "async function f() { }",
				Options: []any{map[string]any{"version": "9.9.9"}}},
			{Code: "function* f() { }",
				Options: []any{map[string]any{"version": "9.9.9"}}},
		}, invalid: []rule_tester.InvalidTestCase{
			{Code: "async function f() { for await (const x of xs) {} }",
				Options: []any{map[string]any{"version": "9.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'async-iteration' is not supported until Node.js >=10.0.0. The configured version range is '9.9.9'.", Line: 1, Column: 22, EndLine: 1, EndColumn: 50}}},
			{Code: "async function* f() { }",
				Options: []any{map[string]any{"version": "9.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'async-iteration' is not supported until Node.js >=10.0.0. The configured version range is '9.9.9'.", Line: 1, Column: 1, EndLine: 1, EndColumn: 24}}},
			{Code: "(async function* () { })",
				Options: []any{map[string]any{"version": "9.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'async-iteration' is not supported until Node.js >=10.0.0. The configured version range is '9.9.9'.", Line: 1, Column: 2, EndLine: 1, EndColumn: 24}}},
			{Code: "({ async* method() { } })",
				Options: []any{map[string]any{"version": "9.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'async-iteration' is not supported until Node.js >=10.0.0. The configured version range is '9.9.9'.", Line: 1, Column: 17, EndLine: 1, EndColumn: 23}}},
			{Code: "class A { async* method() { } }",
				Options: []any{map[string]any{"version": "9.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'async-iteration' is not supported until Node.js >=10.0.0. The configured version range is '9.9.9'.", Line: 1, Column: 24, EndLine: 1, EndColumn: 30}}},
			{Code: "(class { async* method() { } })",
				Options: []any{map[string]any{"version": "9.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'async-iteration' is not supported until Node.js >=10.0.0. The configured version range is '9.9.9'.", Line: 1, Column: 23, EndLine: 1, EndColumn: 29}}},
		}},
		{name: "malformedTemplateLiterals", ignores: []string{"malformedTemplateLiterals"}, valid: []rule_tester.ValidTestCase{
			{Code: "tag`\\unicode`",
				Options: []any{map[string]any{"version": "8.10.0"}}},
		}, invalid: []rule_tester.InvalidTestCase{
			{Code: "tag`\\unicode`",
				Options: []any{map[string]any{"version": "8.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'malformed-template-literals' is not supported until Node.js >=8.10.0. The configured version range is '8.9.9'.", Line: 1, Column: 4, EndLine: 1, EndColumn: 14}}},
		}},
		{name: "regexpLookbehind, regexpLookbehindAssertions", ignores: []string{"regexpLookbehind", "regexpLookbehindAssertions"}, valid: []rule_tester.ValidTestCase{
			{Code: "var a = /(?<=a)foo/",
				Options: []any{map[string]any{"version": "8.10.0"}}},
			{Code: "var a = /(?<!a)foo/",
				Options: []any{map[string]any{"version": "8.10.0"}}},
			{Code: "var a = new RegExp(\"/(?<=a)foo/\")",
				Options: []any{map[string]any{"version": "8.10.0"}}},
			{Code: "var a = new RegExp(pattern)",
				Options: []any{map[string]any{"version": "8.9.9"}}},
			{Code: "var a = new RegExp(\"(?<=\")",
				Options: []any{map[string]any{"version": "8.9.9"}}},
			{Code: "var a = /\\(?<=a\\)foo/",
				Options: []any{map[string]any{"version": "8.9.9"}}},
		}, invalid: []rule_tester.InvalidTestCase{
			{Code: "var a = /(?<=a)foo/",
				Options: []any{map[string]any{"version": "8.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'regexp-lookbehind-assertions' is not supported until Node.js >=8.10.0. The configured version range is '8.9.9'.", Line: 1, Column: 9, EndLine: 1, EndColumn: 20}}},
			{Code: "var a = /(?<!a)foo/",
				Options: []any{map[string]any{"version": "8.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'regexp-lookbehind-assertions' is not supported until Node.js >=8.10.0. The configured version range is '8.9.9'.", Line: 1, Column: 9, EndLine: 1, EndColumn: 20}}},
			{Code: "var a = new RegExp(\"/(?<=a)foo/\")",
				Options: []any{map[string]any{"version": "8.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'regexp-lookbehind-assertions' is not supported until Node.js >=8.10.0. The configured version range is '8.9.9'.", Line: 1, Column: 9, EndLine: 1, EndColumn: 34}}},
		}},
		{name: "regexpNamedCaptureGroups", ignores: []string{"regexpNamedCaptureGroups"}, valid: []rule_tester.ValidTestCase{
			{Code: "var a = /(?<key>a)foo/",
				Options: []any{map[string]any{"version": "10.0.0"}}},
			{Code: "var a = /(?<key>a)\\k<key>/",
				Options: []any{map[string]any{"version": "10.0.0"}}},
			{Code: "var a = new RegExp(\"(?<key>a)foo\")",
				Options: []any{map[string]any{"version": "10.0.0"}}},
			{Code: "var a = new RegExp(pattern)",
				Options: []any{map[string]any{"version": "8.9.9"}}},
			{Code: "var a = new RegExp(\"(?<key\")",
				Options: []any{map[string]any{"version": "8.9.9"}}},
			{Code: "var a = /\\(?<key>a\\)foo/",
				Options: []any{map[string]any{"version": "8.9.9"}}},
		}, invalid: []rule_tester.InvalidTestCase{
			{Code: "var a = /(?<key>a)foo/",
				Options: []any{map[string]any{"version": "9.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'regexp-named-capture-groups' is not supported until Node.js >=10.0.0. The configured version range is '9.9.9'.", Line: 1, Column: 9, EndLine: 1, EndColumn: 23}}},
			{Code: "var a = /(?<key>a)\\k<key>/",
				Options: []any{map[string]any{"version": "9.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'regexp-named-capture-groups' is not supported until Node.js >=10.0.0. The configured version range is '9.9.9'.", Line: 1, Column: 9, EndLine: 1, EndColumn: 27}}},
			{Code: "var a = new RegExp(\"(?<key>a)foo\")",
				Options: []any{map[string]any{"version": "9.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'regexp-named-capture-groups' is not supported until Node.js >=10.0.0. The configured version range is '9.9.9'.", Line: 1, Column: 9, EndLine: 1, EndColumn: 35}}},
		}},
		{name: "regexpS, regexpSFlag", ignores: []string{"regexpS", "regexpSFlag"}, valid: []rule_tester.ValidTestCase{
			{Code: "var a = /foo/s",
				Options: []any{map[string]any{"version": "8.10.0"}}},
			{Code: "var a = new RegExp(\"foo\", \"s\")",
				Options: []any{map[string]any{"version": "8.10.0"}}},
			{Code: "var a = new RegExp(a, b)",
				Options: []any{map[string]any{"version": "8.9.9"}}},
			{Code: "var a = new RegExp(\"(aaaaa\", b)",
				Options: []any{map[string]any{"version": "8.9.9"}}},
		}, invalid: []rule_tester.InvalidTestCase{
			{Code: "var a = /foo/s",
				Options: []any{map[string]any{"version": "8.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'regexp-s-flag' is not supported until Node.js >=8.10.0. The configured version range is '8.9.9'.", Line: 1, Column: 9, EndLine: 1, EndColumn: 15}}},
			{Code: "var a = new RegExp(\"foo\", \"s\")",
				Options: []any{map[string]any{"version": "8.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'regexp-s-flag' is not supported until Node.js >=8.10.0. The configured version range is '8.9.9'.", Line: 1, Column: 9, EndLine: 1, EndColumn: 31}}},
		}},
		{name: "regexpUnicodeProperties, regexpUnicodePropertyEscapes", ignores: []string{"regexpUnicodeProperties", "regexpUnicodePropertyEscapes"}, valid: []rule_tester.ValidTestCase{
			{Code: "var a = /\\p{Letter}/u",
				Options: []any{map[string]any{"version": "10.0.0"}}},
			{Code: "var a = /\\P{Letter}/u",
				Options: []any{map[string]any{"version": "10.0.0"}}},
			{Code: "var a = new RegExp(\"\\\\p{Letter}\", \"u\")",
				Options: []any{map[string]any{"version": "10.0.0"}}},
			{Code: "var a = new RegExp(\"\\\\p{Letter}\")",
				Options: []any{map[string]any{"version": "9.9.9"}}},
			{Code: "var a = new RegExp(pattern, \"u\")",
				Options: []any{map[string]any{"version": "9.9.9"}}},
			{Code: "var a = new RegExp(\"\\\\p{Letter\")",
				Options: []any{map[string]any{"version": "9.9.9"}}},
		}, invalid: []rule_tester.InvalidTestCase{
			{Code: "var a = /\\p{Letter}/u",
				Options: []any{map[string]any{"version": "9.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'regexp-unicode-property-escapes' is not supported until Node.js >=10.0.0. The configured version range is '9.9.9'.", Line: 1, Column: 9, EndLine: 1, EndColumn: 22}}},
			{Code: "var a = /\\P{Letter}/u",
				Options: []any{map[string]any{"version": "9.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'regexp-unicode-property-escapes' is not supported until Node.js >=10.0.0. The configured version range is '9.9.9'.", Line: 1, Column: 9, EndLine: 1, EndColumn: 22}}},
			{Code: "var a = new RegExp(\"\\\\p{Letter}\", \"u\")",
				Options: []any{map[string]any{"version": "9.9.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'regexp-unicode-property-escapes' is not supported until Node.js >=10.0.0. The configured version range is '9.9.9'.", Line: 1, Column: 9, EndLine: 1, EndColumn: 39}}},
		}},
		{name: "restSpreadProperties", ignores: []string{"restSpreadProperties"}, valid: []rule_tester.ValidTestCase{
			{Code: "({ ...obj })",
				Options: []any{map[string]any{"version": "8.3.0"}}},
			{Code: "({ ...rest } = obj)",
				Options: []any{map[string]any{"version": "8.3.0"}}},
			{Code: "({ obj })",
				Options: []any{map[string]any{"version": "8.2.9"}}},
			{Code: "({ obj: 1 })",
				Options: []any{map[string]any{"version": "8.2.9"}}},
			{Code: "({ obj } = a)",
				Options: []any{map[string]any{"version": "8.2.9"}}},
			{Code: "({ obj: a } = b)",
				Options: []any{map[string]any{"version": "8.2.9"}}},
			{Code: "([...xs])",
				Options: []any{map[string]any{"version": "8.2.9"}}},
			{Code: "([a, ...xs] = ys)",
				Options: []any{map[string]any{"version": "8.2.9"}}},
		}, invalid: []rule_tester.InvalidTestCase{
			{Code: "({ ...obj })",
				Options: []any{map[string]any{"version": "8.2.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'rest-spread-properties' is not supported until Node.js >=8.3.0. The configured version range is '8.2.9'.", Line: 1, Column: 4, EndLine: 1, EndColumn: 10}}},
			{Code: "({ ...rest } = obj)",
				Options: []any{map[string]any{"version": "8.2.9"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'rest-spread-properties' is not supported until Node.js >=8.3.0. The configured version range is '8.2.9'.", Line: 1, Column: 4, EndLine: 1, EndColumn: 11}}},
		}},
		{name: "jsonSuperset", ignores: []string{"jsonSuperset"}, valid: []rule_tester.ValidTestCase{
			{Code: "var s = 'foo'",
				Options: []any{map[string]any{"version": "9.99.99"}}},
			{Code: "var s = '\\\u2028'",
				Options: []any{map[string]any{"version": "9.99.99"}}},
			{Code: "var s = '\\\u2029'",
				Options: []any{map[string]any{"version": "9.99.99"}}},
			{Code: "var s = '\u2028'",
				Options: []any{map[string]any{"version": "10.0.0"}}},
			{Code: "var s = '\u2029'",
				Options: []any{map[string]any{"version": "10.0.0"}}},
		}, invalid: []rule_tester.InvalidTestCase{
			{Code: "var s = '\u2028'",
				Options: []any{map[string]any{"version": "9.99.99"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'json-superset' is not supported until Node.js >=10.0.0. The configured version range is '9.99.99'.", Line: 1, Column: 10, EndLine: 1, EndColumn: 10}}},
			{Code: "var s = '\u2029'",
				Options: []any{map[string]any{"version": "9.99.99"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'json-superset' is not supported until Node.js >=10.0.0. The configured version range is '9.99.99'.", Line: 1, Column: 10, EndLine: 1, EndColumn: 10}}},
		}},
		{name: "optionalCatchBinding", ignores: []string{"optionalCatchBinding"}, valid: []rule_tester.ValidTestCase{
			{Code: "try {} catch {}",
				Options: []any{map[string]any{"version": "10.0.0"}}},
			{Code: "try {} catch (error) {}",
				Options: []any{map[string]any{"version": "9.99.99"}}},
		}, invalid: []rule_tester.InvalidTestCase{
			{Code: "try {} catch {}",
				Options: []any{map[string]any{"version": "9.99.99"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'optional-catch-binding' is not supported until Node.js >=10.0.0. The configured version range is '9.99.99'.", Line: 1, Column: 8, EndLine: 1, EndColumn: 16}}},
		}},
		{name: "bigint", ignores: []string{"bigint"}, valid: []rule_tester.ValidTestCase{
			{Code: "var n = 0n",
				Options: []any{map[string]any{"version": "10.4.0"}}},
			{Code: "var n = BigInt(0)",
				Options: []any{map[string]any{"version": "10.4.0"}}},
			{Code: "var n = new BigInt64Array()",
				Options: []any{map[string]any{"version": "10.4.0"}}},
			{Code: "var n = new BigUint64Array()",
				Options: []any{map[string]any{"version": "10.4.0"}}},
			{Code: "var n = { [0n]: 0 }",
				Options: []any{map[string]any{"version": "10.4.0"}}},
			{Code: "var n = class { [0n]() {} }",
				Options: []any{map[string]any{"version": "10.4.0"}}},
		}, invalid: []rule_tester.InvalidTestCase{
			{Code: "var n = 0n",
				Options: []any{map[string]any{"version": "10.3.0"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'bigint' is not supported until Node.js >=10.4.0. The configured version range is '10.3.0'.", Line: 1, Column: 9, EndLine: 1, EndColumn: 11}}},
		}},
		{name: "dynamicImport", ignores: []string{"dynamicImport"}, valid: []rule_tester.ValidTestCase{
			{Code: "obj.import(source)",
				Options: []any{map[string]any{"version": "12.0.0"}}},
			{Code: "import(source)",
				Options: []any{map[string]any{"version": "12.17.0"}}},
			{Code: "import(source)",
				Options: []any{map[string]any{"version": "13.2.0"}}},
		}, invalid: []rule_tester.InvalidTestCase{
			{Code: "import(source)",
				Options: []any{map[string]any{"version": "12.16.0"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'dynamic-import' is not supported until Node.js ^12.17.0 || >=13.2.0. The configured version range is '12.16.0'.", Line: 1, Column: 1, EndLine: 1, EndColumn: 15}}},
			{Code: "import(source)",
				Options: []any{map[string]any{"version": "13.0.0"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'dynamic-import' is not supported until Node.js ^12.17.0 || >=13.2.0. The configured version range is '13.0.0'.", Line: 1, Column: 1, EndLine: 1, EndColumn: 15}}},
			{Code: "import(source)",
				Options: []any{map[string]any{"version": "13.1.0"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'dynamic-import' is not supported until Node.js ^12.17.0 || >=13.2.0. The configured version range is '13.1.0'.", Line: 1, Column: 1, EndLine: 1, EndColumn: 15}}},
			{Code: "import(source)",
				Options: []any{map[string]any{"version": ">=8.0.0"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'dynamic-import' is not supported until Node.js ^12.17.0 || >=13.2.0. The configured version range is '>=8.0.0'.", Line: 1, Column: 1, EndLine: 1, EndColumn: 15}}},
		}},
		{name: "optionalChaining", ignores: []string{"optionalChaining"}, valid: []rule_tester.ValidTestCase{
			{Code: "foo?.bar;",
				Options: []any{map[string]any{"version": "14.0.0"}}},
		}, invalid: []rule_tester.InvalidTestCase{
			{Code: "foo?.bar",
				Options: []any{map[string]any{"version": "13.0.0"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'optional-chaining' is not supported until Node.js >=14.0.0. The configured version range is '13.0.0'.", Line: 1, Column: 4, EndLine: 1, EndColumn: 6}}},
		}},
		{name: "nullishCoalescingOperators", ignores: []string{"nullishCoalescingOperators"}, valid: []rule_tester.ValidTestCase{
			{Code: "foo ?? bar;",
				Options: []any{map[string]any{"version": "14.0.0"}}},
			{Code: "foo ?? bar;",
				Settings: map[string]any{"node": map[string]any{"version": "14.0.0"}}},
		}, invalid: []rule_tester.InvalidTestCase{
			{Code: "foo ?? bar",
				Options: []any{map[string]any{"version": "13.0.0"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'nullish-coalescing-operators' is not supported until Node.js >=14.0.0. The configured version range is '13.0.0'.", Line: 1, Column: 5, EndLine: 1, EndColumn: 7}}},
			{Code: "foo ?? bar",
				Settings: map[string]any{"node": map[string]any{"version": "13.0.0"}},
				Errors:   []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'nullish-coalescing-operators' is not supported until Node.js >=14.0.0. The configured version range is '13.0.0'.", Line: 1, Column: 5, EndLine: 1, EndColumn: 7}}},
		}},
		{name: "logicalAssignmentOperators", ignores: []string{"logicalAssignmentOperators"}, valid: []rule_tester.ValidTestCase{
			{Code: "a ||= b",
				Options: []any{map[string]any{"version": "15.0.0"}}},
			{Code: "a &&= b",
				Options: []any{map[string]any{"version": "15.0.0"}}},
			{Code: "a ??= b",
				Options: []any{map[string]any{"version": "15.0.0"}}},
		}, invalid: []rule_tester.InvalidTestCase{
			{Code: "a ||= b",
				Options: []any{map[string]any{"version": "14.0.0"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'logical-assignment-operators' is not supported until Node.js >=15.0.0. The configured version range is '14.0.0'.", Line: 1, Column: 3, EndLine: 1, EndColumn: 6}}},
			{Code: "a &&= b",
				Options: []any{map[string]any{"version": "14.0.0"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'logical-assignment-operators' is not supported until Node.js >=15.0.0. The configured version range is '14.0.0'.", Line: 1, Column: 3, EndLine: 1, EndColumn: 6}}},
			{Code: "a ??= b",
				Options: []any{map[string]any{"version": "14.0.0"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'logical-assignment-operators' is not supported until Node.js >=15.0.0. The configured version range is '14.0.0'.", Line: 1, Column: 3, EndLine: 1, EndColumn: 6}}},
		}},
		{name: "numericSeparators", ignores: []string{"numericSeparators"}, valid: []rule_tester.ValidTestCase{
			{Code: "a = 123_456_789",
				Options: []any{map[string]any{"version": "12.5.0"}}},
		}, invalid: []rule_tester.InvalidTestCase{
			{Code: "a = 123_456_789",
				Options: []any{map[string]any{"version": "12.4.0"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'numeric-separators' is not supported until Node.js >=12.5.0. The configured version range is '12.4.0'.", Line: 1, Column: 5, EndLine: 1, EndColumn: 16}}},
		}},
		{name: "configuration", ignores: []string{}, valid: []rule_tester.ValidTestCase{
			{Code: "var a = () => 1",
				FileName: "gte-4.0.0/a.js"},
			{Code: "var a = () => 1",
				FileName: "gte-4.4.0-lt-5.0.0/a.js"},
			{Code: "var a = () => 1",
				FileName: "hat-4.1.2/a.js"},
			{Code: "'\\\\u{0123}'"},
			{Code: "var a = async () => 1",
				FileName: "gte-4.0.0/a.js",
				Options:  []any{map[string]any{"ignores": []any{"asyncFunctions"}}}},
			{Code: "var a = async () => 1",
				FileName: "gte-7.6.0/a.js"},
			{Code: "var a = async () => 1",
				FileName: "gte-7.10.0/a.js"},
			{Code: "var a = () => 1",
				FileName: "invalid/a.js"},
			{Code: "var a = () => 1",
				FileName: "nothing/a.js"},
			{Code: "var a = async () => 1",
				Options: []any{map[string]any{"version": "7.10.0"}}},
			{Code: "var a = async () => 1",
				Settings: map[string]any{"node": map[string]any{"version": "7.10.0"}}},
			{Code: "var a = () => 1",
				FileName: "without-node/a.js"},
			{Code: "var a = async () => 1",
				FileName: "dev-engines-non-node-only/a.js"},
		}, invalid: []rule_tester.InvalidTestCase{
			{Code: "var a = () => 1",
				FileName: "gte-0.12.8/a.js",
				Errors:   []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'arrow-functions' is not supported until Node.js >=4.0.0. The configured version range is '>=0.12.8'.", Line: 1, Column: 9, EndLine: 1, EndColumn: 16}}},
			{Code: "var a = { ...obj }",
				FileName: "invalid/a.js",
				Options:  []any{map[string]any{"version": ">=8.0.0"}},
				Errors:   []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'rest-spread-properties' is not supported until Node.js >=8.3.0. The configured version range is '>=8.0.0'.", Line: 1, Column: 11, EndLine: 1, EndColumn: 17}}},
			{Code: "var a = () => 1",
				FileName: "lt-6.0.0/a.js",
				Errors:   []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'arrow-functions' is not supported until Node.js >=4.0.0. The configured version range is '<6.0.0'.", Line: 1, Column: 9, EndLine: 1, EndColumn: 16}}},
			{Code: "var a = { ...obj }",
				FileName: "nothing/a.js",
				Options:  []any{map[string]any{"version": ">=8.0.0"}},
				Errors:   []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'rest-spread-properties' is not supported until Node.js >=8.3.0. The configured version range is '>=8.0.0'.", Line: 1, Column: 11, EndLine: 1, EndColumn: 17}}},
			{Code: "var a = async () => 1",
				FileName: "gte-7.5.0/a.js",
				Errors:   []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'async-functions' is not supported until Node.js >=7.6.0. The configured version range is '>=7.5.0'.", Line: 1, Column: 9, EndLine: 1, EndColumn: 22}}},
			{Code: "\"use strict\"; let a = 1",
				FileName: "star/a.js",
				Errors:   []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'block-scoped-variables' is not supported until Node.js >=4.0.0. The configured version range is '*'.", Line: 1, Column: 15, EndLine: 1, EndColumn: 24}}},
			{Code: "var a = async () => 1",
				FileName: "dev-engines-gte-7.5.0/a.js",
				Errors:   []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'async-functions' is not supported until Node.js >=7.6.0. The configured version range is '>=7.5.0'.", Line: 1, Column: 9, EndLine: 1, EndColumn: 22}}},
			{Code: "var a = async () => 1",
				FileName: "dev-engines-array-gte-7.5.0/a.js",
				Errors:   []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'async-functions' is not supported until Node.js >=7.6.0. The configured version range is '>=7.5.0'.", Line: 1, Column: 9, EndLine: 1, EndColumn: 22}}},
			{Code: "var a = async () => 1",
				FileName: "engines-over-dev-engines/a.js",
				Errors:   []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'async-functions' is not supported until Node.js >=7.6.0. The configured version range is '>=4.0.0'.", Line: 1, Column: 9, EndLine: 1, EndColumn: 22}}},
			{Code: "var a = async () => 1",
				FileName: "dev-engines-non-node/a.js",
				Errors:   []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'async-functions' is not supported until Node.js >=7.6.0. The configured version range is '>=7.5.0'.", Line: 1, Column: 9, EndLine: 1, EndColumn: 22}}},
			{Code: "var a = async () => 1",
				Options: []any{map[string]any{"version": "7.1.0"}},
				Errors:  []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'async-functions' is not supported until Node.js >=7.6.0. The configured version range is '7.1.0'.", Line: 1, Column: 9, EndLine: 1, EndColumn: 22}}},
			{Code: "var a = async () => 1",
				Settings: map[string]any{"node": map[string]any{"version": "7.1.0"}},
				Errors:   []rule_tester.InvalidTestCaseError{{MessageId: "not-supported-till", Message: "'async-functions' is not supported until Node.js >=7.6.0. The configured version range is '7.1.0'.", Line: 1, Column: 9, EndLine: 1, EndColumn: 22}}},
		}},
	}
	for _, group := range groups {
		t.Run(group.name, func(t *testing.T) {
			valid := group.valid
			// Preserve upstream's generated valid cases for every legacy ignore alias.
			for _, ignore := range group.ignores {
				for _, item := range group.invalid {
					options := map[string]any{}
					if values, ok := item.Options.([]any); ok && len(values) > 0 {
						options = maps.Clone(values[0].(map[string]any))
					}
					ignored, _ := options["ignores"].([]any)
					options["ignores"] = append(append([]any{}, ignored...), ignore)
					valid = append(valid, rule_tester.ValidTestCase{Code: item.Code, FileName: item.FileName, Options: []any{options}, Settings: item.Settings, LanguageOptions: item.LanguageOptions})
				}
			}
			runSyntaxTests(t, valid, group.invalid)
		})
	}
}

// The upstream documentation contains configuration examples only.
func TestESSyntaxDocumentation(t *testing.T) {
	runSyntaxTests(t, []rule_tester.ValidTestCase{
		{Code: "", Options: map[string]any{"version": ">=16.0.0", "ignores": []any{}}},
		{Code: "", Options: map[string]any{"ignores": []any{}}, Settings: map[string]any{"node": map[string]any{"version": ">=16.0.0"}}},
	}, nil)
}
