// cspell:ignore arraybuffers codepointat copywithin datetimeformat defineproperties defineproperty displaynames endswith
// cspell:ignore findindex findlast findlastindex fontcolor fontsize formatrange formatrangetoparts formattoparts
// cspell:ignore fromcodepoint fromentries getcanonicallocales getownpropertydescriptor getownpropertydescriptors
// cspell:ignore getownpropertynames getownpropertysymbols getprototypeof getyear groupby hasown indexof isextensible
// cspell:ignore isfinite isfrozen isinteger issafeinteger issealed iswellformed lastindexof listformat matchall
// cspell:ignore maxsafeinteger minsafeinteger numberformat padend padstart parsefloat parseint pluralrules
// cspell:ignore preventextensions reduceright relativetimeformat replaceall selectrange setprototypeof setyear startswith
// cspell:ignore supportedvaluesof togmtstring toreversed tosorted tospliced towellformed trimend trimleft trimright
// cspell:ignore trimstart waitasync weakrefs withresolvers
// Feature versions and aliases from eslint-plugin-n v18.3.0; API paths from eslint-plugin-es-x v7.8.0.
// https://github.com/eslint-community/eslint-plugin-n/blob/v18.3.0/lib/rules/no-unsupported-features/es-syntax.json
package es_syntax

type feature struct {
	name, supported, sloppy string
	aliases, reads          []string
	prototypes              []prototype
}
type prototype struct {
	class      string
	properties []string
}

var features = []feature{
	{name: "accessor-properties", supported: ">=0.10.0"},
	{name: "arbitrary-module-namespace-names", supported: ">=13.2.0"},
	{name: "array-from", supported: ">=4.0.0", reads: []string{"Array.from"}},
	{name: "array-isarray", supported: ">=0.10.0", reads: []string{"Array.isArray"}},
	{name: "array-of", supported: ">=4.0.0", reads: []string{"Array.of"}},
	{name: "array-prototype-copywithin", supported: ">=4.0.0", prototypes: []prototype{{"Array", []string{"copyWithin"}}}},
	{name: "array-prototype-entries", supported: ">=0.12.0", prototypes: []prototype{{"Array", []string{"entries"}}}},
	{name: "array-prototype-every", supported: ">=0.10.0", prototypes: []prototype{{"Array", []string{"every"}}}},
	{name: "array-prototype-fill", supported: ">=4.0.0", prototypes: []prototype{{"Array", []string{"fill"}}}},
	{name: "array-prototype-filter", supported: ">=0.10.0", prototypes: []prototype{{"Array", []string{"filter"}}}},
	{name: "array-prototype-find", supported: ">=4.0.0", prototypes: []prototype{{"Array", []string{"find"}}}},
	{name: "array-prototype-findindex", supported: ">=4.0.0", prototypes: []prototype{{"Array", []string{"findIndex"}}}},
	{name: "array-prototype-findlast-findlastindex", supported: ">=18.0.0", prototypes: []prototype{{"Array", []string{"findLast", "findLastIndex"}}, {"Int8Array", []string{"findLast", "findLastIndex"}}, {"Uint8Array", []string{"findLast", "findLastIndex"}}, {"Uint8ClampedArray", []string{"findLast", "findLastIndex"}}, {"Int16Array", []string{"findLast", "findLastIndex"}}, {"Uint16Array", []string{"findLast", "findLastIndex"}}, {"Int32Array", []string{"findLast", "findLastIndex"}}, {"Uint32Array", []string{"findLast", "findLastIndex"}}, {"Float32Array", []string{"findLast", "findLastIndex"}}, {"Float64Array", []string{"findLast", "findLastIndex"}}, {"BigInt64Array", []string{"findLast", "findLastIndex"}}, {"BigUint64Array", []string{"findLast", "findLastIndex"}}}},
	{name: "array-prototype-flat", supported: ">=11.0.0", prototypes: []prototype{{"Array", []string{"flat", "flatMap"}}}},
	{name: "array-prototype-foreach", supported: ">=0.10.0", prototypes: []prototype{{"Array", []string{"forEach"}}}},
	{name: "array-prototype-includes", supported: ">=6.0.0", prototypes: []prototype{{"Array", []string{"includes"}}, {"Int8Array", []string{"includes"}}, {"Uint8Array", []string{"includes"}}, {"Uint8ClampedArray", []string{"includes"}}, {"Int16Array", []string{"includes"}}, {"Uint16Array", []string{"includes"}}, {"Int32Array", []string{"includes"}}, {"Uint32Array", []string{"includes"}}, {"Float32Array", []string{"includes"}}, {"Float64Array", []string{"includes"}}, {"BigInt64Array", []string{"includes"}}, {"BigUint64Array", []string{"includes"}}}},
	{name: "array-prototype-indexof", supported: ">=0.10.0", prototypes: []prototype{{"Array", []string{"indexOf"}}}},
	{name: "array-prototype-keys", supported: ">=0.12.0", prototypes: []prototype{{"Array", []string{"keys"}}}},
	{name: "array-prototype-lastindexof", supported: ">=0.10.0", prototypes: []prototype{{"Array", []string{"lastIndexOf"}}}},
	{name: "array-prototype-map", supported: ">=0.10.0", prototypes: []prototype{{"Array", []string{"map"}}}},
	{name: "array-prototype-reduce", supported: ">=0.10.0", prototypes: []prototype{{"Array", []string{"reduce"}}}},
	{name: "array-prototype-reduceright", supported: ">=0.10.0", prototypes: []prototype{{"Array", []string{"reduceRight"}}}},
	{name: "array-prototype-some", supported: ">=0.10.0", prototypes: []prototype{{"Array", []string{"some"}}}},
	{name: "array-prototype-toreversed", supported: ">=20.0.0", prototypes: []prototype{{"Array", []string{"toReversed"}}, {"Int8Array", []string{"toReversed"}}, {"Uint8Array", []string{"toReversed"}}, {"Uint8ClampedArray", []string{"toReversed"}}, {"Int16Array", []string{"toReversed"}}, {"Uint16Array", []string{"toReversed"}}, {"Int32Array", []string{"toReversed"}}, {"Uint32Array", []string{"toReversed"}}, {"Float32Array", []string{"toReversed"}}, {"Float64Array", []string{"toReversed"}}, {"BigInt64Array", []string{"toReversed"}}, {"BigUint64Array", []string{"toReversed"}}}},
	{name: "array-prototype-tosorted", supported: ">=20.0.0", prototypes: []prototype{{"Array", []string{"toSorted"}}, {"Int8Array", []string{"toSorted"}}, {"Uint8Array", []string{"toSorted"}}, {"Uint8ClampedArray", []string{"toSorted"}}, {"Int16Array", []string{"toSorted"}}, {"Uint16Array", []string{"toSorted"}}, {"Int32Array", []string{"toSorted"}}, {"Uint32Array", []string{"toSorted"}}, {"Float32Array", []string{"toSorted"}}, {"Float64Array", []string{"toSorted"}}, {"BigInt64Array", []string{"toSorted"}}, {"BigUint64Array", []string{"toSorted"}}}},
	{name: "array-prototype-tospliced", supported: ">=20.0.0", prototypes: []prototype{{"Array", []string{"toSpliced"}}}},
	{name: "array-prototype-values", supported: ">=10.9.0", prototypes: []prototype{{"Array", []string{"values"}}}},
	{name: "array-prototype-with", supported: ">=20.0.0", prototypes: []prototype{{"Array", []string{"with"}}, {"Int8Array", []string{"with"}}, {"Uint8Array", []string{"with"}}, {"Uint8ClampedArray", []string{"with"}}, {"Int16Array", []string{"with"}}, {"Uint16Array", []string{"with"}}, {"Int32Array", []string{"with"}}, {"Uint32Array", []string{"with"}}, {"Float32Array", []string{"with"}}, {"Float64Array", []string{"with"}}, {"BigInt64Array", []string{"with"}}, {"BigUint64Array", []string{"with"}}}},
	{name: "array-string-prototype-at", supported: ">=16.6.0", prototypes: []prototype{{"Array", []string{"at"}}, {"String", []string{"at"}}, {"Int8Array", []string{"at"}}, {"Uint8Array", []string{"at"}}, {"Uint8ClampedArray", []string{"at"}}, {"Int16Array", []string{"at"}}, {"Uint16Array", []string{"at"}}, {"Int32Array", []string{"at"}}, {"Uint32Array", []string{"at"}}, {"Float32Array", []string{"at"}}, {"Float64Array", []string{"at"}}, {"BigInt64Array", []string{"at"}}, {"BigUint64Array", []string{"at"}}}},
	{name: "arrow-functions", supported: ">=4.0.0"},
	{name: "async-functions", supported: ">=7.6.0"},
	{name: "async-iteration", supported: ">=10.0.0"},
	{name: "atomics-waitasync", supported: ">=16.0.0", reads: []string{"Atomics.waitAsync"}},
	{name: "atomics", supported: ">=8.10.0", reads: []string{"Atomics"}},
	{name: "bigint", supported: ">=10.4.0", reads: []string{"BigInt", "BigInt64Array", "BigUint64Array"}},
	{name: "binary-numeric-literals", supported: ">=4.0.0"},
	{name: "block-scoped-functions", supported: ">=4.0.0", sloppy: ">=6.0.0"},
	{name: "block-scoped-variables", supported: ">=4.0.0", sloppy: ">=6.0.0"},
	{name: "class-fields", supported: ">=12.0.0"},
	{name: "class-static-block", supported: ">=16.11.0"},
	{name: "classes", supported: ">=4.0.0", sloppy: ">=6.0.0"},
	{name: "computed-properties", supported: ">=4.0.0"},
	{name: "date-now", supported: ">=0.10.0", reads: []string{"Date.now"}},
	{name: "date-prototype-getyear-setyear", supported: ">=0.10.0", prototypes: []prototype{{"Date", []string{"getYear", "setYear"}}}},
	{name: "date-prototype-togmtstring", supported: ">=0.10.0", prototypes: []prototype{{"Date", []string{"toGMTString"}}}},
	{name: "default-parameters", supported: ">=6.0.0"},
	{name: "destructuring", supported: ">=6.0.0"},
	{name: "dynamic-import", supported: "^12.17.0 || >=13.2.0"},
	{name: "error-cause", supported: ">=16.9.0"},
	{name: "escape-unescape", supported: ">=0.10.0", reads: []string{"escape", "unescape"}},
	{name: "exponential-operators", supported: ">=7.0.0"},
	{name: "export-ns-from", supported: ">=13.2.0"},
	{name: "for-of-loops", supported: ">=0.12.0"},
	{name: "function-declarations-in-if-statement-clauses-without-block", supported: ">=0.10.0"},
	{name: "function-prototype-bind", supported: ">=0.10.0", prototypes: []prototype{{"Function", []string{"bind"}}}},
	{name: "generators", supported: ">=4.0.0"},
	{name: "global-this", supported: ">=12.0.0", reads: []string{"globalThis"}},
	{name: "hashbang", supported: ">=12.5.0"},
	{name: "import-meta", supported: ">=10.4.0"},
	{name: "initializers-in-for-in", supported: ">=0.10.0"},
	{name: "intl-datetimeformat-prototype-formatrange", supported: ">=12.9.0", prototypes: []prototype{{"Intl.DateTimeFormat", []string{"formatRange"}}}},
	{name: "intl-datetimeformat-prototype-formattoparts", supported: ">=12.9.0", prototypes: []prototype{{"Intl.DateTimeFormat", []string{"formatToParts"}}}},
	{name: "intl-displaynames", supported: ">=14.0.0", reads: []string{"Intl.DisplayNames"}},
	{name: "intl-getcanonicallocales", supported: ">=7.0.0", reads: []string{"Intl.getCanonicalLocales"}},
	{name: "intl-listformat", supported: ">=12.0.0", reads: []string{"Intl.ListFormat"}},
	{name: "intl-locale", supported: ">=12.0.0", reads: []string{"Intl.Locale"}},
	{name: "intl-numberformat-prototype-formatrange", supported: ">=19.0.0", prototypes: []prototype{{"Intl.NumberFormat", []string{"formatRange"}}}},
	{name: "intl-numberformat-prototype-formatrangetoparts", supported: ">=19.0.0", prototypes: []prototype{{"Intl.NumberFormat", []string{"formatRangeToParts"}}}},
	{name: "intl-numberformat-prototype-formattoparts", supported: ">=10.0.0", prototypes: []prototype{{"Intl.NumberFormat", []string{"formatToParts"}}}},
	{name: "intl-pluralrules-prototype-selectrange", supported: ">=19.0.0", prototypes: []prototype{{"Intl.PluralRules", []string{"selectRange"}}}},
	{name: "intl-pluralrules", supported: ">=10.0.0", reads: []string{"Intl.PluralRules"}},
	{name: "intl-relativetimeformat", supported: ">=12.0.0", reads: []string{"Intl.RelativeTimeFormat"}},
	{name: "intl-segmenter", supported: ">=16.0.0", reads: []string{"Intl.Segmenter"}},
	{name: "intl-supportedvaluesof", supported: ">=18.0.0", reads: []string{"Intl.supportedValuesOf"}},
	{name: "json-superset", supported: ">=10.0.0"},
	{name: "json", supported: ">=0.10.0", reads: []string{"JSON"}},
	{name: "keyword-properties", supported: ">=0.10.0"},
	{name: "labelled-function-declarations", supported: ">=0.10.0"},
	{name: "legacy-object-prototype-accessor-methods", supported: ">=0.10.0"},
	{name: "logical-assignment-operators", supported: ">=15.0.0"},
	{name: "malformed-template-literals", supported: ">=8.10.0"},
	{name: "map", supported: ">=0.12.0", reads: []string{"Map"}},
	{name: "math-acosh", supported: ">=0.12.0", reads: []string{"Math.acosh"}},
	{name: "math-asinh", supported: ">=0.12.0", reads: []string{"Math.asinh"}},
	{name: "math-atanh", supported: ">=0.12.0", reads: []string{"Math.atanh"}},
	{name: "math-cbrt", supported: ">=0.12.0", reads: []string{"Math.cbrt"}},
	{name: "math-clz32", supported: ">=0.12.0", reads: []string{"Math.clz32"}},
	{name: "math-cosh", supported: ">=0.12.0", reads: []string{"Math.cosh"}},
	{name: "math-expm1", supported: ">=0.12.0", reads: []string{"Math.expm1"}},
	{name: "math-fround", supported: ">=0.12.0", reads: []string{"Math.fround"}},
	{name: "math-hypot", supported: ">=0.12.0", reads: []string{"Math.hypot"}},
	{name: "math-imul", supported: ">=0.12.0", reads: []string{"Math.imul"}},
	{name: "math-log10", supported: ">=0.12.0", reads: []string{"Math.log10"}},
	{name: "math-log1p", supported: ">=0.12.0", reads: []string{"Math.log1p"}},
	{name: "math-log2", supported: ">=0.12.0", reads: []string{"Math.log2"}},
	{name: "math-sign", supported: ">=0.12.0", reads: []string{"Math.sign"}},
	{name: "math-sinh", supported: ">=0.12.0", reads: []string{"Math.sinh"}},
	{name: "math-tanh", supported: ">=0.12.0", reads: []string{"Math.tanh"}},
	{name: "math-trunc", supported: ">=0.12.0", reads: []string{"Math.trunc"}},
	{name: "modules", supported: "^12.17.0 || >=13.2.0"},
	{name: "new-target", supported: ">=5.0.0", aliases: []string{"new.target"}},
	{name: "nullish-coalescing-operators", supported: ">=14.0.0"},
	{name: "number-epsilon", supported: ">=0.12.0", reads: []string{"Number.EPSILON"}},
	{name: "number-isfinite", supported: ">=0.10.0", reads: []string{"Number.isFinite"}},
	{name: "number-isinteger", supported: ">=0.10.0", reads: []string{"Number.isInteger"}},
	{name: "number-isnan", supported: ">=0.10.0", reads: []string{"Number.isNaN"}},
	{name: "number-issafeinteger", supported: ">=0.12.0", reads: []string{"Number.isSafeInteger"}},
	{name: "number-maxsafeinteger", supported: ">=0.12.0", reads: []string{"Number.MAX_SAFE_INTEGER"}},
	{name: "number-minsafeinteger", supported: ">=0.12.0", reads: []string{"Number.MIN_SAFE_INTEGER"}},
	{name: "number-parsefloat", supported: ">=0.12.0", reads: []string{"Number.parseFloat"}},
	{name: "number-parseint", supported: ">=0.12.0", reads: []string{"Number.parseInt"}},
	{name: "numeric-separators", supported: ">=12.5.0"},
	{name: "object-assign", supported: ">=4.0.0", reads: []string{"Object.assign"}},
	{name: "object-create", supported: ">=0.10.0", reads: []string{"Object.create"}},
	{name: "object-defineproperties", supported: ">=0.10.0", reads: []string{"Object.defineProperties"}},
	{name: "object-defineproperty", supported: ">=0.10.0", reads: []string{"Object.defineProperty"}},
	{name: "object-entries", supported: ">=7.0.0", reads: []string{"Object.entries"}},
	{name: "object-freeze", supported: ">=0.10.0", reads: []string{"Object.freeze"}},
	{name: "object-fromentries", supported: ">=12.0.0", reads: []string{"Object.fromEntries"}},
	{name: "object-getownpropertydescriptor", supported: ">=0.10.0", reads: []string{"Object.getOwnPropertyDescriptor"}},
	{name: "object-getownpropertydescriptors", supported: ">=7.0.0", reads: []string{"Object.getOwnPropertyDescriptors"}},
	{name: "object-getownpropertynames", supported: ">=0.10.0", reads: []string{"Object.getOwnPropertyNames"}},
	{name: "object-getownpropertysymbols", supported: ">=0.12.0", reads: []string{"Object.getOwnPropertySymbols"}},
	{name: "object-getprototypeof", supported: ">=0.10.0", reads: []string{"Object.getPrototypeOf"}},
	{name: "object-hasown", supported: ">=16.9.0", reads: []string{"Object.hasOwn"}},
	{name: "object-is", supported: ">=0.10.0", reads: []string{"Object.is"}},
	{name: "object-isextensible", supported: ">=0.10.0", reads: []string{"Object.isExtensible"}},
	{name: "object-isfrozen", supported: ">=0.10.0", reads: []string{"Object.isFrozen"}},
	{name: "object-issealed", supported: ">=0.10.0", reads: []string{"Object.isSealed"}},
	{name: "object-keys", supported: ">=0.10.0", reads: []string{"Object.keys"}},
	{name: "object-map-groupby", supported: ">=21.0.0", reads: []string{"Object.groupBy", "Map.groupBy"}},
	{name: "object-preventextensions", supported: ">=0.10.0", reads: []string{"Object.preventExtensions"}},
	{name: "object-seal", supported: ">=0.10.0", reads: []string{"Object.seal"}},
	{name: "object-setprototypeof", supported: ">=0.12.0", reads: []string{"Object.setPrototypeOf"}},
	{name: "object-super-properties", supported: ">=4.0.0"},
	{name: "object-values", supported: ">=7.0.0", reads: []string{"Object.values"}},
	{name: "octal-numeric-literals", supported: ">=4.0.0"},
	{name: "optional-catch-binding", supported: ">=10.0.0"},
	{name: "optional-chaining", supported: ">=14.0.0"},
	{name: "private-in", supported: ">=16.4.0"},
	{name: "promise-all-settled", supported: ">=12.9.0", reads: []string{"Promise.allSettled"}},
	{name: "promise-any", supported: ">=15.0.0", reads: []string{"AggregateError", "Promise.any"}},
	{name: "promise-prototype-finally", supported: ">=10.0.0", prototypes: []prototype{{"Promise", []string{"finally"}}}},
	{name: "promise-withresolvers", supported: ">=22.11.0", reads: []string{"Promise.withResolvers"}},
	{name: "promise", supported: ">=0.12.0", reads: []string{"Promise"}},
	{name: "property-shorthands", supported: ">=4.0.0"},
	{name: "proxy", supported: ">=6.0.0", reads: []string{"Proxy"}},
	{name: "reflect", supported: ">=6.0.0", reads: []string{"Reflect"}},
	{name: "regexp-d-flag", supported: ">=16.0.0"},
	{name: "regexp-lookbehind-assertions", supported: ">=8.10.0", aliases: []string{"regexpLookbehind"}},
	{name: "regexp-named-capture-groups", supported: ">=10.0.0"},
	{name: "regexp-prototype-compile", supported: ">=0.10.0", prototypes: []prototype{{"RegExp", []string{"compile"}}}},
	{name: "regexp-prototype-flags", supported: ">=6.0.0", prototypes: []prototype{{"RegExp", []string{"flags"}}}},
	{name: "regexp-s-flag", supported: ">=8.10.0", aliases: []string{"regexpS"}},
	{name: "regexp-u-flag", supported: ">=6.0.0", aliases: []string{"regexpU"}},
	{name: "regexp-unicode-property-escapes-2019", supported: ">=12.1.0 || ^10.16.0"},
	{name: "regexp-unicode-property-escapes-2020", supported: ">=13.12.0 || ^12.17.0"},
	{name: "regexp-unicode-property-escapes-2021", supported: ">=17.2.0 || ^16.14.0"},
	{name: "regexp-unicode-property-escapes-2022", supported: ">=19.1.0 || ^18.13.0"},
	{name: "regexp-unicode-property-escapes-2023", supported: "<0"},
	{name: "regexp-unicode-property-escapes", supported: ">=10.0.0", aliases: []string{"regexpUnicodeProperties"}},
	{name: "regexp-v-flag", supported: ">=20.0.0"},
	{name: "regexp-y-flag", supported: ">=6.0.0", aliases: []string{"regexpY"}},
	{name: "resizable-and-growable-arraybuffers", supported: ">=20.0.0", prototypes: []prototype{{"ArrayBuffer", []string{"maxByteLength", "resizable", "resize"}}, {"SharedArrayBuffer", []string{"grow", "growable", "maxByteLength"}}}},
	{name: "rest-parameters", supported: ">=6.0.0"},
	{name: "rest-spread-properties", supported: ">=8.3.0"},
	{name: "set", supported: ">=0.12.0", reads: []string{"Set"}},
	{name: "shadow-catch-param", supported: ">=0.10.0"},
	{name: "shared-array-buffer", supported: ">=8.10.0", reads: []string{"SharedArrayBuffer"}},
	{name: "spread-elements", supported: ">=5.0.0"},
	{name: "string-create-html-methods", supported: ">=0.10.0", prototypes: []prototype{{"String", []string{"anchor", "big", "blink", "bold", "fixed", "fontcolor", "fontsize", "italics", "link", "small", "strike", "sub", "sup"}}}},
	{name: "string-fromcodepoint", supported: ">=4.0.0", reads: []string{"String.fromCodePoint"}},
	{name: "string-prototype-codepointat", supported: ">=4.0.0", prototypes: []prototype{{"String", []string{"codePointAt"}}}},
	{name: "string-prototype-endswith", supported: ">=4.0.0", prototypes: []prototype{{"String", []string{"endsWith"}}}},
	{name: "string-prototype-includes", supported: ">=6.0.0", prototypes: []prototype{{"String", []string{"includes"}}}},
	{name: "string-prototype-iswellformed-towellformed", supported: ">=20.0.0", prototypes: []prototype{{"String", []string{"isWellFormed", "toWellFormed"}}}},
	{name: "string-prototype-matchall", supported: ">=12.0.0", prototypes: []prototype{{"String", []string{"matchAll"}}}},
	{name: "string-prototype-normalize", supported: ">=0.12.0", prototypes: []prototype{{"String", []string{"normalize"}}}},
	{name: "string-prototype-padstart-padend", supported: ">=8.0.0", prototypes: []prototype{{"String", []string{"padEnd", "padStart"}}}},
	{name: "string-prototype-repeat", supported: ">=4.0.0", prototypes: []prototype{{"String", []string{"repeat"}}}},
	{name: "string-prototype-replaceall", supported: ">=15.0.0", prototypes: []prototype{{"String", []string{"replaceAll"}}}},
	{name: "string-prototype-startswith", supported: ">=4.0.0", prototypes: []prototype{{"String", []string{"startsWith"}}}},
	{name: "string-prototype-substr", supported: ">=0.10.0", prototypes: []prototype{{"String", []string{"substr"}}}},
	{name: "string-prototype-trim", supported: ">=0.10.0", prototypes: []prototype{{"String", []string{"trim"}}}},
	{name: "string-prototype-trimleft-trimright", supported: ">=0.10.0", prototypes: []prototype{{"String", []string{"trimLeft", "trimRight"}}}},
	{name: "string-prototype-trimstart-trimend", supported: ">=10.0.0", prototypes: []prototype{{"String", []string{"trimEnd", "trimStart"}}}},
	{name: "string-raw", supported: ">=4.0.0", reads: []string{"String.raw"}},
	{name: "subclassing-builtins", supported: ">=4.0.0", reads: []string{"Array", "Boolean", "Error", "RegExp", "Function", "Map", "Number", "Promise", "Set", "String"}},
	{name: "symbol-prototype-description", supported: ">=11.0.0", prototypes: []prototype{{"Symbol", []string{"description"}}}},
	{name: "symbol", supported: ">=0.12.0", reads: []string{"Symbol"}},
	{name: "template-literals", supported: ">=4.0.0"},
	{name: "top-level-await", supported: ">=14.8.0"},
	{name: "trailing-commas", supported: ">=0.10.0"},
	{name: "trailing-function-commas", supported: ">=8.0.0", aliases: []string{"trailingCommasInFunctions"}},
	{name: "typed-arrays", supported: ">=0.10.0", reads: []string{"Int8Array", "Uint8Array", "Uint8ClampedArray", "Int16Array", "Uint16Array", "Int32Array", "Uint32Array", "Float32Array", "Float64Array", "DataView"}},
	{name: "unicode-codepoint-escapes", supported: ">=4.0.0", aliases: []string{"unicodeCodePointEscapes"}},
	{name: "weak-map", supported: ">=0.12.0", reads: []string{"WeakMap"}},
	{name: "weak-set", supported: ">=0.12.0", reads: []string{"WeakSet"}},
	{name: "weakrefs", supported: ">=14.6.0", reads: []string{"FinalizationRegistry", "WeakRef"}},
}
