import { RuleTester } from '../rule-tester';

// `aria-query`'s `roles.keys()`, partitioned by `abstract === false` / `=== true`.
// Order matches the live aria-query output (ARIA 1.x core alphabetic,
// followed by DPUB-ARIA `doc-*`, then Graphics-ARIA `graphics-*`). Mirrors
// the Go-side `jsxa11yutil.AriaRoleNonAbstract` / `AriaRoleAbstract` data.
const validRoles = [
  'alert',
  'alertdialog',
  'application',
  'article',
  'banner',
  'blockquote',
  'button',
  'caption',
  'cell',
  'checkbox',
  'code',
  'columnheader',
  'combobox',
  'complementary',
  'contentinfo',
  'definition',
  'deletion',
  'dialog',
  'directory',
  'document',
  'emphasis',
  'feed',
  'figure',
  'form',
  'generic',
  'grid',
  'gridcell',
  'group',
  'heading',
  'img',
  'insertion',
  'link',
  'list',
  'listbox',
  'listitem',
  'log',
  'main',
  'mark',
  'marquee',
  'math',
  'menu',
  'menubar',
  'menuitem',
  'menuitemcheckbox',
  'menuitemradio',
  'meter',
  'navigation',
  'none',
  'note',
  'option',
  'paragraph',
  'presentation',
  'progressbar',
  'radio',
  'radiogroup',
  'region',
  'row',
  'rowgroup',
  'rowheader',
  'scrollbar',
  'search',
  'searchbox',
  'separator',
  'slider',
  'spinbutton',
  'status',
  'strong',
  'subscript',
  'superscript',
  'switch',
  'tab',
  'table',
  'tablist',
  'tabpanel',
  'term',
  'textbox',
  'time',
  'timer',
  'toolbar',
  'tooltip',
  'tree',
  'treegrid',
  'treeitem',
  // DPUB-ARIA roles.
  'doc-abstract',
  'doc-acknowledgments',
  'doc-afterword',
  'doc-appendix',
  'doc-backlink',
  'doc-biblioentry',
  'doc-bibliography',
  'doc-biblioref',
  'doc-chapter',
  'doc-colophon',
  'doc-conclusion',
  'doc-cover',
  'doc-credit',
  'doc-credits',
  'doc-dedication',
  'doc-endnote',
  'doc-endnotes',
  'doc-epigraph',
  'doc-epilogue',
  'doc-errata',
  'doc-example',
  'doc-footnote',
  'doc-foreword',
  'doc-glossary',
  'doc-glossref',
  'doc-index',
  'doc-introduction',
  'doc-noteref',
  'doc-notice',
  'doc-pagebreak',
  'doc-pagefooter',
  'doc-pageheader',
  'doc-pagelist',
  'doc-part',
  'doc-preface',
  'doc-prologue',
  'doc-pullquote',
  'doc-qna',
  'doc-subtitle',
  'doc-tip',
  'doc-toc',
  // Graphics-ARIA roles.
  'graphics-document',
  'graphics-object',
  'graphics-symbol',
];

const abstractRoles = [
  'command',
  'composite',
  'input',
  'landmark',
  'range',
  'roletype',
  'section',
  'sectionhead',
  'select',
  'structure',
  'widget',
  'window',
];

const errorMessage =
  'Elements with ARIA roles must use a valid, non-abstract ARIA role.';

const allowedInvalidRolesOption = [
  { allowedInvalidRoles: ['invalid-role', 'other-invalid-role'] },
];
const ignoreNonDOMOption = [{ ignoreNonDOM: true }];

const customDivSettings = {
  'jsx-a11y': {
    polymorphicPropName: 'asChild',
    components: { Div: 'div' },
  },
};

new RuleTester().run('aria-role', null as never, {
  valid: [
    // Upstream test file — order preserved.
    { code: '<div />' },
    { code: '<div></div>' },
    { code: '<div role={role} />' },
    { code: '<div role={role || "button"} />' },
    { code: '<div role={role || "foobar"} />' },
    { code: '<div role="tabpanel row" />' },
    { code: '<div role="switch" />' },
    { code: '<div role="doc-abstract" />' },
    { code: '<div role="doc-appendix doc-bibliography" />' },
    { code: '<Bar baz />' },
    {
      code: '<img role="invalid-role" />',
      options: allowedInvalidRolesOption,
    },
    {
      code: '<img role="invalid-role tabpanel" />',
      options: allowedInvalidRolesOption,
    },
    {
      code: '<img role="invalid-role other-invalid-role" />',
      options: allowedInvalidRolesOption,
    },
    { code: '<Foo role="bar" />', options: ignoreNonDOMOption },
    { code: '<fakeDOM role="bar" />', options: ignoreNonDOMOption },
    { code: '<img role="presentation" />', options: ignoreNonDOMOption },
    { code: '<Div role="button" />', settings: customDivSettings },
    {
      code: '<Box asChild="div" role="button" />',
      settings: customDivSettings,
    },
    { code: '<svg role="graphics-document document" />' },
    { code: '<svg role="img" />' },
    // Upstream's createTests(validRoles) — one per non-abstract role.
    ...validRoles.map((role) => ({ code: `<div role="${role}" />` })),
  ],
  invalid: [
    // Upstream test file — order preserved.
    { code: '<div role="foobar" />', errors: [{ message: errorMessage }] },
    {
      code: '<div role="datepicker"></div>',
      errors: [{ message: errorMessage }],
    },
    { code: '<div role="range"></div>', errors: [{ message: errorMessage }] },
    {
      code: '<div role="Button"></div>',
      errors: [{ message: errorMessage }],
    },
    { code: '<div role=""></div>', errors: [{ message: errorMessage }] },
    {
      code: '<div role="tabpanel row foobar"></div>',
      errors: [{ message: errorMessage }],
    },
    {
      code: '<div role="tabpanel row range"></div>',
      errors: [{ message: errorMessage }],
    },
    {
      code: '<div role="doc-endnotes range"></div>',
      errors: [{ message: errorMessage }],
    },
    { code: '<div role />', errors: [{ message: errorMessage }] },
    {
      code: '<div role="unknown-invalid-role" />',
      options: allowedInvalidRolesOption,
      errors: [{ message: errorMessage }],
    },
    { code: '<div role={null}></div>', errors: [{ message: errorMessage }] },
    { code: '<Foo role="datepicker" />', errors: [{ message: errorMessage }] },
    { code: '<Foo role="Button" />', errors: [{ message: errorMessage }] },
    {
      code: '<Div role="Button" />',
      settings: customDivSettings,
      errors: [{ message: errorMessage }],
    },
    {
      code: '<Div role="Button" />',
      options: ignoreNonDOMOption,
      settings: customDivSettings,
      errors: [{ message: errorMessage }],
    },
    {
      code: '<Box asChild="div" role="Button" />',
      settings: customDivSettings,
      errors: [{ message: errorMessage }],
    },
    // Upstream's createTests(invalidRoles) — one per abstract role.
    ...abstractRoles.map((role) => ({
      code: `<div role="${role}" />`,
      errors: [{ message: errorMessage }],
    })),
  ],
});
