// TestPreferReadonlyParameterTypesUpstream migrates the full valid/invalid
// suite from upstream packages/eslint-plugin/tests/rules/prefer-readonly-parameter-types.test.ts
// at v8.68.0 1:1. Position assertions cover every invalid case.
// rslint-specific lock-ins live in prefer_readonly_parameter_types_extras_test.go.
package prefer_readonly_parameter_types

import (
	"testing"

	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/fixtures"
	"github.com/web-infra-dev/rslint/internal/rule_tester"
)

func TestPreferReadonlyParameterTypesUpstream(t *testing.T) {
	rule_tester.RunRuleTester(fixtures.GetRootDir(), "tsconfig.json", t, &PreferReadonlyParameterTypesRule, []rule_tester.ValidTestCase{
		{Code: "function foo() {}"},
		{Code: "function foo(arg: boolean) {}"},
		{Code: "function foo(arg: true) {}"},
		{Code: "function foo(arg: string) {}"},
		{Code: "function foo(arg: 'a') {}"},
		{Code: "function foo(arg: number) {}"},
		{Code: "function foo(arg: 1) {}"},
		{Code: "function foo(arg: symbol) {}"},
		{Code: "function foo(arg: any) {}"},
		{Code: "function foo(arg: unknown) {}"},
		{Code: "function foo(arg: never) {}"},
		{Code: "function foo(arg: null) {}"},
		{Code: "function foo(arg: undefined) {}"},
		{Code: "\nconst symb = Symbol('a');\nfunction foo(arg: typeof symb) {}\n    "},
		{Code: "\nenum Enum {\n  a,\n  b,\n}\nfunction foo(arg: Enum) {}\n    "},
		{Code: "function foo(arg: readonly string[]) {}"},
		{Code: "function foo(arg: Readonly<string[]>) {}"},
		{Code: "function foo(arg: ReadonlyArray<string>) {}"},
		{Code: "function foo(arg: readonly [string]) {}"},
		{Code: "function foo(arg: Readonly<[string]>) {}"},
		{Code: "function foo(arg: readonly (readonly string[])[]) {}"},
		{Code: "function foo(arg: Readonly<Readonly<string[]>[]>) {}"},
		{Code: "function foo(arg: ReadonlyArray<ReadonlyArray<string>>) {}"},
		{Code: "function foo(arg: () => void) {}"},
		{Code: "function foo(arg: string | null) {}"},
		{Code: "function foo(arg: string | ReadonlyArray<string>) {}"},
		{Code: "function foo(arg: string | (() => void)) {}"},
		{Code: "function foo(arg: ReadonlyArray<string> | ReadonlyArray<number>) {}"},
		{Code: "function foo(arg: Readonly<{ foo: '' }>) {}"},
		{Code: "function foo(arg: Readonly<{ foo: readonly string[] }>) {}"},
		{Code: "function foo(arg: Readonly<{ foo(): void }>) {}"},
		{Code: "\nfunction foo(arg: {\n  readonly foo: {\n    readonly bar: string;\n  };\n}) {}\n    "},
		{Code: "\nfunction foo(arg: { readonly [k: string]: string }) {}\n    "},
		{Code: "\nfunction foo(arg: { readonly [k: number]: string }) {}\n    "},
		{Code: "\ninterface Empty {}\nfunction foo(arg: Empty) {}\n    "},
		{Code: "\ninterface Test {\n  (): void;\n  readonly property: boolean;\n}\nfunction foo(arg: Test) {}\n    "},
		{Code: "\ntype Test = (() => void) & {\n  readonly property: boolean;\n};\nfunction foo(arg: Test) {}\n    "},
		{Code: "\ninterface Test extends ReadonlyArray<string> {\n  readonly property: boolean;\n}\nfunction foo(arg: Readonly<Test>) {}\n    "},
		{Code: "\ntype Test = readonly string[] & {\n  readonly property: boolean;\n};\nfunction foo(arg: Readonly<Test>) {}\n    "},
		{Code: "\ntype Test = string & number;\nfunction foo(arg: Test) {}\n    "},
		{Code: "\nclass Foo {\n  readonly bang = 1;\n}\ninterface Foo {\n  readonly prop: string;\n}\ninterface Foo {\n  readonly prop2: string;\n}\nfunction foo(arg: Foo) {}\n    "},
		{Code: "\nclass Foo {\n  method() {}\n}\nfunction foo(arg: Readonly<Foo>) {}\n    "},
		{Code: "\ntype MyType = Readonly<{\n  prop: string;\n  method(): string;\n}>;\nfunction foo(arg: MyType) {}\n    "},
		{Code: "\ntype MyType = {\n  readonly prop: string;\n  readonly method: () => string;\n};\nfunction bar(arg: MyType) {}\n    "},
		{Code: "\nclass Foo {\n  #privateField = 'foo';\n  #privateMember() {}\n}\nfunction foo(arg: Foo) {}\n      "},
		{Code: "\nclass HasText {\n  readonly #text: string;\n}\n\nexport function onDone(task: HasText): void {}\n      "},
		{Code: "\ntype MyType = {\n  readonly prop: string;\n  method(): string;\n};\nfunction foo(arg: MyType) {}\n      ", Options: map[string]any{"treatMethodsAsReadonly": true}},
		{Code: "\nclass Foo {\n  method() {}\n}\nfunction foo(arg: Foo) {}\n      ", Options: map[string]any{"treatMethodsAsReadonly": true}},
		{Code: "\ninterface Foo {\n  method(): void;\n}\nfunction foo(arg: Foo) {}\n      ", Options: map[string]any{"treatMethodsAsReadonly": true}},
		{Code: "\nfunction foo(arg: ReadonlySet<string>) {}\nfunction bar(arg: ReadonlyMap<string, string>) {}\n      ", Options: map[string]any{"treatMethodsAsReadonly": true}},
		{Code: "\nclass Foo {\n  constructor(\n    private arg1: readonly string[],\n    public arg2: readonly string[],\n    protected arg3: readonly string[],\n    readonly arg4: readonly string[],\n  ) {}\n}\n      ", Options: map[string]any{"checkParameterProperties": true}},
		{Code: "\nclass Foo {\n  constructor(\n    private arg1: string[],\n    public arg2: string[],\n    protected arg3: string[],\n    readonly arg4: string[],\n  ) {}\n}\n      ", Options: map[string]any{"checkParameterProperties": false}},
		{Code: "\ninterface Foo {\n  (arg: readonly string[]): void;\n}\n    "},
		{Code: "\ninterface Foo {\n  new (arg: readonly string[]): void;\n}\n    "},
		{Code: "class Foo { foo(arg: readonly string[]): void; };"},
		{Code: "function foo(arg: readonly string[]);"},
		{Code: "type Foo = (arg: readonly string[]) => void;"},
		{Code: "\ninterface Foo {\n  foo(arg: readonly string[]): void;\n}\n    "},
		{Code: "\ninterface Foo {\n  readonly prop: Foo;\n}\nfunction foo(arg: Foo) {}\n    "},
		{Code: "\ntype MyType = string | readonly MyType[];\n\nfunction foo<A extends MyType[]>(a: A): MyType[] {\n  return [];\n}\n    "},
		{Code: "\ninterface Foo {\n  readonly prop: Bar;\n}\ninterface Bar {\n  readonly prop: Foo;\n}\nfunction foo(arg: Foo) {}\n    "},
		{Code: "\ninterface Foo {\n  prop: Readonly<Bar>;\n}\ninterface Bar {\n  prop: Readonly<Foo>;\n}\nfunction foo(arg: Readonly<Foo>) {}\n    "},
		{Code: "\nconst sym = Symbol('sym');\n\ninterface WithSymbol {\n  [sym]: number;\n}\n\nconst willNotCrash = (foo: Readonly<WithSymbol>) => {};\n    "},
		{Code: "\ntype TaggedBigInt = bigint & {\n  readonly __tag: unique symbol;\n};\nfunction custom1(arg: TaggedBigInt) {}\n    "},
		{Code: "\ntype TaggedNumber = number & {\n  readonly __tag: unique symbol;\n};\nfunction custom1(arg: TaggedNumber) {}\n    "},
		{Code: "\ntype TaggedString = string & {\n  readonly __tag: unique symbol;\n};\nfunction custom1(arg: TaggedString) {}\n    "},
		{Code: "\ntype TaggedString = string & {\n  readonly __tagA: unique symbol;\n  readonly __tagB: unique symbol;\n};\nfunction custom1(arg: TaggedString) {}\n    "},
		{Code: "\ntype TaggedString = string & {\n  readonly __tag: unique symbol;\n};\n\ntype OtherSpecialString = string & {\n  readonly ' __other_tag': unique symbol;\n};\n\nfunction custom1(arg: TaggedString | OtherSpecialString) {}\n    "},
		{Code: "\ntype TaggedTemplateLiteral = `${string}-${string}` & {\n  readonly __tag: unique symbol;\n};\nfunction custom1(arg: TaggedTemplateLiteral) {}\n    "},
		{Code: "\ntype TaggedNumber = 1 & {\n  readonly __tag: unique symbol;\n};\n\nfunction custom1(arg: TaggedNumber) {}\n    "},
		{Code: "\ntype TaggedNumber = (1 | 2) & {\n  readonly __tag: unique symbol;\n};\n\nfunction custom1(arg: TaggedNumber) {}\n    "},
		{Code: "\ntype TaggedString = ('a' | 'b') & {\n  readonly __tag: unique symbol;\n};\n\nfunction custom1(arg: TaggedString) {}\n    "},
		{Code: "\ntype Strings = 'one' | 'two' | 'three';\n\ntype TaggedString = Strings & {\n  readonly __tag: unique symbol;\n};\n\nfunction custom1(arg: TaggedString) {}\n    "},
		{Code: "\ntype Strings = 'one' | 'two' | 'three';\n\ntype TaggedString = Strings & {\n  __tag: unique symbol;\n};\n\nfunction custom1(arg: TaggedString) {}\n    "},
		{Code: "\ntype TaggedString = string & {\n  __tag: unique symbol;\n} & {\n  __tag: unique symbol;\n};\nfunction custom1(arg: TaggedString) {}\n    "},
		{Code: "\ntype TaggedString = string & {\n  __tagA: unique symbol;\n} & {\n  __tagB: unique symbol;\n};\nfunction custom1(arg: TaggedString) {}\n    "},
		{Code: "\ntype TaggedString = string &\n  ({ __tag: unique symbol } | { __tag: unique symbol });\nfunction custom1(arg: TaggedString) {}\n    "},
		{Code: "\ntype TaggedFunction = (() => void) & {\n  readonly __tag: unique symbol;\n};\nfunction custom1(arg: TaggedFunction) {}\n    "},
		{Code: "\ntype Callback<T> = (options: T) => void;\n\ndeclare const acceptsCallback: <T>(callback: Callback<T>) => void;\n\ninterface CallbackOptions {\n  prop: string;\n}\n\nacceptsCallback<CallbackOptions>(options => {});\n      ", Options: map[string]any{"ignoreInferredTypes": true}},
		{Code: "\ninterface Obj {\n  readonly [K: string]: Obj;\n}\n\nfunction foo(event: Obj): void {}\n      ", Options: map[string]any{"checkParameterProperties": true, "ignoreInferredTypes": false, "allow": []any{}, "treatMethodsAsReadonly": false}},
		{Code: "\ninterface Obj1 {\n  readonly [K: string]: Obj2;\n}\n\ninterface Obj2 {\n  readonly [K: string]: Obj1;\n}\n\nfunction foo(event: Obj1): void {}\n      ", Options: map[string]any{"checkParameterProperties": true, "ignoreInferredTypes": false, "allow": []any{}, "treatMethodsAsReadonly": false}},
		{Code: "\ninterface Foo {\n  readonly prop: RegExp;\n}\n\nfunction foo(arg: Foo) {}\n      ", Options: map[string]any{"allow": []any{map[string]any{"from": "lib", "name": "RegExp"}}}},
		{Code: "\ninterface Foo {\n  prop: RegExp;\n}\n\nfunction foo(arg: Readonly<Foo>) {}\n      ", Options: map[string]any{"allow": []any{map[string]any{"from": "lib", "name": "RegExp"}}}},
		{Code: "\ninterface Foo {\n  prop: string;\n}\n\nfunction foo(arg: Foo) {}\n      ", Options: map[string]any{"allow": []any{map[string]any{"from": "file", "name": "Foo"}}}},
		{Code: "\ninterface Bar {\n  prop: string;\n}\ninterface Foo {\n  readonly prop: Bar;\n}\n\nfunction foo(arg: Foo) {}\n      ", Options: map[string]any{"allow": []any{map[string]any{"from": "file", "name": "Foo"}}}},
		{Code: "\ninterface Bar {\n  prop: string;\n}\ninterface Foo {\n  readonly prop: Bar;\n}\n\nfunction foo(arg: Foo) {}\n      ", Options: map[string]any{"allow": []any{map[string]any{"from": "file", "name": "Bar"}}}},
		{Code: "\ninterface ViewStyle {\n  field1: number;\n}\ntype Falsy = undefined | null | false | '';\n\ninterface RecursiveArray<T> extends Array<\n  T | ReadonlyArray<T> | RecursiveArray<T>\n> {}\n\ntype RegisteredStyle<T> = number & { __registeredStyleBrand: T };\n\ntype StyleProp<T> =\n  | T\n  | RegisteredStyle<T>\n  | RecursiveArray<T | RegisteredStyle<T> | Falsy>\n  | Falsy;\n\nfunction process(arg1: ViewStyle, arg2: StyleProp<ViewStyle>): void {}\n      ", Options: map[string]any{"allow": []any{map[string]any{"from": "file", "name": []any{"StyleProp", "ViewStyle"}}}}},
		{Code: "\ntype MyArray<T> = T | T[] | null;\ninterface Item {\n  value: string;\n}\nfunction process(items: MyArray<Item>): void {}\n      ", Options: map[string]any{"allow": []any{map[string]any{"from": "file", "name": []any{"MyArray", "Item"}}}}},
		{Code: "\ndeclare function foo<T>(callback: (arg: T) => void): void;\nfoo<readonly string[]>(arg => {});\n      "},
		{Code: "\ntype MyReadonlyType = Readonly<{\n  prop: string;\n}>;\n\nfunction foo(arg: MyReadonlyType) {}\n      ", Options: map[string]any{"allow": []any{"OtherType"}}},
	}, []rule_tester.InvalidTestCase{
		{Code: "function foo(arg: string[]) {}", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldBeReadonly", Message: "Parameter should be a read only type.", Line: 1, Column: 14, EndLine: 1, EndColumn: 27}}},
		{Code: "function foo(arg: Array<string>) {}", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldBeReadonly", Message: "Parameter should be a read only type.", Line: 1, Column: 14, EndLine: 1, EndColumn: 32}}},
		{Code: "function foo(arg: [string]) {}", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldBeReadonly", Message: "Parameter should be a read only type.", Line: 1, Column: 14, EndLine: 1, EndColumn: 27}}},
		{Code: "function foo(arg: readonly string[][]) {}", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldBeReadonly", Message: "Parameter should be a read only type.", Line: 1, Column: 14, EndLine: 1, EndColumn: 38}}},
		{Code: "function foo(arg: Readonly<string[][]>) {}", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldBeReadonly", Message: "Parameter should be a read only type.", Line: 1, Column: 14, EndLine: 1, EndColumn: 39}}},
		{Code: "function foo(arg: ReadonlyArray<Array<string>>) {}", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldBeReadonly", Message: "Parameter should be a read only type.", Line: 1, Column: 14, EndLine: 1, EndColumn: 47}}},
		{Code: "function foo(arg: { foo: '' }) {}", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldBeReadonly", Message: "Parameter should be a read only type.", Line: 1, Column: 14, EndLine: 1, EndColumn: 30}}},
		{Code: "function foo(arg: { foo: readonly string[] }) {}", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldBeReadonly", Message: "Parameter should be a read only type.", Line: 1, Column: 14, EndLine: 1, EndColumn: 45}}},
		{Code: "function foo(arg: { foo(): void }) {}", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldBeReadonly", Message: "Parameter should be a read only type.", Line: 1, Column: 14, EndLine: 1, EndColumn: 34}}},
		{Code: "\nfunction foo(arg: {\n  readonly foo: {\n    bar: string;\n  };\n}) {}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldBeReadonly", Message: "Parameter should be a read only type.", Line: 2, Column: 14, EndLine: 6, EndColumn: 2}}},
		{Code: "\nfunction foo(arg: { [key: string]: string }) {}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldBeReadonly", Message: "Parameter should be a read only type.", Line: 2, Column: 14, EndLine: 2, EndColumn: 44}}},
		{Code: "\nfunction foo(arg: { [key: number]: string }) {}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldBeReadonly", Message: "Parameter should be a read only type.", Line: 2, Column: 14, EndLine: 2, EndColumn: 44}}},
		{Code: "\ninterface Test {\n  (): void;\n  property: boolean;\n}\nfunction foo(arg: Test) {}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldBeReadonly", Message: "Parameter should be a read only type.", Line: 6, Column: 14, EndLine: 6, EndColumn: 23}}},
		{Code: "\ntype Test = (() => void) & {\n  property: boolean;\n};\nfunction foo(arg: Test) {}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldBeReadonly", Message: "Parameter should be a read only type.", Line: 5, Column: 14, EndLine: 5, EndColumn: 23}}},
		{Code: "\ninterface Test extends Array<string> {\n  readonly property: boolean;\n}\nfunction foo(arg: Test) {}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldBeReadonly", Message: "Parameter should be a read only type.", Line: 5, Column: 14, EndLine: 5, EndColumn: 23}}},
		{Code: "\ninterface Test extends Array<string> {\n  property: boolean;\n}\nfunction foo(arg: Test) {}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldBeReadonly", Message: "Parameter should be a read only type.", Line: 5, Column: 14, EndLine: 5, EndColumn: 23}}},
		{Code: "\nclass Foo {\n  constructor(\n    private arg1: string[],\n    public arg2: string[],\n    protected arg3: string[],\n    readonly arg4: string[],\n  ) {}\n}\n      ", Options: map[string]any{"checkParameterProperties": true}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldBeReadonly", Message: "Parameter should be a read only type.", Line: 4, Column: 13, EndLine: 4, EndColumn: 27}, {MessageId: "shouldBeReadonly", Message: "Parameter should be a read only type.", Line: 5, Column: 12, EndLine: 5, EndColumn: 26}, {MessageId: "shouldBeReadonly", Message: "Parameter should be a read only type.", Line: 6, Column: 15, EndLine: 6, EndColumn: 29}, {MessageId: "shouldBeReadonly", Message: "Parameter should be a read only type.", Line: 7, Column: 14, EndLine: 7, EndColumn: 28}}},
		{Code: "\nclass Foo {\n  constructor(\n    private arg1: readonly string[],\n    public arg2: readonly string[],\n    protected arg3: readonly string[],\n    readonly arg4: readonly string[],\n    arg5: string[],\n  ) {}\n}\n      ", Options: map[string]any{"checkParameterProperties": false}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldBeReadonly", Message: "Parameter should be a read only type.", Line: 8, Column: 5, EndLine: 8, EndColumn: 19}}},
		{Code: "\ninterface Foo {\n  (arg: string[]): void;\n}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldBeReadonly", Message: "Parameter should be a read only type.", Line: 3, Column: 4, EndLine: 3, EndColumn: 17}}},
		{Code: "\ninterface Foo {\n  new (arg: string[]): void;\n}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldBeReadonly", Message: "Parameter should be a read only type.", Line: 3, Column: 8, EndLine: 3, EndColumn: 21}}},
		{Code: "class Foo { foo(arg: string[]): void; };", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldBeReadonly", Message: "Parameter should be a read only type.", Line: 1, Column: 17, EndLine: 1, EndColumn: 30}}},
		{Code: "function foo(arg: string[]);", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldBeReadonly", Message: "Parameter should be a read only type.", Line: 1, Column: 14, EndLine: 1, EndColumn: 27}}},
		{Code: "type Foo = (arg: string[]) => void;", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldBeReadonly", Message: "Parameter should be a read only type.", Line: 1, Column: 13, EndLine: 1, EndColumn: 26}}},
		{Code: "\ninterface Foo {\n  foo(arg: string[]): void;\n}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldBeReadonly", Message: "Parameter should be a read only type.", Line: 3, Column: 7, EndLine: 3, EndColumn: 20}}},
		{Code: "\ninterface Foo {\n  prop: Foo;\n}\nfunction foo(arg: Foo) {}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldBeReadonly", Message: "Parameter should be a read only type.", Line: 5, Column: 14, EndLine: 5, EndColumn: 22}}},
		{Code: "\ninterface Foo {\n  prop: Foo;\n}\nfunction foo(arg: Readonly<Foo>) {}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldBeReadonly", Message: "Parameter should be a read only type.", Line: 5, Column: 14, EndLine: 5, EndColumn: 32}}},
		{Code: "\ninterface Foo {\n  prop: Bar;\n}\ninterface Bar {\n  readonly prop: Foo;\n}\nfunction foo(arg: Foo) {}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldBeReadonly", Message: "Parameter should be a read only type.", Line: 8, Column: 14, EndLine: 8, EndColumn: 22}}},
		{Code: "\ninterface Foo {\n  prop: Bar;\n}\ninterface Bar {\n  readonly prop: Foo;\n}\nfunction foo(arg: Readonly<Foo>) {}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldBeReadonly", Message: "Parameter should be a read only type.", Line: 8, Column: 14, EndLine: 8, EndColumn: 32}}},
		{Code: "\ninterface Foo {\n  prop: Readonly<Bar>;\n}\ninterface Bar {\n  prop: Readonly<Foo>;\n}\nfunction foo(arg: Foo) {}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldBeReadonly", Message: "Parameter should be a read only type.", Line: 8, Column: 14, EndLine: 8, EndColumn: 22}}},
		{Code: "\nclass ClassExample {}\ntype Test = typeof ClassExample & {\n  readonly property: boolean;\n};\nfunction foo(arg: Test) {}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldBeReadonly", Message: "Parameter should be a read only type.", Line: 6, Column: 14, EndLine: 6, EndColumn: 23}}},
		{Code: "\nconst sym = Symbol('sym');\n\ninterface WithSymbol {\n  [sym]: number;\n}\n\nconst willNot = (foo: WithSymbol) => {};\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldBeReadonly", Message: "Parameter should be a read only type.", Line: 8, Column: 18, EndLine: 8, EndColumn: 33}}},
		{Code: "\ntype Callback<T> = (options: T) => void;\n\ndeclare const acceptsCallback: <T>(callback: Callback<T>) => void;\n\ninterface CallbackOptions {\n  prop: string;\n}\n\nacceptsCallback<CallbackOptions>((options: CallbackOptions) => {});\n      ", Options: map[string]any{"ignoreInferredTypes": true}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldBeReadonly", Message: "Parameter should be a read only type.", Line: 10, Column: 35, EndLine: 10, EndColumn: 59}}},
		{Code: "\ntype MyType = {\n  readonly prop: string;\n  method(): string;\n};\nfunction foo(arg: MyType) {}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldBeReadonly", Message: "Parameter should be a read only type.", Line: 6, Column: 14, EndLine: 6, EndColumn: 25}}},
		{Code: "\ntype MyType<T> = {\n  [K in keyof T]: 'cat' | 'dog' | T[K];\n};\n\nfunction method<A extends any[] = string[]>(value: MyType<A>) {\n  return value;\n}\n\nmethod(['cat', 'dog']);\nmethod<'mouse'[]>(['cat', 'mouse']);\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldBeReadonly", Message: "Parameter should be a read only type.", Line: 6, Column: 45, EndLine: 6, EndColumn: 61}}},
		{Code: "\ndeclare const fooFactory: <T>(x: readonly T[]) => (f: (x: T) => void) => void;\nfooFactory([{ abc: 42 }])(x => {});\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldBeReadonly", Message: "Parameter should be a read only type.", Line: 3, Column: 27, EndLine: 3, EndColumn: 28}}},
		{Code: "\nfunction foo(arg: RegExp) {}\n      ", Options: map[string]any{"allow": []any{map[string]any{"from": "file", "name": "Foo"}}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldBeReadonly", Message: "Parameter should be a read only type.", Line: 2, Column: 14, EndLine: 2, EndColumn: 25}}},
		{Code: "\ninterface Foo {\n  readonly prop: RegExp;\n}\n\nfunction foo(arg: Foo) {}\n      ", Options: map[string]any{"allow": []any{map[string]any{"from": "file", "name": "Bar"}}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldBeReadonly", Message: "Parameter should be a read only type.", Line: 6, Column: 14, EndLine: 6, EndColumn: 22}}},
		{Code: "\ninterface Foo {\n  readonly prop: RegExp;\n}\n\nfunction foo(arg: Foo) {}\n      ", Options: map[string]any{"allow": []any{map[string]any{"from": "lib", "name": "Foo"}}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldBeReadonly", Message: "Parameter should be a read only type.", Line: 6, Column: 14, EndLine: 6, EndColumn: 22}}},
		{Code: "\ninterface Foo {\n  readonly prop: RegExp;\n}\n\nfunction foo(arg: Foo) {}\n      ", Options: map[string]any{"allow": []any{map[string]any{"from": "package", "name": "Foo", "package": "foo-lib"}}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldBeReadonly", Message: "Parameter should be a read only type.", Line: 6, Column: 14, EndLine: 6, EndColumn: 22}}},
		{Code: "\nfunction foo(arg: RegExp) {}\n      ", Options: map[string]any{"allow": []any{map[string]any{"from": "file", "name": "RegExp", "path": "../.."}}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldBeReadonly", Message: "Parameter should be a read only type.", Line: 2, Column: 14, EndLine: 2, EndColumn: 25}}},
		{Code: "\nfunction foo(arg: RegExp) {}\n      ", Options: map[string]any{"allow": []any{map[string]any{"from": "package", "name": "RegExp", "package": "regexp-lib"}}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldBeReadonly", Message: "Parameter should be a read only type.", Line: 2, Column: 14, EndLine: 2, EndColumn: 25}}},
		{Code: "\ndeclare function foo<T>(callback: (arg: T) => void): void;\nfoo<string[]>(arg => {});\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldBeReadonly", Message: "Parameter should be a read only type.", Line: 3, Column: 15, EndLine: 3, EndColumn: 18}}},
	})
}
