// Command generate emits the private IPC bindings owned by Go.
// cspell:words usize
package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"unsafe"

	"github.com/web-infra-dev/rslint/internal/ipc"
)

const generatedHeader = "// Code generated by internal/ipc/internal/generate; DO NOT EDIT.\n"

type output struct {
	path string
	data []byte
}

func main() {
	root := flag.String("root", ".", "repository root")
	check := flag.Bool("check", false, "check generated files without writing them")
	flag.Parse()
	if err := run(*root, *check); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(root string, check bool) error {
	outputs, err := generate()
	if err != nil {
		return err
	}
	for _, output := range outputs {
		path := filepath.Join(root, filepath.FromSlash(output.path))
		if check {
			actual, err := os.ReadFile(path)
			if err != nil {
				return err
			}
			// Git may check out text as CRLF on Windows. The emitted protocol
			// stays deterministic without treating checkout newlines as drift.
			actual = bytes.ReplaceAll(actual, []byte("\r\n"), []byte("\n"))
			if !bytes.Equal(actual, output.data) {
				return fmt.Errorf("%s is stale; run go generate ./internal/ipc", output.path)
			}
		} else if err := os.WriteFile(path, output.data, 0o644); err != nil {
			return err
		}
	}
	return nil
}

func generate() ([]output, error) {
	if ipc.FrameHeaderSize != int(unsafe.Sizeof(uint32(0))) ||
		ipc.MaxFrameSize <= 0 || ipc.MaxFrameSize > math.MaxUint32 ||
		ipc.SourcePublicationStride != int(unsafe.Sizeof(uint32(0))) ||
		ipc.SourceSlotCount <= 0 || ipc.SourceSlotSize <= 0 ||
		ipc.SourceHeaderSize < ipc.SourceSlotCount*ipc.SourcePublicationStride ||
		ipc.SourceHeaderSize%ipc.SourcePublicationStride != 0 ||
		ipc.SourceSlotSize%ipc.SourcePublicationStride != 0 ||
		ipc.SourceCapacity > math.MaxUint32 ||
		ipc.SourceInheritedFD < 3 {
		return nil, errors.New("invalid IPC protocol layout")
	}

	var rust, ts bytes.Buffer
	rust.WriteString(generatedHeader + "\nuse napi_derive::napi;\n\n")
	fmt.Fprintf(&rust, "pub const PROTOCOL_VERSION: u32 = %d;\n", ipc.SourceVersion)
	fmt.Fprintf(&rust, "pub const SLOT_COUNT: usize = %d;\n", ipc.SourceSlotCount)
	fmt.Fprintf(&rust, "pub const SLOT_SIZE: usize = %d;\n", ipc.SourceSlotSize)
	fmt.Fprintf(&rust, "pub const HEADER_SIZE: usize = %d;\n", ipc.SourceHeaderSize)
	fmt.Fprintf(&rust, "pub const CAPACITY: usize = %d;\n", ipc.SourceCapacity)
	fmt.Fprintf(&rust, "pub const PUBLICATION_STRIDE: usize = %d;\n", ipc.SourcePublicationStride)
	ts.WriteString(generatedHeader + "\n")
	fmt.Fprintf(&ts, "export const FRAME_HEADER_SIZE = %d;\n", ipc.FrameHeaderSize)
	fmt.Fprintf(&ts, "export const MAX_FRAME_SIZE = %d;\n", ipc.MaxFrameSize)
	fmt.Fprintf(&ts, "export const KIND_RESPONSE = '%s';\n", ipc.KindResponse)
	fmt.Fprintf(&ts, "export const KIND_ERROR = '%s';\n", ipc.KindError)
	fmt.Fprintf(&ts, "export const KIND_HANDSHAKE = '%s';\n", ipc.KindHandshake)
	fmt.Fprintf(&ts, "export const KIND_EXIT = '%s';\n", ipc.KindExit)
	fmt.Fprintf(&ts, "export const PROTOCOL_VERSION = %d;\n", ipc.SourceVersion)
	fmt.Fprintf(&ts, "export const SLOT_COUNT = %d;\n", ipc.SourceSlotCount)
	fmt.Fprintf(&ts, "export const SLOT_SIZE = %d;\n", ipc.SourceSlotSize)
	fmt.Fprintf(&ts, "export const INHERITED_FD = %d;\n", ipc.SourceInheritedFD)
	fmt.Fprintf(&ts, "export const MAX_GENERATION = %d;\n", ipc.SourceMaxGeneration)

	for _, dto := range protocolDTOs {
		if err := writeDTO(&rust, &ts, dto.name, dto.typeOf, dto.native); err != nil {
			return nil, err
		}
	}
	return []output{
		{"crates/rslint-native/src/source_transport/protocol_generated.rs", rust.Bytes()},
		{"packages/rslint/src/ipc/protocol.generated.ts", ts.Bytes()},
	}, nil
}

// Only these protocol DTOs are supported. This is not a general Go schema
// generator: adding a new wire type requires an explicit entry here.
var protocolDTOs = []struct {
	name   string
	typeOf reflect.Type
	native bool
}{
	{"SourceMapping", reflect.TypeFor[ipc.SourceDescriptor](), true},
	{"SourceBatch", reflect.TypeFor[ipc.SourceBatch](), false},
	{"SourceRange", reflect.TypeFor[ipc.SourceRange](), false},
	{"TextAttachment", reflect.TypeFor[ipc.TextAttachment](), false},
	{"TransportMetadata", reflect.TypeFor[ipc.TransportMetadata](), false},
	{"WireMessage", reflect.TypeFor[ipc.Message](), false},
	{"ErrorResponseData", reflect.TypeFor[ipc.ErrorResponseData](), false},
}

func tsType(typeOf reflect.Type) (string, error) {
	switch typeOf {
	case reflect.TypeFor[int](), reflect.TypeFor[int32](), reflect.TypeFor[uint32]():
		return "number", nil
	case reflect.TypeFor[string](), reflect.TypeFor[ipc.MessageKind]():
		return "string", nil
	case reflect.TypeFor[json.RawMessage]():
		return "unknown", nil
	case reflect.TypeFor[[]ipc.TextAttachment]():
		return "TextAttachment[]", nil
	}
	for _, dto := range protocolDTOs {
		if typeOf == dto.typeOf {
			return dto.name, nil
		}
	}
	return "", fmt.Errorf("unsupported protocol type %s", typeOf)
}

func writeDTO(rust, ts *bytes.Buffer, name string, typeOf reflect.Type, native bool) error {
	if native {
		fmt.Fprintf(rust, "\n#[napi(object)]\npub struct %s {\n", name)
	}
	fmt.Fprintf(ts, "\nexport interface %s {\n", name)
	for i := range typeOf.NumField() {
		field := typeOf.Field(i)
		jsonName, option, _ := strings.Cut(field.Tag.Get("json"), ",")
		if field.Anonymous || !field.IsExported() || jsonName == "" || jsonName == "-" ||
			(option != "" && option != "omitempty") {
			return fmt.Errorf("unsupported protocol field %s.%s", typeOf.Name(), field.Name)
		}
		fieldType := field.Type
		nullable := fieldType.Kind() == reflect.Pointer
		if nullable {
			fieldType = fieldType.Elem()
		}
		tsFieldType, err := tsType(fieldType)
		if err != nil {
			return fmt.Errorf("%s.%s: %w", typeOf.Name(), field.Name, err)
		}
		optional := ""
		if option == "omitempty" {
			optional = "?"
		} else if nullable {
			tsFieldType += " | null"
		}
		if native {
			var rustType string
			switch fieldType {
			case reflect.TypeFor[int32]():
				rustType = "i32"
			case reflect.TypeFor[uint32]():
				rustType = "u32"
			case reflect.TypeFor[string]():
				rustType = "String"
			default:
				return fmt.Errorf("unsupported native protocol type %s.%s: %s", typeOf.Name(), field.Name, fieldType)
			}
			if nullable || optional != "" {
				rustType = "Option<" + rustType + ">"
			}
			// JSON uses lower camel case; Rust requires its snake-case spelling.
			var rustName strings.Builder
			for _, letter := range jsonName {
				if letter >= 'A' && letter <= 'Z' {
					rustName.WriteByte('_')
					letter += 'a' - 'A'
				}
				rustName.WriteRune(letter)
			}
			fmt.Fprintf(rust, "    pub %s: %s,\n", rustName.String(), rustType)
		}
		fmt.Fprintf(ts, "  %s%s: %s;\n", jsonName, optional, tsFieldType)
	}
	if native {
		rust.WriteString("}\n")
	}
	ts.WriteString("}\n")
	return nil
}
