/**
 * ECMAScript language globals recognized by the ESLint version rslint targets,
 * paired with the first edition that provides each name.
 *
 * Keep this table aligned with `internal/rule/globals.go` when upgrading
 * ESLint. `builtin-globals.test.ts` checks the two runtime implementations for
 * drift. The plugin worker uses this instead of the unversioned
 * `globals.builtin` snapshot.
 */
export const LATEST_ECMASCRIPT_VERSION = 2026;
export const ECMASCRIPT_GLOBALS: readonly (readonly [string, number])[] = [
  ['Array', 3],
  ['Boolean', 3],
  ['constructor', 3],
  ['Date', 3],
  ['decodeURI', 3],
  ['decodeURIComponent', 3],
  ['encodeURI', 3],
  ['encodeURIComponent', 3],
  ['Error', 3],
  ['escape', 3],
  ['eval', 3],
  ['EvalError', 3],
  ['Function', 3],
  ['hasOwnProperty', 3],
  ['Infinity', 3],
  ['isFinite', 3],
  ['isNaN', 3],
  ['isPrototypeOf', 3],
  ['Math', 3],
  ['NaN', 3],
  ['Number', 3],
  ['Object', 3],
  ['parseFloat', 3],
  ['parseInt', 3],
  ['propertyIsEnumerable', 3],
  ['RangeError', 3],
  ['ReferenceError', 3],
  ['RegExp', 3],
  ['String', 3],
  ['SyntaxError', 3],
  ['toLocaleString', 3],
  ['toString', 3],
  ['TypeError', 3],
  ['undefined', 3],
  ['unescape', 3],
  ['URIError', 3],
  ['valueOf', 3],
  ['JSON', 5],
  ['ArrayBuffer', 2015],
  ['DataView', 2015],
  ['Float32Array', 2015],
  ['Float64Array', 2015],
  ['Int16Array', 2015],
  ['Int32Array', 2015],
  ['Int8Array', 2015],
  ['Intl', 2015],
  ['Map', 2015],
  ['Promise', 2015],
  ['Proxy', 2015],
  ['Reflect', 2015],
  ['Set', 2015],
  ['Symbol', 2015],
  ['Uint16Array', 2015],
  ['Uint32Array', 2015],
  ['Uint8Array', 2015],
  ['Uint8ClampedArray', 2015],
  ['WeakMap', 2015],
  ['WeakSet', 2015],
  ['Atomics', 2017],
  ['SharedArrayBuffer', 2017],
  ['BigInt', 2020],
  ['BigInt64Array', 2020],
  ['BigUint64Array', 2020],
  ['globalThis', 2020],
  ['AggregateError', 2021],
  ['FinalizationRegistry', 2021],
  ['WeakRef', 2021],
  ['Float16Array', 2025],
  ['Iterator', 2025],
  ['AsyncDisposableStack', 2026],
  ['DisposableStack', 2026],
  ['SuppressedError', 2026],
  ['Temporal', 2026],
] as const;
