/**
 * ECMAScript built-in global names — vendored from the `globals` package
 * (17.6.0) `.builtin` set.
 *
 * `scope-factory` seeds these as readonly globals so rules like `no-undef`
 * don't false-positive on `Array` / `Object` / `Promise` / etc. We vendor the
 * list rather than `import 'globals'`: scope-factory needs only this one set
 * (62 names, ~1KB), but the package ships all 58 environments (~84KB of JSON) —
 * bundling it into the worker wasted 98.7% of that. `builtin-globals.test.ts`
 * is a drift guard that fails if this list diverges from `globals.builtin`.
 */
export const BUILTIN_GLOBAL_NAMES: readonly string[] = [
  'AggregateError',
  'Array',
  'ArrayBuffer',
  'Atomics',
  'BigInt',
  'BigInt64Array',
  'BigUint64Array',
  'Boolean',
  'DataView',
  'Date',
  'decodeURI',
  'decodeURIComponent',
  'encodeURI',
  'encodeURIComponent',
  'Error',
  'escape',
  'eval',
  'EvalError',
  'FinalizationRegistry',
  'Float16Array',
  'Float32Array',
  'Float64Array',
  'Function',
  'globalThis',
  'Infinity',
  'Int16Array',
  'Int32Array',
  'Int8Array',
  'Intl',
  'isFinite',
  'isNaN',
  'Iterator',
  'JSON',
  'Map',
  'Math',
  'NaN',
  'Number',
  'Object',
  'parseFloat',
  'parseInt',
  'Promise',
  'Proxy',
  'RangeError',
  'ReferenceError',
  'Reflect',
  'RegExp',
  'Set',
  'SharedArrayBuffer',
  'String',
  'Symbol',
  'SyntaxError',
  'TypeError',
  'Uint16Array',
  'Uint32Array',
  'Uint8Array',
  'Uint8ClampedArray',
  'undefined',
  'unescape',
  'URIError',
  'WeakMap',
  'WeakRef',
  'WeakSet',
];
