import path from 'node:path';

import { lint } from '@rslint/core/internal';

import { RuleTester, type InvalidTestCase } from '../rule-tester';

const message =
  '`new Array()` is unclear in intent; use an array literal or `Array.from()`.';

function invalid(
  code: string,
  filename: string,
  line: number,
  column: number,
  endLine: number,
  endColumn: number,
  output: string | null,
  suggestion: string | null,
): InvalidTestCase {
  return {
    code,
    filename,
    output,
    errors: [
      {
        messageId: 'error',
        message,
        line,
        column,
        endLine,
        endColumn,
        suggestions:
          suggestion === null
            ? []
            : [
                {
                  messageId: 'spread',
                  desc: 'Spread the argument.',
                  output: suggestion,
                },
              ],
      },
    ],
  };
}

// Complete semantic mirror of the v77.0.0 tests and documentation examples.
// https://github.com/sindresorhus/eslint-plugin-unicorn/blob/v77.0.0/test/no-new-array.js
const cases = {
  valid: [
    // Snapshots
    { code: 'const array = Array.from({length: 1})', filename: 'file.js' },
    { code: 'const array = new Array()', filename: 'file.js' },
    { code: 'const array = new Array', filename: 'file.js' },
    { code: 'const array = new Array(1, 2)', filename: 'file.js' },
    { code: 'const array = Array(1, 2)', filename: 'file.js' },
    { code: 'const array = Array(1)', filename: 'file.js' },
    // Documentation
    { code: 'const array = [onlyElement];', filename: 'file.js' },
    {
      code: "const items = ['foo', 'bar'];\nconst array = [...items];",
      filename: 'file.js',
    },
  ],
  invalid: [
    // Snapshots
    invalid(
      "const modes = new Set(['foo']);\nmodes.clear();\nnew Array(modes.size ? 1 : 'x');",
      'file.js',
      3,
      1,
      3,
      32,
      null,
      null,
    ),
    invalid(
      'const modes = new Set(["foo"]); modes.clear(); new Array((modes.size && 1) || value);',
      'file.js',
      1,
      48,
      1,
      85,
      null,
      null,
    ),
    invalid(
      'const object = {value: true}; Object.defineProperty(object, "value", {get() { return false; }}); new Array(object.value ? 1 : value);',
      'file.js',
      1,
      98,
      1,
      133,
      null,
      null,
    ),
    invalid(
      'const modes = new Set(["foo"]); modes.clear(); new Array((modes.size ? "x" : 1) as number);',
      'file.ts',
      1,
      48,
      1,
      91,
      null,
      null,
    ),
    invalid('const array = new Array(1)', 'file.js', 1, 15, 1, 27, null, null),
    invalid(
      'const zero = 0;\nconst array = new Array(zero);',
      'file.js',
      2,
      15,
      2,
      30,
      null,
      null,
    ),
    invalid(
      'const length = 1;\nconst array = new Array(length);',
      'file.js',
      2,
      15,
      2,
      32,
      null,
      null,
    ),
    invalid(
      'const array = new Array(1.5)',
      'file.js',
      1,
      15,
      1,
      29,
      null,
      null,
    ),
    invalid(
      'const array = new Array(Number("1"))',
      'file.js',
      1,
      15,
      1,
      37,
      null,
      null,
    ),
    invalid(
      'const array = new Array("1")',
      'file.js',
      1,
      15,
      1,
      29,
      'const array = ["1"]',
      null,
    ),
    invalid(
      'const array = new Array(null)',
      'file.js',
      1,
      15,
      1,
      30,
      'const array = [null]',
      null,
    ),
    invalid(
      'const array = new Array(("1"))',
      'file.js',
      1,
      15,
      1,
      31,
      'const array = [("1")]',
      null,
    ),
    invalid(
      'const array = new Array((0, 1))',
      'file.js',
      1,
      15,
      1,
      32,
      null,
      null,
    ),
    invalid(
      'const foo = []\nnew Array("bar").forEach(baz)',
      'file.js',
      2,
      1,
      2,
      17,
      'const foo = []\n;["bar"].forEach(baz)',
      null,
    ),
    invalid('new Array(0xff)', 'file.js', 1, 1, 1, 16, null, null),
    invalid('new Array(Math.PI | foo)', 'file.js', 1, 1, 1, 25, null, null),
    invalid(
      'new Array(Math.min(foo, bar))',
      'file.js',
      1,
      1,
      1,
      30,
      null,
      null,
    ),
    invalid('new Array(Number(foo))', 'file.js', 1, 1, 1, 23, null, null),
    invalid(
      'new Array(Number.MAX_SAFE_INTEGER)',
      'file.js',
      1,
      1,
      1,
      35,
      null,
      null,
    ),
    invalid('new Array(parseInt(foo))', 'file.js', 1, 1, 1, 25, null, null),
    invalid(
      'new Array(Number.parseInt(foo))',
      'file.js',
      1,
      1,
      1,
      32,
      null,
      null,
    ),
    invalid('new Array(+foo)', 'file.js', 1, 1, 1, 16, null, null),
    invalid('new Array(-Math.PI)', 'file.js', 1, 1, 1, 20, null, null),
    invalid('new Array(-"-2")', 'file.js', 1, 1, 1, 17, null, null),
    invalid('new Array(foo.length)', 'file.js', 1, 1, 1, 22, null, null),
    invalid(
      'const array = [1]; new Array(array.length)',
      'file.js',
      1,
      20,
      1,
      43,
      null,
      null,
    ),
    invalid(
      'const text = "foo"; new Array(text.length)',
      'file.js',
      1,
      21,
      1,
      43,
      null,
      null,
    ),
    invalid(
      'const foo = 1; new Array(foo + 2)',
      'file.js',
      1,
      16,
      1,
      34,
      null,
      null,
    ),
    invalid('new Array(foo - 2)', 'file.js', 1, 1, 1, 19, null, null),
    invalid('new Array(foo -= 2)', 'file.js', 1, 1, 1, 20, null, null),
    invalid('new Array(foo ? 1 : 2)', 'file.js', 1, 1, 1, 23, null, null),
    invalid(
      'const truthy = "truthy"; new Array(truthy ? 1 : foo)',
      'file.js',
      1,
      26,
      1,
      53,
      null,
      null,
    ),
    invalid(
      'const falsy = !"truthy"; new Array(falsy ? foo : 1)',
      'file.js',
      1,
      26,
      1,
      52,
      null,
      null,
    ),
    invalid('new Array((1n, 2))', 'file.js', 1, 1, 1, 19, null, null),
    invalid('new Array(Number.NaN)', 'file.js', 1, 1, 1, 22, null, null),
    invalid('new Array(NaN)', 'file.js', 1, 1, 1, 15, null, null),
    invalid('new Array(foo >>> bar)', 'file.js', 1, 1, 1, 23, null, null),
    invalid('new Array(foo >>>= bar)', 'file.js', 1, 1, 1, 24, null, null),
    invalid('new Array(++bar.length)', 'file.js', 1, 1, 1, 24, null, null),
    invalid('new Array(bar.length++)', 'file.js', 1, 1, 1, 24, null, null),
    invalid('new Array(foo = bar.length)', 'file.js', 1, 1, 1, 28, null, null),
    invalid('new Array("0xff")', 'file.js', 1, 1, 1, 18, '["0xff"]', null),
    invalid(
      'new Array(Math.NON_EXISTS_PROPERTY)',
      'file.js',
      1,
      1,
      1,
      36,
      null,
      null,
    ),
    invalid(
      'new Array(Math.NON_EXISTS_METHOD(foo))',
      'file.js',
      1,
      1,
      1,
      39,
      null,
      null,
    ),
    invalid(
      'new Array(Math[min](foo, bar))',
      'file.js',
      1,
      1,
      1,
      31,
      null,
      null,
    ),
    invalid(
      'new Array(Number[MAX_SAFE_INTEGER])',
      'file.js',
      1,
      1,
      1,
      36,
      null,
      null,
    ),
    invalid('new Array(new Number(foo))', 'file.js', 1, 1, 1, 27, null, null),
    invalid(
      'const foo = 1; new Array(foo + "2")',
      'file.js',
      1,
      16,
      1,
      36,
      'const foo = 1; [foo + "2"]',
      null,
    ),
    invalid('new Array(foo - 2n)', 'file.js', 1, 1, 1, 20, null, null),
    invalid('new Array(foo -= 2n)', 'file.js', 1, 1, 1, 21, null, null),
    invalid('new Array(foo instanceof 1)', 'file.js', 1, 1, 1, 28, null, null),
    invalid('new Array(foo || 1)', 'file.js', 1, 1, 1, 20, null, null),
    invalid('new Array(foo ||= 1)', 'file.js', 1, 1, 1, 21, null, null),
    invalid('new Array(foo ? 1n : 2)', 'file.js', 1, 1, 1, 24, null, null),
    invalid('new Array((1, 2n))', 'file.js', 1, 1, 1, 19, '[(1, 2n)]', null),
    invalid('new Array(-foo)', 'file.js', 1, 1, 1, 16, null, null),
    invalid('new Array(~foo)', 'file.js', 1, 1, 1, 16, null, null),
    invalid('new Array(typeof 1)', 'file.js', 1, 1, 1, 20, '[typeof 1]', null),
    invalid(
      'const truthy = "truthy"; new Array(truthy ? foo : 1)',
      'file.js',
      1,
      26,
      1,
      53,
      null,
      null,
    ),
    invalid(
      'const falsy = !"truthy"; new Array(falsy ? 1 : foo)',
      'file.js',
      1,
      26,
      1,
      52,
      null,
      null,
    ),
    invalid('new Array(unknown ? foo : 1)', 'file.js', 1, 1, 1, 29, null, null),
    invalid('new Array(unknown ? 1 : foo)', 'file.js', 1, 1, 1, 29, null, null),
    invalid('new Array(++foo)', 'file.js', 1, 1, 1, 17, null, null),
    invalid(
      'const array = new Array(foo)',
      'file.js',
      1,
      15,
      1,
      29,
      null,
      null,
    ),
    invalid(
      'const array = new Array(length)',
      'file.js',
      1,
      15,
      1,
      32,
      null,
      null,
    ),
    invalid(
      'const foo = []\nnew Array(bar).forEach(baz)',
      'file.js',
      2,
      1,
      2,
      15,
      null,
      null,
    ),
    invalid(
      'const array = new Array(...[foo])',
      'file.js',
      1,
      15,
      1,
      34,
      null,
      'const array = [...[foo]]',
    ),
    invalid(
      'const array = new Array(...foo)',
      'file.js',
      1,
      15,
      1,
      32,
      null,
      'const array = [...foo]',
    ),
    invalid(
      'const array = new Array(...[...foo])',
      'file.js',
      1,
      15,
      1,
      37,
      null,
      'const array = [...[...foo]]',
    ),
    invalid(
      'const array = new Array(...[1])',
      'file.js',
      1,
      15,
      1,
      32,
      null,
      'const array = [...[1]]',
    ),
    invalid(
      'const array = new Array(...["1"])',
      'file.js',
      1,
      15,
      1,
      34,
      null,
      'const array = [...["1"]]',
    ),
    invalid(
      'const array = new Array(...[1, "1"])',
      'file.js',
      1,
      15,
      1,
      37,
      null,
      'const array = [...[1, "1"]]',
    ),
    invalid(
      'const foo = []\nnew Array(...bar).forEach(baz)',
      'file.js',
      2,
      1,
      2,
      18,
      null,
      'const foo = []\n;[...bar].forEach(baz)',
    ),
    // Explicit
    invalid(
      'const object = {}; Object.defineProperty(object, "length", {get() { return "foo"; }}); new Array(object.length);',
      'file.js',
      1,
      88,
      1,
      112,
      null,
      null,
    ),
    invalid(
      'const array = []; new Array(1 + array.length);',
      'file.js',
      1,
      19,
      1,
      46,
      null,
      null,
    ),
    invalid(
      'const alias = condition; var condition = true; new Array(alias ? "x" : 1);',
      'file.js',
      1,
      48,
      1,
      74,
      null,
      null,
    ),
    invalid('new Array(1.5)', 'file.js', 1, 1, 1, 15, null, null),
    invalid('new Array(-1)', 'file.js', 1, 1, 1, 14, null, null),
    invalid('new Array(1 / 2)', 'file.js', 1, 1, 1, 17, null, null),
    invalid(
      'const size = 3; new Array(size / 2);',
      'file.js',
      1,
      17,
      1,
      36,
      null,
      null,
    ),
    invalid(
      'const size = 3; new Array(size * 2);',
      'file.js',
      1,
      17,
      1,
      36,
      null,
      null,
    ),
    invalid('new Array(-0)', 'file.js', 1, 1, 1, 14, null, null),
    invalid('new Array(2.5 * 2)', 'file.js', 1, 1, 1, 19, null, null),
    invalid('new Array(Infinity)', 'file.js', 1, 1, 1, 20, null, null),
    invalid(
      'const array = new Array(0xff);',
      'file.js',
      1,
      15,
      1,
      30,
      null,
      null,
    ),
    invalid(
      'const array = new Array(1e2);',
      'file.js',
      1,
      15,
      1,
      29,
      null,
      null,
    ),
    invalid(
      'const array = new Array(0b1);',
      'file.js',
      1,
      15,
      1,
      29,
      null,
      null,
    ),
    invalid(
      'const array = new Array(1_0);',
      'file.js',
      1,
      15,
      1,
      29,
      null,
      null,
    ),
    invalid('new Array(/* the size */ 3);', 'file.js', 1, 1, 1, 28, null, null),
    invalid('new /* c */ Array(1);', 'file.js', 1, 1, 1, 21, null, null),
    invalid('new Array(1 /* c */);', 'file.js', 1, 1, 1, 21, null, null),
    invalid('new Array(/* c */ "x");', 'file.js', 1, 1, 1, 23, null, null),
    invalid('new /* c */ Array("x");', 'file.js', 1, 1, 1, 23, null, null),
    invalid('new Array(/* c */ ...foo);', 'file.js', 1, 1, 1, 26, null, null),
    // Documentation
    invalid(
      'const length = 10;\nconst array = new Array(length);',
      'file.js',
      2,
      15,
      2,
      32,
      null,
      null,
    ),
    invalid(
      'const array = new Array(3);\narray.filter(() => true).length;\nArray.from({length: 3}).filter(() => true).length;',
      'file.js',
      1,
      15,
      1,
      27,
      null,
      null,
    ),
    invalid(
      'const array = new Array(onlyElement);',
      'file.js',
      1,
      15,
      1,
      37,
      null,
      null,
    ),
    invalid(
      "const items = ['foo', 'bar'];\nconst array = new Array(...items);",
      'file.js',
      2,
      15,
      2,
      34,
      null,
      "const items = ['foo', 'bar'];\nconst array = [...items];",
    ),
  ],
};

new RuleTester().run('no-new-array', null as never, cases);

// The suite wrapper checks messages; verify ranges and applied edits through IPC too.
test('upstream diagnostic ranges, fixes, and suggestions', async () => {
  for (const item of cases.invalid) {
    const filename = path.resolve(
      import.meta.dirname,
      '../src',
      item.filename!,
    );
    const { diagnostics } = await lint({
      config: [
        { plugins: ['unicorn'], rules: { 'unicorn/no-new-array': 'error' } },
      ],
      configDirectory: process.cwd(),
      workingDirectory: process.cwd(),
      fileContents: { [filename]: item.code },
    });
    expect(diagnostics, item.code).toHaveLength(1);
    const diagnostic = diagnostics[0];
    const expected = (
      item.errors as Exclude<InvalidTestCase['errors'], number>
    )[0];
    if (typeof expected === 'string')
      throw new Error('Expected structured diagnostic');
    expect(diagnostic, item.code).toMatchObject({
      ruleName: 'unicorn/no-new-array',
      messageId: 'error',
      message,
      range: {
        start: { line: expected.line, column: expected.column },
        end: { line: expected.endLine, column: expected.endColumn },
      },
    });
    expect(applyEdits(item.code, diagnostic.fixes), item.code).toBe(
      item.output,
    );
    expect(
      (diagnostic.suggestions ?? []).map((suggestion) => ({
        messageId: suggestion.messageId,
        desc: suggestion.message,
        output: applyEdits(item.code, suggestion.fixes),
      })),
      item.code,
    ).toEqual(expected.suggestions);
  }
});

function applyEdits(
  code: string,
  fixes?: { startPos: number; endPos: number; text: string }[],
): string | null {
  if (!fixes?.length) return null;
  for (const fix of [...fixes].sort((a, b) => b.startPos - a.startPos)) {
    code = code.slice(0, fix.startPos) + fix.text + code.slice(fix.endPos);
  }
  return code;
}
