import { RuleTester } from '../rule-tester';

const ruleTester = new RuleTester();

const valid = (code: string, options?: unknown[]) =>
  options === undefined ? { code } : { code, options };
const invalid = (code: string, errors = 1, options?: unknown[]) =>
  options === undefined ? { code, errors } : { code, errors, options };
const checkInfinity = [{ checkInfinity: true }];
const checkNaNFalse = [{ checkNaN: false }];

ruleTester.run('prefer-number-properties', null as never, {
  valid: [
    valid('Number.parseInt("10", 2);'),
    valid('Number.parseFloat("10.5");'),
    valid('Number.isNaN(10);'),
    valid('Number.isFinite(10);'),

    // Shadowed
    valid('const parseInt = function() {};\nparseInt("10", 2);'),
    valid('const parseFloat = function() {};\nparseFloat("10.5");'),
    valid('const isNaN = function() {};\nisNaN(10);'),
    valid('const isFinite = function() {};\nisFinite(10);'),
    valid('const {parseInt} = Number;\nparseInt("10", 2);'),
    valid('const {parseFloat} = Number;\nparseFloat("10.5");'),
    valid('const {isNaN} = Number;\nisNaN(10);'),
    valid('const {isFinite} = Number;\nisFinite(10);'),
    valid(
      'const parseInt = function() {};\nfunction inner() {\n\treturn parseInt("10", 2);\n}',
    ),
    valid(
      'const parseFloat = function() {};\nfunction inner() {\n\treturn parseFloat("10.5");\n}',
    ),
    valid(
      'const isNaN = function() {};\nfunction inner() {\n\treturn isNaN(10);\n}',
    ),
    valid(
      'const isFinite = function() {};\nfunction inner() {\n\treturn isFinite(10);\n}',
    ),

    // Not read
    valid('global.isFinite = Number.isFinite;'),
    valid('global.isFinite ??= 1;'),
    valid('isFinite ||= 1;'),
    valid('[global.isFinite] = [];'),
    valid('[global.isFinite = 1] = [];'),
    valid('[[global.isFinite = 1]] = [];'),
    valid('[isFinite] = [];'),
    valid('[isFinite = 1] = [];'),
    valid('[[isFinite = 1]] = [];'),
    valid('({foo: global.isFinite} = {});'),
    valid('({foo: global.isFinite = 1} = {});'),
    valid('({foo: {bar: global.isFinite = 1}} = {});'),
    valid('({foo: isFinite} = {});'),
    valid('({foo: isFinite = 1} = {});'),
    valid('({foo: {bar: isFinite = 1}} = {});'),
    valid('delete global.isFinite;'),

    valid('const foo = Number.NaN;'),
    valid('const foo = window.Number.NaN;'),
    valid('const foo = bar.NaN;'),
    valid('const foo = nan;'),
    valid('const foo = "NaN";'),
    valid('function foo () {\n\tconst NaN = 2;\n\treturn NaN;\n}'),
    valid('const {NaN} = {};'),
    valid('const {a: NaN} = {};'),
    valid('const {[a]: NaN} = {};'),
    valid('const [NaN] = [];'),
    valid('function NaN() {}'),
    valid('const foo = function NaN() {}'),
    valid('function foo(NaN) {}'),
    valid('foo = function (NaN) {}'),
    valid('foo = (NaN) => {}'),
    valid('function foo({NaN}) {}'),
    valid('function foo({a: NaN}) {}'),
    valid('function foo({[a]: NaN}) {}'),
    valid('function foo([NaN]) {}'),
    valid('class NaN {}'),
    valid('const Foo = class NaN {}'),
    valid('class Foo {NaN(){}}'),
    valid('class Foo {#NaN(){}}'),
    valid('class Foo3 {NaN = 1}'),
    valid('class Foo {#NaN = 1}'),
    valid(
      'NaN: for (const foo of bar) {\n\tif (a) {\n\t\tcontinue NaN;\n\t} else {\n\t\tbreak NaN;\n\t}\n}',
    ),
    valid('import {NaN} from "foo"'),
    valid('import {NaN as NaN} from "foo"'),
    valid('import NaN from "foo"'),
    valid('import * as NaN from "foo"'),
    valid('export {NaN} from "foo"'),
    valid('export {NaN as NaN} from "foo"'),
    valid('export * as NaN from "foo"'),
    valid('const foo = Number.POSITIVE_INFINITY;'),
    valid('const foo = window.Number.POSITIVE_INFINITY;'),
    valid('const foo = bar.POSITIVE_INFINITY;'),
    valid('const foo = Number.Infinity;'),
    valid('const foo = window.Number.Infinity;'),
    valid('const foo = bar.Infinity;'),
    valid('const foo = infinity;'),
    valid('const foo = "Infinity";'),
    valid('const foo = "-Infinity";'),
    valid('function foo () {\n\tconst Infinity = 2;\n\treturn Infinity;\n}'),
    valid('const {Infinity} = {};'),
    valid('function Infinity() {}'),
    valid('class Infinity {}'),
    valid('class Foo { Infinity(){}}'),
    valid('const foo = Infinity;'),
    valid('const foo = -Infinity;'),
    valid('const foo = NaN', checkNaNFalse),
    valid('export enum NumberSymbol {\n\tDecimal,\n\tNaN,\n}'),
    valid('declare var NaN: number;'),
    valid('interface NumberConstructor {\n\treadonly NaN: number;\n}'),
    valid('declare function NaN(s: string, radix?: number): number;'),
    valid('class Foo {NaN = 1}'),
    valid('const foo = ++Infinity;'),
    valid('const foo = --Infinity;'),
    valid('const foo = -(--Infinity);'),
  ],
  invalid: [
    invalid('parseInt("10", 2);'),
    invalid('parseFloat("10.5");'),
    invalid('isNaN(10);'),
    invalid('isFinite(10);'),
    invalid(
      'const a = parseInt("10", 2);\nconst b = parseFloat("10.5");\nconst c = isNaN(10);\nconst d = isFinite(10);',
      4,
    ),
    invalid('const foo = NaN;'),
    invalid('if (Number.isNaN(NaN)) {}'),
    invalid('if (Object.is(foo, NaN)) {}'),
    invalid('const foo = bar[NaN];'),
    invalid('const foo = {NaN};'),
    invalid('const foo = {NaN: NaN};'),
    invalid('const {foo = NaN} = {};'),
    invalid('const foo = NaN.toString();'),
    invalid('class Foo3 {[NaN] = 1}'),
    invalid('const foo = Infinity;', 1, checkInfinity),
    invalid('const foo = -Infinity;', 1, checkInfinity),
    invalid('class Foo {[NaN] = 1}'),
    invalid('const foo = {[NaN]: 1}'),
    invalid('const foo = {[NaN]() {}}'),
    invalid('foo[NaN] = 1;'),
    invalid('class A {[NaN](){}}'),
    invalid('foo = {[NaN]: 1}'),
    invalid('if (Number.isNaN(Infinity)) {}', 1, checkInfinity),
    invalid('if (Object.is(foo, Infinity)) {}', 1, checkInfinity),
    invalid('const foo = bar[Infinity];', 1, checkInfinity),
    invalid('const foo = {Infinity};', 1, checkInfinity),
    invalid('const foo = {Infinity: Infinity};', 1, checkInfinity),
    invalid('const foo = {[Infinity]: -Infinity};', 2, checkInfinity),
    invalid('const foo = {[-Infinity]: Infinity};', 2, checkInfinity),
    invalid('const foo = {Infinity: -Infinity};', 1, checkInfinity),
    invalid('const {foo = Infinity} = {};', 1, checkInfinity),
    invalid('const {foo = -Infinity} = {};', 1, checkInfinity),
    invalid('const foo = Infinity.toString();', 1, checkInfinity),
    invalid('const foo = -Infinity.toString();', 1, checkInfinity),
    invalid('const foo = (-Infinity).toString();', 1, checkInfinity),
    invalid('const foo = +Infinity;', 1, checkInfinity),
    invalid('const foo = +-Infinity;', 1, checkInfinity),
    invalid('const foo = -Infinity;', 1, checkInfinity),
    invalid('const foo = -(-Infinity);', 1, checkInfinity),
    invalid('const foo = 1 - Infinity;', 1, checkInfinity),
    invalid('const foo = 1 - -Infinity;', 1, checkInfinity),
    invalid(
      'const isPositiveZero = value => value === 0 && 1 / value === Infinity;',
      1,
      checkInfinity,
    ),
    invalid(
      'const isNegativeZero = value => value === 0 && 1 / value === -Infinity;',
      1,
      checkInfinity,
    ),
    invalid('const {a = NaN} = {};'),
    invalid('const {[NaN]: a = NaN} = {};', 2),
    invalid('const [a = NaN] = [];'),
    invalid('function foo({a = NaN}) {}'),
    invalid('function foo({[NaN]: a = NaN}) {}', 2),
    invalid('function foo([a = NaN]) {}'),
    invalid('function foo() {return-Infinity}', 1, checkInfinity),
    invalid('globalThis.isNaN(foo);'),
    invalid('global.isNaN(foo);'),
    invalid('window.isNaN(foo);'),
    invalid('self.isNaN(foo);'),
    invalid('globalThis.parseFloat(foo);'),
    invalid('global.parseFloat(foo);'),
    invalid('window.parseFloat(foo);'),
    invalid('self.parseFloat(foo);'),
    invalid('globalThis.NaN'),
    invalid('-globalThis.Infinity', 1, checkInfinity),
    invalid(
      'const options = {\n\tnormalize: parseFloat,\n\tparseInt,\n};\n\nrun(foo, options);',
      2,
    ),
  ],
});
