name: Setup Go
description: Setup Go

inputs:
  go-version:
    description: Go version range to set up.
    required: true
  cache-name:
    description: Name of scoped cache for this set up.
    default: 'cache'

runs:
  using: composite
  steps:
    - name: Install Go
      id: install-go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
      with:
        go-version: ${{ inputs.go-version }}
        cache: false

    - name: Clean Go module cache dir
      shell: bash
      if: runner.os == 'linux'
      run: sudo rm -rf ~/go/pkg/mod/golang.org/toolchain*

    - name: Go cache
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      if: runner.environment == 'github-hosted'
      with:
        key: setup-go-${{ runner.os }}-${{ steps.install-go.outputs.go-version }}-${{ inputs.cache-name }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          setup-go-${{ runner.os }}-${{ steps.install-go.outputs.go-version }}-${{ inputs.cache-name }}-${{ hashFiles('**/go.sum') }}
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
          ~/Library/Caches/go-build
          ~/AppData/Local/go-build

    - name: Go cache
      uses: lynx-infra/cache@5c6160a6a4c7fca80a2f3057bb9dfc9513fcb732
      if: runner.environment == 'self-hosted'
      with:
        key: setup-go-SH-1-${{ runner.os }}-${{ steps.install-go.outputs.go-version }}-${{ inputs.cache-name }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          setup-go-SH-1-${{ runner.os }}-${{ steps.install-go.outputs.go-version }}-${{ inputs.cache-name }}-${{ hashFiles('**/go.sum') }}
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
          ~/Library/Caches/go-build
          ~/AppData/Local/go-build

    - name: Patch tsgo
      shell: bash
      run: ./scripts/apply-tsgo-patch.sh
