name: Setup Go
description: Setup Go

inputs:
  go-version:
    description: Go version range to set up.
    required: true
  cache-name:
    description: Name of scoped cache for this set up.
    default: 'cache'

runs:
  using: composite
  steps:
    - name: Install Go
      id: install-go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
      with:
        go-version: ${{ inputs.go-version }}
        cache: false

    - name: Go cache
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      if: runner.environment == 'github-hosted'
      with:
        key: setup-go-${{ runner.os }}-${{ steps.install-go.outputs.go-version }}-${{ inputs.cache-name }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          setup-go-${{ runner.os }}-${{ steps.install-go.outputs.go-version }}-${{ inputs.cache-name }}-${{ hashFiles('**/go.sum') }}
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
          ~/Library/Caches/go-build
          ~/AppData/Local/go-build

    - name: Go cache
      uses: lynx-infra/cache@5c6160a6a4c7fca80a2f3057bb9dfc9513fcb732
      if: runner.environment == 'self-hosted'
      with:
        key: setup-go-SH-1-${{ runner.os }}-${{ steps.install-go.outputs.go-version }}-${{ inputs.cache-name }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          setup-go-SH-1-${{ runner.os }}-${{ steps.install-go.outputs.go-version }}-${{ inputs.cache-name }}-${{ hashFiles('**/go.sum') }}
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
          ~/Library/Caches/go-build
          ~/AppData/Local/go-build

    - name: Clean Go module cache dir (Linux)
      shell: bash
      if: runner.os == 'Linux'
      run: sudo rm -rf ~/go/pkg/mod/golang.org/toolchain*

    - name: Clean Go cache dir (Windows)
      shell: pwsh
      if: runner.os == 'Windows'
      run: |
        # Show disk space before cleanup
        Write-Host "Disk space before cleanup:"
        Get-PSDrive C | Select-Object Used,Free | Format-Table

        # Clean toolchain cache
        $toolchainPath = Join-Path $env:USERPROFILE "go/pkg/mod/golang.org"
        if (Test-Path $toolchainPath) {
          Get-ChildItem -Path $toolchainPath -Filter "toolchain*" -Directory | Remove-Item -Recurse -Force -ErrorAction SilentlyContinue
        }

        # Clean both build and test cache to free disk space
        go clean -cache -testcache

        # Clean temp directory completely
        Get-ChildItem -Path $env:TEMP -ErrorAction SilentlyContinue | Remove-Item -Recurse -Force -ErrorAction SilentlyContinue

        # Clean AppData Local go-build cache
        $goBuildCache = Join-Path $env:LOCALAPPDATA "go-build"
        if (Test-Path $goBuildCache) {
          Remove-Item -Path $goBuildCache -Recurse -Force -ErrorAction SilentlyContinue
        }

        # Show disk space after cleanup
        Write-Host "Disk space after cleanup:"
        Get-PSDrive C | Select-Object Used,Free | Format-Table

    - name: Patch tsgo
      shell: bash
      run: ./scripts/apply-tsgo-patch.sh
