// TestIdLengthUpstream migrates the full valid/invalid suite from upstream
// eslint/tests/lib/rules/id-length.js 1:1. Position assertions cover
// line/column for every invalid case. rslint-specific lock-in cases live in
// the id_length_extras_test.go file.
package id_length

import (
	"testing"

	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/fixtures"
	"github.com/web-infra-dev/rslint/internal/rule_tester"
)

func TestIdLengthUpstream(t *testing.T) {
	rule_tester.RunRuleTester(
		fixtures.GetRootDir(),
		"tsconfig.json",
		t,
		&IdLengthRule,
		[]rule_tester.ValidTestCase{
			// ---- valid ----
			{Code: `var xyz;`},
			{Code: `var xy = 1;`},
			{Code: `function xyz() {};`},
			{Code: `function xyz(abc, de) {};`},
			{Code: `var obj = { abc: 1, de: 2 };`},
			{Code: `var obj = { 'a': 1, bc: 2 };`},
			{Code: `var obj = {}; obj['a'] = 2;`},
			{Code: `abc = d;`},
			{Code: `try { blah(); } catch (err) { /* pass */ }`},
			{Code: `var handler = function ($e) {};`},
			{Code: `var _a = 2`},
			{Code: `var _ad$$ = new $;`},
			{Code: `var xyz = new ΣΣ();`},
			{Code: `unrelatedExpressionThatNeedsToBeIgnored();`},
			{Code: `var obj = { 'a': 1, bc: 2 }; obj.tk = obj.a;`},
			{Code: `var query = location.query.q || '';`},
			{Code: `var query = location.query.q ? location.query.q : ''`},
			{Code: `let {a: foo} = bar;`},
			{Code: `let foo = { [a]: 1 };`},
			{Code: `let foo = { [a + b]: 1 };`},
			{Code: `var x = Foo(42)`, Options: map[string]any{"min": 1}},
			{Code: `var x = Foo(42)`, Options: map[string]any{"min": 0}},
			{Code: `foo.$x = Foo(42)`, Options: map[string]any{"min": 1}},
			{Code: `var lalala = Foo(42)`, Options: map[string]any{"max": 6}},
			{Code: `for (var q, h=0; h < 10; h++) { console.log(h); q++; }`, Options: map[string]any{"exceptions": []any{"h", "q"}}},
			{Code: `(num) => { num * num };`},
			{Code: `function foo(num = 0) { }`},
			{Code: `class MyClass { }`},
			{Code: `class Foo { method() {} }`},
			{Code: `function foo(...args) { }`},
			{Code: `var { prop } = {};`},
			{Code: `var { [a]: prop } = {};`},
			{Code: `var { a: foo } = {};`, Options: map[string]any{"min": 3}},
			{Code: `var { prop: foo } = {};`, Options: map[string]any{"max": 3}},
			{Code: `var { longName: foo } = {};`, Options: map[string]any{"min": 3, "max": 5}},
			{Code: `var { foo: a } = {};`, Options: map[string]any{"exceptions": []any{"a"}}},
			{Code: `var { a: { b: { c: longName } } } = {};`},
			{Code: `({ a: obj.x.y.z } = {});`, Options: map[string]any{"properties": "never"}},
			{Code: `import something from 'y';`},
			{Code: `export var num = 0;`},
			{Code: `import * as something from 'y';`},
			{Code: `import { x } from 'y';`},
			{Code: `import { x as x } from 'y';`},
			{Code: `import { 'x' as x } from 'y';`},
			{Code: `import { x as foo } from 'y';`},
			{Code: `import { longName } from 'y';`, Options: map[string]any{"max": 5}},
			{Code: `import { x as bar } from 'y';`, Options: map[string]any{"max": 5}},
			{Code: `({ prop: obj.x.y.something } = {});`},
			{Code: `({ prop: obj.longName } = {});`},
			{Code: `var obj = { a: 1, bc: 2 };`, Options: map[string]any{"properties": "never"}},
			{Code: `var obj = { [a]: 2 };`, Options: map[string]any{"properties": "never"}},
			{Code: `var obj = {}; obj.a = 1; obj.bc = 2;`, Options: map[string]any{"properties": "never"}},
			{Code: `({ prop: obj.x } = {});`, Options: map[string]any{"properties": "never"}},
			{Code: `var obj = { aaaaa: 1 };`, Options: map[string]any{"max": 4, "properties": "never"}},
			{Code: `var obj = {}; obj.aaaaa = 1;`, Options: map[string]any{"max": 4, "properties": "never"}},
			{Code: `({ a: obj.x.y.z } = {});`, Options: map[string]any{"max": 4, "properties": "never"}},
			{Code: `({ prop: obj.xxxxx } = {});`, Options: map[string]any{"max": 4, "properties": "never"}},
			{Code: `var arr = [i,j,f,b]`},
			{Code: `function foo([arr]) {}`},
			{Code: `var {x} = foo;`, Options: map[string]any{"properties": "never"}},
			{Code: `var {x, y: {z}} = foo;`, Options: map[string]any{"properties": "never"}},
			{Code: `let foo = { [a]: 1 };`, Options: map[string]any{"properties": "always"}},
			{Code: `let foo = { [a + b]: 1 };`, Options: map[string]any{"properties": "always"}},
			{Code: `function BEFORE_send() {};`, Options: map[string]any{"min": 3, "max": 5, "exceptionPatterns": []any{"^BEFORE_"}}},
			{Code: `function BEFORE_send() {};`, Options: map[string]any{"min": 3, "max": 5, "exceptionPatterns": []any{"^BEFORE_", "send$"}}},
			{Code: `function BEFORE_send() {};`, Options: map[string]any{"min": 3, "max": 5, "exceptionPatterns": []any{"^BEFORE_", "^A", "^Z"}}},
			{Code: `function BEFORE_send() {};`, Options: map[string]any{"min": 3, "max": 5, "exceptionPatterns": []any{"^A", "^BEFORE_", "^Z"}}},
			{Code: `var x = 1 ;`, Options: map[string]any{"min": 3, "max": 5, "exceptionPatterns": []any{"[x-z]"}}},

			// ---- Class Fields ----
			{Code: `class Foo { #xyz() {} }`},
			{Code: `class Foo { xyz = 1 }`},
			{Code: `class Foo { #xyz = 1 }`},
			{Code: `class Foo { #abc() {} }`, Options: map[string]any{"max": 3}},
			{Code: `class Foo { abc = 1 }`, Options: map[string]any{"max": 3}},
			{Code: `class Foo { #abc = 1 }`, Options: map[string]any{"max": 3}},

			// ---- Identifier consisting of two code units ----
			{Code: `var 𠮟 = 2`, Options: map[string]any{"min": 1, "max": 1}},
			{Code: `var 葛󠄀 = 2`, Options: map[string]any{"min": 1, "max": 1}}, // 2 code points but only 1 grapheme
			{Code: `var a = { 𐌘: 1 };`, Options: map[string]any{"min": 1, "max": 1}},
			{Code: `(𐌘) => { 𐌘 * 𐌘 };`, Options: map[string]any{"min": 1, "max": 1}},
			{Code: `class 𠮟 { }`, Options: map[string]any{"min": 1, "max": 1}},
			{Code: `class F { 𐌘() {} }`, Options: map[string]any{"min": 1, "max": 1}},
			{Code: `class F { #𐌘() {} }`, Options: map[string]any{"min": 1, "max": 1}},
			{Code: `class F { 𐌘 = 1 }`, Options: map[string]any{"min": 1, "max": 1}},
			{Code: `class F { #𐌘 = 1 }`, Options: map[string]any{"min": 1, "max": 1}},
			{Code: `function f(...𐌘) { }`, Options: map[string]any{"min": 1, "max": 1}},
			{Code: `function f([𐌘]) { }`, Options: map[string]any{"min": 1, "max": 1}},
			{Code: `var [ 𐌘 ] = a;`, Options: map[string]any{"min": 1, "max": 1}},
			{Code: `var { p: [𐌘]} = {};`, Options: map[string]any{"min": 1, "max": 1}},
			{Code: `function f({𐌘}) { }`, Options: map[string]any{"min": 1, "max": 1}},
			{Code: `var { 𐌘 } = {};`, Options: map[string]any{"min": 1, "max": 1}},
			{Code: `var { p: 𐌘} = {};`, Options: map[string]any{"min": 1, "max": 1}},
			{Code: `({ prop: o.𐌘 } = {});`, Options: map[string]any{"min": 1, "max": 1}},

			// ---- Import attribute keys ----
			{Code: `import foo from 'foo.json' with { type: 'json' }`, Options: map[string]any{"min": 1, "max": 3, "properties": "always"}},
			{Code: `export * from 'foo.json' with { type: 'json' }`, Options: map[string]any{"min": 1, "max": 3, "properties": "always"}},
			{Code: `export { default } from 'foo.json' with { type: 'json' }`, Options: map[string]any{"min": 1, "max": 3, "properties": "always"}},
			{Code: `import('foo.json', { with: { type: 'json' } })`, Options: map[string]any{"min": 1, "max": 3, "properties": "always"}},
			{Code: `import('foo.json', { 'with': { type: 'json' } })`, Options: map[string]any{"min": 1, "max": 3, "properties": "always"}},
			{Code: `import('foo.json', { with: { type } })`, Options: map[string]any{"min": 1, "max": 3, "properties": "always"}},
		},
		[]rule_tester.InvalidTestCase{
			// ---- invalid ----
			{Code: `var x = 1;`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name 'x' is too short (< 2).", Line: 1, Column: 5}}},
			{Code: `var x;`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name 'x' is too short (< 2).", Line: 1, Column: 5}}},
			{Code: `obj.e = document.body;`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name 'e' is too short (< 2).", Line: 1, Column: 5}}},
			{Code: `function x() {};`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name 'x' is too short (< 2).", Line: 1, Column: 10}}},
			{Code: `function xyz(a) {};`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name 'a' is too short (< 2).", Line: 1, Column: 14}}},
			{Code: `var obj = { a: 1, bc: 2 };`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name 'a' is too short (< 2).", Line: 1, Column: 13}}},
			{Code: `try { blah(); } catch (e) { /* pass */ }`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name 'e' is too short (< 2).", Line: 1, Column: 24}}},
			{Code: `var handler = function (e) {};`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name 'e' is too short (< 2).", Line: 1, Column: 25}}},
			{Code: `for (var i=0; i < 10; i++) { console.log(i); }`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name 'i' is too short (< 2).", Line: 1, Column: 10}}},
			{Code: `var j=0; while (j > -10) { console.log(--j); }`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name 'j' is too short (< 2).", Line: 1, Column: 5}}},
			{Code: `var [i] = arr;`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name 'i' is too short (< 2).", Line: 1, Column: 6}}},
			{Code: `var [,i,a] = arr;`, Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "tooShort", Message: "Identifier name 'i' is too short (< 2).", Line: 1, Column: 7},
				{MessageId: "tooShort", Message: "Identifier name 'a' is too short (< 2).", Line: 1, Column: 9},
			}},
			{Code: `function foo([a]) {}`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name 'a' is too short (< 2).", Line: 1, Column: 15}}},
			{Code: `import x from 'module';`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name 'x' is too short (< 2).", Line: 1, Column: 8}}},
			{Code: `import { x as z } from 'module';`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name 'z' is too short (< 2).", Line: 1, Column: 15}}},
			{Code: `import { foo as z } from 'module';`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name 'z' is too short (< 2).", Line: 1, Column: 17}}},
			{Code: `import { 'foo' as z } from 'module';`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name 'z' is too short (< 2).", Line: 1, Column: 19}}},
			{Code: `import * as x from 'module';`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name 'x' is too short (< 2).", Line: 1, Column: 13}}},
			{Code: `import longName from 'module';`, Options: map[string]any{"max": 5}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooLong", Message: "Identifier name 'longName' is too long (> 5).", Line: 1, Column: 8}}},
			{Code: `import * as longName from 'module';`, Options: map[string]any{"max": 5}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooLong", Message: "Identifier name 'longName' is too long (> 5).", Line: 1, Column: 13}}},
			{Code: `import { foo as longName } from 'module';`, Options: map[string]any{"max": 5}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooLong", Message: "Identifier name 'longName' is too long (> 5).", Line: 1, Column: 17}}},
			{Code: `var _$xt_$ = Foo(42)`, Options: map[string]any{"min": 2, "max": 4}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooLong", Message: "Identifier name '_$xt_$' is too long (> 4).", Line: 1, Column: 5}}},
			{Code: `var _$x$_t$ = Foo(42)`, Options: map[string]any{"min": 2, "max": 4}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooLong", Message: "Identifier name '_$x$_t$' is too long (> 4).", Line: 1, Column: 5}}},
			{Code: `var toString;`, Options: map[string]any{"max": 5}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooLong", Message: "Identifier name 'toString' is too long (> 5).", Line: 1, Column: 5}}},
			{Code: `(a) => { a * a };`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name 'a' is too short (< 2).", Line: 1, Column: 2}}},
			{Code: `function foo(x = 0) { }`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name 'x' is too short (< 2).", Line: 1, Column: 14}}},
			{Code: `class x { }`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name 'x' is too short (< 2).", Line: 1, Column: 7}}},
			{Code: `class Foo { x() {} }`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name 'x' is too short (< 2).", Line: 1, Column: 13}}},
			{Code: `function foo(...x) { }`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name 'x' is too short (< 2).", Line: 1, Column: 17}}},
			{Code: `function foo({x}) { }`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name 'x' is too short (< 2).", Line: 1, Column: 15}}},
			{Code: `function foo({x: a}) { }`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name 'a' is too short (< 2).", Line: 1, Column: 18}}},
			{Code: `function foo({x: a, longName}) { }`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name 'a' is too short (< 2).", Line: 1, Column: 18}}},
			{Code: `function foo({ longName: a }) {}`, Options: map[string]any{"min": 3, "max": 5}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name 'a' is too short (< 3).", Line: 1, Column: 26}}},
			{Code: `function foo({ prop: longName }) {};`, Options: map[string]any{"min": 3, "max": 5}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooLong", Message: "Identifier name 'longName' is too long (> 5)."}}},
			{Code: `function foo({ a: b }) {};`, Options: map[string]any{"exceptions": []any{"a"}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name 'b' is too short (< 2).", Line: 1, Column: 19}}},
			{Code: `var hasOwnProperty;`, Options: map[string]any{"max": 10, "exceptions": []any{}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooLong", Message: "Identifier name 'hasOwnProperty' is too long (> 10).", Line: 1, Column: 5}}},
			{Code: `function foo({ a: { b: { c: d, e } } }) { }`, Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "tooShort", Message: "Identifier name 'd' is too short (< 2).", Line: 1, Column: 29},
				{MessageId: "tooShort", Message: "Identifier name 'e' is too short (< 2).", Line: 1, Column: 32},
			}},
			{Code: `var { x} = {};`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name 'x' is too short (< 2).", Line: 1, Column: 7}}},
			{Code: `var { x: a} = {};`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name 'a' is too short (< 2).", Line: 1, Column: 10}}},
			{Code: `var { a: a} = {};`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name 'a' is too short (< 2).", Line: 1, Column: 7}}},
			{Code: `var { prop: a } = {};`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name 'a' is too short (< 2).", Line: 1, Column: 13}}},
			{Code: `var { longName: a } = {};`, Options: map[string]any{"min": 3, "max": 5}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name 'a' is too short (< 3).", Line: 1, Column: 17}}},
			{Code: `var { prop: [x] } = {};`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name 'x' is too short (< 2).", Line: 1, Column: 14}}},
			{Code: `var { prop: [[x]] } = {};`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name 'x' is too short (< 2).", Line: 1, Column: 15}}},
			{Code: `var { prop: longName } = {};`, Options: map[string]any{"min": 3, "max": 5}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooLong", Message: "Identifier name 'longName' is too long (> 5).", Line: 1, Column: 13}}},
			{Code: `var { x: a} = {};`, Options: map[string]any{"exceptions": []any{"x"}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name 'a' is too short (< 2).", Line: 1, Column: 10}}},
			{Code: `var { a: { b: { c: d } } } = {};`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name 'd' is too short (< 2).", Line: 1, Column: 20}}},
			{Code: `var { a: { b: { c: d, e } } } = {};`, Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "tooShort", Message: "Identifier name 'd' is too short (< 2).", Line: 1, Column: 20},
				{MessageId: "tooShort", Message: "Identifier name 'e' is too short (< 2).", Line: 1, Column: 23},
			}},
			{Code: `var { a: { b: { c, e: longName } } } = {};`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name 'c' is too short (< 2).", Line: 1, Column: 17}}},
			{Code: `var { a: { b: { c: d, e: longName } } } = {};`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name 'd' is too short (< 2).", Line: 1, Column: 20}}},
			{Code: `var { a, b: { c: d, e: longName } } = {};`, Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "tooShort", Message: "Identifier name 'a' is too short (< 2).", Line: 1, Column: 7},
				{MessageId: "tooShort", Message: "Identifier name 'd' is too short (< 2).", Line: 1, Column: 18},
			}},
			{Code: `import x from 'y';`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name 'x' is too short (< 2).", Line: 1, Column: 8}}},
			{Code: `export var x = 0;`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name 'x' is too short (< 2).", Line: 1, Column: 12}}},
			{Code: `({ a: obj.x.y.z } = {});`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name 'z' is too short (< 2).", Line: 1, Column: 15}}},
			{Code: `({ prop: obj.x } = {});`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name 'x' is too short (< 2).", Line: 1, Column: 14}}},
			{Code: `var x = 1;`, Options: map[string]any{"properties": "never"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name 'x' is too short (< 2).", Line: 1, Column: 5}}},
			{Code: `var {prop: x} = foo;`, Options: map[string]any{"properties": "never"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name 'x' is too short (< 2).", Line: 1, Column: 12}}},
			{Code: `var foo = {x: prop};`, Options: map[string]any{"properties": "always"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name 'x' is too short (< 2).", Line: 1, Column: 12}}},
			{Code: `function BEFORE_send() {};`, Options: map[string]any{"min": 3, "max": 5}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooLong", Message: "Identifier name 'BEFORE_send' is too long (> 5).", Line: 1, Column: 10}}},
			{Code: `function NOTMATCHED_send() {};`, Options: map[string]any{"min": 3, "max": 5, "exceptionPatterns": []any{"^BEFORE_"}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooLong", Message: "Identifier name 'NOTMATCHED_send' is too long (> 5).", Line: 1, Column: 10}}},
			{Code: `function N() {};`, Options: map[string]any{"min": 3, "max": 5, "exceptionPatterns": []any{"^BEFORE_"}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name 'N' is too short (< 3).", Line: 1, Column: 10}}},

			// ---- Class Fields ----
			{Code: `class Foo { #x() {} }`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShortPrivate", Message: "Identifier name '#x' is too short (< 2).", Line: 1, Column: 13}}},
			{Code: `class Foo { x = 1 }`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name 'x' is too short (< 2).", Line: 1, Column: 13}}},
			{Code: `class Foo { #x = 1 }`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShortPrivate", Message: "Identifier name '#x' is too short (< 2).", Line: 1, Column: 13}}},
			{Code: `class Foo { #abcdefg() {} }`, Options: map[string]any{"max": 3}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooLongPrivate", Message: "Identifier name #'abcdefg' is too long (> 3).", Line: 1, Column: 13}}},
			{Code: `class Foo { abcdefg = 1 }`, Options: map[string]any{"max": 3}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooLong", Message: "Identifier name 'abcdefg' is too long (> 3).", Line: 1, Column: 13}}},
			{Code: `class Foo { #abcdefg = 1 }`, Options: map[string]any{"max": 3}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooLongPrivate", Message: "Identifier name #'abcdefg' is too long (> 3).", Line: 1, Column: 13}}},

			// ---- Identifier consisting of two code units ----
			{Code: `var 𠮟 = 2`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name '𠮟' is too short (< 2).", Line: 1, Column: 5}}},
			{Code: `var 葛󠄀 = 2`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name '葛󠄀' is too short (< 2).", Line: 1, Column: 5}}}, // 2 code points but only 1 grapheme
			{Code: `var myObj = { 𐌘: 1 };`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name '𐌘' is too short (< 2).", Line: 1, Column: 15}}},
			{Code: `(𐌘) => { 𐌘 * 𐌘 };`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name '𐌘' is too short (< 2).", Line: 1, Column: 2}}},
			{Code: `class 𠮟 { }`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name '𠮟' is too short (< 2).", Line: 1, Column: 7}}},
			{Code: `class Foo { 𐌘() {} }`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name '𐌘' is too short (< 2).", Line: 1, Column: 13}}},
			{Code: `class Foo1 { #𐌘() {} }`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShortPrivate", Message: "Identifier name '#𐌘' is too short (< 2).", Line: 1, Column: 14}}},
			{Code: `class Foo2 { 𐌘 = 1 }`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name '𐌘' is too short (< 2).", Line: 1, Column: 14}}},
			{Code: `class Foo3 { #𐌘 = 1 }`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShortPrivate", Message: "Identifier name '#𐌘' is too short (< 2).", Line: 1, Column: 14}}},
			{Code: `function foo1(...𐌘) { }`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name '𐌘' is too short (< 2).", Line: 1, Column: 18}}},
			{Code: `function foo([𐌘]) { }`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name '𐌘' is too short (< 2).", Line: 1, Column: 15}}},
			{Code: `var [ 𐌘 ] = arr;`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name '𐌘' is too short (< 2).", Line: 1, Column: 7}}},
			{Code: `var { prop: [𐌘]} = {};`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name '𐌘' is too short (< 2).", Line: 1, Column: 14}}},
			{Code: `function foo({𐌘}) { }`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name '𐌘' is too short (< 2).", Line: 1, Column: 15}}},
			{Code: `var { 𐌘 } = {};`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name '𐌘' is too short (< 2).", Line: 1, Column: 7}}},
			{Code: `var { prop: 𐌘} = {};`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name '𐌘' is too short (< 2).", Line: 1, Column: 13}}},
			{Code: `({ prop: obj.𐌘 } = {});`, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "tooShort", Message: "Identifier name '𐌘' is too short (< 2).", Line: 1, Column: 14}}},
		},
	)
}
