
// Code generated by tools/gen_shims. DO NOT EDIT.

package jsxtransforms

import "github.com/microsoft/typescript-go/internal/transformers"
import "github.com/microsoft/typescript-go/internal/transformers/jsxtransforms"
import _ "unsafe"

type JSXTransformer = jsxtransforms.JSXTransformer
//go:linkname NewJSXTransformer github.com/microsoft/typescript-go/internal/transformers/jsxtransforms.NewJSXTransformer
func NewJSXTransformer(opts *transformers.TransformOptions) *transformers.Transformer
//go:linkname DecodeEntities github.com/microsoft/typescript-go/internal/transformers/jsxtransforms.decodeEntities
func DecodeEntities(text string) string
//go:linkname DecodeEntity github.com/microsoft/typescript-go/internal/transformers/jsxtransforms.decodeEntity
func DecodeEntity(entity string) (rune, bool)
