
// Code generated by tools/gen_shims. DO NOT EDIT.

package vfs

import "github.com/microsoft/typescript-go/internal/vfs"
import "github.com/microsoft/typescript-go/internal/vfs/vfsmatch"
import _ "unsafe"

type DirEntry = vfs.DirEntry
type Entries = vfs.Entries
var ErrClosed = vfs.ErrClosed
var ErrExist = vfs.ErrExist
var ErrInvalid = vfs.ErrInvalid
var ErrNotExist = vfs.ErrNotExist
var ErrPermission = vfs.ErrPermission
type FS = vfs.FS
type FileInfo = vfs.FileInfo
//go:linkname IsImplicitGlob github.com/microsoft/typescript-go/internal/vfs/vfsmatch.IsImplicitGlob
func IsImplicitGlob(lastPathComponent string) bool
//go:linkname ReadDirectory github.com/microsoft/typescript-go/internal/vfs/vfsmatch.ReadDirectory
func ReadDirectory(host vfs.FS, currentDir string, path string, extensions []string, excludes []string, includes []string, depth int) []string
var SkipAll = vfs.SkipAll
var SkipDir = vfs.SkipDir
type Usage = vfsmatch.Usage
const UsageDirectories = vfsmatch.UsageDirectories
const UsageExclude = vfsmatch.UsageExclude
const UsageFiles = vfsmatch.UsageFiles
type WalkDirFunc = vfs.WalkDirFunc
