// Ported from eslint-plugin-unicorn v77.0.0 test/no-useless-spread.js and docs/rules/no-useless-spread.md.
// https://github.com/sindresorhus/eslint-plugin-unicorn/tree/v77.0.0
// Safety differences: copyWithin/accessors are allowed; for-of/yield* edits are suggestions.
// Other messages, ranges, fixes and suggestions match ESLint 10.12.0.
package no_useless_spread_test

import (
	"testing"

	"github.com/web-infra-dev/rslint/internal/plugins/unicorn/fixtures"
	"github.com/web-infra-dev/rslint/internal/plugins/unicorn/rules/no_useless_spread"
	"github.com/web-infra-dev/rslint/internal/rule_tester"
)

func TestNoUselessSpreadSpreadInList(t *testing.T) {
	rule_tester.RunRuleTester(fixtures.GetRootDir(), "tsconfig.json", t, &no_useless_spread.NoUselessSpreadRule,
		[]rule_tester.ValidTestCase{
			{Code: "const array = [[]]", FileName: "file.js"},
			{Code: "const array = [{}]", FileName: "file.js"},
			{Code: "const object = ({...[]})", FileName: "file.js"},
			{Code: "foo([])", FileName: "file.js"},
			{Code: "foo({})", FileName: "file.js"},
			{Code: "new Foo([])", FileName: "file.js"},
			{Code: "new Foo({})", FileName: "file.js"},
			{Code: "const array = [...a]", FileName: "file.js"},
			{Code: "const object = {...a}", FileName: "file.js"},
			{Code: "const [first, ...rest] = []", FileName: "file.js"},
			{Code: "const {foo, ...rest} = {}", FileName: "file.js"},
			{Code: "function a(foo, ...rest) {}", FileName: "file.js"},
			{Code: "({\n\tget a() {},\n\tset a(v) {},\n\t...{\n\t\tget a() {}\n\t}\n})", FileName: "file.js"},
		},
		[]rule_tester.InvalidTestCase{
			{Code: "const array = [...[a]]", FileName: "file.js", Output: []string{"const array = [a]"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an array literal in array literal is unnecessary.", Line: 1, Column: 16, EndLine: 1, EndColumn: 19}}},
			{Code: "const object = {...{a}}", FileName: "file.js", Output: []string{"const object = {a}"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an object literal in object literal is unnecessary.", Line: 1, Column: 17, EndLine: 1, EndColumn: 20}}},
			{Code: "foo(...[a])", FileName: "file.js", Output: []string{"foo(a)"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an array literal in arguments is unnecessary.", Line: 1, Column: 5, EndLine: 1, EndColumn: 8}}},
			{Code: "new Foo(...[a])", FileName: "file.js", Output: []string{"new Foo(a)"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an array literal in arguments is unnecessary.", Line: 1, Column: 9, EndLine: 1, EndColumn: 12}}},
			{Code: "const array = [...[a,]]", FileName: "file.js", Output: []string{"const array = [a]"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an array literal in array literal is unnecessary.", Line: 1, Column: 16, EndLine: 1, EndColumn: 19}}},
			{Code: "const object = {...{a,}}", FileName: "file.js", Output: []string{"const object = {a}"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an object literal in object literal is unnecessary.", Line: 1, Column: 17, EndLine: 1, EndColumn: 20}}},
			{Code: "foo(...[a,])", FileName: "file.js", Output: []string{"foo(a)"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an array literal in arguments is unnecessary.", Line: 1, Column: 5, EndLine: 1, EndColumn: 8}}},
			{Code: "new Foo(...[a,])", FileName: "file.js", Output: []string{"new Foo(a)"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an array literal in arguments is unnecessary.", Line: 1, Column: 9, EndLine: 1, EndColumn: 12}}},
			{Code: "const array = [...[a,],]", FileName: "file.js", Output: []string{"const array = [a,]"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an array literal in array literal is unnecessary.", Line: 1, Column: 16, EndLine: 1, EndColumn: 19}}},
			{Code: "const object = {...{a,},}", FileName: "file.js", Output: []string{"const object = {a,}"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an object literal in object literal is unnecessary.", Line: 1, Column: 17, EndLine: 1, EndColumn: 20}}},
			{Code: "foo(...[a,],)", FileName: "file.js", Output: []string{"foo(a,)"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an array literal in arguments is unnecessary.", Line: 1, Column: 5, EndLine: 1, EndColumn: 8}}},
			{Code: "new Foo(...[a,],)", FileName: "file.js", Output: []string{"new Foo(a,)"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an array literal in arguments is unnecessary.", Line: 1, Column: 9, EndLine: 1, EndColumn: 12}}},
			{Code: "const array = [...(( [a] ))]", FileName: "file.js", Output: []string{"const array = [ a ]"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an array literal in array literal is unnecessary.", Line: 1, Column: 16, EndLine: 1, EndColumn: 19}}},
			{Code: "const object = {...(( {a} ))}", FileName: "file.js", Output: []string{"const object = { a }"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an object literal in object literal is unnecessary.", Line: 1, Column: 17, EndLine: 1, EndColumn: 20}}},
			{Code: "foo(...(( [a] )))", FileName: "file.js", Output: []string{"foo( a )"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an array literal in arguments is unnecessary.", Line: 1, Column: 5, EndLine: 1, EndColumn: 8}}},
			{Code: "new Foo(...(( [a] )))", FileName: "file.js", Output: []string{"new Foo( a )"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an array literal in arguments is unnecessary.", Line: 1, Column: 9, EndLine: 1, EndColumn: 12}}},
			{Code: "const array = [...[]]", FileName: "file.js", Output: []string{"const array = []"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an array literal in array literal is unnecessary.", Line: 1, Column: 16, EndLine: 1, EndColumn: 19}}},
			{Code: "const object = {...{}}", FileName: "file.js", Output: []string{"const object = {}"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an object literal in object literal is unnecessary.", Line: 1, Column: 17, EndLine: 1, EndColumn: 20}}},
			{Code: "foo(...[])", FileName: "file.js", Output: []string{"foo()"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an array literal in arguments is unnecessary.", Line: 1, Column: 5, EndLine: 1, EndColumn: 8}}},
			{Code: "new Foo(...[])", FileName: "file.js", Output: []string{"new Foo()"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an array literal in arguments is unnecessary.", Line: 1, Column: 9, EndLine: 1, EndColumn: 12}}},
			{Code: "const array = [...[,]]", FileName: "file.js", Output: []string{"const array = []"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an array literal in array literal is unnecessary.", Line: 1, Column: 16, EndLine: 1, EndColumn: 19}}},
			{Code: "foo(...[,])", FileName: "file.js", Output: []string{"foo(undefined)"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an array literal in arguments is unnecessary.", Line: 1, Column: 5, EndLine: 1, EndColumn: 8}}},
			{Code: "new Foo(...[,])", FileName: "file.js", Output: []string{"new Foo(undefined)"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an array literal in arguments is unnecessary.", Line: 1, Column: 9, EndLine: 1, EndColumn: 12}}},
			{Code: "const array = [...[,,]]", FileName: "file.js", Output: []string{"const array = [,]"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an array literal in array literal is unnecessary.", Line: 1, Column: 16, EndLine: 1, EndColumn: 19}}},
			{Code: "foo(...[,,])", FileName: "file.js", Output: []string{"foo(undefined,undefined)"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an array literal in arguments is unnecessary.", Line: 1, Column: 5, EndLine: 1, EndColumn: 8}}},
			{Code: "new Foo(...[,,])", FileName: "file.js", Output: []string{"new Foo(undefined,undefined)"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an array literal in arguments is unnecessary.", Line: 1, Column: 9, EndLine: 1, EndColumn: 12}}},
			{Code: "const array = [...[a, , b,]]", FileName: "file.js", Output: []string{"const array = [a, , b]"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an array literal in array literal is unnecessary.", Line: 1, Column: 16, EndLine: 1, EndColumn: 19}}},
			{Code: "foo(...[a, , b,])", FileName: "file.js", Output: []string{"foo(a, undefined, b)"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an array literal in arguments is unnecessary.", Line: 1, Column: 5, EndLine: 1, EndColumn: 8}}},
			{Code: "new Foo(...[a, , b,])", FileName: "file.js", Output: []string{"new Foo(a, undefined, b)"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an array literal in arguments is unnecessary.", Line: 1, Column: 9, EndLine: 1, EndColumn: 12}}},
			{Code: "const array = [...[a, , b,],]", FileName: "file.js", Output: []string{"const array = [a, , b,]"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an array literal in array literal is unnecessary.", Line: 1, Column: 16, EndLine: 1, EndColumn: 19}}},
			{Code: "foo(...[a, , b,],)", FileName: "file.js", Output: []string{"foo(a, undefined, b,)"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an array literal in arguments is unnecessary.", Line: 1, Column: 5, EndLine: 1, EndColumn: 8}}},
			{Code: "new Foo(...[a, , b,],)", FileName: "file.js", Output: []string{"new Foo(a, undefined, b,)"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an array literal in arguments is unnecessary.", Line: 1, Column: 9, EndLine: 1, EndColumn: 12}}},
			{Code: "foo(...[,, ,(( a )), ,,(0, b), ,,])", FileName: "file.js", Output: []string{"foo(undefined,undefined, undefined,(( a )), undefined,undefined,(0, b), undefined,undefined)"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an array literal in arguments is unnecessary.", Line: 1, Column: 5, EndLine: 1, EndColumn: 8}}},
			{Code: "const array = [a, ...[a, b]]", FileName: "file.js", Output: []string{"const array = [a, a, b]"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an array literal in array literal is unnecessary.", Line: 1, Column: 19, EndLine: 1, EndColumn: 22}}},
			{Code: "const object = {a, ...{a, b}}", FileName: "file.js", Output: []string{"const object = {a, a, b}"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an object literal in object literal is unnecessary.", Line: 1, Column: 20, EndLine: 1, EndColumn: 23}}},
			{Code: "foo(a, ...[a, b])", FileName: "file.js", Output: []string{"foo(a, a, b)"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an array literal in arguments is unnecessary.", Line: 1, Column: 8, EndLine: 1, EndColumn: 11}}},
			{Code: "new Foo(a, ...[a, b])", FileName: "file.js", Output: []string{"new Foo(a, a, b)"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an array literal in arguments is unnecessary.", Line: 1, Column: 12, EndLine: 1, EndColumn: 15}}},
			{Code: "const array = [...[a, b], b,]", FileName: "file.js", Output: []string{"const array = [a, b, b,]"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an array literal in array literal is unnecessary.", Line: 1, Column: 16, EndLine: 1, EndColumn: 19}}},
			{Code: "const object = {...{a, b}, b,}", FileName: "file.js", Output: []string{"const object = {a, b, b,}"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an object literal in object literal is unnecessary.", Line: 1, Column: 17, EndLine: 1, EndColumn: 20}}},
			{Code: "foo(...[a, b], b,)", FileName: "file.js", Output: []string{"foo(a, b, b,)"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an array literal in arguments is unnecessary.", Line: 1, Column: 5, EndLine: 1, EndColumn: 8}}},
			{Code: "new Foo(...[a, b], b,)", FileName: "file.js", Output: []string{"new Foo(a, b, b,)"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an array literal in arguments is unnecessary.", Line: 1, Column: 9, EndLine: 1, EndColumn: 12}}},
			{Code: "const array = [a, ...[a, b], b,]", FileName: "file.js", Output: []string{"const array = [a, a, b, b,]"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an array literal in array literal is unnecessary.", Line: 1, Column: 19, EndLine: 1, EndColumn: 22}}},
			{Code: "const object = {a, ...{a, b}, b,}", FileName: "file.js", Output: []string{"const object = {a, a, b, b,}"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an object literal in object literal is unnecessary.", Line: 1, Column: 20, EndLine: 1, EndColumn: 23}}},
			{Code: "foo(a, ...[a, b], b,)", FileName: "file.js", Output: []string{"foo(a, a, b, b,)"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an array literal in arguments is unnecessary.", Line: 1, Column: 8, EndLine: 1, EndColumn: 11}}},
			{Code: "new Foo(a, ...[a, b], b,)", FileName: "file.js", Output: []string{"new Foo(a, a, b, b,)"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an array literal in arguments is unnecessary.", Line: 1, Column: 12, EndLine: 1, EndColumn: 15}}},
			{Code: "const array = [a, ...[], b]", FileName: "file.js", Output: []string{"const array = [a,  b]"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an array literal in array literal is unnecessary.", Line: 1, Column: 19, EndLine: 1, EndColumn: 22}}},
			{Code: "const array = [a, ...(( [] )),]", FileName: "file.js", Output: []string{"const array = [a,   ]"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an array literal in array literal is unnecessary.", Line: 1, Column: 19, EndLine: 1, EndColumn: 22}}},
			{Code: "const array = [a, ...(( [] ))]", FileName: "file.js", Output: []string{"const array = [a,   ]"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an array literal in array literal is unnecessary.", Line: 1, Column: 19, EndLine: 1, EndColumn: 22}}},
			{Code: "const array = [a, ...[b], c]", FileName: "file.js", Output: []string{"const array = [a, b, c]"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an array literal in array literal is unnecessary.", Line: 1, Column: 19, EndLine: 1, EndColumn: 22}}},
			{Code: "const object = {a, ...(({})), b,}", FileName: "file.js", Output: []string{"const object = {a,  b,}"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an object literal in object literal is unnecessary.", Line: 1, Column: 20, EndLine: 1, EndColumn: 23}}},
			{Code: "({a:1, ...{a: 2}})", FileName: "file.js", Output: []string{"({a:1, a: 2})"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an object literal in object literal is unnecessary.", Line: 1, Column: 8, EndLine: 1, EndColumn: 11}}},
			{Code: "({...{a:1}, ...{a: 2}})", FileName: "file.js", Output: []string{"({a:1, a: 2})"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an object literal in object literal is unnecessary.", Line: 1, Column: 3, EndLine: 1, EndColumn: 6}, {MessageId: "spread-in-list", Message: "Spread an object literal in object literal is unnecessary.", Line: 1, Column: 13, EndLine: 1, EndColumn: 16}}},
			{Code: "({[a]:1, ...{[a]: 2}})", FileName: "file.js", Output: []string{"({[a]:1, [a]: 2})"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an object literal in object literal is unnecessary.", Line: 1, Column: 10, EndLine: 1, EndColumn: 13}}},
			{Code: "const object = {\n\ta: 1,\n\n\t...{\n\t\ttestKeys() {\n\t\t\tconsole.assert(Object.keys(this).length === 2)\n\t\t}\n\t}\n}\nobject.testKeys();", FileName: "file.js", Output: []string{"const object = {\n\ta: 1,\n\n\t\n\t\ttestKeys() {\n\t\t\tconsole.assert(Object.keys(this).length === 2)\n\t\t}\n\t\n}\nobject.testKeys();"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an object literal in object literal is unnecessary.", Line: 4, Column: 2, EndLine: 4, EndColumn: 5}}},
			{Code: "new Foo(\n\tfoo(\n\t\ta,\n\t\t...[a, b],\n\t\tb,\n\t),\n\t...[\n\t\ta,\n\t\t...[\n\t\t\ta,\n\t\t\tb,\n\t\t],\n\t\tb,\n\t],\n\t{\n\t\ta: [...[a, b]],\n\t\t...{\n\t\t\ta,\n\t\t\tb,\n\t\t},\n\t}\n)", FileName: "file.js", Output: []string{"new Foo(\n\tfoo(\n\t\ta,\n\t\ta, b,\n\t\tb,\n\t),\n\t\n\t\ta,\n\t\t...[\n\t\t\ta,\n\t\t\tb,\n\t\t],\n\t\tb\n\t,\n\t{\n\t\ta: [a, b],\n\t\t\n\t\t\ta,\n\t\t\tb\n\t\t,\n\t}\n)", "new Foo(\n\tfoo(\n\t\ta,\n\t\ta, b,\n\t\tb,\n\t),\n\t\n\t\ta,\n\t\t\n\t\t\ta,\n\t\t\tb\n\t\t,\n\t\tb\n\t,\n\t{\n\t\ta: [a, b],\n\t\t\n\t\t\ta,\n\t\t\tb\n\t\t,\n\t}\n)"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an array literal in arguments is unnecessary.", Line: 4, Column: 3, EndLine: 4, EndColumn: 6}, {MessageId: "spread-in-list", Message: "Spread an array literal in arguments is unnecessary.", Line: 7, Column: 2, EndLine: 7, EndColumn: 5}, {MessageId: "spread-in-list", Message: "Spread an array literal in array literal is unnecessary.", Line: 9, Column: 3, EndLine: 9, EndColumn: 6}, {MessageId: "spread-in-list", Message: "Spread an array literal in array literal is unnecessary.", Line: 16, Column: 7, EndLine: 16, EndColumn: 10}, {MessageId: "spread-in-list", Message: "Spread an object literal in object literal is unnecessary.", Line: 17, Column: 3, EndLine: 17, EndColumn: 6}}},
			{Code: "const baz = [2];\ncall(foo, ...[bar, ...baz]);", FileName: "file.js", Output: []string{"const baz = [2];\ncall(foo, bar, ...baz);"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an array literal in arguments is unnecessary.", Line: 2, Column: 11, EndLine: 2, EndColumn: 14}}},
			{Code: "Promise.all(...[...iterable])", FileName: "file.js", Output: []string{"Promise.all(...iterable)"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an array literal in arguments is unnecessary.", Line: 1, Column: 13, EndLine: 1, EndColumn: 16}}},
			{Code: "new Map(...[...iterable])", FileName: "file.js", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an array literal in arguments is unnecessary.", Line: 1, Column: 9, EndLine: 1, EndColumn: 12}}},
			{Code: "new Set(...[iterable])", FileName: "file.js", Output: []string{"new Set(iterable)"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an array literal in arguments is unnecessary.", Line: 1, Column: 9, EndLine: 1, EndColumn: 12}}},
			{Code: "Object.assign(target, {...{a}})", FileName: "file.js", Output: []string{"Object.assign(target, {a})"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an object literal in object literal is unnecessary.", Line: 1, Column: 24, EndLine: 1, EndColumn: 27}}},
		})
}

func TestNoUselessSpreadObjectAssign(t *testing.T) {
	rule_tester.RunRuleTester(fixtures.GetRootDir(), "tsconfig.json", t, &no_useless_spread.NoUselessSpreadRule,
		[]rule_tester.ValidTestCase{
			{Code: "Object.assign(target, source)", FileName: "file.js"},
			{Code: "Object.assign(target, {})", FileName: "file.js"},
			{Code: "Object.assign(target, {foo})", FileName: "file.js"},
			{Code: "Object.assign(target, {foo, ...source})", FileName: "file.js"},
			{Code: "Object.assign(target, {...source, foo})", FileName: "file.js"},
			{Code: "Object.assign?.(target, {...source})", FileName: "file.js"},
			{Code: "Object?.assign(target, {...source})", FileName: "file.js"},
			{Code: "Object[assign](target, {...source})", FileName: "file.js"},
			{Code: "NotObject.assign(target, {...source})", FileName: "file.js"},
			{Code: "Object.assign({...source})", FileName: "file.js"},
			{Code: "Object.assign({...target}, source)", FileName: "file.js"},
			{Code: "Object.assign(...args, {...source})", FileName: "file.js"},
		},
		[]rule_tester.InvalidTestCase{
			{Code: "Object.assign(target, {...source})", FileName: "file.js", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-object-assign", Message: "`Object.assign(…)` source object with only spread properties is unnecessary.", Line: 1, Column: 24, EndLine: 1, EndColumn: 27, Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestion/remove-object-assign-spread", Output: "Object.assign(target, source)"}}}}},
			{Code: "Object.assign(target, {...a}, {...b})", FileName: "file.js", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-object-assign", Message: "`Object.assign(…)` source object with only spread properties is unnecessary.", Line: 1, Column: 24, EndLine: 1, EndColumn: 27, Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestion/remove-object-assign-spread", Output: "Object.assign(target, a, {...b})"}}}, {MessageId: "spread-in-object-assign", Message: "`Object.assign(…)` source object with only spread properties is unnecessary.", Line: 1, Column: 32, EndLine: 1, EndColumn: 35, Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestion/remove-object-assign-spread", Output: "Object.assign(target, {...a}, b)"}}}}},
			{Code: "Object.assign(target, first, {...second})", FileName: "file.js", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-object-assign", Message: "`Object.assign(…)` source object with only spread properties is unnecessary.", Line: 1, Column: 31, EndLine: 1, EndColumn: 34, Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestion/remove-object-assign-spread", Output: "Object.assign(target, first, second)"}}}}},
			{Code: "Object.assign(...args, target, {...source})", FileName: "file.js", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-object-assign", Message: "`Object.assign(…)` source object with only spread properties is unnecessary.", Line: 1, Column: 33, EndLine: 1, EndColumn: 36, Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestion/remove-object-assign-spread", Output: "Object.assign(...args, target, source)"}}}}},
			{Code: "Object.assign(target, {...first, ...second}, third)", FileName: "file.js", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-object-assign", Message: "`Object.assign(…)` source object with only spread properties is unnecessary.", Line: 1, Column: 24, EndLine: 1, EndColumn: 27, Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestion/remove-object-assign-spread", Output: "Object.assign(target, first, second, third)"}}}}},
			{Code: "Object.assign(target, {...source,}, third)", FileName: "file.js", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-object-assign", Message: "`Object.assign(…)` source object with only spread properties is unnecessary.", Line: 1, Column: 24, EndLine: 1, EndColumn: 27, Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestion/remove-object-assign-spread", Output: "Object.assign(target, source, third)"}}}}},
			{Code: "Object.assign(target, {...(( source ))})", FileName: "file.js", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-object-assign", Message: "`Object.assign(…)` source object with only spread properties is unnecessary.", Line: 1, Column: 24, EndLine: 1, EndColumn: 27, Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestion/remove-object-assign-spread", Output: "Object.assign(target, (( source )))"}}}}},
			{Code: "Object.assign(target, {...(foo, bar)})", FileName: "file.js", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-object-assign", Message: "`Object.assign(…)` source object with only spread properties is unnecessary.", Line: 1, Column: 24, EndLine: 1, EndColumn: 27, Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestion/remove-object-assign-spread", Output: "Object.assign(target, (foo, bar))"}}}}},
			{Code: "Object.assign(target, {/* keep */ ...source})", FileName: "file.js", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-object-assign", Message: "`Object.assign(…)` source object with only spread properties is unnecessary.", Line: 1, Column: 35, EndLine: 1, EndColumn: 38}}},
		})
}

func TestNoUselessSpreadCollectionConstructor(t *testing.T) {
	rule_tester.RunRuleTester(fixtures.GetRootDir(), "tsconfig.json", t, &no_useless_spread.NoUselessSpreadRule,
		[]rule_tester.ValidTestCase{
			{Code: "new Set(iterable)", FileName: "file.js"},
			{Code: "new NotSet(...iterable)", FileName: "file.js"},
			{Code: "new namespace.Set(...iterable)", FileName: "file.js"},
			{Code: "Set(...iterable)", FileName: "file.js"},
			{Code: "new Uint8Array(...iterable)", FileName: "file.js"},
			{Code: "new Set(...iterable, extraArgument)", FileName: "file.js"},
		},
		[]rule_tester.InvalidTestCase{
			{Code: "new Set(...iterable)", FileName: "file.js", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-collection-constructor", Message: "`new Set(…)` accepts a single iterable argument, spreading is misleading.", Line: 1, Column: 9, EndLine: 1, EndColumn: 20}}},
			{Code: "new Map(...iterable)", FileName: "file.js", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-collection-constructor", Message: "`new Map(…)` accepts a single iterable argument, spreading is misleading.", Line: 1, Column: 9, EndLine: 1, EndColumn: 20}}},
			{Code: "new WeakSet(...iterable)", FileName: "file.js", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-collection-constructor", Message: "`new WeakSet(…)` accepts a single iterable argument, spreading is misleading.", Line: 1, Column: 13, EndLine: 1, EndColumn: 24}}},
			{Code: "new WeakMap(...iterable)", FileName: "file.js", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-collection-constructor", Message: "`new WeakMap(…)` accepts a single iterable argument, spreading is misleading.", Line: 1, Column: 13, EndLine: 1, EndColumn: 24}}},
			{Code: "new Set(...getNames())", FileName: "file.js", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-collection-constructor", Message: "`new Set(…)` accepts a single iterable argument, spreading is misleading.", Line: 1, Column: 9, EndLine: 1, EndColumn: 22}}},
		})
}

func TestNoUselessSpreadIterableConversion(t *testing.T) {
	rule_tester.RunRuleTester(fixtures.GetRootDir(), "tsconfig.json", t, &no_useless_spread.NoUselessSpreadRule,
		[]rule_tester.ValidTestCase{
			{Code: "new NotMatchedConstructor([...iterable])", FileName: "file.js"},
			{Code: "new foo.Map([...iterable])", FileName: "file.js"},
			{Code: "new Map([...iterable], extraArgument)", FileName: "file.js"},
			{Code: "new Map()", FileName: "file.js"},
			{Code: "new Map([,...iterable])", FileName: "file.js"},
			{Code: "new Map([...iterable, extraElement])", FileName: "file.js"},
			{Code: "new Map({...iterable})", FileName: "file.js"},
			{Code: "new Uint8Array(...iterable)", FileName: "file.js"},
			{Code: "new Uint8Array(before, [...iterable])", FileName: "file.js"},
			{Code: "new Uint8Array([...iterable])", FileName: "file.js"},
			{Code: "new Float64Array([...iterable])", FileName: "file.js"},
			{Code: "new Int32Array([...iterable])", FileName: "file.js"},
			{Code: "new BigInt64Array([...iterable])", FileName: "file.js"},
			{Code: "new Uint8Array([...iterable], 0)", FileName: "file.js"},
			{Code: "const typed = new BigUint64Array([...iterable], byteOffset, length)", FileName: "file.js"},
			{Code: "const typed = new BigUint64Array([...iterable], ...args)", FileName: "file.js"},
			{Code: "Promise.notMatchedMethod([...iterable])", FileName: "file.js"},
			{Code: "NotPromise.all([...iterable])", FileName: "file.js"},
			{Code: "foo.Promise.all([...iterable])", FileName: "file.js"},
			{Code: "Promise.all?.([...iterable])", FileName: "file.js"},
			{Code: "Promise?.all([...iterable])", FileName: "file.js"},
			{Code: "Promise[all]([...iterable])", FileName: "file.js"},
			{Code: "Promise.all()", FileName: "file.js"},
			{Code: "Promise.all([...iterable], extraArgument)", FileName: "file.js"},
			{Code: "Promise.all(...iterable)", FileName: "file.js"},
			{Code: "Promise.all([,...iterable])", FileName: "file.js"},
			{Code: "Promise.all([...iterable, extraElement])", FileName: "file.js"},
			{Code: "Promise.all({...iterable})", FileName: "file.js"},
			{Code: "Object.notFromEntries([...iterable])", FileName: "file.js"},
			{Code: "NotObject.fromEntries([...iterable])", FileName: "file.js"},
			{Code: "Object.fromEntries?.([...iterable])", FileName: "file.js"},
			{Code: "Object?.fromEntries([...iterable])", FileName: "file.js"},
			{Code: "Object[fromEntries]([...iterable])", FileName: "file.js"},
			{Code: "Object.fromEntries()", FileName: "file.js"},
			{Code: "Object.fromEntries([...iterable], extraArgument)", FileName: "file.js"},
			{Code: "Object.fromEntries(...iterable)", FileName: "file.js"},
			{Code: "Object.fromEntries({...iterable})", FileName: "file.js"},
			{Code: "Uint8Array.notFrom([...iterable])", FileName: "file.js"},
			{Code: "NotTypedArray.from([...iterable])", FileName: "file.js"},
			{Code: "Uint8Array.from?.([...iterable])", FileName: "file.js"},
			{Code: "Uint8Array?.from([...iterable])", FileName: "file.js"},
			{Code: "Uint8Array.from([...iterable], extraArgument)", FileName: "file.js"},
			{Code: "Uint8Array.from(...iterable)", FileName: "file.js"},
			{Code: "Uint8Array.from({...iterable})", FileName: "file.js"},
			{Code: "for (const [...iterable] of foo);", FileName: "file.js"},
			{Code: "for (const foo of bar) [...iterable];", FileName: "file.js"},
			{Code: "for (const foo of [,...iterable]);", FileName: "file.js"},
			{Code: "for (const foo of [...iterable, extraElement]);", FileName: "file.js"},
			{Code: "for (const foo of {...iterable});", FileName: "file.js"},
			{Code: "for (const foo in [...iterable]);", FileName: "file.js"},
			{Code: "function * fn() {yield [...iterable];}", FileName: "file.js"},
			{Code: "function * fn() {yield* [...iterable, extraElement];}", FileName: "file.js"},
			{Code: "function * fn() {yield* {...iterable};}", FileName: "file.js"},
		},
		[]rule_tester.InvalidTestCase{
			{Code: "const map = new Map([...iterable])", FileName: "file.js", Output: []string{"const map = new Map(iterable)"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "iterable-to-array", Message: "`new Map(…)` accepts an iterable as an argument, it's unnecessary to convert to an array.", Line: 1, Column: 21, EndLine: 1, EndColumn: 34}}},
			{Code: "const weakMap = new WeakMap([...iterable])", FileName: "file.js", Output: []string{"const weakMap = new WeakMap(iterable)"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "iterable-to-array", Message: "`new WeakMap(…)` accepts an iterable as an argument, it's unnecessary to convert to an array.", Line: 1, Column: 29, EndLine: 1, EndColumn: 42}}},
			{Code: "const set = new Set([...iterable])", FileName: "file.js", Output: []string{"const set = new Set(iterable)"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "iterable-to-array", Message: "`new Set(…)` accepts an iterable as an argument, it's unnecessary to convert to an array.", Line: 1, Column: 21, EndLine: 1, EndColumn: 34}}},
			{Code: "const weakSet = new WeakSet([...iterable])", FileName: "file.js", Output: []string{"const weakSet = new WeakSet(iterable)"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "iterable-to-array", Message: "`new WeakSet(…)` accepts an iterable as an argument, it's unnecessary to convert to an array.", Line: 1, Column: 29, EndLine: 1, EndColumn: 42}}},
			{Code: "const promise = Promise.all([...iterable])", FileName: "file.js", Output: []string{"const promise = Promise.all(iterable)"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "iterable-to-array", Message: "`Promise.all(…)` accepts an iterable as an argument, it's unnecessary to convert to an array.", Line: 1, Column: 29, EndLine: 1, EndColumn: 42}}},
			{Code: "const promise = Promise.allSettled([...iterable])", FileName: "file.js", Output: []string{"const promise = Promise.allSettled(iterable)"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "iterable-to-array", Message: "`Promise.allSettled(…)` accepts an iterable as an argument, it's unnecessary to convert to an array.", Line: 1, Column: 36, EndLine: 1, EndColumn: 49}}},
			{Code: "const promise = Promise.any([...iterable])", FileName: "file.js", Output: []string{"const promise = Promise.any(iterable)"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "iterable-to-array", Message: "`Promise.any(…)` accepts an iterable as an argument, it's unnecessary to convert to an array.", Line: 1, Column: 29, EndLine: 1, EndColumn: 42}}},
			{Code: "const promise = Promise.race([...iterable])", FileName: "file.js", Output: []string{"const promise = Promise.race(iterable)"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "iterable-to-array", Message: "`Promise.race(…)` accepts an iterable as an argument, it's unnecessary to convert to an array.", Line: 1, Column: 30, EndLine: 1, EndColumn: 43}}},
			{Code: "const array = Array.from([...iterable])", FileName: "file.js", Output: []string{"const array = Array.from(iterable)"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "iterable-to-array", Message: "`Array.from(…)` accepts an iterable as an argument, it's unnecessary to convert to an array.", Line: 1, Column: 26, EndLine: 1, EndColumn: 39}}},
			{Code: "const typed = BigUint64Array.from([...iterable])", FileName: "file.js", Output: []string{"const typed = BigUint64Array.from(iterable)"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "iterable-to-array", Message: "`BigUint64Array.from(…)` accepts an iterable as an argument, it's unnecessary to convert to an array.", Line: 1, Column: 35, EndLine: 1, EndColumn: 48}}},
			{Code: "const object = Object.fromEntries([...iterable])", FileName: "file.js", Output: []string{"const object = Object.fromEntries(iterable)"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "iterable-to-array", Message: "`Object.fromEntries(…)` accepts an iterable as an argument, it's unnecessary to convert to an array.", Line: 1, Column: 35, EndLine: 1, EndColumn: 48}}},
			{Code: "for (const foo of [...iterable]);", FileName: "file.js", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "iterable-to-array-in-for-of", Message: "`for…of` can iterate directly when an array snapshot is not needed.", Line: 1, Column: 19, EndLine: 1, EndColumn: 32, Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestion/remove-iterable-to-array", Output: "for (const foo of iterable);"}}}}},
			{Code: "async () => {for await (const foo of [...iterable]);}", FileName: "file.js", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "iterable-to-array-in-for-of", Message: "`for…of` can iterate directly when an array snapshot is not needed.", Line: 1, Column: 38, EndLine: 1, EndColumn: 51, Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestion/remove-iterable-to-array", Output: "async () => {for await (const foo of iterable);}"}}}}},
			{Code: "const map = new Map([...iterable,])", FileName: "file.js", Output: []string{"const map = new Map(iterable)"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "iterable-to-array", Message: "`new Map(…)` accepts an iterable as an argument, it's unnecessary to convert to an array.", Line: 1, Column: 21, EndLine: 1, EndColumn: 35}}},
			{Code: "for (const foo of [...iterable,]);", FileName: "file.js", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "iterable-to-array-in-for-of", Message: "`for…of` can iterate directly when an array snapshot is not needed.", Line: 1, Column: 19, EndLine: 1, EndColumn: 33, Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestion/remove-iterable-to-array", Output: "for (const foo of iterable);"}}}}},
			{Code: "const map = new Map([...iterable,],)", FileName: "file.js", Output: []string{"const map = new Map(iterable,)"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "iterable-to-array", Message: "`new Map(…)` accepts an iterable as an argument, it's unnecessary to convert to an array.", Line: 1, Column: 21, EndLine: 1, EndColumn: 35}}},
			{Code: "const map = new Map([...(( iterable ))])", FileName: "file.js", Output: []string{"const map = new Map((( iterable )))"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "iterable-to-array", Message: "`new Map(…)` accepts an iterable as an argument, it's unnecessary to convert to an array.", Line: 1, Column: 21, EndLine: 1, EndColumn: 40}}},
			{Code: "for (const foo of [...(( iterable ))]);", FileName: "file.js", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "iterable-to-array-in-for-of", Message: "`for…of` can iterate directly when an array snapshot is not needed.", Line: 1, Column: 19, EndLine: 1, EndColumn: 38, Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestion/remove-iterable-to-array", Output: "for (const foo of (( iterable )));"}}}}},
			{Code: "const map = new Map((( [...(( iterable ))] )))", FileName: "file.js", Output: []string{"const map = new Map((( (( iterable )) )))"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "iterable-to-array", Message: "`new Map(…)` accepts an iterable as an argument, it's unnecessary to convert to an array.", Line: 1, Column: 24, EndLine: 1, EndColumn: 43}}},
			{Code: "for (const foo of (( [...(( iterable ))] )));", FileName: "file.js", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "iterable-to-array-in-for-of", Message: "`for…of` can iterate directly when an array snapshot is not needed.", Line: 1, Column: 22, EndLine: 1, EndColumn: 41, Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestion/remove-iterable-to-array", Output: "for (const foo of (( (( iterable )) )));"}}}}},
			{Code: "for (const foo of[...iterable]);", FileName: "file.js", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "iterable-to-array-in-for-of", Message: "`for…of` can iterate directly when an array snapshot is not needed.", Line: 1, Column: 18, EndLine: 1, EndColumn: 31, Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestion/remove-iterable-to-array", Output: "for (const foo of iterable);"}}}}},
			{Code: "function * fn() {\n\tyield * [...iterable];\n}", FileName: "file.js", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "iterable-to-array-in-yield-star", Message: "`yield*` can delegate directly when materializing the iterable is unnecessary.", Line: 2, Column: 10, EndLine: 2, EndColumn: 23, Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestion/remove-iterable-to-array", Output: "function * fn() {\n\tyield * iterable;\n}"}}}}},
			{Code: "function * fn() {\n\tyield * [...iterable,];\n}", FileName: "file.js", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "iterable-to-array-in-yield-star", Message: "`yield*` can delegate directly when materializing the iterable is unnecessary.", Line: 2, Column: 10, EndLine: 2, EndColumn: 24, Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestion/remove-iterable-to-array", Output: "function * fn() {\n\tyield * iterable;\n}"}}}}},
			{Code: "function * fn() {\n\tyield * (( [...iterable] ));\n}", FileName: "file.js", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "iterable-to-array-in-yield-star", Message: "`yield*` can delegate directly when materializing the iterable is unnecessary.", Line: 2, Column: 13, EndLine: 2, EndColumn: 26, Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestion/remove-iterable-to-array", Output: "function * fn() {\n\tyield * (( iterable ));\n}"}}}}},
			{Code: "function * fn() {\n\tyield * (( [...(( iterable ))] ));\n}", FileName: "file.js", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "iterable-to-array-in-yield-star", Message: "`yield*` can delegate directly when materializing the iterable is unnecessary.", Line: 2, Column: 13, EndLine: 2, EndColumn: 32, Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestion/remove-iterable-to-array", Output: "function * fn() {\n\tyield * (( (( iterable )) ));\n}"}}}}},
		})
}

func TestNoUselessSpreadArrayClone(t *testing.T) {
	rule_tester.RunRuleTester(fixtures.GetRootDir(), "tsconfig.json", t, &no_useless_spread.NoUselessSpreadRule,
		[]rule_tester.ValidTestCase{
			{Code: "[...not.array]", FileName: "file.js"},
			{Code: "[...not.array()]", FileName: "file.js"},
			{Code: "[...array.unknown()]", FileName: "file.js"},
			{Code: "[...Object.notReturningArray(foo)]", FileName: "file.js"},
			{Code: "[...NotObject.keys(foo)]", FileName: "file.js"},
			{Code: "[...Int8Array.from(foo)]", FileName: "file.js"},
			{Code: "[...Int8Array.of()]", FileName: "file.js"},
			{Code: "[...new Int8Array(3)]", FileName: "file.js"},
			{Code: "[...Promise.all(foo)]", FileName: "file.js"},
			{Code: "[...Promise.allSettled(foo)]", FileName: "file.js"},
			{Code: "[...await Promise.all(foo, extraArgument)]", FileName: "file.js"},
			{Code: "[...foo.filter(bar)]", FileName: "file.js"},
			{Code: "[...foo.flatMap(bar)]", FileName: "file.js"},
			{Code: "[...foo.map(bar)]", FileName: "file.js"},
			{Code: "function foo(array: number[]) { return [...array]; }", FileName: "file.ts"},
			{Code: "function foo(array: number[]) { return [...array]; }", FileName: "file.ts"},
			{Code: "const data = new Map([[\"a\", 1], [\"b\", 2], [\"c\", 3]]); const foo = [...data.values().map(value => value * 2)];", FileName: "file.ts"},
			{Code: "function foo(value: string) { return [...value.slice(1)]; }", FileName: "file.ts"},
			{Code: "function foo(value: {slice(start: number): string}) { return [...value.slice(1)]; }", FileName: "file.ts"},
			{Code: "function foo(value: {split(separator: string): string}) { return [...value.split(\"|\")]; }", FileName: "file.ts"},
			{Code: "function foo(value: {concat(value: string): string}) { return [...value.concat(\"bar\")]; }", FileName: "file.ts"},
			{Code: "function foo(value: {map(): number[]}) { return [...value.map()]; }", FileName: "file.ts"},
			{Code: "function foo(value: {slice(start: number): number[]}) { return [...value.slice(1)]; }", FileName: "file.ts"},
			{Code: "function foo(value: Int32Array) { return [...value.slice(1)]; }", FileName: "file.ts"},
			{Code: "class ArraySubclass extends Array<number> {} function foo(value: ArraySubclass) { return [...value.slice(1)]; }", FileName: "file.ts"},
			{Code: "function foo(value: string) { return [...value.slice(1)]; }", FileName: "file.ts"},
			{Code: "function foo(value: Int32Array) { return [...value.slice(1)]; }", FileName: "file.ts"},
			{Code: "[...Iterator.concat(bar)]", FileName: "file.js"},
			{Code: "[...foo.copyWithin(-2)]", FileName: "file.js"},
		},
		[]rule_tester.InvalidTestCase{
			{Code: "[...foo.concat(bar)]", FileName: "file.js", Output: []string{"foo.concat(bar)"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "clone-array", Message: "Unnecessarily cloning an array.", Line: 1, Column: 1, EndLine: 1, EndColumn: 21}}},
			{Code: "[...foo.flat()]", FileName: "file.js", Output: []string{"foo.flat()"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "clone-array", Message: "Unnecessarily cloning an array.", Line: 1, Column: 1, EndLine: 1, EndColumn: 16}}},
			{Code: "[...foo.slice(1)]", FileName: "file.js", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "clone-array", Message: "Unnecessarily cloning an array.", Line: 1, Column: 1, EndLine: 1, EndColumn: 18}}},
			{Code: "[...foo.splice(1)]", FileName: "file.js", Output: []string{"foo.splice(1)"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "clone-array", Message: "Unnecessarily cloning an array.", Line: 1, Column: 1, EndLine: 1, EndColumn: 19}}},
			{Code: "[...foo.toReversed()]", FileName: "file.js", Output: []string{"foo.toReversed()"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "clone-array", Message: "Unnecessarily cloning an array.", Line: 1, Column: 1, EndLine: 1, EndColumn: 22}}},
			{Code: "[...foo.toSorted()]", FileName: "file.js", Output: []string{"foo.toSorted()"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "clone-array", Message: "Unnecessarily cloning an array.", Line: 1, Column: 1, EndLine: 1, EndColumn: 20}}},
			{Code: "[...foo.toSpliced(0, 1)]", FileName: "file.js", Output: []string{"foo.toSpliced(0, 1)"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "clone-array", Message: "Unnecessarily cloning an array.", Line: 1, Column: 1, EndLine: 1, EndColumn: 25}}},
			{Code: "[...foo.with(0, bar)]", FileName: "file.js", Output: []string{"foo.with(0, bar)"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "clone-array", Message: "Unnecessarily cloning an array.", Line: 1, Column: 1, EndLine: 1, EndColumn: 22}}},
			{Code: "[...foo.split(\"|\")]", FileName: "file.js", Output: []string{"foo.split(\"|\")"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "clone-array", Message: "Unnecessarily cloning an array.", Line: 1, Column: 1, EndLine: 1, EndColumn: 20}}},
			{Code: "[...Object.keys(foo)]", FileName: "file.js", Output: []string{"Object.keys(foo)"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "clone-array", Message: "Unnecessarily cloning an array.", Line: 1, Column: 1, EndLine: 1, EndColumn: 22}}},
			{Code: "[...Object.values(foo)]", FileName: "file.js", Output: []string{"Object.values(foo)"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "clone-array", Message: "Unnecessarily cloning an array.", Line: 1, Column: 1, EndLine: 1, EndColumn: 24}}},
			{Code: "[...Array.from(foo)]", FileName: "file.js", Output: []string{"Array.from(foo)"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "clone-array", Message: "Unnecessarily cloning an array.", Line: 1, Column: 1, EndLine: 1, EndColumn: 21}}},
			{Code: "[...Array.of()]", FileName: "file.js", Output: []string{"Array.of()"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "clone-array", Message: "Unnecessarily cloning an array.", Line: 1, Column: 1, EndLine: 1, EndColumn: 16}}},
			{Code: "[...new Array(3)]", FileName: "file.js", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "clone-array", Message: "Unnecessarily cloning an array.", Line: 1, Column: 1, EndLine: 1, EndColumn: 18}}},
			{Code: "[...await Promise.all(foo)]", FileName: "file.js", Output: []string{"(await Promise.all(foo))"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "clone-array", Message: "Unnecessarily cloning an array.", Line: 1, Column: 1, EndLine: 1, EndColumn: 28}}},
			{Code: "[...await Promise.allSettled(foo)]", FileName: "file.js", Output: []string{"(await Promise.allSettled(foo))"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "clone-array", Message: "Unnecessarily cloning an array.", Line: 1, Column: 1, EndLine: 1, EndColumn: 35}}},
			{Code: "function foo(array: number[]) { return [...array.map(value => value * 2)]; }", FileName: "file.ts", Output: []string{"function foo(array: number[]) { return array.map(value => value * 2); }"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "clone-array", Message: "Unnecessarily cloning an array.", Line: 1, Column: 40, EndLine: 1, EndColumn: 74}}},
			{Code: "function foo(array: number[]) { return [...array.filter(Boolean)]; }", FileName: "file.ts", Output: []string{"function foo(array: number[]) { return array.filter(Boolean); }"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "clone-array", Message: "Unnecessarily cloning an array.", Line: 1, Column: 40, EndLine: 1, EndColumn: 66}}},
			{Code: "function foo(array: number[]) { return [...array.flatMap(value => value)]; }", FileName: "file.ts", Output: []string{"function foo(array: number[]) { return array.flatMap(value => value); }"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "clone-array", Message: "Unnecessarily cloning an array.", Line: 1, Column: 40, EndLine: 1, EndColumn: 74}}},
			{Code: "function foo(bar) {\n\treturn[...Object.keys(bar)];\n}", FileName: "file.js", Output: []string{"function foo(bar) {\n\treturn Object.keys(bar);\n}"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "clone-array", Message: "Unnecessarily cloning an array.", Line: 2, Column: 8, EndLine: 2, EndColumn: 29}}},
			{Code: "function foo(bar) {\n\treturn[\n\t\t...Object.keys(bar)\n\t];\n}", FileName: "file.js", Output: []string{"function foo(bar) {\n\treturn (\n\t\tObject.keys(bar)\n\t);\n}"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "clone-array", Message: "Unnecessarily cloning an array.", Line: 2, Column: 8, EndLine: 4, EndColumn: 3}}},
			{Code: "function foo(bar) {\n\treturn[\n\t\t...(\n\t\t\tObject.keys(bar)\n\t\t)\n\t];\n}", FileName: "file.js", Output: []string{"function foo(bar) {\n\treturn (\n\t\t(\n\t\t\tObject.keys(bar)\n\t\t)\n\t);\n}"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "clone-array", Message: "Unnecessarily cloning an array.", Line: 2, Column: 8, EndLine: 6, EndColumn: 3}}},
			{Code: "function foo(bar) {\n\treturn([\n\t\t...Object.keys(bar)\n\t]);\n}", FileName: "file.js", Output: []string{"function foo(bar) {\n\treturn (\n\t\tObject.keys(bar)\n\t);\n}"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "clone-array", Message: "Unnecessarily cloning an array.", Line: 2, Column: 9, EndLine: 4, EndColumn: 3}}},
		})
}

func TestNoUselessSpreadTypeScript(t *testing.T) {
	rule_tester.RunRuleTester(fixtures.GetRootDir(), "tsconfig.json", t, &no_useless_spread.NoUselessSpreadRule,
		[]rule_tester.ValidTestCase{},
		[]rule_tester.InvalidTestCase{
			{Code: "for (const foo of[...iterable2]);", FileName: "file.ts", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "iterable-to-array-in-for-of", Message: "`for…of` can iterate directly when an array snapshot is not needed.", Line: 1, Column: 18, EndLine: 1, EndColumn: 32, Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestion/remove-iterable-to-array", Output: "for (const foo of iterable2);"}}}}},
		})
}

func TestNoUselessSpreadPrecedence(t *testing.T) {
	rule_tester.RunRuleTester(fixtures.GetRootDir(), "tsconfig.json", t, &no_useless_spread.NoUselessSpreadRule,
		[]rule_tester.ValidTestCase{},
		[]rule_tester.InvalidTestCase{
			{Code: "const n = [...await Promise.all(x)].length;", FileName: "file.js", Output: []string{"const n = (await Promise.all(x)).length;"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "clone-array", Message: "Unnecessarily cloning an array.", Line: 1, Column: 11, EndLine: 1, EndColumn: 36}}},
			{Code: "const n = [...await Promise.all(x)][0];", FileName: "file.js", Output: []string{"const n = (await Promise.all(x))[0];"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "clone-array", Message: "Unnecessarily cloning an array.", Line: 1, Column: 11, EndLine: 1, EndColumn: 36}}},
			{Code: "const n = [...await Promise.all(x)].map(f);", FileName: "file.js", Output: []string{"const n = (await Promise.all(x)).map(f);"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "clone-array", Message: "Unnecessarily cloning an array.", Line: 1, Column: 11, EndLine: 1, EndColumn: 36}}},
			{Code: "const n = [...await Promise.all(x)]?.length;", FileName: "file.js", Output: []string{"const n = (await Promise.all(x))?.length;"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "clone-array", Message: "Unnecessarily cloning an array.", Line: 1, Column: 11, EndLine: 1, EndColumn: 36}}},
		})
}

func TestNoUselessSpreadDocumentation(t *testing.T) {
	rule_tester.RunRuleTester(fixtures.GetRootDir(), "tsconfig.json", t, &no_useless_spread.NoUselessSpreadRule,
		[]rule_tester.ValidTestCase{
			{Code: "const array = [firstElement, secondElement, thirdElement];", FileName: "file.js"},
			{Code: "const object = {firstProperty, secondProperty, thirdProperty};", FileName: "file.js"},
			{Code: "foo(firstArgument, secondArgument, thirdArgument);", FileName: "file.js"},
			{Code: "const object = new Foo(firstArgument, secondArgument, thirdArgument);", FileName: "file.js"},
			{Code: "Object.assign(target, source);", FileName: "file.js"},
			{Code: "const set = new Set(iterable);", FileName: "file.js"},
			{Code: "const results = await Promise.all(iterable);", FileName: "file.js"},
			{Code: "for (const foo of set);", FileName: "file.js"},
			{Code: "function * foo() {\n\tyield * anotherGenerator();\n}", FileName: "file.js"},
			{Code: "const array = [...foo, bar];", FileName: "file.js"},
			{Code: "const object = {...foo, bar};", FileName: "file.js"},
			{Code: "foo(foo, ...bar);", FileName: "file.js"},
			{Code: "const object = new Foo(...foo, bar);", FileName: "file.js"},
			{Code: "new Uint8Array([...'ab'])", FileName: "file.js"},
			{Code: "new Uint8Array('ab')", FileName: "file.js"},
		},
		[]rule_tester.InvalidTestCase{
			{Code: "const array = [firstElement, ...[secondElement], thirdElement];", FileName: "file.js", Output: []string{"const array = [firstElement, secondElement, thirdElement];"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an array literal in array literal is unnecessary.", Line: 1, Column: 30, EndLine: 1, EndColumn: 33}}},
			{Code: "const object = {firstProperty, ...{secondProperty}, thirdProperty};", FileName: "file.js", Output: []string{"const object = {firstProperty, secondProperty, thirdProperty};"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an object literal in object literal is unnecessary.", Line: 1, Column: 32, EndLine: 1, EndColumn: 35}}},
			{Code: "foo(firstArgument, ...[secondArgument], thirdArgument);", FileName: "file.js", Output: []string{"foo(firstArgument, secondArgument, thirdArgument);"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an array literal in arguments is unnecessary.", Line: 1, Column: 20, EndLine: 1, EndColumn: 23}}},
			{Code: "const object = new Foo(firstArgument, ...[secondArgument], thirdArgument);", FileName: "file.js", Output: []string{"const object = new Foo(firstArgument, secondArgument, thirdArgument);"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-list", Message: "Spread an array literal in arguments is unnecessary.", Line: 1, Column: 39, EndLine: 1, EndColumn: 42}}},
			{Code: "Object.assign(target, {...source});", FileName: "file.js", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-object-assign", Message: "`Object.assign(…)` source object with only spread properties is unnecessary.", Line: 1, Column: 24, EndLine: 1, EndColumn: 27, Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestion/remove-object-assign-spread", Output: "Object.assign(target, source);"}}}}},
			{Code: "const set = new Set([...iterable]);", FileName: "file.js", Output: []string{"const set = new Set(iterable);"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "iterable-to-array", Message: "`new Set(…)` accepts an iterable as an argument, it's unnecessary to convert to an array.", Line: 1, Column: 21, EndLine: 1, EndColumn: 34}}},
			{Code: "const set = new Set(...iterable);", FileName: "file.js", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spread-in-collection-constructor", Message: "`new Set(…)` accepts a single iterable argument, spreading is misleading.", Line: 1, Column: 21, EndLine: 1, EndColumn: 32}}},
			{Code: "const results = await Promise.all([...iterable]);", FileName: "file.js", Output: []string{"const results = await Promise.all(iterable);"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "iterable-to-array", Message: "`Promise.all(…)` accepts an iterable as an argument, it's unnecessary to convert to an array.", Line: 1, Column: 35, EndLine: 1, EndColumn: 48}}},
			{Code: "for (const foo of [...set]);", FileName: "file.js", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "iterable-to-array-in-for-of", Message: "`for…of` can iterate directly when an array snapshot is not needed.", Line: 1, Column: 19, EndLine: 1, EndColumn: 27, Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestion/remove-iterable-to-array", Output: "for (const foo of set);"}}}}},
			{Code: "function * foo() {\n\tyield * [...anotherGenerator()];\n}", FileName: "file.js", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "iterable-to-array-in-yield-star", Message: "`yield*` can delegate directly when materializing the iterable is unnecessary.", Line: 2, Column: 10, EndLine: 2, EndColumn: 33, Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestion/remove-iterable-to-array", Output: "function * foo() {\n\tyield * anotherGenerator();\n}"}}}}},
		})
}
