// Upstream cases from typescript-eslint v8.70.1.
package array_type

import (
	"testing"

	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/fixtures"
	"github.com/web-infra-dev/rslint/internal/rule_tester"
)

func TestArrayTypeUpstream(t *testing.T) {
	rule_tester.RunRuleTester(fixtures.GetRootDir(), "tsconfig.json", t, &ArrayTypeRule, []rule_tester.ValidTestCase{
		{Code: "let a: number[] = [];", Options: []any{map[string]any{"default": "array"}}},
		{Code: "let a: (string | number)[] = [];", Options: []any{map[string]any{"default": "array"}}},
		{Code: "let a: readonly number[] = [];", Options: []any{map[string]any{"default": "array"}}},
		{Code: "let a: readonly (string | number)[] = [];", Options: []any{map[string]any{"default": "array"}}},
		{Code: "let a: number[] = [];", Options: []any{map[string]any{"default": "array", "readonly": "array"}}},
		{Code: "let a: (string | number)[] = [];", Options: []any{map[string]any{"default": "array", "readonly": "array"}}},
		{Code: "let a: readonly number[] = [];", Options: []any{map[string]any{"default": "array", "readonly": "array"}}},
		{Code: "let a: readonly (string | number)[] = [];", Options: []any{map[string]any{"default": "array", "readonly": "array"}}},
		{Code: "let a: number[] = [];", Options: []any{map[string]any{"default": "array", "readonly": "array-simple"}}},
		{Code: "let a: (string | number)[] = [];", Options: []any{map[string]any{"default": "array", "readonly": "array-simple"}}},
		{Code: "let a: readonly number[] = [];", Options: []any{map[string]any{"default": "array", "readonly": "array-simple"}}},
		{Code: "let a: ReadonlyArray<string | number> = [];", Options: []any{map[string]any{"default": "array", "readonly": "array-simple"}}},
		{Code: "let a: number[] = [];", Options: []any{map[string]any{"default": "array", "readonly": "generic"}}},
		{Code: "let a: (string | number)[] = [];", Options: []any{map[string]any{"default": "array", "readonly": "generic"}}},
		{Code: "let a: ReadonlyArray<number> = [];", Options: []any{map[string]any{"default": "array", "readonly": "generic"}}},
		{Code: "let a: ReadonlyArray<string | number> = [];", Options: []any{map[string]any{"default": "array", "readonly": "generic"}}},
		{Code: "let a: number[] = [];", Options: []any{map[string]any{"default": "array-simple"}}},
		{Code: "let a: Array<string | number> = [];", Options: []any{map[string]any{"default": "array-simple"}}},
		{Code: "let a: readonly number[] = [];", Options: []any{map[string]any{"default": "array-simple"}}},
		{Code: "let a: ReadonlyArray<string | number> = [];", Options: []any{map[string]any{"default": "array-simple"}}},
		{Code: "let a: number[] = [];", Options: []any{map[string]any{"default": "array-simple", "readonly": "array"}}},
		{Code: "let a: Array<string | number> = [];", Options: []any{map[string]any{"default": "array-simple", "readonly": "array"}}},
		{Code: "let a: readonly number[] = [];", Options: []any{map[string]any{"default": "array-simple", "readonly": "array"}}},
		{Code: "let a: readonly (string | number)[] = [];", Options: []any{map[string]any{"default": "array-simple", "readonly": "array"}}},
		{Code: "let a: number[] = [];", Options: []any{map[string]any{"default": "array-simple", "readonly": "array-simple"}}},
		{Code: "let a: Array<string | number> = [];", Options: []any{map[string]any{"default": "array-simple", "readonly": "array-simple"}}},
		{Code: "let a: readonly number[] = [];", Options: []any{map[string]any{"default": "array-simple", "readonly": "array-simple"}}},
		{Code: "let a: ReadonlyArray<string | number> = [];", Options: []any{map[string]any{"default": "array-simple", "readonly": "array-simple"}}},
		{Code: "let a: number[] = [];", Options: []any{map[string]any{"default": "array-simple", "readonly": "generic"}}},
		{Code: "let a: Array<string | number> = [];", Options: []any{map[string]any{"default": "array-simple", "readonly": "generic"}}},
		{Code: "let a: ReadonlyArray<number> = [];", Options: []any{map[string]any{"default": "array-simple", "readonly": "generic"}}},
		{Code: "let a: ReadonlyArray<string | number> = [];", Options: []any{map[string]any{"default": "array-simple", "readonly": "generic"}}},
		{Code: "let a: Array<number> = [];", Options: []any{map[string]any{"default": "generic"}}},
		{Code: "let a: Array<string | number> = [];", Options: []any{map[string]any{"default": "generic"}}},
		{Code: "let a: ReadonlyArray<number> = [];", Options: []any{map[string]any{"default": "generic"}}},
		{Code: "let a: ReadonlyArray<string | number> = [];", Options: []any{map[string]any{"default": "generic"}}},
		{Code: "let a: Array<number> = [];", Options: []any{map[string]any{"default": "generic", "readonly": "generic"}}},
		{Code: "let a: Array<string | number> = [];", Options: []any{map[string]any{"default": "generic", "readonly": "generic"}}},
		{Code: "let a: ReadonlyArray<number> = [];", Options: []any{map[string]any{"default": "generic", "readonly": "generic"}}},
		{Code: "let a: ReadonlyArray<string | number> = [];", Options: []any{map[string]any{"default": "generic", "readonly": "generic"}}},
		{Code: "let a: Array<number> = [];", Options: []any{map[string]any{"default": "generic", "readonly": "array"}}},
		{Code: "let a: Array<string | number> = [];", Options: []any{map[string]any{"default": "generic", "readonly": "array"}}},
		{Code: "let a: readonly number[] = [];", Options: []any{map[string]any{"default": "generic", "readonly": "array"}}},
		{Code: "let a: readonly (string | number)[] = [];", Options: []any{map[string]any{"default": "generic", "readonly": "array"}}},
		{Code: "let a: Array<number> = [];", Options: []any{map[string]any{"default": "generic", "readonly": "array-simple"}}},
		{Code: "let a: Array<string | number> = [];", Options: []any{map[string]any{"default": "generic", "readonly": "array-simple"}}},
		{Code: "let a: readonly number[] = [];", Options: []any{map[string]any{"default": "generic", "readonly": "array-simple"}}},
		{Code: "let a: ReadonlyArray<string | number> = [];", Options: []any{map[string]any{"default": "generic", "readonly": "array-simple"}}},
		{Code: "let a: Array<bigint> = [];", Options: []any{map[string]any{"default": "generic", "readonly": "array"}}},
		{Code: "let a: readonly bigint[] = [];", Options: []any{map[string]any{"default": "generic", "readonly": "array"}}},
		{Code: "let a: readonly (string | bigint)[] = [];", Options: []any{map[string]any{"default": "generic", "readonly": "array"}}},
		{Code: "let a: Array<bigint> = [];", Options: []any{map[string]any{"default": "generic", "readonly": "array-simple"}}},
		{Code: "let a: Array<string | bigint> = [];", Options: []any{map[string]any{"default": "generic", "readonly": "array-simple"}}},
		{Code: "let a: readonly bigint[] = [];", Options: []any{map[string]any{"default": "generic", "readonly": "array-simple"}}},
		{Code: "let a: ReadonlyArray<string | bigint> = [];", Options: []any{map[string]any{"default": "generic", "readonly": "array-simple"}}},
		{Code: "let a = new Array();", Options: []any{map[string]any{"default": "array"}}},
		{Code: "let a: { foo: Bar[] }[] = [];", Options: []any{map[string]any{"default": "array"}}},
		{Code: "function foo(a: Array<Bar>): Array<Bar> {}", Options: []any{map[string]any{"default": "generic"}}},
		{Code: "let yy: number[][] = [[4, 5], [6]];", Options: []any{map[string]any{"default": "array-simple"}}},
		{Code: "\nfunction fooFunction(foo: Array<ArrayClass<string>>) {\n  return foo.map(e => e.foo);\n}\n      ", Options: []any{map[string]any{"default": "array-simple"}}},
		{Code: "\nfunction bazFunction(baz: Arr<ArrayClass<String>>) {\n  return baz.map(e => e.baz);\n}\n      ", Options: []any{map[string]any{"default": "array-simple"}}},
		{Code: "let fooVar: Array<(c: number) => number>;", Options: []any{map[string]any{"default": "array-simple"}}},
		{Code: "type fooUnion = Array<string | number | boolean>;", Options: []any{map[string]any{"default": "array-simple"}}},
		{Code: "type fooIntersection = Array<string & number>;", Options: []any{map[string]any{"default": "array-simple"}}},
		{Code: "\nnamespace fooName {\n  type BarType = { bar: string };\n  type BazType<T> = Arr<T>;\n}\n      ", Options: []any{map[string]any{"default": "array-simple"}}},
		{Code: "\ninterface FooInterface {\n  '.bar': { baz: string[] };\n}\n      ", Options: []any{map[string]any{"default": "array-simple"}}},
		{Code: "let yy: number[][] = [[4, 5], [6]];", Options: []any{map[string]any{"default": "array"}}},
		{Code: "let ya = [[1, '2']] as [number, string][];", Options: []any{map[string]any{"default": "array"}}},
		{Code: "\nfunction barFunction(bar: ArrayClass<String>[]) {\n  return bar.map(e => e.bar);\n}\n      ", Options: []any{map[string]any{"default": "array"}}},
		{Code: "\nfunction bazFunction(baz: Arr<ArrayClass<String>>) {\n  return baz.map(e => e.baz);\n}\n      ", Options: []any{map[string]any{"default": "array"}}},
		{Code: "let barVar: ((c: number) => number)[];", Options: []any{map[string]any{"default": "array"}}},
		{Code: "type barUnion = (string | number | boolean)[];", Options: []any{map[string]any{"default": "array"}}},
		{Code: "type barIntersection = (string & number)[];", Options: []any{map[string]any{"default": "array"}}},
		{Code: "\ninterface FooInterface {\n  '.bar': { baz: string[] };\n}\n      ", Options: []any{map[string]any{"default": "array"}}},
		{Code: "type Unwrap<T> = T extends (infer E)[] ? E : T;", Options: []any{map[string]any{"default": "array"}}},
		{Code: "let xx: Array<Array<number>> = [[1, 2], [3]];", Options: []any{map[string]any{"default": "generic"}}},
		{Code: "type Arr<T> = Array<T>;", Options: []any{map[string]any{"default": "generic"}}},
		{Code: "\nfunction fooFunction(foo: Array<ArrayClass<string>>) {\n  return foo.map(e => e.foo);\n}\n      ", Options: []any{map[string]any{"default": "generic"}}},
		{Code: "\nfunction bazFunction(baz: Arr<ArrayClass<String>>) {\n  return baz.map(e => e.baz);\n}\n      ", Options: []any{map[string]any{"default": "generic"}}},
		{Code: "let fooVar: Array<(c: number) => number>;", Options: []any{map[string]any{"default": "generic"}}},
		{Code: "type fooUnion = Array<string | number | boolean>;", Options: []any{map[string]any{"default": "generic"}}},
		{Code: "type fooIntersection = Array<string & number>;", Options: []any{map[string]any{"default": "generic"}}},
		{Code: "type Unwrap<T> = T extends Array<infer E> ? E : T;", Options: []any{map[string]any{"default": "generic"}}},
		{Code: "let a: ReadonlyArray<number[]> = [[]];", Options: []any{map[string]any{"default": "array", "readonly": "generic"}}},
		{Code: "let a: readonly Array<number>[] = [[]];", Options: []any{map[string]any{"default": "generic", "readonly": "array"}}},
		{Code: "let a: Readonly = [];", Options: []any{map[string]any{"default": "generic", "readonly": "array"}}},
		{Code: "const x: Readonly<string> = 'a';", Options: []any{map[string]any{"default": "array"}}},
		{Code: "type Generic<Array extends unknown[]> = { array: Array };", Options: []any{map[string]any{"default": "array"}}},
		{Code: "type Generic<ReadonlyArray> = { array: ReadonlyArray };", Options: []any{map[string]any{"default": "array"}}},
		{Code: "\ndeclare module '2' {\n  type Array<Y> = Y;\n  const y: Array<2>;\n}\n      ", Options: []any{map[string]any{"default": "generic"}}},
		{Code: "let x: Array;", Options: []any{map[string]any{"default": "array"}}},
		{Code: "let x: Array;", Options: []any{map[string]any{"default": "array-simple"}}},
		{Code: "let z: Array = [3, '4'];", Options: []any{map[string]any{"default": "array"}}},
		{Code: "let z: Array = [3, '4'];", Options: []any{map[string]any{"default": "array-simple"}}},
	}, []rule_tester.InvalidTestCase{
		{Code: "let a: Array<number> = [];", Options: []any{map[string]any{"default": "array"}},
			Output: []string{"let a: number[] = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArray", Message: "Array type using 'Array<number>' is forbidden. Use 'number[]' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 21},
			}},
		{Code: "let a: Array<string | number> = [];", Options: []any{map[string]any{"default": "array"}},
			Output: []string{"let a: (string | number)[] = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArray", Message: "Array type using 'Array<T>' is forbidden. Use 'T[]' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 30},
			}},
		{Code: "let a: ReadonlyArray<number> = [];", Options: []any{map[string]any{"default": "array"}},
			Output: []string{"let a: readonly number[] = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArray", Message: "Array type using 'ReadonlyArray<number>' is forbidden. Use 'readonly number[]' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 29},
			}},
		{Code: "let a: ReadonlyArray<string | number> = [];", Options: []any{map[string]any{"default": "array"}},
			Output: []string{"let a: readonly (string | number)[] = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArray", Message: "Array type using 'ReadonlyArray<T>' is forbidden. Use 'readonly T[]' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 38},
			}},
		{Code: "let a: Array<number> = [];", Options: []any{map[string]any{"default": "array", "readonly": "array"}},
			Output: []string{"let a: number[] = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArray", Message: "Array type using 'Array<number>' is forbidden. Use 'number[]' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 21},
			}},
		{Code: "let a: Array<string | number> = [];", Options: []any{map[string]any{"default": "array", "readonly": "array"}},
			Output: []string{"let a: (string | number)[] = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArray", Message: "Array type using 'Array<T>' is forbidden. Use 'T[]' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 30},
			}},
		{Code: "let a: ReadonlyArray<number> = [];", Options: []any{map[string]any{"default": "array", "readonly": "array"}},
			Output: []string{"let a: readonly number[] = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArray", Message: "Array type using 'ReadonlyArray<number>' is forbidden. Use 'readonly number[]' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 29},
			}},
		{Code: "let a: ReadonlyArray<string | number> = [];", Options: []any{map[string]any{"default": "array", "readonly": "array"}},
			Output: []string{"let a: readonly (string | number)[] = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArray", Message: "Array type using 'ReadonlyArray<T>' is forbidden. Use 'readonly T[]' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 38},
			}},
		{Code: "let a: Array<number> = [];", Options: []any{map[string]any{"default": "array", "readonly": "array-simple"}},
			Output: []string{"let a: number[] = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArray", Message: "Array type using 'Array<number>' is forbidden. Use 'number[]' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 21},
			}},
		{Code: "let a: Array<string | number> = [];", Options: []any{map[string]any{"default": "array", "readonly": "array-simple"}},
			Output: []string{"let a: (string | number)[] = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArray", Message: "Array type using 'Array<T>' is forbidden. Use 'T[]' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 30},
			}},
		{Code: "let a: ReadonlyArray<number> = [];", Options: []any{map[string]any{"default": "array", "readonly": "array-simple"}},
			Output: []string{"let a: readonly number[] = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArraySimple", Message: "Array type using 'ReadonlyArray<number>' is forbidden for simple types. Use 'readonly number[]' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 29},
			}},
		{Code: "let a: readonly (string | number)[] = [];", Options: []any{map[string]any{"default": "array", "readonly": "array-simple"}},
			Output: []string{"let a: ReadonlyArray<string | number> = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGenericSimple", Message: "Array type using 'readonly T[]' is forbidden for non-simple types. Use 'ReadonlyArray<T>' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 36},
			}},
		{Code: "let a: Array<number> = [];", Options: []any{map[string]any{"default": "array", "readonly": "generic"}},
			Output: []string{"let a: number[] = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArray", Message: "Array type using 'Array<number>' is forbidden. Use 'number[]' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 21},
			}},
		{Code: "let a: Array<string | number> = [];", Options: []any{map[string]any{"default": "array", "readonly": "generic"}},
			Output: []string{"let a: (string | number)[] = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArray", Message: "Array type using 'Array<T>' is forbidden. Use 'T[]' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 30},
			}},
		{Code: "let a: readonly number[] = [];", Options: []any{map[string]any{"default": "array", "readonly": "generic"}},
			Output: []string{"let a: ReadonlyArray<number> = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGeneric", Message: "Array type using 'readonly number[]' is forbidden. Use 'ReadonlyArray<number>' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 25},
			}},
		{Code: "let a: readonly (string | number)[] = [];", Options: []any{map[string]any{"default": "array", "readonly": "generic"}},
			Output: []string{"let a: ReadonlyArray<string | number> = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGeneric", Message: "Array type using 'readonly T[]' is forbidden. Use 'ReadonlyArray<T>' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 36},
			}},
		{Code: "let a: Array<number> = [];", Options: []any{map[string]any{"default": "array-simple"}},
			Output: []string{"let a: number[] = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArraySimple", Message: "Array type using 'Array<number>' is forbidden for simple types. Use 'number[]' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 21},
			}},
		{Code: "let a: (string | number)[] = [];", Options: []any{map[string]any{"default": "array-simple"}},
			Output: []string{"let a: Array<string | number> = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGenericSimple", Message: "Array type using 'T[]' is forbidden for non-simple types. Use 'Array<T>' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 27},
			}},
		{Code: "let a: ReadonlyArray<number> = [];", Options: []any{map[string]any{"default": "array-simple"}},
			Output: []string{"let a: readonly number[] = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArraySimple", Message: "Array type using 'ReadonlyArray<number>' is forbidden for simple types. Use 'readonly number[]' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 29},
			}},
		{Code: "let a: readonly (string | number)[] = [];", Options: []any{map[string]any{"default": "array-simple"}},
			Output: []string{"let a: ReadonlyArray<string | number> = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGenericSimple", Message: "Array type using 'readonly T[]' is forbidden for non-simple types. Use 'ReadonlyArray<T>' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 36},
			}},
		{Code: "let a: Array<number> = [];", Options: []any{map[string]any{"default": "array-simple", "readonly": "array"}},
			Output: []string{"let a: number[] = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArraySimple", Message: "Array type using 'Array<number>' is forbidden for simple types. Use 'number[]' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 21},
			}},
		{Code: "let a: (string | number)[] = [];", Options: []any{map[string]any{"default": "array-simple", "readonly": "array"}},
			Output: []string{"let a: Array<string | number> = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGenericSimple", Message: "Array type using 'T[]' is forbidden for non-simple types. Use 'Array<T>' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 27},
			}},
		{Code: "let a: ReadonlyArray<number> = [];", Options: []any{map[string]any{"default": "array-simple", "readonly": "array"}},
			Output: []string{"let a: readonly number[] = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArray", Message: "Array type using 'ReadonlyArray<number>' is forbidden. Use 'readonly number[]' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 29},
			}},
		{Code: "let a: ReadonlyArray<string | number> = [];", Options: []any{map[string]any{"default": "array-simple", "readonly": "array"}},
			Output: []string{"let a: readonly (string | number)[] = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArray", Message: "Array type using 'ReadonlyArray<T>' is forbidden. Use 'readonly T[]' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 38},
			}},
		{Code: "let a: Array<number> = [];", Options: []any{map[string]any{"default": "array-simple", "readonly": "array-simple"}},
			Output: []string{"let a: number[] = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArraySimple", Message: "Array type using 'Array<number>' is forbidden for simple types. Use 'number[]' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 21},
			}},
		{Code: "let a: (string | number)[] = [];", Options: []any{map[string]any{"default": "array-simple", "readonly": "array-simple"}},
			Output: []string{"let a: Array<string | number> = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGenericSimple", Message: "Array type using 'T[]' is forbidden for non-simple types. Use 'Array<T>' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 27},
			}},
		{Code: "let a: ReadonlyArray<number> = [];", Options: []any{map[string]any{"default": "array-simple", "readonly": "array-simple"}},
			Output: []string{"let a: readonly number[] = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArraySimple", Message: "Array type using 'ReadonlyArray<number>' is forbidden for simple types. Use 'readonly number[]' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 29},
			}},
		{Code: "let a: readonly (string | number)[] = [];", Options: []any{map[string]any{"default": "array-simple", "readonly": "array-simple"}},
			Output: []string{"let a: ReadonlyArray<string | number> = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGenericSimple", Message: "Array type using 'readonly T[]' is forbidden for non-simple types. Use 'ReadonlyArray<T>' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 36},
			}},
		{Code: "let a: Array<number> = [];", Options: []any{map[string]any{"default": "array-simple", "readonly": "generic"}},
			Output: []string{"let a: number[] = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArraySimple", Message: "Array type using 'Array<number>' is forbidden for simple types. Use 'number[]' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 21},
			}},
		{Code: "let a: (string | number)[] = [];", Options: []any{map[string]any{"default": "array-simple", "readonly": "generic"}},
			Output: []string{"let a: Array<string | number> = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGenericSimple", Message: "Array type using 'T[]' is forbidden for non-simple types. Use 'Array<T>' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 27},
			}},
		{Code: "let a: readonly number[] = [];", Options: []any{map[string]any{"default": "array-simple", "readonly": "generic"}},
			Output: []string{"let a: ReadonlyArray<number> = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGeneric", Message: "Array type using 'readonly number[]' is forbidden. Use 'ReadonlyArray<number>' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 25},
			}},
		{Code: "let a: readonly (string | number)[] = [];", Options: []any{map[string]any{"default": "array-simple", "readonly": "generic"}},
			Output: []string{"let a: ReadonlyArray<string | number> = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGeneric", Message: "Array type using 'readonly T[]' is forbidden. Use 'ReadonlyArray<T>' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 36},
			}},
		{Code: "let a: number[] = [];", Options: []any{map[string]any{"default": "generic"}},
			Output: []string{"let a: Array<number> = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGeneric", Message: "Array type using 'number[]' is forbidden. Use 'Array<number>' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 16},
			}},
		{Code: "let a: (string | number)[] = [];", Options: []any{map[string]any{"default": "generic"}},
			Output: []string{"let a: Array<string | number> = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGeneric", Message: "Array type using 'T[]' is forbidden. Use 'Array<T>' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 27},
			}},
		{Code: "let a: readonly number[] = [];", Options: []any{map[string]any{"default": "generic"}},
			Output: []string{"let a: ReadonlyArray<number> = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGeneric", Message: "Array type using 'readonly number[]' is forbidden. Use 'ReadonlyArray<number>' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 25},
			}},
		{Code: "let a: readonly (string | number)[] = [];", Options: []any{map[string]any{"default": "generic"}},
			Output: []string{"let a: ReadonlyArray<string | number> = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGeneric", Message: "Array type using 'readonly T[]' is forbidden. Use 'ReadonlyArray<T>' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 36},
			}},
		{Code: "let a: number[] = [];", Options: []any{map[string]any{"default": "generic", "readonly": "array"}},
			Output: []string{"let a: Array<number> = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGeneric", Message: "Array type using 'number[]' is forbidden. Use 'Array<number>' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 16},
			}},
		{Code: "let a: (string | number)[] = [];", Options: []any{map[string]any{"default": "generic", "readonly": "array"}},
			Output: []string{"let a: Array<string | number> = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGeneric", Message: "Array type using 'T[]' is forbidden. Use 'Array<T>' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 27},
			}},
		{Code: "let a: ReadonlyArray<number> = [];", Options: []any{map[string]any{"default": "generic", "readonly": "array"}},
			Output: []string{"let a: readonly number[] = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArray", Message: "Array type using 'ReadonlyArray<number>' is forbidden. Use 'readonly number[]' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 29},
			}},
		{Code: "let a: ReadonlyArray<string | number> = [];", Options: []any{map[string]any{"default": "generic", "readonly": "array"}},
			Output: []string{"let a: readonly (string | number)[] = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArray", Message: "Array type using 'ReadonlyArray<T>' is forbidden. Use 'readonly T[]' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 38},
			}},
		{Code: "let a: number[] = [];", Options: []any{map[string]any{"default": "generic", "readonly": "array-simple"}},
			Output: []string{"let a: Array<number> = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGeneric", Message: "Array type using 'number[]' is forbidden. Use 'Array<number>' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 16},
			}},
		{Code: "let a: (string | number)[] = [];", Options: []any{map[string]any{"default": "generic", "readonly": "array-simple"}},
			Output: []string{"let a: Array<string | number> = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGeneric", Message: "Array type using 'T[]' is forbidden. Use 'Array<T>' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 27},
			}},
		{Code: "let a: ReadonlyArray<number> = [];", Options: []any{map[string]any{"default": "generic", "readonly": "array-simple"}},
			Output: []string{"let a: readonly number[] = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArraySimple", Message: "Array type using 'ReadonlyArray<number>' is forbidden for simple types. Use 'readonly number[]' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 29},
			}},
		{Code: "let a: readonly (string | number)[] = [];", Options: []any{map[string]any{"default": "generic", "readonly": "array-simple"}},
			Output: []string{"let a: ReadonlyArray<string | number> = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGenericSimple", Message: "Array type using 'readonly T[]' is forbidden for non-simple types. Use 'ReadonlyArray<T>' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 36},
			}},
		{Code: "let a: number[] = [];", Options: []any{map[string]any{"default": "generic", "readonly": "generic"}},
			Output: []string{"let a: Array<number> = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGeneric", Message: "Array type using 'number[]' is forbidden. Use 'Array<number>' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 16},
			}},
		{Code: "let a: (string | number)[] = [];", Options: []any{map[string]any{"default": "generic", "readonly": "generic"}},
			Output: []string{"let a: Array<string | number> = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGeneric", Message: "Array type using 'T[]' is forbidden. Use 'Array<T>' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 27},
			}},
		{Code: "let a: readonly number[] = [];", Options: []any{map[string]any{"default": "generic", "readonly": "generic"}},
			Output: []string{"let a: ReadonlyArray<number> = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGeneric", Message: "Array type using 'readonly number[]' is forbidden. Use 'ReadonlyArray<number>' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 25},
			}},
		{Code: "let a: readonly (string | number)[] = [];", Options: []any{map[string]any{"default": "generic", "readonly": "generic"}},
			Output: []string{"let a: ReadonlyArray<string | number> = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGeneric", Message: "Array type using 'readonly T[]' is forbidden. Use 'ReadonlyArray<T>' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 36},
			}},
		{Code: "let a: bigint[] = [];", Options: []any{map[string]any{"default": "generic", "readonly": "array-simple"}},
			Output: []string{"let a: Array<bigint> = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGeneric", Message: "Array type using 'bigint[]' is forbidden. Use 'Array<bigint>' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 16},
			}},
		{Code: "let a: (string | bigint)[] = [];", Options: []any{map[string]any{"default": "generic", "readonly": "array-simple"}},
			Output: []string{"let a: Array<string | bigint> = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGeneric", Message: "Array type using 'T[]' is forbidden. Use 'Array<T>' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 27},
			}},
		{Code: "let a: ReadonlyArray<bigint> = [];", Options: []any{map[string]any{"default": "generic", "readonly": "array-simple"}},
			Output: []string{"let a: readonly bigint[] = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArraySimple", Message: "Array type using 'ReadonlyArray<bigint>' is forbidden for simple types. Use 'readonly bigint[]' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 29},
			}},
		{Code: "let a: (string | bigint)[] = [];", Options: []any{map[string]any{"default": "generic", "readonly": "generic"}},
			Output: []string{"let a: Array<string | bigint> = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGeneric", Message: "Array type using 'T[]' is forbidden. Use 'Array<T>' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 27},
			}},
		{Code: "let a: readonly bigint[] = [];", Options: []any{map[string]any{"default": "generic", "readonly": "generic"}},
			Output: []string{"let a: ReadonlyArray<bigint> = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGeneric", Message: "Array type using 'readonly bigint[]' is forbidden. Use 'ReadonlyArray<bigint>' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 25},
			}},
		{Code: "let a: readonly (string | bigint)[] = [];", Options: []any{map[string]any{"default": "generic", "readonly": "generic"}},
			Output: []string{"let a: ReadonlyArray<string | bigint> = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGeneric", Message: "Array type using 'readonly T[]' is forbidden. Use 'ReadonlyArray<T>' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 36},
			}},
		{Code: "let a: { foo: Array<Bar> }[] = [];", Options: []any{map[string]any{"default": "array"}},
			Output: []string{"let a: { foo: Bar[] }[] = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArray", Message: "Array type using 'Array<Bar>' is forbidden. Use 'Bar[]' instead.", Line: 1, Column: 15, EndLine: 1, EndColumn: 25},
			}},
		{Code: "let a: Array<{ foo: Bar[] }> = [];", Options: []any{map[string]any{"default": "generic"}},
			Output: []string{"let a: Array<{ foo: Array<Bar> }> = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGeneric", Message: "Array type using 'Bar[]' is forbidden. Use 'Array<Bar>' instead.", Line: 1, Column: 21, EndLine: 1, EndColumn: 26},
			}},
		{Code: "let a: Array<{ foo: Foo | Bar[] }> = [];", Options: []any{map[string]any{"default": "generic"}},
			Output: []string{"let a: Array<{ foo: Foo | Array<Bar> }> = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGeneric", Message: "Array type using 'Bar[]' is forbidden. Use 'Array<Bar>' instead.", Line: 1, Column: 27, EndLine: 1, EndColumn: 32},
			}},
		{Code: "function foo(a: Array<Bar>): Array<Bar> {}", Options: []any{map[string]any{"default": "array"}},
			Output: []string{"function foo(a: Bar[]): Bar[] {}"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArray", Message: "Array type using 'Array<Bar>' is forbidden. Use 'Bar[]' instead.", Line: 1, Column: 17, EndLine: 1, EndColumn: 27},
				{MessageId: "errorStringArray", Message: "Array type using 'Array<Bar>' is forbidden. Use 'Bar[]' instead.", Line: 1, Column: 30, EndLine: 1, EndColumn: 40},
			}},
		{Code: "let x: Array<undefined> = [undefined] as undefined[];", Options: []any{map[string]any{"default": "array-simple"}},
			Output: []string{"let x: undefined[] = [undefined] as undefined[];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArraySimple", Message: "Array type using 'Array<undefined>' is forbidden for simple types. Use 'undefined[]' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 24},
			}},
		{Code: "let y: string[] = <Array<string>>['2'];", Options: []any{map[string]any{"default": "array-simple"}},
			Output: []string{"let y: string[] = <string[]>['2'];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArraySimple", Message: "Array type using 'Array<string>' is forbidden for simple types. Use 'string[]' instead.", Line: 1, Column: 20, EndLine: 1, EndColumn: 33},
			}},
		{Code: "let ya = [[1, '2']] as [number, string][];", Options: []any{map[string]any{"default": "array-simple"}},
			Output: []string{"let ya = [[1, '2']] as Array<[number, string]>;"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGenericSimple", Message: "Array type using 'T[]' is forbidden for non-simple types. Use 'Array<T>' instead.", Line: 1, Column: 24, EndLine: 1, EndColumn: 42},
			}},
		{Code: "type Arr<T> = Array<T>;", Options: []any{map[string]any{"default": "array-simple"}},
			Output: []string{"type Arr<T> = T[];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArraySimple", Message: "Array type using 'Array<T>' is forbidden for simple types. Use 'T[]' instead.", Line: 1, Column: 15, EndLine: 1, EndColumn: 23},
			}},
		{Code: "\n// Ignore user defined aliases\nlet yyyy: Arr<Array<Arr<string>>[]> = [[[['2']]]];\n      ", Options: []any{map[string]any{"default": "array-simple"}},
			Output: []string{"\n// Ignore user defined aliases\nlet yyyy: Arr<Array<Array<Arr<string>>>> = [[[['2']]]];\n      "},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGenericSimple", Message: "Array type using 'T[]' is forbidden for non-simple types. Use 'Array<T>' instead.", Line: 3, Column: 15, EndLine: 3, EndColumn: 35},
			}},
		{Code: "\ninterface ArrayClass<T> {\n  foo: Array<T>;\n  bar: T[];\n  baz: Arr<T>;\n  xyz: this[];\n}\n      ", Options: []any{map[string]any{"default": "array-simple"}},
			Output: []string{"\ninterface ArrayClass<T> {\n  foo: T[];\n  bar: T[];\n  baz: Arr<T>;\n  xyz: this[];\n}\n      "},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArraySimple", Message: "Array type using 'Array<T>' is forbidden for simple types. Use 'T[]' instead.", Line: 3, Column: 8, EndLine: 3, EndColumn: 16},
			}},
		{Code: "\nfunction barFunction(bar: ArrayClass<String>[]) {\n  return bar.map(e => e.bar);\n}\n      ", Options: []any{map[string]any{"default": "array-simple"}},
			Output: []string{"\nfunction barFunction(bar: Array<ArrayClass<String>>) {\n  return bar.map(e => e.bar);\n}\n      "},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGenericSimple", Message: "Array type using 'T[]' is forbidden for non-simple types. Use 'Array<T>' instead.", Line: 2, Column: 27, EndLine: 2, EndColumn: 47},
			}},
		{Code: "let barVar: ((c: number) => number)[];", Options: []any{map[string]any{"default": "array-simple"}},
			Output: []string{"let barVar: Array<(c: number) => number>;"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGenericSimple", Message: "Array type using 'T[]' is forbidden for non-simple types. Use 'Array<T>' instead.", Line: 1, Column: 13, EndLine: 1, EndColumn: 38},
			}},
		{Code: "type barUnion = (string | number | boolean)[];", Options: []any{map[string]any{"default": "array-simple"}},
			Output: []string{"type barUnion = Array<string | number | boolean>;"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGenericSimple", Message: "Array type using 'T[]' is forbidden for non-simple types. Use 'Array<T>' instead.", Line: 1, Column: 17, EndLine: 1, EndColumn: 46},
			}},
		{Code: "type barIntersection = (string & number)[];", Options: []any{map[string]any{"default": "array-simple"}},
			Output: []string{"type barIntersection = Array<string & number>;"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGenericSimple", Message: "Array type using 'T[]' is forbidden for non-simple types. Use 'Array<T>' instead.", Line: 1, Column: 24, EndLine: 1, EndColumn: 43},
			}},
		{Code: "let v: Array<fooName.BarType> = [{ bar: 'bar' }];", Options: []any{map[string]any{"default": "array-simple"}},
			Output: []string{"let v: fooName.BarType[] = [{ bar: 'bar' }];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArraySimple", Message: "Array type using 'Array<fooName.BarType>' is forbidden for simple types. Use 'fooName.BarType[]' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 30},
			}},
		{Code: "let w: fooName.BazType<string>[] = [['baz']];", Options: []any{map[string]any{"default": "array-simple"}},
			Output: []string{"let w: Array<fooName.BazType<string>> = [['baz']];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGenericSimple", Message: "Array type using 'T[]' is forbidden for non-simple types. Use 'Array<T>' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 33},
			}},
		{Code: "let x: Array<undefined> = [undefined] as undefined[];", Options: []any{map[string]any{"default": "array"}},
			Output: []string{"let x: undefined[] = [undefined] as undefined[];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArray", Message: "Array type using 'Array<undefined>' is forbidden. Use 'undefined[]' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 24},
			}},
		{Code: "let y: string[] = <Array<string>>['2'];", Options: []any{map[string]any{"default": "array"}},
			Output: []string{"let y: string[] = <string[]>['2'];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArray", Message: "Array type using 'Array<string>' is forbidden. Use 'string[]' instead.", Line: 1, Column: 20, EndLine: 1, EndColumn: 33},
			}},
		{Code: "type Arr<T> = Array<T>;", Options: []any{map[string]any{"default": "array"}},
			Output: []string{"type Arr<T> = T[];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArray", Message: "Array type using 'Array<T>' is forbidden. Use 'T[]' instead.", Line: 1, Column: 15, EndLine: 1, EndColumn: 23},
			}},
		{Code: "\n// Ignore user defined aliases\nlet yyyy: Arr<Array<Arr<string>>[]> = [[[['2']]]];\n      ", Options: []any{map[string]any{"default": "array"}},
			Output: []string{"\n// Ignore user defined aliases\nlet yyyy: Arr<Arr<string>[][]> = [[[['2']]]];\n      "},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArray", Message: "Array type using 'Array<T>' is forbidden. Use 'T[]' instead.", Line: 3, Column: 15, EndLine: 3, EndColumn: 33},
			}},
		{Code: "\ninterface ArrayClass<T> {\n  foo: Array<T>;\n  bar: T[];\n  baz: Arr<T>;\n}\n      ", Options: []any{map[string]any{"default": "array"}},
			Output: []string{"\ninterface ArrayClass<T> {\n  foo: T[];\n  bar: T[];\n  baz: Arr<T>;\n}\n      "},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArray", Message: "Array type using 'Array<T>' is forbidden. Use 'T[]' instead.", Line: 3, Column: 8, EndLine: 3, EndColumn: 16},
			}},
		{Code: "\nfunction fooFunction(foo: Array<ArrayClass<string>>) {\n  return foo.map(e => e.foo);\n}\n      ", Options: []any{map[string]any{"default": "array"}},
			Output: []string{"\nfunction fooFunction(foo: ArrayClass<string>[]) {\n  return foo.map(e => e.foo);\n}\n      "},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArray", Message: "Array type using 'Array<T>' is forbidden. Use 'T[]' instead.", Line: 2, Column: 27, EndLine: 2, EndColumn: 52},
			}},
		{Code: "let fooVar: Array<(c: number) => number>;", Options: []any{map[string]any{"default": "array"}},
			Output: []string{"let fooVar: ((c: number) => number)[];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArray", Message: "Array type using 'Array<T>' is forbidden. Use 'T[]' instead.", Line: 1, Column: 13, EndLine: 1, EndColumn: 41},
			}},
		{Code: "type fooUnion = Array<string | number | boolean>;", Options: []any{map[string]any{"default": "array"}},
			Output: []string{"type fooUnion = (string | number | boolean)[];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArray", Message: "Array type using 'Array<T>' is forbidden. Use 'T[]' instead.", Line: 1, Column: 17, EndLine: 1, EndColumn: 49},
			}},
		{Code: "type fooIntersection = Array<string & number>;", Options: []any{map[string]any{"default": "array"}},
			Output: []string{"type fooIntersection = (string & number)[];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArray", Message: "Array type using 'Array<T>' is forbidden. Use 'T[]' instead.", Line: 1, Column: 24, EndLine: 1, EndColumn: 46},
			}},
		{Code: "let x: Array<number> = [1] as number[];", Options: []any{map[string]any{"default": "generic"}},
			Output: []string{"let x: Array<number> = [1] as Array<number>;"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGeneric", Message: "Array type using 'number[]' is forbidden. Use 'Array<number>' instead.", Line: 1, Column: 31, EndLine: 1, EndColumn: 39},
			}},
		{Code: "let y: string[] = <Array<string>>['2'];", Options: []any{map[string]any{"default": "generic"}},
			Output: []string{"let y: Array<string> = <Array<string>>['2'];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGeneric", Message: "Array type using 'string[]' is forbidden. Use 'Array<string>' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 16},
			}},
		{Code: "let ya = [[1, '2']] as [number, string][];", Options: []any{map[string]any{"default": "generic"}},
			Output: []string{"let ya = [[1, '2']] as Array<[number, string]>;"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGeneric", Message: "Array type using 'T[]' is forbidden. Use 'Array<T>' instead.", Line: 1, Column: 24, EndLine: 1, EndColumn: 42},
			}},
		{Code: "\n// Ignore user defined aliases\nlet yyyy: Arr<Array<Arr<string>>[]> = [[[['2']]]];\n      ", Options: []any{map[string]any{"default": "generic"}},
			Output: []string{"\n// Ignore user defined aliases\nlet yyyy: Arr<Array<Array<Arr<string>>>> = [[[['2']]]];\n      "},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGeneric", Message: "Array type using 'T[]' is forbidden. Use 'Array<T>' instead.", Line: 3, Column: 15, EndLine: 3, EndColumn: 35},
			}},
		{Code: "\ninterface ArrayClass<T> {\n  foo: Array<T>;\n  bar: T[];\n  baz: Arr<T>;\n}\n      ", Options: []any{map[string]any{"default": "generic"}},
			Output: []string{"\ninterface ArrayClass<T> {\n  foo: Array<T>;\n  bar: Array<T>;\n  baz: Arr<T>;\n}\n      "},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGeneric", Message: "Array type using 'T[]' is forbidden. Use 'Array<T>' instead.", Line: 4, Column: 8, EndLine: 4, EndColumn: 11},
			}},
		{Code: "\nfunction barFunction(bar: ArrayClass<String>[]) {\n  return bar.map(e => e.bar);\n}\n      ", Options: []any{map[string]any{"default": "generic"}},
			Output: []string{"\nfunction barFunction(bar: Array<ArrayClass<String>>) {\n  return bar.map(e => e.bar);\n}\n      "},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGeneric", Message: "Array type using 'T[]' is forbidden. Use 'Array<T>' instead.", Line: 2, Column: 27, EndLine: 2, EndColumn: 47},
			}},
		{Code: "let barVar: ((c: number) => number)[];", Options: []any{map[string]any{"default": "generic"}},
			Output: []string{"let barVar: Array<(c: number) => number>;"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGeneric", Message: "Array type using 'T[]' is forbidden. Use 'Array<T>' instead.", Line: 1, Column: 13, EndLine: 1, EndColumn: 38},
			}},
		{Code: "type barUnion = (string | number | boolean)[];", Options: []any{map[string]any{"default": "generic"}},
			Output: []string{"type barUnion = Array<string | number | boolean>;"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGeneric", Message: "Array type using 'T[]' is forbidden. Use 'Array<T>' instead.", Line: 1, Column: 17, EndLine: 1, EndColumn: 46},
			}},
		{Code: "type barIntersection = (string & number)[];", Options: []any{map[string]any{"default": "generic"}},
			Output: []string{"type barIntersection = Array<string & number>;"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGeneric", Message: "Array type using 'T[]' is forbidden. Use 'Array<T>' instead.", Line: 1, Column: 24, EndLine: 1, EndColumn: 43},
			}},
		{Code: "\ninterface FooInterface {\n  '.bar': { baz: string[] };\n}\n      ", Options: []any{map[string]any{"default": "generic"}},
			Output: []string{"\ninterface FooInterface {\n  '.bar': { baz: Array<string> };\n}\n      "},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGeneric", Message: "Array type using 'string[]' is forbidden. Use 'Array<string>' instead.", Line: 3, Column: 18, EndLine: 3, EndColumn: 26},
			}},
		{Code: "type Unwrap<T> = T extends Array<infer E> ? E : T;", Options: []any{map[string]any{"default": "array"}},
			Output: []string{"type Unwrap<T> = T extends (infer E)[] ? E : T;"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArray", Message: "Array type using 'Array<T>' is forbidden. Use 'T[]' instead.", Line: 1, Column: 28, EndLine: 1, EndColumn: 42},
			}},
		{Code: "type Unwrap<T> = T extends (infer E)[] ? E : T;", Options: []any{map[string]any{"default": "generic"}},
			Output: []string{"type Unwrap<T> = T extends Array<infer E> ? E : T;"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGeneric", Message: "Array type using 'T[]' is forbidden. Use 'Array<T>' instead.", Line: 1, Column: 28, EndLine: 1, EndColumn: 39},
			}},
		{Code: "type Foo = ReadonlyArray<object>[];", Options: []any{map[string]any{"default": "array"}},
			Output: []string{"type Foo = (readonly object[])[];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArray", Message: "Array type using 'ReadonlyArray<object>' is forbidden. Use 'readonly object[]' instead.", Line: 1, Column: 12, EndLine: 1, EndColumn: 33},
			}},
		{Code: "const foo: Array<new (...args: any[]) => void> = [];", Options: []any{map[string]any{"default": "array"}},
			Output: []string{"const foo: (new (...args: any[]) => void)[] = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArray", Message: "Array type using 'Array<T>' is forbidden. Use 'T[]' instead.", Line: 1, Column: 12, EndLine: 1, EndColumn: 47},
			}},
		{Code: "const foo: ReadonlyArray<new (...args: any[]) => void> = [];", Options: []any{map[string]any{"default": "array"}},
			Output: []string{"const foo: readonly (new (...args: any[]) => void)[] = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArray", Message: "Array type using 'ReadonlyArray<T>' is forbidden. Use 'readonly T[]' instead.", Line: 1, Column: 12, EndLine: 1, EndColumn: 55},
			}},
		{Code: "const x: Readonly<string[]> = ['a', 'b'];", Options: []any{map[string]any{"default": "array"}},
			Output: []string{"const x: readonly string[] = ['a', 'b'];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArrayReadonly", Message: "Array type using 'Readonly<string[]>' is forbidden. Use 'readonly string[]' instead.", Line: 1, Column: 10, EndLine: 1, EndColumn: 28},
			}},
		{Code: "declare function foo<E extends Readonly<string[]>>(extra: E): E;", Options: []any{map[string]any{"default": "array-simple"}},
			Output: []string{"declare function foo<E extends readonly string[]>(extra: E): E;"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArraySimpleReadonly", Message: "Array type using 'Readonly<string[]>' is forbidden for simple types. Use 'readonly string[]' instead.", Line: 1, Column: 32, EndLine: 1, EndColumn: 50},
			}},
		{Code: "type Conditional<T> = Array<T extends string ? string : number>;", Options: []any{map[string]any{"default": "array"}},
			Output: []string{"type Conditional<T> = (T extends string ? string : number)[];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArray", Message: "Array type using 'Array<T>' is forbidden. Use 'T[]' instead.", Line: 1, Column: 23, EndLine: 1, EndColumn: 64},
			}},
		{Code: "type Conditional<T> = (T extends string ? string : number)[];", Options: []any{map[string]any{"default": "array-simple"}},
			Output: []string{"type Conditional<T> = Array<T extends string ? string : number>;"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGenericSimple", Message: "Array type using 'T[]' is forbidden for non-simple types. Use 'Array<T>' instead.", Line: 1, Column: 23, EndLine: 1, EndColumn: 61},
			}},
		{Code: "type Conditional<T> = (T extends string ? string : number)[];", Options: []any{map[string]any{"default": "generic"}},
			Output: []string{"type Conditional<T> = Array<T extends string ? string : number>;"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGeneric", Message: "Array type using 'T[]' is forbidden. Use 'Array<T>' instead.", Line: 1, Column: 23, EndLine: 1, EndColumn: 61},
			}},
		{Code: "let a: ({ foo: Array<Array<Bar> | Array<any>> })[] = []", Options: []any{map[string]any{"default": "array"}},
			Output: []string{"let a: ({ foo: (Array<Bar> | Array<any>)[] })[] = []", "let a: ({ foo: (Bar[] | any[])[] })[] = []"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArray", Message: "Array type using 'Array<T>' is forbidden. Use 'T[]' instead.", Line: 1, Column: 16, EndLine: 1, EndColumn: 46},
				{MessageId: "errorStringArray", Message: "Array type using 'Array<Bar>' is forbidden. Use 'Bar[]' instead.", Line: 1, Column: 22, EndLine: 1, EndColumn: 32},
				{MessageId: "errorStringArray", Message: "Array type using 'Array<any>' is forbidden. Use 'any[]' instead.", Line: 1, Column: 35, EndLine: 1, EndColumn: 45},
			}},
		{Code: "\nclass Foo<T = Array<Array<Bar>>> extends Bar<T, Array<T>> implements Baz<Array<T>> {\n    private s: Array<T>\n\n    constructor (p: Array<T>) {\n        return new Array()\n    }\n}\n      ", Options: []any{map[string]any{"default": "array"}},
			Output: []string{"\nclass Foo<T = Array<Bar>[]> extends Bar<T, T[]> implements Baz<T[]> {\n    private s: T[]\n\n    constructor (p: T[]) {\n        return new Array()\n    }\n}\n      ", "\nclass Foo<T = Bar[][]> extends Bar<T, T[]> implements Baz<T[]> {\n    private s: T[]\n\n    constructor (p: T[]) {\n        return new Array()\n    }\n}\n      "},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArray", Message: "Array type using 'Array<Array<Bar>>' is forbidden. Use 'Array<Bar>[]' instead.", Line: 2, Column: 15, EndLine: 2, EndColumn: 32},
				{MessageId: "errorStringArray", Message: "Array type using 'Array<Bar>' is forbidden. Use 'Bar[]' instead.", Line: 2, Column: 21, EndLine: 2, EndColumn: 31},
				{MessageId: "errorStringArray", Message: "Array type using 'Array<T>' is forbidden. Use 'T[]' instead.", Line: 2, Column: 49, EndLine: 2, EndColumn: 57},
				{MessageId: "errorStringArray", Message: "Array type using 'Array<T>' is forbidden. Use 'T[]' instead.", Line: 2, Column: 74, EndLine: 2, EndColumn: 82},
				{MessageId: "errorStringArray", Message: "Array type using 'Array<T>' is forbidden. Use 'T[]' instead.", Line: 3, Column: 16, EndLine: 3, EndColumn: 24},
				{MessageId: "errorStringArray", Message: "Array type using 'Array<T>' is forbidden. Use 'T[]' instead.", Line: 5, Column: 21, EndLine: 5, EndColumn: 29},
			}},
		{Code: "\ninterface WorkingArray {\n  outerProperty: Array<\n    { innerPropertyOne: string } & { innerPropertyTwo: string }\n  >;\n}\n\ninterface BrokenArray {\n  outerProperty: Array<\n    ({ innerPropertyOne: string } & { innerPropertyTwo: string })\n  >;\n}\n      ", Options: []any{map[string]any{"default": "array"}},
			Output: []string{"\ninterface WorkingArray {\n  outerProperty: ({ innerPropertyOne: string } & { innerPropertyTwo: string })[];\n}\n\ninterface BrokenArray {\n  outerProperty: ({ innerPropertyOne: string } & { innerPropertyTwo: string })[];\n}\n      "},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArray", Message: "Array type using 'Array<T>' is forbidden. Use 'T[]' instead.", Line: 3, Column: 18, EndLine: 5, EndColumn: 4},
				{MessageId: "errorStringArray", Message: "Array type using 'Array<T>' is forbidden. Use 'T[]' instead.", Line: 9, Column: 18, EndLine: 11, EndColumn: 4},
			}},
		{Code: "\ntype WorkingArray = {\n  outerProperty: Array<\n    { innerPropertyOne: string } & { innerPropertyTwo: string }\n  >;\n}\n\ntype BrokenArray = {\n  outerProperty: Array<\n    ({ innerPropertyOne: string } & { innerPropertyTwo: string })\n  >;\n}\n      ", Options: []any{map[string]any{"default": "array"}},
			Output: []string{"\ntype WorkingArray = {\n  outerProperty: ({ innerPropertyOne: string } & { innerPropertyTwo: string })[];\n}\n\ntype BrokenArray = {\n  outerProperty: ({ innerPropertyOne: string } & { innerPropertyTwo: string })[];\n}\n      "},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArray", Message: "Array type using 'Array<T>' is forbidden. Use 'T[]' instead.", Line: 3, Column: 18, EndLine: 5, EndColumn: 4},
				{MessageId: "errorStringArray", Message: "Array type using 'Array<T>' is forbidden. Use 'T[]' instead.", Line: 9, Column: 18, EndLine: 11, EndColumn: 4},
			}},
		{Code: "const a: Array<(string|number)>;", Options: []any{map[string]any{"default": "array"}},
			Output: []string{"const a: (string|number)[];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArray", Message: "Array type using 'Array<T>' is forbidden. Use 'T[]' instead.", Line: 1, Column: 10, EndLine: 1, EndColumn: 32},
			}},
		{Code: "let xx: Array<Array<number>> = [[1, 2], [3]];", Options: []any{map[string]any{"default": "array-simple"}},
			Output: []string{"let xx: Array<number>[] = [[1, 2], [3]];", "let xx: number[][] = [[1, 2], [3]];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArraySimple", Message: "Array type using 'Array<Array<number>>' is forbidden for simple types. Use 'Array<number>[]' instead.", Line: 1, Column: 9, EndLine: 1, EndColumn: 29},
				{MessageId: "errorStringArraySimple", Message: "Array type using 'Array<number>' is forbidden for simple types. Use 'number[]' instead.", Line: 1, Column: 15, EndLine: 1, EndColumn: 28},
			}},
		{Code: "let xx: Array<Array<number>> = [[1, 2], [3]];", Options: []any{map[string]any{"default": "array"}},
			Output: []string{"let xx: Array<number>[] = [[1, 2], [3]];", "let xx: number[][] = [[1, 2], [3]];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArray", Message: "Array type using 'Array<Array<number>>' is forbidden. Use 'Array<number>[]' instead.", Line: 1, Column: 9, EndLine: 1, EndColumn: 29},
				{MessageId: "errorStringArray", Message: "Array type using 'Array<number>' is forbidden. Use 'number[]' instead.", Line: 1, Column: 15, EndLine: 1, EndColumn: 28},
			}},
		{Code: "let yy: number[][] = [[4, 5], [6]];", Options: []any{map[string]any{"default": "generic"}},
			Output: []string{"let yy: Array<number>[] = [[4, 5], [6]];", "let yy: Array<Array<number>> = [[4, 5], [6]];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGeneric", Message: "Array type using 'number[][]' is forbidden. Use 'Array<number[]>' instead.", Line: 1, Column: 9, EndLine: 1, EndColumn: 19},
				{MessageId: "errorStringGeneric", Message: "Array type using 'number[]' is forbidden. Use 'Array<number>' instead.", Line: 1, Column: 9, EndLine: 1, EndColumn: 17},
			}},
		{Code: "let a: Array<any[]> = [];", Options: []any{map[string]any{"default": "array"}},
			Output: []string{"let a: any[][] = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArray", Message: "Array type using 'Array<any[]>' is forbidden. Use 'any[][]' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 20},
			}},
		{Code: "let a: Array<any[]>[] = [];", Options: []any{map[string]any{"default": "array"}},
			Output: []string{"let a: any[][][] = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArray", Message: "Array type using 'Array<any[]>' is forbidden. Use 'any[][]' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 20},
			}},
		{Code: "let a: Array<any[]> = [];", Options: []any{map[string]any{"default": "generic"}},
			Output: []string{"let a: Array<Array<any>> = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGeneric", Message: "Array type using 'any[]' is forbidden. Use 'Array<any>' instead.", Line: 1, Column: 14, EndLine: 1, EndColumn: 19},
			}},
		{Code: "let a: Array<any[]>[] = [];", Options: []any{map[string]any{"default": "generic"}},
			Output: []string{"let a: Array<Array<any[]>> = [];", "let a: Array<Array<Array<any>>> = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGeneric", Message: "Array type using 'Array<any[]>[]' is forbidden. Use 'Array<Array<any[]>>' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 22},
				{MessageId: "errorStringGeneric", Message: "Array type using 'any[]' is forbidden. Use 'Array<any>' instead.", Line: 1, Column: 14, EndLine: 1, EndColumn: 19},
			}},
		{Code: "let a: Array<Array>[] = [];", Options: []any{map[string]any{"default": "generic"}},
			Output: []string{"let a: Array<Array<Array>> = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGeneric", Message: "Array type using 'Array<Array>[]' is forbidden. Use 'Array<Array<Array>>' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 22},
			}},
		{Code: "let a: Array<Array[]>[] = [];", Options: []any{map[string]any{"default": "generic"}},
			Output: []string{"let a: Array<Array<Array[]>> = [];", "let a: Array<Array<Array<Array>>> = [];"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGeneric", Message: "Array type using 'Array<Array[]>[]' is forbidden. Use 'Array<Array<Array[]>>' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 24},
				{MessageId: "errorStringGeneric", Message: "Array type using 'Array[]' is forbidden. Use 'Array<Array>' instead.", Line: 1, Column: 14, EndLine: 1, EndColumn: 21},
			}},
		{Code: "let x: readonly number[][]", Options: []any{map[string]any{"default": "generic"}},
			Output: []string{"let x: ReadonlyArray<number[]>", "let x: ReadonlyArray<Array<number>>"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGeneric", Message: "Array type using 'readonly number[][]' is forbidden. Use 'ReadonlyArray<number[]>' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 27},
				{MessageId: "errorStringGeneric", Message: "Array type using 'number[]' is forbidden. Use 'Array<number>' instead.", Line: 1, Column: 17, EndLine: 1, EndColumn: 25},
			}},
		{Code: "let x: readonly (readonly number[])[]", Options: []any{map[string]any{"default": "generic"}},
			Output: []string{"let x: ReadonlyArray<readonly number[]>", "let x: ReadonlyArray<ReadonlyArray<number>>"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGeneric", Message: "Array type using 'readonly T[]' is forbidden. Use 'ReadonlyArray<T>' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 38},
				{MessageId: "errorStringGeneric", Message: "Array type using 'readonly number[]' is forbidden. Use 'ReadonlyArray<number>' instead.", Line: 1, Column: 18, EndLine: 1, EndColumn: 35},
			}},
		{Code: "let x: ReadonlyArray<Array<number>>", Options: []any{map[string]any{"default": "array"}},
			Output: []string{"let x: readonly Array<number>[]", "let x: readonly number[][]"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArray", Message: "Array type using 'ReadonlyArray<Array<number>>' is forbidden. Use 'readonly Array<number>[]' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 36},
				{MessageId: "errorStringArray", Message: "Array type using 'Array<number>' is forbidden. Use 'number[]' instead.", Line: 1, Column: 22, EndLine: 1, EndColumn: 35},
			}},
		{Code: "let x: ReadonlyArray<ReadonlyArray<number>>", Options: []any{map[string]any{"default": "array"}},
			Output: []string{"let x: readonly (ReadonlyArray<number>)[]", "let x: readonly (readonly number[])[]"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArray", Message: "Array type using 'ReadonlyArray<T>' is forbidden. Use 'readonly T[]' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 44},
				{MessageId: "errorStringArray", Message: "Array type using 'ReadonlyArray<number>' is forbidden. Use 'readonly number[]' instead.", Line: 1, Column: 22, EndLine: 1, EndColumn: 43},
			}},
		{Code: "let x: ReadonlyArray<readonly number[]>", Options: []any{map[string]any{"default": "array"}},
			Output: []string{"let x: readonly (readonly number[])[]"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringArray", Message: "Array type using 'ReadonlyArray<T>' is forbidden. Use 'readonly T[]' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 40},
			}},
		{Code: "let a: readonly number[][] = []", Options: []any{map[string]any{"default": "array", "readonly": "generic"}},
			Output: []string{"let a: ReadonlyArray<number[]> = []"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGeneric", Message: "Array type using 'readonly number[][]' is forbidden. Use 'ReadonlyArray<number[]>' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 27},
			}},
		{Code: "let a: readonly number[][] = []", Options: []any{map[string]any{"default": "generic", "readonly": "array"}},
			Output: []string{"let a: readonly Array<number>[] = []"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGeneric", Message: "Array type using 'number[]' is forbidden. Use 'Array<number>' instead.", Line: 1, Column: 17, EndLine: 1, EndColumn: 25},
			}},
		{Code: "type T = readonly(string)[]", Options: []any{map[string]any{"default": "generic", "readonly": "generic"}},
			Output: []string{"type T = ReadonlyArray<string>"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGeneric", Message: "Array type using 'readonly string[]' is forbidden. Use 'ReadonlyArray<string>' instead.", Line: 1, Column: 10, EndLine: 1, EndColumn: 28},
			}},
		{Code: "let a: readonly(readonly string[])[] = []", Options: []any{map[string]any{"default": "generic", "readonly": "generic"}},
			Output: []string{"let a: ReadonlyArray<readonly string[]> = []", "let a: ReadonlyArray<ReadonlyArray<string>> = []"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGeneric", Message: "Array type using 'readonly T[]' is forbidden. Use 'ReadonlyArray<T>' instead.", Line: 1, Column: 8, EndLine: 1, EndColumn: 37},
				{MessageId: "errorStringGeneric", Message: "Array type using 'readonly string[]' is forbidden. Use 'ReadonlyArray<string>' instead.", Line: 1, Column: 17, EndLine: 1, EndColumn: 34},
			}},
		{Code: "type T = readonly(readonly string[])[]", Options: []any{map[string]any{"default": "generic", "readonly": "generic"}},
			Output: []string{"type T = ReadonlyArray<readonly string[]>", "type T = ReadonlyArray<ReadonlyArray<string>>"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGeneric", Message: "Array type using 'readonly T[]' is forbidden. Use 'ReadonlyArray<T>' instead.", Line: 1, Column: 10, EndLine: 1, EndColumn: 39},
				{MessageId: "errorStringGeneric", Message: "Array type using 'readonly string[]' is forbidden. Use 'ReadonlyArray<string>' instead.", Line: 1, Column: 19, EndLine: 1, EndColumn: 36},
			}},
		{Code: "type T = readonly (readonly string[])[]", Options: []any{map[string]any{"default": "generic", "readonly": "generic"}},
			Output: []string{"type T = ReadonlyArray<readonly string[]>", "type T = ReadonlyArray<ReadonlyArray<string>>"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGeneric", Message: "Array type using 'readonly T[]' is forbidden. Use 'ReadonlyArray<T>' instead.", Line: 1, Column: 10, EndLine: 1, EndColumn: 40},
				{MessageId: "errorStringGeneric", Message: "Array type using 'readonly string[]' is forbidden. Use 'ReadonlyArray<string>' instead.", Line: 1, Column: 20, EndLine: 1, EndColumn: 37},
			}},
		{Code: "type T = readonly    (readonly string[])[]", Options: []any{map[string]any{"default": "generic", "readonly": "generic"}},
			Output: []string{"type T = ReadonlyArray<readonly string[]>", "type T = ReadonlyArray<ReadonlyArray<string>>"},
			Errors: []rule_tester.InvalidTestCaseError{
				{MessageId: "errorStringGeneric", Message: "Array type using 'readonly T[]' is forbidden. Use 'ReadonlyArray<T>' instead.", Line: 1, Column: 10, EndLine: 1, EndColumn: 43},
				{MessageId: "errorStringGeneric", Message: "Array type using 'readonly string[]' is forbidden. Use 'ReadonlyArray<string>' instead.", Line: 1, Column: 23, EndLine: 1, EndColumn: 40},
			}},
	})
}

func TestArrayTypeUpstreamSchema(t *testing.T) {
	// Upstream regressions #6852 and #6892.
	for _, options := range [][]any{{map[string]any{"default": "simple-array"}}, {"array"}} {
		if err := ArrayTypeRule.Schema.Validate(options); err == nil {
			t.Errorf("expected invalid options: %#v", options)
		}
	}
}
