
// Code generated by tools/gen_shims. DO NOT EDIT.

package osvfs

import "github.com/microsoft/TypeScript/tsc/internal/vfs"
import _ "github.com/microsoft/TypeScript/tsc/internal/vfs/osvfs"
import _ "unsafe"

//go:linkname FS github.com/microsoft/TypeScript/tsc/internal/vfs/osvfs.FS
func FS() vfs.FS
//go:linkname GetGlobalTypingsCacheLocation github.com/microsoft/TypeScript/tsc/internal/vfs/osvfs.GetGlobalTypingsCacheLocation
func GetGlobalTypingsCacheLocation() string
