name: Move rslint artifacts
description: Assemble @rslint/native platform packages from release artifacts
runs:
  using: composite

  steps:
    - name: Move artifacts
      shell: bash
      run: |
        node .github/actions/move-artifacts/move-artifacts.js
