/* auto-generated by NAPI-RS */
/* eslint-disable */

export type TypedArray = Int8Array | Uint8Array | Uint8ClampedArray | Int16Array | Uint16Array | Int32Array | Uint32Array | Float32Array | Float64Array | BigInt64Array | BigUint64Array
/** ESLint-shape comment (`{ type, value, start, end }`). start/end are UTF-16 offsets. */
export interface CommentObj {
  /** "Line" | "Block" */
  type: string
  /** Comment body with the delimiters (`//` or `/* *\/`) stripped. */
  value: string
  start: number
  end: number
}

/**
 * Parse JS/TS/JSX source -> ESTree JSON + ESLint-shape comments (UTF-16 offsets).
 * Replaces npm `oxc-parser`'s `parseSync`.
 *
 * - `filename`: used for lang inference (extension).
 * - `source_type`: `"module"` | `"script"` | `"commonjs"` (commonjs is treated as script).
 * - `jsx`: `languageOptions.parserOptions.ecmaFeatures.jsx`; true promotes `.ts->tsx`/`.js->jsx`.
 *
 * Returns `Err` only for the size guard above; the JS side maps that to a `parseError`
 * (matching the current "parseSync throw -> parseError" contract). `catch_unwind` turns a
 * Rust panic into a JS exception (the worker survives). Note: a stack overflow (deep
 * nesting) is a SIGSEGV that catch_unwind does NOT catch.
 */
export declare function parse(filename: string, source: string, sourceType: string, jsx: boolean): ParseResult

export interface ParseResult {
  /**
   * ESTree JSON (UTF-16 offsets, no `range` -- normalize-ast derives it from start/end).
   * The JS side runs `JSON.parse`.
   */
  program: string
  comments: Array<CommentObj>
  /**
   * Parser-driven token stream in columnar form, all UTF-16 offsets.
   * TypedArrays (not `Vec`/JS `number[]`) so the whole column transfers as one
   * ArrayBuffer instead of N per-element `napi_set_element` crossings:
   * - `token_types[i]`: ESLint token type as `token_map::TokenType as u8`
   * - `token_starts[i]` / `token_ends[i]`: range
   * `value`/`loc` are recomputed JS-side (source slice + lazy loc), so they are not sent.
   * Empty only on a fatal parse abort (oxc sets `panicked`); recoverable
   * syntax errors still produce a full token stream alongside the recovery AST.
   */
  tokenTypes: Uint8Array
  tokenStarts: Uint32Array
  tokenEnds: Uint32Array
}
