import { defineConfig } from '@rstest/core';

export default defineConfig({
  testEnvironment: 'node',
  globals: true,
  testTimeout: 600000,
  include: [
    // cli
    './tests/cli/basic.test.ts',
    './tests/cli/file-args.test.ts',
    './tests/cli/disable-comments.test.ts',
    './tests/cli/js-config/normalize-config.test.ts',
    './tests/cli/js-config/load-config.test.ts',
    './tests/cli/js-config/cli-integration.test.ts',
    './tests/cli/js-config/plugin-enforcement.test.ts',
    './tests/cli/js-config/presets.test.ts',
    './tests/cli/js-config/config-discovery.test.ts',
    './tests/cli/js-config/dir-args.test.ts',
    './tests/cli/js-config/config-ignores-filter.test.ts',
    './tests/cli/js-config/ignore-negation.test.ts',
    './tests/cli/js-config/files-driven-lint.test.ts',
    './tests/cli/js-config/files-driven-monorepo.test.ts',
    './tests/cli/js-config/gitignore-integration.test.ts',
    './tests/cli/entry-point.test.ts',
    './tests/cli/type-check/type-check.test.ts',
    './tests/cli/type-check/type-check-snapshot.test.ts',
    './tests/cli/type-check/ignores-suppression.test.ts',

    // eslint
    './tests/eslint/rules/accessor-pairs.test.ts',
    './tests/eslint/rules/default-case.test.ts',
    './tests/eslint/rules/no-case-declarations.test.ts',
    './tests/eslint/rules/no-console.test.ts',
    './tests/eslint/rules/no-dupe-args.test.ts',
    './tests/eslint/rules/no-dupe-class-members.test.ts',
    './tests/eslint/rules/no-dupe-keys.test.ts',
    './tests/eslint/rules/no-duplicate-case.test.ts',
    './tests/eslint/rules/no-duplicate-imports.test.ts',
    './tests/eslint/rules/no-empty.test.ts',
    './tests/eslint/rules/no-empty-pattern.test.ts',
    './tests/eslint/rules/no-eval.test.ts',
    './tests/eslint/rules/no-implicit-coercion.test.ts',
    './tests/eslint/rules/no-implied-eval.test.ts',
    './tests/eslint/rules/no-iterator.test.ts',
    './tests/eslint/rules/getter-return.test.ts',
    './tests/eslint/rules/guard-for-in.test.ts',
    './tests/eslint/rules/no-loss-of-precision.test.ts',
    './tests/eslint/rules/no-ex-assign.test.ts',
    './tests/eslint/rules/no-constant-binary-expression.test.ts',
    './tests/eslint/rules/no-caller.test.ts',

    './tests/eslint/rules/default-case-last.test.ts',
    './tests/eslint/rules/no-extend-native.test.ts',
    './tests/eslint/rules/no-extra-bind.test.ts',
    './tests/eslint/rules/no-extra-label.test.ts',
    './tests/eslint/rules/no-func-assign.test.ts',
    './tests/eslint/rules/no-global-assign.test.ts',
    './tests/eslint/rules/no-import-assign.test.ts',
    './tests/eslint/rules/no-inner-declarations.test.ts',
    './tests/eslint/rules/no-irregular-whitespace.test.ts',
    './tests/eslint/rules/no-new.test.ts',
    './tests/eslint/rules/no-new-func.test.ts',
    './tests/eslint/rules/no-new-object.test.ts',
    './tests/eslint/rules/no-new-wrappers.test.ts',
    './tests/eslint/rules/no-param-reassign.test.ts',
    './tests/eslint/rules/no-self-assign.test.ts',
    './tests/eslint/rules/no-undef.test.ts',
    './tests/eslint/rules/no-undef-init.test.ts',
    './tests/eslint/rules/no-var.test.ts',
    './tests/eslint/rules/one-var.test.ts',
    './tests/eslint/rules/prefer-const.test.ts',
    './tests/eslint/rules/no-this-before-super.test.ts',
    './tests/eslint/rules/prefer-rest-params.test.ts',
    './tests/eslint/rules/prefer-spread.test.ts',
    './tests/eslint/rules/prefer-template.test.ts',
    './tests/eslint/rules/no-useless-computed-key.test.ts',
    './tests/eslint/rules/no-useless-concat.test.ts',
    // eslint-plugin-import
    './tests/eslint-plugin-import/rules/first.test.ts',
    './tests/eslint-plugin-import/rules/newline-after-import.test.ts',
    './tests/eslint-plugin-import/rules/no-duplicates.test.ts',
    './tests/eslint-plugin-import/rules/no-self-import.test.ts',
    './tests/eslint-plugin-import/rules/no-mutable-exports.test.ts',
    './tests/eslint-plugin-import/rules/no-webpack-loader-syntax.test.ts',

    // eslint-plugin-react
    './tests/eslint-plugin-react/rules/boolean-prop-naming.test.ts',
    './tests/eslint-plugin-react/rules/button-has-type.test.ts',
    './tests/eslint-plugin-react/rules/forbid-component-props.test.ts',
    './tests/eslint-plugin-react/rules/jsx-child-element-spacing.test.ts',
    './tests/eslint-plugin-react/rules/self-closing-comp.test.ts',
    './tests/eslint-plugin-react/rules/void-dom-elements-no-children.test.ts',
    './tests/eslint-plugin-react/rules/style-prop-object.test.ts',
    './tests/eslint-plugin-react/rules/jsx-boolean-value.test.ts',
    './tests/eslint-plugin-react/rules/jsx-equals-spacing.test.ts',
    './tests/eslint-plugin-react/rules/jsx-filename-extension.test.ts',
    './tests/eslint-plugin-react/rules/jsx-first-prop-new-line.test.ts',
    './tests/eslint-plugin-react/rules/jsx-key.test.ts',
    './tests/eslint-plugin-react/rules/jsx-max-props-per-line.test.ts',
    './tests/eslint-plugin-react/rules/jsx-no-bind.test.ts',
    './tests/eslint-plugin-react/rules/jsx-no-comment-textnodes.test.ts',
    './tests/eslint-plugin-react/rules/jsx-no-duplicate-props.test.ts',
    './tests/eslint-plugin-react/rules/jsx-no-leaked-render.test.ts',
    './tests/eslint-plugin-react/rules/jsx-no-script-url.test.ts',
    './tests/eslint-plugin-react/rules/jsx-no-target-blank.test.ts',
    './tests/eslint-plugin-react/rules/jsx-no-undef.test.ts',
    './tests/eslint-plugin-react/rules/jsx-pascal-case.test.ts',
    './tests/eslint-plugin-react/rules/jsx-props-no-multi-spaces.test.ts',
    './tests/eslint-plugin-react/rules/jsx-closing-tag-location.test.ts',
    './tests/eslint-plugin-react/rules/jsx-curly-brace-presence.test.ts',
    './tests/eslint-plugin-react/rules/jsx-wrap-multilines.test.ts',
    './tests/eslint-plugin-react/rules/no-access-state-in-setstate.test.ts',
    './tests/eslint-plugin-react/rules/no-children-prop.test.ts',
    './tests/eslint-plugin-react/rules/no-danger.test.ts',
    './tests/eslint-plugin-react/rules/no-danger-with-children.test.ts',
    './tests/eslint-plugin-react/rules/no-deprecated.test.ts',
    './tests/eslint-plugin-react/rules/no-did-update-set-state.test.ts',
    './tests/eslint-plugin-react/rules/no-direct-mutation-state.test.ts',
    './tests/eslint-plugin-react/rules/no-find-dom-node.test.ts',
    './tests/eslint-plugin-react/rules/no-is-mounted.test.ts',
    './tests/eslint-plugin-react/rules/no-redundant-should-component-update.test.ts',
    './tests/eslint-plugin-react/rules/no-render-return-value.test.ts',
    './tests/eslint-plugin-react/rules/no-string-refs.test.ts',
    './tests/eslint-plugin-react/rules/no-this-in-sfc.test.ts',
    './tests/eslint-plugin-react/rules/no-unstable-nested-components.test.ts',
    './tests/eslint-plugin-react/rules/no-typos.test.ts',
    './tests/eslint-plugin-react/rules/no-unescaped-entities.test.ts',
    './tests/eslint-plugin-react/rules/no-unused-class-component-methods.test.ts',
    './tests/eslint-plugin-react/rules/no-unused-state.test.ts',
    './tests/eslint-plugin-react/rules/no-unknown-property.test.ts',
    './tests/eslint-plugin-react/rules/no-will-update-set-state.test.ts',
    './tests/eslint-plugin-react/rules/prefer-es6-class.test.ts',
    './tests/eslint-plugin-react/rules/prefer-stateless-function.test.ts',
    './tests/eslint-plugin-react/rules/require-render-return.test.ts',

    // eslint-plugin-react-hooks
    './tests/eslint-plugin-react-hooks/rules/rules-of-hooks.test.ts',
    './tests/eslint-plugin-react-hooks/rules/exhaustive-deps.test.ts',

    // typescript-eslint
    './tests/typescript-eslint/rules/adjacent-overload-signatures.test.ts',
    './tests/typescript-eslint/rules/array-type.test.ts',
    './tests/typescript-eslint/rules/await-thenable.test.ts',
    './tests/typescript-eslint/rules/ban-ts-comment.test.ts',
    './tests/typescript-eslint/rules/ban-tslint-comment.test.ts',
    './tests/typescript-eslint/rules/class-literal-property-style.test.ts',
    // './tests/typescript-eslint/rules/class-methods-use-this/class-methods-use-this-core.test.ts',
    // './tests/typescript-eslint/rules/class-methods-use-this/class-methods-use-this.test.ts',
    // './tests/typescript-eslint/rules/consistent-generic-constructors.test.ts',
    // './tests/typescript-eslint/rules/consistent-indexed-object-style.test.ts',
    // './tests/typescript-eslint/rules/consistent-return.test.ts',
    // './tests/typescript-eslint/rules/consistent-type-assertions.test.ts',
    './tests/typescript-eslint/rules/consistent-type-definitions.test.ts',
    // './tests/typescript-eslint/rules/consistent-type-exports.test.ts',
    // './tests/typescript-eslint/rules/consistent-type-imports.test.ts',
    './tests/typescript-eslint/rules/default-param-last.test.ts',
    './tests/typescript-eslint/rules/dot-notation.test.ts',
    './tests/typescript-eslint/rules/explicit-function-return-type.test.ts',
    './tests/typescript-eslint/rules/explicit-member-accessibility.test.ts',
    // './tests/typescript-eslint/rules/explicit-module-boundary-types.test.ts',
    // './tests/typescript-eslint/rules/init-declarations.test.ts',
    './tests/typescript-eslint/rules/max-params.test.ts',
    './tests/typescript-eslint/rules/member-ordering.test.ts',
    './tests/typescript-eslint/rules/member-ordering/member-ordering-alphabetically-case-insensitive-order.test.ts',
    './tests/typescript-eslint/rules/member-ordering/member-ordering-alphabetically-order.test.ts',
    './tests/typescript-eslint/rules/member-ordering/member-ordering-natural-case-insensitive-order.test.ts',
    './tests/typescript-eslint/rules/member-ordering/member-ordering-natural-order.test.ts',
    './tests/typescript-eslint/rules/member-ordering/member-ordering-optionalMembers.test.ts',
    './tests/typescript-eslint/rules/method-signature-style.test.ts',
    // './tests/typescript-eslint/rules/naming-convention/cases/accessor.test.ts',
    // './tests/typescript-eslint/rules/naming-convention/cases/autoAccessor.test.ts',
    // './tests/typescript-eslint/rules/naming-convention/cases/class.test.ts',
    // './tests/typescript-eslint/rules/naming-convention/cases/classicAccessor.test.ts',
    // './tests/typescript-eslint/rules/naming-convention/cases/default.test.ts',
    // './tests/typescript-eslint/rules/naming-convention/cases/enum.test.ts',
    // './tests/typescript-eslint/rules/naming-convention/cases/enumMember.test.ts',
    // './tests/typescript-eslint/rules/naming-convention/cases/function.test.ts',
    // './tests/typescript-eslint/rules/naming-convention/cases/interface.test.ts',
    // './tests/typescript-eslint/rules/naming-convention/cases/method.test.ts',
    // './tests/typescript-eslint/rules/naming-convention/cases/parameter.test.ts',
    // './tests/typescript-eslint/rules/naming-convention/cases/parameterProperty.test.ts',
    // './tests/typescript-eslint/rules/naming-convention/cases/property.test.ts',
    // './tests/typescript-eslint/rules/naming-convention/cases/typeAlias.test.ts',
    // './tests/typescript-eslint/rules/naming-convention/cases/typeParameter.test.ts',
    // './tests/typescript-eslint/rules/naming-convention/cases/variable.test.ts',
    './tests/typescript-eslint/rules/naming-convention/naming-convention.test.ts',
    './tests/typescript-eslint/rules/no-array-constructor.test.ts',
    './tests/typescript-eslint/rules/no-array-delete.test.ts',
    // './tests/typescript-eslint/rules/no-base-to-string.test.ts',
    // './tests/typescript-eslint/rules/no-confusing-non-null-assertion.test.ts',
    './tests/typescript-eslint/rules/no-confusing-void-expression.test.ts',
    // './tests/typescript-eslint/rules/no-deprecated.test.ts',
    './tests/typescript-eslint/rules/no-dupe-class-members.test.ts',
    './tests/typescript-eslint/rules/no-duplicate-enum-values.test.ts',
    './tests/typescript-eslint/rules/no-duplicate-type-constituents.test.ts',
    './tests/typescript-eslint/rules/no-dynamic-delete.test.ts',
    './tests/typescript-eslint/rules/no-empty-function.test.ts',
    './tests/typescript-eslint/rules/no-empty-interface.test.ts',
    // './tests/typescript-eslint/rules/no-empty-object-type.test.ts',
    './tests/typescript-eslint/rules/no-explicit-any.test.ts',
    './tests/typescript-eslint/rules/no-extra-non-null-assertion.test.ts',
    './tests/typescript-eslint/rules/no-extraneous-class.test.ts',
    './tests/typescript-eslint/rules/no-floating-promises.test.ts',
    './tests/typescript-eslint/rules/no-for-in-array.test.ts',
    // './tests/typescript-eslint/rules/no-import-type-side-effects.test.ts',
    './tests/typescript-eslint/rules/no-implied-eval.test.ts',
    './tests/typescript-eslint/rules/no-inferrable-types.test.ts',
    // './tests/typescript-eslint/rules/no-invalid-this.test.ts',
    './tests/typescript-eslint/rules/no-invalid-void-type.test.ts',
    './tests/typescript-eslint/rules/no-loop-func.test.ts',
    // './tests/typescript-eslint/rules/no-loss-of-precision.test.ts',
    './tests/typescript-eslint/rules/no-magic-numbers.test.ts',
    // './tests/typescript-eslint/rules/no-meaningless-void-operator.test.ts',
    './tests/typescript-eslint/rules/no-misused-new.test.ts',
    './tests/typescript-eslint/rules/no-misused-promises.test.ts',
    // './tests/typescript-eslint/rules/no-misused-spread.test.ts',
    './tests/typescript-eslint/rules/no-mixed-enums.test.ts',
    // './tests/typescript-eslint/rules/no-namespace.test.ts',
    './tests/typescript-eslint/rules/no-non-null-asserted-nullish-coalescing.test.ts',
    './tests/typescript-eslint/rules/no-non-null-asserted-optional-chain.test.ts',
    './tests/typescript-eslint/rules/no-non-null-assertion.test.ts',
    './tests/typescript-eslint/rules/no-redeclare.test.ts',
    './tests/typescript-eslint/rules/no-redundant-type-constituents.test.ts',
    './tests/typescript-eslint/rules/no-require-imports.test.ts',
    './tests/typescript-eslint/rules/no-restricted-imports.test.ts',
    // './tests/typescript-eslint/rules/no-restricted-types.test.ts',
    // './tests/typescript-eslint/rules/no-shadow/no-shadow-eslint.test.ts',
    './tests/typescript-eslint/rules/no-shadow/no-shadow.test.ts',
    './tests/typescript-eslint/rules/no-this-alias.test.ts',
    // './tests/typescript-eslint/rules/no-type-alias.test.ts',
    './tests/typescript-eslint/rules/no-use-before-define.test.ts',
    './tests/typescript-eslint/rules/no-unnecessary-boolean-literal-compare.test.ts',
    './tests/typescript-eslint/rules/no-unnecessary-condition.test.ts',
    // './tests/typescript-eslint/rules/no-unnecessary-parameter-property-assignment.test.ts',
    // './tests/typescript-eslint/rules/no-unnecessary-qualifier.test.ts',
    './tests/typescript-eslint/rules/no-unnecessary-template-expression.test.ts',
    // './tests/typescript-eslint/rules/no-unnecessary-type-arguments.test.ts',
    // './tests/typescript-eslint/rules/no-unnecessary-type-assertion.test.ts',
    './tests/typescript-eslint/rules/no-unnecessary-type-constraint.test.ts',
    // './tests/typescript-eslint/rules/no-unnecessary-type-conversion.test.ts',
    // './tests/typescript-eslint/rules/no-unnecessary-type-parameters.test.ts',
    './tests/typescript-eslint/rules/no-unsafe-argument.test.ts',
    // './tests/typescript-eslint/rules/no-unsafe-assignment.test.ts',
    './tests/typescript-eslint/rules/no-unsafe-call.test.ts',
    // './tests/typescript-eslint/rules/no-unsafe-declaration-merging.test.ts',
    './tests/typescript-eslint/rules/no-unsafe-enum-comparison.test.ts',
    // './tests/typescript-eslint/rules/no-unsafe-function-type.test.ts',
    './tests/typescript-eslint/rules/no-unsafe-member-access.test.ts',
    './tests/typescript-eslint/rules/no-unsafe-return.test.ts',
    './tests/typescript-eslint/rules/no-unsafe-type-assertion.test.ts',
    './tests/typescript-eslint/rules/no-unsafe-unary-minus.test.ts',
    './tests/typescript-eslint/rules/no-unused-expressions.test.ts',
    './tests/typescript-eslint/rules/no-unused-vars/no-unused-vars-eslint-basic.test.ts',
    './tests/typescript-eslint/rules/no-unused-vars/no-unused-vars-eslint-patterns.test.ts',
    './tests/typescript-eslint/rules/no-unused-vars/no-unused-vars-eslint-catch-loops.test.ts',
    './tests/typescript-eslint/rules/no-unused-vars/no-unused-vars-eslint-advanced.test.ts',
    './tests/typescript-eslint/rules/no-unused-vars/no-unused-vars-eslint-report-used.test.ts',
    './tests/typescript-eslint/rules/no-unused-vars/no-unused-vars.test.ts',
    './tests/typescript-eslint/rules/no-unused-vars/no-unused-vars-declare.test.ts',
    // './tests/typescript-eslint/rules/no-use-before-define.test.ts',
    './tests/typescript-eslint/rules/no-useless-constructor.test.ts',
    // './tests/typescript-eslint/rules/no-useless-empty-export.test.ts',
    // './tests/typescript-eslint/rules/no-var-requires.test.ts',
    // './tests/typescript-eslint/rules/no-wrapper-object-types.test.ts',
    './tests/typescript-eslint/rules/no_namespace.test.ts',
    './tests/typescript-eslint/rules/non-nullable-type-assertion-style.test.ts',
    './tests/typescript-eslint/rules/only-throw-error.test.ts',
    './tests/typescript-eslint/rules/parameter-properties.test.ts',
    './tests/typescript-eslint/rules/prefer-as-const.test.ts',
    './tests/typescript-eslint/rules/prefer-destructuring.test.ts',
    // './tests/typescript-eslint/rules/prefer-enum-initializers.test.ts',
    // './tests/typescript-eslint/rules/prefer-find.test.ts',
    './tests/typescript-eslint/rules/prefer-for-of.test.ts',
    // './tests/typescript-eslint/rules/prefer-function-type.test.ts',
    './tests/typescript-eslint/rules/prefer-includes.test.ts',
    './tests/typescript-eslint/rules/prefer-literal-enum-member.test.ts',
    './tests/typescript-eslint/rules/prefer-namespace-keyword.test.ts',
    './tests/typescript-eslint/rules/prefer-nullish-coalescing.test.ts',
    './tests/typescript-eslint/rules/prefer-optional-chain/prefer-optional-chain.test.ts',
    // './tests/typescript-eslint/rules/prefer-promise-reject-errors.test.ts',
    // './tests/typescript-eslint/rules/prefer-readonly-parameter-types.test.ts',
    './tests/typescript-eslint/rules/prefer-readonly.test.ts',
    './tests/typescript-eslint/rules/prefer-reduce-type-parameter.test.ts',
    './tests/typescript-eslint/rules/prefer-regexp-exec.test.ts',
    './tests/typescript-eslint/rules/prefer-return-this-type.test.ts',
    './tests/typescript-eslint/rules/prefer-string-starts-ends-with.test.ts',
    './tests/typescript-eslint/rules/prefer-ts-expect-error.test.ts',
    // './tests/typescript-eslint/rules/promise-function-async.test.ts',
    './tests/typescript-eslint/rules/related-getter-setter-pairs.test.ts',
    // './tests/typescript-eslint/rules/require-array-sort-compare.test.ts',
    './tests/typescript-eslint/rules/require-await.test.ts',
    // './tests/typescript-eslint/rules/restrict-plus-operands.test.ts',
    // './tests/typescript-eslint/rules/restrict-template-expressions.test.ts',
    // './tests/typescript-eslint/rules/return-await.test.ts',
    // './tests/typescript-eslint/rules/sort-type-constituents.test.ts',
    // './tests/typescript-eslint/rules/strict-boolean-expressions.test.ts',
    // './tests/typescript-eslint/rules/switch-exhaustiveness-check.test.ts',
    // './tests/typescript-eslint/rules/triple-slash-reference.test.ts',
    // './tests/typescript-eslint/rules/typedef.test.ts',
    // './tests/typescript-eslint/rules/unbound-method.test.ts',
    // './tests/typescript-eslint/rules/unified-signatures.test.ts',
    // './tests/typescript-eslint/rules/use-unknown-in-catch-callback-variable.test.ts',
    './tests/eslint/rules/no-control-regex.test.ts',
    './tests/eslint/rules/no-dupe-else-if.test.ts',
    './tests/eslint/rules/no-extra-boolean-cast.test.ts',
    './tests/eslint/rules/no-empty-character-class.test.ts',
    './tests/eslint/rules/no-fallthrough.test.ts',
    './tests/eslint/rules/no-invalid-regexp.test.ts',
    './tests/eslint/rules/no-misleading-character-class.test.ts',
    './tests/eslint/rules/no-regex-spaces.test.ts',
    './tests/eslint/rules/no-new-symbol.test.ts',
    './tests/eslint/rules/no-restricted-imports.test.ts',
    './tests/eslint/rules/no-restricted-syntax.test.ts',
    './tests/eslint/rules/no-obj-calls.test.ts',
    './tests/eslint/rules/no-setter-return.test.ts',
    './tests/eslint/rules/no-unreachable.test.ts',
    './tests/eslint/rules/no-unsafe-finally.test.ts',
    './tests/eslint/rules/no-unsafe-negation.test.ts',
    './tests/eslint/rules/no-throw-literal.test.ts',
    './tests/eslint/rules/no-unsafe-optional-chaining.test.ts',
    './tests/eslint/rules/no-useless-backreference.test.ts',
    './tests/eslint/rules/no-useless-call.test.ts',
    './tests/eslint/rules/no-useless-catch.test.ts',
    './tests/eslint/rules/no-useless-escape.test.ts',
    './tests/eslint/rules/no-useless-rename.test.ts',
    './tests/eslint/rules/no-useless-constructor.test.ts',
    './tests/eslint/rules/no-prototype-builtins.test.ts',
    './tests/eslint/rules/use-isnan.test.ts',
    './tests/eslint/rules/eqeqeq.test.ts',
    './tests/eslint/rules/valid-typeof.test.ts',
    './tests/eslint/rules/no-unmodified-loop-condition.test.ts',
    './tests/eslint/rules/no-alert.test.ts',
    './tests/eslint/rules/no-bitwise.test.ts',
    './tests/eslint/rules/complexity.test.ts',
    './tests/eslint/rules/max-depth.test.ts',
    './tests/eslint/rules/max-lines.test.ts',
    './tests/eslint/rules/max-lines-per-function.test.ts',
    './tests/eslint/rules/max-nested-callbacks.test.ts',
    './tests/eslint/rules/no-label-var.test.ts',
    './tests/eslint/rules/no-shadow.test.ts',
    './tests/eslint/rules/no-labels.test.ts',
    './tests/eslint/rules/no-lone-blocks.test.ts',
    './tests/eslint/rules/no-loop-func.test.ts',
    './tests/eslint/rules/no-multi-assign.test.ts',
    './tests/eslint/rules/no-multi-str.test.ts',
    './tests/eslint/rules/no-nested-ternary.test.ts',
    './tests/eslint/rules/no-nonoctal-decimal-escape.test.ts',
    './tests/eslint/rules/no-unexpected-multiline.test.ts',
    './tests/eslint/rules/object-shorthand.test.ts',
    './tests/eslint/rules/no-octal.test.ts',
    './tests/eslint/rules/no-octal-escape.test.ts',
    './tests/eslint/rules/no-script-url.test.ts',
    './tests/eslint/rules/no-with.test.ts',
    './tests/eslint/rules/no-proto.test.ts',
    './tests/eslint/rules/no-return-assign.test.ts',
    './tests/eslint/rules/no-self-compare.test.ts',
    './tests/eslint/rules/no-sequences.test.ts',
    './tests/eslint/rules/strict.test.ts',
    './tests/eslint/rules/no-unneeded-ternary.test.ts',
    './tests/eslint/rules/no-delete-var.test.ts',
    './tests/eslint/rules/prefer-promise-reject-errors.test.ts',
    './tests/eslint/rules/radix.test.ts',
    './tests/eslint/rules/require-atomic-updates.test.ts',
    './tests/eslint/rules/require-yield.test.ts',
    './tests/eslint/rules/symbol-description.test.ts',

    // eslint-plugin-jest
    './tests/eslint-plugin-jest/rules/no-alias-methods.test.ts',
    './tests/eslint-plugin-jest/rules/no-disabled-tests.test.ts',
    './tests/eslint-plugin-jest/rules/no-done-callback.test.ts',
    './tests/eslint-plugin-jest/rules/no-focused-tests.test.ts',
    './tests/eslint-plugin-jest/rules/no-hooks.test.ts',
    './tests/eslint-plugin-jest/rules/no-mocks-import.test.ts',
    './tests/eslint-plugin-jest/rules/no-test-prefixes.test.ts',
    './tests/eslint-plugin-jest/rules/prefer-strict-equal.test.ts',
    './tests/eslint-plugin-jest/rules/prefer-to-contain.test.ts',
    './tests/eslint-plugin-jest/rules/prefer-to-have-length.test.ts',
    './tests/eslint-plugin-jest/rules/prefer-todo.test.ts',
    './tests/eslint-plugin-jest/rules/valid-describe-callback.test.ts',

    // eslint-plugin-promise
    './tests/eslint-plugin-promise/rules/param-names.test.ts',

    // eslint-plugin-unicorn
    './tests/eslint-plugin-unicorn/rules/filename-case.test.ts',
    './tests/eslint-plugin-unicorn/rules/no-static-only-class.test.ts',

    './tests/eslint/rules/no-shadow-restricted-names.test.ts',
  ],
});
