package typescript

import (
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/adjacent_overload_signatures"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/array_type"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/await_thenable"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/ban_ts_comment"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/ban_tslint_comment"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/class_literal_property_style"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/class_methods_use_this"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/consistent_generic_constructors"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/consistent_indexed_object_style"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/consistent_return"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/consistent_type_assertions"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/consistent_type_definitions"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/consistent_type_exports"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/consistent_type_imports"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/default_param_last"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/dot_notation"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/explicit_function_return_type"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/explicit_member_accessibility"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/explicit_module_boundary_types"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/init_declarations"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/max_params"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/member_ordering"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/method_signature_style"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/naming_convention"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_array_constructor"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_array_delete"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_base_to_string"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_confusing_non_null_assertion"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_confusing_void_expression"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_deprecated"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_dupe_class_members"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_duplicate_enum_values"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_duplicate_type_constituents"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_dynamic_delete"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_empty_function"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_empty_interface"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_empty_object_type"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_explicit_any"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_extra_non_null_assertion"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_extraneous_class"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_floating_promises"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_for_in_array"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_implied_eval"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_import_type_side_effects"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_inferrable_types"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_invalid_this"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_invalid_void_type"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_loop_func"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_magic_numbers"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_meaningless_void_operator"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_misused_new"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_misused_promises"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_misused_spread"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_mixed_enums"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_namespace"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_non_null_asserted_nullish_coalescing"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_non_null_asserted_optional_chain"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_non_null_assertion"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_redeclare"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_redundant_type_constituents"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_require_imports"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_restricted_imports"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_restricted_types"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_shadow"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_this_alias"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_type_alias"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_unnecessary_boolean_literal_compare"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_unnecessary_condition"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_unnecessary_parameter_property_assignment"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_unnecessary_qualifier"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_unnecessary_template_expression"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_unnecessary_type_arguments"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_unnecessary_type_assertion"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_unnecessary_type_constraint"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_unnecessary_type_conversion"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_unsafe_argument"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_unsafe_assignment"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_unsafe_call"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_unsafe_declaration_merging"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_unsafe_enum_comparison"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_unsafe_function_type"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_unsafe_member_access"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_unsafe_return"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_unsafe_type_assertion"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_unsafe_unary_minus"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_unused_expressions"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_unused_private_class_members"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_unused_vars"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_use_before_define"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_useless_constructor"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_useless_default_assignment"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_useless_empty_export"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_var_requires"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/no_wrapper_object_types"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/non_nullable_type_assertion_style"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/only_throw_error"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/parameter_properties"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/prefer_as_const"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/prefer_destructuring"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/prefer_enum_initializers"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/prefer_find"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/prefer_for_of"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/prefer_function_type"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/prefer_includes"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/prefer_literal_enum_member"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/prefer_namespace_keyword"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/prefer_nullish_coalescing"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/prefer_optional_chain"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/prefer_promise_reject_errors"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/prefer_readonly"
	// "github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/prefer_readonly_parameter_types" // Temporarily disabled - incomplete implementation
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/prefer_reduce_type_parameter"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/prefer_regexp_exec"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/prefer_return_this_type"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/prefer_string_starts_ends_with"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/prefer_ts_expect_error"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/promise_function_async"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/related_getter_setter_pairs"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/require_array_sort_compare"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/require_await"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/restrict_plus_operands"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/restrict_template_expressions"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/return_await"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/strict_boolean_expressions"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/strict_void_return"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/switch_exhaustiveness_check"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/triple_slash_reference"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/unbound_method"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/unified_signatures"
	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/use_unknown_in_catch_callback_variable"
	"github.com/web-infra-dev/rslint/internal/rule"
)

func GetAllRules() []rule.Rule {
	return []rule.Rule{
		adjacent_overload_signatures.AdjacentOverloadSignaturesRule,
		array_type.ArrayTypeRule,
		await_thenable.AwaitThenableRule,
		ban_ts_comment.BanTsCommentRule,
		ban_tslint_comment.BanTslintCommentRule,
		class_literal_property_style.ClassLiteralPropertyStyleRule,
		class_methods_use_this.ClassMethodsUseThisRule,
		consistent_generic_constructors.ConsistentGenericConstructorsRule,
		consistent_indexed_object_style.ConsistentIndexedObjectStyleRule,
		consistent_return.ConsistentReturnRule,
		consistent_type_assertions.ConsistentTypeAssertionsRule,
		consistent_type_definitions.ConsistentTypeDefinitionsRule,
		consistent_type_exports.ConsistentTypeExportsRule,
		consistent_type_imports.ConsistentTypeImportsRule,
		default_param_last.DefaultParamLastRule,
		dot_notation.DotNotationRule,
		explicit_function_return_type.ExplicitFunctionReturnTypeRule,
		explicit_member_accessibility.ExplicitMemberAccessibilityRule,
		explicit_module_boundary_types.ExplicitModuleBoundaryTypesRule,
		init_declarations.InitDeclarationsRule,
		max_params.MaxParamsRule,
		member_ordering.MemberOrderingRule,
		method_signature_style.MethodSignatureStyleRule,
		naming_convention.NamingConventionRule,
		no_array_constructor.NoArrayConstructorRule,
		no_array_delete.NoArrayDeleteRule,
		no_base_to_string.NoBaseToStringRule,
		no_confusing_non_null_assertion.NoConfusingNonNullAssertionRule,
		no_confusing_void_expression.NoConfusingVoidExpressionRule,
		no_deprecated.NoDeprecatedRule,
		no_dupe_class_members.NoDupeClassMembersRule,
		no_duplicate_enum_values.NoDuplicateEnumValuesRule,
		no_duplicate_type_constituents.NoDuplicateTypeConstituentsRule,
		no_dynamic_delete.NoDynamicDeleteRule,
		no_explicit_any.NoExplicitAnyRule,
		no_empty_function.NoEmptyFunctionRule,
		no_empty_interface.NoEmptyInterfaceRule,
		no_empty_object_type.NoEmptyObjectTypeRule,
		no_extra_non_null_assertion.NoExtraNonNullAssertionRule,
		no_extraneous_class.NoExtraneousClassRule,
		no_invalid_this.NoInvalidThisRule,
		no_invalid_void_type.NoInvalidVoidTypeRule,
		no_floating_promises.NoFloatingPromisesRule,
		no_for_in_array.NoForInArrayRule,
		no_implied_eval.NoImpliedEvalRule,
		no_import_type_side_effects.NoImportTypeSideEffectsRule,
		no_inferrable_types.NoInferrableTypesRule,
		no_loop_func.NoLoopFuncRule,
		no_magic_numbers.NoMagicNumbersRule,
		no_meaningless_void_operator.NoMeaninglessVoidOperatorRule,
		no_misused_new.NoMisusedNewRule,
		no_misused_promises.NoMisusedPromisesRule,
		no_misused_spread.NoMisusedSpreadRule,
		no_mixed_enums.NoMixedEnumsRule,
		no_namespace.NoNamespaceRule,
		no_non_null_asserted_nullish_coalescing.NoNonNullAssertedNullishCoalescingRule,
		no_non_null_asserted_optional_chain.NoNonNullAssertedOptionalChainRule,
		no_non_null_assertion.NoNonNullAssertionRule,
		no_redeclare.NoRedeclareRule,
		no_redundant_type_constituents.NoRedundantTypeConstituentsRule,
		no_this_alias.NoThisAliasRule,
		no_type_alias.NoTypeAliasRule,
		no_require_imports.NoRequireImportsRule,
		no_restricted_imports.NoRestrictedImportsRule,
		no_restricted_types.NoRestrictedTypesRule,
		no_shadow.NoShadowRule,
		no_unnecessary_boolean_literal_compare.NoUnnecessaryBooleanLiteralCompareRule,
		no_unnecessary_condition.NoUnnecessaryConditionRule,
		no_unnecessary_parameter_property_assignment.NoUnnecessaryParameterPropertyAssignmentRule,
		no_unnecessary_qualifier.NoUnnecessaryQualifierRule,
		no_unnecessary_template_expression.NoUnnecessaryTemplateExpressionRule,
		no_unnecessary_type_arguments.NoUnnecessaryTypeArgumentsRule,
		no_unnecessary_type_assertion.NoUnnecessaryTypeAssertionRule,
		no_unnecessary_type_constraint.NoUnnecessaryTypeConstraintRule,
		no_unnecessary_type_conversion.NoUnnecessaryTypeConversionRule,
		no_unsafe_argument.NoUnsafeArgumentRule,
		no_unsafe_assignment.NoUnsafeAssignmentRule,
		no_unsafe_call.NoUnsafeCallRule,
		no_unsafe_declaration_merging.NoUnsafeDeclarationMergingRule,
		no_unsafe_enum_comparison.NoUnsafeEnumComparisonRule,
		no_unsafe_function_type.NoUnsafeFunctionTypeRule,
		no_unsafe_member_access.NoUnsafeMemberAccessRule,
		no_unsafe_return.NoUnsafeReturnRule,
		no_unsafe_type_assertion.NoUnsafeTypeAssertionRule,
		no_unsafe_unary_minus.NoUnsafeUnaryMinusRule,
		no_unused_expressions.NoUnusedExpressionsRule,
		no_unused_private_class_members.NoUnusedPrivateClassMembersRule,
		no_unused_vars.NoUnusedVarsRule,
		no_use_before_define.NoUseBeforeDefineRule,
		no_useless_constructor.NoUselessConstructorRule,
		no_useless_default_assignment.NoUselessDefaultAssignmentRule,
		no_useless_empty_export.NoUselessEmptyExportRule,
		no_var_requires.NoVarRequiresRule,
		no_wrapper_object_types.NoWrapperObjectTypesRule,
		non_nullable_type_assertion_style.NonNullableTypeAssertionStyleRule,
		only_throw_error.OnlyThrowErrorRule,
		parameter_properties.ParameterPropertiesRule,
		prefer_as_const.PreferAsConstRule,
		prefer_destructuring.PreferDestructuringRule,
		prefer_enum_initializers.PreferEnumInitializersRule,
		prefer_find.PreferFindRule,
		prefer_includes.PreferIncludesRule,
		prefer_literal_enum_member.PreferLiteralEnumMemberRule,
		prefer_namespace_keyword.PreferNamespaceKeywordRule,
		prefer_for_of.PreferForOfRule,
		prefer_function_type.PreferFunctionTypeRule,
		prefer_nullish_coalescing.PreferNullishCoalescingRule,
		prefer_optional_chain.PreferOptionalChainRule,
		prefer_promise_reject_errors.PreferPromiseRejectErrorsRule,
		prefer_readonly.PreferReadonlyRule,
		// TODO: prefer-readonly-parameter-types needs complete implementation for proper type checking
		// Temporarily disabled until the isReadonlyType function is fully implemented with proper
		// detection of readonly arrays, readonly objects, function types, and other edge cases
		// prefer_readonly_parameter_types.PreferReadonlyParameterTypesRule,
		prefer_reduce_type_parameter.PreferReduceTypeParameterRule,
		prefer_regexp_exec.PreferRegExpExecRule,
		prefer_return_this_type.PreferReturnThisTypeRule,
		prefer_string_starts_ends_with.PreferStringStartsEndsWithRule,
		prefer_ts_expect_error.PreferTsExpectErrorRule,
		promise_function_async.PromiseFunctionAsyncRule,
		related_getter_setter_pairs.RelatedGetterSetterPairsRule,
		require_array_sort_compare.RequireArraySortCompareRule,
		require_await.RequireAwaitRule,
		restrict_plus_operands.RestrictPlusOperandsRule,
		restrict_template_expressions.RestrictTemplateExpressionsRule,
		return_await.ReturnAwaitRule,
		strict_boolean_expressions.StrictBooleanExpressionsRule,
		strict_void_return.StrictVoidReturnRule,
		switch_exhaustiveness_check.SwitchExhaustivenessCheckRule,
		triple_slash_reference.TripleSlashReferenceRule,
		unbound_method.UnboundMethodRule,
		unified_signatures.UnifiedSignaturesRule,
		use_unknown_in_catch_callback_variable.UseUnknownInCatchCallbackVariableRule,
	}
}
