// TestOrderUpstreamTypescript02 migrates the upstream typescript cases from import-js/eslint-plugin-import at 1a39fb8672c83f8781c3a97f02eee00a7a2f0253.
// It preserves upstream messages, source positions, options, and iterative autofix outputs.
// Framework-only parser/resolver settings use rslint native equivalents; tsgo lock-ins live in order_extras_*_test.go.
package order_test

import (
	"testing"

	"github.com/web-infra-dev/rslint/internal/plugins/import/fixtures"
	"github.com/web-infra-dev/rslint/internal/plugins/import/rules/order"
	"github.com/web-infra-dev/rslint/internal/rule_tester"
)

func TestOrderUpstreamTypescript02(t *testing.T) {
	rule_tester.RunRuleTester(
		fixtures.GetRootDir(),
		"tsconfig.json",
		t,
		&order.OrderRule,
		[]rule_tester.ValidTestCase{
			// Upstream case 1:20.
			{Code: "\n              import type A from \"fs\";\n              import type B from \"path\";\n              import type C from \"../foo.js\";\n              import type D from \"./bar.js\";\n              import type E from './';\n\n              import a from \"fs\";\n              import b from \"path\";\n              import c from \"../foo.js\";\n              import d from \"./bar.js\";\n              import e from \"./\";\n            ", Options: []any{map[string]any{"groups": []any{"type", "builtin", "parent", "sibling", "index"}, "alphabetize": map[string]any{"order": "asc", "caseInsensitive": true}, "sortTypesGroup": true}}},
			// Upstream case 1:21, 1:42.
			{Code: "\n              import type A from \"fs\";\n              import type B from \"path\";\n              import type C from \"../foo.js\";\n              import type D from \"./bar.js\";\n              import type E from './';\n\n              import a from \"fs\";\n              import b from \"path\";\n\n              import c from \"../foo.js\";\n\n              import d from \"./bar.js\";\n\n              import e from \"./\";\n            ", Options: []any{map[string]any{"groups": []any{"type", "builtin", "parent", "sibling", "index"}, "sortTypesGroup": true, "newlines-between": "always", "newlines-between-types": "ignore"}}},
			// Upstream case 1:22, 1:43.
			{Code: "\n              import a from \"fs\";\n              import b from \"path\";\n\n              import c from \"../foo.js\";\n\n              import d from \"./bar.js\";\n\n              import e from \"./\";\n\n              import type A from \"fs\";\n              import type B from \"path\";\n              import type C from \"../foo.js\";\n              import type D from \"./bar.js\";\n              import type E from './';\n            ", Options: []any{map[string]any{"groups": []any{"builtin", "parent", "sibling", "index", "type"}, "sortTypesGroup": true, "newlines-between": "always", "newlines-between-types": "ignore"}}},
			// Upstream case 1:23, 1:44.
			{Code: "\n              import type A from \"fs\";\n              import type B from \"path\";\n\n              import type C from \"../foo.js\";\n\n              import type D from \"./bar.js\";\n\n              import type E from './';\n\n              import a from \"fs\";\n              import b from \"path\";\n              import c from \"../foo.js\";\n              import d from \"./bar.js\";\n              import e from \"./\";\n            ", Options: []any{map[string]any{"groups": []any{"type", "builtin", "parent", "sibling", "index"}, "sortTypesGroup": true, "newlines-between": "never", "newlines-between-types": "always"}}},
			// Upstream case 1:24, 1:45.
			{Code: "\n              import a from \"fs\";\n              import b from \"path\";\n              import c from \"../foo.js\";\n              import d from \"./bar.js\";\n              import e from \"./\";\n\n              import type A from \"fs\";\n              import type B from \"path\";\n\n              import type C from \"../foo.js\";\n\n              import type D from \"./bar.js\";\n\n              import type E from './';\n            ", Options: []any{map[string]any{"groups": []any{"builtin", "parent", "sibling", "index", "type"}, "sortTypesGroup": true, "newlines-between": "never", "newlines-between-types": "always"}}},
			// Upstream case 1:25.
			{Code: "\n              import fs from 'fs';\n\n              import '@scoped/package';\n              import type { B } from 'fs';\n\n              import type { A1 } from '/bad/bad/bad/bad';\n              import './a/b/c';\n              import type { A2 } from '/bad/bad/bad/bad';\n              import type { A3 } from '/bad/bad/bad/bad';\n              import type { D1 } from '/bad/bad/not/good';\n              import type { D2 } from '/bad/bad/not/good';\n              import type { D3 } from '/bad/bad/not/good';\n\n              import type { C } from '@something/else';\n\n              import type { E } from './index.js';\n            ", Options: []any{map[string]any{"alphabetize": map[string]any{"order": "asc"}, "groups": []any{"builtin", "type", "unknown", "external"}, "sortTypesGroup": true, "newlines-between": "always"}}},
			// Upstream case 1:26.
			{Code: "\n              // https://prettier.io/docs/en/options.html\n\n              module.exports = {\n                  ...require('@xxxx/.prettierrc.js'),\n              };\n            ", Options: []any{map[string]any{"named": map[string]any{"enabled": true}}}},
			// Upstream case 1:27.
			{Code: "\n              import c from 'Bar';\n              import d from 'bar';\n\n              import {\n                aa,\n                bb,\n                cc,\n                dd,\n                ee,\n                ff,\n                gg\n              } from 'baz';\n\n              import {\n                hh,\n                ii,\n                jj,\n                kk,\n                ll,\n                mm,\n                nn\n              } from 'fizz';\n\n              import a from 'foo';\n\n              import b from 'dirA/bar';\n\n              import index from './';\n\n              import type { AA,\n                BB, CC } from 'abc';\n\n              import type { Z } from 'fizz';\n\n              import type {\n                A,\n                B\n              } from 'foo';\n\n              import type { C2 } from 'dirB/Bar';\n\n              import type {\n                D2,\n                X2,\n                Y2\n              } from 'dirB/bar';\n\n              import type { E2 } from 'dirB/baz';\n\n              import type { C3 } from 'dirC/Bar';\n\n              import type {\n                D3,\n                X3,\n                Y3\n              } from 'dirC/bar';\n\n              import type { E3 } from 'dirC/baz';\n              import type { F3 } from 'dirC/caz';\n\n              import type { C1 } from 'dirA/Bar';\n\n              import type {\n                D1,\n                X1,\n                Y1\n              } from 'dirA/bar';\n\n              import type { E1 } from 'dirA/baz';\n\n              import type { F } from './index.js';\n\n              import type { G } from './aaa.js';\n              import type { H } from './bbb';\n            ", Options: []any{map[string]any{"alphabetize": map[string]any{"order": "asc"}, "groups": []any{"external", "internal", "index", "type"}, "pathGroups": []any{map[string]any{"pattern": "dirA/**", "group": "internal", "position": "after"}, map[string]any{"pattern": "dirB/**", "group": "internal", "position": "before"}, map[string]any{"pattern": "dirC/**", "group": "internal"}}, "newlines-between": "always-and-inside-groups", "newlines-between-types": "always-and-inside-groups", "pathGroupsExcludedImportTypes": []any{}, "sortTypesGroup": true, "consolidateIslands": "inside-groups"}}},
			// Upstream case 1:28.
			{Code: "\n              import c from 'Bar';\n              import d from 'bar';\n\n              import {\n                aa,\n                bb,\n                cc,\n                dd,\n                ee,\n                ff,\n                gg\n              } from 'baz';\n\n              import {\n                hh,\n                ii,\n                jj,\n                kk,\n                ll,\n                mm,\n                nn\n              } from 'fizz';\n\n              import a from 'foo';\n\n              import b from 'dirA/bar';\n\n              import index from './';\n\n              import type { AA,\n                BB, CC } from 'abc';\n\n              import type { Z } from 'fizz';\n\n              import type {\n                A,\n                B\n              } from 'foo';\n\n              import type { C2 } from 'dirB/Bar';\n\n              import type {\n                D2,\n                X2,\n                Y2\n              } from 'dirB/bar';\n\n              import type { E2 } from 'dirB/baz';\n\n              import type { C3 } from 'dirC/Bar';\n\n              import type {\n                D3,\n                X3,\n                Y3\n              } from 'dirC/bar';\n\n              import type { E3 } from 'dirC/baz';\n              import type { F3 } from 'dirC/caz';\n\n              import type { C1 } from 'dirA/Bar';\n\n              import type {\n                D1,\n                X1,\n                Y1\n              } from 'dirA/bar';\n\n              import type { E1 } from 'dirA/baz';\n\n              import type { F } from './index.js';\n\n              import type { G } from './aaa.js';\n              import type { H } from './bbb';\n            ", Options: []any{map[string]any{"alphabetize": map[string]any{"order": "asc"}, "groups": []any{"external", "internal", "index", "type"}, "pathGroups": []any{map[string]any{"pattern": "dirA/**", "group": "internal", "position": "after"}, map[string]any{"pattern": "dirB/**", "group": "internal", "position": "before"}, map[string]any{"pattern": "dirC/**", "group": "internal"}}, "newlines-between": "always-and-inside-groups", "newlines-between-types": "always-and-inside-groups", "pathGroupsExcludedImportTypes": []any{}, "sortTypesGroup": true, "consolidateIslands": "never"}}},
			// Upstream case 1:29.
			{Code: "\n              import makeVanillaYargs from 'yargs/yargs';\n\n              import { createDebugLogger } from 'multiverse+rejoinder';\n\n              import { globalDebuggerNamespace } from 'rootverse+bfe:src/constant.ts';\n              import { ErrorMessage, type KeyValueEntry } from 'rootverse+bfe:src/error.ts';\n\n              import {\n                $artificiallyInvoked,\n                $canonical,\n                $exists,\n                $genesis\n              } from 'rootverse+bfe:src/symbols.ts';\n\n              import type {\n                Entries,\n                LiteralUnion,\n                OmitIndexSignature,\n                Promisable,\n                StringKeyOf\n              } from 'type-fest';\n            ", Options: []any{map[string]any{"alphabetize": map[string]any{"order": "asc", "orderImportKind": "asc", "caseInsensitive": true}, "named": map[string]any{"enabled": true, "types": "types-last"}, "groups": []any{"builtin", "external", "internal", []any{"parent", "sibling", "index"}, []any{"object", "type"}}, "pathGroups": []any{map[string]any{"pattern": "multiverse{*,*/**}", "group": "external", "position": "after"}, map[string]any{"pattern": "rootverse{*,*/**}", "group": "external", "position": "after"}, map[string]any{"pattern": "universe{*,*/**}", "group": "external", "position": "after"}}, "distinctGroup": true, "pathGroupsExcludedImportTypes": []any{"builtin", "object"}, "newlines-between": "always-and-inside-groups", "newlines-between-types": "never", "sortTypesGroup": true, "consolidateIslands": "inside-groups"}}},
			// Upstream case 1:30.
			{Code: "\n              import makeVanillaYargs from 'yargs/yargs';\n              import { createDebugLogger } from 'multiverse+rejoinder';\n              import { globalDebuggerNamespace } from 'rootverse+bfe:src/constant.ts';\n              import { ErrorMessage, type KeyValueEntry } from 'rootverse+bfe:src/error.ts';\n              import { $artificiallyInvoked } from 'rootverse+bfe:src/symbols.ts';\n\n              import type {\n                Entries,\n                LiteralUnion,\n                OmitIndexSignature,\n                Promisable,\n                StringKeyOf\n              } from 'type-fest';\n            ", Options: []any{map[string]any{"alphabetize": map[string]any{"order": "asc", "orderImportKind": "asc", "caseInsensitive": true}, "named": map[string]any{"enabled": true, "types": "types-last"}, "groups": []any{"builtin", "external", "internal", []any{"parent", "sibling", "index"}, []any{"object", "type"}}, "pathGroups": []any{map[string]any{"pattern": "multiverse{*,*/**}", "group": "external", "position": "after"}, map[string]any{"pattern": "rootverse{*,*/**}", "group": "external", "position": "after"}, map[string]any{"pattern": "universe{*,*/**}", "group": "external", "position": "after"}}, "distinctGroup": true, "pathGroupsExcludedImportTypes": []any{"builtin", "object"}, "newlines-between": "never", "newlines-between-types": "always-and-inside-groups", "sortTypesGroup": true, "consolidateIslands": "inside-groups"}}},
			// Upstream case 1:31.
			{Code: "\n              import c from 'Bar';\n              import d from 'bar';\n\n              import {\n                aa,\n                bb,\n                cc,\n                dd,\n                ee,\n                ff,\n                gg\n              } from 'baz';\n\n              import {\n                hh,\n                ii,\n                jj,\n                kk,\n                ll,\n                mm,\n                nn\n              } from 'fizz';\n\n              import a from 'foo';\n              import b from 'dirA/bar';\n              import index from './';\n\n              import type { AA,\n                BB, CC } from 'abc';\n\n              import type { Z } from 'fizz';\n\n              import type {\n                A,\n                B\n              } from 'foo';\n\n              import type { C2 } from 'dirB/Bar';\n\n              import type {\n                D2,\n                X2,\n                Y2\n              } from 'dirB/bar';\n\n              import type { E2 } from 'dirB/baz';\n\n              import type { C3 } from 'dirC/Bar';\n\n              import type {\n                D3,\n                X3,\n                Y3\n              } from 'dirC/bar';\n\n              import type { E3 } from 'dirC/baz';\n              import type { F3 } from 'dirC/caz';\n\n              import type { C1 } from 'dirA/Bar';\n\n              import type {\n                D1,\n                X1,\n                Y1\n              } from 'dirA/bar';\n\n              import type { E1 } from 'dirA/baz';\n\n              import type { F } from './index.js';\n\n              import type { G } from './aaa.js';\n              import type { H } from './bbb';\n            ", Options: []any{map[string]any{"alphabetize": map[string]any{"order": "asc"}, "groups": []any{"external", "internal", "index", "type"}, "pathGroups": []any{map[string]any{"pattern": "dirA/**", "group": "internal", "position": "after"}, map[string]any{"pattern": "dirB/**", "group": "internal", "position": "before"}, map[string]any{"pattern": "dirC/**", "group": "internal"}}, "newlines-between": "never", "newlines-between-types": "always-and-inside-groups", "pathGroupsExcludedImportTypes": []any{}, "sortTypesGroup": true, "consolidateIslands": "inside-groups"}}},
			// Upstream case 1:32.
			{Code: "\n              import assert from 'assert';\n              import { isNativeError } from 'util/types';\n\n              import { runNoRejectOnBadExit } from '@-xun/run';\n              import { TrialError } from 'named-app-errors';\n              import { resolve as resolverLibrary } from 'resolve.exports';\n\n              import { toAbsolutePath, type AbsolutePath } from 'rootverse+project-utils:src/fs.ts';\n\n              import type { PackageJson } from 'type-fest';\n              // Some comment about remembering to do something\n              import type { XPackageJson } from 'rootverse:src/assets/config/_package.json.ts';\n            ", Options: []any{map[string]any{"alphabetize": map[string]any{"order": "asc", "orderImportKind": "asc", "caseInsensitive": true}, "named": map[string]any{"enabled": true, "types": "types-last"}, "groups": []any{"builtin", "external", "internal", []any{"parent", "sibling", "index"}, []any{"object", "type"}}, "pathGroups": []any{map[string]any{"pattern": "rootverse{*,*/**}", "group": "external", "position": "after"}}, "distinctGroup": true, "pathGroupsExcludedImportTypes": []any{"builtin", "object"}, "newlines-between": "always-and-inside-groups", "newlines-between-types": "never", "sortTypesGroup": true, "consolidateIslands": "inside-groups"}}},
			// Upstream case 1:33.
			{Code: "\n              import fs from 'fs';\n              import path from 'path';\n\n              import sibling from './foo';\n\n              import index from './';\n            ", Options: []any{map[string]any{"newlines-between": "always"}}},
			// Upstream case 1:34.
			{Code: "\n              import fs from 'fs';\n\n              import path from 'path';\n\n              import sibling from './foo';\n\n              import index from './';\n            ", Options: []any{map[string]any{"newlines-between": "always-and-inside-groups"}}},
			// Upstream case 1:35.
			{Code: "\n              import fs from 'fs';\n              import path from 'path';\n              import sibling from './foo';\n              import index from './';\n            ", Options: []any{map[string]any{"newlines-between": "never"}}},
			// Upstream case 1:36.
			{Code: "\n              import blist2 from 'blist';\n              import blist from 'BList';\n              import * as classnames from 'classnames';\n              import aTypes from 'prop-types';\n              import React, { PureComponent } from 'react';\n              import { compose, apply } from 'xcompose';\n            ", Options: []any{map[string]any{"alphabetize": map[string]any{"order": "asc", "caseInsensitive": true}}}},
			// Upstream case 1:37.
			{Code: "\n              import blist from 'BList';\n              import blist2 from 'blist';\n              import * as classnames from 'classnames';\n              import aTypes from 'prop-types';\n              import React, { PureComponent } from 'react';\n              import { compose, apply } from 'xcompose';\n            ", Options: []any{map[string]any{"alphabetize": map[string]any{"order": "asc", "caseInsensitive": false}}}},
			// Upstream case 1:38.
			{Code: "\n              import { apply, compose } from 'xcompose';\n            ", Options: []any{map[string]any{"named": true, "alphabetize": map[string]any{"order": "asc"}}}},
			// Upstream case 1:39.
			{Code: "\n              import fs from 'fs';\n              import path from 'path';\n              import './styles.css';\n            ", Options: []any{map[string]any{"warnOnUnassignedImports": true}}},
		},
		[]rule_tester.InvalidTestCase{},
	)
}
