// TestOrderUpstreamCore08 migrates the upstream core cases from import-js/eslint-plugin-import at 1a39fb8672c83f8781c3a97f02eee00a7a2f0253.
// It preserves upstream messages, source positions, options, and iterative autofix outputs.
// Framework-only parser/resolver settings use rslint native equivalents; tsgo lock-ins live in order_extras_*_test.go.
package order_test

import (
	"testing"

	"github.com/web-infra-dev/rslint/internal/plugins/import/fixtures"
	"github.com/web-infra-dev/rslint/internal/plugins/import/rules/order"
	"github.com/web-infra-dev/rslint/internal/rule_tester"
)

func TestOrderUpstreamCore08(t *testing.T) {
	rule_tester.RunRuleTester(
		fixtures.GetRootDir(),
		"tsconfig.json",
		t,
		&order.OrderRule,
		[]rule_tester.ValidTestCase{},
		[]rule_tester.InvalidTestCase{
			// Upstream case 0:65.
			{Code: "\n        import async from 'async';\n        var a = require('./value.js')(a);\n        import fs from 'fs';\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "order", Message: "`fs` import should occur before import of `async`", Line: 4, Column: 9, EndLine: 4, EndColumn: 29}}},
			// Upstream case 0:66.
			{Code: "\n        import async from 'async';\n        import './aa';\n        import fs from 'fs';\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "order", Message: "`fs` import should occur before import of `async`", Line: 4, Column: 9, EndLine: 4, EndColumn: 29}}},
			// Upstream case 0:67.
			{Code: "\n        import b from 'bar';\n        import c from 'Bar';\n        import a from 'foo';\n\n        import index from './';\n      ", Options: []any{map[string]any{"groups": []any{"external", "index"}, "alphabetize": map[string]any{"order": "asc"}}}, Output: []string{"\n        import c from 'Bar';\n        import b from 'bar';\n        import a from 'foo';\n\n        import index from './';\n      "}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "order", Message: "`Bar` import should occur before import of `bar`", Line: 3, Column: 9, EndLine: 3, EndColumn: 29}}},
			// Upstream case 0:68.
			{Code: "\n        import a from 'foo';\n        import c from 'Bar';\n        import b from 'bar';\n\n        import index from './';\n      ", Options: []any{map[string]any{"groups": []any{"external", "index"}, "alphabetize": map[string]any{"order": "desc"}}}, Output: []string{"\n        import a from 'foo';\n        import b from 'bar';\n        import c from 'Bar';\n\n        import index from './';\n      "}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "order", Message: "`bar` import should occur before import of `Bar`", Line: 4, Column: 9, EndLine: 4, EndColumn: 29}}},
			// Upstream case 0:69.
			{Code: "\n        import a from \"foo\";\n        import b from \"foo-bar\";\n        import c from \"foo/bar\";\n        import d from \"foo/barfoo\";\n      ", Options: []any{map[string]any{"alphabetize": map[string]any{"order": "asc"}}}, Output: []string{"\n        import a from \"foo\";\n        import c from \"foo/bar\";\n        import d from \"foo/barfoo\";\n        import b from \"foo-bar\";\n      "}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "order", Message: "`foo-bar` import should occur after import of `foo/barfoo`", Line: 3, Column: 9, EndLine: 3, EndColumn: 33}}},
			// Upstream case 0:70.
			{Code: "\n        import b from 'foo';\n        import a from 'Bar';\n\n        import index from './';\n      ", Options: []any{map[string]any{"groups": []any{"external", "index"}, "alphabetize": map[string]any{"order": "asc", "caseInsensitive": true}}}, Output: []string{"\n        import a from 'Bar';\n        import b from 'foo';\n\n        import index from './';\n      "}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "order", Message: "`Bar` import should occur before import of `foo`", Line: 3, Column: 9, EndLine: 3, EndColumn: 29}}},
			// Upstream case 0:71.
			{Code: "\n        import a from 'Bar';\n        import b from 'foo';\n\n        import index from './';\n      ", Options: []any{map[string]any{"groups": []any{"external", "index"}, "alphabetize": map[string]any{"order": "desc", "caseInsensitive": true}}}, Output: []string{"\n        import b from 'foo';\n        import a from 'Bar';\n\n        import index from './';\n      "}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "order", Message: "`foo` import should occur before import of `Bar`", Line: 3, Column: 9, EndLine: 3, EndColumn: 29}}},
			// Upstream case 0:72.
			{Code: "\n        const b = require('./b').get();\n        const a = require('./a');\n      ", Options: []any{map[string]any{"alphabetize": map[string]any{"order": "asc"}}}, Output: []string{"\n        const a = require('./a');\n        const b = require('./b').get();\n      "}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "order", Message: "`./a` import should occur before import of `./b`", Line: 3, Column: 19, EndLine: 3, EndColumn: 33}}},
			// Upstream case 0:73.
			{Code: "\n        import a from '../a';\n        import p from '..';\n      ", Options: []any{map[string]any{"groups": []any{"external", "index"}, "alphabetize": map[string]any{"order": "asc"}}}, Output: []string{"\n        import p from '..';\n        import a from '../a';\n      "}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "order", Message: "`..` import should occur before import of `../a`", Line: 3, Column: 9, EndLine: 3, EndColumn: 28}}},
			// Upstream case 0:74.
			{Code: "\n        import A from 'a';\n        import C from './c';\n      ", Options: []any{map[string]any{"newlines-between": "always", "distinctGroup": false, "pathGroupsExcludedImportTypes": []any{}}}, Output: []string{"\n        import A from 'a';\n\n        import C from './c';\n      "}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "groupNewline", Message: "There should be at least one empty line between import groups", Line: 2, Column: 9, EndLine: 2, EndColumn: 27}}},
			// Upstream case 0:75.
			{Code: "\n        import A from 'a';\n\n        import C from 'c';\n      ", Options: []any{map[string]any{"newlines-between": "always", "distinctGroup": false, "pathGroupsExcludedImportTypes": []any{}, "pathGroups": []any{map[string]any{"pattern": "a", "group": "external", "position": "before"}, map[string]any{"pattern": "c", "group": "external", "position": "after"}}}}, Output: []string{"\n        import A from 'a';\n        import C from 'c';\n      "}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "withinGroupNewline", Message: "There should be no empty line within import group", Line: 2, Column: 9, EndLine: 2, EndColumn: 27}}},
			// Upstream case 0:76.
			{Code: "\n        var { B, A: R } = require(\"./Z\");\n        import { O as G, D } from \"./Z\";\n        import { K, L, J } from \"./Z\";\n        export { Z, X, Y } from \"./Z\";\n      ", Options: []any{map[string]any{"named": true, "alphabetize": map[string]any{"order": "asc"}}}, Output: []string{"\n        var { A: R, B } = require(\"./Z\");\n        import { D, O as G } from \"./Z\";\n        import { J, K, L } from \"./Z\";\n        export { X, Y, Z } from \"./Z\";\n      "}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "order", Message: "`A` import should occur before import of `B`", Line: 2, Column: 18, EndLine: 2, EndColumn: 22}, {MessageId: "order", Message: "`D` import should occur before import of `O`", Line: 3, Column: 26, EndLine: 3, EndColumn: 27}, {MessageId: "order", Message: "`J` import should occur before import of `K`", Line: 4, Column: 24, EndLine: 4, EndColumn: 25}, {MessageId: "order", Message: "`Z` export should occur after export of `Y`", Line: 5, Column: 18, EndLine: 5, EndColumn: 19}}},
			// Upstream case 0:77.
			{Code: "\n        import { D, C } from \"./Z\";\n        var { B, A } = require(\"./Z\");\n        export { B, A };\n      ", Options: []any{map[string]any{"named": map[string]any{"require": false, "import": true, "export": true}, "alphabetize": map[string]any{"order": "asc"}}}, Output: []string{"\n        import { C, D } from \"./Z\";\n        var { B, A } = require(\"./Z\");\n        export { A, B };\n      "}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "order", Message: "`C` import should occur before import of `D`", Line: 2, Column: 21, EndLine: 2, EndColumn: 22}, {MessageId: "order", Message: "`A` export should occur before export of `B`", Line: 4, Column: 21, EndLine: 4, EndColumn: 22}}},
			// Upstream case 0:78.
			{Code: "\n        import { A as B, A as C, A } from \"./Z\";\n        export { A, A as D, A as B, A as C } from \"./Z\";\n        const { a: b, a: c, a } = require(\"./Z\");\n      ", Options: []any{map[string]any{"named": true, "alphabetize": map[string]any{"order": "asc"}}}, Output: []string{"\n        import { A, A as B, A as C } from \"./Z\";\n        export { A, A as B, A as C, A as D } from \"./Z\";\n        const { a, a: b, a: c } = require(\"./Z\");\n      "}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "order", Message: "`A` import should occur before import of `A as B`", Line: 2, Column: 34, EndLine: 2, EndColumn: 35}, {MessageId: "order", Message: "`A as D` export should occur after export of `A as C`", Line: 3, Column: 21, EndLine: 3, EndColumn: 27}, {MessageId: "order", Message: "`a` import should occur before import of `a as b`", Line: 4, Column: 29, EndLine: 4, EndColumn: 30}}},
			// Upstream case 0:79.
			{Code: "\n        import { A, B, C } from \"./Z\";\n        exports = { B, C, A };\n        module.exports = { c: C, a: A, b: B };\n      ", Options: []any{map[string]any{"named": map[string]any{"cjsExports": true}, "alphabetize": map[string]any{"order": "asc"}}}, Output: []string{"\n        import { A, B, C } from \"./Z\";\n        exports = { A, B, C };\n        module.exports = { a: A, b: B, c: C };\n      "}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "order", Message: "`A` export should occur before export of `B`", Line: 3, Column: 27, EndLine: 3, EndColumn: 28}, {MessageId: "order", Message: "`c` export should occur after export of `b`", Line: 4, Column: 28, EndLine: 4, EndColumn: 32}}},
			// Upstream case 0:80.
			{Code: "\n        exports.B = { };\n        module.exports.A = { };\n        module.exports.C = { };\n      ", Options: []any{map[string]any{"named": map[string]any{"cjsExports": true}, "alphabetize": map[string]any{"order": "asc"}}}, Output: []string{"\n        module.exports.A = { };\n        exports.B = { };\n        module.exports.C = { };\n      "}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "order", Message: "`A` export should occur before export of `B`", Line: 3, Column: 9, EndLine: 3, EndColumn: 31}}},
			// Upstream case 0:81.
			{Code: "\n        exports.A.C = { };\n        module.exports.A.A = { };\n        exports.A.B = { };\n      ", Options: []any{map[string]any{"named": map[string]any{"cjsExports": true}, "alphabetize": map[string]any{"order": "asc"}}}, Output: []string{"\n        module.exports.A.A = { };\n        exports.A.B = { };\n        exports.A.C = { };\n      "}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "order", Message: "`A.C` export should occur after export of `A.B`", Line: 2, Column: 9, EndLine: 2, EndColumn: 26}}},
			// Upstream case 0:82.
			{Code: "\n        const {\n          F: O,\n          O: B,\n          /* Hello World */\n          A: R\n        } = require(\"./Z\");\n        import {\n          Y,\n          X,\n        } from \"./Z\";\n        export {\n          Z, A,\n          B\n        } from \"./Z\";\n        module.exports = {\n          a: A, o: O,\n          b: B\n        };\n      ", Options: []any{map[string]any{"named": map[string]any{"enabled": true}, "alphabetize": map[string]any{"order": "asc"}}}, Output: []string{"\n        const {\n          /* Hello World */\n          A: R,\n          F: O,\n          O: B\n        } = require(\"./Z\");\n        import {\n          X,\n          Y,\n        } from \"./Z\";\n        export { A,\n          B,\n          Z\n        } from \"./Z\";\n        module.exports = {\n          a: A,\n          b: B, o: O\n        };\n      "}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "order", Message: "`A` import should occur before import of `F`", Line: 6, Column: 11, EndLine: 6, EndColumn: 15}, {MessageId: "order", Message: "`X` import should occur before import of `Y`", Line: 10, Column: 11, EndLine: 10, EndColumn: 12}, {MessageId: "order", Message: "`Z` export should occur after export of `B`", Line: 13, Column: 11, EndLine: 13, EndColumn: 12}, {MessageId: "order", Message: "`b` export should occur before export of `o`", Line: 18, Column: 11, EndLine: 18, EndColumn: 15}}},
			// Upstream case 0:83.
			{Code: "\n          const { cello } = require('./cello');\n          import { int } from './int';\n          const blah = require('./blah');\n          import { hello } from './hello';\n        ", Output: []string{"\n          import { int } from './int';\n          const { cello } = require('./cello');\n          const blah = require('./blah');\n          import { hello } from './hello';\n        ", "\n          import { int } from './int';\n          import { hello } from './hello';\n          const { cello } = require('./cello');\n          const blah = require('./blah');\n        "}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "order", Message: "`./int` import should occur before import of `./cello`", Line: 3, Column: 11, EndLine: 3, EndColumn: 39}, {MessageId: "order", Message: "`./hello` import should occur before import of `./cello`", Line: 5, Column: 11, EndLine: 5, EndColumn: 43}}},
			// Upstream case 0:84.
			{Code: "\n        var fs = require('fs');\n        var path = require('path');\n        var { util1, util2, util3 } = require('util');\n        var async = require('async');\n        var relParent1 = require('../foo');\n        var {\n          relParent21,\n          relParent22,\n          relParent23,\n          relParent24,\n        } = require('../');\n        var relParent3 = require('../bar');\n        var { sibling1,\n          sibling2, sibling3 } = require('./foo');\n        var sibling2 = require('./bar');\n        var sibling3 = require('./foobar');\n      ", Options: []any{map[string]any{"newlines-between": "always-and-inside-groups", "consolidateIslands": "inside-groups"}}, Output: []string{"\n        var fs = require('fs');\n        var path = require('path');\n        var { util1, util2, util3 } = require('util');\n\n        var async = require('async');\n\n        var relParent1 = require('../foo');\n\n        var {\n          relParent21,\n          relParent22,\n          relParent23,\n          relParent24,\n        } = require('../');\n\n        var relParent3 = require('../bar');\n\n        var { sibling1,\n          sibling2, sibling3 } = require('./foo');\n\n        var sibling2 = require('./bar');\n        var sibling3 = require('./foobar');\n      "}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "groupNewline", Message: "There should be at least one empty line between import groups", Line: 4, Column: 39, EndLine: 4, EndColumn: 54}, {MessageId: "groupNewline", Message: "There should be at least one empty line between import groups", Line: 5, Column: 21, EndLine: 5, EndColumn: 37}, {MessageId: "consolidate", Message: "There should be at least one empty line between this import and the multi-line import that follows it", Line: 6, Column: 26, EndLine: 6, EndColumn: 43}, {MessageId: "consolidate", Message: "There should be at least one empty line between this multi-line import and the import that follows it", Line: 12, Column: 13, EndLine: 12, EndColumn: 27}, {MessageId: "groupNewline", Message: "There should be at least one empty line between import groups", Line: 13, Column: 26, EndLine: 13, EndColumn: 43}, {MessageId: "consolidate", Message: "There should be at least one empty line between this multi-line import and the import that follows it", Line: 15, Column: 34, EndLine: 15, EndColumn: 50}}},
		},
	)
}
