// TestOrderUpstreamCore06 migrates the upstream core cases from import-js/eslint-plugin-import at 1a39fb8672c83f8781c3a97f02eee00a7a2f0253.
// It preserves upstream messages, source positions, options, and iterative autofix outputs.
// Framework-only parser/resolver settings use rslint native equivalents; tsgo lock-ins live in order_extras_*_test.go.
package order_test

import (
	"testing"

	"github.com/web-infra-dev/rslint/internal/plugins/import/fixtures"
	"github.com/web-infra-dev/rslint/internal/plugins/import/rules/order"
	"github.com/web-infra-dev/rslint/internal/rule_tester"
)

func TestOrderUpstreamCore06(t *testing.T) {
	rule_tester.RunRuleTester(
		fixtures.GetRootDir(),
		"tsconfig.json",
		t,
		&order.OrderRule,
		[]rule_tester.ValidTestCase{},
		[]rule_tester.InvalidTestCase{
			// Upstream case 0:25.
			{Code: "\n        import async, {foo1} from 'async';\n        import relParent2, {foo2} from '../foo/bar';\n        var fs = require('fs');\n        var relParent1 = require('../foo');\n        var relParent3 = require('../');\n        import sibling, {foo3} from './foo';\n        var index = require('./');\n      ", Output: []string{"\n        import async, {foo1} from 'async';\n        import relParent2, {foo2} from '../foo/bar';\n        import sibling, {foo3} from './foo';\n        var fs = require('fs');\n        var relParent1 = require('../foo');\n        var relParent3 = require('../');\n        var index = require('./');\n      "}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "order", Message: "`./foo` import should occur before import of `fs`", Line: 7, Column: 9, EndLine: 7, EndColumn: 45}}},
			// Upstream case 0:26.
			{Code: "\n        var fs = require('fs');\n        import async, {foo1} from 'async';\n        import relParent2, {foo2} from '../foo/bar';\n      ", Output: []string{"\n        import async, {foo1} from 'async';\n        import relParent2, {foo2} from '../foo/bar';\n        var fs = require('fs');\n      "}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "order", Message: "`fs` import should occur after import of `../foo/bar`", Line: 2, Column: 18, EndLine: 2, EndColumn: 31}}},
			// Upstream case 0:27.
			{Code: "\n          var fs = require('fs');\n          import async, {foo1} from 'async';\n          import bar = require(\"../foo/bar\");\n        ", Output: []string{"\n          import async, {foo1} from 'async';\n          import bar = require(\"../foo/bar\");\n          var fs = require('fs');\n        "}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "order", Message: "`fs` import should occur after import of `../foo/bar`", Line: 2, Column: 20, EndLine: 2, EndColumn: 33}}},
			// Upstream case 0:28.
			{Code: "\n          var async = require('async');\n          var fs = require('fs');\n        ", Output: []string{"\n          var fs = require('fs');\n          var async = require('async');\n        "}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "order", Message: "`fs` import should occur before import of `async`", Line: 3, Column: 20, EndLine: 3, EndColumn: 33}}},
			// Upstream case 0:29.
			{Code: "\n          import sync = require('sync');\n          import async, {foo1} from 'async';\n\n          import index from './';\n        ", Options: []any{map[string]any{"groups": []any{"external", "index"}, "alphabetize": map[string]any{"order": "asc"}}}, Output: []string{"\n          import async, {foo1} from 'async';\n          import sync = require('sync');\n\n          import index from './';\n        "}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "order", Message: "`async` import should occur before import of `sync`", Line: 3, Column: 11, EndLine: 3, EndColumn: 45}}},
			// Upstream case 0:30.
			{Code: "\n          import log = console.log;\n          import blah = require('./blah');", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "order", Message: "`./blah` import should occur before import of `console.log`", Line: 3, Column: 11, EndLine: 3, EndColumn: 43}}},
			// Upstream case 0:31.
			{Code: "\n        import { Button } from '-/components/Button';\n        import { add } from './helper';\n        import fs from 'fs';\n      ", Options: []any{map[string]any{"groups": []any{"builtin", "external", "unknown", "parent", "sibling", "index"}}}, Output: []string{"\n        import fs from 'fs';\n        import { Button } from '-/components/Button';\n        import { add } from './helper';\n      "}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "order", Message: "`fs` import should occur before import of `-/components/Button`", Line: 4, Column: 9, EndLine: 4, EndColumn: 29}}},
			// Upstream case 0:32.
			{Code: "\n        import fs from 'fs';\n        import { Button } from '-/components/Button';\n        import { LinkButton } from '-/components/Link';\n        import { add } from './helper';\n      ", Options: []any{map[string]any{"groups": []any{"builtin", "external", "unknown", "parent", "sibling", "index"}, "newlines-between": "always"}}, Output: []string{"\n        import fs from 'fs';\n\n        import { Button } from '-/components/Button';\n        import { LinkButton } from '-/components/Link';\n\n        import { add } from './helper';\n      "}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "groupNewline", Message: "There should be at least one empty line between import groups", Line: 2, Column: 9, EndLine: 2, EndColumn: 29}, {MessageId: "groupNewline", Message: "There should be at least one empty line between import groups", Line: 4, Column: 9, EndLine: 4, EndColumn: 56}}},
			// Upstream case 0:33.
			{Code: "\n        var fs = require('fs');\n        var index = require('./');\n        var path = require('path');\n\n        var sibling = require('./foo');\n\n        var relParent1 = require('../foo');\n        var relParent3 = require('../');\n        var async = require('async');\n      ", Options: []any{map[string]any{"groups": []any{[]any{"builtin", "index"}, []any{"sibling"}, []any{"parent", "external"}}, "newlines-between": "never"}}, Output: []string{"\n        var fs = require('fs');\n        var index = require('./');\n        var path = require('path');\n        var sibling = require('./foo');\n        var relParent1 = require('../foo');\n        var relParent3 = require('../');\n        var async = require('async');\n      "}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "groupNewline", Message: "There should be no empty line between import groups", Line: 4, Column: 20, EndLine: 4, EndColumn: 35}, {MessageId: "groupNewline", Message: "There should be no empty line between import groups", Line: 6, Column: 23, EndLine: 6, EndColumn: 39}}},
			// Upstream case 0:34.
			{Code: "\n        var fs = require('fs'); /* comment */\n\n        var index = require('./');\n      ", Options: []any{map[string]any{"groups": []any{[]any{"builtin"}, []any{"index"}}, "newlines-between": "never"}}, Output: []string{"\n        var fs = require('fs'); /* comment */\n        var index = require('./');\n      "}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "groupNewline", Message: "There should be no empty line between import groups", Line: 2, Column: 18, EndLine: 2, EndColumn: 31}}},
			// Upstream case 0:35.
			{Code: "\n        var fs = require('fs'); /* multi-line\n        comment */\n\n        var index = require('./');\n      ", Options: []any{map[string]any{"groups": []any{[]any{"builtin"}, []any{"index"}}, "newlines-between": "never"}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "groupNewline", Message: "There should be no empty line between import groups", Line: 2, Column: 18, EndLine: 2, EndColumn: 31}}},
			// Upstream case 0:36.
			{Code: "\n        var fs = require('fs');\n        var index = require('./');\n        var path = require('path');\n        var sibling = require('./foo');\n        var relParent1 = require('../foo');\n        var relParent3 = require('../');\n        var async = require('async');\n      ", Options: []any{map[string]any{"groups": []any{[]any{"builtin", "index"}, []any{"sibling"}, []any{"parent", "external"}}, "newlines-between": "always"}}, Output: []string{"\n        var fs = require('fs');\n        var index = require('./');\n        var path = require('path');\n\n        var sibling = require('./foo');\n\n        var relParent1 = require('../foo');\n        var relParent3 = require('../');\n        var async = require('async');\n      "}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "groupNewline", Message: "There should be at least one empty line between import groups", Line: 4, Column: 20, EndLine: 4, EndColumn: 35}, {MessageId: "groupNewline", Message: "There should be at least one empty line between import groups", Line: 5, Column: 23, EndLine: 5, EndColumn: 39}}},
			// Upstream case 0:37.
			{Code: "\n        var fs = require('fs');\n\n        var path = require('path');\n        var index = require('./');\n\n        var sibling = require('./foo');\n\n        var async = require('async');\n      ", Options: []any{map[string]any{"groups": []any{[]any{"builtin", "index"}, []any{"sibling", "parent", "external"}}, "newlines-between": "always"}}, Output: []string{"\n        var fs = require('fs');\n        var path = require('path');\n        var index = require('./');\n\n        var sibling = require('./foo');\n        var async = require('async');\n      "}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "withinGroupNewline", Message: "There should be no empty line within import group", Line: 2, Column: 18, EndLine: 2, EndColumn: 31}, {MessageId: "withinGroupNewline", Message: "There should be no empty line within import group", Line: 7, Column: 23, EndLine: 7, EndColumn: 39}}},
			// Upstream case 0:38.
			{Code: "\n        import path from 'path';\n        import 'loud-rejection';\n\n        import 'something-else';\n        import _ from 'lodash';\n      ", Options: []any{map[string]any{"newlines-between": "never", "warnOnUnassignedImports": false}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "groupNewline", Message: "There should be no empty line between import groups", Line: 2, Column: 9, EndLine: 2, EndColumn: 33}}},
			// Upstream case 0:39.
			{Code: "\n        import path from 'path';\n        import 'loud-rejection';\n\n        import 'something-else';\n        import _ from 'lodash';\n      ", Options: []any{map[string]any{"newlines-between": "never", "warnOnUnassignedImports": true}}, Output: []string{"\n        import path from 'path';\n        import 'loud-rejection';\n        import 'something-else';\n        import _ from 'lodash';\n      "}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "groupNewline", Message: "There should be no empty line between import groups", Line: 3, Column: 9, EndLine: 3, EndColumn: 33}}},
			// Upstream case 0:40.
			{Code: "\n        import path from 'path';\n        export const abc = 123;\n\n        import 'something-else';\n        import _ from 'lodash';\n      ", Options: []any{map[string]any{"newlines-between": "never"}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "groupNewline", Message: "There should be no empty line between import groups", Line: 2, Column: 9, EndLine: 2, EndColumn: 33}}},
			// Upstream case 0:41.
			{Code: "\n        import path from 'path';\n        import 'loud-rejection';\n        import 'something-else';\n        import _ from 'lodash';\n      ", Options: []any{map[string]any{"newlines-between": "always"}}, Output: []string{"\n        import path from 'path';\n\n        import 'loud-rejection';\n        import 'something-else';\n        import _ from 'lodash';\n      "}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "groupNewline", Message: "There should be at least one empty line between import groups", Line: 2, Column: 9, EndLine: 2, EndColumn: 33}}},
			// Upstream case 0:42.
			{Code: "\n        import path from 'path'; // comment\n        import _ from 'lodash';\n      ", Options: []any{map[string]any{"newlines-between": "always"}}, Output: []string{"\n        import path from 'path'; // comment\n\n        import _ from 'lodash';\n      "}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "groupNewline", Message: "There should be at least one empty line between import groups", Line: 2, Column: 9, EndLine: 2, EndColumn: 33}}},
			// Upstream case 0:43.
			{Code: "\n        import path from 'path'; /* comment */ /* comment */\n        import _ from 'lodash';\n      ", Options: []any{map[string]any{"newlines-between": "always"}}, Output: []string{"\n        import path from 'path'; /* comment */ /* comment */\n\n        import _ from 'lodash';\n      "}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "groupNewline", Message: "There should be at least one empty line between import groups", Line: 2, Column: 9, EndLine: 2, EndColumn: 33}}},
			// Upstream case 0:44.
			{Code: "\n        import path from 'path'; /* 1\n        2 */\n        import _ from 'lodash';\n      ", Options: []any{map[string]any{"newlines-between": "always"}}, Output: []string{"\n        import path from 'path';\n /* 1\n        2 */\n        import _ from 'lodash';\n      ", "\n        import path from 'path';\n\n /* 1\n        2 */\n        import _ from 'lodash';\n      "}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "groupNewline", Message: "There should be at least one empty line between import groups", Line: 2, Column: 9, EndLine: 2, EndColumn: 33}}},
		},
	)
}
