// Generated by scripts/sync-releases.mjs. Do not edit.
export const generatedBuildInfo = {
  "version": "unreleased",
  "typescript": {
    "commit": "1f70213d4922b434345f639b441681e470c7cfc1",
    "releaseVersion": null
  }
} as const;
