// Regenerate with: node generate.mjs /path/to/eslint-plugin-n-v18.3.0
// Restored from https://github.com/web-infra-dev/rslint/pull/2234 and adapted for indexed data.
import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { execFileSync } from 'node:child_process';

const upstream = resolve(process.argv[2]);
const pkg = JSON.parse(
  await readFile(resolve(upstream, 'package.json'), 'utf8'),
);
if (pkg.name !== 'eslint-plugin-n' || pkg.version !== '18.3.0') {
  throw new Error(
    'Expected an eslint-plugin-n v18.3.0 checkout with dependencies installed',
  );
}
const load = (file) => import(pathToFileURL(resolve(upstream, file)).href);
const { NodeBuiltinGlobals, NodeBuiltinModules, NodeBuiltinImportMeta } =
  await load('lib/unsupported-features/node-builtins.js');
const { default: rule } = await load(
  'lib/rules/no-unsupported-features/node-builtins.js',
);
const { READ, CALL, CONSTRUCT } = await load(
  'node_modules/@eslint-community/eslint-utils/index.mjs',
);
const { default: semver } = await load('node_modules/semver/index.js');

const quote = JSON.stringify;
const texts = [''];
const versions = [''];
const textIndex = new Map([['', 0]]);
const versionIndex = new Map([['', 0]]);
function intern(values, index, value) {
  if (!index.has(value)) {
    index.set(value, values.length);
    values.push(value);
  }
  return index.get(value);
}
const textID = (value) => intern(texts, textIndex, value);
const versionID = (values) =>
  intern(versions, versionIndex, semver.rsort([...(values ?? [])]).join(',')); // cspell:ignore rsort

// The first three nodes are the roots for globals, modules, and import.meta.
const roots = [NodeBuiltinGlobals, NodeBuiltinModules, NodeBuiltinImportMeta];
const nodes = roots.map(() => [0, 0]);
const features = [];
const aliases = [];
function visit(tree, id, stack) {
  stack = new Map(stack).set(tree, id);
  for (const [kind, value] of [
    [READ, 0],
    [CALL, 1],
    [CONSTRUCT, 2],
  ]) {
    if (tree[kind]) {
      features.push([
        id,
        versionID(tree[kind].supported),
        versionID(tree[kind].experimental),
        value,
      ]);
    }
  }
  for (const [text, child] of Object.entries(tree)) {
    const label = textID(text);
    if (stack.has(child)) {
      aliases.push([id, label, stack.get(child)]);
    } else {
      const childID = nodes.length;
      nodes.push([id, label]);
      visit(child, childID, stack);
    }
  }
}
roots.forEach((root, id) => visit(root, id, new Map()));
for (const [name, values] of Object.entries({
  texts,
  versions,
  nodes,
  features,
  aliases,
})) {
  if (values.length > 65536) throw new Error(`${name} exceeds uint16 indexes`);
}

let output = `// Code generated by generate.mjs from eslint-plugin-n v18.3.0; DO NOT EDIT.
// https://github.com/eslint-community/eslint-plugin-n/tree/v18.3.0/lib/unsupported-features
// cspell:ignore CLEVEL Cipheriv Decipheriv Diffie Fips Keypress Naptr Spkac Tlsa Uncloneable alpn btlazy btopt btultra cpus debuglog dfast diffie dlopen execve fdatasync fips freemem initgroups loadavg onresourcetimingbufferfull ppid readv timerify totalmem webcrypto
package node_builtins

`;
for (const [name, type, values, render] of [
  ['builtinTexts', 'string', texts, quote],
  ['builtinVersions', 'string', versions, quote],
  ['builtinNodes', 'builtinNode', nodes, (entry) => `{${entry.join(', ')}}`],
  [
    'builtinFeatures',
    'builtinFeature',
    features,
    (entry) => `{${entry.join(', ')}}`,
  ],
  [
    'builtinAliases',
    'builtinAlias',
    aliases,
    (entry) => `{${entry.join(', ')}}`,
  ],
]) {
  output += `var ${name} = [...]${type}{\n`;
  for (const value of values) output += `\t${render(value)},\n`;
  output += '}\n\n';
}
const dataFile = new URL('apis_generated.go', import.meta.url);
await writeFile(dataFile, output);
execFileSync('gofmt', ['-w', dataFile.pathname]);
await writeFile(
  new URL('node_builtins.schema.json', import.meta.url),
  JSON.stringify(
    { type: 'array', items: rule.meta.schema, minItems: 0, maxItems: 1 },
    null,
    2,
  ) + '\n',
);
