// Code generated by tools/gen_shims. DO NOT EDIT.

package ls

import "context"
import "github.com/microsoft/typescript-go/internal/ast"
import "github.com/microsoft/typescript-go/internal/compiler"
import "github.com/microsoft/typescript-go/internal/core"
import "github.com/microsoft/typescript-go/internal/ls"
import "github.com/microsoft/typescript-go/internal/lsp/lsproto"
import _ "unsafe"

type CandidateOrTypeInfo = ls.CandidateOrTypeInfo

//go:linkname ComparePositions github.com/microsoft/typescript-go/internal/ls.ComparePositions
func ComparePositions(pos lsproto.Position, other lsproto.Position) int

//go:linkname CompareRanges github.com/microsoft/typescript-go/internal/ls.CompareRanges
func CompareRanges(lsRange *lsproto.Range, other *lsproto.Range) int

type CompletionKind = ls.CompletionKind

const CompletionKindGlobal = ls.CompletionKindGlobal
const CompletionKindMemberLike = ls.CompletionKindMemberLike
const CompletionKindNone = ls.CompletionKindNone
const CompletionKindObjectPropertyDeclaration = ls.CompletionKindObjectPropertyDeclaration
const CompletionKindPropertyAccess = ls.CompletionKindPropertyAccess
const CompletionKindString = ls.CompletionKindString

type CompletionsTriggerCharacter = ls.CompletionsTriggerCharacter

//go:linkname ComputeLineStarts github.com/microsoft/typescript-go/internal/ls.ComputeLineStarts
func ComputeLineStarts(text string) *ls.LineMap

type Converters = ls.Converters
type DeclarationInfo = ls.DeclarationInfo
type Definition = ls.Definition

//go:linkname DocumentURIToFileName github.com/microsoft/typescript-go/internal/ls.DocumentURIToFileName
func DocumentURIToFileName(uri lsproto.DocumentUri) string

var ErrNoSourceFile = ls.ErrNoSourceFile
var ErrNoTokenAtPosition = ls.ErrNoTokenAtPosition

type ExportInfo = ls.ExportInfo
type ExportKind = ls.ExportKind

const ExportKindDefault = ls.ExportKindDefault
const ExportKindExportEquals = ls.ExportKindExportEquals
const ExportKindNamed = ls.ExportKindNamed

//go:linkname FileNameToDocumentURI github.com/microsoft/typescript-go/internal/ls.FileNameToDocumentURI
func FileNameToDocumentURI(fileName string) lsproto.DocumentUri

type Host = ls.Host

//go:linkname IsInString github.com/microsoft/typescript-go/internal/ls.IsInString
func IsInString(sourceFile *ast.SourceFile, position int, previousToken *ast.Node) bool

type JsxAttributeCompletionStyle = ls.JsxAttributeCompletionStyle

const JsxAttributeCompletionStyleAuto = ls.JsxAttributeCompletionStyleAuto
const JsxAttributeCompletionStyleBraces = ls.JsxAttributeCompletionStyleBraces
const JsxAttributeCompletionStyleNone = ls.JsxAttributeCompletionStyleNone

type KeywordCompletionFilters = ls.KeywordCompletionFilters

const KeywordCompletionFiltersAll = ls.KeywordCompletionFiltersAll
const KeywordCompletionFiltersClassElementKeywords = ls.KeywordCompletionFiltersClassElementKeywords
const KeywordCompletionFiltersConstructorParameterKeywords = ls.KeywordCompletionFiltersConstructorParameterKeywords
const KeywordCompletionFiltersFunctionLikeBodyKeywords = ls.KeywordCompletionFiltersFunctionLikeBodyKeywords
const KeywordCompletionFiltersInterfaceElementKeywords = ls.KeywordCompletionFiltersInterfaceElementKeywords
const KeywordCompletionFiltersLast = ls.KeywordCompletionFiltersLast
const KeywordCompletionFiltersNone = ls.KeywordCompletionFiltersNone
const KeywordCompletionFiltersTypeAssertionKeywords = ls.KeywordCompletionFiltersTypeAssertionKeywords
const KeywordCompletionFiltersTypeKeyword = ls.KeywordCompletionFiltersTypeKeyword
const KeywordCompletionFiltersTypeKeywords = ls.KeywordCompletionFiltersTypeKeywords

//go:linkname LanguageKindToScriptKind github.com/microsoft/typescript-go/internal/ls.LanguageKindToScriptKind
func LanguageKindToScriptKind(languageID lsproto.LanguageKind) core.ScriptKind

type LanguageService = ls.LanguageService
type LineMap = ls.LineMap
type Location = ls.Location

//go:linkname NewConverters github.com/microsoft/typescript-go/internal/ls.NewConverters
func NewConverters(positionEncoding lsproto.PositionEncodingKind, getLineMap func(fileName string) *ls.LineMap) *ls.Converters

//go:linkname NewLanguageService github.com/microsoft/typescript-go/internal/ls.NewLanguageService
func NewLanguageService(host ls.Host) *ls.LanguageService

type PossibleTypeArgumentInfo = ls.PossibleTypeArgumentInfo

//go:linkname ProvideWorkspaceSymbols github.com/microsoft/typescript-go/internal/ls.ProvideWorkspaceSymbols
func ProvideWorkspaceSymbols(ctx context.Context, programs []*compiler.Program, converters *ls.Converters, query string) (lsproto.WorkspaceSymbolResponse, error)

//go:linkname RangeContainsRange github.com/microsoft/typescript-go/internal/ls.RangeContainsRange
func RangeContainsRange(r1 core.TextRange, r2 core.TextRange) bool

type Script = ls.Script
type ScriptElementKind = ls.ScriptElementKind

const ScriptElementKindAlias = ls.ScriptElementKindAlias
const ScriptElementKindCallSignatureElement = ls.ScriptElementKindCallSignatureElement
const ScriptElementKindClassElement = ls.ScriptElementKindClassElement
const ScriptElementKindConstElement = ls.ScriptElementKindConstElement
const ScriptElementKindConstructSignatureElement = ls.ScriptElementKindConstructSignatureElement
const ScriptElementKindConstructorImplementationElement = ls.ScriptElementKindConstructorImplementationElement
const ScriptElementKindDirectory = ls.ScriptElementKindDirectory
const ScriptElementKindEnumElement = ls.ScriptElementKindEnumElement
const ScriptElementKindEnumMemberElement = ls.ScriptElementKindEnumMemberElement
const ScriptElementKindExternalModuleName = ls.ScriptElementKindExternalModuleName
const ScriptElementKindFunctionElement = ls.ScriptElementKindFunctionElement
const ScriptElementKindIndexSignatureElement = ls.ScriptElementKindIndexSignatureElement
const ScriptElementKindInterfaceElement = ls.ScriptElementKindInterfaceElement
const ScriptElementKindKeyword = ls.ScriptElementKindKeyword
const ScriptElementKindLabel = ls.ScriptElementKindLabel
const ScriptElementKindLetElement = ls.ScriptElementKindLetElement
const ScriptElementKindLink = ls.ScriptElementKindLink
const ScriptElementKindLinkName = ls.ScriptElementKindLinkName
const ScriptElementKindLinkText = ls.ScriptElementKindLinkText
const ScriptElementKindLocalClassElement = ls.ScriptElementKindLocalClassElement
const ScriptElementKindLocalFunctionElement = ls.ScriptElementKindLocalFunctionElement
const ScriptElementKindLocalVariableElement = ls.ScriptElementKindLocalVariableElement
const ScriptElementKindMemberAccessorVariableElement = ls.ScriptElementKindMemberAccessorVariableElement
const ScriptElementKindMemberFunctionElement = ls.ScriptElementKindMemberFunctionElement
const ScriptElementKindMemberGetAccessorElement = ls.ScriptElementKindMemberGetAccessorElement
const ScriptElementKindMemberSetAccessorElement = ls.ScriptElementKindMemberSetAccessorElement
const ScriptElementKindMemberVariableElement = ls.ScriptElementKindMemberVariableElement

type ScriptElementKindModifier = ls.ScriptElementKindModifier

const ScriptElementKindModifierAbstract = ls.ScriptElementKindModifierAbstract
const ScriptElementKindModifierAmbient = ls.ScriptElementKindModifierAmbient
const ScriptElementKindModifierCjs = ls.ScriptElementKindModifierCjs
const ScriptElementKindModifierCts = ls.ScriptElementKindModifierCts
const ScriptElementKindModifierDcts = ls.ScriptElementKindModifierDcts
const ScriptElementKindModifierDeprecated = ls.ScriptElementKindModifierDeprecated
const ScriptElementKindModifierDmts = ls.ScriptElementKindModifierDmts
const ScriptElementKindModifierDts = ls.ScriptElementKindModifierDts
const ScriptElementKindModifierExported = ls.ScriptElementKindModifierExported
const ScriptElementKindModifierJs = ls.ScriptElementKindModifierJs
const ScriptElementKindModifierJson = ls.ScriptElementKindModifierJson
const ScriptElementKindModifierJsx = ls.ScriptElementKindModifierJsx
const ScriptElementKindModifierMjs = ls.ScriptElementKindModifierMjs
const ScriptElementKindModifierMts = ls.ScriptElementKindModifierMts
const ScriptElementKindModifierNone = ls.ScriptElementKindModifierNone
const ScriptElementKindModifierOptional = ls.ScriptElementKindModifierOptional
const ScriptElementKindModifierPrivate = ls.ScriptElementKindModifierPrivate
const ScriptElementKindModifierProtected = ls.ScriptElementKindModifierProtected
const ScriptElementKindModifierPublic = ls.ScriptElementKindModifierPublic
const ScriptElementKindModifierStatic = ls.ScriptElementKindModifierStatic
const ScriptElementKindModifierTs = ls.ScriptElementKindModifierTs
const ScriptElementKindModifierTsx = ls.ScriptElementKindModifierTsx
const ScriptElementKindModuleElement = ls.ScriptElementKindModuleElement
const ScriptElementKindParameterElement = ls.ScriptElementKindParameterElement
const ScriptElementKindPrimitiveType = ls.ScriptElementKindPrimitiveType
const ScriptElementKindScriptElement = ls.ScriptElementKindScriptElement
const ScriptElementKindString = ls.ScriptElementKindString
const ScriptElementKindTypeElement = ls.ScriptElementKindTypeElement
const ScriptElementKindTypeParameterElement = ls.ScriptElementKindTypeParameterElement
const ScriptElementKindUnknown = ls.ScriptElementKindUnknown
const ScriptElementKindVariableAwaitUsingElement = ls.ScriptElementKindVariableAwaitUsingElement
const ScriptElementKindVariableElement = ls.ScriptElementKindVariableElement
const ScriptElementKindVariableUsingElement = ls.ScriptElementKindVariableUsingElement
const ScriptElementKindWarning = ls.ScriptElementKindWarning
const SortTextAutoImportSuggestions = ls.SortTextAutoImportSuggestions
const SortTextClassMemberSnippets = ls.SortTextClassMemberSnippets
const SortTextGlobalsOrKeywords = ls.SortTextGlobalsOrKeywords
const SortTextJavascriptIdentifiers = ls.SortTextJavascriptIdentifiers
const SortTextLocalDeclarationPriority = ls.SortTextLocalDeclarationPriority
const SortTextLocationPriority = ls.SortTextLocationPriority
const SortTextMemberDeclaredBySpreadAssignment = ls.SortTextMemberDeclaredBySpreadAssignment
const SortTextOptionalMember = ls.SortTextOptionalMember
const SortTextSuggestedClassMembers = ls.SortTextSuggestedClassMembers
const SourceClassMemberSnippet = ls.SourceClassMemberSnippet
const SourceObjectLiteralMemberWithComma = ls.SourceObjectLiteralMemberWithComma
const SourceObjectLiteralMethodSnippet = ls.SourceObjectLiteralMethodSnippet
const SourceSwitchCases = ls.SourceSwitchCases
const SourceThisProperty = ls.SourceThisProperty
const SourceTypeOnlyAlias = ls.SourceTypeOnlyAlias

type SymbolAndEntries = ls.SymbolAndEntries

var TriggerCharacters = ls.TriggerCharacters

type UserPreferences = ls.UserPreferences
