
// Code generated by tools/gen_shims. DO NOT EDIT.

package ls

import "context"
import "github.com/microsoft/typescript-go/internal/ast"
import "github.com/microsoft/typescript-go/internal/compiler"
import "github.com/microsoft/typescript-go/internal/core"
import "github.com/microsoft/typescript-go/internal/ls"
import "github.com/microsoft/typescript-go/internal/ls/lsconv"
import "github.com/microsoft/typescript-go/internal/ls/lsutil"
import "github.com/microsoft/typescript-go/internal/lsp/lsproto"
import "github.com/microsoft/typescript-go/internal/tspath"
import _ "unsafe"

type CallHierarchyDeclaration = ls.CallHierarchyDeclaration
type CandidateOrTypeInfo = ls.CandidateOrTypeInfo
type CodeAction = ls.CodeAction
type CodeFixContext = ls.CodeFixContext
type CodeFixProvider = ls.CodeFixProvider
type CombinedCodeActions = ls.CombinedCodeActions
//go:linkname CompareCompletionEntries github.com/microsoft/typescript-go/internal/ls.CompareCompletionEntries
func CompareCompletionEntries(a *lsproto.CompletionItem, b *lsproto.CompletionItem) int
type CompletionKind = ls.CompletionKind
const CompletionKindGlobal = ls.CompletionKindGlobal
const CompletionKindMemberLike = ls.CompletionKindMemberLike
const CompletionKindNone = ls.CompletionKindNone
const CompletionKindObjectPropertyDeclaration = ls.CompletionKindObjectPropertyDeclaration
const CompletionKindPropertyAccess = ls.CompletionKindPropertyAccess
const CompletionKindString = ls.CompletionKindString
type CompletionsTriggerCharacter = ls.CompletionsTriggerCharacter
type CrossProjectOrchestrator = ls.CrossProjectOrchestrator
type DeclarationInfo = ls.DeclarationInfo
type Definition = ls.Definition
type DefinitionKind = ls.DefinitionKind
var ErrNeedsAutoImports = ls.ErrNeedsAutoImports
var ErrNoSourceFile = ls.ErrNoSourceFile
var ErrNoTokenAtPosition = ls.ErrNoTokenAtPosition
type ExportInfo = ls.ExportInfo
type ExportKind = ls.ExportKind
const ExportKindDefault = ls.ExportKindDefault
const ExportKindExportEquals = ls.ExportKindExportEquals
const ExportKindModule = ls.ExportKindModule
const ExportKindNamed = ls.ExportKindNamed
const ExportKindUMD = ls.ExportKindUMD
type Host = ls.Host
type ImpExpKind = ls.ImpExpKind
const ImpExpKindExport = ls.ImpExpKindExport
const ImpExpKindImport = ls.ImpExpKindImport
const ImpExpKindUnknown = ls.ImpExpKindUnknown
type ImportExportSymbol = ls.ImportExportSymbol
var ImportFixProvider = ls.ImportFixProvider
type ImportTracker = ls.ImportTracker
type ImportsResult = ls.ImportsResult
//go:linkname IsInString github.com/microsoft/typescript-go/internal/ls.IsInString
func IsInString(sourceFile *ast.SourceFile, position int, previousToken *ast.Node) bool
type KeywordCompletionFilters = ls.KeywordCompletionFilters
const KeywordCompletionFiltersAll = ls.KeywordCompletionFiltersAll
const KeywordCompletionFiltersClassElementKeywords = ls.KeywordCompletionFiltersClassElementKeywords
const KeywordCompletionFiltersConstructorParameterKeywords = ls.KeywordCompletionFiltersConstructorParameterKeywords
const KeywordCompletionFiltersFunctionLikeBodyKeywords = ls.KeywordCompletionFiltersFunctionLikeBodyKeywords
const KeywordCompletionFiltersInterfaceElementKeywords = ls.KeywordCompletionFiltersInterfaceElementKeywords
const KeywordCompletionFiltersLast = ls.KeywordCompletionFiltersLast
const KeywordCompletionFiltersNone = ls.KeywordCompletionFiltersNone
const KeywordCompletionFiltersTypeAssertionKeywords = ls.KeywordCompletionFiltersTypeAssertionKeywords
const KeywordCompletionFiltersTypeKeyword = ls.KeywordCompletionFiltersTypeKeyword
const KeywordCompletionFiltersTypeKeywords = ls.KeywordCompletionFiltersTypeKeywords
type LanguageService = ls.LanguageService
type LocationAndSymbol = ls.LocationAndSymbol
type ModuleReference = ls.ModuleReference
type ModuleReferenceKind = ls.ModuleReferenceKind
const ModuleReferenceKindImplicit = ls.ModuleReferenceKindImplicit
const ModuleReferenceKindImport = ls.ModuleReferenceKindImport
const ModuleReferenceKindReference = ls.ModuleReferenceKindReference
//go:linkname NewLanguageService github.com/microsoft/typescript-go/internal/ls.NewLanguageService
func NewLanguageService(projectPath tspath.Path, program *compiler.Program, host ls.Host, activeFile string) *ls.LanguageService
type PossibleTypeArgumentInfo = ls.PossibleTypeArgumentInfo
type Project = ls.Project
//go:linkname ProvideWorkspaceSymbols github.com/microsoft/typescript-go/internal/ls.ProvideWorkspaceSymbols
func ProvideWorkspaceSymbols(ctx context.Context, programs []*compiler.Program, converters *lsconv.Converters, preferences *lsutil.UserPreferences, query string) (lsproto.WorkspaceSymbolResponse, error)
//go:linkname RangeContainsRange github.com/microsoft/typescript-go/internal/ls.RangeContainsRange
func RangeContainsRange(r1 core.TextRange, r2 core.TextRange) bool
type ReferenceEntry = ls.ReferenceEntry
type SortText = ls.SortText
const SortTextAutoImportSuggestions = ls.SortTextAutoImportSuggestions
const SortTextClassMemberSnippets = ls.SortTextClassMemberSnippets
const SortTextGlobalsOrKeywords = ls.SortTextGlobalsOrKeywords
const SortTextJavascriptIdentifiers = ls.SortTextJavascriptIdentifiers
const SortTextLocalDeclarationPriority = ls.SortTextLocalDeclarationPriority
const SortTextLocationPriority = ls.SortTextLocationPriority
const SortTextMemberDeclaredBySpreadAssignment = ls.SortTextMemberDeclaredBySpreadAssignment
const SortTextOptionalMember = ls.SortTextOptionalMember
const SortTextSuggestedClassMembers = ls.SortTextSuggestedClassMembers
const SourceClassMemberSnippet = ls.SourceClassMemberSnippet
const SourceObjectLiteralMemberWithComma = ls.SourceObjectLiteralMemberWithComma
const SourceObjectLiteralMethodSnippet = ls.SourceObjectLiteralMethodSnippet
const SourceSwitchCases = ls.SourceSwitchCases
const SourceThisProperty = ls.SourceThisProperty
const SourceTypeOnlyAlias = ls.SourceTypeOnlyAlias
type SymbolAndEntries = ls.SymbolAndEntries
type SymbolAndEntriesData = ls.SymbolAndEntriesData
var TriggerCharacters = ls.TriggerCharacters
