// TestRequireDefaultPropsUpstream migrates all 168 upstream cases from
// eslint-plugin-react v7.37.5 tests/lib/rules/require-default-props.js.
// Flow-only cases retain their input and expectations with an explicit skip.
// Parser-generated duplicates are represented once using TypeScript syntax.
// Extras live in require_default_props_extras_test.go.
package require_default_props

import (
	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/fixtures"
	"github.com/web-infra-dev/rslint/internal/rule_tester"
	"testing"
)

func TestRequireDefaultPropsUpstream(t *testing.T) {
	rule_tester.RunRuleTester(fixtures.GetRootDir(), "tsconfig.json", t, &RequireDefaultPropsRule, []rule_tester.ValidTestCase{
		// Upstream valid-1
		{Code: "\n        function MyStatelessComponent({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n        MyStatelessComponent.propTypes = {\n          foo: PropTypes.string.isRequired,\n          bar: PropTypes.string.isRequired\n        };\n      ", Tsx: true},
		// Upstream valid-2
		{Code: "\n        function MyStatelessComponent({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n        MyStatelessComponent.propTypes = {\n          foo: PropTypes.string,\n          bar: PropTypes.string.isRequired\n        };\n        MyStatelessComponent.defaultProps = {\n          foo: \"foo\"\n        };\n      ", Tsx: true},
		// Upstream valid-3
		{Code: "\n        function MyStatelessComponent({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n      ", Tsx: true},
		// Upstream valid-4
		{Code: "\n        function MyStatelessComponent({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n        MyStatelessComponent.propTypes = {\n          bar: PropTypes.string.isRequired\n        };\n        MyStatelessComponent.propTypes.foo = PropTypes.string;\n        MyStatelessComponent.defaultProps = {\n          foo: \"foo\"\n        };\n      ", Tsx: true},
		// Upstream valid-5
		{Code: "\n        function MyStatelessComponent({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n        MyStatelessComponent.propTypes = {\n          bar: PropTypes.string.isRequired\n        };\n        MyStatelessComponent.propTypes.foo = PropTypes.string;\n        MyStatelessComponent.defaultProps = {};\n        MyStatelessComponent.defaultProps.foo = \"foo\";\n      ", Tsx: true},
		// Upstream valid-6
		{Code: "\n        function MyStatelessComponent({ foo }) {\n          return <div>{foo}</div>;\n        }\n        MyStatelessComponent.propTypes = {};\n        MyStatelessComponent.propTypes.foo = PropTypes.string;\n        MyStatelessComponent.defaultProps = {};\n        MyStatelessComponent.defaultProps.foo = \"foo\";\n      ", Tsx: true},
		// Upstream valid-7
		{Code: "\n        const types = {\n          foo: PropTypes.string,\n          bar: PropTypes.string.isRequired\n        };\n        function MyStatelessComponent({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n        MyStatelessComponent.propTypes = types;\n        MyStatelessComponent.defaultProps = {\n          foo: \"foo\"\n        };\n      ", Tsx: true},
		// Upstream valid-8
		{Code: "\n        const defaults = {\n          foo: \"foo\"\n        };\n        function MyStatelessComponent({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n        MyStatelessComponent.propTypes = {\n          foo: PropTypes.string,\n          bar: PropTypes.string.isRequired\n        };\n        MyStatelessComponent.defaultProps = defaults;\n      ", Tsx: true},
		// Upstream valid-9
		{Code: "\n        const defaults = {\n          foo: \"foo\"\n        };\n        const types = {\n          foo: PropTypes.string,\n          bar: PropTypes.string.isRequired\n        };\n        function MyStatelessComponent({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n        MyStatelessComponent.propTypes = types;\n        MyStatelessComponent.defaultProps = defaults;\n      ", Tsx: true},
		// Upstream valid-10
		{Code: "\n        function MyStatelessComponent({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n        MyStatelessComponent.propTypes = {\n          foo: PropTypes.string,\n          bar: PropTypes.string.isRequired\n        };\n      ", Tsx: true, Options: []any{map[string]any{"ignoreFunctionalComponents": true}}},
		// Upstream valid-11
		{Code: "\n        function MyStatelessComponent({ foo = \"test\", bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n        MyStatelessComponent.propTypes = {\n          foo: PropTypes.string,\n          bar: PropTypes.string.isRequired\n        };\n      ", Tsx: true, Options: []any{map[string]any{"ignoreFunctionalComponents": true}}},
		// Upstream valid-12
		{Code: "\n        function MyStatelessComponent({ foo = \"test\", bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n        MyStatelessComponent.propTypes = {\n          foo: PropTypes.string,\n        };\n      ", Tsx: true, Options: []any{map[string]any{"forbidDefaultForRequired": true, "ignoreFunctionalComponents": true}}},
		// Upstream valid-13
		{Code: "\n        export function MyStatelessComponent({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n        MyStatelessComponent.propTypes = {\n          foo: PropTypes.string,\n          bar: PropTypes.string.isRequired\n        };\n      ", Tsx: true, Options: []any{map[string]any{"ignoreFunctionalComponents": true}}},
		// Upstream valid-14
		{Code: "\n        export default function MyStatelessComponent({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n        MyStatelessComponent.propTypes = {\n          foo: PropTypes.string,\n          bar: PropTypes.string.isRequired\n        };\n      ", Tsx: true, Options: []any{map[string]any{"ignoreFunctionalComponents": true}}},
		// Upstream valid-15
		{Code: "\n        function Hello(props) {\n          return <div>Hello {props.foo}</div>;\n        }\n        Hello.propTypes = {\n          foo: PropTypes.string\n        };\n        Hello.defaultProps = {\n          foo: 'bar;'\n        }\n      ", Tsx: true, Options: []any{map[string]any{"forbidDefaultForRequired": true}}},
		// Upstream valid-16
		{Code: "\n        function Hello({ foo = 'asdf', bar }) {\n          return <div>Hello {foo} and {bar}</div>;\n        }\n        Hello.propTypes = {\n          foo: PropTypes.string,\n          bar: PropTypes.string.isRequired\n        };\n      ", Tsx: true, Options: []any{map[string]any{"functions": "defaultArguments"}}},
		// Upstream valid-17
		{Code: "\n        function Hello({ foo = 'asdf', bar = 'qwer' }) {\n          return <div>Hello {foo} and {bar}</div>;\n        }\n        Hello.propTypes = {\n          foo: PropTypes.string,\n          bar: PropTypes.string\n        };\n      ", Tsx: true, Options: []any{map[string]any{"functions": "defaultArguments"}}},
		// Upstream valid-18
		{Code: "\n        function Hello(props) {\n          return <div>Hello {foo} and {bar}</div>;\n        }\n        Hello.propTypes = {\n          foo: PropTypes.string.isRequired,\n          bar: PropTypes.string.isRequired,\n        };\n      ", Tsx: true, Options: []any{map[string]any{"functions": "defaultArguments"}}},
		// Upstream valid-19
		{Code: "\n        function MyStatelessComponent({ foo, bar = 'asdf', ...props }) {\n          return <div>{foo}{bar}</div>;\n        }\n        MyStatelessComponent.propTypes = {\n          foo: PropTypes.string.isRequired,\n          bar: PropTypes.string,\n          hello: PropTypes.string.isRequired,\n          world: PropTypes.string.isRequired\n        }\n      ", Tsx: true, Options: []any{map[string]any{"functions": "defaultArguments"}}},
		// Upstream valid-20
		{Code: "\n        function MyStatelessComponent({ foo, bar, ...props }) {\n          return <div>{foo}{bar}</div>;\n        }\n        MyStatelessComponent.propTypes = {\n          foo: PropTypes.string.isRequired,\n          bar: PropTypes.string.isRequired,\n          hello: PropTypes.string.isRequired,\n          world: PropTypes.string.isRequired\n        }\n      ", Tsx: true, Options: []any{map[string]any{"functions": "defaultArguments"}}},
		// Upstream valid-21
		{Code: "\n        import PropTypes from 'prop-types';\n        import React from 'react';\n\n        const MyComponent = function({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        };\n\n        MyComponent.propTypes = {\n          foo: PropTypes.string,\n          bar: PropTypes.string.isRequired\n        };\n\n        export default MyComponent;\n      ", Tsx: true, Options: []any{map[string]any{"ignoreFunctionalComponents": true}}},
		// Upstream valid-22
		{Code: "\n        import PropTypes from 'prop-types';\n        import React from 'react';\n\n        export const MyComponent = function({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        };\n\n        MyComponent.propTypes = {\n          foo: PropTypes.string,\n          bar: PropTypes.string.isRequired\n        };\n      ", Tsx: true, Options: []any{map[string]any{"ignoreFunctionalComponents": true}}},
		// Upstream valid-23
		{Code: "\n        const Hello = function({ foo = 'asdf', bar = 'qwer' }) {\n          return <div>Hello {foo} and {bar}</div>;\n        }\n        Hello.propTypes = {\n          foo: PropTypes.string,\n          bar: PropTypes.string\n        };\n      ", Tsx: true, Options: []any{map[string]any{"functions": "defaultArguments"}}},
		// Upstream valid-24
		{Code: "\n        const NoPropsComponent = function () {\n          return <div>Hello, world!</div>;\n        }\n      ", Tsx: true, Options: []any{map[string]any{"functions": "defaultArguments"}}},
		// Upstream valid-25
		{Code: "\n        function NoPropsComponent() {\n          return <div>Hello, world!</div>;\n        }\n      ", Tsx: true, Options: []any{map[string]any{"functions": "defaultArguments"}}},
		// Upstream valid-26
		{Code: "\n        const NoPropsComponent = () => {\n          return <div>Hello, world!</div>;\n        }\n      ", Tsx: true, Options: []any{map[string]any{"functions": "defaultArguments"}}},
		// Upstream valid-27
		{Code: "\n        const NoPropsComponent = function () {\n          return <div>Hello, world!</div>;\n        }\n        NoPropsComponent.propTypes = {};\n      ", Tsx: true, Options: []any{map[string]any{"functions": "defaultArguments"}}},
		// Upstream valid-28
		{Code: "\n        import PropTypes from 'prop-types';\n        import React from 'react';\n\n        const MyComponent = ({ foo, bar }) => {\n          return <div>{foo}{bar}</div>;\n        };\n\n        MyComponent.propTypes = {\n          foo: PropTypes.string,\n          bar: PropTypes.string.isRequired\n        };\n\n        export default MyComponent;\n      ", Tsx: true, Options: []any{map[string]any{"ignoreFunctionalComponents": true}}},
		// Upstream valid-29
		{Code: "\n        import PropTypes from 'prop-types';\n        import React from 'react';\n\n        export const MyComponent = ({ foo, bar }) => {\n          return <div>{foo}{bar}</div>;\n        };\n\n        MyComponent.propTypes = {\n          foo: PropTypes.string,\n          bar: PropTypes.string.isRequired\n        };\n\n        export default MyComponent;\n      ", Tsx: true, Options: []any{map[string]any{"ignoreFunctionalComponents": true}}},
		// Upstream valid-30
		{Code: "\n        const Hello = ({ foo = 'asdf', bar = 'qwer' }) => {\n          return <div>Hello {foo} and {bar}</div>;\n        }\n        Hello.propTypes = {\n          foo: PropTypes.string,\n          bar: PropTypes.string\n        };\n      ", Tsx: true, Options: []any{map[string]any{"functions": "defaultArguments"}}},
		// Upstream valid-31
		{Code: "\n        var Greeting = createReactClass({\n          render: function() {\n            return <div>Hello {this.props.foo} {this.props.bar}</div>;\n          },\n          propTypes: {\n            foo: PropTypes.string.isRequired,\n            bar: PropTypes.string.isRequired\n          }\n        });\n      ", Tsx: true},
		// Upstream valid-32
		{Code: "\n        var Greeting = createReactClass({\n          render: function() {\n            return <div>Hello {this.props.foo} {this.props.bar}</div>;\n          },\n          propTypes: {\n            foo: PropTypes.string,\n            bar: PropTypes.string.isRequired\n          },\n          getDefaultProps: function() {\n            return {\n              foo: \"foo\"\n            };\n          }\n        });\n      ", Tsx: true},
		// Upstream valid-33
		{Code: "\n        var Greeting = createReactClass({\n          render: function() {\n            return <div>Hello {this.props.foo} {this.props.bar}</div>;\n          },\n          propTypes: {\n            foo: PropTypes.string,\n            bar: PropTypes.string\n          },\n          getDefaultProps: function() {\n            return {\n              foo: \"foo\",\n              bar: \"bar\"\n            };\n          }\n        });\n      ", Tsx: true},
		// Upstream valid-34
		{Code: "\n        var Greeting = createReactClass({\n          render: function() {\n            return <div>Hello {this.props.foo} {this.props.bar}</div>;\n          }\n        });\n      ", Tsx: true},
		// Upstream valid-35
		{Code: "\n        var Greeting = createReactClass({\n          render: function() {\n            return <div>Hello {this.props.foo} {this.props.bar}</div>;\n          },\n          propTypes: {\n            foo: PropTypes.string,\n            bar: PropTypes.string\n          },\n          getDefaultProps: function() {\n            return {\n              foo: \"foo\",\n              bar: \"bar\"\n            };\n          }\n        });\n      ", Tsx: true, Options: []any{map[string]any{"ignoreFunctionalComponents": true}}},
		// Upstream valid-36
		{Code: "\n        var Greeting = createReactClass({\n          render: function() {\n            return <div>Hello {this.props.foo} {this.props.bar}</div>;\n          },\n          propTypes: {\n            foo: PropTypes.string,\n            bar: PropTypes.string\n          },\n          getDefaultProps: function() {\n            return {\n              foo: \"foo\",\n              bar: \"bar\"\n            };\n          }\n        });\n      ", Tsx: true, Options: []any{map[string]any{"functions": "defaultArguments"}}},
		// Upstream valid-37
		{Code: "\n        class Greeting extends React.Component {\n          render() {\n            return (\n              <h1>Hello, {this.props.foo} {this.props.bar}</h1>\n            );\n          }\n        }\n        Greeting.propTypes = {\n          foo: PropTypes.string.isRequired,\n          bar: PropTypes.string.isRequired\n        };\n        Greeting.defaultProps = {\n          foo: \"foo\"\n        };\n      ", Tsx: true},
		// Upstream valid-38
		{Code: "\n        class Greeting extends React.Component {\n          render() {\n            return (\n              <h1>Hello, {this.props.foo} {this.props.bar}</h1>\n            );\n          }\n        }\n        Greeting.propTypes = {\n          foo: PropTypes.string,\n          bar: PropTypes.string.isRequired\n        };\n        Greeting.defaultProps = {\n          foo: \"foo\"\n        };\n      ", Tsx: true},
		// Upstream valid-39
		{Code: "\n        class Greeting extends React.Component {\n          render() {\n            return (\n              <h1>Hello, {this.props.foo} {this.props.bar}</h1>\n            );\n          }\n        }\n      ", Tsx: true},
		// Upstream valid-40
		{Code: "\n        class Greeting extends React.Component {\n          render() {\n            return (\n              <h1>Hello, {this.props.foo} {this.props.bar}</h1>\n            );\n          }\n        }\n        Greeting.propTypes = {\n          bar: PropTypes.string.isRequired\n        };\n        Greeting.propTypes.foo = PropTypes.string;\n        Greeting.defaultProps = {\n          foo: \"foo\"\n        };\n      ", Tsx: true},
		// Upstream valid-41
		{Code: "\n        class Greeting extends React.Component {\n          render() {\n            return (\n              <h1>Hello, {this.props.foo} {this.props.bar}</h1>\n            );\n          }\n        }\n        Greeting.propTypes = {\n          bar: PropTypes.string.isRequired\n        };\n        Greeting.propTypes.foo = PropTypes.string;\n        Greeting.defaultProps = {};\n        Greeting.defaultProps.foo = \"foo\";\n      ", Tsx: true},
		// Upstream valid-42
		{Code: "\n        class Greeting extends React.Component {\n          render() {\n            return (\n              <h1>Hello, {this.props.foo} {this.props.bar}</h1>\n            );\n          }\n        }\n        Greeting.propTypes = {};\n        Greeting.propTypes.foo = PropTypes.string;\n        Greeting.defaultProps = {};\n        Greeting.defaultProps.foo = \"foo\";\n      ", Tsx: true},
		// Upstream valid-43
		{Code: "\n        class Greeting extends React.Component {\n          render() {\n            return (\n              <h1>Hello, {this.props.foo} {this.props.bar}</h1>\n            );\n          }\n        }\n        Greeting.propTypes = {\n          foo: PropTypes.string,\n          bar: PropTypes.string.isRequired\n        };\n        Greeting.defaultProps = {\n          foo: \"foo\"\n        };\n      ", Tsx: true, Options: []any{map[string]any{"ignoreFunctionalComponents": true}}},
		// Upstream valid-44
		{Code: "\n        class Greeting extends React.Component {\n          render() {\n            return (\n              <h1>Hello, {this.props.foo} {this.props.bar}</h1>\n            );\n          }\n        }\n        Greeting.propTypes = {\n          foo: PropTypes.string,\n          bar: PropTypes.string.isRequired\n        };\n        Greeting.defaultProps = {\n          foo: \"foo\"\n        };\n      ", Tsx: true, Options: []any{map[string]any{"functions": "defaultArguments"}}},
		// Upstream valid-45
		{Code: "\n        class Greeting extends React.Component {\n          render() {\n            return (\n              <h1>Hello, {this.props.foo} {this.props.bar}</h1>\n            );\n          }\n        }\n        Greeting.propTypes = {\n          foo: PropTypes.string,\n          bar: PropTypes.string.isRequired\n        };\n      ", Tsx: true, Options: []any{map[string]any{"classes": "ignore"}}},
		// Upstream valid-46
		{Code: "\n        class Greeting extends React.Component {\n          render() {\n            return (\n              <h1>Hello, {this.props.foo} {this.props.bar}</h1>\n            );\n          }\n        }\n        Greeting.propTypes = {\n          foo: PropTypes.string,\n          bar: PropTypes.string\n        };\n        Greeting.defaultProps = {\n          foo: \"foo\"\n        };\n      ", Tsx: true, Options: []any{map[string]any{"classes": "ignore"}}},
		// Upstream valid-47
		{Code: "\n        class Hello extends React.Component {\n          static get propTypes() {\n            return {\n              name: PropTypes.string\n            };\n          }\n          render() {\n            return <div>Hello {this.props.name}</div>;\n          }\n        }\n      ", Tsx: true, Options: []any{map[string]any{"classes": "ignore"}}},
		// Upstream valid-48
		{Code: "\n        function NotAComponent({ foo, bar }) {}\n        NotAComponent.propTypes = {\n          foo: PropTypes.string,\n          bar: PropTypes.string.isRequired\n        };\n      ", Tsx: true},
		// Upstream valid-49
		{Code: "\n        class Greeting {\n          render() {\n            return (\n              <h1>Hello, {this.props.foo} {this.props.bar}</h1>\n            );\n          }\n        }\n        Greeting.propTypes = {\n          bar: PropTypes.string.isRequired\n        };\n      ", Tsx: true},
		// Upstream valid-50
		{Code: "\n        let Greetings = {};\n        Greetings.Hello = class extends React.Component {\n          render () {\n            return <div>Hello {this.props.foo}</div>;\n          }\n        }\n        Greetings.Hello.propTypes = {\n          foo: PropTypes.string\n        };\n      ", Tsx: true, Options: []any{map[string]any{"classes": "ignore"}}},
		// Upstream valid-51
		{Code: "\n        const defaults = require(\"./defaults\");\n        const types = {\n          foo: PropTypes.string,\n          bar: PropTypes.string\n        };\n        function MyStatelessComponent({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n        MyStatelessComponent.propTypes = types;\n        MyStatelessComponent.defaultProps = defaults;\n      ", Tsx: true},
		// Upstream valid-52
		{Code: "\n        const defaults = {\n          foo: \"foo\"\n        };\n        const types = require(\"./propTypes\");\n        function MyStatelessComponent({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n        MyStatelessComponent.propTypes = types;\n        MyStatelessComponent.defaultProps = defaults;\n      ", Tsx: true},
		// Upstream valid-53
		{Code: "\n        MyStatelessComponent.propTypes = {\n          foo: PropTypes.string\n        };\n        MyStatelessComponent.defaultProps = require(\"./defaults\").foo;\n        function MyStatelessComponent({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n      ", Tsx: true},
		// Upstream valid-54
		{Code: "\n        MyStatelessComponent.propTypes = {\n          foo: PropTypes.string\n        };\n        MyStatelessComponent.defaultProps = require(\"./defaults\").foo;\n        MyStatelessComponent.defaultProps.bar = \"bar\";\n        function MyStatelessComponent({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n      ", Tsx: true},
		// Upstream valid-55
		{Code: "\n        import defaults from \"./defaults\";\n        MyStatelessComponent.propTypes = {\n          foo: PropTypes.string\n        };\n        MyStatelessComponent.defaultProps = defaults;\n        function MyStatelessComponent({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n      ", Tsx: true},
		// Upstream valid-56
		{Code: "\n        import { foo } from \"./defaults\";\n        MyStatelessComponent.propTypes = {\n          foo: PropTypes.string\n        };\n        MyStatelessComponent.defaultProps = foo;\n        function MyStatelessComponent({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n      ", Tsx: true},
		// Upstream valid-57
		{Code: "\n        const component = rowsOfType(GuestlistEntry, (rowData, ownProps) => ({\n            ...rowData,\n            onPress: () => ownProps.onPress(rowData.id),\n        }));\n      ", Tsx: true},
		// Upstream valid-58
		{Code: "\n        MyStatelessComponent.propTypes = {\n          ...stuff,\n          foo: PropTypes.string\n        };\n        MyStatelessComponent.defaultProps = {\n        foo: \"foo\"\n        };\n        function MyStatelessComponent({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n      ", Tsx: true},
		// Upstream valid-59
		{Code: "\n        MyStatelessComponent.propTypes = {\n          foo: PropTypes.string\n        };\n        MyStatelessComponent.defaultProps = {\n        ...defaults,\n        };\n        function MyStatelessComponent({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n      ", Tsx: true},
		// Upstream valid-60
		{Code: "\n        MyStatelessComponent.propTypes = {\n          ...stuff,\n          foo: PropTypes.string\n        };\n        function MyStatelessComponent({ foo = \"foo\", bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n      ", Tsx: true, Options: []any{map[string]any{"functions": "defaultArguments"}}},
		// Upstream valid-61
		{Code: "\n        class Greeting extends React.Component {\n          render() {\n            return (\n              <h1>Hello, {this.props.foo} {this.props.bar}</h1>\n            );\n          }\n        }\n        Greeting.propTypes = {\n          ...someProps,\n          bar: PropTypes.string.isRequired\n        };\n      ", Tsx: true},
		// Upstream valid-62
		{Code: "\n        class Greeting extends React.Component {\n          render() {\n            return (\n              <h1>Hello, {this.props.foo} {this.props.bar}</h1>\n            );\n          }\n        }\n        Greeting.propTypes = {\n          foo: PropTypes.string,\n          bar: PropTypes.string.isRequired\n        };\n        Greeting.defaultProps = {\n          ...defaults,\n          bar: \"bar\"\n        };\n      ", Tsx: true},
		// Upstream valid-63
		{Code: "\n        type Props = {\n          foo: string\n        };\n        class Hello extends React.Component {\n          props: Props;\n          render() {\n            return <div>Hello {this.props.foo}</div>;\n          }\n        }\n      ", Tsx: true},
		// Upstream valid-64
		{Code: "\n        type Props = {\n          foo: string,\n          bar?: string\n        };\n        class Hello extends React.Component {\n          props: Props;\n          render() {\n            return <div>Hello {this.props.foo}</div>;\n          }\n        }\n        Hello.defaultProps = {\n          bar: \"bar\"\n        };\n      ", Tsx: true},
		// Upstream valid-65
		{Code: "\n        class Hello extends React.Component {\n          props: {\n            foo: string,\n            bar?: string\n          };\n          render() {\n            return <div>Hello {this.props.foo}</div>;\n          }\n        }\n        Hello.defaultProps = {\n          bar: \"bar\"\n        };\n      ", Tsx: true},
		// Upstream valid-66
		{Code: "\n        class Hello extends React.Component {\n          props: {\n            foo: string\n          };\n          render() {\n            return <div>Hello {this.props.foo}</div>;\n          }\n        }\n      ", Tsx: true},
		// Upstream valid-67
		{Code: "\n        function Hello(props: { foo?: string }) {\n          return <div>Hello {props.foo}</div>;\n        }\n        Hello.defaultProps = { foo: \"foo\" };\n      ", Tsx: true},
		// Upstream valid-68
		{Code: "\n        function Hello(props: { foo: string }) {\n          return <div>Hello {foo}</div>;\n        }\n      ", Tsx: true},
		// Upstream valid-69
		{Code: "\n        const Hello = (props: { foo?: string }) => {\n          return <div>Hello {props.foo}</div>;\n        };\n        Hello.defaultProps = { foo: \"foo\" };\n      ", Tsx: true},
		// Upstream valid-70
		{Code: "\n        const Hello = (props: { foo: string }) => {\n          return <div>Hello {foo}</div>;\n        };\n      ", Tsx: true},
		// Upstream valid-71
		{Code: "\n        const Hello = function(props: { foo?: string }) {\n          return <div>Hello {props.foo}</div>;\n        };\n        Hello.defaultProps = { foo: \"foo\" };\n      ", Tsx: true},
		// Upstream valid-72
		{Code: "\n        const Hello = function(props: { foo: string }) {\n          return <div>Hello {foo}</div>;\n        };\n      ", Tsx: true},
		// Upstream valid-73
		{Code: "\n        type Props = {\n          foo: string,\n          bar?: string\n        };\n        type Props2 = {\n          foo: string,\n          baz?: string\n        }\n        function Hello(props: Props | Props2) {\n          return <div>Hello {props.foo}</div>;\n        }\n        Hello.defaultProps = {\n          bar: \"bar\",\n          baz: \"baz\"\n        };\n      ", Tsx: true},
		// Upstream valid-74
		{Code: "\n        import type Props from \"fake\";\n        class Hello extends React.Component {\n          props: Props;\n          render () {\n            return <div>Hello {this.props.name.firstname}</div>;\n          }\n        }\n      ", Tsx: true},
		// Upstream valid-75
		{Code: "\n        type Props = any;\n        const Hello = function({ foo }: Props) {\n          return <div>Hello {foo}</div>;\n        };\n      ", Tsx: true},
		// Upstream valid-76
		{Code: "\n        import type ImportedProps from \"fake\";\n        type Props = ImportedProps;\n        function Hello(props: Props) {\n          return <div>Hello {props.name.firstname}</div>;\n        }\n      ", Tsx: true},
		// Upstream valid-77
		{Code: "\n        import type { ImportedType } from \"fake\";\n        type Props = ImportedType;\n        function Hello(props: Props) {\n          return <div>Hello {props.name.firstname}</div>;\n        }\n      ", Tsx: true},
		// Upstream valid-78
		{Code: "\n        import type ImportedProps from \"fake\";\n        type NestedProps = ImportedProps;\n        type Props = NestedProps;\n        function Hello(props: Props) {\n          return <div>Hello {props.name.firstname}</div>;\n        }\n      ", Tsx: true},
		// Upstream valid-79
		{Code: "\n        function Hello(props) {\n          return <div>Hello {props.bar}</div>;\n        }\n        Hello.propTypes = {\n          bar: PropTypes.string\n        };\n        Hello.defaultProps = {\n          \"bar\": \"bar\"\n        };\n      ", Tsx: true},
		// Upstream valid-80
		{Code: "\n        class Hello extends React.Component {\n          static propTypes = {\n            foo: PropTypes.string.isRequired\n          }\n          render() {\n            return <div>Hello {this.props.foo}</div>;\n          }\n        }\n      ", Tsx: true, Options: []any{map[string]any{"forbidDefaultForRequired": true}}},
		// Upstream valid-81 — SKIP: Flow parser syntax is unsupported by rslint.
		{Code: "\n        type HelloProps = {\n          foo: string,\n          bar?: string\n        };\n        class Hello extends React.Component<HelloProps> {\n          static defaultProps = {\n            bar: \"bar\"\n          }\n          render() {\n            return <div>Hello {this.props.foo}</div>;\n          }\n        }\n      ", Tsx: true, Options: []any{map[string]any{"forbidDefaultForRequired": true}}, Skip: true},
		// Upstream valid-82 — SKIP: Flow parser syntax is unsupported by rslint.
		{Code: "\n        type HelloProps = {\n          foo: string,\n          bar?: string\n        };\n        class Hello extends Component<HelloProps> {\n          static defaultProps = {\n            bar: \"bar\"\n          }\n          render() {\n            return <div>Hello {this.props.foo}</div>;\n          }\n        }\n      ", Tsx: true, Options: []any{map[string]any{"forbidDefaultForRequired": true}}, Skip: true},
		// Upstream valid-83 — SKIP: Flow parser syntax is unsupported by rslint.
		{Code: "\n        type HelloProps = {\n          foo: string,\n          bar?: string\n        };\n        type HelloState = {\n          dummyState: string\n        };\n        class Hello extends Component<HelloProps, HelloState> {\n          static defaultProps = {\n            bar: \"bar\"\n          }\n          render() {\n            return <div>Hello {this.props.foo}</div>;\n          }\n        }\n      ", Tsx: true, Options: []any{map[string]any{"forbidDefaultForRequired": true}}, Skip: true},
		// Upstream valid-84 — SKIP: Flow parser syntax is unsupported by rslint.
		{Code: "\n        type HelloProps = {\n          foo?: string,\n          bar?: string\n        };\n        class Hello extends Component<HelloProps> {\n          static defaultProps = {\n            foo: \"foo\",\n            bar: \"bar\"\n          }\n          render() {\n            return <div>Hello {this.props.foo}</div>;\n          }\n        }\n      ", Tsx: true, Options: []any{map[string]any{"forbidDefaultForRequired": true}}, Skip: true},
		// Upstream valid-85
		{Code: "\n        type Props = {\n          foo?: string,\n          bar?: string\n        }\n        function Hello({ foo = 'asdf', bar = 'qwer' }: Props) {\n          return <div>Hello {foo} and {bar}</div>;\n        }\n      ", Tsx: true, Options: []any{map[string]any{"functions": "defaultArguments"}}},
		// Upstream valid-86
		{Code: "\n        type Props = {\n          foo?: string,\n          bar: string\n        }\n        function Hello({ foo = 'asdf', bar }: Props) {\n          return <div>Hello {foo} and {bar}</div>;\n        }\n      ", Tsx: true, Options: []any{map[string]any{"functions": "defaultArguments"}}},
		// Upstream valid-87 — SKIP: Flow parser syntax is unsupported by rslint.
		{Code: "\n        type Props = {\n          +name?: string,\n        };\n        function Hello(props: Props) {\n          return <div>Hello {props.name}</div>;\n        }\n        Hello.defaultProps = {\n          name: 'foo'\n        };\n      ", Tsx: true, Skip: true},
		// Upstream valid-88
		{Code: "\n        import React from \"react\";\n\n        interface Props {\n          name: string;\n        }\n\n        const MyComponent: React.FC<Props> = ({ name }) => {\n          return <div>{name}</div>;\n        };\n\n        export default MyComponent;\n      ", Tsx: true},
		// Upstream valid-89
		{Code: "\n        interface Props {\n          foo?: string,\n          bar?: string\n        }\n        const Hello: React.FC<Props> = ({ foo = 'asdf', bar = 'qwer' }) => {\n          return <div>Hello {foo} and {bar}</div>;\n        }\n      ", Tsx: true, Options: []any{map[string]any{"functions": "defaultArguments"}}},
	}, []rule_tester.InvalidTestCase{
		// Upstream invalid-1
		{Code: "\n        function MyStatelessComponent({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n        MyStatelessComponent.propTypes = {\n          foo: PropTypes.string,\n          bar: PropTypes.string.isRequired\n        };\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"foo\" is not required, but has no corresponding defaultProps declaration.", Line: 6, Column: 11, EndLine: 6, EndColumn: 32}}},
		// Upstream invalid-2
		{Code: "\n        function MyStatelessComponent({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n        MyStatelessComponent.propTypes = forbidExtraProps({\n          foo: PropTypes.string,\n          bar: PropTypes.string.isRequired\n        });\n      ", Tsx: true, Settings: map[string]any{"propWrapperFunctions": []any{"forbidExtraProps"}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"foo\" is not required, but has no corresponding defaultProps declaration.", Line: 6, Column: 11, EndLine: 6, EndColumn: 32}}},
		// Upstream invalid-3
		{Code: "\n        function MyStatelessComponent({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n        const propTypes = {\n          foo: PropTypes.string,\n          bar: PropTypes.string.isRequired\n        };\n        MyStatelessComponent.propTypes = forbidExtraProps(propTypes);\n      ", Tsx: true, Settings: map[string]any{"propWrapperFunctions": []any{"forbidExtraProps"}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"foo\" is not required, but has no corresponding defaultProps declaration.", Line: 6, Column: 11, EndLine: 6, EndColumn: 32}}},
		// Upstream invalid-4
		{Code: "\n        function MyStatelessComponent({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n        MyStatelessComponent.propTypes = {\n          foo: PropTypes.string,\n          bar: PropTypes.string.isRequired\n        };\n        MyStatelessComponent.propTypes.baz = React.propTypes.string;\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"foo\" is not required, but has no corresponding defaultProps declaration.", Line: 6, Column: 11, EndLine: 6, EndColumn: 32}, {MessageId: "shouldHaveDefault", Message: "propType \"baz\" is not required, but has no corresponding defaultProps declaration.", Line: 9, Column: 9, EndLine: 9, EndColumn: 68}}},
		// Upstream invalid-5
		{Code: "\n        const types = {\n          foo: PropTypes.string,\n          bar: PropTypes.string.isRequired\n        };\n        function MyStatelessComponent({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n        MyStatelessComponent.propTypes = types;\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"foo\" is not required, but has no corresponding defaultProps declaration.", Line: 3, Column: 11, EndLine: 3, EndColumn: 32}}},
		// Upstream invalid-6
		{Code: "\n        const defaults = {\n          foo: \"foo\"\n        };\n        function MyStatelessComponent({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n        MyStatelessComponent.propTypes = {\n          foo: PropTypes.string,\n          bar: PropTypes.string\n        };\n        MyStatelessComponent.defaultProps = defaults;\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"bar\" is not required, but has no corresponding defaultProps declaration.", Line: 10, Column: 11, EndLine: 10, EndColumn: 32}}},
		// Upstream invalid-7
		{Code: "\n        const defaults = {\n          foo: \"foo\"\n        };\n        const types = {\n          foo: PropTypes.string,\n          bar: PropTypes.string\n        };\n        function MyStatelessComponent({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n        MyStatelessComponent.propTypes = types;\n        MyStatelessComponent.defaultProps = defaults;\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"bar\" is not required, but has no corresponding defaultProps declaration.", Line: 7, Column: 11, EndLine: 7, EndColumn: 32}}},
		// Upstream invalid-8
		{Code: "\n        const types = {\n          foo: PropTypes.string,\n          bar: PropTypes.string\n        };\n        function MyStatelessComponent({ foo, bar = \"asdf\" }) {\n          return <div>{foo}{bar}</div>;\n        }\n        MyStatelessComponent.propTypes = types;\n      ", Tsx: true, Options: []any{map[string]any{"functions": "defaultArguments"}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldAssignObjectDefault", Message: "propType \"foo\" is not required, but has no corresponding default argument value.", Line: 6, Column: 41, EndLine: 6, EndColumn: 44}}},
		// Upstream invalid-9
		{Code: "\n        const types = {\n          foo: PropTypes.string,\n        };\n        function MyStatelessComponent(props) {\n          return <div>{props.foo}</div>;\n        }\n        MyStatelessComponent.propTypes = types;\n      ", Tsx: true, Options: []any{map[string]any{"functions": "defaultArguments"}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "destructureInSignature", Message: "Must destructure props in the function signature to initialize an optional prop.", Line: 5, Column: 39, EndLine: 5, EndColumn: 44}}},
		// Upstream invalid-10
		{Code: "\n        function MyStatelessComponent({ foo, bar, ...props }) {\n          return <div>{foo}{bar}</div>;\n        }\n        MyStatelessComponent.propTypes = {\n          foo: PropTypes.string,\n          bar: PropTypes.string.isRequired,\n          hello: PropTypes.string.isRequired,\n          world: PropTypes.string.isRequired\n        }\n      ", Tsx: true, Options: []any{map[string]any{"functions": "defaultArguments"}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldAssignObjectDefault", Message: "propType \"foo\" is not required, but has no corresponding default argument value.", Line: 2, Column: 41, EndLine: 2, EndColumn: 44}}},
		// Upstream invalid-11
		{Code: "\n        var Greeting = createReactClass({\n          render: function() {\n            return <div>Hello {this.props.foo} {this.props.bar}</div>;\n          },\n          propTypes: {\n            foo: PropTypes.string,\n            bar: PropTypes.string.isRequired\n          }\n        });\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"foo\" is not required, but has no corresponding defaultProps declaration.", Line: 7, Column: 13, EndLine: 7, EndColumn: 34}}},
		// Upstream invalid-12
		{Code: "\n        var Greeting = createReactClass({\n          render: function() {\n            return <div>Hello {this.props.foo} {this.props.bar}</div>;\n          },\n          propTypes: {\n            foo: PropTypes.string,\n            bar: PropTypes.string.isRequired\n          }\n        });\n      ", Tsx: true, Options: []any{map[string]any{"ignoreFunctionalComponents": true}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"foo\" is not required, but has no corresponding defaultProps declaration.", Line: 7, Column: 13, EndLine: 7, EndColumn: 34}}},
		// Upstream invalid-13
		{Code: "\n        var Greeting = createReactClass({\n          render: function() {\n            return <div>Hello {this.props.foo} {this.props.bar}</div>;\n          },\n          propTypes: {\n            foo: PropTypes.string,\n            bar: PropTypes.string\n          },\n          getDefaultProps: function() {\n            return {\n              foo: \"foo\"\n            };\n          }\n        });\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"bar\" is not required, but has no corresponding defaultProps declaration.", Line: 8, Column: 13, EndLine: 8, EndColumn: 34}}},
		// Upstream invalid-14
		{Code: "\n        class Greeting extends React.Component {\n          render() {\n            return (\n              <h1>Hello, {this.props.foo} {this.props.bar}</h1>\n            );\n          }\n        }\n        Greeting.propTypes = {\n          foo: PropTypes.string,\n          bar: PropTypes.string.isRequired\n        };\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"foo\" is not required, but has no corresponding defaultProps declaration.", Line: 10, Column: 11, EndLine: 10, EndColumn: 32}}},
		// Upstream invalid-15
		{Code: "\n        class Greeting extends React.Component {\n          render() {\n            return (\n              <h1>Hello, {this.props.foo} {this.props.bar}</h1>\n            );\n          }\n        }\n        Greeting.propTypes = {\n          foo: PropTypes.string,\n          bar: PropTypes.string.isRequired\n        };\n      ", Tsx: true, Options: []any{map[string]any{"ignoreFunctionalComponents": true}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"foo\" is not required, but has no corresponding defaultProps declaration.", Line: 10, Column: 11, EndLine: 10, EndColumn: 32}}},
		// Upstream invalid-16
		{Code: "\n        class Greeting extends React.Component {\n          render() {\n            return (\n              <h1>Hello, {this.props.foo} {this.props.bar}</h1>\n            );\n          }\n        }\n        Greeting.propTypes = {\n          foo: PropTypes.string,\n          bar: PropTypes.string\n        };\n        Greeting.defaultProps = {\n          foo: \"foo\"\n        };\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"bar\" is not required, but has no corresponding defaultProps declaration.", Line: 11, Column: 11, EndLine: 11, EndColumn: 32}}},
		// Upstream invalid-17
		{Code: "\n        class Greeting extends React.Component {\n          render() {\n            return (\n              <h1>Hello, {this.props.foo} {this.props.bar}</h1>\n            );\n          }\n        }\n        Greeting.propTypes = {\n          bar: PropTypes.string.isRequired\n        };\n        Greeting.propTypes.foo = PropTypes.string;\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"foo\" is not required, but has no corresponding defaultProps declaration.", Line: 12, Column: 9, EndLine: 12, EndColumn: 50}}},
		// Upstream invalid-18
		{Code: "\n        class Greeting extends React.Component {\n          render() {\n            return (\n              <h1>Hello, {this.props.foo} {this.props.bar}</h1>\n            );\n          }\n        }\n        Greeting.propTypes = {\n          bar: PropTypes.string\n        };\n        Greeting.propTypes.foo = PropTypes.string;\n        Greeting.defaultProps = {};\n        Greeting.defaultProps.foo = \"foo\";\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"bar\" is not required, but has no corresponding defaultProps declaration.", Line: 10, Column: 11, EndLine: 10, EndColumn: 32}}},
		// Upstream invalid-19
		{Code: "\n        class Greeting extends React.Component {\n          render() {\n            return (\n              <h1>Hello, {this.props.foo} {this.props.bar}</h1>\n            );\n          }\n        }\n        Greeting.propTypes = {};\n        Greeting.propTypes.foo = PropTypes.string;\n        Greeting.defaultProps = {};\n        Greeting.defaultProps.bar = \"bar\";\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"foo\" is not required, but has no corresponding defaultProps declaration.", Line: 10, Column: 9, EndLine: 10, EndColumn: 50}}},
		// Upstream invalid-20
		{Code: "\n        class Greeting extends React.Component {\n          render() {\n            return (\n              <h1>Hello, {this.props.foo} {this.props.bar}</h1>\n            );\n          }\n        }\n        const props = {\n          foo: PropTypes.string,\n          bar: PropTypes.string.isRequired\n        };\n        Greeting.propTypes = props;\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"foo\" is not required, but has no corresponding defaultProps declaration.", Line: 10, Column: 11, EndLine: 10, EndColumn: 32}}},
		// Upstream invalid-21
		{Code: "\n        class Greeting extends React.Component {\n          render() {\n            return (\n              <h1>Hello, {this.props.foo} {this.props.bar}</h1>\n            );\n          }\n        }\n        const props = {\n          foo: PropTypes.string,\n          bar: PropTypes.string\n        };\n        const defaults = {\n          foo: \"foo\"\n        };\n        Greeting.propTypes = props;\n        Greeting.defaultProps = defaults;\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"bar\" is not required, but has no corresponding defaultProps declaration.", Line: 11, Column: 11, EndLine: 11, EndColumn: 32}}},
		// Upstream invalid-22
		{Code: "\n        class Hello extends React.Component {\n          static get propTypes() {\n            return {\n              name: PropTypes.string\n            };\n          }\n          render() {\n            return <div>Hello {this.props.name}</div>;\n          }\n        }\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"name\" is not required, but has no corresponding defaultProps declaration.", Line: 5, Column: 15, EndLine: 5, EndColumn: 37}}},
		// Upstream invalid-23
		{Code: "\n        class Hello extends React.Component {\n          static get propTypes() {\n            return {\n              name: PropTypes.string\n            };\n          }\n          render() {\n            return <div>Hello {this.props.name}</div>;\n          }\n        }\n      ", Tsx: true, Options: []any{map[string]any{"ignoreFunctionalComponents": true}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"name\" is not required, but has no corresponding defaultProps declaration.", Line: 5, Column: 15, EndLine: 5, EndColumn: 37}}},
		// Upstream invalid-24
		{Code: "\n        class Hello extends React.Component {\n          static get propTypes() {\n            return {\n              foo: PropTypes.string,\n              bar: PropTypes.string\n            };\n          }\n          static get defaultProps() {\n            return {\n              bar: \"world\"\n            };\n          }\n          render() {\n            return <div>Hello {this.props.name}</div>;\n          }\n        }\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"foo\" is not required, but has no corresponding defaultProps declaration.", Line: 5, Column: 15, EndLine: 5, EndColumn: 36}}},
		// Upstream invalid-25
		{Code: "\n        const props = {\n          foo: PropTypes.string\n        };\n        class Hello extends React.Component {\n          static get propTypes() {\n            return props;\n          }\n          render() {\n            return <div>Hello {this.props.name}</div>;\n          }\n        }\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"foo\" is not required, but has no corresponding defaultProps declaration.", Line: 3, Column: 11, EndLine: 3, EndColumn: 32}}},
		// Upstream invalid-26
		{Code: "\n        const defaults = {\n          bar: \"world\"\n        };\n        class Hello extends React.Component {\n          static get propTypes() {\n            return {\n              foo: PropTypes.string,\n              bar: PropTypes.string\n            };\n          }\n          static get defaultProps() {\n            return defaults;\n          }\n          render() {\n            return <div>Hello {this.props.name}</div>;\n          }\n        }\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"foo\" is not required, but has no corresponding defaultProps declaration.", Line: 8, Column: 15, EndLine: 8, EndColumn: 36}}},
		// Upstream invalid-27
		{Code: "\n        class Greeting extends React.Component {\n          render() {\n            return (\n              <h1>Hello, {this.props.foo} {this.props.bar}</h1>\n            );\n          }\n          static propTypes = {\n            foo: PropTypes.string,\n            bar: PropTypes.string.isRequired\n          };\n        }\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"foo\" is not required, but has no corresponding defaultProps declaration.", Line: 9, Column: 13, EndLine: 9, EndColumn: 34}}},
		// Upstream invalid-28
		{Code: "\n        class Greeting extends React.Component {\n          render() {\n            return (\n              <h1>Hello, {this.props.foo} {this.props.bar}</h1>\n            );\n          }\n          static propTypes = {\n            foo: PropTypes.string,\n            bar: PropTypes.string.isRequired\n          };\n        }\n      ", Tsx: true, Options: []any{map[string]any{"ignoreFunctionalComponents": true}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"foo\" is not required, but has no corresponding defaultProps declaration.", Line: 9, Column: 13, EndLine: 9, EndColumn: 34}}},
		// Upstream invalid-29
		{Code: "\n        class Greeting extends React.Component {\n          render() {\n            return (\n              <h1>Hello, {this.props.foo} {this.props.bar}</h1>\n            );\n          }\n          static propTypes = {\n            foo: PropTypes.string,\n            bar: PropTypes.string\n          };\n          static defaultProps = {\n            foo: \"foo\"\n          };\n        }\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"bar\" is not required, but has no corresponding defaultProps declaration.", Line: 10, Column: 13, EndLine: 10, EndColumn: 34}}},
		// Upstream invalid-30
		{Code: "\n        const props = {\n          foo: PropTypes.string,\n          bar: PropTypes.string.isRequired\n        };\n        class Greeting extends React.Component {\n          render() {\n            return (\n              <h1>Hello, {this.props.foo} {this.props.bar}</h1>\n            );\n          }\n          static propTypes = props;\n        }\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"foo\" is not required, but has no corresponding defaultProps declaration.", Line: 3, Column: 11, EndLine: 3, EndColumn: 32}}},
		// Upstream invalid-31
		{Code: "\n        const props = {\n          foo: PropTypes.string,\n          bar: PropTypes.string\n        };\n        const defaults = {\n          foo: \"foo\"\n        };\n        class Greeting extends React.Component {\n          render() {\n            return (\n              <h1>Hello, {this.props.foo} {this.props.bar}</h1>\n            );\n          }\n          static propTypes = props;\n          static defaultProps = defaults;\n        }\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"bar\" is not required, but has no corresponding defaultProps declaration.", Line: 4, Column: 11, EndLine: 4, EndColumn: 32}}},
		// Upstream invalid-32
		{Code: "\n        let Greetings = {};\n        Greetings.Hello = class extends React.Component {\n          render () {\n            return <div>Hello {this.props.foo}</div>;\n          }\n        }\n        Greetings.Hello.propTypes = {\n          foo: PropTypes.string\n        };\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"foo\" is not required, but has no corresponding defaultProps declaration.", Line: 9, Column: 11, EndLine: 9, EndColumn: 32}}},
		// Upstream invalid-33
		{Code: "\n        var Greetings = ({ foo = \"foo\" }) => {\n          return <div>Hello {this.props.foo}</div>;\n        }\n        Greetings.propTypes = {\n          foo: PropTypes.string\n        };\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"foo\" is not required, but has no corresponding defaultProps declaration.", Line: 6, Column: 11, EndLine: 6, EndColumn: 32}}},
		// Upstream invalid-34
		{Code: "\n        var ComponentWithNoProps = ({ bar = \"bar\" }) => {\n          return <div>Hello {this.props.foo}</div>;\n        }\n        var Greetings = ({ foo = \"foo\" }) => {\n          return <div>Hello {this.props.foo}</div>;\n        }\n        Greetings.propTypes = {\n          foo: PropTypes.string\n        };\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"foo\" is not required, but has no corresponding defaultProps declaration.", Line: 9, Column: 11, EndLine: 9, EndColumn: 32}}},
		// Upstream invalid-35 — SKIP: Flow parser syntax is unsupported by rslint.
		{Code: "\n        class Hello extends React.Component {\n          props: {\n            foo?: string,\n            bar?: string\n          };\n          render() {\n            return <div>Hello {this.props.foo}</div>;\n          }\n        }\n        Hello.defaultProps = {\n          foo: \"foo\"\n        };\n      ", Tsx: true, Skip: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"bar\" is not required, but has no corresponding defaultProps declaration.", Line: 5, Column: 13}}},
		// Upstream invalid-36 — SKIP: Flow parser syntax is unsupported by rslint.
		{Code: "\n        type Props = {\n          foo: string,\n          bar?: string\n        };\n        class Hello extends React.Component {\n          props: Props;\n          render() {\n            return <div>Hello {this.props.foo}</div>;\n          }\n        }\n      ", Tsx: true, Skip: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"bar\" is not required, but has no corresponding defaultProps declaration.", Line: 4, Column: 11}}},
		// Upstream invalid-37 — SKIP: Flow parser syntax is unsupported by rslint.
		{Code: "\n        type Props = {\n          foo?: string\n        };\n        class Hello extends React.Component {\n          props: Props;\n          static defaultProps: { foo: string };\n          render() {\n            return <div>Hello {this.props.foo}</div>;\n          }\n        }\n      ", Tsx: true, Skip: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"foo\" is not required, but has no corresponding defaultProps declaration.", Line: 3, Column: 11}}},
		// Upstream invalid-38 — SKIP: Flow parser syntax is unsupported by rslint.
		{Code: "\n        class Hello extends React.Component {\n          props: {\n            foo: string,\n            bar?: string\n          };\n          render() {\n            return <div>Hello {this.props.foo}</div>;\n          }\n        }\n      ", Tsx: true, Skip: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"bar\" is not required, but has no corresponding defaultProps declaration.", Line: 5, Column: 13}}},
		// Upstream invalid-39 — SKIP: Flow parser syntax is unsupported by rslint.
		{Code: "\n        class Hello extends React.Component {\n          props: {\n            foo?: string,\n            bar?: string\n          };\n          render() {\n            return <div>Hello {this.props.foo}</div>;\n          }\n        }\n      ", Tsx: true, Skip: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"foo\" is not required, but has no corresponding defaultProps declaration.", Line: 4, Column: 13}, {MessageId: "shouldHaveDefault", Message: "propType \"bar\" is not required, but has no corresponding defaultProps declaration.", Line: 5, Column: 13}}},
		// Upstream invalid-40 — SKIP: Flow parser syntax is unsupported by rslint.
		{Code: "\n        class Hello extends React.Component {\n          props: {\n            foo?: string\n          };\n          static defaultProps: { foo: string };\n          render() {\n            return <div>Hello {this.props.foo}</div>;\n          }\n        }\n      ", Tsx: true, Skip: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"foo\" is not required, but has no corresponding defaultProps declaration.", Line: 4, Column: 13}}},
		// Upstream invalid-41 — SKIP: Flow parser syntax is unsupported by rslint.
		{Code: "\n        type Props = {\n          foo?: string,\n          bar?: string\n        };\n        class Hello extends React.Component {\n          props: Props;\n          render() {\n            return <div>Hello {this.props.foo}</div>;\n          }\n        }\n        Hello.defaultProps = {\n          foo: \"foo\"\n        };\n      ", Tsx: true, Skip: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"bar\" is not required, but has no corresponding defaultProps declaration.", Line: 4, Column: 11}}},
		// Upstream invalid-42 — SKIP: Flow parser syntax is unsupported by rslint.
		{Code: "\n        type Props = {\n          foo?: string,\n          bar?: string\n        };\n        class Hello extends React.Component {\n          props: Props;\n          static defaultProps: { foo: string, bar: string };\n          render() {\n            return <div>Hello {this.props.foo}</div>;\n          }\n        }\n        Hello.defaultProps = {\n          foo: \"foo\"\n        };\n      ", Tsx: true, Skip: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"bar\" is not required, but has no corresponding defaultProps declaration.", Line: 4, Column: 11}}},
		// Upstream invalid-43 — SKIP: Flow parser syntax is unsupported by rslint.
		{Code: "\n        class Hello extends React.Component {\n          props: {\n            foo?: string,\n            bar?: string\n          };\n          static defaultProps: { foo: string, bar: string };\n          render() {\n            return <div>Hello {this.props.foo}</div>;\n          }\n        }\n        Hello.defaultProps = {\n          foo: \"foo\"\n        };\n      ", Tsx: true, Skip: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"bar\" is not required, but has no corresponding defaultProps declaration.", Line: 5, Column: 13}}},
		// Upstream invalid-44 — SKIP: Flow parser syntax is unsupported by rslint.
		{Code: "\n        function Hello(props: { foo?: string }) {\n          return <div>Hello {props.foo}</div>;\n        }\n      ", Tsx: true, Skip: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"foo\" is not required, but has no corresponding defaultProps declaration.", Line: 2, Column: 33}}},
		// Upstream invalid-45 — SKIP: Flow parser syntax is unsupported by rslint.
		{Code: "\n        function Hello({ foo = \"foo\" }: { foo?: string }) {\n          return <div>Hello {foo}</div>;\n        }\n      ", Tsx: true, Skip: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"foo\" is not required, but has no corresponding defaultProps declaration.", Line: 2, Column: 43}}},
		// Upstream invalid-46 — SKIP: Flow parser syntax is unsupported by rslint.
		{Code: "\n        function Hello(props: { foo?: string, bar?: string }) {\n          return <div>Hello {props.foo}</div>;\n        }\n        Hello.defaultProps = { foo: \"foo\" };\n      ", Tsx: true, Skip: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"bar\" is not required, but has no corresponding defaultProps declaration.", Line: 2, Column: 47}}},
		// Upstream invalid-47 — SKIP: Flow parser syntax is unsupported by rslint.
		{Code: "\n        function Hello(props: { foo?: string, bar?: string }) {\n          return <div>Hello {props.foo}</div>;\n        }\n      ", Tsx: true, Skip: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"foo\" is not required, but has no corresponding defaultProps declaration.", Line: 2, Column: 33}, {MessageId: "shouldHaveDefault", Message: "propType \"bar\" is not required, but has no corresponding defaultProps declaration.", Line: 2, Column: 47}}},
		// Upstream invalid-48 — SKIP: Flow parser syntax is unsupported by rslint.
		{Code: "\n        type Props = {\n          foo?: string\n        };\n        function Hello(props: Props) {\n          return <div>Hello {props.foo}</div>;\n        }\n      ", Tsx: true, Skip: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"foo\" is not required, but has no corresponding defaultProps declaration.", Line: 3, Column: 11}}},
		// Upstream invalid-49 — SKIP: Flow parser syntax is unsupported by rslint.
		{Code: "\n        const Hello = (props: { foo?: string }) => {\n          return <div>Hello {props.foo}</div>;\n        };\n      ", Tsx: true, Skip: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"foo\" is not required, but has no corresponding defaultProps declaration.", Line: 2, Column: 33}}},
		// Upstream invalid-50 — SKIP: Flow parser syntax is unsupported by rslint.
		{Code: "\n        const Hello = (props: { foo?: string, bar?: string }) => {\n          return <div>Hello {props.foo}</div>;\n        };\n        Hello.defaultProps = { foo: \"foo\" };\n      ", Tsx: true, Skip: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"bar\" is not required, but has no corresponding defaultProps declaration.", Line: 2, Column: 47}}},
		// Upstream invalid-51 — SKIP: Flow parser syntax is unsupported by rslint.
		{Code: "\n        const Hello = function(props: { foo?: string }) {\n          return <div>Hello {props.foo}</div>;\n        };\n      ", Tsx: true, Skip: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"foo\" is not required, but has no corresponding defaultProps declaration.", Line: 2, Column: 41}}},
		// Upstream invalid-52 — SKIP: Flow parser syntax is unsupported by rslint.
		{Code: "\n        const Hello = function(props: { foo?: string, bar?: string }) {\n          return <div>Hello {props.foo}</div>;\n        };\n        Hello.defaultProps = { foo: \"foo\" };\n      ", Tsx: true, Skip: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"bar\" is not required, but has no corresponding defaultProps declaration.", Line: 2, Column: 55}}},
		// Upstream invalid-53 — SKIP: Flow parser syntax is unsupported by rslint.
		{Code: "\n        type Props = {\n          foo?: string,\n          bar?: string\n        };\n        function Hello(props: Props) {\n          return <div>Hello {props.foo}</div>;\n        }\n        Hello.defaultProps = { foo: \"foo\" };\n      ", Tsx: true, Skip: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"bar\" is not required, but has no corresponding defaultProps declaration.", Line: 4, Column: 11}}},
		// Upstream invalid-54 — SKIP: Flow parser syntax is unsupported by rslint.
		{Code: "\n        function Hello(props: { one?: string } | { two?: string }) {\n          return <div>Hello {props.foo}</div>;\n        }\n      ", Tsx: true, Skip: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"one\" is not required, but has no corresponding defaultProps declaration.", Line: 2, Column: 33}, {MessageId: "shouldHaveDefault", Message: "propType \"two\" is not required, but has no corresponding defaultProps declaration.", Line: 2, Column: 52}}},
		// Upstream invalid-55 — SKIP: Flow parser syntax is unsupported by rslint.
		{Code: "\n        type Props = {\n          foo: string,\n          bar?: string\n        };\n        type Props2 = {\n          foo: string,\n          baz?: string\n        }\n        function Hello(props: Props | Props2) {\n          return <div>Hello {props.foo}</div>;\n        }\n      ", Tsx: true, Skip: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"bar\" is not required, but has no corresponding defaultProps declaration.", Line: 4, Column: 11}, {MessageId: "shouldHaveDefault", Message: "propType \"baz\" is not required, but has no corresponding defaultProps declaration.", Line: 8, Column: 11}}},
		// Upstream invalid-56 — SKIP: Flow parser syntax is unsupported by rslint.
		{Code: "\n        type Props = {\n          foo: string,\n          bar?: string\n        };\n        type Props2 = {\n          foo: string,\n          baz?: string\n        }\n        function Hello(props: Props | Props2) {\n          return <div>Hello {props.foo}</div>;\n        }\n        Hello.defaultProps = {\n          bar: \"bar\"\n        };\n      ", Tsx: true, Skip: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"baz\" is not required, but has no corresponding defaultProps declaration.", Line: 8, Column: 11}}},
		// Upstream invalid-57 — SKIP: Flow parser syntax is unsupported by rslint.
		{Code: "\n        type HelloProps = {\n          two?: string,\n          three: string\n        };\n        function Hello(props: { one?: string } | HelloProps) {\n          return <div>Hello {props.foo}</div>;\n        }\n      ", Tsx: true, Skip: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"two\" is not required, but has no corresponding defaultProps declaration.", Line: 3, Column: 11}, {MessageId: "shouldHaveDefault", Message: "propType \"one\" is not required, but has no corresponding defaultProps declaration.", Line: 6, Column: 33}}},
		// Upstream invalid-58 — SKIP: Flow parser syntax is unsupported by rslint.
		{Code: "\n        type HelloProps = {\n          two?: string,\n          three: string\n        };\n        function Hello(props: ExternalProps | HelloProps) {\n          return <div>Hello {props.foo}</div>;\n        }\n      ", Tsx: true, Skip: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"two\" is not required, but has no corresponding defaultProps declaration.", Line: 3, Column: 11}}},
		// Upstream invalid-59
		{Code: "\n        class Hello extends React.Component {\n          static propTypes = {\n            foo: PropTypes.string\n          };\n          render() {\n            return <div>Hello {this.props.foo}</div>;\n          }\n        }\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"foo\" is not required, but has no corresponding defaultProps declaration.", Line: 4, Column: 13, EndLine: 4, EndColumn: 34}}},
		// Upstream invalid-60
		{Code: "\n        class Hello extends React.Component {\n          static get propTypes() {\n            return {\n              name: PropTypes.string\n            };\n          }\n          static defaultProps() {\n            return {\n              name: 'John'\n            };\n          }\n          render() {\n            return <div>Hello {this.props.name}</div>;\n          }\n        }\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"name\" is not required, but has no corresponding defaultProps declaration.", Line: 5, Column: 15, EndLine: 5, EndColumn: 37}}},
		// Upstream invalid-61
		{Code: "\n        class Hello extends React.Component {\n          static get propTypes() {\n            return {\n              'first-name': PropTypes.string\n            };\n          }\n          render() {\n            return <div>Hello {this.props['first-name']}</div>;\n          }\n        }\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"first-name\" is not required, but has no corresponding defaultProps declaration.", Line: 5, Column: 15, EndLine: 5, EndColumn: 45}}},
		// Upstream invalid-62
		{Code: "\n        class Hello extends React.Component {\n          render() {\n            return <div>Hello {this.props.foo}</div>;\n          }\n        }\n        Hello.propTypes = {\n          foo: PropTypes.string.isRequired\n        };\n        Hello.defaultProps = {\n          foo: 'bar'\n        };\n      ", Tsx: true, Options: []any{map[string]any{"forbidDefaultForRequired": true}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "noDefaultWithRequired", Message: "propType \"foo\" is required and should not have a defaultProps declaration.", Line: 8, Column: 11, EndLine: 8, EndColumn: 43}}},
		// Upstream invalid-63
		{Code: "\n        function Hello(props) {\n          return <div>Hello {props.foo}</div>;\n        }\n        Hello.propTypes = {\n          foo: PropTypes.string.isRequired\n        };\n        Hello.defaultProps = {\n          foo: 'bar'\n        };\n      ", Tsx: true, Options: []any{map[string]any{"forbidDefaultForRequired": true}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "noDefaultWithRequired", Message: "propType \"foo\" is required and should not have a defaultProps declaration.", Line: 6, Column: 11, EndLine: 6, EndColumn: 43}}},
		// Upstream invalid-64
		{Code: "\n        const Hello = (props) => {\n          return <div>Hello {props.foo}</div>;\n        };\n        Hello.propTypes = {\n          foo: PropTypes.string.isRequired\n        };\n        Hello.defaultProps = {\n          foo: 'bar'\n        };\n      ", Tsx: true, Options: []any{map[string]any{"forbidDefaultForRequired": true}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "noDefaultWithRequired", Message: "propType \"foo\" is required and should not have a defaultProps declaration.", Line: 6, Column: 11, EndLine: 6, EndColumn: 43}}},
		// Upstream invalid-65
		{Code: "\n        class Hello extends React.Component {\n          static propTypes = {\n            foo: PropTypes.string.isRequired\n          }\n          static defaultProps = {\n            foo: 'bar'\n          }\n          render() {\n            return <div>Hello {this.props.foo}</div>;\n          }\n        }\n      ", Tsx: true, Options: []any{map[string]any{"forbidDefaultForRequired": true}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "noDefaultWithRequired", Message: "propType \"foo\" is required and should not have a defaultProps declaration.", Line: 4, Column: 13, EndLine: 4, EndColumn: 45}}},
		// Upstream invalid-66
		{Code: "\n        class Hello extends React.Component {\n          static get propTypes () {\n            return {\n              foo: PropTypes.string.isRequired\n            };\n          }\n          static get defaultProps() {\n            return {\n              foo: 'bar'\n            };\n          }\n          render() {\n            return <div>Hello {this.props.foo}</div>;\n          }\n        }\n      ", Tsx: true, Options: []any{map[string]any{"forbidDefaultForRequired": true}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "noDefaultWithRequired", Message: "propType \"foo\" is required and should not have a defaultProps declaration.", Line: 5, Column: 15, EndLine: 5, EndColumn: 47}}},
		// Upstream invalid-67
		{Code: "\n        function Hello(props) {\n          return <div>Hello {props.foo}</div>;\n        }\n        Hello.propTypes = {\n          foo: PropTypes.string.isRequired\n        };\n        Hello.defaultProps = {\n          foo: 'bar'\n        };\n      ", Tsx: true, Options: []any{map[string]any{"functions": "defaultArguments"}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "noDefaultPropsWithFunction", Message: "Don’t use defaultProps with function components.", Line: 2, Column: 9, EndLine: 4, EndColumn: 10}}},
		// Upstream invalid-68
		{Code: "\n        function Hello(props) {\n          return <div>Hello {props.foo} and {props.bar}</div>;\n        }\n        Hello.propTypes = {\n          foo: PropTypes.string.isRequired,\n          bar: PropTypes.string\n        };\n      ", Tsx: true, Options: []any{map[string]any{"functions": "defaultArguments"}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "destructureInSignature", Message: "Must destructure props in the function signature to initialize an optional prop.", Line: 2, Column: 24, EndLine: 2, EndColumn: 29}}},
		// Upstream invalid-69 — SKIP: Flow parser syntax is unsupported by rslint.
		{Code: "\n        type HelloProps = {\n          foo: string,\n          bar?: string\n        };\n        class Hello extends React.Component<HelloProps> {\n          render() {\n            return <div>Hello {this.props.foo}</div>;\n          }\n        }\n      ", Tsx: true, Skip: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"bar\" is not required, but has no corresponding defaultProps declaration.", Line: 0, Column: 0}}},
		// Upstream invalid-70 — SKIP: Flow parser syntax is unsupported by rslint.
		{Code: "\n        type HelloProps = {\n          foo: string,\n          bar?: string\n        };\n        class Hello extends Component<HelloProps> {\n          render() {\n            return <div>Hello {this.props.foo}</div>;\n          }\n        }\n      ", Tsx: true, Skip: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"bar\" is not required, but has no corresponding defaultProps declaration.", Line: 0, Column: 0}}},
		// Upstream invalid-71 — SKIP: Flow parser syntax is unsupported by rslint.
		{Code: "\n        type HelloProps = {\n          foo: string,\n          bar?: string\n        };\n        type HelloState = {\n          dummyState: string\n        };\n        class Hello extends Component<HelloProps, HelloState> {\n          render() {\n            return <div>Hello {this.props.foo}</div>;\n          }\n        }\n      ", Tsx: true, Skip: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"bar\" is not required, but has no corresponding defaultProps declaration.", Line: 0, Column: 0}}},
		// Upstream invalid-72 — SKIP: Flow parser syntax is unsupported by rslint.
		{Code: "\n        type HelloProps = {\n          foo?: string,\n          bar?: string\n        };\n        class Hello extends Component<HelloProps> {\n          render() {\n            return <div>Hello {this.props.foo}</div>;\n          }\n        }\n      ", Tsx: true, Skip: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"foo\" is not required, but has no corresponding defaultProps declaration.", Line: 0, Column: 0}, {MessageId: "shouldHaveDefault", Message: "propType \"bar\" is not required, but has no corresponding defaultProps declaration.", Line: 0, Column: 0}}},
		// Upstream invalid-73 — SKIP: Flow parser syntax is unsupported by rslint.
		{Code: "\n        type Props = {\n          +name?: string,\n        };\n        function Hello(props: Props) {\n          return <div>Hello {props.name}</div>;\n        }\n      ", Tsx: true, Skip: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"name\" is not required, but has no corresponding defaultProps declaration.", Line: 0, Column: 0}}},
		// Upstream invalid-74
		{Code: "\n        import PropTypes from 'prop-types';\n        import React from 'react';\n\n        const MyComponent= (props) => {\n          switch (props.usedProp) {\n            case 1:\n              return (<div />);\n            default:\n              return <div />;\n          }\n        };\n\n        MyComponent.propTypes = {\n          usedProp: PropTypes.string,\n        };\n\n        export default MyComponent;\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"usedProp\" is not required, but has no corresponding defaultProps declaration.", Line: 15, Column: 11, EndLine: 15, EndColumn: 37}}},
		// Upstream invalid-75
		{Code: "\n        Foo.propTypes = {\n          a: PropTypes.string,\n        }\n\n        export default function Foo(props) {\n          return <p>{props.a}</p>\n        };\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"a\" is not required, but has no corresponding defaultProps declaration.", Line: 3, Column: 11, EndLine: 3, EndColumn: 30}}},
		// Upstream invalid-76
		{Code: "\n        type Props = {\n          history: {\n            push: Function,\n          },\n          match?: {\n            params?: {\n              date?: string\n            },\n          },\n        };\n\n        export const Daily = ({ history, match: {\n          params: {\n            date = moment().toISOString(),\n          } = {},\n        } = {} }: Props) => (\n              <div>\n                <div style={{ textAlign: 'right', paddingRight: '25px' }}>\n                  Show <DatePicker\n                    selected={moment(date)}\n                    className=\"datetime\"\n                    onChange={d => history.push(`./${d.toISOString()}`)}\n                  />\n                </div>\n                <WithData url=\"/payments/daily\" body={{ date: moment(date).toISOString() }}>\n                  <Flashcards date={moment(date)} />\n                </WithData>\n              </div>\n        );\n      ", Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"match\" is not required, but has no corresponding defaultProps declaration.", Line: 6, Column: 11, EndLine: 10, EndColumn: 13}}},
		// Upstream invalid-77
		{Code: "\n        function MyStatelessComponent({ foo, bar }) {\n          return <div>{foo}{bar}</div>;\n        }\n        const propTypes = forbidExtraProps({\n          foo: PropTypes.string,\n          bar: PropTypes.string.isRequired\n        });\n        MyStatelessComponent.propTypes = propTypes;\n      ", Tsx: true, Settings: map[string]any{"propWrapperFunctions": []any{"forbidExtraProps"}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "shouldHaveDefault", Message: "propType \"foo\" is not required, but has no corresponding defaultProps declaration.", Line: 6, Column: 11, EndLine: 6, EndColumn: 32}}},
		// Upstream invalid-78
		{Code: "\n      function MyStatelessComponent({ foo = 'foo' }) {\n        return <div>{foo}{bar}</div>;\n      }\n      MyStatelessComponent.propTypes = {\n        foo: PropTypes.string.isRequired,\n      };\n      ", Tsx: true, Options: []any{map[string]any{"functions": "defaultArguments"}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "noDefaultWithRequired", Message: "propType \"foo\" is required and should not have a defaultProps declaration.", Line: 2, Column: 39, EndLine: 2, EndColumn: 50}}},
		// Upstream invalid-79
		{Code: "\n      function MyStatelessComponent({ foo = 'foo', bar }) {\n        return <div>{foo}{bar}</div>;\n      }\n      MyStatelessComponent.propTypes = {\n        foo: PropTypes.string.isRequired,\n        bar: PropTypes.string\n      };\n      ", Tsx: true, Options: []any{map[string]any{"functions": "defaultArguments"}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "noDefaultWithRequired", Message: "propType \"foo\" is required and should not have a defaultProps declaration.", Line: 2, Column: 39, EndLine: 2, EndColumn: 50}, {MessageId: "shouldAssignObjectDefault", Message: "propType \"bar\" is not required, but has no corresponding default argument value.", Line: 2, Column: 52, EndLine: 2, EndColumn: 55}}},
	})
}
