// Code generated by internal/ipc/internal/generate; DO NOT EDIT.

use napi_derive::napi;

pub const PROTOCOL_VERSION: u32 = 1;
pub const SLOT_COUNT: usize = 16;
pub const SLOT_SIZE: usize = 16777216;
pub const HEADER_SIZE: usize = 4096;
pub const CAPACITY: usize = 268439552;
pub const PUBLICATION_STRIDE: usize = 4;

#[napi(object)]
pub struct SourceMapping {
    pub version: u32,
    pub fd: Option<i32>,
    pub handle: Option<String>,
    pub process_id: Option<u32>,
}
