import type { RslintConfigEntry } from '../define-config.js';

// Aligned with official eslint-plugin-unicorn@72.x recommended.
// Rules commented out with "not implemented" are in the official preset but not yet available.
// The official preset also injects `languageOptions.globals` (Array, Promise, Map, …);
// rslint's config entry doesn't expose a `globals` field, so that part is omitted.
const recommended: RslintConfigEntry = {
  plugins: ['unicorn'],
  rules: {
    // Core ESLint rules disabled by upstream once their unicorn equivalents take over.
    // Keep them enabled (i.e. don't override) until the unicorn replacements are implemented,
    // otherwise users would lose all coverage for these patterns.
    // 'logical-assignment-operators': 'off',
    // 'no-negated-condition': 'off',
    // 'no-nested-ternary': 'off',
    // 'no-process-exit': 'off',

    // 'unicorn/better-dom-traversing': 'error', // not implemented
    // 'unicorn/catch-error-name': 'error', // not implemented
    // 'unicorn/class-reference-in-static-methods': 'error', // not implemented
    // 'unicorn/comment-content': 'off', // not implemented
    // 'unicorn/consistent-assert': 'error', // not implemented
    // 'unicorn/consistent-boolean-name': 'error', // not implemented
    // 'unicorn/consistent-class-member-order': 'error', // not implemented
    // 'unicorn/consistent-compound-words': 'error', // not implemented
    // 'unicorn/consistent-conditional-object-spread': 'error', // not implemented
    // 'unicorn/consistent-date-clone': 'error', // not implemented
    // 'unicorn/consistent-destructuring': 'off', // not implemented
    // 'unicorn/consistent-empty-array-spread': 'error', // not implemented
    // 'unicorn/consistent-existence-index-check': 'error', // not implemented
    // 'unicorn/consistent-export-decorator-position': 'error', // not implemented
    // 'unicorn/consistent-function-scoping': 'error', // not implemented
    // 'unicorn/consistent-function-style': 'off', // not implemented
    // 'unicorn/consistent-json-file-read': 'error', // not implemented
    // 'unicorn/consistent-optional-chaining': 'error', // not implemented
    // 'unicorn/consistent-template-literal-escape': 'error', // not implemented
    // 'unicorn/consistent-tuple-labels': 'error', // not implemented
    // 'unicorn/custom-error-definition': 'off', // not implemented
    // 'unicorn/default-export-style': 'error', // not implemented
    // 'unicorn/dom-node-dataset': 'error', // not implemented
    // 'unicorn/empty-brace-spaces': 'error', // not implemented
    // 'unicorn/error-message': 'error', // not implemented
    // 'unicorn/escape-case': 'error', // not implemented
    // 'unicorn/expiring-todo-comments': 'error', // not implemented
    // 'unicorn/explicit-length-check': 'error', // not implemented
    // 'unicorn/explicit-timer-delay': 'error', // not implemented
    'unicorn/filename-case': 'error',
    // 'unicorn/id-match': 'off', // not implemented
    // 'unicorn/import-style': 'error', // not implemented
    // 'unicorn/isolated-functions': 'error', // not implemented
    // 'unicorn/logical-assignment-operators': 'error', // not implemented
    // 'unicorn/max-nested-calls': 'error', // not implemented
    // 'unicorn/name-replacements': 'error', // not implemented
    'unicorn/new-for-builtins': 'error',
    // 'unicorn/no-abusive-eslint-disable': 'error', // not implemented
    // 'unicorn/no-accessor-recursion': 'error', // not implemented
    // 'unicorn/no-accidental-bitwise-operator': 'error', // not implemented
    // 'unicorn/no-anonymous-default-export': 'error', // not implemented
    // 'unicorn/no-array-callback-reference': 'error', // not implemented
    // 'unicorn/no-array-concat-in-loop': 'error', // not implemented
    // 'unicorn/no-array-fill-with-reference-type': 'error', // not implemented
    // 'unicorn/no-array-from-fill': 'error', // not implemented
    // 'unicorn/no-array-front-mutation': 'off', // not implemented
    // 'unicorn/no-array-method-this-argument': 'error', // not implemented
    // 'unicorn/no-array-reduce': 'error', // not implemented
    // 'unicorn/no-array-reverse': 'error', // not implemented
    // 'unicorn/no-array-sort': 'error', // not implemented
    // 'unicorn/no-array-sort-for-min-max': 'error', // not implemented
    // 'unicorn/no-array-splice': 'error', // not implemented
    // 'unicorn/no-asterisk-prefix-in-documentation-comments': 'off', // not implemented
    // 'unicorn/no-async-promise-finally': 'error', // not implemented
    // 'unicorn/no-await-expression-member': 'error', // not implemented
    // 'unicorn/no-await-in-promise-methods': 'error', // not implemented
    // 'unicorn/no-blob-to-file': 'error', // not implemented
    // 'unicorn/no-boolean-sort-comparator': 'error', // not implemented
    // 'unicorn/no-break-in-nested-loop': 'error', // not implemented
    // 'unicorn/no-canvas-to-image': 'error', // not implemented
    // 'unicorn/no-chained-comparison': 'error', // not implemented
    // 'unicorn/no-collection-bracket-access': 'error', // not implemented
    // 'unicorn/no-computed-property-existence-check': 'error', // not implemented
    // 'unicorn/no-confusing-array-splice': 'error', // not implemented
    // 'unicorn/no-confusing-array-with': 'error', // not implemented
    // 'unicorn/no-console-spaces': 'error', // not implemented
    // 'unicorn/no-constant-zero-expression': 'error', // not implemented
    // 'unicorn/no-declarations-before-early-exit': 'error', // not implemented
    // 'unicorn/no-document-cookie': 'error', // not implemented
    // 'unicorn/no-double-comparison': 'error', // not implemented
    // 'unicorn/no-duplicate-if-branches': 'error', // not implemented
    // 'unicorn/no-duplicate-logical-operands': 'error', // not implemented
    // 'unicorn/no-duplicate-loops': 'error', // not implemented
    // 'unicorn/no-duplicate-set-values': 'error', // not implemented
    // 'unicorn/no-empty-file': 'error', // not implemented
    // 'unicorn/no-error-property-assignment': 'error', // not implemented
    // 'unicorn/no-exports-in-scripts': 'error', // not implemented
    // 'unicorn/no-for-each': 'error', // not implemented
    // 'unicorn/no-for-loop': 'error', // not implemented
    // 'unicorn/no-global-object-property-assignment': 'error', // not implemented
    // 'unicorn/no-immediate-mutation': 'error', // not implemented
    // 'unicorn/no-impossible-length-comparison': 'error', // not implemented
    // 'unicorn/no-incorrect-query-selector': 'error', // not implemented
    // 'unicorn/no-incorrect-template-string-interpolation': 'error', // not implemented
    'unicorn/no-instanceof-builtins': 'error',
    // 'unicorn/no-invalid-argument-count': 'error', // not implemented
    // 'unicorn/no-invalid-character-comparison': 'error', // not implemented
    // 'unicorn/no-invalid-fetch-options': 'error', // not implemented
    // 'unicorn/no-invalid-file-input-accept': 'off', // not implemented
    // 'unicorn/no-invalid-remove-event-listener': 'error', // not implemented
    // 'unicorn/no-invalid-well-known-symbol-methods': 'error', // not implemented
    // 'unicorn/no-keyword-prefix': 'off', // not implemented
    // 'unicorn/no-late-current-target-access': 'error', // not implemented
    // 'unicorn/no-late-event-control': 'error', // not implemented
    // 'unicorn/no-lonely-if': 'error', // not implemented
    // 'unicorn/no-loop-iterable-mutation': 'error', // not implemented
    // 'unicorn/no-magic-array-flat-depth': 'error', // not implemented
    // 'unicorn/no-manually-wrapped-comments': 'off', // not implemented
    // 'unicorn/no-mismatched-map-key': 'error', // not implemented
    // 'unicorn/no-misrefactored-assignment': 'error', // not implemented
    // 'unicorn/no-missing-local-resource': 'off', // not implemented
    // 'unicorn/no-multiple-promise-resolver-calls': 'error', // not implemented
    // 'unicorn/no-named-default': 'error', // not implemented
    // 'unicorn/no-negated-array-predicate': 'error', // not implemented
    // 'unicorn/no-negated-comparison': 'error', // not implemented
    // 'unicorn/no-negated-condition': 'error', // not implemented
    // 'unicorn/no-negation-in-equality-check': 'error', // not implemented
    // 'unicorn/no-nested-ternary': 'error', // not implemented
    // 'unicorn/no-new-array': 'error', // not implemented
    // 'unicorn/no-new-buffer': 'error', // not implemented
    // 'unicorn/no-non-function-verb-prefix': 'error', // not implemented
    // 'unicorn/no-nonstandard-builtin-properties': 'error', // not implemented
    // 'unicorn/no-null': 'error', // not implemented
    // 'unicorn/no-object-as-default-parameter': 'error', // not implemented
    // 'unicorn/no-object-methods-with-collections': 'error', // not implemented
    // 'unicorn/no-optional-chaining-on-undeclared-variable': 'error', // not implemented
    // 'unicorn/no-process-exit': 'error', // not implemented
    // 'unicorn/no-redundant-comparison': 'error', // not implemented
    // 'unicorn/no-return-array-push': 'error', // not implemented
    // 'unicorn/no-selector-as-dom-name': 'error', // not implemented
    // 'unicorn/no-shorthand-property-overrides': 'error', // not implemented
    // 'unicorn/no-single-promise-in-promise-methods': 'error', // not implemented
    'unicorn/no-static-only-class': 'error',
    // 'unicorn/no-subtraction-comparison': 'error', // not implemented
    'unicorn/no-thenable': 'error',
    // 'unicorn/no-this-assignment': 'error', // not implemented
    // 'unicorn/no-this-outside-of-class': 'error', // not implemented
    // 'unicorn/no-top-level-assignment-in-function': 'error', // not implemented
    // 'unicorn/no-top-level-side-effects': 'error', // not implemented
    // 'unicorn/no-transition-all': 'error', // not implemented
    // 'unicorn/no-typeof-undefined': 'error', // not implemented
    // 'unicorn/no-uncalled-method': 'error', // not implemented
    // 'unicorn/no-undeclared-class-members': 'error', // not implemented
    // 'unicorn/no-unnecessary-array-flat-depth': 'error', // not implemented
    // 'unicorn/no-unnecessary-array-flat-map': 'error', // not implemented
    // 'unicorn/no-unnecessary-array-splice-count': 'error', // not implemented
    // 'unicorn/no-unnecessary-await': 'error', // not implemented
    // 'unicorn/no-unnecessary-boolean-comparison': 'error', // not implemented
    // 'unicorn/no-unnecessary-fetch-options': 'error', // not implemented
    // 'unicorn/no-unnecessary-global-this': 'error', // not implemented
    // 'unicorn/no-unnecessary-nested-ternary': 'error', // not implemented
    // 'unicorn/no-unnecessary-polyfills': 'error', // not implemented
    // 'unicorn/no-unnecessary-slice-end': 'error', // not implemented
    // 'unicorn/no-unnecessary-splice': 'error', // not implemented
    // 'unicorn/no-unnecessary-string-trim': 'error', // not implemented
    // 'unicorn/no-unreadable-array-destructuring': 'error', // not implemented
    // 'unicorn/no-unreadable-for-of-expression': 'error', // not implemented
    // 'unicorn/no-unreadable-iife': 'error', // not implemented
    // 'unicorn/no-unreadable-new-expression': 'off', // not implemented
    // 'unicorn/no-unreadable-object-destructuring': 'error', // not implemented
    // 'unicorn/no-unsafe-buffer-conversion': 'error', // not implemented
    // 'unicorn/no-unsafe-dom-html': 'off', // not implemented
    // 'unicorn/no-unsafe-promise-all-settled-values': 'error', // not implemented
    // 'unicorn/no-unsafe-property-key': 'error', // not implemented
    // 'unicorn/no-unsafe-string-replacement': 'error', // not implemented
    // 'unicorn/no-unused-array-method-return': 'error', // not implemented
    // 'unicorn/no-unused-properties': 'off', // not implemented
    // 'unicorn/no-useless-boolean-cast': 'error', // not implemented
    // 'unicorn/no-useless-coercion': 'error', // not implemented
    // 'unicorn/no-useless-collection-argument': 'error', // not implemented
    // 'unicorn/no-useless-compound-assignment': 'error', // not implemented
    // 'unicorn/no-useless-concat': 'error', // not implemented
    // 'unicorn/no-useless-continue': 'error', // not implemented
    // 'unicorn/no-useless-delete-check': 'error', // not implemented
    // 'unicorn/no-useless-else': 'error', // not implemented
    // 'unicorn/no-useless-error-capture-stack-trace': 'error', // not implemented
    // 'unicorn/no-useless-fallback-in-spread': 'error', // not implemented
    // 'unicorn/no-useless-iterator-to-array': 'error', // not implemented
    // 'unicorn/no-useless-length-check': 'error', // not implemented
    // 'unicorn/no-useless-logical-operand': 'error', // not implemented
    // 'unicorn/no-useless-override': 'error', // not implemented
    // 'unicorn/no-useless-promise-resolve-reject': 'error', // not implemented
    // 'unicorn/no-useless-re-export': 'error', // not implemented
    // 'unicorn/no-useless-recursion': 'error', // not implemented
    // 'unicorn/no-useless-spread': 'error', // not implemented
    'unicorn/no-useless-switch-case': 'error',
    // 'unicorn/no-useless-template-literals': 'error', // not implemented
    // 'unicorn/no-useless-undefined': 'error', // not implemented
    // 'unicorn/no-xor-as-exponentiation': 'error', // not implemented
    // 'unicorn/no-zero-fractions': 'error', // not implemented
    // 'unicorn/number-literal-case': 'error', // not implemented
    // 'unicorn/numeric-separators-style': 'error', // not implemented
    // 'unicorn/operator-assignment': 'error', // not implemented
    // 'unicorn/prefer-abort-signal-any': 'error', // not implemented
    // 'unicorn/prefer-abort-signal-timeout': 'error', // not implemented
    // 'unicorn/prefer-add-event-listener': 'error', // not implemented
    // 'unicorn/prefer-add-event-listener-options': 'error', // not implemented
    // 'unicorn/prefer-aggregate-error': 'error', // not implemented
    // 'unicorn/prefer-array-find': 'error', // not implemented
    'unicorn/prefer-array-flat': 'error',
    'unicorn/prefer-array-flat-map': 'error',
    // 'unicorn/prefer-array-from-async': 'error', // not implemented
    // 'unicorn/prefer-array-from-map': 'error', // not implemented
    // 'unicorn/prefer-array-from-range': 'error', // not implemented
    // 'unicorn/prefer-array-index-of': 'error', // not implemented
    // 'unicorn/prefer-array-iterable-methods': 'error', // not implemented
    // 'unicorn/prefer-array-last-methods': 'error', // not implemented
    // 'unicorn/prefer-array-slice': 'error', // not implemented
    // 'unicorn/prefer-array-some': 'error', // not implemented
    // 'unicorn/prefer-at': 'error', // not implemented
    // 'unicorn/prefer-await': 'error', // not implemented
    // 'unicorn/prefer-bigint-literals': 'error', // not implemented
    // 'unicorn/prefer-blob-reading-methods': 'error', // not implemented
    // 'unicorn/prefer-block-statement-over-iife': 'error', // not implemented
    // 'unicorn/prefer-boolean-return': 'error', // not implemented
    // 'unicorn/prefer-class-fields': 'error', // not implemented
    // 'unicorn/prefer-classlist-toggle': 'error', // not implemented
    // 'unicorn/prefer-code-point': 'error', // not implemented
    // 'unicorn/prefer-continue': 'error', // not implemented
    // 'unicorn/prefer-date-now': 'error', // not implemented
    // 'unicorn/prefer-default-parameters': 'error', // not implemented
    // 'unicorn/prefer-direct-iteration': 'error', // not implemented
    // 'unicorn/prefer-dispose': 'off', // not implemented
    // 'unicorn/prefer-dom-node-append': 'error', // not implemented
    // 'unicorn/prefer-dom-node-html-methods': 'error', // not implemented
    // 'unicorn/prefer-dom-node-remove': 'error', // not implemented
    // 'unicorn/prefer-dom-node-replace-children': 'error', // not implemented
    // 'unicorn/prefer-dom-node-text-content': 'error', // not implemented
    // 'unicorn/prefer-early-return': 'error', // not implemented
    // 'unicorn/prefer-else-if': 'error', // not implemented
    // 'unicorn/prefer-error-is-error': 'off', // not implemented
    // 'unicorn/prefer-event-target': 'error', // not implemented
    // 'unicorn/prefer-explicit-viewport-units': 'off', // not implemented
    // 'unicorn/prefer-export-from': 'error', // not implemented
    // 'unicorn/prefer-flat-math-min-max': 'error', // not implemented
    // 'unicorn/prefer-get-or-insert-computed': 'error', // not implemented
    // 'unicorn/prefer-global-number-constants': 'error', // not implemented
    // 'unicorn/prefer-global-this': 'error', // not implemented
    // 'unicorn/prefer-group-by': 'error', // not implemented
    // 'unicorn/prefer-has-check': 'error', // not implemented
    // 'unicorn/prefer-hoisting-branch-code': 'error', // not implemented
    // 'unicorn/prefer-https': 'error', // not implemented
    // 'unicorn/prefer-identifier-import-export-specifiers': 'error', // not implemented
    // 'unicorn/prefer-import-meta-properties': 'off', // not implemented
    // 'unicorn/prefer-includes': 'error', // not implemented
    // 'unicorn/prefer-includes-over-repeated-comparisons': 'error', // not implemented
    // 'unicorn/prefer-iterable-in-constructor': 'error', // not implemented
    // 'unicorn/prefer-iterator-concat': 'off', // not implemented
    // 'unicorn/prefer-iterator-helpers': 'error', // not implemented
    // 'unicorn/prefer-iterator-to-array': 'error', // not implemented
    // 'unicorn/prefer-iterator-to-array-at-end': 'error', // not implemented
    // 'unicorn/prefer-keyboard-event-key': 'error', // not implemented
    // 'unicorn/prefer-location-assign': 'error', // not implemented
    // 'unicorn/prefer-logical-operator-over-ternary': 'error', // not implemented
    // 'unicorn/prefer-map-from-entries': 'error', // not implemented
    // 'unicorn/prefer-math-abs': 'error', // not implemented
    // 'unicorn/prefer-math-constants': 'error', // not implemented
    // 'unicorn/prefer-math-min-max': 'error', // not implemented
    // 'unicorn/prefer-math-trunc': 'error', // not implemented
    // 'unicorn/prefer-minimal-ternary': 'error', // not implemented
    // 'unicorn/prefer-modern-dom-apis': 'error', // not implemented
    // 'unicorn/prefer-modern-math-apis': 'error', // not implemented
    // 'unicorn/prefer-module': 'error', // not implemented
    // 'unicorn/prefer-native-coercion-functions': 'error', // not implemented
    // 'unicorn/prefer-negative-index': 'error', // not implemented
    'unicorn/prefer-node-protocol': 'error',
    // 'unicorn/prefer-number-coercion': 'error', // not implemented
    // 'unicorn/prefer-number-is-safe-integer': 'error', // not implemented
    'unicorn/prefer-number-properties': 'error',
    // 'unicorn/prefer-object-define-properties': 'error', // not implemented
    // 'unicorn/prefer-object-destructuring-defaults': 'error', // not implemented
    // 'unicorn/prefer-object-from-entries': 'error', // not implemented
    // 'unicorn/prefer-object-iterable-methods': 'error', // not implemented
    // 'unicorn/prefer-observer-apis': 'error', // not implemented
    // 'unicorn/prefer-optional-catch-binding': 'error', // not implemented
    // 'unicorn/prefer-path2d': 'error', // not implemented
    // 'unicorn/prefer-private-class-fields': 'error', // not implemented
    // 'unicorn/prefer-promise-try': 'error', // not implemented
    // 'unicorn/prefer-promise-with-resolvers': 'error', // not implemented
    // 'unicorn/prefer-prototype-methods': 'error', // not implemented
    // 'unicorn/prefer-query-selector': 'error', // not implemented
    // 'unicorn/prefer-queue-microtask': 'error', // not implemented
    // 'unicorn/prefer-reflect-apply': 'error', // not implemented
    // 'unicorn/prefer-regexp-escape': 'off', // not implemented
    // 'unicorn/prefer-regexp-test': 'error', // not implemented
    // 'unicorn/prefer-response-static-json': 'error', // not implemented
    // 'unicorn/prefer-scoped-selector': 'error', // not implemented
    // 'unicorn/prefer-set-has': 'error', // not implemented
    // 'unicorn/prefer-set-methods': 'error', // not implemented
    // 'unicorn/prefer-set-size': 'error', // not implemented
    // 'unicorn/prefer-short-arrow-method': 'off', // not implemented
    // 'unicorn/prefer-simple-condition-first': 'error', // not implemented
    // 'unicorn/prefer-simple-sort-comparator': 'error', // not implemented
    // 'unicorn/prefer-simplified-conditions': 'error', // not implemented
    // 'unicorn/prefer-single-array-predicate': 'error', // not implemented
    // 'unicorn/prefer-single-call': 'error', // not implemented
    // 'unicorn/prefer-single-object-destructuring': 'error', // not implemented
    // 'unicorn/prefer-single-replace': 'error', // not implemented
    // 'unicorn/prefer-smaller-scope': 'error', // not implemented
    // 'unicorn/prefer-split-limit': 'error', // not implemented
    // 'unicorn/prefer-spread': 'error', // not implemented
    // 'unicorn/prefer-string-match-all': 'error', // not implemented
    // 'unicorn/prefer-string-pad-start-end': 'error', // not implemented
    // 'unicorn/prefer-string-raw': 'error', // not implemented
    // 'unicorn/prefer-string-repeat': 'error', // not implemented
    // 'unicorn/prefer-string-replace-all': 'error', // not implemented
    // 'unicorn/prefer-string-slice': 'error', // not implemented
    // 'unicorn/prefer-string-starts-ends-with': 'error', // not implemented
    // 'unicorn/prefer-string-trim-start-end': 'error', // not implemented
    // 'unicorn/prefer-structured-clone': 'error', // not implemented
    // 'unicorn/prefer-switch': 'error', // not implemented
    // 'unicorn/prefer-temporal': 'off', // not implemented
    // 'unicorn/prefer-ternary': 'error', // not implemented
    // 'unicorn/prefer-then-catch': 'error', // not implemented
    // 'unicorn/prefer-toggle-attribute': 'error', // not implemented
    // 'unicorn/prefer-top-level-await': 'error', // not implemented
    // 'unicorn/prefer-type-error': 'error', // not implemented
    // 'unicorn/prefer-type-literal-last': 'error', // not implemented
    // 'unicorn/prefer-uint8array-base64': 'off', // not implemented
    // 'unicorn/prefer-unary-minus': 'error', // not implemented
    // 'unicorn/prefer-unicode-code-point-escapes': 'error', // not implemented
    // 'unicorn/prefer-url-can-parse': 'error', // not implemented
    // 'unicorn/prefer-url-href': 'error', // not implemented
    // 'unicorn/prefer-url-search-parameters': 'error', // not implemented
    // 'unicorn/prefer-while-loop-condition': 'error', // not implemented
    // 'unicorn/relative-url-style': 'error', // not implemented
    'unicorn/require-array-join-separator': 'error',
    // 'unicorn/require-array-sort-compare': 'error', // not implemented
    // 'unicorn/require-css-escape': 'error', // not implemented
    // 'unicorn/require-frontmatter-fields': 'off', // not implemented
    // 'unicorn/require-module-attributes': 'error', // not implemented
    // 'unicorn/require-module-specifiers': 'error', // not implemented
    'unicorn/require-number-to-fixed-digits-argument': 'error',
    // 'unicorn/require-passive-events': 'error', // not implemented
    // 'unicorn/require-post-message-target-origin': 'off', // not implemented
    // 'unicorn/require-proxy-trap-boolean-return': 'error', // not implemented
    // 'unicorn/string-content': 'off', // not implemented
    // 'unicorn/switch-case-braces': 'error', // not implemented
    // 'unicorn/switch-case-break-position': 'error', // not implemented
    // 'unicorn/template-indent': 'error', // not implemented
    // 'unicorn/text-encoding-identifier-case': 'error', // not implemented
    // 'unicorn/throw-new-error': 'error', // not implemented
    // 'unicorn/try-complexity': 'off', // not implemented
  },
};

export { recommended };
