// Code generated by scripts/sync-releases.mjs. DO NOT EDIT.

package buildinfo

const currentJSON = "{\"version\":\"unreleased\",\"typescript\":{\"commit\":\"1f70213d4922b434345f639b441681e470c7cfc1\",\"releaseVersion\":null}}"
