// Ported from eslint-plugin-unicorn v75.0.0; see LICENSE.
// https://github.com/sindresorhus/eslint-plugin-unicorn/blob/v75.0.0/test/explicit-timer-delay.js
package explicit_timer_delay_test

import (
	"testing"

	"github.com/web-infra-dev/rslint/internal/plugins/unicorn/fixtures"
	"github.com/web-infra-dev/rslint/internal/plugins/unicorn/rules/explicit_timer_delay"
	"github.com/web-infra-dev/rslint/internal/rule"
	"github.com/web-infra-dev/rslint/internal/rule_tester"
)

func TestExplicitTimerDelayUpstream(t *testing.T) {
	rule_tester.RunRuleTester(fixtures.GetRootDir(), "tsconfig.json", t, &explicit_timer_delay.ExplicitTimerDelayRule, []rule_tester.ValidTestCase{
		{Code: "setTimeout(() => console.log(\"Hello\"), 0);", FileName: "case.js", LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}},
		{Code: "setInterval(callback, 0);", FileName: "case.js", LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}},
		{Code: "setTimeout(() => console.log(\"Hello\"), 1000);", FileName: "case.js", LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}},
		{Code: "setInterval(callback, 100);", FileName: "case.js", LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}},
		{Code: "window.setTimeout(() => console.log(\"Hello\"), 0);", FileName: "case.js", LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}},
		{Code: "globalThis.setInterval(callback, 0);", FileName: "case.js", LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}},
		{Code: "global.setTimeout(() => {}, 0);", FileName: "case.js", LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}},
		{Code: "self.setTimeout(() => {}, 0);", FileName: "case.js", LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}},
		{Code: "setTimeout(callback, 0, arg1, arg2);", FileName: "case.js", LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}},
		{Code: "setInterval(callback, 100, arg1);", FileName: "case.js", LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}},
		{Code: "import {setTimeout as delay} from 'node:timers/promises';\n\nawait delay(100);", FileName: "case.js", LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}},
		{Code: "setTimeout?.(() => {});", FileName: "case.js", LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}},
		{Code: "window.setTimeout?.(callback);", FileName: "case.js", LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}},
		{Code: "setTimeout();", FileName: "case.js", LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}},
		{Code: "setTimeout(...args);", FileName: "case.js", LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}},
		{Code: "customSetTimeout(callback);", FileName: "case.js", LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}},
		{Code: "obj.customSetTimeout(callback);", FileName: "case.js", LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}},
		{Code: "globalThis[\"setTimeout\"](callback);", FileName: "case.js", LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}},
		{Code: "Math.setTimeout(callback);", FileName: "case.js", LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}},
		{Code: "foo.setTimeout(callback);", FileName: "case.js", LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}},
		{Code: "const window = foo;\nwindow.setTimeout(callback);", FileName: "case.js", LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}},
		{Code: "const self = foo;\nself.setInterval(callback);", FileName: "case.js", LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}},
		{Code: "setTimeout(() => console.log(\"Hello\"));", FileName: "case.js", Options: []any{"never"}, LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}},
		{Code: "setInterval(callback);", FileName: "case.js", Options: []any{"never"}, LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}},
		{Code: "window.setTimeout(() => console.log(\"Hello\"));", FileName: "case.js", Options: []any{"never"}, LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}},
		{Code: "globalThis.setInterval(callback);", FileName: "case.js", Options: []any{"never"}, LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}},
		{Code: "setTimeout((callback), 0);", FileName: "case.js", LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}},
		{Code: "setTimeout(() => console.log(\"Hello\"), 1000);", FileName: "case.js", Options: []any{"never"}, LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}},
		{Code: "setTimeout(callback, (1000));", FileName: "case.js", Options: []any{"never"}, LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}},
		{Code: "setInterval(callback, 100);", FileName: "case.js", Options: []any{"never"}, LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}},
		{Code: "setInterval(callback, 0, arg1);", FileName: "case.js", Options: []any{"never"}, LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}},
		{Code: "setTimeout(callback, 500, arg1);", FileName: "case.js", Options: []any{"never"}, LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}},
		{Code: "setTimeout(callback, 0, arg1, arg2);", FileName: "case.js", Options: []any{"never"}, LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}},
		{Code: "// ✅\nsetTimeout(() => console.log('Hello'), 1000);\nsetInterval(callback, 100);", FileName: "case.js", LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}},
		{Code: "// ✅\nsetTimeout(() => console.log('Hello'), 1000);\nglobalThis.setInterval(callback, 100);", FileName: "case.js", Options: []any{"never"}, LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}},
	}, []rule_tester.InvalidTestCase{
		{Code: "setTimeout(() => console.log(\"Hello\"));", FileName: "case.js", LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}, Output: []string{"setTimeout(() => console.log(\"Hello\"), 0);"}, Errors: []rule_tester.InvalidTestCaseError{
			{MessageId: "missing-delay", Message: "`setTimeout` should have an explicit delay argument.", Line: 1, Column: 1, EndLine: 1, EndColumn: 39, Suggestions: []rule_tester.InvalidTestCaseSuggestion{}},
		}},
		{Code: "setInterval(callback);", FileName: "case.js", LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}, Output: []string{"setInterval(callback, 0);"}, Errors: []rule_tester.InvalidTestCaseError{
			{MessageId: "missing-delay", Message: "`setInterval` should have an explicit delay argument.", Line: 1, Column: 1, EndLine: 1, EndColumn: 22, Suggestions: []rule_tester.InvalidTestCaseSuggestion{}},
		}},
		{Code: "window.setTimeout(() => console.log(\"Hello\"));", FileName: "case.js", LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}, Output: []string{"window.setTimeout(() => console.log(\"Hello\"), 0);"}, Errors: []rule_tester.InvalidTestCaseError{
			{MessageId: "missing-delay", Message: "`setTimeout` should have an explicit delay argument.", Line: 1, Column: 1, EndLine: 1, EndColumn: 46, Suggestions: []rule_tester.InvalidTestCaseSuggestion{}},
		}},
		{Code: "globalThis.setInterval(callback);", FileName: "case.js", LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}, Output: []string{"globalThis.setInterval(callback, 0);"}, Errors: []rule_tester.InvalidTestCaseError{
			{MessageId: "missing-delay", Message: "`setInterval` should have an explicit delay argument.", Line: 1, Column: 1, EndLine: 1, EndColumn: 33, Suggestions: []rule_tester.InvalidTestCaseSuggestion{}},
		}},
		{Code: "global.setTimeout(fn);", FileName: "case.js", LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}, Output: []string{"global.setTimeout(fn, 0);"}, Errors: []rule_tester.InvalidTestCaseError{
			{MessageId: "missing-delay", Message: "`setTimeout` should have an explicit delay argument.", Line: 1, Column: 1, EndLine: 1, EndColumn: 22, Suggestions: []rule_tester.InvalidTestCaseSuggestion{}},
		}},
		{Code: "self.setTimeout(fn);", FileName: "case.js", LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}, Output: []string{"self.setTimeout(fn, 0);"}, Errors: []rule_tester.InvalidTestCaseError{
			{MessageId: "missing-delay", Message: "`setTimeout` should have an explicit delay argument.", Line: 1, Column: 1, EndLine: 1, EndColumn: 20, Suggestions: []rule_tester.InvalidTestCaseSuggestion{}},
		}},
		{Code: "setTimeout(\n\t() => console.log(\"Hello\")\n);", FileName: "case.js", LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}, Output: []string{"setTimeout(\n\t() => console.log(\"Hello\"), 0\n);"}, Errors: []rule_tester.InvalidTestCaseError{
			{MessageId: "missing-delay", Message: "`setTimeout` should have an explicit delay argument.", Line: 1, Column: 1, EndLine: 3, EndColumn: 2, Suggestions: []rule_tester.InvalidTestCaseSuggestion{}},
		}},
		{Code: "setInterval(\n\tcallback\n);", FileName: "case.js", LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}, Output: []string{"setInterval(\n\tcallback, 0\n);"}, Errors: []rule_tester.InvalidTestCaseError{
			{MessageId: "missing-delay", Message: "`setInterval` should have an explicit delay argument.", Line: 1, Column: 1, EndLine: 3, EndColumn: 2, Suggestions: []rule_tester.InvalidTestCaseSuggestion{}},
		}},
		{Code: "setTimeout((callback));", FileName: "case.js", LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}, Output: []string{"setTimeout((callback), 0);"}, Errors: []rule_tester.InvalidTestCaseError{
			{MessageId: "missing-delay", Message: "`setTimeout` should have an explicit delay argument.", Line: 1, Column: 1, EndLine: 1, EndColumn: 23, Suggestions: []rule_tester.InvalidTestCaseSuggestion{}},
		}},
		{Code: "setTimeout(() => console.log(\"Hello\"), 0);", FileName: "case.js", Options: []any{"never"}, LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}, Output: []string{"setTimeout(() => console.log(\"Hello\"));"}, Errors: []rule_tester.InvalidTestCaseError{
			{MessageId: "redundant-delay", Message: "`setTimeout` should not have an explicit delay of `0`.", Line: 1, Column: 40, EndLine: 1, EndColumn: 41, Suggestions: []rule_tester.InvalidTestCaseSuggestion{}},
		}},
		{Code: "setInterval(callback, 0);", FileName: "case.js", Options: []any{"never"}, LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}, Output: []string{"setInterval(callback);"}, Errors: []rule_tester.InvalidTestCaseError{
			{MessageId: "redundant-delay", Message: "`setInterval` should not have an explicit delay of `0`.", Line: 1, Column: 23, EndLine: 1, EndColumn: 24, Suggestions: []rule_tester.InvalidTestCaseSuggestion{}},
		}},
		{Code: "setTimeout((callback), 0);", FileName: "case.js", Options: []any{"never"}, LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}, Output: []string{"setTimeout((callback));"}, Errors: []rule_tester.InvalidTestCaseError{
			{MessageId: "redundant-delay", Message: "`setTimeout` should not have an explicit delay of `0`.", Line: 1, Column: 24, EndLine: 1, EndColumn: 25, Suggestions: []rule_tester.InvalidTestCaseSuggestion{}},
		}},
		{Code: "self.setTimeout(fn, 0);", FileName: "case.js", Options: []any{"never"}, LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}, Output: []string{"self.setTimeout(fn);"}, Errors: []rule_tester.InvalidTestCaseError{
			{MessageId: "redundant-delay", Message: "`setTimeout` should not have an explicit delay of `0`.", Line: 1, Column: 21, EndLine: 1, EndColumn: 22, Suggestions: []rule_tester.InvalidTestCaseSuggestion{}},
		}},
		{Code: "self.setInterval(fn, 0);", FileName: "case.js", Options: []any{"never"}, LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}, Output: []string{"self.setInterval(fn);"}, Errors: []rule_tester.InvalidTestCaseError{
			{MessageId: "redundant-delay", Message: "`setInterval` should not have an explicit delay of `0`.", Line: 1, Column: 22, EndLine: 1, EndColumn: 23, Suggestions: []rule_tester.InvalidTestCaseSuggestion{}},
		}},
		{Code: "window.setTimeout(() => console.log(\"Hello\"), 0);", FileName: "case.js", Options: []any{"never"}, LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}, Output: []string{"window.setTimeout(() => console.log(\"Hello\"));"}, Errors: []rule_tester.InvalidTestCaseError{
			{MessageId: "redundant-delay", Message: "`setTimeout` should not have an explicit delay of `0`.", Line: 1, Column: 47, EndLine: 1, EndColumn: 48, Suggestions: []rule_tester.InvalidTestCaseSuggestion{}},
		}},
		{Code: "globalThis.setInterval(callback, 0);", FileName: "case.js", Options: []any{"never"}, LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}, Output: []string{"globalThis.setInterval(callback);"}, Errors: []rule_tester.InvalidTestCaseError{
			{MessageId: "redundant-delay", Message: "`setInterval` should not have an explicit delay of `0`.", Line: 1, Column: 34, EndLine: 1, EndColumn: 35, Suggestions: []rule_tester.InvalidTestCaseSuggestion{}},
		}},
		{Code: "global.setTimeout(fn, 0);", FileName: "case.js", Options: []any{"never"}, LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}, Output: []string{"global.setTimeout(fn);"}, Errors: []rule_tester.InvalidTestCaseError{
			{MessageId: "redundant-delay", Message: "`setTimeout` should not have an explicit delay of `0`.", Line: 1, Column: 23, EndLine: 1, EndColumn: 24, Suggestions: []rule_tester.InvalidTestCaseSuggestion{}},
		}},
		{Code: "setTimeout(() => console.log(\"Hello\"), -0);", FileName: "case.js", Options: []any{"never"}, LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}, Output: []string{"setTimeout(() => console.log(\"Hello\"));"}, Errors: []rule_tester.InvalidTestCaseError{
			{MessageId: "redundant-delay", Message: "`setTimeout` should not have an explicit delay of `0`.", Line: 1, Column: 40, EndLine: 1, EndColumn: 42, Suggestions: []rule_tester.InvalidTestCaseSuggestion{}},
		}},
		{Code: "setTimeout(callback, +0);", FileName: "case.js", Options: []any{"never"}, LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}, Output: []string{"setTimeout(callback);"}, Errors: []rule_tester.InvalidTestCaseError{
			{MessageId: "redundant-delay", Message: "`setTimeout` should not have an explicit delay of `0`.", Line: 1, Column: 22, EndLine: 1, EndColumn: 24, Suggestions: []rule_tester.InvalidTestCaseSuggestion{}},
		}},
		{Code: "setInterval(callback, +(0));", FileName: "case.js", Options: []any{"never"}, LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}, Output: []string{"setInterval(callback);"}, Errors: []rule_tester.InvalidTestCaseError{
			{MessageId: "redundant-delay", Message: "`setInterval` should not have an explicit delay of `0`.", Line: 1, Column: 23, EndLine: 1, EndColumn: 27, Suggestions: []rule_tester.InvalidTestCaseSuggestion{}},
		}},
		{Code: "setTimeout(callback, (-0));", FileName: "case.js", Options: []any{"never"}, LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}, Output: []string{"setTimeout(callback);"}, Errors: []rule_tester.InvalidTestCaseError{
			{MessageId: "redundant-delay", Message: "`setTimeout` should not have an explicit delay of `0`.", Line: 1, Column: 23, EndLine: 1, EndColumn: 25, Suggestions: []rule_tester.InvalidTestCaseSuggestion{}},
		}},
		{Code: "setTimeout(\n\t() => console.log(\"Hello\"),\n\t0\n);", FileName: "case.js", Options: []any{"never"}, LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}, Output: []string{"setTimeout(\n\t() => console.log(\"Hello\")\n);"}, Errors: []rule_tester.InvalidTestCaseError{
			{MessageId: "redundant-delay", Message: "`setTimeout` should not have an explicit delay of `0`.", Line: 3, Column: 2, EndLine: 3, EndColumn: 3, Suggestions: []rule_tester.InvalidTestCaseSuggestion{}},
		}},
		{Code: "setInterval(\n\tcallback,\n\t0\n);", FileName: "case.js", Options: []any{"never"}, LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}, Output: []string{"setInterval(\n\tcallback\n);"}, Errors: []rule_tester.InvalidTestCaseError{
			{MessageId: "redundant-delay", Message: "`setInterval` should not have an explicit delay of `0`.", Line: 3, Column: 2, EndLine: 3, EndColumn: 3, Suggestions: []rule_tester.InvalidTestCaseSuggestion{}},
		}},
		{Code: "setTimeout(callback, (0));", FileName: "case.js", Options: []any{"never"}, LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}, Output: []string{"setTimeout(callback);"}, Errors: []rule_tester.InvalidTestCaseError{
			{MessageId: "redundant-delay", Message: "`setTimeout` should not have an explicit delay of `0`.", Line: 1, Column: 23, EndLine: 1, EndColumn: 24, Suggestions: []rule_tester.InvalidTestCaseSuggestion{}},
		}},
		{Code: "// ❌\nsetTimeout(() => console.log('Hello'));\n\n// ✅\nsetTimeout(() => console.log('Hello'), 0);", FileName: "case.js", LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}, Output: []string{"// ❌\nsetTimeout(() => console.log('Hello'), 0);\n\n// ✅\nsetTimeout(() => console.log('Hello'), 0);"}, Errors: []rule_tester.InvalidTestCaseError{
			{MessageId: "missing-delay", Message: "`setTimeout` should have an explicit delay argument.", Line: 2, Column: 1, EndLine: 2, EndColumn: 39, Suggestions: []rule_tester.InvalidTestCaseSuggestion{}},
		}},
		{Code: "// ❌\nsetInterval(callback);\n\n// ✅\nsetInterval(callback, 0);", FileName: "case.js", LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}, Output: []string{"// ❌\nsetInterval(callback, 0);\n\n// ✅\nsetInterval(callback, 0);"}, Errors: []rule_tester.InvalidTestCaseError{
			{MessageId: "missing-delay", Message: "`setInterval` should have an explicit delay argument.", Line: 2, Column: 1, EndLine: 2, EndColumn: 22, Suggestions: []rule_tester.InvalidTestCaseSuggestion{}},
		}},
		{Code: "// ❌\nwindow.setTimeout(() => console.log('Hello'));\n\n// ✅\nwindow.setTimeout(() => console.log('Hello'), 0);", FileName: "case.js", LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}, Output: []string{"// ❌\nwindow.setTimeout(() => console.log('Hello'), 0);\n\n// ✅\nwindow.setTimeout(() => console.log('Hello'), 0);"}, Errors: []rule_tester.InvalidTestCaseError{
			{MessageId: "missing-delay", Message: "`setTimeout` should have an explicit delay argument.", Line: 2, Column: 1, EndLine: 2, EndColumn: 46, Suggestions: []rule_tester.InvalidTestCaseSuggestion{}},
		}},
		{Code: "// ❌\nglobalThis.setInterval(callback);\n\n// ✅\nglobalThis.setInterval(callback, 0);", FileName: "case.js", LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}, Output: []string{"// ❌\nglobalThis.setInterval(callback, 0);\n\n// ✅\nglobalThis.setInterval(callback, 0);"}, Errors: []rule_tester.InvalidTestCaseError{
			{MessageId: "missing-delay", Message: "`setInterval` should have an explicit delay argument.", Line: 2, Column: 1, EndLine: 2, EndColumn: 33, Suggestions: []rule_tester.InvalidTestCaseSuggestion{}},
		}},
		{Code: "// ❌\nsetTimeout(() => console.log('Hello'), 0);\n\n// ✅\nsetTimeout(() => console.log('Hello'));", FileName: "case.js", Options: []any{"never"}, LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}, Output: []string{"// ❌\nsetTimeout(() => console.log('Hello'));\n\n// ✅\nsetTimeout(() => console.log('Hello'));"}, Errors: []rule_tester.InvalidTestCaseError{
			{MessageId: "redundant-delay", Message: "`setTimeout` should not have an explicit delay of `0`.", Line: 2, Column: 40, EndLine: 2, EndColumn: 41, Suggestions: []rule_tester.InvalidTestCaseSuggestion{}},
		}},
		{Code: "// ❌\nsetInterval(callback, 0);\n\n// ✅\nsetInterval(callback);", FileName: "case.js", Options: []any{"never"}, LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}, Output: []string{"// ❌\nsetInterval(callback);\n\n// ✅\nsetInterval(callback);"}, Errors: []rule_tester.InvalidTestCaseError{
			{MessageId: "redundant-delay", Message: "`setInterval` should not have an explicit delay of `0`.", Line: 2, Column: 23, EndLine: 2, EndColumn: 24, Suggestions: []rule_tester.InvalidTestCaseSuggestion{}},
		}},
		{Code: "// ❌\nwindow.setTimeout(() => console.log('Hello'), 0);\n\n// ✅\nwindow.setTimeout(() => console.log('Hello'));", FileName: "case.js", Options: []any{"never"}, LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}, Output: []string{"// ❌\nwindow.setTimeout(() => console.log('Hello'));\n\n// ✅\nwindow.setTimeout(() => console.log('Hello'));"}, Errors: []rule_tester.InvalidTestCaseError{
			{MessageId: "redundant-delay", Message: "`setTimeout` should not have an explicit delay of `0`.", Line: 2, Column: 47, EndLine: 2, EndColumn: 48, Suggestions: []rule_tester.InvalidTestCaseSuggestion{}},
		}},
		{Code: "// ❌\nglobalThis.setInterval(callback, 0);\n\n// ✅\nglobalThis.setInterval(callback);", FileName: "case.js", Options: []any{"never"}, LanguageOptions: rule.LanguageOptions{SourceType: "module"}, Globals: map[string]any{"setTimeout": "readonly", "setInterval": "readonly", "window": "readonly", "globalThis": "readonly", "global": "readonly", "self": "readonly"}, Output: []string{"// ❌\nglobalThis.setInterval(callback);\n\n// ✅\nglobalThis.setInterval(callback);"}, Errors: []rule_tester.InvalidTestCaseError{
			{MessageId: "redundant-delay", Message: "`setInterval` should not have an explicit delay of `0`.", Line: 2, Column: 34, EndLine: 2, EndColumn: 35, Suggestions: []rule_tester.InvalidTestCaseSuggestion{}},
		}},
	})
}
