package react_plugin

import (
	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/boolean_prop_naming"
	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/button_has_type"
	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/forbid_component_props"
	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/jsx_boolean_value"
	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/jsx_closing_tag_location"
	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/jsx_equals_spacing"
	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/jsx_filename_extension"
	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/jsx_first_prop_new_line"
	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/jsx_key"
	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/jsx_max_props_per_line"
	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/jsx_no_bind"
	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/jsx_no_duplicate_props"
	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/jsx_no_target_blank"
	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/jsx_no_undef"
	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/jsx_pascal_case"
	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/jsx_props_no_multi_spaces"
	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/jsx_uses_react"
	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/jsx_uses_vars"
	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/jsx_wrap_multilines"
	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/no_access_state_in_setstate"
	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/no_children_prop"
	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/no_danger"
	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/no_danger_with_children"
	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/no_deprecated"
	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/no_did_update_set_state"
	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/no_direct_mutation_state"
	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/no_find_dom_node"
	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/no_is_mounted"
	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/no_redundant_should_component_update"
	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/no_render_return_value"
	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/no_string_refs"
	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/no_this_in_sfc"
	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/no_typos"
	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/no_unescaped_entities"
	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/no_unknown_property"
	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/no_unstable_nested_components"
	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/no_unused_class_component_methods"
	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/no_unused_state"
	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/no_will_update_set_state"
	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/prefer_es6_class"
	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/prefer_stateless_function"
	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/react_in_jsx_scope"
	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/require_render_return"
	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/self_closing_comp"
	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/style_prop_object"
	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/void_dom_elements_no_children"
	"github.com/web-infra-dev/rslint/internal/rule"

	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/jsx_child_element_spacing"
	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/jsx_curly_brace_presence"
	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/jsx_no_comment_textnodes"
	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/jsx_no_leaked_render"
	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/jsx_no_script_url"
)

func GetAllRules() []rule.Rule {
	return []rule.Rule{
		boolean_prop_naming.BooleanPropNamingRule,
		button_has_type.ButtonHasTypeRule,
		forbid_component_props.ForbidComponentPropsRule,
		jsx_boolean_value.JsxBooleanValueRule,
		jsx_closing_tag_location.JsxClosingTagLocationRule,
		jsx_equals_spacing.JsxEqualsSpacingRule,
		jsx_filename_extension.JsxFilenameExtensionRule,
		jsx_first_prop_new_line.JsxFirstPropNewLineRule,
		jsx_key.JsxKeyRule,
		jsx_max_props_per_line.JsxMaxPropsPerLineRule,
		jsx_no_bind.JsxNoBindRule,
		jsx_no_duplicate_props.JsxNoDuplicatePropsRule,
		jsx_no_target_blank.JsxNoTargetBlankRule,
		jsx_no_undef.JsxNoUndefRule,
		jsx_pascal_case.JsxPascalCaseRule,
		jsx_props_no_multi_spaces.JsxPropsNoMultiSpacesRule,
		jsx_uses_react.JsxUsesReactRule,
		jsx_uses_vars.JsxUsesVarsRule,
		jsx_wrap_multilines.JsxWrapMultilinesRule,
		no_access_state_in_setstate.NoAccessStateInSetstateRule,
		no_children_prop.NoChildrenPropRule,
		no_danger.NoDangerRule,
		no_danger_with_children.NoDangerWithChildrenRule,
		no_deprecated.NoDeprecatedRule,
		no_did_update_set_state.NoDidUpdateSetStateRule,
		no_direct_mutation_state.NoDirectMutationStateRule,
		no_find_dom_node.NoFindDomNodeRule,
		no_is_mounted.NoIsMountedRule,
		no_unstable_nested_components.NoUnstableNestedComponentsRule,
		no_unused_class_component_methods.NoUnusedClassComponentMethodsRule,
		no_unused_state.NoUnusedStateRule,
		no_redundant_should_component_update.NoRedundantShouldComponentUpdateRule,
		no_render_return_value.NoRenderReturnValueRule,
		no_string_refs.NoStringRefsRule,
		no_this_in_sfc.NoThisInSfcRule,
		no_typos.NoTyposRule,
		no_unescaped_entities.NoUnescapedEntitiesRule,
		no_unknown_property.NoUnknownPropertyRule,
		no_will_update_set_state.NoWillUpdateSetStateRule,
		prefer_es6_class.PreferEs6ClassRule,
		prefer_stateless_function.PreferStatelessFunctionRule,
		react_in_jsx_scope.ReactInJsxScopeRule,
		require_render_return.RequireRenderReturnRule,
		self_closing_comp.SelfClosingCompRule,
		style_prop_object.StylePropObjectRule,
		void_dom_elements_no_children.VoidDomElementsNoChildrenRule,
		jsx_child_element_spacing.JsxChildElementSpacingRule,
		jsx_curly_brace_presence.JsxCurlyBracePresenceRule,
		jsx_no_comment_textnodes.JsxNoCommentTextnodesRule,
		jsx_no_leaked_render.JsxNoLeakedRenderRule,
		jsx_no_script_url.JsxNoScriptUrlRule,
	}
}
