/**
 * @fileoverview enforce consistent line breaks inside function parentheses
 * @author Teddy Katz
 *
 * Ported verbatim from @stylistic/eslint-plugin v5.10.0:
 *   packages/eslint-plugin/rules/function-paren-newline/function-paren-newline.test.ts
 *
 * Transformations applied per the porting spec:
 *  - `run({ name, rule, lang, valid, invalid })` -> `ruleTester.run('function-paren-newline', null as never, { valid, invalid })`.
 *  - The `$` unindent template tag (`unindent` from eslint-vitest-rule-tester /
 *    @antfu/utils) is evaluated to its real multi-line string: leading/trailing
 *    fully-whitespace lines are dropped and the common leading indentation is
 *    stripped. Trailing whitespace inside a line is preserved (several fix
 *    `output`s depend on it).
 *  - The local error helper constants are inlined to their final `{ messageId }`:
 *      LEFT_MISSING_ERROR    -> { messageId: 'expectedAfter' }
 *      LEFT_UNEXPECTED_ERROR -> { messageId: 'unexpectedAfter' }
 *      RIGHT_MISSING_ERROR   -> { messageId: 'expectedBefore' }
 *      RIGHT_UNEXPECTED_ERROR-> { messageId: 'unexpectedBefore' }
 *      EXPECTED_BETWEEN      -> { messageId: 'expectedBetween' }
 *  - `parserOptions` (ecmaVersion 2017/2020) and `parser: tsParser` dropped —
 *    rslint parses every fixture with ts-go via the generated tsconfig; async
 *    arrows, dynamic `import()`, and TS generics are all valid TS there.
 *
 * The upstream file is a single `run()` block — there is no second `if (!skipBabel)`
 * block and no Babel/Flow cases. The `._css_` / `._json_` / `._markdown_` test files
 * don't exist for this rule. No `suggestions` and no output-only invalid cases exist.
 *
 * Cases that surface a real rslint<->upstream gap are NOT deleted or altered: they
 * are moved to the `KNOWN GAPS` block at the bottom, each annotated with what
 * upstream expects vs. what rslint produces.
 */

import { RuleTester } from '../rule-tester';

const ruleTester = new RuleTester();

ruleTester.run('function-paren-newline', null as never, {
  valid: [
    "new new Foo();",
    "function baz(foo, bar) {}",
    "(function(foo, bar) {});",
    "(function baz(foo, bar) {});",
    "(foo, bar) => {};",
    "foo => {};",
    "baz(foo, bar);",
    "function baz() {}",
    "function baz(\n    foo,\n    bar\n) {}",
    "(function(\n    foo,\n    bar\n) {});",
    "(function baz(\n    foo,\n    bar\n) {});",
    "(\n    foo,\n    bar\n) => {};",
    "baz(\n    foo,\n    bar\n);",
    "baz(`foo\n    bar`)",
    "new Foo(bar, baz)",
    "new Foo",
    "new (Foo)",
    "(foo)\n(bar)",
    "foo.map(value => {\n  return value;\n})",
    { code: "function baz(foo, bar) {}", options: ["multiline"] },
    { code: "async (foo, bar) => {};" },
    { code: "async (\n    foo,\n    bar\n) => {};" },
    { code: "async foo => {};" },
    { code: "import(source)" },
    { code: "import(source\n  + ext)" },
    { code: "import(source, options)" },
    { code: "import(source\n  + ext, options)" },
    { code: "function baz(foo, bar) {}", options: ["multiline-arguments"] },
    { code: "function baz(foo) {}", options: ["multiline-arguments"] },
    { code: "(function(foo, bar) {});", options: ["multiline-arguments"] },
    { code: "(function(foo) {});", options: ["multiline-arguments"] },
    { code: "(function baz(foo, bar) {});", options: ["multiline-arguments"] },
    { code: "(function baz(foo) {});", options: ["multiline-arguments"] },
    { code: "(foo, bar) => {};", options: ["multiline-arguments"] },
    { code: "foo => {};", options: ["multiline-arguments"] },
    { code: "baz(foo, bar);", options: ["multiline-arguments"] },
    { code: "baz(foo);", options: ["multiline-arguments"] },
    { code: "function baz() {}", options: ["multiline-arguments"] },
    { code: "function baz(\n    foo,\n    bar\n) {}", options: ["multiline-arguments"] },
    { code: "function baz(\n    foo\n) {}", options: ["multiline-arguments"] },
    { code: "(function(\n    foo,\n    bar\n) {});", options: ["multiline-arguments"] },
    { code: "(function(\n    foo\n) {});", options: ["multiline-arguments"] },
    { code: "(function baz(\n    foo,\n    bar\n) {});", options: ["multiline-arguments"] },
    { code: "(function baz(\n    foo\n) {});", options: ["multiline-arguments"] },
    { code: "(\n    foo,\n    bar\n) => {};", options: ["multiline-arguments"] },
    { code: "(\n    foo\n) => {};", options: ["multiline-arguments"] },
    { code: "baz(\n    foo,\n    bar\n);", options: ["multiline-arguments"] },
    { code: "baz(\n    foo\n);", options: ["multiline-arguments"] },
    { code: "baz(`foo\n    bar`)", options: ["multiline-arguments"] },
    { code: "new Foo(bar, baz)", options: ["multiline-arguments"] },
    { code: "new Foo(bar)", options: ["multiline-arguments"] },
    { code: "new Foo", options: ["multiline-arguments"] },
    { code: "new (Foo)", options: ["multiline-arguments"] },
    { code: "async (foo, bar) => {};", options: ["multiline-arguments"] },
    { code: "async (foo) => {};", options: ["multiline-arguments"] },
    { code: "async (\n    foo\n) => {};", options: ["multiline-arguments"] },
    { code: "async (\n    foo,\n    bar\n) => {};", options: ["multiline-arguments"] },
    { code: "async foo => {};", options: ["multiline-arguments"] },
    { code: "import(source)", options: ["multiline-arguments"] },
    { code: "import(source\n  + ext)", options: ["multiline-arguments"] },
    { code: "import(source, options)", options: ["multiline-arguments"] },
    { code: "import(source\n  + ext, options)", options: ["multiline-arguments"] },
    { code: "(foo)\n(bar)", options: ["multiline-arguments"] },
    { code: "foo.map(value => {\n  return value;\n})", options: ["multiline-arguments"] },
    { code: "function baz(\n    foo,\n    bar\n) {}", options: ["always"] },
    { code: "(function(\n    foo,\n    bar\n) {});", options: ["always"] },
    { code: "(function baz(\n    foo,\n    bar\n) {});", options: ["always"] },
    { code: "(\n    foo,\n    bar\n) => {};", options: ["always"] },
    { code: "baz(\n    foo,\n    bar\n);", options: ["always"] },
    { code: "function baz(\n) {}", options: ["always"] },
    { code: "async (\n    foo\n) => {};", options: ["always"] },
    { code: "async (\n    foo,\n    bar\n) => {};", options: ["always"] },
    { code: "async foo => {};", options: ["always"] },
    { code: "import(\n  source\n)", options: ["always"] },
    { code: "import(\n  source, options\n)", options: ["always"] },
    { code: "function baz(foo, bar) {}", options: ["never"] },
    { code: "(function(foo, bar) {});", options: ["never"] },
    { code: "(function baz(foo, bar) {});", options: ["never"] },
    { code: "(foo, bar) => {};", options: ["never"] },
    { code: "baz(foo, bar);", options: ["never"] },
    { code: "function baz() {}", options: ["never"] },
    { code: "async (foo, bar) => {};", options: ["never"] },
    { code: "async foo => {};", options: ["never"] },
    { code: "import(source)", options: ["never"] },
    { code: "import(source, options)", options: ["never"] },
    { code: "function baz(foo, bar) {}", options: [{"minItems":3}] },
    { code: "function baz(\n    foo, bar, qux\n) {}", options: [{"minItems":3}] },
    { code: "baz(\n    foo, bar, qux\n);", options: [{"minItems":3}] },
    { code: "baz(foo, bar);", options: [{"minItems":3}] },
    { code: "async (foo, bar) => {};", options: [{"minItems":3}] },
    { code: "async (\n    foo,\n    bar,\n    baz\n) => {};", options: [{"minItems":3}] },
    { code: "async foo => {};", options: [{"minItems":3}] },
    { code: "import(source)", options: [{"minItems":3}] },
    { code: "import(\n  source\n)", options: [{"minItems":1}] },
    { code: "import(source, options)", options: [{"minItems":3}] },
    { code: "import(\n  source, options\n)", options: [{"minItems":2}] },
    { code: "foo(bar, baz)", options: ["consistent"] },
    { code: "foo(bar,\nbaz)", options: ["consistent"] },
    { code: "foo(\n    bar, baz\n)", options: ["consistent"] },
    { code: "foo(\n    bar,\n    baz\n)", options: ["consistent"] },
    { code: "async (foo, bar) => {};", options: ["consistent"] },
    { code: "async foo => {};", options: ["consistent"] },
    { code: "async (foo,\n    bar) => {};", options: ["consistent"] },
    { code: "async (\n    foo, bar\n) => {};", options: ["consistent"] },
    { code: "async (\n    foo,\n    bar\n) => {};", options: ["consistent"] },
    { code: "import(source)", options: ["consistent"] },
    { code: "import(source, options)", options: ["consistent"] },
    { code: "import(\n  source, options\n)", options: ["consistent"] },
    { code: "const method6 = (\n  abc: number,\n  def: () => void,\n): [\n  string,\n  () => void\n] => [`a${abc}`, def];\nmethod6(3, () => {});", options: ["multiline"] },
    { code: "function a<A extends Array<any>, T extends (...args: any[]) => any> (\n  b: T,\n  c: any,\n): any {}", options: ["multiline"] },
    { code: "const a = function <A extends Array<any>, T extends (...args: any[]) => any> (\n  b: T,\n  c: any,\n): any {}", options: ["multiline"] },
    { code: "a<Array<any>, (...args: any[]) => any>(\n  b,\n  c,\n)", options: ["multiline"] },
  ],

  invalid: [
    { code: "function baz(foo,\n    bar\n) {}", output: "function baz(\nfoo,\n    bar\n) {}", errors: [{ messageId: "expectedAfter" }] },
    { code: "(function(\n    foo,\n    bar) {})", output: "(function(\n    foo,\n    bar\n) {})", errors: [{ messageId: "expectedBefore" }] },
    { code: "(function baz(foo,\n    bar) {})", output: "(function baz(\nfoo,\n    bar\n) {})", errors: [{ messageId: "expectedAfter" }, { messageId: "expectedBefore" }] },
    { code: "baz(\n    foo, bar);", output: "baz(foo, bar);", errors: [{ messageId: "unexpectedAfter" }] },
    { code: "(foo, bar\n) => {};", output: "(foo, bar) => {};", errors: [{ messageId: "unexpectedBefore" }] },
    { code: "function baz(\n    foo, bar\n) {}", output: "function baz(foo, bar) {}", errors: [{ messageId: "unexpectedAfter" }, { messageId: "unexpectedBefore" }] },
    { code: "function baz(\n    foo =\n    1\n) {}", output: "function baz(foo =\n    1) {}", errors: [{ messageId: "unexpectedAfter" }, { messageId: "unexpectedBefore" }] },
    { code: "function baz(\n) {}", output: "function baz() {}", errors: [{ messageId: "unexpectedAfter" }, { messageId: "unexpectedBefore" }] },
    { code: "new Foo(bar,\n    baz);", output: "new Foo(\nbar,\n    baz\n);", errors: [{ messageId: "expectedAfter" }, { messageId: "expectedBefore" }] },
    { code: "function baz(/* not fixed due to comment */\nfoo) {}", output: null, errors: [{ messageId: "unexpectedAfter" }] },
    { code: "function baz(foo\n/* not fixed due to comment */) {}", output: null, errors: [{ messageId: "unexpectedBefore" }] },
    { code: "async (\n    foo, bar\n) => {};", output: "async (foo, bar) => {};", errors: [{ messageId: "unexpectedAfter" }, { messageId: "unexpectedBefore" }] },
    { code: "async (foo, bar\n) => {};", output: "async (foo, bar) => {};", errors: [{ messageId: "unexpectedBefore" }] },
    { code: "async (foo,\n    bar) => {};", output: "async (\nfoo,\n    bar\n) => {};", errors: [{ messageId: "expectedAfter" }, { messageId: "expectedBefore" }] },
    { code: "async (\n    foo,\n    bar) => {};", output: "async (\n    foo,\n    bar\n) => {};", errors: [{ messageId: "expectedBefore" }] },
    { code: "import(\n  source\n)", output: "import(source)", errors: [{ messageId: "unexpectedAfter" }, { messageId: "unexpectedBefore" }] },
    { code: "import(\n  source, options\n)", output: "import(source, options)", errors: [{ messageId: "unexpectedAfter" }, { messageId: "unexpectedBefore" }] },
    { code: "function baz(foo,\n    bar\n) {}", options: ["multiline-arguments"], output: "function baz(\nfoo,\n    bar\n) {}", errors: [{ messageId: "expectedAfter" }] },
    { code: "(function(\n    foo,\n    bar) {})", options: ["multiline-arguments"], output: "(function(\n    foo,\n    bar\n) {})", errors: [{ messageId: "expectedBefore" }] },
    { code: "(function baz(foo,\n    bar) {})", options: ["multiline-arguments"], output: "(function baz(\nfoo,\n    bar\n) {})", errors: [{ messageId: "expectedAfter" }, { messageId: "expectedBefore" }] },
    { code: "baz(\n    foo, bar);", options: ["multiline-arguments"], output: "baz(foo, bar);", errors: [{ messageId: "unexpectedAfter" }] },
    { code: "(foo, bar\n) => {};", options: ["multiline-arguments"], output: "(foo, bar) => {};", errors: [{ messageId: "unexpectedBefore" }] },
    { code: "function baz(\n    foo, bar\n) {}", options: ["multiline-arguments"], output: "function baz(foo, bar) {}", errors: [{ messageId: "unexpectedAfter" }, { messageId: "unexpectedBefore" }] },
    { code: "function baz(\n) {}", options: ["multiline-arguments"], output: "function baz() {}", errors: [{ messageId: "unexpectedAfter" }, { messageId: "unexpectedBefore" }] },
    { code: "new Foo(bar,\n    baz);", options: ["multiline-arguments"], output: "new Foo(\nbar,\n    baz\n);", errors: [{ messageId: "expectedAfter" }, { messageId: "expectedBefore" }] },
    { code: "function baz(/* not fixed due to comment */\nfoo) {}", options: ["multiline-arguments"], output: "function baz(/* not fixed due to comment */\nfoo\n) {}", errors: [{ messageId: "expectedBefore" }] },
    { code: "function baz(foo\n/* not fixed due to comment */) {}", options: ["multiline-arguments"], output: null, errors: [{ messageId: "unexpectedBefore" }] },
    { code: "function baz(\n    qwe,\n    foo, bar\n) {}", options: ["multiline-arguments"], output: "function baz(\n    qwe,\n    foo, \nbar\n) {}", errors: [{ messageId: "expectedBetween" }] },
    { code: "function baz(\n    qwe, foo,\n    bar\n) {}", options: ["multiline-arguments"], output: "function baz(\n    qwe, \nfoo,\n    bar\n) {}", errors: [{ messageId: "expectedBetween" }] },
    { code: "function baz(qwe, foo,\n    bar) {}", options: ["multiline-arguments"], output: "function baz(\nqwe, \nfoo,\n    bar\n) {}", errors: [{ messageId: "expectedAfter" }, { messageId: "expectedBetween" }, { messageId: "expectedBefore" }] },
    { code: "baz(\n    foo);", options: ["multiline-arguments"], output: "baz(\n    foo\n);", errors: [{ messageId: "expectedBefore" }] },
    { code: "baz(foo\n    );", options: ["multiline-arguments"], output: "baz(foo);", errors: [{ messageId: "unexpectedBefore" }] },
    { code: "async (foo, bar\n) => {};", options: ["multiline-arguments"], output: "async (foo, bar) => {};", errors: [{ messageId: "unexpectedBefore" }] },
    { code: "async (foo,\n    bar) => {};", options: ["multiline-arguments"], output: "async (\nfoo,\n    bar\n) => {};", errors: [{ messageId: "expectedAfter" }, { messageId: "expectedBefore" }] },
    { code: "async (\n    foo,\n    bar) => {};", options: ["multiline-arguments"], output: "async (\n    foo,\n    bar\n) => {};", errors: [{ messageId: "expectedBefore" }] },
    { code: "import(source\n)", options: ["multiline-arguments"], output: "import(source)", errors: [{ messageId: "unexpectedBefore" }] },
    { code: "import(\n  source)", options: ["multiline-arguments"], output: "import(\n  source\n)", errors: [{ messageId: "expectedBefore" }] },
    { code: "import(source, options\n)", options: ["multiline-arguments"], output: "import(source, options)", errors: [{ messageId: "unexpectedBefore" }] },
    { code: "import(source,\noptions)", options: ["multiline-arguments"], output: "import(\nsource,\noptions\n)", errors: [{ messageId: "expectedAfter" }, { messageId: "expectedBefore" }] },
    { code: "function baz(foo,\n    bar\n) {}", options: ["always"], output: "function baz(\nfoo,\n    bar\n) {}", errors: [{ messageId: "expectedAfter" }] },
    { code: "(function(\n    foo,\n    bar) {})", options: ["always"], output: "(function(\n    foo,\n    bar\n) {})", errors: [{ messageId: "expectedBefore" }] },
    { code: "(function baz(foo,\n    bar) {})", options: ["always"], output: "(function baz(\nfoo,\n    bar\n) {})", errors: [{ messageId: "expectedAfter" }, { messageId: "expectedBefore" }] },
    { code: "function baz(foo, bar) {}", options: ["always"], output: "function baz(\nfoo, bar\n) {}", errors: [{ messageId: "expectedAfter" }, { messageId: "expectedBefore" }] },
    { code: "(function(foo, bar) {});", options: ["always"], output: "(function(\nfoo, bar\n) {});", errors: [{ messageId: "expectedAfter" }, { messageId: "expectedBefore" }] },
    { code: "(function baz(foo, bar) {});", options: ["always"], output: "(function baz(\nfoo, bar\n) {});", errors: [{ messageId: "expectedAfter" }, { messageId: "expectedBefore" }] },
    { code: "(foo, bar) => {};", options: ["always"], output: "(\nfoo, bar\n) => {};", errors: [{ messageId: "expectedAfter" }, { messageId: "expectedBefore" }] },
    { code: "baz(foo, bar);", options: ["always"], output: "baz(\nfoo, bar\n);", errors: [{ messageId: "expectedAfter" }, { messageId: "expectedBefore" }] },
    { code: "function baz() {}", options: ["always"], output: "function baz(\n) {}", errors: [{ messageId: "expectedAfter" }, { messageId: "expectedBefore" }] },
    { code: "async (foo, bar) => {};", options: ["always"], output: "async (\nfoo, bar\n) => {};", errors: [{ messageId: "expectedAfter" }, { messageId: "expectedBefore" }] },
    { code: "async (foo,\n    bar) => {};", options: ["always"], output: "async (\nfoo,\n    bar\n) => {};", errors: [{ messageId: "expectedAfter" }, { messageId: "expectedBefore" }] },
    { code: "async (\n    foo,\n    bar) => {};", options: ["always"], output: "async (\n    foo,\n    bar\n) => {};", errors: [{ messageId: "expectedBefore" }] },
    { code: "import(source)", options: ["always"], output: "import(\nsource\n)", errors: [{ messageId: "expectedAfter" }, { messageId: "expectedBefore" }] },
    { code: "import(source, options)", options: ["always"], output: "import(\nsource, options\n)", errors: [{ messageId: "expectedAfter" }, { messageId: "expectedBefore" }] },
    { code: "function baz(foo,\n    bar\n) {}", options: ["never"], output: "function baz(foo,\n    bar) {}", errors: [{ messageId: "unexpectedBefore" }] },
    { code: "(function(\n    foo,\n    bar) {})", options: ["never"], output: "(function(foo,\n    bar) {})", errors: [{ messageId: "unexpectedAfter" }] },
    { code: "new new C()(\n);", options: ["never"], output: "new new C()();", errors: [{ messageId: "unexpectedAfter" }, { messageId: "unexpectedBefore" }] },
    { code: "function baz(\n    foo,\n    bar\n) {}", options: ["never"], output: "function baz(foo,\n    bar) {}", errors: [{ messageId: "unexpectedAfter" }, { messageId: "unexpectedBefore" }] },
    { code: "(function(\n    foo,\n    bar\n) {});", options: ["never"], output: "(function(foo,\n    bar) {});", errors: [{ messageId: "unexpectedAfter" }, { messageId: "unexpectedBefore" }] },
    { code: "(function baz(\n    foo,\n    bar\n) {});", options: ["never"], output: "(function baz(foo,\n    bar) {});", errors: [{ messageId: "unexpectedAfter" }, { messageId: "unexpectedBefore" }] },
    { code: "(\n    foo,\n    bar\n) => {};", options: ["never"], output: "(foo,\n    bar) => {};", errors: [{ messageId: "unexpectedAfter" }, { messageId: "unexpectedBefore" }] },
    { code: "baz(\n    foo,\n    bar\n);", options: ["never"], output: "baz(foo,\n    bar);", errors: [{ messageId: "unexpectedAfter" }, { messageId: "unexpectedBefore" }] },
    { code: "function baz(\n) {}", options: ["never"], output: "function baz() {}", errors: [{ messageId: "unexpectedAfter" }, { messageId: "unexpectedBefore" }] },
    { code: "async (\n    foo,\n    bar\n) => {};", options: ["never"], output: "async (foo,\n    bar) => {};", errors: [{ messageId: "unexpectedAfter" }, { messageId: "unexpectedBefore" }] },
    { code: "async (\n    foo,\n    bar) => {};", options: ["never"], output: "async (foo,\n    bar) => {};", errors: [{ messageId: "unexpectedAfter" }] },
    { code: "import(\n  source\n)", options: ["never"], output: "import(source)", errors: [{ messageId: "unexpectedAfter" }, { messageId: "unexpectedBefore" }] },
    { code: "import(\n  source, options\n)", options: ["never"], output: "import(source, options)", errors: [{ messageId: "unexpectedAfter" }, { messageId: "unexpectedBefore" }] },
    { code: "function baz(foo, bar, qux) {}", options: [{"minItems":3}], output: "function baz(\nfoo, bar, qux\n) {}", errors: [{ messageId: "expectedAfter" }, { messageId: "expectedBefore" }] },
    { code: "function baz(\n    foo, bar\n) {}", options: [{"minItems":3}], output: "function baz(foo, bar) {}", errors: [{ messageId: "unexpectedAfter" }, { messageId: "unexpectedBefore" }] },
    { code: "baz(foo, bar, qux);", options: [{"minItems":3}], output: "baz(\nfoo, bar, qux\n);", errors: [{ messageId: "expectedAfter" }, { messageId: "expectedBefore" }] },
    { code: "baz(\n    foo,\n    bar\n);", options: [{"minItems":3}], output: "baz(foo,\n    bar);", errors: [{ messageId: "unexpectedAfter" }, { messageId: "unexpectedBefore" }] },
    { code: "async (\n    foo,\n    bar\n) => {};", options: [{"minItems":3}], output: "async (foo,\n    bar) => {};", errors: [{ messageId: "unexpectedAfter" }, { messageId: "unexpectedBefore" }] },
    { code: "async (\n    foo,\n    bar) => {};", options: [{"minItems":3}], output: "async (foo,\n    bar) => {};", errors: [{ messageId: "unexpectedAfter" }] },
    { code: "async (foo, bar, baz) => {};", options: [{"minItems":3}], output: "async (\nfoo, bar, baz\n) => {};", errors: [{ messageId: "expectedAfter" }, { messageId: "expectedBefore" }] },
    { code: "import(\n  source\n)", options: [{"minItems":3}], output: "import(source)", errors: [{ messageId: "unexpectedAfter" }, { messageId: "unexpectedBefore" }] },
    { code: "import(source)", options: [{"minItems":1}], output: "import(\nsource\n)", errors: [{ messageId: "expectedAfter" }, { messageId: "expectedBefore" }] },
    { code: "import(\n  source, options\n)", options: [{"minItems":3}], output: "import(source, options)", errors: [{ messageId: "unexpectedAfter" }, { messageId: "unexpectedBefore" }] },
    { code: "import(source, options)", options: [{"minItems":2}], output: "import(\nsource, options\n)", errors: [{ messageId: "expectedAfter" }, { messageId: "expectedBefore" }] },
    { code: "foo(\n    bar,\n    baz)", options: ["consistent"], output: "foo(\n    bar,\n    baz\n)", errors: [{ messageId: "expectedBefore" }] },
    { code: "foo(bar,\n    baz\n)", options: ["consistent"], output: "foo(bar,\n    baz)", errors: [{ messageId: "unexpectedBefore" }] },
    { code: "async (\n    foo,\n    bar) => {};", options: ["consistent"], output: "async (\n    foo,\n    bar\n) => {};", errors: [{ messageId: "expectedBefore" }] },
    { code: "async (foo,\n    bar\n) => {};", options: ["consistent"], output: "async (foo,\n    bar) => {};", errors: [{ messageId: "unexpectedBefore" }] },
    { code: "import(source\n)", options: ["consistent"], output: "import(source)", errors: [{ messageId: "unexpectedBefore" }] },
    { code: "import(\n  source)", options: ["consistent"], output: "import(\n  source\n)", errors: [{ messageId: "expectedBefore" }] },
    { code: "import(source, options\n)", options: ["consistent"], output: "import(source, options)", errors: [{ messageId: "unexpectedBefore" }] },
    { code: "import(\n  source, options)", options: ["consistent"], output: "import(\n  source, options\n)", errors: [{ messageId: "expectedBefore" }] },
    { code: "const method6 = (\n  abc: number,\n  def: () => void,\n): [\n  string,\n  () => void\n] => [`a${abc}`, def];\nmethod6(3, () => {});", options: ["never"], output: "const method6 = (abc: number,\n  def: () => void,): [\n  string,\n  () => void\n] => [`a${abc}`, def];\nmethod6(3, () => {});", errors: [{ messageId: "unexpectedAfter" }, { messageId: "unexpectedBefore" }] },
  ],
});
