package node_plugin

import (
	"github.com/web-infra-dev/rslint/internal/plugins/node/rules/callback_return"
	"github.com/web-infra-dev/rslint/internal/plugins/node/rules/exports_style"
	"github.com/web-infra-dev/rslint/internal/plugins/node/rules/file_extension_in_import"
	"github.com/web-infra-dev/rslint/internal/plugins/node/rules/global_require"
	"github.com/web-infra-dev/rslint/internal/plugins/node/rules/handle_callback_err"
	"github.com/web-infra-dev/rslint/internal/plugins/node/rules/hashbang"
	"github.com/web-infra-dev/rslint/internal/plugins/node/rules/no_callback_literal"
	"github.com/web-infra-dev/rslint/internal/plugins/node/rules/no_deprecated_api"
	"github.com/web-infra-dev/rslint/internal/plugins/node/rules/no_exports_assign"
	"github.com/web-infra-dev/rslint/internal/plugins/node/rules/no_extraneous_import"
	"github.com/web-infra-dev/rslint/internal/plugins/node/rules/no_extraneous_require"
	"github.com/web-infra-dev/rslint/internal/plugins/node/rules/no_missing_import"
	"github.com/web-infra-dev/rslint/internal/plugins/node/rules/no_missing_require"
	"github.com/web-infra-dev/rslint/internal/plugins/node/rules/no_mixed_requires"
	"github.com/web-infra-dev/rslint/internal/plugins/node/rules/no_new_require"
	"github.com/web-infra-dev/rslint/internal/plugins/node/rules/no_path_concat"
	"github.com/web-infra-dev/rslint/internal/plugins/node/rules/no_process_env"
	"github.com/web-infra-dev/rslint/internal/plugins/node/rules/no_process_exit"
	"github.com/web-infra-dev/rslint/internal/plugins/node/rules/no_restricted_import"
	"github.com/web-infra-dev/rslint/internal/plugins/node/rules/no_restricted_require"
	"github.com/web-infra-dev/rslint/internal/plugins/node/rules/no_sync"
	"github.com/web-infra-dev/rslint/internal/plugins/node/rules/no_top_level_await"
	"github.com/web-infra-dev/rslint/internal/plugins/node/rules/no_unpublished_bin"
	"github.com/web-infra-dev/rslint/internal/plugins/node/rules/no_unpublished_import"
	"github.com/web-infra-dev/rslint/internal/plugins/node/rules/prefer_global/buffer"
	"github.com/web-infra-dev/rslint/internal/plugins/node/rules/prefer_global/console"
	"github.com/web-infra-dev/rslint/internal/plugins/node/rules/prefer_global/process"
	"github.com/web-infra-dev/rslint/internal/plugins/node/rules/prefer_global/text_decoder"
	"github.com/web-infra-dev/rslint/internal/plugins/node/rules/prefer_global/text_encoder"
	"github.com/web-infra-dev/rslint/internal/plugins/node/rules/prefer_global/url"
	"github.com/web-infra-dev/rslint/internal/plugins/node/rules/prefer_global/url_search_params"
	"github.com/web-infra-dev/rslint/internal/plugins/node/rules/prefer_node_protocol"
	"github.com/web-infra-dev/rslint/internal/plugins/node/rules/prefer_promises/dns"
	"github.com/web-infra-dev/rslint/internal/plugins/node/rules/prefer_promises/fs"
	"github.com/web-infra-dev/rslint/internal/rule"
)

func GetAllRules() []rule.Rule {
	return []rule.Rule{
		callback_return.CallbackReturnRule,
		exports_style.ExportsStyleRule,
		file_extension_in_import.FileExtensionInImportRule,
		global_require.GlobalRequireRule,
		handle_callback_err.HandleCallbackErrRule,
		hashbang.HashbangRule,
		no_callback_literal.NoCallbackLiteralRule,
		no_deprecated_api.NoDeprecatedAPIRule,
		no_exports_assign.NoExportsAssignRule,
		no_extraneous_import.NoExtraneousImportRule,
		no_extraneous_require.NoExtraneousRequireRule,
		no_missing_import.NoMissingImportRule,
		no_missing_require.NoMissingRequireRule,
		no_mixed_requires.NoMixedRequiresRule,
		no_new_require.NoNewRequireRule,
		no_path_concat.NoPathConcatRule,
		no_process_env.NoProcessEnvRule,
		no_process_exit.NoProcessExitRule,
		no_restricted_import.NoRestrictedImportRule,
		no_restricted_require.NoRestrictedRequireRule,
		no_sync.NoSyncRule,
		no_top_level_await.NoTopLevelAwaitRule,
		no_unpublished_bin.NoUnpublishedBinRule,
		no_unpublished_import.NoUnpublishedImportRule,
		buffer.PreferGlobalBufferRule,
		console.PreferGlobalConsoleRule,
		process.ProcessRule,
		text_decoder.TextDecoderRule,
		text_encoder.TextEncoderRule,
		url.PreferGlobalURLRule,
		url_search_params.URLSearchParamsRule,
		prefer_node_protocol.PreferNodeProtocolRule,
		dns.PreferPromisesDNSRule,
		fs.PreferPromisesFSRule,
	}
}
