// TestNoInvalidHtmlAttributeRuleUpstream migrates every valid and invalid fixture
// from eslint-plugin-react v7.37.5's tests/lib/rules/no-invalid-html-attribute.js.
// The cases are deliberately written as explicit literals to preserve the upstream suite.
// Data assertions are retained for the value-bearing and non-string branches.
// ESTree `type` values are not copied: ts-go node kinds do not have a one-to-one
// mapping to ESTree names, and native diagnostics intentionally store source
// ranges rather than parser-specific node type strings.
package no_invalid_html_attribute

import (
	"testing"

	"github.com/web-infra-dev/rslint/internal/plugins/react/rules/fixtures"
	"github.com/web-infra-dev/rslint/internal/rule_tester"
)

func TestNoInvalidHtmlAttributeRuleUpstream(t *testing.T) {
	rule_tester.RunRuleTester(fixtures.GetRootDir(), "tsconfig.json", t, &NoInvalidHtmlAttributeRule, []rule_tester.ValidTestCase{
		{Code: `<a rel="alternate"></a>`, Tsx: true},
		{Code: `React.createElement("a", { rel: "alternate" })`, Tsx: true},
		{Code: `React.createElement("a", { rel: ["alternate"] })`, Tsx: true},
		{Code: `<a rel="author"></a>`, Tsx: true},
		{Code: `React.createElement("a", { rel: "author" })`, Tsx: true},
		{Code: `React.createElement("a", { rel: ["author"] })`, Tsx: true},
		{Code: `<a rel="bookmark"></a>`, Tsx: true},
		{Code: `React.createElement("a", { rel: "bookmark" })`, Tsx: true},
		{Code: `React.createElement("a", { rel: ["bookmark"] })`, Tsx: true},
		{Code: `<a rel="external"></a>`, Tsx: true},
		{Code: `React.createElement("a", { rel: "external" })`, Tsx: true},
		{Code: `React.createElement("a", { rel: ["external"] })`, Tsx: true},
		{Code: `<a rel="help"></a>`, Tsx: true},
		{Code: `React.createElement("a", { rel: "help" })`, Tsx: true},
		{Code: `React.createElement("a", { rel: ["help"] })`, Tsx: true},
		{Code: `<a rel="license"></a>`, Tsx: true},
		{Code: `React.createElement("a", { rel: "license" })`, Tsx: true},
		{Code: `React.createElement("a", { rel: ["license"] })`, Tsx: true},
		{Code: `<a rel="next"></a>`, Tsx: true},
		{Code: `React.createElement("a", { rel: "next" })`, Tsx: true},
		{Code: `React.createElement("a", { rel: ["next"] })`, Tsx: true},
		{Code: `<a rel="nofollow"></a>`, Tsx: true},
		{Code: `React.createElement("a", { rel: "nofollow" })`, Tsx: true},
		{Code: `React.createElement("a", { rel: ["nofollow"] })`, Tsx: true},
		{Code: `<a rel="noopener"></a>`, Tsx: true},
		{Code: `React.createElement("a", { rel: "noopener" })`, Tsx: true},
		{Code: `React.createElement("a", { rel: ["noopener"] })`, Tsx: true},
		{Code: `<a rel="noreferrer"></a>`, Tsx: true},
		{Code: `React.createElement("a", { rel: "noreferrer" })`, Tsx: true},
		{Code: `React.createElement("a", { rel: ["noreferrer"] })`, Tsx: true},
		{Code: `<a rel="opener"></a>`, Tsx: true},
		{Code: `React.createElement("a", { rel: "opener" })`, Tsx: true},
		{Code: `React.createElement("a", { rel: ["opener"] })`, Tsx: true},
		{Code: `<a rel="prev"></a>`, Tsx: true},
		{Code: `React.createElement("a", { rel: "prev" })`, Tsx: true},
		{Code: `React.createElement("a", { rel: ["prev"] })`, Tsx: true},
		{Code: `<a rel="search"></a>`, Tsx: true},
		{Code: `React.createElement("a", { rel: "search" })`, Tsx: true},
		{Code: `React.createElement("a", { rel: ["search"] })`, Tsx: true},
		{Code: `<a rel="tag"></a>`, Tsx: true},
		{Code: `React.createElement("a", { rel: "tag" })`, Tsx: true},
		{Code: `React.createElement("a", { rel: ["tag"] })`, Tsx: true},
		{Code: `<area rel="alternate"></area>`, Tsx: true},
		{Code: `React.createElement("area", { rel: "alternate" })`, Tsx: true},
		{Code: `React.createElement("area", { rel: ["alternate"] })`, Tsx: true},
		{Code: `<area rel="author"></area>`, Tsx: true},
		{Code: `React.createElement("area", { rel: "author" })`, Tsx: true},
		{Code: `React.createElement("area", { rel: ["author"] })`, Tsx: true},
		{Code: `<area rel="bookmark"></area>`, Tsx: true},
		{Code: `React.createElement("area", { rel: "bookmark" })`, Tsx: true},
		{Code: `React.createElement("area", { rel: ["bookmark"] })`, Tsx: true},
		{Code: `<area rel="external"></area>`, Tsx: true},
		{Code: `React.createElement("area", { rel: "external" })`, Tsx: true},
		{Code: `React.createElement("area", { rel: ["external"] })`, Tsx: true},
		{Code: `<area rel="help"></area>`, Tsx: true},
		{Code: `React.createElement("area", { rel: "help" })`, Tsx: true},
		{Code: `React.createElement("area", { rel: ["help"] })`, Tsx: true},
		{Code: `<area rel="license"></area>`, Tsx: true},
		{Code: `React.createElement("area", { rel: "license" })`, Tsx: true},
		{Code: `React.createElement("area", { rel: ["license"] })`, Tsx: true},
		{Code: `<area rel="next"></area>`, Tsx: true},
		{Code: `React.createElement("area", { rel: "next" })`, Tsx: true},
		{Code: `React.createElement("area", { rel: ["next"] })`, Tsx: true},
		{Code: `<area rel="nofollow"></area>`, Tsx: true},
		{Code: `React.createElement("area", { rel: "nofollow" })`, Tsx: true},
		{Code: `React.createElement("area", { rel: ["nofollow"] })`, Tsx: true},
		{Code: `<area rel="noopener"></area>`, Tsx: true},
		{Code: `React.createElement("area", { rel: "noopener" })`, Tsx: true},
		{Code: `React.createElement("area", { rel: ["noopener"] })`, Tsx: true},
		{Code: `<area rel="noreferrer"></area>`, Tsx: true},
		{Code: `React.createElement("area", { rel: "noreferrer" })`, Tsx: true},
		{Code: `React.createElement("area", { rel: ["noreferrer"] })`, Tsx: true},
		{Code: `<area rel="opener"></area>`, Tsx: true},
		{Code: `React.createElement("area", { rel: "opener" })`, Tsx: true},
		{Code: `React.createElement("area", { rel: ["opener"] })`, Tsx: true},
		{Code: `<area rel="prev"></area>`, Tsx: true},
		{Code: `React.createElement("area", { rel: "prev" })`, Tsx: true},
		{Code: `React.createElement("area", { rel: ["prev"] })`, Tsx: true},
		{Code: `<area rel="search"></area>`, Tsx: true},
		{Code: `React.createElement("area", { rel: "search" })`, Tsx: true},
		{Code: `React.createElement("area", { rel: ["search"] })`, Tsx: true},
		{Code: `<area rel="tag"></area>`, Tsx: true},
		{Code: `React.createElement("area", { rel: "tag" })`, Tsx: true},
		{Code: `React.createElement("area", { rel: ["tag"] })`, Tsx: true},
		{Code: `<link rel="alternate"></link>`, Tsx: true},
		{Code: `React.createElement("link", { rel: "alternate" })`, Tsx: true},
		{Code: `React.createElement("link", { rel: ["alternate"] })`, Tsx: true},
		{Code: `<link rel="author"></link>`, Tsx: true},
		{Code: `React.createElement("link", { rel: "author" })`, Tsx: true},
		{Code: `React.createElement("link", { rel: ["author"] })`, Tsx: true},
		{Code: `<link rel="canonical"></link>`, Tsx: true},
		{Code: `React.createElement("link", { rel: "canonical" })`, Tsx: true},
		{Code: `React.createElement("link", { rel: ["canonical"] })`, Tsx: true},
		{Code: `<link rel="dns-prefetch"></link>`, Tsx: true},
		{Code: `React.createElement("link", { rel: "dns-prefetch" })`, Tsx: true},
		{Code: `React.createElement("link", { rel: ["dns-prefetch"] })`, Tsx: true},
		{Code: `<link rel="help"></link>`, Tsx: true},
		{Code: `React.createElement("link", { rel: "help" })`, Tsx: true},
		{Code: `React.createElement("link", { rel: ["help"] })`, Tsx: true},
		{Code: `<link rel="icon"></link>`, Tsx: true},
		{Code: `React.createElement("link", { rel: "icon" })`, Tsx: true},
		{Code: `React.createElement("link", { rel: ["icon"] })`, Tsx: true},
		{Code: `<link rel="shortcut icon"></link>`, Tsx: true},
		{Code: `React.createElement("link", { rel: "shortcut icon" })`, Tsx: true},
		{Code: `React.createElement("link", { rel: ["shortcut icon"] })`, Tsx: true},
		{Code: `<link rel="license"></link>`, Tsx: true},
		{Code: `React.createElement("link", { rel: "license" })`, Tsx: true},
		{Code: `React.createElement("link", { rel: ["license"] })`, Tsx: true},
		{Code: `<link rel="manifest"></link>`, Tsx: true},
		{Code: `React.createElement("link", { rel: "manifest" })`, Tsx: true},
		{Code: `React.createElement("link", { rel: ["manifest"] })`, Tsx: true},
		{Code: `<link rel="modulepreload"></link>`, Tsx: true},
		{Code: `React.createElement("link", { rel: "modulepreload" })`, Tsx: true},
		{Code: `React.createElement("link", { rel: ["modulepreload"] })`, Tsx: true},
		{Code: `<link rel="next"></link>`, Tsx: true},
		{Code: `React.createElement("link", { rel: "next" })`, Tsx: true},
		{Code: `React.createElement("link", { rel: ["next"] })`, Tsx: true},
		{Code: `<link rel="pingback"></link>`, Tsx: true},
		{Code: `React.createElement("link", { rel: "pingback" })`, Tsx: true},
		{Code: `React.createElement("link", { rel: ["pingback"] })`, Tsx: true},
		{Code: `<link rel="preconnect"></link>`, Tsx: true},
		{Code: `React.createElement("link", { rel: "preconnect" })`, Tsx: true},
		{Code: `React.createElement("link", { rel: ["preconnect"] })`, Tsx: true},
		{Code: `<link rel="prefetch"></link>`, Tsx: true},
		{Code: `React.createElement("link", { rel: "prefetch" })`, Tsx: true},
		{Code: `React.createElement("link", { rel: ["prefetch"] })`, Tsx: true},
		{Code: `<link rel="preload"></link>`, Tsx: true},
		{Code: `React.createElement("link", { rel: "preload" })`, Tsx: true},
		{Code: `React.createElement("link", { rel: ["preload"] })`, Tsx: true},
		{Code: `<link rel="prerender"></link>`, Tsx: true},
		{Code: `React.createElement("link", { rel: "prerender" })`, Tsx: true},
		{Code: `React.createElement("link", { rel: ["prerender"] })`, Tsx: true},
		{Code: `<link rel="prev"></link>`, Tsx: true},
		{Code: `React.createElement("link", { rel: "prev" })`, Tsx: true},
		{Code: `React.createElement("link", { rel: ["prev"] })`, Tsx: true},
		{Code: `<link rel="search"></link>`, Tsx: true},
		{Code: `React.createElement("link", { rel: "search" })`, Tsx: true},
		{Code: `React.createElement("link", { rel: ["search"] })`, Tsx: true},
		{Code: `<link rel="stylesheet"></link>`, Tsx: true},
		{Code: `React.createElement("link", { rel: "stylesheet" })`, Tsx: true},
		{Code: `React.createElement("link", { rel: ["stylesheet"] })`, Tsx: true},
		{Code: `<form rel="external"></form>`, Tsx: true},
		{Code: `React.createElement("form", { rel: "external" })`, Tsx: true},
		{Code: `React.createElement("form", { rel: ["external"] })`, Tsx: true},
		{Code: `<form rel="help"></form>`, Tsx: true},
		{Code: `React.createElement("form", { rel: "help" })`, Tsx: true},
		{Code: `React.createElement("form", { rel: ["help"] })`, Tsx: true},
		{Code: `<form rel="license"></form>`, Tsx: true},
		{Code: `React.createElement("form", { rel: "license" })`, Tsx: true},
		{Code: `React.createElement("form", { rel: ["license"] })`, Tsx: true},
		{Code: `<form rel="next"></form>`, Tsx: true},
		{Code: `React.createElement("form", { rel: "next" })`, Tsx: true},
		{Code: `React.createElement("form", { rel: ["next"] })`, Tsx: true},
		{Code: `<form rel="nofollow"></form>`, Tsx: true},
		{Code: `React.createElement("form", { rel: "nofollow" })`, Tsx: true},
		{Code: `React.createElement("form", { rel: ["nofollow"] })`, Tsx: true},
		{Code: `<form rel="noopener"></form>`, Tsx: true},
		{Code: `React.createElement("form", { rel: "noopener" })`, Tsx: true},
		{Code: `React.createElement("form", { rel: ["noopener"] })`, Tsx: true},
		{Code: `<form rel="noreferrer"></form>`, Tsx: true},
		{Code: `React.createElement("form", { rel: "noreferrer" })`, Tsx: true},
		{Code: `React.createElement("form", { rel: ["noreferrer"] })`, Tsx: true},
		{Code: `<form rel="opener"></form>`, Tsx: true},
		{Code: `React.createElement("form", { rel: "opener" })`, Tsx: true},
		{Code: `React.createElement("form", { rel: ["opener"] })`, Tsx: true},
		{Code: `<form rel="prev"></form>`, Tsx: true},
		{Code: `React.createElement("form", { rel: "prev" })`, Tsx: true},
		{Code: `React.createElement("form", { rel: ["prev"] })`, Tsx: true},
		{Code: `<form rel="search"></form>`, Tsx: true},
		{Code: `React.createElement("form", { rel: "search" })`, Tsx: true},
		{Code: `React.createElement("form", { rel: ["search"] })`, Tsx: true},
		{Code: `<form rel={callFoo()}></form>`, Tsx: true},
		{Code: `React.createElement("form", { rel: callFoo() })`, Tsx: true},
		{Code: `React.createElement("form", { rel: [callFoo()] })`, Tsx: true},
		{Code: `<a rel={{a: "noreferrer"}["a"]}></a>`, Tsx: true},
		{Code: `<a rel={{a: "noreferrer"}["b"]}></a>`, Tsx: true},
		{Code: `<Foo rel></Foo>`, Tsx: true},
		{Code: `React.createElement("Foo", { rel: true })`, Tsx: true},
		{Code: `
        React.createElement('a', {
          ...rest,
          href: to,
        })
      `, Tsx: true},
		{Code: `<link rel="apple-touch-icon" sizes="60x60" href="apple-touch-icon-60x60.png" />`, Tsx: true},
		{Code: `<link rel="apple-touch-icon" sizes="76x76" href="apple-touch-icon-76x76.png" />`, Tsx: true},
		{Code: `<link rel="apple-touch-icon" sizes="120x120" href="apple-touch-icon-120x120.png" />`, Tsx: true},
		{Code: `<link rel="apple-touch-icon" sizes="152x152" href="apple-touch-icon-152x152.png" />`, Tsx: true},
		{Code: `<link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon-180x180.png" />`, Tsx: true},
		{Code: `<link rel="apple-touch-startup-image" href="launch.png" />`, Tsx: true},
		{Code: `<link rel="apple-touch-startup-image" href="iphone5.png" media="(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)" />`, Tsx: true},
		{Code: `<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#fff" />`, Tsx: true},
	}, []rule_tester.InvalidTestCase{
		{Code: `<a rel="alternatex"></a>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "neverValid", Data: map[string]string{"attributeName": "rel", "reportingValue": "alternatex"}, Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Data: map[string]string{"attributeName": "rel", "reportingValue": "alternatex"}, Output: `<a rel=""></a>`}}}}},
		{Code: `React.createElement("a", { rel: "alternatex" })`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "neverValid", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `React.createElement("a", { rel: "" })`}}}}},
		{Code: `React.createElement("a", { rel: ["alternatex"] })`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "neverValid", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `React.createElement("a", { rel: [""] })`}}}}},
		{Code: `<a rel="alternatex alternate"></a>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "neverValid", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<a rel=" alternate"></a>`}}}}},
		{Code: `React.createElement("a", { rel: "alternatex alternate" })`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "neverValid", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `React.createElement("a", { rel: "" })`}}}}},
		{Code: `React.createElement("a", { rel: ["alternatex alternate"] })`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "neverValid", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `React.createElement("a", { rel: [""] })`}}}}},
		{Code: `<a rel="alternate alternatex"></a>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "neverValid", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<a rel="alternate "></a>`}}}}},
		{Code: `React.createElement("a", { rel: "alternate alternatex" })`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "neverValid", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `React.createElement("a", { rel: "" })`}}}}},
		{Code: `React.createElement("a", { rel: ["alternate alternatex"] })`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "neverValid", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `React.createElement("a", { rel: [""] })`}}}}},
		{Code: `<html rel></html>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "onlyMeaningfulFor", Data: map[string]string{"attributeName": "rel", "tagNames": `"<link>", "<a>", "<area>", "<form>"`}, Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveDefault", Data: map[string]string{"attributeName": "rel", "tagNames": `"<link>", "<a>", "<area>", "<form>"`}, Output: `<html ></html>`}}}}},
		{Code: `React.createElement("html", { rel: 1 })`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "onlyMeaningfulFor"}}},
		{Code: `<a rel></a>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "emptyIsMeaningless", Data: map[string]string{"attributeName": "rel"}, Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveEmpty", Data: map[string]string{"attributeName": "rel"}, Output: `<a ></a>`}}}}},
		// SKIP: upstream incorrectly treats this non-string Literal as a rel
		// string and offers a malformed suggestion; rslint intentionally skips it.
		{Code: `React.createElement("a", { rel: 1 })`, Tsx: true, Skip: true},
		{Code: `React.createElement("a", { rel() { return 1; } })`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "noMethod"}}},
		{Code: `<span rel></span>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "onlyMeaningfulFor", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveDefault", Output: `<span ></span>`}}}}},
		{Code: `<a rel={null}></a>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "onlyStrings", Data: map[string]string{"attributeName": "rel"}, Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveNonString", Data: map[string]string{"attributeName": "rel"}, Output: `<a ></a>`}}}}},
		{Code: `<a rel={5}></a>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "onlyStrings", Data: map[string]string{"attributeName": "rel"}, Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveNonString", Data: map[string]string{"attributeName": "rel"}, Output: `<a ></a>`}}}}},
		{Code: `<a rel={true}></a>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "onlyStrings", Data: map[string]string{"attributeName": "rel", "reportingValue": "true"}, Line: 1, Column: 9, EndLine: 1, EndColumn: 13, Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveNonString", Data: map[string]string{"attributeName": "rel", "reportingValue": "true"}, Output: `<a ></a>`}}}}},
		{Code: `<a rel={{}}></a>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "onlyStrings", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveDefault", Output: `<a ></a>`}}}}},
		{Code: `<a rel={undefined}></a>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "onlyStrings", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveDefault", Output: `<a ></a>`}}}}},
		{Code: `<a rel="noreferrer noopener foobar"></a>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "neverValid", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<a rel="noreferrer noopener "></a>`}}}}},
		{Code: `<a rel="noreferrer noopener   "></a>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spaceDelimited", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveWhitespaces", Output: `<a rel="noreferrer noopener"></a>`}}}}},
		{Code: `<a rel="noreferrer        noopener"></a>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spaceDelimited", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveWhitespaces", Output: `<a rel="noreferrer noopener"></a>`}}}}},
		{Code: `<a rel="noreferrer  noopener"></a>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spaceDelimited", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveWhitespaces", Output: `<a rel="noreferrer noopener"></a>`}}}}},
		{Code: `<a rel={"noreferrer noopener foobar"}></a>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "neverValid", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<a rel={"noreferrer noopener "}></a>`}}}}},
		{Code: `React.createElement("a", { rel: ["noreferrer", "noopener", "foobar" ] })`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "neverValid", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `React.createElement("a", { rel: ["noreferrer", "noopener", "" ] })`}}}}},
		{Code: `<a rel={"foobar noreferrer noopener"}></a>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "neverValid", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<a rel={" noreferrer noopener"}></a>`}}}}},
		{Code: `<a rel={"foobar batgo       noopener"}></a>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "neverValid", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<a rel={" batgo       noopener"}></a>`}}}, {MessageId: "neverValid", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<a rel={"foobar        noopener"}></a>`}}}, {MessageId: "spaceDelimited", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveWhitespaces", Output: `<a rel={"foobar batgo noopener"}></a>`}}}}},
		{Code: `<a rel={"        noopener"}></a>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spaceDelimited", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveWhitespaces", Output: `<a rel={"noopener"}></a>`}}}}},
		{Code: `<a rel={"noopener        "}></a>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spaceDelimited", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveWhitespaces", Output: `<a rel={"noopener"}></a>`}}}}},
		{Code: `<a rel={" batgo noopener"}></a>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "neverValid", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<a rel={"  noopener"}></a>`}}}, {MessageId: "spaceDelimited", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveWhitespaces", Output: `<a rel={"batgo noopener"}></a>`}}}}},
		{Code: `<a rel={"batgo noopener"}></a>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "neverValid", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<a rel={" noopener"}></a>`}}}}},
		{Code: `<a rel={" noopener"}></a>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spaceDelimited", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveWhitespaces", Output: `<a rel={"noopener"}></a>`}}}}},
		{Code: `<a rel="canonical"></a>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "notValidFor", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<a rel=""></a>`}}}}},
		{Code: `<a rel="dns-prefetch"></a>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "notValidFor", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<a rel=""></a>`}}}}},
		{Code: `<a rel="icon"></a>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "notValidFor", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<a rel=""></a>`}}}}},
		{Code: `<link rel="shortcut"></link>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "notAlone"}}},
		{Code: `<link rel="shortcut foo"></link>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "neverValid", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<link rel="shortcut "></link>`}}}, {MessageId: "notPaired"}}},
		{Code: `<link rel="shortcut  icon"></link>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "spaceDelimited", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveWhitespaces", Output: `<link rel="shortcut icon"></link>`}}}}},
		{Code: `<link rel="shortcut  foo"></link>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "neverValid", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<link rel="shortcut  "></link>`}}}, {MessageId: "notAlone"}, {MessageId: "spaceDelimited", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveWhitespaces", Output: `<link rel="shortcut foo"></link>`}}}}},
		{Code: `<a rel="manifest"></a>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "notValidFor", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<a rel=""></a>`}}}}},
		{Code: `<a rel="modulepreload"></a>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "notValidFor", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<a rel=""></a>`}}}}},
		{Code: `<a rel="pingback"></a>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "notValidFor", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<a rel=""></a>`}}}}},
		{Code: `<a rel="preconnect"></a>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "notValidFor", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<a rel=""></a>`}}}}},
		{Code: `<a rel="prefetch"></a>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "notValidFor", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<a rel=""></a>`}}}}},
		{Code: `<a rel="preload"></a>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "notValidFor", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<a rel=""></a>`}}}}},
		{Code: `<a rel="prerender"></a>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "notValidFor", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<a rel=""></a>`}}}}},
		{Code: `<a rel="stylesheet"></a>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "notValidFor", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<a rel=""></a>`}}}}},
		{Code: `<area rel="canonical"></area>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "notValidFor", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<area rel=""></area>`}}}}},
		{Code: `<area rel="dns-prefetch"></area>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "notValidFor", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<area rel=""></area>`}}}}},
		{Code: `<area rel="icon"></area>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "notValidFor", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<area rel=""></area>`}}}}},
		{Code: `<area rel="manifest"></area>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "notValidFor", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<area rel=""></area>`}}}}},
		{Code: `<area rel="modulepreload"></area>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "notValidFor", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<area rel=""></area>`}}}}},
		{Code: `<area rel="pingback"></area>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "notValidFor", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<area rel=""></area>`}}}}},
		{Code: `<area rel="preconnect"></area>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "notValidFor", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<area rel=""></area>`}}}}},
		{Code: `<area rel="prefetch"></area>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "notValidFor", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<area rel=""></area>`}}}}},
		{Code: `<area rel="preload"></area>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "notValidFor", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<area rel=""></area>`}}}}},
		{Code: `<area rel="prerender"></area>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "notValidFor", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<area rel=""></area>`}}}}},
		{Code: `<area rel="stylesheet"></area>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "notValidFor", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<area rel=""></area>`}}}}},
		{Code: `<link rel="bookmark"></link>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "notValidFor", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<link rel=""></link>`}}}}},
		{Code: `<link rel="external"></link>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "notValidFor", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<link rel=""></link>`}}}}},
		{Code: `<link rel="nofollow"></link>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "notValidFor", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<link rel=""></link>`}}}}},
		{Code: `<link rel="noopener"></link>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "notValidFor", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<link rel=""></link>`}}}}},
		{Code: `<link rel="noreferrer"></link>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "notValidFor", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<link rel=""></link>`}}}}},
		{Code: `<link rel="opener"></link>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "notValidFor", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<link rel=""></link>`}}}}},
		{Code: `<link rel="tag"></link>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "notValidFor", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<link rel=""></link>`}}}}},
		{Code: `<form rel="alternate"></form>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "notValidFor", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<form rel=""></form>`}}}}},
		{Code: `<form rel="author"></form>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "notValidFor", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<form rel=""></form>`}}}}},
		{Code: `<form rel="bookmark"></form>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "notValidFor", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<form rel=""></form>`}}}}},
		{Code: `<form rel="canonical"></form>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "notValidFor", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<form rel=""></form>`}}}}},
		{Code: `<form rel="dns-prefetch"></form>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "notValidFor", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<form rel=""></form>`}}}}},
		{Code: `<form rel="icon"></form>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "notValidFor", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<form rel=""></form>`}}}}},
		{Code: `<form rel="manifest"></form>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "notValidFor", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<form rel=""></form>`}}}}},
		{Code: `<form rel="modulepreload"></form>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "notValidFor", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<form rel=""></form>`}}}}},
		{Code: `<form rel="pingback"></form>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "notValidFor", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<form rel=""></form>`}}}}},
		{Code: `<form rel="preconnect"></form>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "notValidFor", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<form rel=""></form>`}}}}},
		{Code: `<form rel="prefetch"></form>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "notValidFor", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<form rel=""></form>`}}}}},
		{Code: `<form rel="preload"></form>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "notValidFor", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<form rel=""></form>`}}}}},
		{Code: `<form rel="prerender"></form>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "notValidFor", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<form rel=""></form>`}}}}},
		{Code: `<form rel="stylesheet"></form>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "notValidFor", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<form rel=""></form>`}}}}},
		{Code: `<form rel="tag"></form>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "notValidFor", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveInvalid", Output: `<form rel=""></form>`}}}}},
		{Code: `<form rel=""></form>`, Tsx: true, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "noEmpty", Suggestions: []rule_tester.InvalidTestCaseSuggestion{{MessageId: "suggestRemoveEmpty", Output: `<form ></form>`}}}}},
	})
}
