// API metadata from eslint-plugin-n v18.3.0 lib/rules/no-deprecated-api.js.
package no_deprecated_api

var deprecatedAPIs = []deprecatedAPI{
	{path: "_linklist", kind: "read", since: "5.0.0"},
	{path: "_stream_wrap", kind: "read", since: "12.0.0"},
	{path: "async_hooks.currentId", kind: "read", since: "8.2.0", alternatives: []replacement{{"'async_hooks.executionAsyncId()'", "8.1.0"}}},
	{path: "async_hooks.triggerId", kind: "read", since: "8.2.0", replacement: "'async_hooks.triggerAsyncId()'"},
	{path: "buffer.Buffer", kind: "construct", since: "6.0.0", alternatives: []replacement{{"'buffer.Buffer.alloc()'", "5.10.0"}, {"'buffer.Buffer.from()'", "5.10.0"}}},
	{path: "buffer.Buffer", kind: "call", since: "6.0.0", alternatives: []replacement{{"'buffer.Buffer.alloc()'", "5.10.0"}, {"'buffer.Buffer.from()'", "5.10.0"}}},
	{path: "buffer.SlowBuffer", kind: "read", since: "6.0.0", alternatives: []replacement{{"'buffer.Buffer.allocUnsafeSlow()'", "5.12.0"}}},
	{path: "constants", kind: "read", since: "6.3.0", replacement: "'constants' property of each module"},
	{path: "crypto._toBuf", kind: "read", since: "11.0.0"},
	{path: "crypto.Credentials", kind: "read", since: "0.12.0", replacement: "'tls.SecureContext'"},
	{path: "crypto.DEFAULT_ENCODING", kind: "read", since: "10.0.0"},
	{path: "crypto.createCipher", kind: "read", since: "10.0.0", alternatives: []replacement{{"'crypto.createCipheriv()'", "0.1.94"}}},
	{path: "crypto.createCredentials", kind: "read", since: "0.12.0", alternatives: []replacement{{"'tls.createSecureContext()'", "0.11.13"}}},
	{path: "crypto.createDecipher", kind: "read", since: "10.0.0", alternatives: []replacement{{"'crypto.createDecipheriv()'", "0.1.94"}}},
	{path: "crypto.fips", kind: "read", since: "10.0.0", alternatives: []replacement{{"'crypto.getFips()' and 'crypto.setFips()'", "10.0.0"}}},
	{path: "crypto.prng", kind: "read", since: "11.0.0", alternatives: []replacement{{"'crypto.randomBytes()'", "0.5.8"}}},
	{path: "crypto.pseudoRandomBytes", kind: "read", since: "11.0.0", alternatives: []replacement{{"'crypto.randomBytes()'", "0.5.8"}}},
	{path: "crypto.rng", kind: "read", since: "11.0.0", alternatives: []replacement{{"'crypto.randomBytes()'", "0.5.8"}}},
	{path: "domain", kind: "read", since: "4.0.0"},
	{path: "events.EventEmitter.listenerCount", kind: "read", since: "4.0.0", alternatives: []replacement{{"'events.EventEmitter#listenerCount()'", "3.2.0"}}},
	{path: "events.listenerCount", kind: "read", since: "4.0.0", alternatives: []replacement{{"'events.EventEmitter#listenerCount()'", "3.2.0"}}},
	{path: "freelist", kind: "read", since: "4.0.0"},
	{path: "fs.SyncWriteStream", kind: "read", since: "4.0.0"},
	{path: "fs.exists", kind: "read", since: "4.0.0", alternatives: []replacement{{"'fs.stat()'", "0.0.2"}, {"'fs.access()'", "0.11.15"}}},
	{path: "fs.lchmod", kind: "read", since: "0.4.0"},
	{path: "fs.lchmodSync", kind: "read", since: "0.4.0"},
	{path: "http.createClient", kind: "read", since: "0.10.0", alternatives: []replacement{{"'http.request()'", "0.3.6"}}},
	{path: "module.Module.createRequireFromPath", kind: "read", since: "12.2.0", alternatives: []replacement{{"'module.createRequire()'", "12.2.0"}}},
	{path: "module.Module.requireRepl", kind: "read", since: "6.0.0", replacement: "'require(\"repl\")'"},
	{path: "module.Module._debug", kind: "read", since: "9.0.0"},
	{path: "module.createRequireFromPath", kind: "read", since: "12.2.0", alternatives: []replacement{{"'module.createRequire()'", "12.2.0"}}},
	{path: "module.requireRepl", kind: "read", since: "6.0.0", replacement: "'require(\"repl\")'"},
	{path: "module._debug", kind: "read", since: "9.0.0"},
	{path: "net._setSimultaneousAccepts", kind: "read", since: "12.0.0"},
	{path: "os.getNetworkInterfaces", kind: "read", since: "0.6.0", alternatives: []replacement{{"'os.networkInterfaces()'", "0.6.0"}}},
	{path: "os.tmpDir", kind: "read", since: "7.0.0", alternatives: []replacement{{"'os.tmpdir()'", "0.9.9"}}},
	{path: "path._makeLong", kind: "read", since: "9.0.0", alternatives: []replacement{{"'path.toNamespacedPath()'", "9.0.0"}}},
	{path: "process.EventEmitter", kind: "read", since: "0.6.0", replacement: "'require(\"events\")'"},
	{path: "process.assert", kind: "read", since: "10.0.0", replacement: "'require(\"assert\")'"},
	{path: "process.binding", kind: "read", since: "10.9.0"},
	{path: "process.env.NODE_REPL_HISTORY_FILE", kind: "read", since: "4.0.0", replacement: "'NODE_REPL_HISTORY'"},
	{path: "process.report.triggerReport", kind: "read", since: "11.12.0", replacement: "'process.report.writeReport()'"},
	{path: "punycode", kind: "read", since: "7.0.0", replacement: "'https://www.npmjs.com/package/punycode'"},
	{path: "readline.codePointAt", kind: "read", since: "4.0.0"},
	{path: "readline.getStringWidth", kind: "read", since: "6.0.0"},
	{path: "readline.isFullWidthCodePoint", kind: "read", since: "6.0.0"},
	{path: "readline.stripVTControlCharacters", kind: "read", since: "6.0.0"},
	{path: "repl.REPLServer", kind: "read", since: "22.9.0", replacement: "new repl.REPLServer()"},
	{path: "repl.Recoverable", kind: "read", since: "22.9.0", replacement: "new repl.Recoverable()"},
	{path: "repl.REPL_MODE_MAGIC", kind: "read", since: "8.0.0"},
	{path: "repl.builtinModules", kind: "read", since: "22.16.0", replacement: "module.builtinModules"},
	{path: "safe-buffer.Buffer", kind: "construct", since: "6.0.0", alternatives: []replacement{{"'buffer.Buffer.alloc()'", "5.10.0"}, {"'buffer.Buffer.from()'", "5.10.0"}}},
	{path: "safe-buffer.Buffer", kind: "call", since: "6.0.0", alternatives: []replacement{{"'buffer.Buffer.alloc()'", "5.10.0"}, {"'buffer.Buffer.from()'", "5.10.0"}}},
	{path: "safe-buffer.SlowBuffer", kind: "read", since: "6.0.0", alternatives: []replacement{{"'buffer.Buffer.allocUnsafeSlow()'", "5.12.0"}}},
	{path: "sys", kind: "read", since: "0.3.0", replacement: "'util' module"},
	{path: "timers.enroll", kind: "read", since: "10.0.0", alternatives: []replacement{{"'setTimeout()'", "0.0.1"}, {"'setInterval()'", "0.0.1"}}},
	{path: "timers.unenroll", kind: "read", since: "10.0.0", alternatives: []replacement{{"'clearTimeout()'", "0.0.1"}, {"'clearInterval()'", "0.0.1"}}},
	{path: "tls.CleartextStream", kind: "read", since: "0.10.0"},
	{path: "tls.CryptoStream", kind: "read", since: "0.12.0", alternatives: []replacement{{"'tls.TLSSocket'", "0.11.4"}}},
	{path: "tls.SecurePair", kind: "read", since: "6.0.0", alternatives: []replacement{{"'tls.TLSSocket'", "0.11.4"}}},
	{path: "tls.convertNPNProtocols", kind: "read", since: "10.0.0"},
	{path: "tls.createSecurePair", kind: "read", since: "6.0.0", alternatives: []replacement{{"'tls.TLSSocket'", "0.11.4"}}},
	{path: "tls.parseCertString", kind: "read", since: "8.6.0", alternatives: []replacement{{"'querystring.parse()'", "0.1.25"}}},
	{path: "tty.setRawMode", kind: "read", since: "0.10.0", replacement: "'tty.ReadStream#setRawMode()' (e.g. 'process.stdin.setRawMode()')"},
	{path: "url.parse", kind: "read", since: "11.0.0", alternatives: []replacement{{"'url.URL' constructor", "6.13.0"}}},
	{path: "url.resolve", kind: "read", since: "11.0.0", alternatives: []replacement{{"'url.URL' constructor", "6.13.0"}}},
	{path: "util.debug", kind: "read", since: "0.12.0", alternatives: []replacement{{"'console.error()'", "0.1.100"}}},
	{path: "util.error", kind: "read", since: "0.12.0", alternatives: []replacement{{"'console.error()'", "0.1.100"}}},
	{path: "util.isArray", kind: "read", since: "4.0.0", alternatives: []replacement{{"'Array.isArray()'", "0.1.100"}}},
	{path: "util.isBoolean", kind: "read", since: "4.0.0"},
	{path: "util.isBuffer", kind: "read", since: "4.0.0", alternatives: []replacement{{"'Buffer.isBuffer()'", "0.1.101"}}},
	{path: "util.isDate", kind: "read", since: "4.0.0"},
	{path: "util.isError", kind: "read", since: "4.0.0"},
	{path: "util.isFunction", kind: "read", since: "4.0.0"},
	{path: "util.isNull", kind: "read", since: "4.0.0"},
	{path: "util.isNullOrUndefined", kind: "read", since: "4.0.0"},
	{path: "util.isNumber", kind: "read", since: "4.0.0"},
	{path: "util.isObject", kind: "read", since: "4.0.0"},
	{path: "util.isPrimitive", kind: "read", since: "4.0.0"},
	{path: "util.isRegExp", kind: "read", since: "4.0.0"},
	{path: "util.isString", kind: "read", since: "4.0.0"},
	{path: "util.isSymbol", kind: "read", since: "4.0.0"},
	{path: "util.isUndefined", kind: "read", since: "4.0.0"},
	{path: "util.log", kind: "read", since: "6.0.0", replacement: "a third party module"},
	{path: "util.print", kind: "read", since: "0.12.0", alternatives: []replacement{{"'console.log()'", "0.1.100"}}},
	{path: "util.pump", kind: "read", since: "0.10.0", alternatives: []replacement{{"'stream.Readable#pipe()'", "0.9.4"}}},
	{path: "util.puts", kind: "read", since: "0.12.0", alternatives: []replacement{{"'console.log()'", "0.1.100"}}},
	{path: "util._extend", kind: "read", since: "6.0.0", alternatives: []replacement{{"'Object.assign()'", "4.0.0"}}},
	{path: "vm.runInDebugContext", kind: "read", since: "8.0.0"},
	{path: "zlib.BrotliCompress", kind: "call", since: "22.9.0", replacement: "new zlib.BrotliCompress()"},
	{path: "zlib.BrotliDecompress", kind: "call", since: "22.9.0", replacement: "new zlib.BrotliDecompress()"},
	{path: "zlib.Deflate", kind: "call", since: "22.9.0", replacement: "new zlib.Deflate()"},
	{path: "zlib.DeflateRaw", kind: "call", since: "22.9.0", replacement: "new zlib.DeflateRaw()"},
	{path: "zlib.Gunzip", kind: "call", since: "22.9.0", replacement: "new zlib.Gunzip()"},
	{path: "zlib.Gzip", kind: "call", since: "22.9.0", replacement: "new zlib.Gzip()"},
	{path: "zlib.Inflate", kind: "call", since: "22.9.0", replacement: "new zlib.Inflate()"},
	{path: "zlib.InflateRaw", kind: "call", since: "22.9.0", replacement: "new zlib.InflateRaw()"},
	{path: "zlib.Unzip", kind: "call", since: "22.9.0", replacement: "new zlib.Unzip()"},
	{path: "Buffer", kind: "construct", since: "6.0.0", global: true, alternatives: []replacement{{"'Buffer.alloc()'", "5.10.0"}, {"'Buffer.from()'", "5.10.0"}}},
	{path: "Buffer", kind: "call", since: "6.0.0", global: true, alternatives: []replacement{{"'Buffer.alloc()'", "5.10.0"}, {"'Buffer.from()'", "5.10.0"}}},
	{path: "COUNTER_NET_SERVER_CONNECTION", kind: "read", since: "11.0.0", global: true},
	{path: "COUNTER_NET_SERVER_CONNECTION_CLOSE", kind: "read", since: "11.0.0", global: true},
	{path: "COUNTER_HTTP_SERVER_REQUEST", kind: "read", since: "11.0.0", global: true},
	{path: "COUNTER_HTTP_SERVER_RESPONSE", kind: "read", since: "11.0.0", global: true},
	{path: "COUNTER_HTTP_CLIENT_REQUEST", kind: "read", since: "11.0.0", global: true},
	{path: "COUNTER_HTTP_CLIENT_RESPONSE", kind: "read", since: "11.0.0", global: true},
	{path: "GLOBAL", kind: "read", since: "6.0.0", global: true, alternatives: []replacement{{"'global'", "0.1.27"}}},
	{path: "Intl.v8BreakIterator", kind: "read", since: "7.0.0", global: true, removed: "9.0.0"},
	{path: "require.extensions", kind: "read", since: "0.12.0", global: true, replacement: "compiling them ahead of time"},
	{path: "root", kind: "read", since: "6.0.0", global: true, alternatives: []replacement{{"'global'", "0.1.27"}}},
	{path: "process.EventEmitter", kind: "read", since: "0.6.0", global: true, replacement: "'require(\"events\")'"},
	{path: "process.assert", kind: "read", since: "10.0.0", global: true, replacement: "'require(\"assert\")'"},
	{path: "process.binding", kind: "read", since: "10.9.0", global: true},
	{path: "process.env.NODE_REPL_HISTORY_FILE", kind: "read", since: "4.0.0", global: true, replacement: "'NODE_REPL_HISTORY'"},
	{path: "process.report.triggerReport", kind: "read", since: "11.12.0", global: true, replacement: "'process.report.writeReport()'"},
}
