package exports_style

import (
	"testing"

	"github.com/web-infra-dev/rslint/internal/plugins/typescript/rules/fixtures"
	"github.com/web-infra-dev/rslint/internal/rule"
	"github.com/web-infra-dev/rslint/internal/rule_tester"
)

// Every case and documentation example from eslint-plugin-n v18.3.0.
// https://github.com/eslint-community/eslint-plugin-n/blob/v18.3.0/tests/lib/rules/exports-style.js
// https://github.com/eslint-community/eslint-plugin-n/blob/v18.3.0/docs/rules/exports-style.md
// Diagnostics match upstream; unsafe fixes are intentionally omitted as documented.
func TestExportsStyleUpstream(t *testing.T) {
	rule_tester.RunRuleTester(fixtures.GetRootDir(), "tsconfig.json", t, &ExportsStyleRule, []rule_tester.ValidTestCase{ // upstream valid 1
		{Code: "module.exports = {foo: 1}", FileName: "input.cjs", TSConfig: "tsconfig.allowJs.json", LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"}, Globals: map[string]any{"exports": "writable", "module": "readonly"}},
		// upstream valid 2
		{Code: "module.exports = {foo: 1}", FileName: "input.cjs", TSConfig: "tsconfig.allowJs.json", LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"}, Globals: map[string]any{"exports": "writable", "module": "readonly"}, Options: []any{"module.exports"}},
		// upstream valid 3
		{Code: "exports.foo = 1", FileName: "input.cjs", TSConfig: "tsconfig.allowJs.json", LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"}, Globals: map[string]any{"exports": "writable", "module": "readonly"}, Options: []any{"exports"}},
		// upstream valid 4
		{Code: "exports = module.exports = {foo: 1}", FileName: "input.cjs", TSConfig: "tsconfig.allowJs.json", LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"}, Globals: map[string]any{"exports": "writable", "module": "readonly"}, Options: []any{"module.exports", map[string]any{"allowBatchAssign": true}}},
		// upstream valid 5
		{Code: "module.exports = exports = {foo: 1}", FileName: "input.cjs", TSConfig: "tsconfig.allowJs.json", LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"}, Globals: map[string]any{"exports": "writable", "module": "readonly"}, Options: []any{"module.exports", map[string]any{"allowBatchAssign": true}}},
		// upstream valid 6
		{Code: "exports = module.exports = {foo: 1}", FileName: "input.cjs", TSConfig: "tsconfig.allowJs.json", LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"}, Globals: map[string]any{"exports": "writable", "module": "readonly"}, Options: []any{"exports", map[string]any{"allowBatchAssign": true}}},
		// upstream valid 7
		{Code: "module.exports = exports = {foo: 1}", FileName: "input.cjs", TSConfig: "tsconfig.allowJs.json", LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"}, Globals: map[string]any{"exports": "writable", "module": "readonly"}, Options: []any{"exports", map[string]any{"allowBatchAssign": true}}},
		// upstream valid 8
		{Code: "exports = module.exports = {foo: 1}; exports.bar = 2", FileName: "input.cjs", TSConfig: "tsconfig.allowJs.json", LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"}, Globals: map[string]any{"exports": "writable", "module": "readonly"}, Options: []any{"exports", map[string]any{"allowBatchAssign": true}}},
		// upstream valid 9
		{Code: "module.exports = exports = {foo: 1}; exports.bar = 2", FileName: "input.cjs", TSConfig: "tsconfig.allowJs.json", LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"}, Globals: map[string]any{"exports": "writable", "module": "readonly"}, Options: []any{"exports", map[string]any{"allowBatchAssign": true}}},
		// upstream valid 10
		{Code: "module = {}; module.foo = 1", FileName: "input.cjs", TSConfig: "tsconfig.allowJs.json", LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"}, Globals: map[string]any{"exports": "writable", "module": "readonly"}, Options: []any{"exports"}},
		// upstream valid 11
		{Code: "exports.foo = 1", FileName: "input.cjs", TSConfig: "tsconfig.allowJs.json", LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"}, Globals: map[string]any{"exports": "off", "module": "readonly"}, Options: []any{"module.exports"}},
		// upstream valid 12
		{Code: "module.exports = {foo: 1}", FileName: "input.cjs", TSConfig: "tsconfig.allowJs.json", LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"}, Globals: map[string]any{"exports": "writable", "module": "off"}, Options: []any{"exports"}},
		// documentation 3
		{Code: "/*eslint node/exports-style: [\"error\", \"module.exports\"]*/\n\nmodule.exports = {\n    foo: 1,\n    bar: 2\n}\n\nmodule.exports.baz = 3", FileName: "input.cjs", TSConfig: "tsconfig.allowJs.json", LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"}, Globals: map[string]any{"exports": "writable", "module": "readonly"}, Options: []any{"module.exports"}},
		// documentation 5
		{Code: "/*eslint node/exports-style: [\"error\", \"exports\"]*/\n\nexports.foo = 1\nexports.bar = 2", FileName: "input.cjs", TSConfig: "tsconfig.allowJs.json", LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"}, Globals: map[string]any{"exports": "writable", "module": "readonly"}, Options: []any{"exports"}},
		// documentation 6
		{Code: "/*eslint node/exports-style: [\"error\", \"exports\", {\"allowBatchAssign\": true}]*/\n\n// Allow `module.exports` in the same assignment expression as `exports`.\nmodule.exports = exports = function foo() {\n    // do something.\n}\n\nexports.bar = 1", FileName: "input.cjs", TSConfig: "tsconfig.allowJs.json", LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"}, Globals: map[string]any{"exports": "writable", "module": "readonly"}, Options: []any{"exports", map[string]any{"allowBatchAssign": true}}}}, []rule_tester.InvalidTestCase{ // upstream invalid 1
		{Code: "exports = {foo: 1}", FileName: "input.cjs", TSConfig: "tsconfig.allowJs.json", LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"}, Globals: map[string]any{"exports": "writable", "module": "readonly"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedExports", Message: "Unexpected access to 'exports'. Use 'module.exports' instead.", Line: 1, Column: 1, EndLine: 1, EndColumn: 10}}},
		// upstream invalid 2
		{Code: "exports.foo = 1", FileName: "input.cjs", TSConfig: "tsconfig.allowJs.json", LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"}, Globals: map[string]any{"exports": "writable", "module": "readonly"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedExports", Message: "Unexpected access to 'exports'. Use 'module.exports' instead.", Line: 1, Column: 1, EndLine: 1, EndColumn: 9}}},
		// upstream invalid 3
		{Code: "module.exports = exports = {foo: 1}", FileName: "input.cjs", TSConfig: "tsconfig.allowJs.json", LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"}, Globals: map[string]any{"exports": "writable", "module": "readonly"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedExports", Message: "Unexpected access to 'exports'. Use 'module.exports' instead.", Line: 1, Column: 18, EndLine: 1, EndColumn: 27}}},
		// upstream invalid 4
		{Code: "exports = module.exports = {foo: 1}", FileName: "input.cjs", TSConfig: "tsconfig.allowJs.json", LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"}, Globals: map[string]any{"exports": "writable", "module": "readonly"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedExports", Message: "Unexpected access to 'exports'. Use 'module.exports' instead.", Line: 1, Column: 1, EndLine: 1, EndColumn: 10}}},
		// upstream invalid 5
		{Code: "exports = {foo: 1}", FileName: "input.cjs", TSConfig: "tsconfig.allowJs.json", LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"}, Globals: map[string]any{"exports": "writable", "module": "readonly"}, Options: []any{"module.exports"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedExports", Message: "Unexpected access to 'exports'. Use 'module.exports' instead.", Line: 1, Column: 1, EndLine: 1, EndColumn: 10}}},
		// upstream invalid 6
		{Code: "exports.foo = 1", FileName: "input.cjs", TSConfig: "tsconfig.allowJs.json", LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"}, Globals: map[string]any{"exports": "writable", "module": "readonly"}, Options: []any{"module.exports"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedExports", Message: "Unexpected access to 'exports'. Use 'module.exports' instead.", Line: 1, Column: 1, EndLine: 1, EndColumn: 9}}},
		// upstream invalid 7
		{Code: "module.exports = exports = {foo: 1}", FileName: "input.cjs", TSConfig: "tsconfig.allowJs.json", LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"}, Globals: map[string]any{"exports": "writable", "module": "readonly"}, Options: []any{"module.exports"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedExports", Message: "Unexpected access to 'exports'. Use 'module.exports' instead.", Line: 1, Column: 18, EndLine: 1, EndColumn: 27}}},
		// upstream invalid 8
		{Code: "exports = module.exports = {foo: 1}", FileName: "input.cjs", TSConfig: "tsconfig.allowJs.json", LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"}, Globals: map[string]any{"exports": "writable", "module": "readonly"}, Options: []any{"module.exports"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedExports", Message: "Unexpected access to 'exports'. Use 'module.exports' instead.", Line: 1, Column: 1, EndLine: 1, EndColumn: 10}}},
		// upstream invalid 9
		{Code: "exports = {foo: 1}", FileName: "input.cjs", TSConfig: "tsconfig.allowJs.json", LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"}, Globals: map[string]any{"exports": "writable", "module": "readonly"}, Options: []any{"exports"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedAssignment", Message: "Unexpected assignment to 'exports'. Don't modify 'exports' itself.", Line: 1, Column: 1, EndLine: 1, EndColumn: 10}}},
		// upstream invalid 10
		{Code: "module.exports = {foo: 1}", FileName: "input.cjs", TSConfig: "tsconfig.allowJs.json", LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"}, Globals: map[string]any{"exports": "writable", "module": "readonly"}, Options: []any{"exports"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedModuleExports", Message: "Unexpected access to 'module.exports'. Use 'exports' instead.", Line: 1, Column: 1, EndLine: 1, EndColumn: 17}}},
		// upstream invalid 11
		{Code: "module.exports.foo = 1", FileName: "input.cjs", TSConfig: "tsconfig.allowJs.json", LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"}, Globals: map[string]any{"exports": "writable", "module": "readonly"}, Options: []any{"exports"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedModuleExports", Message: "Unexpected access to 'module.exports'. Use 'exports' instead.", Line: 1, Column: 1, EndLine: 1, EndColumn: 16}}},
		// upstream invalid 12
		{Code: "module.exports = { a: 1 }", FileName: "input.cjs", TSConfig: "tsconfig.allowJs.json", LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"}, Globals: map[string]any{"exports": "writable", "module": "readonly"}, Options: []any{"exports"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedModuleExports", Message: "Unexpected access to 'module.exports'. Use 'exports' instead.", Line: 1, Column: 1, EndLine: 1, EndColumn: 17}}},
		// upstream invalid 13
		{Code: "module.exports = { a: 1, b: 2 }", FileName: "input.cjs", TSConfig: "tsconfig.allowJs.json", LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"}, Globals: map[string]any{"exports": "writable", "module": "readonly"}, Options: []any{"exports"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedModuleExports", Message: "Unexpected access to 'module.exports'. Use 'exports' instead.", Line: 1, Column: 1, EndLine: 1, EndColumn: 17}}},
		// upstream invalid 14
		{Code: "module.exports = { // before a\na: 1, // between a and b\nb: 2 // after b\n}", FileName: "input.cjs", TSConfig: "tsconfig.allowJs.json", LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"}, Globals: map[string]any{"exports": "writable", "module": "readonly"}, Options: []any{"exports"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedModuleExports", Message: "Unexpected access to 'module.exports'. Use 'exports' instead.", Line: 1, Column: 1, EndLine: 1, EndColumn: 17}}},
		// upstream invalid 15
		{Code: "foo(module.exports = {foo: 1})", FileName: "input.cjs", TSConfig: "tsconfig.allowJs.json", LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"}, Globals: map[string]any{"exports": "writable", "module": "readonly"}, Options: []any{"exports"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedModuleExports", Message: "Unexpected access to 'module.exports'. Use 'exports' instead.", Line: 1, Column: 5, EndLine: 1, EndColumn: 21}}},
		// upstream invalid 16
		{Code: "if(foo){ module.exports = { foo: 1};} else { module.exports = {foo: 2};}", FileName: "input.cjs", TSConfig: "tsconfig.allowJs.json", LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"}, Globals: map[string]any{"exports": "writable", "module": "readonly"}, Options: []any{"exports"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedModuleExports", Message: "Unexpected access to 'module.exports'. Use 'exports' instead.", Line: 1, Column: 10, EndLine: 1, EndColumn: 26}, {MessageId: "unexpectedModuleExports", Message: "Unexpected access to 'module.exports'. Use 'exports' instead.", Line: 1, Column: 46, EndLine: 1, EndColumn: 62}}},
		// upstream invalid 17
		{Code: "function bar() { module.exports = { foo: 1 }; }", FileName: "input.cjs", TSConfig: "tsconfig.allowJs.json", LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"}, Globals: map[string]any{"exports": "writable", "module": "readonly"}, Options: []any{"exports"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedModuleExports", Message: "Unexpected access to 'module.exports'. Use 'exports' instead.", Line: 1, Column: 18, EndLine: 1, EndColumn: 34}}},
		// upstream invalid 18
		{Code: "module.exports = { get a() {} }", FileName: "input.cjs", TSConfig: "tsconfig.allowJs.json", LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"}, Globals: map[string]any{"exports": "writable", "module": "readonly"}, Options: []any{"exports"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedModuleExports", Message: "Unexpected access to 'module.exports'. Use 'exports' instead.", Line: 1, Column: 1, EndLine: 1, EndColumn: 17}}},
		// upstream invalid 19
		{Code: "module.exports = { set a(a) {} }", FileName: "input.cjs", TSConfig: "tsconfig.allowJs.json", LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"}, Globals: map[string]any{"exports": "writable", "module": "readonly"}, Options: []any{"exports"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedModuleExports", Message: "Unexpected access to 'module.exports'. Use 'exports' instead.", Line: 1, Column: 1, EndLine: 1, EndColumn: 17}}},
		// upstream invalid 20
		{Code: "module.exports = { a }", FileName: "input.cjs", TSConfig: "tsconfig.allowJs.json", LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"}, Globals: map[string]any{"exports": "writable", "module": "readonly"}, Options: []any{"exports"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedModuleExports", Message: "Unexpected access to 'module.exports'. Use 'exports' instead.", Line: 1, Column: 1, EndLine: 1, EndColumn: 17}}},
		// upstream invalid 21
		{Code: "module.exports = { ...a }", FileName: "input.cjs", TSConfig: "tsconfig.allowJs.json", LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"}, Globals: map[string]any{"exports": "writable", "module": "readonly"}, Options: []any{"exports"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedModuleExports", Message: "Unexpected access to 'module.exports'. Use 'exports' instead.", Line: 1, Column: 1, EndLine: 1, EndColumn: 17}}},
		// upstream invalid 22
		{Code: "module.exports = { ['a' + 'b']: 1 }", FileName: "input.cjs", TSConfig: "tsconfig.allowJs.json", LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"}, Globals: map[string]any{"exports": "writable", "module": "readonly"}, Options: []any{"exports"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedModuleExports", Message: "Unexpected access to 'module.exports'. Use 'exports' instead.", Line: 1, Column: 1, EndLine: 1, EndColumn: 17}}},
		// upstream invalid 23
		{Code: "module.exports = { 'foo': 1 }", FileName: "input.cjs", TSConfig: "tsconfig.allowJs.json", LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"}, Globals: map[string]any{"exports": "writable", "module": "readonly"}, Options: []any{"exports"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedModuleExports", Message: "Unexpected access to 'module.exports'. Use 'exports' instead.", Line: 1, Column: 1, EndLine: 1, EndColumn: 17}}},
		// upstream invalid 24
		{Code: "module.exports = { foo(a) {} }", FileName: "input.cjs", TSConfig: "tsconfig.allowJs.json", LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"}, Globals: map[string]any{"exports": "writable", "module": "readonly"}, Options: []any{"exports"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedModuleExports", Message: "Unexpected access to 'module.exports'. Use 'exports' instead.", Line: 1, Column: 1, EndLine: 1, EndColumn: 17}}},
		// upstream invalid 25
		{Code: "module.exports = { *foo(a) {} }", FileName: "input.cjs", TSConfig: "tsconfig.allowJs.json", LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"}, Globals: map[string]any{"exports": "writable", "module": "readonly"}, Options: []any{"exports"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedModuleExports", Message: "Unexpected access to 'module.exports'. Use 'exports' instead.", Line: 1, Column: 1, EndLine: 1, EndColumn: 17}}},
		// upstream invalid 26
		{Code: "module.exports = { async foo(a) {} }", FileName: "input.cjs", TSConfig: "tsconfig.allowJs.json", LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"}, Globals: map[string]any{"exports": "writable", "module": "readonly"}, Options: []any{"exports"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedModuleExports", Message: "Unexpected access to 'module.exports'. Use 'exports' instead.", Line: 1, Column: 1, EndLine: 1, EndColumn: 17}}},
		// upstream invalid 27
		{Code: "module.exports.foo()", FileName: "input.cjs", TSConfig: "tsconfig.allowJs.json", LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"}, Globals: map[string]any{"exports": "writable", "module": "readonly"}, Options: []any{"exports"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedModuleExports", Message: "Unexpected access to 'module.exports'. Use 'exports' instead.", Line: 1, Column: 1, EndLine: 1, EndColumn: 16}}},
		// upstream invalid 28
		{Code: "a = module.exports.foo + module.exports['bar']", FileName: "input.cjs", TSConfig: "tsconfig.allowJs.json", LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"}, Globals: map[string]any{"exports": "writable", "module": "readonly"}, Options: []any{"exports"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedModuleExports", Message: "Unexpected access to 'module.exports'. Use 'exports' instead.", Line: 1, Column: 5, EndLine: 1, EndColumn: 20}, {MessageId: "unexpectedModuleExports", Message: "Unexpected access to 'module.exports'. Use 'exports' instead.", Line: 1, Column: 26, EndLine: 1, EndColumn: 41}}},
		// upstream invalid 29
		{Code: "module.exports = exports = {foo: 1}", FileName: "input.cjs", TSConfig: "tsconfig.allowJs.json", LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"}, Globals: map[string]any{"exports": "writable", "module": "readonly"}, Options: []any{"exports"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedModuleExports", Message: "Unexpected access to 'module.exports'. Use 'exports' instead.", Line: 1, Column: 1, EndLine: 1, EndColumn: 17}, {MessageId: "unexpectedAssignment", Message: "Unexpected assignment to 'exports'. Don't modify 'exports' itself.", Line: 1, Column: 18, EndLine: 1, EndColumn: 27}}},
		// upstream invalid 30
		{Code: "exports = module.exports = {foo: 1}", FileName: "input.cjs", TSConfig: "tsconfig.allowJs.json", LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"}, Globals: map[string]any{"exports": "writable", "module": "readonly"}, Options: []any{"exports"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedAssignment", Message: "Unexpected assignment to 'exports'. Don't modify 'exports' itself.", Line: 1, Column: 1, EndLine: 1, EndColumn: 10}, {MessageId: "unexpectedModuleExports", Message: "Unexpected access to 'module.exports'. Use 'exports' instead.", Line: 1, Column: 11, EndLine: 1, EndColumn: 27}}},
		// upstream invalid 31
		{Code: "module.exports = exports = {foo: 1}; exports = obj", FileName: "input.cjs", TSConfig: "tsconfig.allowJs.json", LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"}, Globals: map[string]any{"exports": "writable", "module": "readonly"}, Options: []any{"exports", map[string]any{"allowBatchAssign": true}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedAssignment", Message: "Unexpected assignment to 'exports'. Don't modify 'exports' itself.", Line: 1, Column: 38, EndLine: 1, EndColumn: 47}}},
		// upstream invalid 32
		{Code: "exports = module.exports = {foo: 1}; exports = obj", FileName: "input.cjs", TSConfig: "tsconfig.allowJs.json", LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"}, Globals: map[string]any{"exports": "writable", "module": "readonly"}, Options: []any{"exports", map[string]any{"allowBatchAssign": true}}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedAssignment", Message: "Unexpected assignment to 'exports'. Don't modify 'exports' itself.", Line: 1, Column: 38, EndLine: 1, EndColumn: 47}}},
		// documentation 1
		{Code: "module.exports = {\n    foo: 1\n}\n\nexports.bar = 2", FileName: "input.cjs", TSConfig: "tsconfig.allowJs.json", LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"}, Globals: map[string]any{"exports": "writable", "module": "readonly"}, Options: []any{}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedExports", Message: "Unexpected access to 'exports'. Use 'module.exports' instead.", Line: 5, Column: 1, EndLine: 5, EndColumn: 9}}},
		// documentation 2
		{Code: "/*eslint node/exports-style: [\"error\", \"module.exports\"]*/\n\nexports.foo = 1\nexports.bar = 2", FileName: "input.cjs", TSConfig: "tsconfig.allowJs.json", LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"}, Globals: map[string]any{"exports": "writable", "module": "readonly"}, Options: []any{"module.exports"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedExports", Message: "Unexpected access to 'exports'. Use 'module.exports' instead.", Line: 3, Column: 1, EndLine: 3, EndColumn: 9}, {MessageId: "unexpectedExports", Message: "Unexpected access to 'exports'. Use 'module.exports' instead.", Line: 4, Column: 1, EndLine: 4, EndColumn: 9}}},
		// documentation 4
		{Code: "/*eslint node/exports-style: [\"error\", \"exports\"]*/\n\nmodule.exports = {\n    foo: 1,\n    bar: 2\n}\n\nmodule.exports.baz = 3", FileName: "input.cjs", TSConfig: "tsconfig.allowJs.json", LanguageOptions: rule.LanguageOptions{SourceType: "commonjs"}, Globals: map[string]any{"exports": "writable", "module": "readonly"}, Options: []any{"exports"}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unexpectedModuleExports", Message: "Unexpected access to 'module.exports'. Use 'exports' instead.", Line: 3, Column: 1, EndLine: 3, EndColumn: 17}, {MessageId: "unexpectedModuleExports", Message: "Unexpected access to 'module.exports'. Use 'exports' instead.", Line: 8, Column: 1, EndLine: 8, EndColumn: 16}}}})
}
