name: Benchmark Go

on:
  workflow_call:

jobs:
  benchmark-go:
    name: Run Go benchmarks
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
    env:
      GOMAXPROCS: 8
    steps:
      - name: Checkout code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          submodules: true
          fetch-depth: 1

      - name: Setup Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: '1.26.0'
          cache: false

      - name: Run benchmarks
        uses: CodSpeedHQ/action@d872884a306dd4853acf0f584f4b706cf0cc72a2
        with:
          mode: walltime
          run: go test -bench=. -benchtime=5s ./tests/bench-go/
          go-runner-version: 1.1.0
