// Migrates every rule-tester case of eslint-plugin-jest v29.16.6
// src/rules/__tests__/unbound-method.test.ts. Upstream's error-handling suite
// covers loading @typescript-eslint/eslint-plugin at runtime; the base rule is
// built into rslint, so it has no counterpart here.
// Additional shapes and branch coverage live in unbound_method_extras_test.go.
package unbound_method

import (
	"embed"
	"testing"

	"github.com/web-infra-dev/rslint/internal/rule_tester"
	"github.com/web-infra-dev/rslint/internal/testutil/embedfs"
)

// testdata/fixtures reproduces the program upstream's cases run in: its
// fixture compiler options (no DOM lib), its class.ts, and the parts of
// @types/node and @types/jest it loads automatically. Type roots are
// processed after the linted file, as upstream's @types packages are, so a
// script-level `class Console` or `const console` in a case takes
// precedence over the ambient declarations of the same name.
//
//go:embed testdata/fixtures
var upstreamFixtures embed.FS

func upstreamRoot() embedfs.Root {
	root := embedfs.EmbedRoot(upstreamFixtures)
	root.Dir = "/testdata/fixtures"
	return root
}

// TestUnboundMethodUpstreamJestEdition is upstream's "unbound-method jest edition" suite.
func TestUnboundMethodUpstreamJestEdition(t *testing.T) {
	rule_tester.RunRuleTester(upstreamRoot(), "tsconfig.json", t, &UnboundMethodRule,
		[]rule_tester.ValidTestCase{
			{Code: "class Console {\n  log(str) {\n    process.stdout.write(str);\n  }\n}\n\nconst console = new Console();\nexpect(Console.prototype.log).toHaveBeenCalledTimes(1);"},
			{Code: "class Console {\n  log(str) {\n    process.stdout.write(str);\n  }\n}\n\nconst console = new Console();\nexpect(Console.prototype.log).not.toHaveBeenCalled();"},
			{Code: "class Console {\n  log(str) {\n    process.stdout.write(str);\n  }\n}\n\nconst console = new Console();\nexpect(Console.prototype.log).toStrictEqual(somethingElse);"},
			{Code: "class Console {\n  log(str) {\n    process.stdout.write(str);\n  }\n}\n\nconst console = new Console();\njest.mocked(Console.prototype.log).mockImplementation(() => {});"},
			{Code: "expect(() => {\n    class Console {\nlog(str) {\n  process.stdout.write(str);\n}\n}\n\nconst console = new Console();\n\n    expect(Console.prototype.log).toHaveBeenCalledTimes(1);\n  }).not.toThrow();"},
			{Code: "expect(() => Promise.resolve().then(console.log)).not.toThrow();"},
			{Code: "expect(console.log).not.toThrow();"},
			{Code: "expect(console.log).not.toThrowError();"},
			{Code: "expect(console.log).not.toThrowErrorMatchingSnapshot();"},
			{Code: "expect(console.log).not.toThrowErrorMatchingInlineSnapshot();"},
			{Code: "expect(console.log).toThrow();"},
			{Code: "expect(console.log).toThrowError();"},
			{Code: "expect(console.log).toThrowErrorMatchingSnapshot();"},
			{Code: "expect(console.log).toThrowErrorMatchingInlineSnapshot();"},
			{Code: "class Service {\n  method() {}\n}\n\nconst service = new Service();\nconst parameter = jest.mocked(service.method).mock.calls[0][0];"},
			{Code: "class Service {\n  method() {}\n}\n\nconst service = new Service();\nconst calls = jest.mocked(service.method).mock.calls;"},
			{Code: "class Service {\n  method() {}\n}\n\nconst service = new Service();\nconst lastCall = jest.mocked(service.method).mock.calls[0];"},
			{Code: "class Service {\n  method() {}\n}\n\nconst service = new Service();\nconst mockedMethod = jest.mocked(service.method); const parameter = mockedMethod.mock.calls[0][0];"},
			{Code: "class Service {\n  method() {}\n}\n\nconst service = new Service();\njest.mocked(service.method).mock;"},
			{Code: "class Service {\n  method() {}\n}\n\nconst service = new Service();\nconst mockProp = jest.mocked(service.method).mock;"},
			{Code: "class Service {\n  method() {}\n}\n\nconst service = new Service();\nconst result = jest.mocked(service.method, true);"},
			{Code: "class Service {\n  method() {}\n}\n\nconst service = new Service();\njest.mocked(service.method, { shallow: true });"},
		},
		[]rule_tester.InvalidTestCase{
			{Code: "class Console {\nlog(str) {\n  process.stdout.write(str);\n}\n}\n\nconst console = new Console();\n\n    expect(Console.prototype.log)", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 9}}},
			{Code: "expect(Console.prototype.log).toHaveBeenCalledTimes", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 1}}},
			{Code: "expect(() => {\n      class Console {\nlog(str) {\n  process.stdout.write(str);\n}\n}\n\nconst console = new Console();\n\n      Promise.resolve().then(console.log);\n    }).not.toThrow();", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 10}}},
			{Code: "class Console {\nlog(str) {\n  process.stdout.write(str);\n}\n}\n\nconst console = new Console();\n\n    expect(console.log).toThrow();", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 9}}},
			{Code: "class Console {\nlog(str) {\n  process.stdout.write(str);\n}\n}\n\nconst console = new Console();\n\n    expect(console.log).toThrowError();", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 9}}},
			{Code: "class Console {\nlog(str) {\n  process.stdout.write(str);\n}\n}\n\nconst console = new Console();\n\n    expect(console.log).toThrowErrorMatchingSnapshot();", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 9}}},
			{Code: "class Console {\nlog(str) {\n  process.stdout.write(str);\n}\n}\n\nconst console = new Console();\n\n    expect(console.log).toThrowErrorMatchingInlineSnapshot();", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 9}}},
			{Code: "class Service {\nmethod() {}\n}\n\nconst service = new Service();\n\n    const method = service.method;\n    jest.mocked(method);", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 7}}},
			{Code: "class Service {\nmethod() {}\n}\n\nconst service = new Service();\n\n    const method = service.method;", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 7}}},
			{Code: "class Service {\nmethod() {}\n}\n\nconst service = new Service();\n\n    Promise.resolve().then(service.method);", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 7}}},
			{Code: "class Console {\nlog(str) {\n  process.stdout.write(str);\n}\n}\n\nconst console = new Console();\n\n    expect(console.log).not.toThrow();", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 9}}},
			{Code: "class Console {\nlog(str) {\n  process.stdout.write(str);\n}\n}\n\nconst console = new Console();\n\n    expect(console.log).not.toThrowError();", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 9}}},
			{Code: "class Console {\nlog(str) {\n  process.stdout.write(str);\n}\n}\n\nconst console = new Console();\n\n    expect(console.log).not.toThrowErrorMatchingSnapshot();", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 9}}},
			{Code: "class Console {\nlog(str) {\n  process.stdout.write(str);\n}\n}\n\nconst console = new Console();\n\n    expect(console.log).not.toThrowErrorMatchingInlineSnapshot();", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 9}}},
		})
}

// TestUnboundMethodUpstreamBaseRule is upstream's "unbound-method" suite,
// which runs the base rule's cases through the Jest rule.
func TestUnboundMethodUpstreamBaseRule(t *testing.T) {
	rule_tester.RunRuleTester(upstreamRoot(), "tsconfig.json", t, &UnboundMethodRule,
		[]rule_tester.ValidTestCase{
			{Code: "Promise.resolve().then(console.log);"},
			{Code: "['1', '2', '3'].map(Number.parseInt);"},
			{Code: "[5.2, 7.1, 3.6].map(Math.floor);"},
			{Code: "\n      const foo = Number;\n      ['1', '2', '3'].map(foo.parseInt);\n    "},
			{Code: "\n      const foo = Math;\n      [5.2, 7.1, 3.6].map(foo.floor);\n    "},
			{Code: "['1', '2', '3'].map(Number['floor']);"},
			{Code: "const x = console.log;"},
			{Code: "const x = Object.defineProperty;"},
			{Code: "\n      const foo = Object;\n      const x = foo.defineProperty;\n    "},
			{Code: "const x = String.fromCharCode;"},
			{Code: "\n      const foo = String;\n      const x = foo.fromCharCode;\n    "},
			{Code: "const x = RegExp.prototype;"},
			{Code: "const x = Symbol.keyFor;"},
			{Code: "\n      const foo = Symbol;\n      const x = foo.keyFor;\n    "},
			{Code: "const x = Array.isArray;"},
			{Code: "\n      const foo = Array;\n      const x = foo.isArray;\n    "},
			{Code: "\n      class Foo extends Array {}\n      const x = Foo.isArray;\n    "},
			{Code: "const x = Proxy.revocable;"},
			{Code: "\n      const foo = Proxy;\n      const x = foo.revocable;\n    "},
			{Code: "const x = Date.parse;"},
			{Code: "\n      const foo = Date;\n      const x = foo.parse;\n    "},
			{Code: "const x = Atomics.load;"},
			{Code: "\n      const foo = Atomics;\n      const x = foo.load;\n    "},
			{Code: "const x = Reflect.deleteProperty;"},
			{Code: "const x = JSON.stringify;"},
			{Code: "\n      const foo = JSON;\n      const x = foo.stringify;\n    "},
			{Code: "\n      const o = {\n        f: function (this: void) {},\n      };\n      const f = o.f;\n    "},
			{Code: "\n      const { alert } = window;\n    "},
			{Code: "\n      let b = window.blur;\n    "},
			{Code: "\n      function foo() {}\n      const fooObject = { foo };\n      const { foo: bar } = fooObject;\n    "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\ninstance.bound();\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\ninstance.unbound();\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\nContainsMethods.boundStatic();\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\nContainsMethods.unboundStatic();\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\nconst bound = instance.bound;\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\nconst boundStatic = ContainsMethods;\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\nconst { bound } = instance;\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\nconst { boundStatic } = ContainsMethods;\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\n(instance.bound)();\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\n(instance.unbound)();\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\n(ContainsMethods.boundStatic)();\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\n(ContainsMethods.unboundStatic)();\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\ninstance.bound``;\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\ninstance.unbound``;\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\nif (instance.bound) { }\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\nif (instance.unbound) { }\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\nif (instance.bound !== undefined) { }\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\nif (instance.unbound !== undefined) { }\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\nif (ContainsMethods.boundStatic) { }\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\nif (ContainsMethods.unboundStatic) { }\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\nif (ContainsMethods.boundStatic !== undefined) { }\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\nif (ContainsMethods.unboundStatic !== undefined) { }\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\nif (ContainsMethods.boundStatic && instance) { }\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\nif (ContainsMethods.unboundStatic && instance) { }\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\nif (instance.bound || instance) { }\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\nif (instance.unbound || instance) { }\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\nContainsMethods.unboundStatic && 0 || ContainsMethods;\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\n(instance.bound || instance) ? 1 : 0\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\n(instance.unbound || instance) ? 1 : 0\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\nwhile (instance.bound) { }\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\nwhile (instance.unbound) { }\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\nwhile (instance.bound !== undefined) { }\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\nwhile (instance.unbound !== undefined) { }\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\nwhile (ContainsMethods.boundStatic) { }\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\nwhile (ContainsMethods.unboundStatic) { }\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\nwhile (ContainsMethods.boundStatic !== undefined) { }\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\nwhile (ContainsMethods.unboundStatic !== undefined) { }\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\ninstance.bound as any;\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\nContainsMethods.boundStatic as any;\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\ninstance.bound++;\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\n+instance.bound;\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\n++instance.bound;\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\ninstance.bound--;\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\n-instance.bound;\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\n--instance.bound;\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\ninstance.bound += 1;\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\ninstance.bound -= 1;\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\ninstance.bound *= 1;\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\ninstance.bound /= 1;\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\ninstance.bound || 0;\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\ninstance.bound && 0;\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\ninstance.bound ? 1 : 0;\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\ninstance.unbound ? 1 : 0;\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\nContainsMethods.boundStatic++;\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\n+ContainsMethods.boundStatic;\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\n++ContainsMethods.boundStatic;\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\nContainsMethods.boundStatic--;\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\n-ContainsMethods.boundStatic;\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\n--ContainsMethods.boundStatic;\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\nContainsMethods.boundStatic += 1;\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\nContainsMethods.boundStatic -= 1;\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\nContainsMethods.boundStatic *= 1;\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\nContainsMethods.boundStatic /= 1;\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\nContainsMethods.boundStatic || 0;\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\ninstane.boundStatic && 0;\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\nContainsMethods.boundStatic ? 1 : 0;\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\nContainsMethods.unboundStatic ? 1 : 0;\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\ntypeof instance.bound === 'function';\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\ntypeof instance.unbound === 'function';\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\ntypeof ContainsMethods.boundStatic === 'function';\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\ntypeof ContainsMethods.unboundStatic === 'function';\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\ninstance.unbound = () => {};\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\ninstance.unbound = instance.unbound.bind(instance);\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\nif (!!instance.unbound) {}\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\nvoid instance.unbound\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\ndelete instance.unbound\n  "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\nconst { double } = arith;\n  "},
			{Code: "\ninterface RecordA {\n  readonly type: 'A';\n  readonly a: {};\n}\ninterface RecordB {\n  readonly type: 'B';\n  readonly b: {};\n}\ntype AnyRecord = RecordA | RecordB;\n\nfunction test(obj: AnyRecord) {\n  switch (obj.type) {\n  }\n}\n    "},
			{Code: "\nclass CommunicationError {\n  constructor() {\n    const x = CommunicationError.prototype;\n  }\n}\n    "},
			{Code: "\nclass CommunicationError {}\nconst x = CommunicationError.prototype;\n    "},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nfunction foo(instance: ContainsMethods | null) {\n  instance?.bound();\n  instance?.unbound();\n\n  if (instance?.bound) {\n  }\n  if (instance?.unbound) {\n  }\n\n  typeof instance?.bound === 'function';\n  typeof instance?.unbound === 'function';\n}\n    "},
			{Code: "\ninterface OptionalMethod {\n  mightBeDefined?(): void;\n}\n\nconst x: OptionalMethod = {};\ndeclare const myCondition: boolean;\nif (myCondition || x.mightBeDefined) {\n  console.log('hello world');\n}\n    "},
			{Code: "\nclass A {\n  unbound(): void {\n    this.unbound = undefined;\n    this.unbound = this.unbound.bind(this);\n  }\n}\n    "},
			{Code: "const { parseInt } = Number;"},
			{Code: "const { log } = console;"},
			{Code: "\nlet parseInt;\n({ parseInt } = Number);\n    "},
			{Code: "\nlet log;\n({ log } = console);\n    "},
			{Code: "\nconst foo = {\n  bar: 'bar',\n};\nconst { bar } = foo;\n    "},
			{Code: "\nclass Foo {\n  unbnound() {}\n  bar = 4;\n}\nconst { bar } = new Foo();\n    "},
			{Code: "\nclass Foo {\n  bound = () => 'foo';\n}\nconst { bound } = new Foo();\n    "},
			{Code: "\nclass Foo {\n  bound = () => 'foo';\n}\nfunction foo({ bound } = new Foo()) {}\n    "},
			{Code: "\nclass Foo {\n  bound = () => 'foo';\n}\ndeclare const bar: Foo;\nfunction foo({ bound }: Foo) {}\n    "},
			{Code: "\nclass Foo {\n  bound = () => 'foo';\n}\nclass Bar {\n  bound = () => 'bar';\n}\nfunction foo({ bound }: Foo | Bar) {}\n    "},
			{Code: "\nclass Foo {\n  bound = () => 'foo';\n}\ntype foo = ({ bound }: Foo) => void;\n    "},
			{Code: "\nclass Foo {\n  unbound = function () {};\n}\ntype foo = ({ unbound }: Foo) => void;\n    "},
			{Code: "\nclass Foo {\n  bound = () => 'foo';\n}\nclass Bar {\n  bound = () => 'bar';\n}\nfunction foo({ bound }: Foo & Bar) {}\n    "},
			{Code: "\nclass Foo {\n  unbound = function () {};\n}\ndeclare const { unbound }: Foo;\n    "},
			{Code: "declare const { unbound } = '***';"},
			{Code: "\nclass Foo {\n  unbound = function () {};\n}\ntype foo = (a: (b: (c: ({ unbound }: Foo) => void) => void) => void) => void;\n    "},
			{Code: "\nclass Foo {\n  unbound = function () {};\n}\nclass Bar {\n  property: ({ unbound }: Foo) => void;\n}\n    "},
			{Code: "\nclass Foo {\n  unbound = function () {};\n}\nfunction foo<T extends ({ unbound }: Foo) => void>() {}\n    "},
			{Code: "\nclass Foo {\n  unbound = function () {};\n}\nabstract class Bar {\n  abstract foo({ unbound }: Foo);\n}\n    "},
			{Code: "\nclass Foo {\n  unbound = function () {};\n}\ndeclare class Bar {\n  foo({ unbound }: Foo);\n}\n    "},
			{Code: "\nclass Foo {\n  unbound = function () {};\n}\ndeclare function foo({ unbound }: Foo);\n    "},
			{Code: "\nclass Foo {\n  unbound = function () {};\n}\ninterface Bar {\n  foo: ({ unbound }: Foo) => void;\n}\n    "},
			{Code: "\nclass Foo {\n  unbound = function () {};\n}\ninterface Bar {\n  foo({ unbound }: Foo): void;\n}\n    "},
			{Code: "\nclass Foo {\n  unbound = function () {};\n}\ninterface Bar {\n  new ({ unbound }: Foo): Foo;\n}\n    "},
			{Code: "\nclass Foo {\n  unbound = function () {};\n}\ntype foo = new ({ unbound }: Foo) => void;\n    "},
			{Code: "const { unbound } = { unbound: () => {} };"},
			{Code: "function foo({ unbound }: { unbound: () => void } = { unbound: () => {} }) {}"},
			{Code: "\nclass BaseClass {\n  x: number = 42;\n  logThis() {}\n}\nclass OtherClass extends BaseClass {\n  superLogThis: any;\n  constructor() {\n    super();\n    this.superLogThis = super.logThis;\n  }\n}\nconst oc = new OtherClass();\noc.superLogThis();\n    "},
		},
		[]rule_tester.InvalidTestCase{
			{Code: "\nclass Console {\n  log(str) {\n    process.stdout.write(str);\n  }\n}\n\nconst console = new Console();\n\nPromise.resolve().then(console.log);\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 10}}},
			{Code: "\nimport { console } from './class';\nconst x = console.log;\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 3}}},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\n\nfunction foo(arg: ContainsMethods | null) {\n  const unbound = arg?.unbound;\n  arg.unbound += 1;\n  arg?.unbound as any;\n}\n      \n  ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 20}, {MessageId: "unboundWithoutThisAnnotation", Line: 21}, {MessageId: "unboundWithoutThisAnnotation", Line: 22}}},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\nconst unbound = instance.unbound;\n  ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 18}}},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\nconst unboundStatic = ContainsMethods.unboundStatic;\n  ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 18}}},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\nconst { unbound } = instance;\n  ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 18}}},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\nconst { unboundStatic } = ContainsMethods;\n  ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 18}}},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\n<any>instance.unbound;\n  ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 18}}},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\ninstance.unbound as any;\n  ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 18}}},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\n<any>ContainsMethods.unboundStatic;\n  ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 18}}},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\nContainsMethods.unboundStatic as any;\n  ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 18}}},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\ninstance.unbound || 0;\n  ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 18}}},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\nContainsMethods.unboundStatic || 0;\n  ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 18}}},
			{Code: "\nclass ContainsMethods {\n  bound?: () => void;\n  unbound?(): void;\n\n  static boundStatic?: () => void;\n  static unboundStatic?(): void;\n}\n\nlet instance = new ContainsMethods();\n\nconst arith = {\n  double(this: void, x: number): number {\n    return x * 2;\n  }\n};\n\ninstance.unbound ? instance.unbound : null\n  ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 18}}},
			{Code: "\nclass ContainsMethods {\n  unbound?(): void;\n\n  static unboundStatic?(): void;\n}\n\nnew ContainsMethods().unbound;\n\nContainsMethods.unboundStatic;\n      ", Options: map[string]any{"ignoreStatic": true}, Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 8}}},
			{Code: "\nclass CommunicationError {\n  foo() {}\n}\nconst x = CommunicationError.prototype.foo;\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 5}}},
			{Code: "const x = Promise.all;", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 1}}},
			{Code: "\nclass Foo {\n  unbound() {}\n}\nconst instance = new Foo();\n\nlet x;\n\nx = instance.unbound; // THIS SHOULD ERROR\ninstance.unbound = x; // THIS SHOULD NOT\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 9}}},
			{Code: "\nclass Foo extends Number {\n  static parseInt = function (string: string, radix?: number): number {};\n}\nconst foo = Foo;\n['1', '2', '3'].map(foo.parseInt);\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unbound", Line: 6}}},
			{Code: "\ndeclare const foo: Number;\nconst x = foo.toFixed;\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 3}}},
			{Code: "\ndeclare const foo: Object;\nconst x = foo.hasOwnProperty;\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 3}}},
			{Code: "\ndeclare const foo: String;\nconst x = foo.slice;\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 3}}},
			{Code: "\ndeclare const foo: Date;\nconst x = foo.getTime;\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 3}}},
			{Code: "\nclass Foo extends Number {}\nconst x = Foo.parseInt;\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 3}}},
			{Code: "\nclass Foo extends String {}\nconst x = Foo.fromCharCode;\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 3}}},
			{Code: "\nclass Foo extends Object {}\nconst x = Foo.defineProperty;\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 3}}},
			{Code: "\nclass Foo extends Date {}\nconst x = Foo.parse;\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 3}}},
			{Code: "\nclass Foo {\n  unbound = function () {};\n}\nconst unbound = new Foo().unbound;\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unbound", Line: 5}}},
			{Code: "\nclass Foo {\n  unbound() {}\n}\nconst { unbound } = new Foo();\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 5}}},
			{Code: "\nclass Foo {\n  unbound = function () {};\n}\nconst { unbound } = new Foo();\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unbound", Line: 5}}},
			{Code: "\nclass Foo {\n  unbound() {}\n}\nlet unbound;\n({ unbound } = new Foo());\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 6}}},
			{Code: "\nclass Foo {\n  unbound = function () {};\n}\nlet unbound;\n({ unbound } = new Foo());\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unbound", Line: 6}}},
			{Code: "\nclass Foo {\n  unbound = function () {};\n}\nfunction foo({ unbound }: Foo = new Foo()) {}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unbound", Line: 5}}},
			{Code: "\nclass Foo {\n  unbound = function () {};\n}\ndeclare const bar: Foo;\nfunction foo({ unbound }: Foo = bar) {}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unbound", Line: 6}}},
			{Code: "\nclass Foo {\n  unbound = function () {};\n}\ndeclare const bar: Foo;\nfunction foo({ unbound }: Foo = { unbound: () => {} }) {}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unbound", Line: 6}}},
			{Code: "\nclass Foo {\n  unbound = function () {};\n}\ndeclare const bar: Foo;\nfunction foo({ unbound }: Foo = { unbound: function () {} }) {}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 6}}},
			{Code: "\nclass Foo {\n  unbound = function () {};\n}\nfunction foo({ unbound }: Foo) {}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unbound", Line: 5}}},
			{Code: "\nclass Foo {\n  unbound = function () {};\n}\nfunction bar(cb: (arg: Foo) => void) {}\nbar(({ unbound }) => {});\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unbound", Line: 6}}},
			{Code: "\nclass Foo {\n  unbound = function () {};\n}\nfunction bar(cb: (arg: { unbound: () => void }) => void) {}\nbar(({ unbound } = new Foo()) => {});\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unbound", Line: 6}}},
			{Code: "\nclass Foo {\n  unbound = function () {};\n}\nfor (const { unbound } of [new Foo(), new Foo()]) {\n}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unbound", Line: 5}}},
			{Code: "\nclass Foo {\n  unbound = function () {};\n\n  foo({ unbound }: Foo) {}\n}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unbound", Line: 5}}},
			{Code: "\nclass Foo {\n  unbound = function () {};\n}\nclass Bar {\n  unbound = function () {};\n}\nfunction foo({ unbound }: Foo | Bar) {}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unbound", Line: 8}}},
			{Code: "\nclass Foo {\n  unbound = function () {};\n}\nfunction foo({ unbound }: { unbound: () => string } | Foo) {}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unbound", Line: 5}}},
			{Code: "\nclass Foo {\n  unbound = function () {};\n}\nclass Bar {\n  unbound = () => {};\n}\nfunction foo({ unbound }: Foo | Bar) {}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unbound", Line: 8}}},
			{Code: "\nclass Foo {\n  unbound = function () {};\n}\nconst foo = ({ unbound }: Foo & { foo: () => 'bar' }) => {};\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unbound", Line: 5}}},
			{Code: "\nclass Foo {\n  unbound = function () {};\n}\nclass Bar {\n  unbound = () => {};\n}\nconst foo = ({ unbound }: (Foo & { foo: () => 'bar' }) | Bar) => {};\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unbound", Line: 8}}},
			{Code: "\nclass Foo {\n  unbound = function () {};\n}\nclass Bar {\n  unbound = () => {};\n}\nconst foo = ({ unbound }: Foo & Bar) => {};\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unbound", Line: 8}}},
			{Code: "\nclass Foo {\n  unbound = function () {};\n\n  other = function () {};\n}\nclass Bar {\n  unbound = () => {};\n}\nconst foo = ({ unbound, ...rest }: Foo & Bar) => {};\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unbound", Line: 10}}},
			{Code: "const { unbound } = { unbound: function () {} };", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 1}}},
			{Code: "\nfunction foo(\n  { unbound }: { unbound: () => void } = { unbound: function () {} },\n) {}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 3}}},
			// Upstream expects unboundWithoutThisAnnotation. The Jest rule inherits
			// the message from rslint's @typescript-eslint/unbound-method, which
			// reports unbound for this case (see its own copy of the case).
			{Code: "\nclass Foo {\n  floor = function () {};\n}\n\nconst { floor } = Math.random() > 0.5 ? new Foo() : Math;\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unbound", Line: 6}}},
			{Code: "\nclass CommunicationError {\n  foo() {}\n}\nconst { foo } = CommunicationError.prototype;\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 5}}},
			{Code: "\nclass CommunicationError {\n  foo() {}\n}\nlet foo;\n({ foo } = CommunicationError.prototype);\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 6}}},
			{Code: "\nimport { console } from './class';\nconst { log } = console;\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 3}}},
			{Code: "const { all } = Promise;", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 1}}},
			{Code: "\nclass BaseClass {\n  logThis() {}\n}\nclass OtherClass extends BaseClass {\n  constructor() {\n    super();\n    const x = super.logThis;\n  }\n}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 8, Column: 15}}},
			{Code: "\nclass BaseClass {\n  logThis() {}\n}\nclass OtherClass extends BaseClass {\n  constructor() {\n    super();\n    let x;\n    x = super.logThis;\n  }\n}\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 9, Column: 9}}},
			{Code: "\nconst values = {\n  a() {},\n  b: () => {},\n};\n\nconst { a, b } = values;\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 7, Column: 9, EndColumn: 10}}},
			{Code: "\nconst values = {\n  a() {},\n  b: () => {},\n};\n\nconst { a: c } = values;\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 7, Column: 9, EndColumn: 10}}},
			{Code: "\nconst values = {\n  a() {},\n  b: () => {},\n};\n\nconst { b, a } = values;\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 7, Column: 12, EndColumn: 13}}},
			{Code: "\nconst objectLiteral = {\n  f: function () {},\n};\nconst f = objectLiteral.f;\n      ", Errors: []rule_tester.InvalidTestCaseError{{MessageId: "unboundWithoutThisAnnotation", Line: 5}}},
		})
}
